### ISSUE TITLE
spacy project clone assumes `master` not `main`. 

### ISSUE THREAD

**Issue by koaning** [explosion/spaCy#10458]
I've started making a custom spaCy project, over [here](https://github.com/koaning/classycookie). 

While I was toying around with it, I noticed that it wouldn't clone if I ran this command; 

```
> python -m spacy project clone --repo https://github.com/koaning/classycookie classification
```

It seems that spaCy assumes that the default branch is `master`, despite new branches on any new repos being `main`. 

Here's the traceback. 

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/spacy/cli/_util.py", line 71, in setup_cli
    command(prog_name=COMMAND)
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/spacy/cli/project/clone.py", line 39, in project_clone_cli
    project_clone(name, dest, repo=repo, branch=branch, sparse_checkout=sparse_checkout)
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/spacy/cli/project/clone.py", line 62, in project_clone
    git_checkout(repo, name, dest, branch=branch, sparse=sparse_checkout)
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/spacy/cli/_util.py", line 400, in git_checkout
    run_command(cmd, capture=True)
  File "/home/vincent/Development/classycookie/venv/lib/python3.8/site-packages/spacy/util.py", line 967, in run_command
    raise error
subprocess.SubprocessError: Error running command:

git -C /tmp/tmpft3wrmsu clone https://github.com/koaning/classycookie . -b master

Subprocess exited with status 128

Process log (stdout and stderr):

Cloning into '.'...
fatal: Remote branch master not found in upstream origin
```

When I manually set the branch everything works. 

```
> python -m spacy project clone --repo https://github.com/koaning/classycookie classification -b main

✔ Cloned 'classification' from koaning/classycookie
/home/vincent/Development/classification
✔ Your project is now ready!
To fetch the assets, run:
python -m spacy project assets /home/vincent/Development/classification
```

Figured I'd mention it here. Given that `main` is the new default on Github ... might it make sense to switch the default in the `-b` param?

**Comment by adrianeboyd** [comment]
I think it would reasonable to change the default here, but since it's going to break any existing instructions/tutorials for repos using `master` we should provide an error message with the exact command to copy and paste to get `master` instead.

**Comment by koaning** [comment]
I guess it's a bit hacky, but the default might also be to first try the `main` and then the `master` branch. This should keep everything working and it feels like a safe assumption. I doubt there are many projects that have both a `main` and `master` where the `main` branch isn't the "main"-branch. This is totally an assumption on my part though.
