### ISSUE TITLE
Using `beam_ner` component fails.

### ISSUE THREAD

**Issue by narayanacharya6** [explosion/spaCy#10504]
## How to reproduce the behaviour
```
import spacy
nlp = spacy.load("en_core_web_lg")
nlp = spacy.load("en_core_web_lg", exclude=[name for name in nlp.pipe_names])
nlp.add_pipe("beam_ner")
content = "George Washington University Washington DC is a premier university in the US"
doc = nlp(content)
```

Stacktrace:
```
Traceback (most recent call last):
  File "/Users/narayan/anaconda3/envs/project-lis/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-077b7f4b02c2>", line 6, in <module>
    doc = nlp(content)
  File "/Users/narayan/anaconda3/envs/project-lis/lib/python3.10/site-packages/spacy/language.py", line 1022, in __call__
    error_handler(name, proc, [doc], e)
  File "/Users/narayan/anaconda3/envs/project-lis/lib/python3.10/site-packages/spacy/util.py", line 1617, in raise_error
    raise e
  File "/Users/narayan/anaconda3/envs/project-lis/lib/python3.10/site-packages/spacy/language.py", line 1017, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "spacy/pipeline/trainable_pipe.pyx", line 56, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "/Users/narayan/anaconda3/envs/project-lis/lib/python3.10/site-packages/spacy/util.py", line 1617, in raise_error
    raise e
  File "spacy/pipeline/trainable_pipe.pyx", line 52, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "spacy/pipeline/transition_parser.pyx", line 252, in spacy.pipeline.transition_parser.Parser.predict
  File "spacy/pipeline/transition_parser.pyx", line 282, in spacy.pipeline.transition_parser.Parser.beam_parse
  File "spacy/pipeline/_parser_internals/_beam_utils.pyx", line 48, in spacy.pipeline._parser_internals._beam_utils.BeamBatch.__init__
  File "thinc/extra/search.pyx", line 13, in thinc.extra.search.Beam.__init__
AssertionError
```

Is this the right way to use `beam_ner`?

## Your Environment
- **spaCy version:** 3.2.3
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.10.0
- **Pipelines:** en_core_web_lg (3.2.0)

**Comment by adrianeboyd** [comment]
`add_pipe` only adds an uninitialized, untrained component, so first you'd need to initialize the component and train it. (Admittedly this error message is not helpful.)

We recommend using the `spacy train` CLI for this. You can create a config with `spacy init config -p beam_ner beam_ner.config`. If you want to use the vectors from `en_core_web_lg` in your pipeline, then:

```shell
spacy init config -p beam_ner beam_ner.config -o accuracy
```

Toy/example NER training data can be found in several [projects](https://spacy.io/usage/projects) including:

* https://github.com/explosion/projects/tree/v3/pipelines/ner_demo
* https://github.com/explosion/projects/tree/v3/pipelines/ner_wikiner

A good place to start in the docs for training: https://spacy.io/usage/training#quickstart

`beam_ner` isn't included in the website config generator, but you can follow the directions starting right afterwards in the same section.

**Comment by adrianeboyd** [comment]
Let me convert this to a discussion...
