### ISSUE TITLE
Training and testing dataset in python

### ISSUE THREAD

**Issue by HinaMalikAwan** [explosion/spaCy#10520]
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by HinaMalikAwan** [comment]
C:\Users\Hina\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/Hina/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "C:\Users\Hina\PycharmProjects\pythonProject\main.py", line 6, in <module>
    df = pd.read_csv('Real estate.csv')
  File "C:\Users\Hina\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Hina\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Hina\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\io\parsers\readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Hina\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\io\parsers\readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\Hina\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "C:\Users\Hina\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\io\common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'Real estate.csv'

Process finished with exit code 1

**Comment by adrianeboyd** [comment]
Hi, I think you might have posted this in the wrong place? The issue tracker here is just for reporting bugs in the `spacy` library.
