### ISSUE TITLE
Korean tokenizer error due to missing key "UNKNOWN" in TAG_MAP

### ISSUE THREAD

**Issue by l-k-11235** [explosion/spaCy#10535]
## How to reproduce the behaviour
```
>>> from spacy.util import get_lang_class
>>> cls = get_lang_class("ko")
>>> cls().tokenizer("미닛 리피터")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/spacy/lang/ko/__init__.py", line 50, in __call__
    token.pos = TAG_MAP[token.tag_][POS]
KeyError: 'UNKNOWN'
>>> 
```
## Your Environment
* Operating System: Ubuntu 20.04.4 LTS
* Python Version Used: 3.8.10
* spaCy Version Used: 3.2.0

**Comment by adrianeboyd** [comment]
Thanks for the report! Should be fixed by #10536 by using `X` for any unknown tags.
