### ISSUE TITLE
Deprecation Warning with Python 3.10.0 and Spacy 3.2.4.

### ISSUE THREAD

**Issue by simurgh9** [explosion/spaCy#10609]
## How to reproduce the behaviour

Run this with Python 3.10.0 and Spacy 3.2.4. 

```
import en_core_web_md
from warnings import filterwarnings
filterwarnings('error')

pipeline = en_core_web_md.load()
```

You'll get,

```
Traceback (most recent call last):
  File "/home/username/project/prog.py", line 5, in <module>
    pipeline = en_core_web_md.load()
  File "/home/username/.local/share/virtualenvs/project-2ZeatEXR/lib/python3.10/site-packages/en_core_web_md/__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/username/.local/share/virtualenvs/project-2ZeatEXR/lib/python3.10/site-packages/spacy/util.py", line 615, in load_model_from_init_py
    return load_model_from_path(
  File "/home/username/.local/share/virtualenvs/project-2ZeatEXR/lib/python3.10/site-packages/spacy/util.py", line 488, in load_model_from_path
    nlp = load_model_from_config(config, vocab=vocab, disable=disable, exclude=exclude)
  File "/home/username/.local/share/virtualenvs/project-2ZeatEXR/lib/python3.10/site-packages/spacy/util.py", line 524, in load_model_from_config
    lang_cls = get_lang_class(nlp_config["lang"])
  File "/home/username/.local/share/virtualenvs/project-2ZeatEXR/lib/python3.10/site-packages/spacy/util.py", line 325, in get_lang_class
    if lang in registry.languages:
  File "/home/username/.local/share/virtualenvs/project-2ZeatEXR/lib/python3.10/site-packages/catalogue/__init__.py", line 49, in __contains__
    has_entry_point = self.entry_points and self.get_entry_point(name)
  File "/home/username/.local/share/virtualenvs/project-2ZeatEXR/lib/python3.10/site-packages/catalogue/__init__.py", line 135, in get_entry_point
    for entry_point in AVAILABLE_ENTRY_POINTS.get(self.entry_point_namespace, []):
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 400, in get
    self._warn()
DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
```

## Your Environment

- **spaCy version:** 3.2.4
- **Platform:** Linux-5.13.0-39-generic-x86_64-with-glibc2.34
- **Python version:** 3.10.0
- **Pipelines:** en_core_web_md (3.2.0)
* Operating System: Ubuntu 21.10
* Python Version Used: 3.10.0
* spaCy Version Used: 3.2.4

**Comment by adrianeboyd** [comment]
Thanks for the report! We're aware that `catalogue` needs a few updates for python 3.10 and likely 3.11, but we don't have a fix yet for this or the test suite (https://github.com/explosion/catalogue/issues/27). Let me transfer this to the `catalogue` repo...
