### ISSUE TITLE
Corrupted Trained Model With pkuseg Tokenizer

### ISSUE THREAD

**Issue by dylank0211** [explosion/spaCy#10638]
## How to reproduce the behaviour
I was using the chinese package zh_core_web_sm 2.3.1 on SpaCy 2.3.2 to train an NER model. In this process I used the following command to update the tokenizer dictionary:

`nlp.tokenizer.pkuseg_update_user_dict(chinese_words)
`

The model training went successfully. However, the trained model wouldn't be loaded, and I got the following error:

` Traceback (most recent call last):

  File "/home/development/dkong/branches/Pythagoras/ner/ner/evaluation/calculate_performance_metrics.py", line 87, in <module>
    main(read_yaml_config(help="calculate_performance_metrics config yaml", required=True))
  File "/home/development/dkong/branches/Pythagoras/ner/ner/evaluation/calculate_performance_metrics.py", line 63, in main
    nlp = spacy.load(input_model_filename)
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/util.py", line 172, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/util.py", line 222, in load_model_from_path
    return nlp.from_disk(model_path, exclude=disable)
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/language.py", line 974, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/util.py", line 690, in from_disk
    reader(path / key)
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/language.py", line 960, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/lang/zh/__init__.py", line 283, in from_disk
    util.from_disk(path, serializers, [])
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/util.py", line 690, in from_disk
    reader(path / key)
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/lang/zh/__init__.py", line 280, in <lambda>
    ("pkuseg_processors", lambda p: load_pkuseg_processors(p)),
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/spacy/lang/zh/__init__.py", line 271, in load_pkuseg_processors
    self.pkuseg_seg.preprocesser = pkuseg.Preprocesser(user_dict)
  File "/home/dkong/anaconda3/lib/python3.9/site-packages/pkuseg/__init__.py", line 57, in __init__
    assert isinstance(w_t, tuple)
AssertionError`
## Your Environment

* Operating System: Linux-4.15.
* Python Version Used: 3.9.7
* spaCy Version Used: 2.3.2
* Environment Information:

**Comment by polm** [comment]
Sorry you're having trouble with this, and thanks for the report. 

For context, can you clarify why you're using v2? v3 has been out a year and I'd recommend you give it a shot if you haven't.

We still want to be aware of issues with v2, and we can try to help you with it, but v2 specific issues are generally lower priority for us than v3.

**Comment by dylank0211** [comment]
Thanks for the prompt reply polm!

My company has been working on transitioning everything from v2 to v3 recently, but as you know these two versions are quite different and many things are not quite compatible so there's a lot of work. Meanwhile I'm exploring the Chinese packages as an approach to see if we can provide our services in other languages besides English, so I'm still working under the old v2 environment. However I'll definitely look into v3 and see if this also happens!

**Comment by adrianeboyd** [comment]
Thanks for the report, this is a bug in how spacy is saving/loading the pkuseg data.

The data itself is not corrupted, but spacy is saving the data with msgpack, which doesn't distinguish between lists and tuples, which causes this problem with pkuseg when it tries to load the model back in and only recognizes tuples. It would be easy to fix in the `spacy-pkuseg` fork, which is used in the v3 models, so that this would work in any existing v3 `zh_*` models, but the v2 models are still using the original `pkuseg` package, so a fix would require a new release of v2.3.x that adds a workaround to `Chinese`.

**Comment by adrianeboyd** [comment]
This should be fixed in `spacy-pkuseg` v0.0.30+, so I think user dict serialization should now work for all spaCy v3 pipelines. If you run into problems, please feel free to reopen this issue.
