### ISSUE TITLE
Fine tuning a transformer based model

### ISSUE THREAD

**Issue by ryszardtuora** [explosion/spaCy#10671]
I am trying to train a transformer based model for Polish. The results are very promising, and I have already got a working model trained on the tasks of NER, dependency parsing, and tagging, on one dataset, but I would like to explore the possibilities of fine-tuning it on some of the tasks on data which is not annotated on all layers (e.g. it only has NER annotation).

My idea on how to proceed, would be to source the model from the one I've trained, freeze the other components (because they are not being trained), freeze the transformer (so as to not alter the behavior of the components downstream from it), and only train the component, for which I have annotation (NER in this case).

I've tried to prepare a config file, which would do something like that:

```[paths]
train = ConvertedResources/pl_pdb-ud-train.spacy
dev = ConvertedResources/pl_pdb-ud-dev.spacy
vectors = null
init_tok2vec = null

[system]
gpu_allocator = null
seed = 0

[nlp]
lang = "pl"
pipeline = ["transformer","parser"]
batch_size = 128
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.parser]
source = "trained_trf_complete_proper/model-best"
component = "parser"

[components.parser.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "parser"
extra_state_tokens = false
hidden_width = 128
maxout_pieces = 3
use_upper = false
nO = null

[components.parser.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 0.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"

[components.transformer]
source = "trained_trf_complete_proper/model-best"
component = "transformer"

[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v3"
name = "trained_trf_complete_proper/model-best/transformer"
mixed_precision = false

[components.transformer.model.get_spans]
@span_getters = "spacy-transformers.strided_spans.v1"
window = 128
stride = 96

[components.transformer.model.grad_scaler_config]

[components.transformer.model.tokenizer_config]
use_fast = true

[components.transformer.model.transformer_config]

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[training]
accumulate_gradient = 3
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = ["transformer"]
annotating_components = ["transformer"]
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_padded.v1"
discard_oversize = true
size = 2000
buffer = 256
get_length = null

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001

[training.optimizer.learn_rate]
@schedules = "warmup_linear.v1"
warmup_steps = 250
total_steps = 20000
initial_rate = 0.00005

[training.score_weights]
dep_uas = 0.5
dep_las = 0.5
dep_las_per_type = null
sents_p = null
sents_r = null
sents_f = 0.0

[pretraining]

[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```

but unfortunately using it produces a rather cryptic error.

```
============================= Training pipeline =============================
ℹ Pipeline: ['transformer', 'parser']
ℹ Frozen components: ['transformer']
ℹ Set annotations on update for: ['transformer']
ℹ Initial learn rate: 0.0
E    #       LOSS PARSER  DEP_UAS  DEP_LAS  SENTS_F  SCORE 
---  ------  -----------  -------  -------  -------  ------
/home/rtuora/.local/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
⚠ Aborting and saving the final best model. Encountered exception:
TypeError("'NoneType' object is not callable")
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rtuora/.local/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/rtuora/.local/lib/python3.8/site-packages/spacy/cli/_util.py", line 71, in setup_cli
    command(prog_name=COMMAND)
  File "/home/rtuora/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/rtuora/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/rtuora/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rtuora/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rtuora/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/rtuora/.local/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/rtuora/.local/lib/python3.8/site-packages/spacy/cli/train.py", line 45, in train_cli
    train(config_path, output_path, use_gpu=use_gpu, overrides=overrides)
  File "/home/rtuora/.local/lib/python3.8/site-packages/spacy/cli/train.py", line 75, in train
    train_nlp(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "/home/rtuora/.local/lib/python3.8/site-packages/spacy/training/loop.py", line 122, in train
    raise e
  File "/home/rtuora/.local/lib/python3.8/site-packages/spacy/training/loop.py", line 105, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "/home/rtuora/.local/lib/python3.8/site-packages/spacy/training/loop.py", line 203, in train_while_improving
    nlp.update(
  File "/home/rtuora/.local/lib/python3.8/site-packages/spacy/language.py", line 1156, in update
    proc.update(examples, sgd=None, losses=losses, **component_cfg[name])  # type: ignore
  File "spacy/pipeline/transition_parser.pyx", line 419, in spacy.pipeline.transition_parser.Parser.update
  File "spacy/ml/parser_model.pyx", line 300, in spacy.ml.parser_model.ParserStepModel.finish_steps
  File "/home/rtuora/.local/lib/python3.8/site-packages/thinc/layers/chain.py", line 60, in backprop
    dX = callback(dY)
  File "/home/rtuora/.local/lib/python3.8/site-packages/thinc/layers/chain.py", line 60, in backprop
    dX = callback(dY)
  File "/home/rtuora/.local/lib/python3.8/site-packages/spacy_transformers/layers/listener.py", line 39, in backprop_and_clear
    result = self._backprop(*args, **kwargs)
TypeError: 'NoneType' object is not callable

```

## Your Environment
- **spaCy version:** 3.2.3
- **Platform:** Linux-5.4.0-99-generic-x86_64-with-glibc2.29
- **Python version:** 3.8.10
- **Pipelines:** en_core_web_lg (3.1.0)

**Comment by adrianeboyd** [comment]
Sorry the delayed response! Thanks for the report, I can reproduce this, and I think it should be pretty easy to fix in `spacy-transformers`, but I need to do a bit more testing first. (I'm not sure how well the training will work with the frozen transformer, especially with `use_upper = false`.)

**Comment by adrianeboyd** [comment]
Should be fixed by: https://github.com/explosion/spacy-transformers/pull/324
