### ISSUE TITLE
error when use zh vacab model

### ISSUE THREAD

**Issue by damao4123** [explosion/spaCy#1086]
hi ,i was doing sth about 'zh',and i have already make a vacab model  by gensim,
and i mv the 'vacab' dir into the spacy/data/zh/vacab, and then i run a test demo :

    # -*- coding: utf-8 -*-
    import spacy
    nlp = spacy.load('zh')
    test_doc = nlp("测试一下分词")
    print(test_doc)

and i got the error:

Traceback (most recent call last):
  File "tool_spacy_test.py", line 5, in <module>
    nlp = spacy.load('zh')
  File "/usr/local/lib/python3.5/site-packages/spacy/__init__.py", line 40, in load
    return cls(**overrides)
  File "/usr/local/lib/python3.5/site-packages/spacy/language.py", line 281, in __init__
    if 'tokenizer' not in overrides \
  File "/usr/local/lib/python3.5/site-packages/spacy/language.py", line 85, in create_tokenizer
    infix_finditer=infix_finditer, token_match=token_match)
  File "spacy/tokenizer.pyx", line 95, in spacy.tokenizer.Tokenizer.__init__ (spacy/tokenizer.cpp:4624)
  File "spacy/tokenizer.pyx", line 389, in spacy.tokenizer.Tokenizer.add_special_case (spacy/tokenizer.cpp:8580)
  File "spacy/vocab.pyx", line 351, in spacy.vocab.Vocab.make_fused_token (spacy/vocab.cpp:8442)
  File "spacy/morphology.pyx", line 64, in spacy.morphology.Morphology.assign_tag (spacy/morphology.cpp:4540)
KeyError: 22481

anyone can help me
* Operating System: macos
* Python Version Used: 3.5
* spaCy Version Used: 1.82

**Comment by ines** [comment]
Sorry for only getting to this now. We've since released a new version, spaCy v2.0, which should make training language models much easier.

There's now also a [`spacy vocab`](https://spacy.io/api/cli#vocab) CLI command that helps you generate a vocabulary from a lexicon. This should hopefully solve your problem. After creating your vocab, you can use [`spacy train`](https://spacy.io/api/cli#train) to train a model.
