### ISSUE TITLE
install does not work

### ISSUE THREAD

**Issue by keithbriggs** [explosion/spaCy#1095]
I did this on a new clean ubuntu 16 system:

>  sudo pip3 install spacy
...
Successfully installed spacy murmurhash cymem preshed thinc plac pathlib ujson dill requests regex ftfy wrapt tqdm cytoolz termcolor chardet certifi urllib3 idna tool

> python3 -m spacy download en
/usr/bin/python3: Error while finding spec for 'spacy.__main__' (<class 'ImportError'>: cannot import name 'IncompleteRead'); 'spacy' is a package and cannot be directly executed

> python -m spacy download en
/usr/bin/python: No module named spacy

**Comment by keithbriggs** [comment]
Another problem, following the "Run tests" instructions at https://spacy.io/docs/usage/ 

> python3 -c "import os; import spacy; print(os.path.dirname(spacy.__file__))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/usr/local/lib/python3.4/dist-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/usr/local/lib/python3.4/dist-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/usr/local/lib/python3.4/dist-packages/spacy/cli/download.py", line 9, in <module>
    from .link import link_package
  File "/usr/local/lib/python3.4/dist-packages/spacy/cli/link.py", line 4, in <module>
    import pip
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'

**Comment by ines** [comment]
Copying over the discussion from #1094 for reference:

> @keithbriggs: I had installed it with pip on an ubuntu 16 system - apparently the version of pip is a bit old. So I uninstalled it, and did a new install with easy_install. This worked.

> @ines: Glad to hear it worked – sorry you were having problems! Did the solution you outlined also solve #1095?

> @keithbriggs: I think so, but I was trying spacy on several different machines and did not keep records of what worked and what did not. Maybe next week I'll try again on a new clean standard-configuration Ubuntu machine.

> @ines: Thanks and no worries! We'll also look into this when we update the cross-platform tests for v2. This issue was particularly interesting, because I don't remember ever seeing this exact error before. (So even if it turns out to be related to a specific pip version or bug, it'd definitely be worth mentioning that in the docs.)
