### ISSUE TITLE
AttributeError: [E046] Can't retrieve unregistered extension attribute 'phrases'. Did you forget to call the `set_extension` method?

### ISSUE THREAD

**Issue by fabmeyer** [explosion/spaCy#10996]
Traceback (most recent call last):
  File "analysis/LanguageModel/LanguageModel.py", line 78, in <module>
    language_model('artificia intelligenc', model)
  File "analysis/LanguageModel/LanguageModel.py", line 71, in language_model
    sentences = extract_sentences(' '.join(definitions), model, number=3)
  File "/home/fabmeyer/Dev/Python/analytics/analysis/LanguageModel/SentenceExtractor.py", line 12, in extract_sentences
    for phrase in doc._.phrases:
  File "/home/fabmeyer/.local/share/virtualenvs/analytics-nko8goOs/lib/python3.8/site-packages/spacy/tokens/underscore.py", line 47, in __getattr__
    raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'phrases'. Did you forget to call the `set_extension` method?

## Info about spaCy
- **spaCy version:** 3.2.4
- **Platform:** Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
- **Python version:** 3.8.0
- **Pipelines:** en_use_lg (0.4.3), en_core_web_lg (3.2.0), en_core_web_sm (3.2.0), en_core_web_trf (3.2.0)

Some weeks ago I wrote (copy pasted) a script that does extract the most important sentences. Now I am getting this error. I haven't found anything useful on Google.

**Comment by polm** [comment]
Moving to Discussions since this is more of a usage question than a bug report.
