### ISSUE TITLE
"python -m spacy download en" throws TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by YanfaAdiPutra** [explosion/spaCy#1102]
running "python -m spacy download en" throws TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'

Here is the error message:
<details>

```
(.env) $ python -m spacy download en
Downloading en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz

Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz (52.2MB)
    100% |████████████████████████████████| 52.2MB 169kB/s 
  Requirement already satisfied (use --upgrade to upgrade): en-core-web-sm==1.2.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz in ./.env/lib/python2.7/site-packages
Requirement already satisfied: spacy<2.0.0,>=1.7.0 in /home/ (from en-core-web-sm==1.2.0)
Requirement already satisfied: numpy>=1.7 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: murmurhash<0.27,>=0.26 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: cymem<1.32,>=1.30 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: thinc<6.6.0,>=6.5.0 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: pip<10.0.0,>=9.0.0 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: six in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: pathlib in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: ujson>=1.35 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: dill<0.3,>=0.2 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: regex==2017.4.5 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: ftfy<5.0.0,>=4.4.2 in ./.env/lib/python2.7/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: termcolor in ./.env/lib/python2.7/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: wrapt in ./.env/lib/python2.7/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: cytoolz<0.9,>=0.8 in ./.env/lib/python2.7/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in ./.env/lib/python2.7/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: idna<2.6,>=2.5 in ./.env/lib/python2.7/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in ./.env/lib/python2.7/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.env/lib/python2.7/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.env/lib/python2.7/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: html5lib in ./.env/lib/python2.7/site-packages (from ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: wcwidth in ./.env/lib/python2.7/site-packages (from ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: toolz>=0.8.0 in ./.env/lib/python2.7/site-packages (from cytoolz<0.9,>=0.8->thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: setuptools>=18.5 in ./.env/lib/python2.7/site-packages (from html5lib->ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: webencodings in ./.env/lib/python2.7/site-packages (from html5lib->ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/spacy/__main__.py", line 133, in <module>
    plac.Interpreter.call(CLI)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 1142, in call
    print(out)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "/home/.env/local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/spacy/__main__.py", line 33, in download
    cli_download(model, direct)
  File "spacy/cli/download.py", line 24, in download
    link_package(model_name, model, force=True)
  File "spacy/cli/link.py", line 27, in link_package
    symlink(model_path, link_name, force)
  File "spacy/cli/link.py", line 37, in symlink
    link_path = util.get_data_path() / link_name
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
```

</details>

## My Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 2.7
* spaCy Version Used: 1.8.2
* Environment Information: `python -m spacy info --markdown` result :
<details>

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/spacy/__main__.py", line 133, in <module>
    plac.Interpreter.call(CLI)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 1142, in call
    print(out)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "/home/.env/local/lib/python2.7/site-packages/plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "/home/.env/local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/spacy/__main__.py", line 60, in info
    cli_info(model, markdown)
  File "spacy/cli/info.py", line 23, in info
    data = get_spacy_data()
  File "spacy/cli/info.py", line 41, in get_spacy_data
    'Installed models': ', '.join(list_models())
TypeError: can only join an iterable
```
</details>

**Comment by ines** [comment]
Hmm, so the cause of that error is that the data path, which spaCy gets via `util.get_data_path()` is set to `None`. (The data path is where spaCy will look for models and model symlinks – by default, it's `spacy/data`.) But this just seems to be a side-effect of an underlying problem with the Python path, especially considering `info` has a similar problem.

It looks like your `PATH` might be set incorrectly – when you're writing `python`, it somehow executes a version outside your virtualenv:

```bash
File "/home/spacy/__main__.py", line 133, in <module>
```

**Comment by ned2** [comment]
You'll also get this error if you delete the 'data' directory inside spaCy's site-package folder. Just recreating it fixes the problem.

**Comment by chbrown** [comment]
Same here; just ran into this with spaCy 1.9.0 after upgrading from a previous version, 1.6.0, IIRC.

I probably removed the data subdirectory a while back to free up disk space. So, it's my own damn fault, unfortunately. But could spaCy automatically create that directory if needed? Or at least show a better error message? I guess I probably could have gotten to the fix quicker with a `pip uninstall` and full reinstall, but instead ended up re-downloading `en_core_web_sm-1.2.0.tar.gz` a half-dozen times trying other solutions before I googled the cryptic error message & trace + "spacy".

**Comment by ines** [comment]
@chbrown Sorry about the bad error message and good point! Will add a check for `util.get_data_path()` to the `link` command that exits and prints a warning if the data path does not exist or is set to `None`.
