### ISSUE TITLE
Windows installation proble

### ISSUE THREAD

**Issue by experyenz** [explosion/spaCy#1108]
Hi when I run the command : pip install -r requirements.txt
I have the following errors : 
Exception:
Traceback (most recent call last):
  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 45: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 518, in _prepare_file
    abstract_dist.prep_for_dist()
  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 45: invalid continuation byte

## Your Environment

* Operating System: windows 10 Family
* Python Version Used: 3.6
* spaCy Version Used:  get by : git clone https://github.com/explosion/spaCy  today
* Environment Information:

**Comment by ines** [comment]
Which version of pip are you using? The problem seem to be happening within pip... just did a quick search for that error message and it turned up a few similar problems related to pip bugs and weirdnesses. If you're not using the latest version of pip, does upgrading help?

**Comment by experyenz** [comment]
Hi, thank you for answering. I have upgaded pip but i stll have errors : 

 

Running setup.py bdist_wheel for cython ... error

  Failed building wheel for cython

  Running setup.py clean for cython

  Running setup.py bdist_wheel for pathlib ... done

  Stored in directory: C:\Users\laurent\AppData\Local\pip\Cache\wheels\2a\23\a5\d8803db5d631e9f391fe6defe982a238bf5483062eeb34e841

  Running setup.py bdist_wheel for cymem ... error

  Failed building wheel for cymem

  Running setup.py clean for cymem

  Running setup.py bdist_wheel for preshed ... error

  Failed building wheel for preshed

  Running setup.py clean for preshed

  Running setup.py bdist_wheel for thinc ... error

  Failed building wheel for thinc

  Running setup.py clean for thinc

  Running setup.py bdist_wheel for murmurhash ... error

  Failed building wheel for murmurhash

  Running setup.py clean for murmurhash

  Running setup.py bdist_wheel for ujson ... error

  Failed building wheel for ujson

  Running setup.py clean for ujson

 

And : 

 

Running setup.py install for cython ... error

Exception:

Traceback (most recent call last):

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str

    return s.decode(sys.__stdout__.encoding)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run

    prefix=options.prefix_path,

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install

    **kwargs

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install

    spinner=spinner,

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess

    line = console_to_str(proc.stdout.readline())

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str

    return s.decode('utf_8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 385, in run

    requirement_set.cleanup_files()

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 729, in cleanup_files

    req.remove_temporary_source()

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 977, in remove_temporary_source

    rmtree(self.source_dir)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f

    return Retrying(*dargs, **dkw).call(f, *args, **kw)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 212, in call

    raise attempt.get()

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 247, in get

    six.reraise(self.value[0], self.value[1], self.value[2])

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\six.py", line 686, in reraise

    raise value

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 200, in call

    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree

    onerror=rmtree_errorhandler)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\shutil.py", line 488, in rmtree

    return _rmtree_unsafe(path, onerror)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\shutil.py", line 387, in _rmtree_unsafe

    onerror(os.rmdir, path, sys.exc_info())

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler

    func(path)

PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\laurent\\AppData\\Local\\Temp\\pip-build-0yxuh9pj\\murmurhash'

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main

    status = self.run(options, args)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 385, in run

    requirement_set.cleanup_files()

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\build.py", line 38, in __exit__

    self.cleanup()

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\build.py", line 42, in cleanup

    rmtree(self.name)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f

    return Retrying(*dargs, **dkw).call(f, *args, **kw)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 212, in call

    raise attempt.get()

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 247, in get

    six.reraise(self.value[0], self.value[1], self.value[2])

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\six.py", line 686, in reraise

    raise value

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 200, in call

    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree

    onerror=rmtree_errorhandler)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\shutil.py", line 488, in rmtree

    return _rmtree_unsafe(path, onerror)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\shutil.py", line 378, in _rmtree_unsafe

    _rmtree_unsafe(fullname, onerror)

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\shutil.py", line 387, in _rmtree_unsafe

    onerror(os.rmdir, path, sys.exc_info())

  File "c:\users\laurent\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler

    func(path)

PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\laurent\\AppData\\Local\\Temp\\pip-build-0yxuh9pj\\cytoolz'

 

SAS eXperYenZ

Laurent Lapierre

+33 (0)6 84 53 04 99

 

De : Ines Montani [mailto:notifications@github.com] 
Envoyé : mercredi 7 juin 2017 12:32
À : explosion/spaCy <spaCy@noreply.github.com>
Cc : experyenz <laurent.lapierre@experyenz.com>; Author <author@noreply.github.com>
Objet : Re: [explosion/spaCy] Windows installation proble (#1108)

 

Which version of pip are you using? The problem seem to be happening within pip... just did a quick search for that error message and it turned up a few similar problems related to pip bugs and weirdnesses. If you're not using the latest version of pip, does upgrading help?

**Comment by ines** [comment]
Hm okay, so this sill seems to be the same issue with pip and it fails before you're even getting to the actual installation.

Do any of the solutions described here work for you?
https://github.com/pypa/pip/issues/4251

**Comment by experyenz** [comment]
Ok I will look at this.

 

Do you have code example to pos tagging an input text file, mark entities and then generate an output file tagged ?

 

SAS eXperYenZ

Laurent Lapierre

+33 (0)6 84 53 04 99

 

De : Ines Montani [mailto:notifications@github.com] 
Envoyé : mercredi 7 juin 2017 13:47
À : explosion/spaCy <spaCy@noreply.github.com>
Cc : experyenz <laurent.lapierre@experyenz.com>; Author <author@noreply.github.com>
Objet : Re: [explosion/spaCy] Windows installation proble (#1108)

 

Hm okay, so this sill seems to be the same issue with pip and it fails before you're even getting to the actual installation.

Do any of the solutions described here work for you?
pypa/pip#4251 <https://github.com/pypa/pip/issues/4251>

**Comment by ines** [comment]
Hope it works!

A good place to start is the lightning tour: https://spacy.io/docs/usage/lightning-tour
It includes an overview of spaCy's functionality, plus simple code examples.

For more details on POS tagging and NER, see the usage guides:
Part-of-speech tagging: https://spacy.io/docs/usage/pos-tagging
Entity Recognition: https://spacy.io/docs/usage/entity-recognition

If you want to test the new version, v2.0.0 alpha, you can find the release notes and details here:
https://github.com/explosion/spaCy/releases/tag/v2.0.0-alpha
The alpha docs also include a more detailed guide on all the spaCy basics in the upcoming v2:
https://alpha.spacy.io/docs/usage/spacy-101

**Comment by experyenz** [comment]
Thank you very much for your help

 

SAS eXperYenZ

Laurent Lapierre

+33 (0)6 84 53 04 99

 

De : Ines Montani [mailto:notifications@github.com] 
Envoyé : mercredi 7 juin 2017 14:13
À : explosion/spaCy <spaCy@noreply.github.com>
Cc : experyenz <laurent.lapierre@experyenz.com>; Author <author@noreply.github.com>
Objet : Re: [explosion/spaCy] Windows installation proble (#1108)

 

Hope it works!

A good place to start is the lightning tour: https://spacy.io/docs/usage/lightning-tour
It includes an overview of spaCy's functionality, plus simple code examples.

For more details on POS tagging and NER, see the usage guides:
Part-of-speech tagging: https://spacy.io/docs/usage/pos-tagging
Entity Recognition: https://spacy.io/docs/usage/entity-recognition

If you want to test the new version, v2.0.0 alpha, you can find the release notes and details here:
https://github.com/explosion/spaCy/releases/tag/v2.0.0-alpha
The alpha docs also include a more detailed guide on all the spaCy basics in the upcoming v2:
https://alpha.spacy.io/docs/usage/spacy-101
