### ISSUE TITLE
AttributeError: 'spacy.tokens.doc.Doc' object has no attribute 'from_json'

### ISSUE THREAD

**Issue by azaddjanibd** [explosion/spaCy#11216]
## How to reproduce the behavior
```
import spacy
from spacy.tokens import Doc


def demo():
    nlp =  spacy.load('en_core_web_sm')

    doc = nlp("All we have to decide is what to do with the time that is given us.")
    doc_json = doc.to_json()
    deserialized_doc = Doc(nlp.vocab).from_json(doc_json)
    assert deserialized_doc.text == doc.text == doc_json["text"]

demo()
```

Output

```
Traceback (most recent call last):
  File "/Users/myuser/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_24.py", line 13, in <module>
    demo()
  File "/Users/myuser/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_24.py", line 10, in demo
    deserialized_doc = Doc(nlp.vocab).from_json(doc_json)
AttributeError: 'spacy.tokens.doc.Doc' object has no attribute 'from_json'. Did you mean: 'to_json'?
```
## Environment

* Operating System: Mac Os Intel
* Python Version Used: 3.10
* spaCy Version Used: spacy==3.3.0
* Environment Information:

**Comment by azaddjanibd** [comment]
I reinstall spacy 3.3.1, now it is working like expected.
