### ISSUE TITLE
Unable to train NER model using A100 GPU

### ISSUE THREAD

**Issue by Anand195** [explosion/spaCy#11225]
### Discussed in https://github.com/explosion/spaCy/discussions/11224

<div type='discussions-op-text'>

<sup>Originally posted by **Anand195** July 27, 2022</sup>
Hi guys 
I had A100 gpu and trying to train NER model using custom dataset.

Got exception

ℹ Saving to output directory: /home/ubuntu/NER/model
ℹ Using GPU: 0
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/ubuntu/.local/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
setup_cli()
File "/home/ubuntu/.local/lib/python3.8/site-packages/spacy/cli/_util.py", line 71, in setup_cli
command(prog_name=COMMAND)
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.8/site-packages/typer/main.py", line 532, in wrapper
return callback(**use_params) # type: ignore
File "/home/ubuntu/.local/lib/python3.8/site-packages/spacy/cli/train.py", line 45, in train_cli
train(config_path, output_path, use_gpu=use_gpu, overrides=overrides)
File "/home/ubuntu/.local/lib/python3.8/site-packages/spacy/cli/train.py", line 67, in train
setup_gpu(use_gpu)
File "/home/ubuntu/.local/lib/python3.8/site-packages/spacy/cli/_util.py", line 571, in setup_gpu
require_gpu(use_gpu)
File "/home/ubuntu/.local/lib/python3.8/site-packages/thinc/util.py", line 195, in require_gpu
raise ValueError("No GPU devices detected")
ValueError: No GPU devices detected
Command exited with non-zero status 1
1.46user 0.90system 0:02.07elapsed 114%CPU (0avgtext+0avgdata 1142240maxresident)k
0inputs+0outputs (2major+122131minor)pagefaults 0swaps

spacy version : 3.4
Python version : 3.8

Kindly share the solution.</div>

**Comment by adrianeboyd** [comment]
Please do not open duplicate issues, we'll follow up in the original discussion thread.
