### ISSUE TITLE
Conda installation is not working

### ISSUE THREAD

**Issue by MilenkoM** [explosion/spaCy#1123]
I have tried this

python -m spacy download en
Traceback (most recent call last):
  File "/home/milenko/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/milenko/anaconda3/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/milenko/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/milenko/anaconda3/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from . import util
  File "/home/milenko/anaconda3/lib/python3.6/site-packages/spacy/util.py", line 5, in <module>
    import regex as re
  File "/home/milenko/anaconda3/lib/python3.6/site-packages/regex.py", line 394, in <module>
    import _regex_core
  File "/home/milenko/anaconda3/lib/python3.6/site-packages/_regex_core.py", line 21, in <module>
    import _regex
ImportError: /home/milenko/anaconda3/lib/python3.6/site-packages/_regex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PySlice_AdjustIndices

## Your Environment

* Operating System: 
Ubuntu 16.04
* Python Version Used: 
Python 3.6.0 :: Anaconda custom (64-bit)
* spaCy Version Used: 
* Environment Information: 

 ldd /home/milenko/anaconda3/lib/python3.6/site-packages/_regex.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007fffdf9a7000)
	libpython3.6m.so.1.0 => /home/milenko/anaconda3/lib/python3.6/site-packages/../../libpython3.6m.so.1.0 (0x00007f48be1df000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f48bdf9f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f48bdbd6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f48bd9d2000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f48bd7ce000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f48bd5c6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f48bd2bd000)
	/lib64/ld-linux-x86-64.so.2 (0x0000557ab540a000)

**Comment by nikhilweee** [comment]
Try updating regex.
```
conda update regex
```

**Comment by MilenkoM** [comment]
Yes, that was the issue, works perfectly now!

**Comment by ines** [comment]
Thanks for updating! Since this has come up before and is hard to prevent from our end, maybe it'll make sense to add this to the troubleshooting section in the docs. I'll put this on my list!
