### ISSUE TITLE
[E871] error when n_process > 1 with custom component

### ISSUE THREAD

**Issue by mglowacki100** [explosion/spaCy#11413]
I've pipeline that works perfectly fine when ` nlp.pipe(texts, n_process=1)`, but throws an error when I set `n_process` to 2 or more:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-85ad8fd456ac> in <module>
     10     docs = nlp.pipe(texts, n_process=2)
     11     with open("FIN.txt", "w", encoding="utf-8") as f:
---> 12       f.write("\n".join(map(str, docs)))

2 frames
/usr/local/lib/python3.7/dist-packages/spacy/language.py in pipe(self, texts, as_tuples, batch_size, disable, component_cfg, n_process)
   1581             for pipe in pipes:
   1582                 docs = pipe(docs)
-> 1583         for doc in docs:
   1584             yield doc
   1585 

/usr/local/lib/python3.7/dist-packages/spacy/language.py in _multiprocessing_pipe(self, texts, pipes, n_process, batch_size)
   1665                     error = srsly.msgpack_loads(byte_error)
   1666                     self.default_error_handler(
-> 1667                         None, None, None, ValueError(Errors.E871.format(error=error))
   1668                     )
   1669                 if i % batch_size == 0:

/usr/local/lib/python3.7/dist-packages/spacy/util.py in raise_error(proc_name, proc, docs, e)
   1656 
   1657 def raise_error(proc_name, proc, docs, e):
-> 1658     raise e
   1659 
   1660 

ValueError: [E871] Error encountered in nlp.pipe with multiprocessing:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/spacy/language.py", line 2263, in _apply_pipes
    byte_docs = [(doc.to_bytes(), doc._context, None) for doc in docs]
  File "/usr/local/lib/python3.7/dist-packages/spacy/language.py", line 2263, in <listcomp>
    byte_docs = [(doc.to_bytes(), doc._context, None) for doc in docs]
AttributeError: 'str' object has no attribute 'to_bytes'
```
Here is pipeline:
```
import spacy

@spacy.Language.component(name="represent_doc")
def represent_doc(doc: spacy.tokens.Doc.doc) -> str:
    clean_sents = (
       " ".join(str(tok) for tok in sent if not tok.is_space) #instead of str(tok) it could be function(tok) that also returns str
       for sent in doc.sents
       if sent.text.strip()
    )
    return " ".join(clean_sents) if clean_sents else ""

if __name__=="__main__":
    texts = ["Apple is looking at buying U.K. startup for $1 billion",
             "dog cat banana afskfsd",
             "Apple is looking at buying U.K. startup for $1 billion. I like salty fries and hamburgers.",
             "Fast food tastes very good.",
             ]

    nlp = spacy.load("en_core_web_sm")
    nlp.add_pipe("represent_doc")
    docs = nlp.pipe(texts, n_process=1) # if n_process=2 throw an error
    with open("FIN.txt", "w", encoding="utf-8") as f:
      f.write("\n".join(map(str, docs)))

```

Here is a gist with google colab to reproduce it:
https://colab.research.google.com/gist/mglowacki100/e516a0368cc965951a16f03718fb3df6/spacy_issue.ipynb#scrollTo=AxkeSDticXFo

Note, this is a simplified pipeline just to reproduce issue. Spacy 3.4.1, problem occurs on Linux, Windows.

I'm not sure if this is a real bug or wrong usage. I've found workaround, use `nlp.pipe(texts, n_process=1)` and `multiprocessing` library, but it'd be great to avoid it.

**Comment by adrianeboyd** [comment]
This isn't a bug, but the behavior and error message are unclear. Pipeline components need to always have the signature `Doc -> Doc`, so returning a string instead isn't supported.

We have a check for `-> None`, since it's common to forget to return the doc in a custom component, but this should really be extended to check anything non-`Doc`.

**Comment by mglowacki100** [comment]
@adrianeboyd Thanks for fast reply and explanation. Yes, it is confusing especially that with n_process=1 it works. I've noticed one thing for my full pipeline, when I removed `represent_doc` from `nlp.pipe` and added it as just regular function, speed improved almost x2.
