### ISSUE TITLE
ValueError: [E1042] Function was called with `enable`=['tagger', 'lemmatizer'] and `disable`=['senter'] but these arguments are conflicting.

### ISSUE THREAD

**Issue by rbracco** [explosion/spaCy#11443]
I am trying to load "en_core_web_sm" and only enable the tagger and lemmatizer following [the docs](https://spacy.io/usage/processing-pipelines#disabling) but I get the stack trace included below. I am not disabling 'senter' and adding 'senter' as an argument to enable, and/or passing `disable=[]` both fail to fix the problem. 

```
File "/home/rob/code/text-corpus/parsers/tagger.py", line 14, in __init__
    self.tagger = spacy.load("en_core_web_sm", enable=["tagger", "lemmatizer"])
  File "/home/rob/code/text-corpus/.venv/lib/python3.8/site-packages/spacy/__init__.py", line 54, in load
    return util.load_model(
  File "/home/rob/code/text-corpus/.venv/lib/python3.8/site-packages/spacy/util.py", line 429, in load_model
    return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
  File "/home/rob/code/text-corpus/.venv/lib/python3.8/site-packages/spacy/util.py", line 465, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, enable=enable, exclude=exclude, config=config)  # type: ignore[attr-defined]
  File "/home/rob/code/text-corpus/.venv/lib/python3.8/site-packages/en_core_web_sm/__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/rob/code/text-corpus/.venv/lib/python3.8/site-packages/spacy/util.py", line 646, in load_model_from_init_py
    return load_model_from_path(
  File "/home/rob/code/text-corpus/.venv/lib/python3.8/site-packages/spacy/util.py", line 503, in load_model_from_path
    nlp = load_model_from_config(
  File "/home/rob/code/text-corpus/.venv/lib/python3.8/site-packages/spacy/util.py", line 551, in load_model_from_config
    nlp = lang_cls.from_config(
  File "/home/rob/code/text-corpus/.venv/lib/python3.8/site-packages/spacy/language.py", line 1869, in from_config
    disabled_pipes = cls._resolve_component_status(
  File "/home/rob/code/text-corpus/.venv/lib/python3.8/site-packages/spacy/language.py", line 2052, in _resolve_component_status
    raise ValueError(
ValueError: [E1042] Function was called with `enable`=['tagger', 'lemmatizer'] and `disable`=['senter'] but these arguments are conflicting.
```

I also found this in the docs when trying to resolve the issue.
![image](https://user-images.githubusercontent.com/47190785/188646701-57a1f3dc-00c1-4ae5-9fa4-5e483ae477a0.png)

## How to reproduce the behaviour
Calling `spacy.load("en_core_web_sm", enable=["tagger", "lemmatizer"])` in spaCy 3.4.1

## Your Environment

Ubuntu 20.04
Python 3.8.10
Spacy 3.4.1

**Comment by tomaarsen** [comment]
I can reproduce this with the following too:
```python
spacy.load("en_core_web_sm", enable=["senter"])
```

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "[sic]\scripts\pick_high_fidelity_sentence.py", line 25, in <module>
    nlp = spacy.load("en_core_web_sm", enable=["senter"])
  File "[sic]\.env310\lib\site-packages\spacy\__init__.py", line 54, in load
    return util.load_model(
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 429, in load_model
    return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 465, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, enable=enable, exclude=exclude, config=config)  # type: ignore[attr-defined]
  File "[sic]\.env310\lib\site-packages\en_core_web_sm\__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 646, in load_model_from_init_py
    return load_model_from_path(
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 503, in load_model_from_path
    nlp = load_model_from_config(
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 551, in load_model_from_config
    nlp = lang_cls.from_config(
  File "[sic]\.env310\lib\site-packages\spacy\language.py", line 1869, in from_config
    disabled_pipes = cls._resolve_component_status(
  File "[sic]\.env310\lib\site-packages\spacy\language.py", line 2052, in _resolve_component_status
    raise ValueError(
ValueError: [E1042] Function was called with `enable`=['senter'] and `disable`=['senter'] but these arguments are conflicting.
```
</details>


```python
spacy.load("en_core_web_sm", enable=["a"])
```

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "[sic]\scripts\pick_high_fidelity_sentence.py", line 25, in <module>
    nlp = spacy.load("en_core_web_sm", enable=["a"])
  File "[sic]\.env310\lib\site-packages\spacy\__init__.py", line 54, in load
    return util.load_model(
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 429, in load_model
    return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 465, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, enable=enable, exclude=exclude, config=config)  # type: ignore[attr-defined]
  File "[sic]\.env310\lib\site-packages\en_core_web_sm\__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 646, in load_model_from_init_py
    return load_model_from_path(
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 503, in load_model_from_path
    nlp = load_model_from_config(
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 551, in load_model_from_config
    nlp = lang_cls.from_config(
  File "[sic]\.env310\lib\site-packages\spacy\language.py", line 1869, in from_config
    disabled_pipes = cls._resolve_component_status(
  File "[sic]\.env310\lib\site-packages\spacy\language.py", line 2052, in _resolve_component_status
    raise ValueError(
ValueError: [E1042] Function was called with `enable`=['a'] and `disable`=['senter'] but these arguments are conflicting.
```
</details>


```python
spacy.load("en_core_web_sm", enable=[""])
```

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "[sic]\scripts\pick_high_fidelity_sentence.py", line 25, in <module>
    nlp = spacy.load("en_core_web_sm", enable=[""])
  File "[sic]\.env310\lib\site-packages\spacy\__init__.py", line 54, in load
    return util.load_model(
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 429, in load_model
    return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 465, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, enable=enable, exclude=exclude, config=config)  # type: ignore[attr-defined]
  File "[sic]\.env310\lib\site-packages\en_core_web_sm\__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 646, in load_model_from_init_py
    return load_model_from_path(
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 503, in load_model_from_path
    nlp = load_model_from_config(
  File "[sic]\.env310\lib\site-packages\spacy\util.py", line 551, in load_model_from_config
    nlp = lang_cls.from_config(
  File "[sic]\.env310\lib\site-packages\spacy\language.py", line 1869, in from_config
    disabled_pipes = cls._resolve_component_status(
  File "[sic]\.env310\lib\site-packages\spacy\language.py", line 2052, in _resolve_component_status
    raise ValueError(
ValueError: [E1042] Function was called with `enable`=[''] and `disable`=['senter'] but these arguments are conflicting.
```
</details>

**Comment by rmitsch** [comment]
Hi @rbracco and @tomaarsen, thanks for reporting this! While this is not a bug, we see how this behavior / the error message is confusing. We are thinking about how to improve on this and will keep you in the loop here.

**Comment by rmitsch** [comment]
A solution for now is to override the `disabled` field in the config:
```python
nlp = spacy.load("en_core_web_sm", enable=["tagger", "lemmatizer"], config={"nlp": {"disabled": []}})
```

**Comment by adrianeboyd** [comment]
A few extra details related to `en_core_web_sm`, which are separate from the concrete `enable` behavior:

You need to additionally enable `tok2vec` for `tagger` and `attribute_ruler` for `lemmatizer` for the components to work in the provided v3 English pipelines.

See: https://spacy.io/models#design

**Comment by rbracco** [comment]
Thank you @rmitsch and @adrianeboyd for the feedback and guidance. I've got it working now.
