### ISSUE TITLE
Transformer component can't be frozen

### ISSUE THREAD

**Issue by polm** [explosion/spaCy#11547]
## How to reproduce the behaviour

If you add a Transformer to `frozen_components` it doesn't work, instead once training starts you get an error like `ValueError: Cannot get dimension 'nO' for model 'transformer-listener': value unset`. Example of detailed error output using the `textcat_goemotions` project:

```
=========================== Initializing pipeline ===========================
[2022-09-28 13:31:37,100] [INFO] Set up nlp object from config
[2022-09-28 13:31:37,109] [INFO] Pipeline: ['transformer', 'textcat']
[2022-09-28 13:31:37,111] [INFO] Created vocabulary
[2022-09-28 13:31:37,112] [INFO] Finished initializing nlp object
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/pool/code/spacy/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/mnt/pool/code/spacy/spacy/cli/_util.py", line 71, in setup_cli
    command(prog_name=COMMAND)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/mnt/pool/code/spacy/spacy/cli/train.py", line 45, in train_cli
    train(config_path, output_path, use_gpu=use_gpu, overrides=overrides)
  File "/mnt/pool/code/spacy/spacy/cli/train.py", line 72, in train
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/mnt/pool/code/spacy/spacy/training/initialize.py", line 84, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/mnt/pool/code/spacy/spacy/language.py", line 1317, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "/mnt/pool/code/spacy/spacy/pipeline/textcat_multilabel.py", line 198, in initialize
    self.model.initialize(X=doc_sample, Y=label_sample)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/model.py", line 299, in initialize
    self.init(self, X=X, Y=Y)
File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/layers/chain.py", line 88, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/model.py", line 299, in initialize
    self.init(self, X=X, Y=Y)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/layers/chain.py", line 88, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/model.py", line 299, in initialize
    self.init(self, X=X, Y=Y)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/layers/chain.py", line 88, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/model.py", line 299, in initialize
    self.init(self, X=X, Y=Y)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/layers/chain.py", line 88, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/model.py", line 299, in initialize
    self.init(self, X=X, Y=Y)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/layers/chain.py", line 92, in init
    curr_input = layer.predict(curr_input)
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/model.py", line 315, in predict
    return self._func(self, X, is_train=False)[0]
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/spacy_transformers/layers/listener.py", line 64, in forward
    width = model.get_dim("nO")
  File "/mnt/pool/work/spacy/env/lib/python3.10/site-packages/thinc/model.py", line 175, in get_dim
    raise ValueError(err)
ValueError: Cannot get dimension 'nO' for model 'transformer-listener': value unset
```

This has also come up in #10939, #11411, #11522, and maybe some other Discussions. 

For now the best workaround is to set `grad_factor` to 0, which disables weight updates, but doesn't skip the backprop step. 

## Your Environment

- **spaCy version:** 3.4.1
- **spacy-transformers version:** 1.1.8
- **Platform:** Linux-5.19.7-arch1-1-x86_64-with-glibc2.36
- **Python version:** 3.10.7
- **Pipelines:** fi_core_news_sm (3.4.0), en_core_web_md (3.4.0), es_core_news_sm (3.4.0), en_core_web_sm (3.4.0), ja_core_news_sm (3.4.0), fr_core_news_sm (3.4.0), en_core_web_trf (3.4.0), nl_core_news_sm (3.4.0), nb_core_news_sm (3.4.0), en_vectors_floret_md (0.0.1), de_core_news_sm (3.4.0), en_core_web_lg (3.4.0), ko_core_news_sm (3.4.0)

**Comment by raoulfasel93** [comment]
Is this still a problem? I read the following in the release notes of 3.5.0:

![image](https://user-images.githubusercontent.com/73660706/230621895-a705d05a-f090-4981-a53b-9be9664e6c63.png)

However when I generate a spacy config file using:

**Comment by adrianeboyd** [comment]
This is a separate issue from this bug report.

If the `transformer` component is in `frozen_components`, it needs to have been initialized in another pipeline and then loaded with `source` rather than `factory` in your current config. You can't configure a new `transformer` with `factory = "transformer"` and immediately freeze it because it hasn't been initialized yet.

I can see what you're trying to do, though, although I suspect that the `textcat` component won't perform very well if you don't fine-tune the `transformer` component, too.

So this is more of a hassle than it should be because all the CLI tools are designed for the case where you're fine-tuning the transformer, but I can describe a workaround.

You can assemble a pipeline just with the transformer and then source from that. Create `transformer.cfg` as a copy of the original `textcat.cfg` (no frozen or annotating components) but remove the `[components.textcat]` blocks and remove `textcat` from `[nlp.pipeline]`. Then assemble to initialize the transformer:

```shell
spacy assemble transformer.cfg /path/to/initialized_trf
```

In your `textcat.cfg`, edit `[components.transformer]` to remove all settings except for:

```ini
[components.transformer]
source = "/path/to/initialized_trf"
```

and add `transformer` to frozen and annotating components.

Then train as before:

```shell
spacy train textcat.cfg ...
```

I suspect that the performance will drop a lot, but it's useful to try this out and see what the differences are.
