### ISSUE TITLE
got TypeError when using model command to Setting up a model directory 

### ISSUE THREAD

**Issue by gispk47** [explosion/spaCy#1162]
i use the command like this:

 python3 -m spacy model zh /data/QA/output freq_word_spacy.txt out-c500-p1.out/paths vectors.bin
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/spacy/__main__.py", line 133, in <module>
    plac.Interpreter.call(CLI)
  File "/usr/local/lib/python3.5/dist-packages/plac_ext.py", line 1142, in call
    print(out)
  File "/usr/local/lib/python3.5/dist-packages/plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "/usr/local/lib/python3.5/dist-packages/plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "/usr/local/lib/python3.5/dist-packages/plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "/usr/local/lib/python3.5/dist-packages/plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "/usr/local/lib/python3.5/dist-packages/plac_ext.py", line 53, in raise_
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "/usr/local/lib/python3.5/dist-packages/plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "/usr/local/lib/python3.5/dist-packages/plac_ext.py", line 49, in raise_
    exc = tp(value)
TypeError: function takes exactly 5 arguments (1 given)
* Operating System: Linux-3.10.0-327.el7.x86_64-x86_64-with-debian-9.0
* Python Version Used: 3.5.3
* spaCy Version Used: 1.8.2
* Environment Information:

**Comment by ines** [comment]
Hmm interesting – I haven't seen this error before. This also looks more like an issues with plac and how the command-line arguments are interpreted, than with the underlying function itself.

Will have to test this and look into what might be causing this problem!

**Comment by gispk47** [comment]
yes it is,i remove the plac part and it works

**Comment by trungtv** [comment]
Hey @gispk47, 
Could you show me what you removed to make it works?
