### ISSUE TITLE
Since 3.4.2 doc.to_json(['noun_chunks']) does not work anymore

### ISSUE THREAD

**Issue by acassaignemondeca** [explosion/spaCy#11688]
## How to reproduce the behaviour
This code works in 3.4.1 but not in 3.4.2:

```
import spacy
from spacy.tokens import Doc
np_getter = lambda doc: [{'start': chunk.start, 'end': chunk.end} for chunk in doc.noun_chunks]
Doc.set_extension("noun_chunks", getter=np_getter, force=True)
nlp = spacy.load("en_core_web_trf")
doc = nlp("I like New York")
doc._.noun_chunks
doc.to_json(['noun_chunks'])
```

In 3.4.2, error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spacy/tokens/doc.pyx", line 1703, in spacy.tokens.doc.Doc.to_json
ValueError: [E106] Can't find `doc._.noun_chunks` attribute specified in the underscore settings: ['noun_chunks']
```

Related to commit: Fix multiple entries per custom extension in doc json #11551

Thank you

**Comment by polm** [comment]
Thanks for the report, that does look like a bug! We'll be right on fixing it.
