### ISSUE TITLE
Spacy 2.3.4, spacy.gold.GoldParse.__init__ 'Float' has no len()

### ISSUE THREAD

**Issue by pitmanm4** [explosion/spaCy#11689]
## How to reproduce the behaviour
for i in range(n_iter):
        losses = {}
        batches = minibatch(train_data, size=compounding(4., 32., 1.001))
        for batch in batches:
            texts, annotations = zip(*batch)
            nlp.update(texts, annotations, sgd=optimizer, drop=0.2,
                       losses=losses)

Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/spacy_doc_recognition_conv.py", line 198, in <module>
    nlp.update(texts, annotations, sgd=optimizer, drop=0.2,
  File "/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/py39/lib/python3.9/site-packages/spacy/language.py", line 510, in update
    docs, golds = self._format_docs_and_golds(docs, golds)
  File "/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/py39/lib/python3.9/site-packages/spacy/language.py", line 482, in _format_docs_and_golds
    gold = GoldParse(doc, **gold)
  File "gold.pyx", line 648, in spacy.gold.GoldParse.__init__
TypeError: object of type 'float' has no len()

## Your Environment
Python 3.9
Spacy 2.3.4

**Comment by adrianeboyd** [comment]
Without more information about what's in `train_data` it's hard to know what's going on for sure, but my first guess is that the training data isn't in the expected format. You can find some example scripts here for different v2 components: https://github.com/explosion/spaCy/tree/v2.x/examples/training

In general we would strongly recommend upgrading to v3, where there are many improvements in training and the training data format.
