### ISSUE TITLE
`InvalidRequirement` exception in coref example project

### ISSUE THREAD

**Issue by itssimon** [explosion/spaCy#11733]
This is an issue in the [experimental coref project](https://github.com/explosion/projects/tree/v3/experimental/coref). If this is not the right place to capture issues regarding that repository, please let me know.

Running `spacy project run all` within that project as described in the README leads to the following error regarding the `requirements.txt`.

```
Traceback (most recent call last):
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pkg_resources._vendor.pyparsing.exceptions.ParseException: Expected string_end, found ':'  (at char 5), (line:1, col:6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jovyan/.envs/clinex/bin/spacy", line 8, in <module>
    sys.exit(setup_cli())
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/spacy/cli/_util.py", line 71, in setup_cli
    command(prog_name=COMMAND)
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/spacy/cli/project/run.py", line 45, in project_run_cli
    project_run(project_dir, subcommand, overrides=overrides, force=force, dry=dry)
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/spacy/cli/project/run.py", line 81, in project_run
    _check_requirements([req.replace("\n", "") for req in requirements_file])
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/spacy/cli/project/run.py", line 336, in _check_requirements
    pkg_resources.require(req)
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/pkg_resources/__init__.py", line 751, in resolve
    requirements = list(requirements)[::-1]
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3102, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/jovyan/.envs/clinex/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'://githu'": Expected string_end
```

This can be resolved by commenting out the line pointing to the URL of the `en_core_web_lg` model and installing that model manually first.

## How to reproduce the behaviour
```shell
git clone https://github.com/explosion/projects.git
cd projects/experimental/coref
# Prepare CoNLL 2012 data...
spacy project run all
```

## Your Environment
- **spaCy version:** 3.4.2
- **Platform:** Ubuntu 22.04
- **Python version:** 3.10.6
- **Pipelines:** en_coreference_web_trf (3.4.0a0), en_core_web_md (3.4.1)

**Comment by rmitsch** [comment]
Thanks for reporting this, @itssimon! Should be fixed by https://github.com/explosion/projects/pull/146. If it still doesn't work for you, feel free to reopen this.
