### ISSUE TITLE
Race condition when using select_pipes in multiple threads

### ISSUE THREAD

**Issue by johnmccain** [explosion/spaCy#11904]
When using a single Language object across multiple threads and using `select_pipes` to enable & disable pipeline components, you can end up with a race condition where pipeline modifications from one thread overwrite those in another thread.

This race condition can be avoided by creating multiple instances of the Language object or by wrapping pipeline modifications in a lock, but those options either require holding multiple copies of the model in memory or incurring performance penalties due to the lock.

Is the `select_pipes` context manager expected to be thread safe? If not, should this be a feature request for a thread-safe method of modifying pipelines or running certain components of pipelines?

## How to reproduce the behaviour
```python
import threading
import time
import spacy

nlp = spacy.load("en_core_web_sm")

def thread1():
    for _ in range(100):
        with nlp.select_pipes(enable=["tokenizer"]):
            time.sleep(0.01)
            doc = nlp("This is a sentence.")

def thread2():
    for _ in range(100):
        with nlp.select_pipes(enable=["parser"]):
            time.sleep(0.01)
            doc = nlp("This is a sentence.")
            noun_chunks = list(doc.noun_chunks)

t1 = threading.Thread(target=thread1)
t2 = threading.Thread(target=thread2)
t1.start()
t2.start()
t1.join()
t2.join()

```

output:

```
Exception in thread Thread-2 (thread2):
Traceback (most recent call last):
  File "/Users/johnmccain/.pyenv/versions/3.10.4/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Users/johnmccain/.pyenv/versions/3.10.4/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/johnmccain/Documents/Repos/spacy-select-pipe-race-condition/spacy-select-pipe-race-condition.py", line 18, in thread2
    noun_chunks = list(doc.noun_chunks)
  File "spacy/tokens/doc.pyx", line 875, in noun_chunks
  File "/Users/johnmccain/Documents/Repos/spacy-select-pipe-race-condition/venv/lib/python3.10/site-packages/spacy/lang/en/syntax_iterators.py", line 26, in noun_chunks
    raise ValueError(Errors.E029)
ValueError: [E029] `noun_chunks` requires the dependency parse, which requires a statistical model to be installed and loaded. For more info, see the documentation:
https://spacy.io/usage/models
```

## Your Environment
- **spaCy version:** 3.4.3
- **Platform:** macOS-12.6-x86_64-i386-64bit
- **Python version:** 3.10.4
- **Pipelines:** en_core_web_sm (3.4.1)

**Comment by polm** [comment]
Thanks for making us aware of this and providing an example. We would not generally expect methods on the Language class like this to be thread-safe, so this isn't exactly surprising, though it is unfortunate. We can treat it as a feature request. 

To help us understand the use case better, can you explain why you're doing things this way rather than using, say, multiple `nlp` objects?
