### ISSUE TITLE
Getting an error on executing line nlp = spacy.load('en')

### ISSUE THREAD

**Issue by mushtaque87** [explosion/spaCy#1194]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/philips/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "/Users/philips/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)
  File "/Users/philips/Documents/python_ds/NLP/spacy_NameEntity.py", line 27, in <module>
    nlp = spacy.load('en')
  File "/Users/philips/anaconda/lib/python2.7/site-packages/spacy/__init__.py", line 40, in load
    return cls(**overrides)
  File "/Users/philips/anaconda/lib/python2.7/site-packages/spacy/en/__init__.py", line 34, in __init__
    Language.__init__(self, **overrides)
  File "/Users/philips/anaconda/lib/python2.7/site-packages/spacy/language.py", line 273, in __init__
    if 'tokenizer' not in overrides \
  File "/Users/philips/anaconda/lib/python2.7/site-packages/spacy/language.py", line 63, in create_tokenizer
    prefix_search  = util.compile_prefix_regex(cls.prefixes).search
  File "/Users/philips/anaconda/lib/python2.7/site-packages/spacy/util.py", line 65, in compile_prefix_regex
    return re.compile(expression)
  File "/Users/philips/anaconda/lib/python2.7/site-packages/regex.py", line 345, in compile
    return _compile(pattern, flags, kwargs)
  File "/Users/philips/anaconda/lib/python2.7/site-packages/regex.py", line 425, in _compile
    pattern_locale = _getlocale()[1]
  File "/Users/philips/anaconda/lib/python2.7/locale.py", line 564, in getlocale
    return _parse_localename(localename)
  File "/Users/philips/anaconda/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

## Your Environment

* Operating System: OsX -64bit
* Python Version Used: 2.7
* spaCy Version Used: spacy-1.8.2
* Environment Information:

**Comment by ValentinHolgado** [comment]
I had the same issue while downloading a model with the command `python -m spacy download es`

Adding `LC_ALL="es_AR.UTF-8"` to my environment variables fixed this error!
