### ISSUE TITLE
import spacy - NVRTCError: NVRTC_ERROR_INVALID_OPTION (5)

### ISSUE THREAD

**Issue by videru** [explosion/spaCy#12068]
(base) PS C:\Windows\system32> python
Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
Traceback (most recent call last):
  File "e:\ProgramData\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 681, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 139, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 151, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 67, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_INVALID_OPTION (5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\deru\AppData\Roaming\Python\Python39\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "C:\Users\deru\AppData\Roaming\Python\Python39\site-packages\spacy\errors.py", line 2, in <module>
    from .compat import Literal
  File "C:\Users\deru\AppData\Roaming\Python\Python39\site-packages\spacy\compat.py", line 38, in <module>
    from thinc.api import Optimizer  # noqa: F401
  File "C:\Users\deru\AppData\Roaming\Python\Python39\site-packages\thinc\api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "C:\Users\deru\AppData\Roaming\Python\Python39\site-packages\thinc\initializers.py", line 4, in <module>
    from .backends import Ops
  File "C:\Users\deru\AppData\Roaming\Python\Python39\site-packages\thinc\backends\__init__.py", line 8, in <module>
    from .cupy_ops import CupyOps
  File "C:\Users\deru\AppData\Roaming\Python\Python39\site-packages\thinc\backends\cupy_ops.py", line 5, in <module>
    from . import _custom_kernels
  File "C:\Users\deru\AppData\Roaming\Python\Python39\site-packages\thinc\backends\_custom_kernels.py", line 83, in <module>
    clipped_linear_kernel_float = _get_kernel("clipped_linear<float>")
  File "C:\Users\deru\AppData\Roaming\Python\Python39\site-packages\thinc\backends\_custom_kernels.py", line 71, in _get_kernel
    return KERNELS.get_function(name)
  File "cupy\_core\raw.pyx", line 470, in cupy._core.raw.RawModule.get_function
  File "cupy\_core\raw.pyx", line 394, in cupy._core.raw.RawModule.module.__get__
  File "cupy\_core\raw.pyx", line 402, in cupy._core.raw.RawModule._module
  File "cupy\_util.pyx", line 67, in cupy._util.memoize.decorator.ret
  File "cupy\_core\raw.pyx", line 547, in cupy._core.raw._get_raw_module
  File "cupy\_core\core.pyx", line 2064, in cupy._core.core.compile_with_cache
  File "cupy\_core\core.pyx", line 2124, in cupy._core.core.compile_with_cache
  File "e:\ProgramData\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 488, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "e:\ProgramData\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 531, in _compile_with_cache_cuda
    base = _preprocess('', options, arch, backend)
  File "e:\ProgramData\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 420, in _preprocess
    result, _ = prog.compile(options)
  File "e:\ProgramData\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 698, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)

**Comment by shadeMe** [comment]
This appears to be an installation issue, so let's move this to the discussion forum.

The above error points to an incompatible or incomplete installation of the prerequisite nVidia CUDA libraries. More information on this and instructions to install the same can be found on the [CuPy website](https://docs.cupy.dev/en/stable/install.html). Please try again after performing a clean installation of the CUDA toolkit for Windows. It could also help to update your GPU drivers.
