### ISSUE TITLE
try to make a Chinese model data error:ValueError: malformed node or string

### ISSUE THREAD

**Issue by BenDerPan** [explosion/spaCy#1209]
I am trying to make a support for Chinese, and add a  Chinese data model ,follow the [instruction](https://spacy.io/docs/usage/adding-languages),I added the needed files as below:
![image](https://user-images.githubusercontent.com/10903567/28446437-4805784a-6dfd-11e7-8d15-fb2dff75d44b.png)

My frequency data [a part]:
![image](https://user-images.githubusercontent.com/10903567/28446275-4e1a9964-6dfc-11e7-83ca-a823763fe14f.png)
My cluster_data [a part]:
![image](https://user-images.githubusercontent.com/10903567/28446452-5b646180-6dfd-11e7-8afb-fc9b11e8ad83.png)

**Error output:**
Echos-MacBook-Pro:spacyDemo echo$ python3 -m spacy model zh ./output ES_WORD_FREQS.TXT paths 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spacy/__main__.py", line 133, in <module>
    plac.Interpreter.call(CLI)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 1142, in call
    print(out)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 53, in raise_
    raise exc.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 53, in raise_
    raise exc.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spacy/__main__.py", line 108, in model
    cli_model(lang, model_dir, freqs_data, clusters_data, vectors_data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spacy/cli/model.py", line 23, in model
    probs, oov_prob = read_probs(freqs_path)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spacy/cli/model.py", line 67, in read_probs
    word = literal_eval(key)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
**ValueError: malformed node or string**: <_ast.Name object at 0x106309208>

## Your Environment

* Operating System: Mac OS 10.12.5 
* Python Version Used: 3.5.3
* spaCy Version Used: 1.8.2

**Comment by honnibal** [comment]
This is a problem with the data format expected by the probabilities script. I made some hacky decisions on this because at the time I didn't foresee it being widely used.

In order to avoid escaping strings, the script expects that the string-content is the output of `repr(word)`. In Python 2 this would look something like this:

    20    1    u'the'

The `read_probs` script then calls the `literal_eval` function from Python's `ast` library on this, to get back the string. That's why you're getting an error: your string isn't quoted, and so it can't interpret the string.

**Comment by ines** [comment]
To add to @honnibal's solution above: spaCy v2.0 now also comes with a [`spacy vocab` command](https://spacy.io/api/cli#vocab) that helps you create the vocabulary from a lexicon.
