### ISSUE TITLE
Cannot import SpaCy for development 

### ISSUE THREAD

**Issue by oxymor0n** [explosion/spaCy#1218]
Hi all,

I'm trying to contribute to SpaCy, but I can't get my test runner to start. when I do `py.test spacy`, I keep getting the following traceback:

```
(spacy) william@William-Trans-Mac:~/Pager/projects/spacy$ py.test spacy
Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/3.5.2/envs/spacy/lib/python3.5/site-packages/_pytest/config.py", line 336, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/william/Pager/projects/spacy/spacy/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/3.5.2/envs/spacy/lib/python3.5/site-packages/_pytest/config.py", line 367, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/william/Pager/projects/spacy/spacy/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/3.5.2/envs/spacy/lib/python3.5/site-packages/_pytest/config.py", line 373, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/william/.pyenv/versions/3.5.2/envs/spacy/lib/python3.5/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/Users/william/Pager/projects/spacy/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/Users/william/Pager/projects/spacy/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/Users/william/Pager/projects/spacy/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/Users/william/Pager/projects/spacy/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/Users/william/Pager/projects/spacy/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ImportError: No module named 'spacy.gold'
ERROR: could not load /Users/william/Pager/projects/spacy/spacy/tests/conftest.py
```

In fact, it seems like I can't import spacy at all despite having set `export PYTHONPATH=$(pwd)`. When I try to do `python -m spacy`, I get a similar error:

```
(spacy) william@William-Trans-Mac:~/Pager/projects/spacy$ python -m spacy
Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/william/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/william/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/william/Pager/projects/spacy/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/Users/william/Pager/projects/spacy/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/Users/william/Pager/projects/spacy/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/Users/william/Pager/projects/spacy/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/Users/william/Pager/projects/spacy/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ImportError: No module named 'spacy.gold'
```

## Your Environment
* Operating System: macOS Sierra 10.12.5
* Python Version Used: 3.5.2
* spaCy Version Used: current master branch
* Environment Information: 
using `pyenv` version `20160726` to manage python runtime and virtualenv. Current virtualenv has the following installed:

```
(spacy) william@William-Trans-Mac:~/Pager/projects/spacy$ pip list
certifi (2017.4.17)
chardet (3.0.4)
cymem (1.31.2)
Cython (0.23.5)
cytoolz (0.8.2)
dill (0.2.7.1)
ftfy (4.4.3)
html5lib (1.0b8)
idna (2.5)
murmurhash (0.26.4)
numpy (1.13.1)
pathlib (1.0.1)
pip (9.0.1)
plac (0.9.6)
preshed (1.0.0)
py (1.4.34)
pytest (3.1.3)
regex (2017.7.11)
requests (2.18.1)
setuptools (20.10.1)
six (1.10.0)
termcolor (1.1.0)
thinc (6.5.2)
toolz (0.8.2)
tqdm (4.15.0)
ujson (1.35)
urllib3 (1.21.1)
wcwidth (0.1.7)
wrapt (1.10.10)
```

**Comment by ines** [comment]
This looks like the Cython didn't compile correctly! Did you install spaCy in development mode via `pip install -e .`? And does rebuilding from source help?

```bash
python setup.py build_ext --inplace
```

**Comment by oxymor0n** [comment]
doing `python setup.py build_ext --inplace` solved it. thanks!

**Comment by shramesh** [comment]
I ran it to the same issue and this helped me resolve it. Thanks :+1:
