### ISSUE TITLE
spacy==2.2.1 not installing

### ISSUE THREAD

**Issue by pradeepdev-1995** [explosion/spaCy#12197]
Can't install spacy==2.2.1 in python 3.9. It shows the following error
```
Collecting spacy==2.2.1
  Using cached spacy-2.2.1.tar.gz (5.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
          parsed = parse_requirement(requirement_string)
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
          raise ParserSyntaxError(
      pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
          spacy_lookups_data>=0.0.5<0.2.0
                            ~~~~~~~^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/home/10666855/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/10666855/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/10666855/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 200, in <module>
        File "<string>", line 190, in setup_package
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 78, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 874, in parse_config_files
          self._finalize_requires()
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 580, in _finalize_requires
          self._convert_extras_requirements()
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 595, in _convert_extras_requirements
          for r in _reqs.parse(v):
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3095, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "/tmp/pip-build-env-xrb1_27b/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
          spacy_lookups_data>=0.0.5<0.2.0
                            ~~~~~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

```

## How to reproduce the behaviour
pip3.9 install spacy==2.2.1

## Your Environment

* Operating System: Ubuntu 18.04.6
* Python Version Used: 3.9
* spaCy Version Used: 2.2.1

**Comment by polm** [comment]
Moving to discussions because this is installation-related...
