### ISSUE TITLE
Error textcat example

### ISSUE THREAD

**Issue by technicatisatio334455** [explosion/spaCy#1237]
When i'm running the text categorisation example (https://github.com/explosion/spaCy/blob/develop/examples/training/train_textcat.py) for spacy 2.0, latest alpha i get a "KeyError: 'textcat" on line 37. 

Traceback (most recent call last):
  File "spacy_tc_2.py", line 148, in <module>
    plac.call(main)
  File "~/anaconda/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "~/anaconda/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_textcat.py", line 136, in main
    dev_texts, dev_cats, n_iter=20)):
  File "train_textcat.py", line 37, in train_textcat
    yield losses['textcat'], scores
KeyError: 'textcat

## Your Environment
* Operating System: MacOs 10.12.5 (Sierra)
* Python Version Used: Python 3.6.1 :: Anaconda 4.4.0 (x86_64)
* spaCy Version Used: 2.0 Alpha 8
* Environment Information:

**Comment by honnibal** [comment]
Thanks for the report --- the example has now been updated for the latest nightly release (v2.0.0a16)
