### ISSUE TITLE
nlp.pipe does not work multithreaded on OSX M1

### ISSUE THREAD

**Issue by tianhuil** [explosion/spaCy#12585]
## How to reproduce the behaviour

It looks like `nlp.pipe` singled threaded works but `n_process=2` does not work.  This problem is on an M1 OSX machine.  Any thoughts on how to solve this?

Here is the code:
```py
# script/spacy_demo.py  
import spacy

texts = ["foo", "bar", "baz"]
nlp = spacy.load("en_core_web_sm")
list(nlp.pipe(texts, n_process=2))

```

Running it provides this:
```
$ poetry run python script/spacy_demo.py  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Volumes/Workspace/aerial/data/script/spacy_demo.py", line 5, in <module>
    list(nlp.pipe(texts, n_process=2))
  File "/Volumes/Workspace/aerial/data/.venv/lib/python3.9/site-packages/spacy/language.py", line 1574, in pipe
    for doc in docs:
  File "/Volumes/Workspace/aerial/data/.venv/lib/python3.9/site-packages/spacy/language.py", line 1640, in _multiprocessing_pipe
    proc.start()
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/tianhuili/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

## Your Environment

* Operating System: M1 OSX (Ventura 13.2.1)
* Python Version Used: Python 3.9.16
* spaCy Version Used: 3.5.2
* Environment Information:

**Comment by adrianeboyd** [comment]
The error message is a bit hard to understand, but it's trying to show you how you need to modify your script for use with multiprocessing:

```
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...                                           <- your code should go here

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

If you search for this error message you can find lots of examples on StackOverflow, etc.

**Comment by adrianeboyd** [comment]
Let me convert this to a discussion...
