### ISSUE TITLE
Downloading models fails with spacy >= 3.2.2

### ISSUE THREAD

**Issue by charlesmass2** [explosion/spaCy#12657]
## How to reproduce the behaviour

To reproduce the issue we had a docker container with the Dockerfile below.
The error happens when downloading models with spaCy, whether we use `python -m spacy download` or directly `spacy download`.
The error only happens with versions >= 3.2.2. To fix the issue, we are working with 3.2.1. 
<details>
<summary>Docker file</summary>

```
FROM python:3.8-slim

RUN apt-get update \
  && apt-get install -y build-essential python-dev git python3-pip \
  && pip3 install -U pip

# spacy
RUN pip install -U spacy \
  && pip uninstall click -y && pip install "click<8" \
  && python -m spacy download en_core_web_md

CMD ["sleep", "360000"]

EXPOSE 80
```
</details>

When building the container, the following error appears: `TypeError: issubclass() arg 1 must be a class`
<details>
<summary>Error and trace</summary>

```

#15 14.30 Traceback (most recent call last):
#15 14.30   File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
#15 14.30     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
#15 14.30   File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
#15 14.30     return _get_module_details(pkg_main_name, error)
#15 14.30   File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
#15 14.30     __import__(pkg_name)
#15 14.30   File "/usr/local/lib/python3.8/site-packages/spacy/__init__.py", line 14, in <module>
#15 14.30     from . import pipeline  # noqa: F401
#15 14.30   File "/usr/local/lib/python3.8/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
#15 14.30     from .attributeruler import AttributeRuler
#15 14.30   File "/usr/local/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
#15 14.30     from .pipe import Pipe
#15 14.30   File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
#15 14.30   File "spacy/vocab.pyx", line 1, in init spacy.vocab
#15 14.30   File "/usr/local/lib/python3.8/site-packages/spacy/tokens/__init__.py", line 1, in <module>
#15 14.30     from .doc import Doc
#15 14.30   File "spacy/tokens/doc.pyx", line 36, in init spacy.tokens.doc
#15 14.30   File "/usr/local/lib/python3.8/site-packages/spacy/schemas.py", line 250, in <module>
#15 14.30     class TokenPattern(BaseModel):
#15 14.30   File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
#15 14.30   File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
#15 14.30   File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
#15 14.30   File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
#15 14.30   File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
#15 14.30   File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
#15 14.30   File "/usr/local/lib/python3.8/typing.py", line 774, in __subclasscheck__
#15 14.30     return issubclass(cls, self.__origin__)
#15 14.30 TypeError: issubclass() arg 1 must be a class

```

</details>

The issue can also be reproduced with a simple Dockefile, such as:
<details>
<summary>Docker file</summary>

```
FROM python:3.9-slim

RUN apt-get update \
  && apt-get install -y build-essential python-dev git python3-pip \
  && pip3 install -U pip

# spacy
RUN pip install -U spacy

CMD ["sleep", "360000"]

EXPOSE 80
```

</details>

And when running `docker exec -it <container_name> bash`, the following command will fail : `spacy download en_core_web_md`

## Your Environment

* Operating System: Debian 11
* Python Version Used: 3.8 or 3.9
* spaCy Version Used: >= 3.2.2. Versions below seem to work fine
* Environment Information: Docker container

**Comment by adrianeboyd** [comment]
This appears to be a bug in Pydantic related to the new release of `typing_extensions` v4.6.0. We're hoping that there will be an upstream fix soon, you can follow this issue: https://github.com/pydantic/pydantic/issues/5821

In the meanwhile, I think you can add `typing_extensions<4.6.0` to your requirements as a workaround.

**Comment by klaudia-kantor** [comment]
I've added `typing-extensions = "4.5.0"` to my requirements and it works

**Comment by adrianeboyd** [comment]
Let me merge this with #12659 so we can keep the discussion in one issue.
