### ISSUE TITLE
Problems when trying to run or download spacy models on linux running python3.8

### ISSUE THREAD

**Issue by pedrovazpimenta** [explosion/spaCy#12663]
How to reproduce this error using Docker: 

```bash
docker run -it --name spacy_test ubuntu:20.04 bash
``` 
the container's terminal should be open, so now type:

```bash
apt-get update
apt-get install python3.8
apt-get install python3-pip
python3.8 -m pip install --upgrade pip
python3.8 -m pip install spacy
python3.8 -m spacy download en_core_web_md
``` 

then we see the following: 

``` 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/usr/local/lib/python3.8/dist-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "/usr/local/lib/python3.8/dist-packages/spacy/tokens/__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy/tokens/doc.pyx", line 36, in init spacy.tokens.doc
  File "/usr/local/lib/python3.8/dist-packages/spacy/schemas.py", line 250, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
``` 

I tried downgrading the spacy version, but I also got the same error just by running:

```python
import spacy
nlp = spacy.load("en_core_web_md")
``` 

I also tried the model en_core_web_lg and the result was the same.

**Comment by adrianeboyd** [comment]
This should now be resolved, please see #12659.
