### ISSUE TITLE
Error running older spaCy versions with Python 3.11

### ISSUE THREAD

**Issue by richardpaulhudson** [explosion/spaCy#12697]
A Coreferee user asked for Python 3.11 support; trying to add it I believe I have found a spaCy error when running older spaCy versions on Python 3.11.

## How to reproduce the behaviour
`python -m spacy download en_core_web_sm`

gives the error

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/richard/explosion/spacy/lib/python3.11/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richard/explosion/spacy/lib/python3.11/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/Users/richard/explosion/spacy/lib/python3.11/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "/Users/richard/explosion/spacy/lib/python3.11/site-packages/spacy/tokens/__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy/tokens/doc.pyx", line 36, in init spacy.tokens.doc
  File "/Users/richard/explosion/spacy/lib/python3.11/site-packages/spacy/schemas.py", line 157, in <module>
    class TokenPatternString(BaseModel):
  File "/Users/richard/explosion/spacy/lib/python3.11/site-packages/pydantic/main.py", line 369, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richard/explosion/spacy/lib/python3.11/site-packages/pydantic/utils.py", line 231, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 2721, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'in' is not a valid parameter name
```

## Your Environment
1)
* Operating System: macOS Ventura 13.4
* Python Version Used: 3.11.1
* spaCy Version Used: 3.3.3

2)
[On Github Actions](https://github.com/richardpaulhudson/coreferee/actions/runs/5178908374/jobs/9331028805) with Ubuntu 20.04

3)
Another user has [reported the same behaviour](https://stackoverflow.com/questions/75978880/spacy-python-package-no-longer-runs).

**Comment by adrianeboyd** [comment]
Hi Richard! Yes, the first version of spacy that supports python 3.11 is spacy v3.4.2. Given a number of changes in `thinc` and `pydantic`, it would be difficult to extend python 3.11 support to earlier minor versions.

**Comment by richardpaulhudson** [comment]
OK, thanks, that makes sense!
