### ISSUE TITLE
Spacy on m1 pro chip doesn't work

### ISSUE THREAD

**Issue by jquintero-02** [explosion/spaCy#12705]
### Discussed in https://github.com/explosion/spaCy/discussions/10683

<div type='discussions-op-text'>

<sup>Originally posted by **maroxtn** April 20, 2022</sup>
When following the instructions of installing Spacy on the m1 pro chip, I got an error. 

## How to reproduce the behaviour

    pip3 install -U pip setuptools wheel
    pip3 install -U 'spacy[apple]'
    python3 -m spacy download en_core_web_sm

When running the third command, I get this error: 
```
 Traceback (most recent call last):
  File "/Users/jacobquintero/Desktop/586/NLP/Diversity/SPACY/test.py", line 7, in <module>
    import spacy
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spacy/errors.py", line 2, in <module>
    from .compat import Literal
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spacy/compat.py", line 38, in <module>
    from thinc.api import Optimizer  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thinc/api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thinc/initializers.py", line 4, in <module>
    from .backends import Ops
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thinc/backends/__init__.py", line 7, in <module>
    from .ops import Ops
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thinc/backends/ops.py", line 16, in <module>
    from .cblas import CBlas
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thinc/backends/cblas.cpython-39-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thinc/backends/cblas.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thinc/backends/cblas.cpython-39-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thinc/backends/cblas.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

## Your Environment

* Operating System: MacOs 13.4 (22F66)
* Python Version Used: 3.9.10
* spaCy Version Used: latest
* Environment Information: m1 MacBook air
</div>

**Comment by adrianeboyd** [comment]
Please don't open duplicate issues/threads. Let's keep this in the installation section of the discussion board: #10683
