### ISSUE TITLE
Installing spacy-nightly (10a) in Windows

### ISSUE THREAD

**Issue by LucasLLC** [explosion/spaCy#1286]
Running `pip install spacy-nightly` fails. The error appears to be in the setup.py script for thinc, which eventually produces the error below. I am running anaconda with python 2.7 on a Windows 10 machine. 

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\lucas\appdata\local\temp\pip-build-bxrui8\thinc\setup.py", line 308, in <module>
        setup_package()
      File "c:\users\lucas\appdata\local\temp\pip-build-bxrui8\thinc\setup.py", line 303, in setup_package
        'build_ext': build_ext_subclass},
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\site-packages\setuptools-27.2.0-py2.7.egg\setuptools\command\install.py", line 61, in run
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "c:\users\lucas\appdata\local\temp\pip-build-bxrui8\thinc\setup.py", line 116, in build_extensions
        build_ext.build_extensions(self)
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self.build_extension(ext)
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\command\build_ext.py", line 499, in build_extension
        depends=ext.depends)
      File "C:\Program Files\Anaconda2\envs\spacy_alpha\lib\distutils\msvc9compiler.py", line 546, in compile
        extra_postargs)
    TypeError: can only concatenate list (not "dict") to list

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by LucasLLC** [comment]
Was able to reproduce bug in Ubuntu 12.04

**Comment by honnibal** [comment]
Thanks.

There's some difficult spaghetti in the thinc setup.py to try to compile the CUDA extensions. I'm trying to figure out what path things take, but it's tricky because I don't have a Windows machine to debug things, and there's no real API for this in distutils.

**Comment by LucasLLC** [comment]
Anything I could do to help?

**Comment by honnibal** [comment]
Sure! If you have the time and energy, you could clone the repo and try to build it:

    git clone https://github.com/explosion/thinc && cd thinc
    pip install -e .

You'll likely find your error. Then you might edit the `setup.py` file. You see how the `msvc` entry is mapping to a dict, keyed by `gcc` and `nvcc` here? https://github.com/explosion/thinc/blob/master/setup.py#L48

That value is getting passed through, when something should be stepping in and passing forward only the appropriate list value. You can likely hard-code a fix for yourself by just passing forward only the list you care about. You could then build a version of your fixed library with `python setup.py sdist`, which will give you an artifact you can pip install into your project.

**Comment by honnibal** [comment]
Just pushed Thinc v6.8.1 which should fix this installation error. GPU usage on Windows might still have problems.

I've now got Appveyor set up for spaCy and Thinc. This should greatly improve Windows stability, and make it easy to ship wheels for all platforms.
