### ISSUE TITLE
xx_ent_wiki_sm AttributeError

### ISSUE THREAD

**Issue by AndreaPivetta** [explosion/spaCy#1295]
This is the first time in ages I use `Python` and the first time I use `spacy`.
I'm trying to use `xx_ent_wiki_sm` to try italian support.

My code:
```
import xx_ent_wiki_sm as xx

nlp = xx.load()
doc = nlp(u'Capisci quello che dico?')
```

But I keep getting an error: `AttributeError: 'FunctionLayer' object has no attribute 'W'`

## Your Environment
* **Python version:** 3.5.2
* **Models:** en_core_web_sm
* **spaCy version:** 2.0.0a11
* **Platform:** Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by AndreaPivetta** [comment]
Same code but with `import en_core_web_sm as xx` works

**Comment by bittlingmayer** [comment]
I see this issue with `import en_core_web_sm` too.

**Comment by bittlingmayer** [comment]
Full stack trace:

```
>>> en = spacy.load("en_core_web_sm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../env/lib/python3.5/site-packages/spacy/__init__.py", line 13, in load
    return util.load_model(name, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 103, in load_model
    return load_model_from_link(name, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 122, in load_model_from_link
    return cls.load(**overrides)
  File ".../env/lib/python3.5/site-packages/spacy/data/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 155, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 138, in load_model_from_path
    return nlp.from_disk(model_path)
  File ".../env/lib/python3.5/site-packages/spacy/language.py", line 541, in from_disk
    util.from_disk(path, deserializers, exclude)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 483, in from_disk
    reader(path / key)
  File ".../env/lib/python3.5/site-packages/spacy/language.py", line 537, in <lambda>
    deserializers[proc.name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "spacy/pipeline.pyx", line 170, in spacy.pipeline.BaseThincComponent.from_disk (spacy/pipeline.cpp:11298)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 483, in from_disk
    reader(path / key)
  File "spacy/pipeline.pyx", line 163, in spacy.pipeline.BaseThincComponent.from_disk.load_model (spacy/pipeline.cpp:10856)
  File ".../env/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 351, in from_bytes
    dest = getattr(layer, name)
AttributeError: 'FunctionLayer' object has no attribute 'W'
```

**Comment by ines** [comment]
Copying over my reply from #1295:

> This error indicates that the model was trained with a different version of spaCy – in this case, it looks like you're using the latest `v2.0.0a13` with an older version of the English model (and spaCy skips the compatibility check, since you're running the download command with the `--direct` flag). The downloader should now be all wired up correctly in v2.0 alpha, so you should simply be able to download the compatible model via `spacy download en`.

> See the [alpha release notes](https://github.com/explosion/spaCy/releases/tag/v2.0.0-alpha) for an overview of all available models and their compatible spaCy versions. Sorry about the frequent updates and different model versions – but we've been making improvements to spaCy and the models pretty quickly over the past few weeks, and we want to make sure you can use the latest models, especially `en_core_web_sm-2.0.0a2`+, as it comes with a nice improvement in accuracy.

Important note about the `xx` model: We haven't yet trained a new version compatible with `2.0.0a10`+, so you'd have to use `2.0.0a9` to use it. (We're trying out a few new ideas for the updated `xx`, since the first one was very experimental and the accuracy hasn't been *that* convincing.)
