### ISSUE TITLE
Language cannot be deepcopied

### ISSUE THREAD

**Issue by jnothman** [explosion/spaCy#1302]
```python
>>> import spacy
>>> nlp = spacy.load('en')
import copy
>>> import copy
>>> copy.deepcopy(nlp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "spacy/vocab.pyx", line 656, in spacy.vocab.unpickle_vocab (spacy/vocab.cpp:13107)
  File "spacy/vocab.pyx", line 490, in spacy.vocab.Vocab._deserialize_lexemes (spacy/vocab.cpp:10196)
  File "spacy/strings.pyx", line 146, in spacy.strings.StringStore.__getitem__ (spacy/strings.cpp:2577)
IndexError: 1609217230
>>> copy.deepcopy(nlp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "spacy/vocab.pyx", line 656, in spacy.vocab.unpickle_vocab (spacy/vocab.cpp:13107)
  File "spacy/vocab.pyx", line 490, in spacy.vocab.Vocab._deserialize_lexemes (spacy/vocab.cpp:10196)
  File "spacy/strings.pyx", line 146, in spacy.strings.StringStore.__getitem__ (spacy/strings.cpp:2577)
IndexError: 389784016
>>> copy.deepcopy(nlp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/joel/anaconda3/envs/myenv/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "spacy/vocab.pyx", line 656, in spacy.vocab.unpickle_vocab (spacy/vocab.cpp:13107)
  File "spacy/vocab.pyx", line 490, in spacy.vocab.Vocab._deserialize_lexemes (spacy/vocab.cpp:10196)
  File "spacy/strings.pyx", line 146, in spacy.strings.StringStore.__getitem__ (spacy/strings.cpp:2577)
IndexError: 1609217230
>>> copy.deepcopy(nlp)
Segmentation fault: 11
```

## Your Environment

* **spaCy version:** 1.9.0
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Installed models:** en

**Comment by jnothman** [comment]
#1141 suggests this may be fixed in v2. Compiling now.

**Comment by jnothman** [comment]
v2.0 raises "TypeError: can't pickle spacy.vocab.Vocab objects"

Which is fair enough.

**Comment by honnibal** [comment]
@jnothman v2 allows you to pickle with the `dill` library (which supports pickling of lambda functions).

It seems a small extra step to make the native pickle work transparently, but I haven't managed to get it quite right.

You can also use `nlp.to_bytes()` and `nlp.from_bytes()` if you're able to write your own hooks.

Finally, loading time in v2 is much reduced, because the NN models are very small. v2 also fixes a long-standing problem with multi-threaded use, by making word IDs the hash value, instead of sequential integer IDs. This makes it easier to use `Doc` objects produced in different processes.

See @1270

**Comment by jnothman** [comment]
By word IDs you mean vocab lookups for out-of-bag words?

This still looks like sequential allocation, but maybe I've not got things installed correctly:

```
>>> spacy.load('en').tokenizer('blahdiblah foodifoo').to_array([attrs.ORTH])
array([[1510242],
       [1510244]], dtype=int32)
>>> spacy.load('en').tokenizer('foodifoo blahdiblah').to_array([attrs.ORTH])
array([[1510242],
       [1510244]], dtype=int32)

Btw, does someone upgrading to v2.0 also have to re-download the models?

**Comment by jnothman** [comment]
> It seems a small extra step to make the native pickle work transparently, but I haven't managed to get it quite right.

The problem isn't lambdas, but objects that can't be retrieved (or constructed) by name from the module namespace. I suspect the problem you're having is with closures more than lambdas per say.

**Comment by honnibal** [comment]
@jnothman You need `dtype=uint64`

You can install v2 with `pip install spacy-nightly` -- but the model for the latest v2 is just finishing training, so you would need to do `pip install spacy-nightly==2.0.0a11`, just for tonight.

Closures are very central to the way I've implemented the neural networks in [Thinc](https://github.com/explosion/thinc/tree/master/thinc) . Each model returns a callback to compute its backward pass. These callbacks are implemented as closures.

I don't think anyone will need to pickle out *those* closures -- but it means I'm generally using closures all over the place, so I don't love the idea of using `functools.partial` to simulate some of them.

**Comment by jnothman** [comment]
Closures are not a problem if not stored on object's...

**Comment by jnothman** [comment]
do you think partials are much less performant than closures? I wouldn't
have thought that is necessarily true.

**Comment by jnothman** [comment]
or do you just find them syntactically unwieldy?

**Comment by honnibal** [comment]
It's mostly about readability. I would find the partials solution pretty non-obvious.

I'll look more closely at what exactly is wrong with the pickling. I can see that the limitations are more subtle than I thought.
