### ISSUE TITLE
Unable to load custom NER model 

### ISSUE THREAD

**Issue by gurunathpr** [explosion/spaCy#1306]
Description : 
I have trained a custom NER model named "en_dec" on spacy and tried to use it on rasa-nlu.But it gives up an error saying word vector length is 0.Suppose I want to load even the word vectors given in spacy(Example: en_vectors_glove_md).

## Info about spaCy

* **Python version:** 2.7.12
* **Platform:** Linux-4.10.0-32-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 1.9.0
* **Installed models:** en_vectors_glove_md, en_dec, en

Error message: 
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/train.py", line 88, in 
do_train(config)
File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/train.py", line 78, in do_train
interpreter = trainer.train(training_data)
File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/model.py", line 145, in train
updates = component.train(data, self.config, **context)
File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/featurizers/spacy_featurizer.py", line 35, in train
features = self.features_for_doc(example.get("spacy_doc"))
File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/featurizers/spacy_featurizer.py", line 47, in features_for_doc
return doc.vector # this will return the sentence embedding as calculated by spacy (currently averaged words)
File "spacy/tokens/doc.pyx", line 275, in spacy.tokens.doc.Doc.vector.get (spacy/tokens/doc.cpp:7291)
File "spacy/tokens/doc.pyx", line 275, in genexpr   ##(spacy/tokens/doc.cpp:7114)
File "spacy/tokens/token.pyx", line 240, in spacy.tokens.token.Token.vector.get (spacy/tokens/token.cpp:7249)
#ValueError: Word vectors set to length 0. This may be because you don't have a model installed or loaded, or because your model doesn't include word vectors. For more info, see the documentation:
https://spacy.io/docs/usage 

#544

**Comment by honnibal** [comment]
Please see here --- the training is much improved in v2, and we've tried to give a lot more guidance about how to make good use of it: https://spacy.io/usage/training
