### ISSUE TITLE
en_core_web_sm.load(): AttributeError: 'FunctionLayer' object has no attribute 'W'

### ISSUE THREAD

**Issue by bittlingmayer** [explosion/spaCy#1315]
Same symptom as #1295, different version, model etc.

To repro:
```
pip install spacy-nightly
python -m spacy download en_core_web_sm-2.0.0-alpha --direct
```
Then:
```
import en_core_web_sm
en_core_web_sm.load()
```
or
```
import spacy
spacy.load("en_core_web_sm")
```

(If I instead download en_core_web_sm, it loads, but then the vectors are not so great.)

Python version: 3.5.2
spaCy version: 2.0.0a13
Platform: Darwin-16.7.0-x86_64-i386-64bit
Models: en_core_web_sm

**Comment by bittlingmayer** [comment]
Stack trace:

```
>>> en = spacy.load("en_core_web_sm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../env/lib/python3.5/site-packages/spacy/__init__.py", line 13, in load
    return util.load_model(name, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 103, in load_model
    return load_model_from_link(name, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 122, in load_model_from_link
    return cls.load(**overrides)
  File ".../env/lib/python3.5/site-packages/spacy/data/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 155, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 138, in load_model_from_path
    return nlp.from_disk(model_path)
  File ".../env/lib/python3.5/site-packages/spacy/language.py", line 541, in from_disk
    util.from_disk(path, deserializers, exclude)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 483, in from_disk
    reader(path / key)
  File ".../env/lib/python3.5/site-packages/spacy/language.py", line 537, in <lambda>
    deserializers[proc.name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "spacy/pipeline.pyx", line 170, in spacy.pipeline.BaseThincComponent.from_disk (spacy/pipeline.cpp:11298)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 483, in from_disk
    reader(path / key)
  File "spacy/pipeline.pyx", line 163, in spacy.pipeline.BaseThincComponent.from_disk.load_model (spacy/pipeline.cpp:10856)
  File ".../env/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 351, in from_bytes
    dest = getattr(layer, name)
AttributeError: 'FunctionLayer' object has no attribute 'W'
```

**Comment by bittlingmayer** [comment]
Rolling back to `a10`, then re-downloading, I get:

```
(env) Adams-MacBook-Pro:Data bittlingmayer$ python test.py data/raw/mix.en.txt el
Traceback (most recent call last):
  ...
    models['en'] = spacy.load("en_core_web_sm", parser=False)
  File ".../env/lib/python3.5/site-packages/spacy/__init__.py", line 13, in load
    return util.load_model(name, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 103, in load_model
    return load_model_from_link(name, **overrides)
  File ".../env/lib/python3.5/site-packages/spacy/util.py", line 117, in load_model_from_link
    cls = import_file(name, path)
  File ".../env/lib/python3.5/site-packages/spacy/compat.py", line 114, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 766, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '.../env/lib/python3.5/site-packages/spacy/data/en_core_web_sm/__init__.py'
```

**Comment by ines** [comment]
This error indicates that the model was trained with a different version of spaCy – in this case, it looks like you're using the latest `v2.0.0a13` with an older version of the English model (and spaCy skips the compatibility check, since you're running the download command with the `--direct` flag). The downloader should now be all wired up correctly in v2.0 alpha, so you should simply be able to download the compatible model via:

```bash
spacy download en
```

See the [alpha release notes](https://github.com/explosion/spaCy/releases/tag/v2.0.0-alpha) for an overview of all available models and their compatible spaCy versions. Sorry about the frequent updates and different model versions – but we've been making improvements to spaCy and the models pretty quickly over the past few weeks, and we want to make sure you can use the latest models, especially `en_core_web_sm-2.0.0a2`+, as it comes with a nice improvement in accuracy.
