### ISSUE TITLE
Issue when calling spacy info

### ISSUE THREAD

**Issue by balachander1964** [explosion/spaCy#13157]
Hi I am Bala. I use Spacy 3.6.1 for NLP. I am facing the following issue when calling spacy info and when loading any model. I use Python 3.8 on Windows 10.
<<
(pnlpbase) PS C:\windows\system32> python -m spacy info
Traceback (most recent call last):
  File "D:\python\Anaconda3\envs\pnlpbase\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\python\Anaconda3\envs\pnlpbase\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\python\Anaconda3\envs\pnlpbase\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "D:\python\Anaconda3\envs\pnlpbase\lib\site-packages\spacy\__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "D:\python\Anaconda3\envs\pnlpbase\lib\site-packages\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "D:\python\Anaconda3\envs\pnlpbase\lib\site-packages\spacy\pipeline\attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy\pipeline\pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy\vocab.pyx", line 1, in init spacy.vocab
  File "D:\python\Anaconda3\envs\pnlpbase\lib\site-packages\spacy\tokens\__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy\tokens\doc.pyx", line 36, in init spacy.tokens.doc
  File "D:\python\Anaconda3\envs\pnlpbase\lib\site-packages\spacy\schemas.py", line 222, in <module>
    class TokenPattern(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 634, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "D:\python\Anaconda3\envs\pnlpbase\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
(pnlpbase) PS C:\windows\system32>
>>
Also, I get a deserialization error when I load models. I will appreciate if you let me know how to fix this. This is bit urgent. Awaiting your reply. Thank you. Bala

**Comment by adrianeboyd** [comment]
Let's keep this discussion in #13155.

**Comment by Rcrossmeister** [comment]
I think my suggested answer works: #13155
