### ISSUE TITLE
doc.vector not working after loading from stored model

### ISSUE THREAD

**Issue by ankitarath2011** [explosion/spaCy#1316]
## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Windows-10-10.0.14393
* **spaCy version:** 1.9.0
* **Installed models:** en

I have trained the model following 
 https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py

I am saving it to some directory, then loading and using it again. But after loading it when I am trying to access doc.vector, it is throwing following error.

```
Traceback (most recent call last):
  File "C:/Users/ankita.a.rath/Desktop/my_codes/Rasa_nlu/rasa_nlu-master/train_spacy_ner.py", line 248, in <module>
    main("en", "new_model")
  File "C:/Users/ankita.a.rath/Desktop/my_codes/Rasa_nlu/rasa_nlu-master/train_spacy_ner.py", line 238, in main
    print (doc2.vector)
  File "spacy/tokens/doc.pyx", line 275, in spacy.tokens.doc.Doc.vector.__get__ (spacy/tokens/doc.cpp:7291)
    self._vector = sum(t.vector for t in self) / len(self)
  File "spacy/tokens/doc.pyx", line 275, in genexpr (spacy/tokens/doc.cpp:7114)
    self._vector = sum(t.vector for t in self) / len(self)
  File "spacy/tokens/token.pyx", line 240, in spacy.tokens.token.Token.vector.__get__ (spacy/tokens/token.cpp:7249)
    raise ValueError(
ValueError: Word vectors set to length 0. This may be because you don't have a model installed or loaded, or because your model doesn't include word vectors. For more info, see the documentation: 
https://spacy.io/docs/usage
```

It is working fine if I am using it directly after the training (i.e. without saving and reloading).
Please suggest some solution.

**Comment by ankitarath2011** [comment]
I think when I am saving the model, the vector is not getting saved. I could not find any direct solution, so what I am doing is, I am storing the vector separately, then loading it after loading the model.

It resolved my issue. Closing this one.
