### ISSUE TITLE
Downloading model error: ModuleNotFoundError: No module named 'spacy.symbols'

### ISSUE THREAD

**Issue by ojo4f3** [explosion/spaCy#13175]
When following the `README.md` guide, ***IF*** the repo is cloned locally and the virtual environment is set up in the `spacy` folder, it will fail to download a model. I have been able to download a model through my IDE and at the CLI, but not if I am in the same directory as the repo. 

The error is: `ModuleNotFoundError: No module named 'spacy.symbols'`. Below are the steps used once the repo was cloned, the error message, and stack trace.

There was an issued open for the same error it appears that was not resolved: [https://github.com/explosion/spaCy/issues/12847](https://github.com/explosion/spaCy/issues/12847).

---
#### Windows

<details>

```(.env) colto@TIMMY C:\Users\colto\Documents\GitHub\test_folder\spacy>pip list
Package    Version
---------- -------
pip        23.2.1
setuptools 65.5.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(.env) colto@TIMMY C:\Users\colto\Documents\GitHub\test_folder\spacy>python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\colto\documents\github\test_folder\spacy\.env\lib\site-pac
kages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/47/6a/453160888fa
b7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl.metadata
  Using cached pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-23.3.1

(.env) colto@TIMMY C:\Users\colto\Documents\GitHub\test_folder\spacy>pip install -U pip setuptools wheel
Requirement already satisfied: pip in c:\users\colto\documents\github\test_folder\spacy\.env\lib\site-pac
kages (23.3.1)
Requirement already satisfied: setuptools in c:\users\colto\documents\github\test_folder\spacy\.env\lib\s
ite-packages (65.5.0)
Collecting setuptools
  Downloading setuptools-69.0.2-py3-none-any.whl.metadata (6.3 kB)
Collecting wheel
  Downloading wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
Downloading setuptools-69.0.2-py3-none-any.whl (819 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.5/819.5 kB 2.6 MB/s eta 0:00:00
Downloading wheel-0.42.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 3.7 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
Successfully installed setuptools-69.0.2 wheel-0.42.0

(.env) colto@TIMMY C:\Users\colto\Documents\GitHub\test_folder\spacy>pip install -U spacy
Collecting spacy
  Using cached spacy-3.7.2-cp311-cp311-win_amd64.whl.metadata (26 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Using cached murmurhash-1.0.10-cp311-cp311-win_amd64.whl.metadata (2.0 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Using cached cymem-2.0.8-cp311-cp311-win_amd64.whl.metadata (8.6 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Using cached preshed-3.0.9-cp311-cp311-win_amd64.whl.metadata (2.2 kB)
Collecting thinc<8.3.0,>=8.1.8 (from spacy)
  Using cached thinc-8.2.1-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.2-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Using cached srsly-2.4.8-cp311-cp311-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.4.0,>=0.1.0 (from spacy)
  Using cached weasel-0.3.4-py3-none-any.whl.metadata (4.7 kB)
Collecting typer<0.10.0,>=0.3.0 (from spacy)
  Using cached typer-0.9.0-py3-none-any.whl (45 kB)
Collecting smart-open<7.0.0,>=5.2.1 (from spacy)
  Using cached smart_open-6.4.0-py3-none-any.whl.metadata (21 kB)
Collecting tqdm<5.0.0,>=4.38.0 (from spacy)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting requests<3.0.0,>=2.13.0 (from spacy)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy)
  Using cached pydantic-2.5.2-py3-none-any.whl.metadata (65 kB)
Collecting jinja2 (from spacy)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Requirement already satisfied: setuptools in c:\users\colto\documents\github\test_folder\spacy\.env\lib\s
ite-packages (from spacy) (69.0.2)
Collecting packaging>=20.0 (from spacy)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy)
  Using cached langcodes-3.3.0-py3-none-any.whl (181 kB)
Collecting numpy>=1.19.0 (from spacy)
  Using cached numpy-1.26.2-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting annotated-types>=0.4.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.14.5 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached pydantic_core-2.14.5-cp311-none-win_amd64.whl.metadata (6.6 kB)
Collecting typing-extensions>=4.6.1 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.1.8->spacy)
  Using cached blis-0.7.11-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.3.0,>=8.1.8->spacy)
  Using cached confection-0.1.4-py3-none-any.whl.metadata (19 kB)
Collecting colorama (from tqdm<5.0.0,>=4.38.0->spacy)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting click<9.0.0,>=7.1.1 (from typer<0.10.0,>=0.3.0->spacy)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting cloudpathlib<0.17.0,>=0.7.0 (from weasel<0.4.0,>=0.1.0->spacy)
  Using cached cloudpathlib-0.16.0-py3-none-any.whl.metadata (14 kB)
Collecting MarkupSafe>=2.0 (from jinja2->spacy)
  Using cached MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Using cached spacy-3.7.2-cp311-cp311-win_amd64.whl (12.1 MB)
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Using cached cymem-2.0.8-cp311-cp311-win_amd64.whl (39 kB)
Using cached murmurhash-1.0.10-cp311-cp311-win_amd64.whl (25 kB)
Using cached numpy-1.26.2-cp311-cp311-win_amd64.whl (15.8 MB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached preshed-3.0.9-cp311-cp311-win_amd64.whl (122 kB)
Using cached pydantic-2.5.2-py3-none-any.whl (381 kB)
Using cached pydantic_core-2.14.5-cp311-none-win_amd64.whl (1.9 MB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached smart_open-6.4.0-py3-none-any.whl (57 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Using cached srsly-2.4.8-cp311-cp311-win_amd64.whl (479 kB)
Using cached thinc-8.2.1-cp311-cp311-win_amd64.whl (1.5 MB)
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Using cached wasabi-1.1.2-py3-none-any.whl (27 kB)
Using cached weasel-0.3.4-py3-none-any.whl (50 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached blis-0.7.11-cp311-cp311-win_amd64.whl (6.6 MB)
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached cloudpathlib-0.16.0-py3-none-any.whl (45 kB)
Using cached confection-0.1.4-py3-none-any.whl (35 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl (17 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Installing collected packages: cymem, urllib3, typing-extensions, spacy-loggers, spacy-legacy, smart-open
, packaging, numpy, murmurhash, MarkupSafe, langcodes, idna, colorama, cloudpathlib, charset-normalizer, 
certifi, catalogue, annotated-types, wasabi, tqdm, srsly, requests, pydantic-core, preshed, jinja2, click
, blis, typer, pydantic, confection, weasel, thinc, spacy
Successfully installed MarkupSafe-2.1.3 annotated-types-0.6.0 blis-0.7.11 catalogue-2.0.10 certifi-2023.1
1.17 charset-normalizer-3.3.2 click-8.1.7 cloudpathlib-0.16.0 colorama-0.4.6 confection-0.1.4 cymem-2.0.8
 idna-3.6 jinja2-3.1.2 langcodes-3.3.0 murmurhash-1.0.10 numpy-1.26.2 packaging-23.2 preshed-3.0.9 pydant
ic-2.5.2 pydantic-core-2.14.5 requests-2.31.0 smart-open-6.4.0 spacy-3.7.2 spacy-legacy-3.0.12 spacy-logg
ers-1.0.5 srsly-2.4.8 thinc-8.2.1 tqdm-4.66.1 typer-0.9.0 typing-extensions-4.8.0 urllib3-2.1.0 wasabi-1.
1.2 weasel-0.3.4

(.env) colto@TIMMY C:\Users\colto\Documents\GitHub\test_folder\spacy>python -m spacy download en_core_web
_sm
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\colto\Documents\GitHub\test_folder\spacy\spacy\__init__.py", line 13, in <module>       
    from . import pipeline  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colto\Documents\GitHub\test_folder\spacy\spacy\pipeline\__init__.py", line 1, in <module
>
    from .attributeruler import AttributeRuler
  File "C:\Users\colto\Documents\GitHub\test_folder\spacy\spacy\pipeline\attributeruler.py", line 6, in <
module>
    from .. import util
  File "C:\Users\colto\Documents\GitHub\test_folder\spacy\spacy\util.py", line 75, in <module>
    from .symbols import ORTH
ModuleNotFoundError: No module named 'spacy.symbols'
```

</details>

#### Linux

<details>

```
colton@tano:~/GitHub$ git clone https://github.com/explosion/spacy.git
Cloning into 'spacy'...
remote: Enumerating objects: 111868, done.
remote: Counting objects: 100% (667/667), done.
remote: Compressing objects: 100% (363/363), done.
remote: Total 111868 (delta 361), reused 558 (delta 292), pack-reused 111201
Receiving objects: 100% (111868/111868), 197.96 MiB | 19.63 MiB/s, done.
Resolving deltas: 100% (84450/84450), done.

colton@tano:~/GitHub$ cd spacy/

colton@tano:~/GitHub/spacy$ python3 -m venv .env

colton@tano:~/GitHub/spacy$ source .env/bin/activate
(.env) 
colton@tano:~/GitHub/spacy$ pip install -U pip setuptools wheel
Requirement already satisfied: pip in ./.env/lib/python3.10/site-packages (22.0.2)
Collecting pip
  Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
Requirement already satisfied: setuptools in ./.env/lib/python3.10/site-packages (59.6.0)
Collecting setuptools
  Using cached setuptools-69.0.2-py3-none-any.whl (819 kB)
Collecting wheel
  Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Uninstalling setuptools-59.6.0:
      Successfully uninstalled setuptools-59.6.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-23.3.1 setuptools-69.0.2 wheel-0.42.0
(.env) 
colton@tano:~/GitHub/spacy$ pip install -U spacy
Collecting spacy
  Using cached spacy-3.7.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Using cached murmurhash-1.0.10-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.0 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Using cached cymem-2.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.4 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Using cached preshed-3.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting thinc<8.3.0,>=8.1.8 (from spacy)
  Using cached thinc-8.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.2-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Using cached srsly-2.4.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.4.0,>=0.1.0 (from spacy)
  Using cached weasel-0.3.4-py3-none-any.whl.metadata (4.7 kB)
Collecting typer<0.10.0,>=0.3.0 (from spacy)
  Using cached typer-0.9.0-py3-none-any.whl (45 kB)
Collecting smart-open<7.0.0,>=5.2.1 (from spacy)
  Using cached smart_open-6.4.0-py3-none-any.whl.metadata (21 kB)
Collecting tqdm<5.0.0,>=4.38.0 (from spacy)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting requests<3.0.0,>=2.13.0 (from spacy)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy)
  Using cached pydantic-2.5.2-py3-none-any.whl.metadata (65 kB)
Collecting jinja2 (from spacy)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Requirement already satisfied: setuptools in ./.env/lib/python3.10/site-packages (from spacy) (69.0.2)
Collecting packaging>=20.0 (from spacy)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy)
  Using cached langcodes-3.3.0-py3-none-any.whl (181 kB)
Collecting numpy>=1.19.0 (from spacy)
  Using cached numpy-1.26.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting annotated-types>=0.4.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.14.5 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached pydantic_core-2.14.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Collecting typing-extensions>=4.6.1 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.1.8->spacy)
  Using cached blis-0.7.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.3.0,>=8.1.8->spacy)
  Using cached confection-0.1.4-py3-none-any.whl.metadata (19 kB)
Collecting click<9.0.0,>=7.1.1 (from typer<0.10.0,>=0.3.0->spacy)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting cloudpathlib<0.17.0,>=0.7.0 (from weasel<0.4.0,>=0.1.0->spacy)
  Using cached cloudpathlib-0.16.0-py3-none-any.whl.metadata (14 kB)
Collecting MarkupSafe>=2.0 (from jinja2->spacy)
  Using cached MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Using cached spacy-3.7.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.6 MB)
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Using cached cymem-2.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (46 kB)
Using cached murmurhash-1.0.10-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29 kB)
Using cached numpy-1.26.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached preshed-3.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
Using cached pydantic-2.5.2-py3-none-any.whl (381 kB)
Using cached pydantic_core-2.14.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached smart_open-6.4.0-py3-none-any.whl (57 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Using cached srsly-2.4.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (493 kB)
Using cached thinc-8.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (920 kB)
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Using cached wasabi-1.1.2-py3-none-any.whl (27 kB)
Using cached weasel-0.3.4-py3-none-any.whl (50 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached blis-0.7.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.2 MB)
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached cloudpathlib-0.16.0-py3-none-any.whl (45 kB)
Using cached confection-0.1.4-py3-none-any.whl (35 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Installing collected packages: cymem, wasabi, urllib3, typing-extensions, tqdm, spacy-loggers, spacy-legacy, smart-open, packaging, numpy, murmurhash, MarkupSafe, langcodes, idna, click, charset-normalizer, certifi, catalogue, annotated-types, typer, srsly, requests, pydantic-core, preshed, jinja2, cloudpathlib, blis, pydantic, confection, weasel, thinc, spacy
Successfully installed MarkupSafe-2.1.3 annotated-types-0.6.0 blis-0.7.11 catalogue-2.0.10 certifi-2023.11.17 charset-normalizer-3.3.2 click-8.1.7 cloudpathlib-0.16.0 confection-0.1.4 cymem-2.0.8 idna-3.6 jinja2-3.1.2 langcodes-3.3.0 murmurhash-1.0.10 numpy-1.26.2 packaging-23.2 preshed-3.0.9 pydantic-2.5.2 pydantic-core-2.14.5 requests-2.31.0 smart-open-6.4.0 spacy-3.7.2 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.4.8 thinc-8.2.1 tqdm-4.66.1 typer-0.9.0 typing-extensions-4.8.0 urllib3-2.1.0 wasabi-1.1.2 weasel-0.3.4
(.env) 
colton@tano:~/GitHub/spacy$ python3 -m spacy download en_core_web_sm
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/colton/GitHub/spacy/spacy/__init__.py", line 13, in <module>
    from . import pipeline  # noqa: F401
  File "/home/colton/GitHub/spacy/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/home/colton/GitHub/spacy/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .. import util
  File "/home/colton/GitHub/spacy/spacy/util.py", line 75, in <module>
    from .symbols import ORTH
ModuleNotFoundError: No module named 'spacy.symbols'

```

</details>

If the repo is not cloned locally and the virtual environment set up inside `spacy` the model download and set up are flawless on both machines I attempted this on.

#### My Environment
**spaCy version:** 3.7.2
**Platform 1:** Windows 10 Home OS build: 19045.3570 64 bit (**Python version:** 3.11.5)
**Platform 2:** Pop!_OS 22.04 LTS "jammy" 64 bit (**Python version:** 3.10.12)
**Pipeline:** attempted to use en_core_web_sm

Colton

**Comment by adrianeboyd** [comment]
The issue isn't where the venv is, but the contents of your working directory. If you have a clone of the repo, python will first try to import `spacy` from the directory `spacy/` instead of from the venv. And if you don't have an editable install in `spacy/`, then `spacy/` is missing the compiled cython modules and the import fails.

Editable installs are only recommended if you're doing active development on spacy itself (https://spacy.io/usage/#source), so the easiest solution is to use a different working directory than the spacy repo directory.
