### ISSUE TITLE
DLL load failed whilst installing language model

### ISSUE THREAD

**Issue by mlatto** [explosion/spaCy#1325]
Hi 

I am having issues whilst installing spaCy for one of our users. Using pip install -U spacy works fine and does not throw any errors but when I use python -m download en I get the below error. I am currently running on Windows 7 64bit with Visual Studio Express (Windows 10 SDK failed to install when I installed this), Python 3.6 and when using pip it installs 1.9.0. I have also tried this installation on another machine with a fresh install of Visual Studio Community 2015 (no errors) and I got the exact same error message. 

Any help would be greatly appreciated. 

C:\Users\hisadminml>python -m spacy download en
Traceback (most recent call last):
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\runpy.py"
, line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\runpy.py"
, line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\runpy.py"
, line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\spacy\__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\spacy\deprecated.py", line 8, in <module>
    from .cli import download
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\spacy\cli\__init__.py", line 5, in <module>
    from .train import train, train_config
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\spacy\cli\train.py", line 8, in <module>
    from ..scorer import Scorer
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\spacy\scorer.py", line 4, in <module>
    from .gold import tags_to_entities
  File "spacy/morphology.pxd", line 25, in init spacy.gold (spacy/gold.cpp:23505
)
    cdef class Morphology:
  File "spacy/vocab.pxd", line 27, in init spacy.morphology (spacy/morphology.cp
p:10713)
    cdef class Vocab:
  File ".env/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd", li
ne 155, in init spacy.vocab (spacy/vocab.cpp:19463)
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\hisadminml\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified procedure could not be found.

## Your Environment

* Operating System: Windows 7 64bit
* Python Version Used: 3.6.0
* spaCy Version Used: 1.9.0
* Environment Information:

**Comment by ines** [comment]
Could you try again installing spaCy v2.0 and downloading the new models? The error might have also been related to #1202, which is fixed now.

Installing everything via `conda` would probably also help. However, we're currently still waiting to get the new version built for conda (it's just taking a bit longer because of Travis errors and the OSX backlogs 😓). 

Once the version is up, could you try again? [See here](https://spacy.io/usage/v2) for details on what's new in v2.0. If there are still problems, feel free to reopen.
