### ISSUE TITLE
catalogue.RegistryError: [E892] Unknown function registry: 'vectors'.

### ISSUE THREAD

**Issue by RengashreeParthasarathy** [explosion/spaCy#13296]
## Your Environment

* Operating System: Mac OS
* Python Version Used:  3.11.1
* spaCy Version Used: 3.4.4
* Environment Information:

I am trying to learn spacy and nlp. when I try to run below code I am getting error, please help

Code:
import spacy
from spacy import displacy
nlp = spacy.load('en_core_web_md')
doc= nlp('I own a ginger cat.')
displacy.serve(doc, style='dep')

Error: 
 warnings.warn(warn_msg)
Traceback (most recent call last):
  File "/SpacyDemo/notes.py", line 3, in <module>
    nlp = spacy.load('en_core_web_md')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/spacy/__init__.py", line 54, in load
    return util.load_model(
           ^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/spacy/util.py", line 432, in load_model
    return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/spacy/util.py", line 468, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, enable=enable, exclude=exclude, config=config)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/en_core_web_md/__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/spacy/util.py", line 649, in load_model_from_init_py
    return load_model_from_path(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/spacy/util.py", line 506, in load_model_from_path
    nlp = load_model_from_config(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/spacy/util.py", line 554, in load_model_from_config
    nlp = lang_cls.from_config(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/spacy/language.py", line 1764, in from_config
    resolved_nlp = registry.resolve(
                   ^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/confection/__init__.py", line 759, in resolve
    resolved, _ = cls._make(
                  ^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/confection/__init__.py", line 808, in _make
    filled, _, resolved = cls._fill(
                          ^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/confection/__init__.py", line 862, in _fill
    promise_schema = cls.make_promise_schema(value, resolve=resolve)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/confection/__init__.py", line 1054, in make_promise_schema
    func = cls.get(reg_name, func_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SpacyDemo/spacyvenv/lib/python3.11/site-packages/spacy/util.py", line 127, in get
    raise RegistryError(Errors.E892.format(name=registry_name, available=names))
catalogue.RegistryError: [E892] Unknown function registry: 'vectors'.

Available names: architectures, augmenters, batchers, callbacks, cli, datasets, displacy_colors, factories, initializers, languages, layers, lemmatizers, loggers, lookups, losses, misc, models, ops, optimizers, readers, schedules, scorers, tokenizers

**Comment by svlandeg** [comment]
Hi! Let me move this to the discussion forum and answer you there!
