### ISSUE TITLE
Compatibility issue with spaCy 3.7.4 and typing-extensions 4.11.0

### ISSUE THREAD

**Issue by manunaik99** [explosion/spaCy#13487]
I'm encountering a compatibility issue when using spaCy version 3.7.4 in conjunction with the typing-extensions package version 4.11.0. Whenever I attempt to install spaCy or run code that utilizes spaCy functionality, I encounter the following error: 

0.710 Traceback (most recent call last):
0.710   File "/usr/local/bin/spacy", line 5, in <module>
0.710     from spacy.cli import setup_cli
0.710   File "/usr/local/lib/python3.9/site-packages/spacy/__init__.py", line 13, in <module>
0.710     from . import pipeline  # noqa: F401
0.710   File "/usr/local/lib/python3.9/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
0.710     from .attributeruler import AttributeRuler
0.710   File "/usr/local/lib/python3.9/site-packages/spacy/pipeline/attributeruler.py", line 8, in <module>
0.710     from ..language import Language
0.710   File "/usr/local/lib/python3.9/site-packages/spacy/language.py", line 43, in <module>
0.710     from .pipe_analysis import analyze_pipes, print_pipe_analysis, validate_attrs
0.710   File "/usr/local/lib/python3.9/site-packages/spacy/pipe_analysis.py", line 6, in <module>
0.710     from .tokens import Doc, Span, Token
0.710   File "/usr/local/lib/python3.9/site-packages/spacy/tokens/__init__.py", line 1, in <module>
0.711     from ._serialize import DocBin
0.711   File "/usr/local/lib/python3.9/site-packages/spacy/tokens/_serialize.py", line 14, in <module>
0.711     from ..vocab import Vocab
0.711   File "spacy/vocab.pyx", line 1, in init spacy.vocab
0.711   File "spacy/tokens/doc.pyx", line 49, in init spacy.tokens.doc
0.711   File "/usr/local/lib/python3.9/site-packages/spacy/schemas.py", line 287, in <module>
0.711     class TokenPattern(BaseModel):
0.711   File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
0.711   File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
0.711   File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
0.711   File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
0.711   File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
0.711   File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
0.711   File "/usr/local/lib/python3.9/typing.py", line 852, in __subclasscheck__
0.711     return issubclass(cls, self.__origin__)
0.711 TypeError: issubclass() arg 1 must be a class
1.137 ERROR: Invalid requirement: ''
------
failed to solve: process "/bin/sh -c pip install \"$(spacy info en_core_web_md --url)\"" did not complete successfully: exit code: 1

**Comment by svlandeg** [comment]
Thanks for the report! We'll look into this.

**Comment by svlandeg** [comment]
Let me move this to the discussion forum and follow up with you there!
