### ISSUE TITLE
Spacy 3.7.5 not working with python 3.12.4

### ISSUE THREAD

**Issue by Snawe** [explosion/spaCy#13550]
## How to reproduce the behaviour
* Install spacy 3.7.5
* Use Python 3.12.4
* Run the example from the homepage
```py
# pip install -U spacy
# python -m spacy download en_core_web_sm
import spacy

# Load English tokenizer, tagger, parser and NER
nlp = spacy.load("en_core_web_sm")

# Process whole documents
text = (
    "When Sebastian Thrun started working on self-driving cars at "
    "Google in 2007, few people outside of the company took him "
    "seriously. “I can tell you very senior CEOs of major American "
    "car companies would shake my hand and turn away because I wasn’t "
    "worth talking to,” said Thrun, in an interview with Recode earlier "
    "this week."
)
doc = nlp(text)

# Analyze syntax
print("Noun phrases:", [chunk.text for chunk in doc.noun_chunks])
print("Verbs:", [token.lemma_ for token in doc if token.pos_ == "VERB"])

# Find named entities, phrases and concepts
for entity in doc.ents:
    print(entity.text, entity.label_)
```

get the error:

```
ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
  File "/path/to/file.py", line 3, in <module>
    import spacy
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

The issue seems to be a pydantic issue and is already solved: https://github.com/pydantic/pydantic/issues/9609

## Your Environment

* Operating System: Ubuntu
* Python Version Used: 3.12.4
* spaCy Version Used: 3.7.5

**Comment by sriharikarthik13** [comment]
Same issue, I think the solution could be to change python version to a lower: 3.12.3 version

**Comment by ewfian** [comment]
same issue here

**Comment by adriano515** [comment]
Faced the same issue, downgrading worked but it would be great to know if there's any work being done on this as we can't live on 3.12.3 forever

**Comment by adriano515** [comment]
Latest release, 3.7.6 from a couple days ago seems to have fixed issues for me, so for python 3.12.4 , either don't use that version or use spacy 3.7.6 (3.7.6 code is the same as 3.7.5 according to release notes)

**Comment by cp2boston** [comment]
Tried 3.7.6 with both Python 3.12.4 and 3.12.5.  Running:
 ```
python -m spacy download en_core_web_md
``` 

results in:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/app/.venv/lib/python3.12/site-packages/spacy/__init__.py", line 13, in <module>
    from . import pipeline  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/app/.venv/lib/python3.12/site-packages/spacy/pipeline/attributeruler.py", line 8, in <module>
    from ..language import Language
  File "/app/.venv/lib/python3.12/site-packages/spacy/language.py", line 43, in <module>
    from .pipe_analysis import analyze_pipes, print_pipe_analysis, validate_attrs
  File "/app/.venv/lib/python3.12/site-packages/spacy/pipe_analysis.py", line 6, in <module>
    from .tokens import Doc, Span, Token
  File "/app/.venv/lib/python3.12/site-packages/spacy/tokens/__init__.py", line 1, in <module>
    from ._serialize import DocBin
  File "/app/.venv/lib/python3.12/site-packages/spacy/tokens/_serialize.py", line 14, in <module>
    from ..vocab import Vocab
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "spacy/tokens/doc.pyx", line 49, in init spacy.tokens.doc
  File "/app/.venv/lib/python3.12/site-packages/spacy/schemas.py", line 195, in <module>
    class TokenPatternString(BaseModel):
  File "/app/.venv/lib/python3.12/site-packages/pydantic/v1/main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "/app/.venv/lib/python3.12/site-packages/pydantic/v1/main.py", line 808, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "/app/.venv/lib/python3.12/site-packages/pydantic/v1/typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "/app/.venv/lib/python3.12/site-packages/pydantic/v1/typing.py", line 529, in update_field_forward_refs
    update_field_forward_refs(sub_f, globalns=globalns, localns=localns)
  File "/app/.venv/lib/python3.12/site-packages/pydantic/v1/typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/pydantic/v1/typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

**Comment by honnibal** [comment]
This should be resolved by pydantic updates now, so closing.
