### ISSUE TITLE
ssl verification failed (expiration)

### ISSUE THREAD

**Issue by meirmaor** [explosion/spaCy#1359]
Trying to install English model on old Spacy version fails due to ssl verification.
Possibly due to index.spacy.io ssl expired Sep 24th (though it may be a different server as the issue seems to have started Sep 23rd)
This StackOverflow question is probably the same issue we are having: https://stackoverflow.com/questions/46383064/spacy-module-install-in-conda

Using paCy 0.101.0
python -m spacy.en.download 

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/miniconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/miniconda/lib/python2.7/site-packages/spacy/en/download.py", line 13, in <module>
    plac.call(main)
  File "/usr/local/miniconda/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/miniconda/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/miniconda/lib/python2.7/site-packages/spacy/en/download.py", line 9, in main
    download('en', force)
  File "/usr/local/miniconda/lib/python2.7/site-packages/spacy/download.py", line 24, in download
    package = sputnik.install(about.__title__, about.__version__, about.__models__[lang])
  File "/usr/local/miniconda/lib/python2.7/site-packages/sputnik/__init__.py", line 37, in install
    index.update()
  File "/usr/local/miniconda/lib/python2.7/site-packages/sputnik/index.py", line 84, in update
    index = json.load(session.open(request, 'utf8'))
  File "/usr/local/miniconda/lib/python2.7/site-packages/sputnik/session.py", line 43, in open
    r = self.opener.open(request)
  File "/usr/local/miniconda/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/miniconda/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/miniconda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/miniconda/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/local/miniconda/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

**Comment by honnibal** [comment]
Fixed now, thanks!

Is there a reason you need the old version? We'd like to retire that download service. The models are available on https://github.com/explosion/spacy-models for legacy support.

**Comment by meirmaor** [comment]
Thanks for the quick turnaround. 
Using old version for the obvious reason, It was the latest when we started using spacy and we don't upgrade without good reason (it has a cost). We probably will upgrade, though I still like to be able to install old versions of my software.

**Comment by honnibal** [comment]
Fair enough. My advice would probably be to wait until spaCy 2 stable to update.

Btw, when you do update, be sure to retrain any statistical models that use the output of spaCy as an input. The predictions of the newer versions are likely to have a differet distribution, so you might get train/test skew if you don't retrain.
