### ISSUE TITLE
catalogue.RegistryError: [E893] Could not find function 'spacy.Tok2Vec.v1' in function registry 'architectures'. 

### ISSUE THREAD

**Issue by Tiny1233** [explosion/spaCy#13605]
## Your Environment

* Operating System:Windows 10
* Python Version Used:3.12.0
* spaCy Version Used:3.7.5
* Environment Information:
* I made a chat project with python package 'chatterbot', and it needs package spacy, When I finish installing spacy and run my code in vscode, it works successfully.But is glitches when I package it with pyinstaller,the packaged program just shows a window,The following text is the detail(what shows on the window)
* Traceback (most recent call last):
  File "basic.py", line 11, in <module>
  File "chatterbot\chatterbot.py", line 28, in __init__
  File "chatterbot\utils.py", line 33, in initialize_class
  File "chatterbot\storage\sql_storage.py", line 20, in __init__
  File "chatterbot\storage\storage_adapter.py", line 20, in __init__
  File "chatterbot\tagging.py", line 17, in __init__
  File "spacy\__init__.py", line 51, in load
  File "spacy\util.py", line 467, in load_model
  File "spacy\util.py", line 539, in load_model_from_path
  File "spacy\util.py", line 587, in load_model_from_config
  File "spacy\language.py", line 1889, in from_config
  File "spacy\language.py", line 821, in add_pipe
  File "spacy\language.py", line 709, in create_pipe
  File "confection\__init__.py", line 760, in resolve
  File "confection\__init__.py", line 809, in _make
  File "confection\__init__.py", line 864, in _fill
  File "confection\__init__.py", line 863, in _fill
  File "confection\__init__.py", line 1069, in make_promise_schema
  File "spacy\util.py", line 163, in get
catalogue.RegistryError: [E893] Could not find function 'spacy.Tok2Vec.v1' in function registry 'architectures'. If you're using a custom function, make sure the code is available. If the function is provided by a third-party package, e.g. spacy-transformers, make sure the package is installed in your environment.

Available names: spacy.CharacterEmbed.v2, spacy.EntityLinker.v2, spacy.HashEmbedCNN.v2, spacy.MaxoutWindowEncoder.v2, spacy.MishWindowEncoder.v2, spacy.MultiHashEmbed.v2, spacy.PretrainCharacters.v1, spacy.PretrainVectors.v1, spacy.SpanCategorizer.v1, spacy.SpanFinder.v1, spacy.Tagger.v2, spacy.TextCatBOW.v2, spacy.TextCatBOW.v3, spacy.TextCatCNN.v2, spacy.TextCatEnsemble.v2, spacy.TextCatLowData.v1, spacy.TextCatParametricAttention.v1, spacy.TextCatReduce.v1, spacy.Tok2Vec.v2, spacy.Tok2VecListener.v1, spacy.TorchBiLSTMEncoder.v1, spacy.TransitionBasedParser.v2      
How can I do to fix it?

**Comment by naLWN** [comment]
I also had the same issue，have you already solved this issue?
