### ISSUE TITLE
load_vectors fails on special characters

### ISSUE THREAD

**Issue by aurelien-clu** [explosion/spaCy#1394]
## Context
Hello,
I am trying to use a different word embedding which contains words with 'special' characters.
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md
For instance French or Polish embeddings from Facebook:

Is it possible to handle these (if this is really the issue as I suspect),  otherwise is it possible to have a flag to discard errors and log [line number, word, error message]?
```python
def load_vectors(self, file_, error_on_failed_lines=True):
```

Imo it is half a bug and half a feature request, depending on how you see it.

## Test data
https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.pl.vec
https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.fr.vec

## Test code
```python
nlp = spacy.load('en')
with open('wiki.pl.vec', "r") as f:
    next(f)  # skipping header
    n = nlp.vocab.load_vectors(f)
```
Encoding makes no difference:
```python
nlp = spacy.load('en')
with open('wiki.pl.vec', encoding='utf-8') as f:
    next(f)  # skipping header
    n = nlp.vocab.load_vectors(f)
```

```python
Traceback (most recent call last):
  File "my_file.py", line 134, in <module>
    nlp = load_nlp_model(settings)
  File "my_file.py", line 118, in load_nlp_model
    n = nlp.vocab.load_vectors(f)
  File "spacy/vocab.pyx", line 553, in spacy.vocab.Vocab.load_vectors 
(spacy/vocab.cpp:10950)
spacy.vocab.VectorReadError: Error reading word vectors from 
<_io.TextIOWrapper name='wiki.pl.vec' mode='r' encoding='UTF-8'> on line 22001.
All vectors must be the same size.
Prev size: 300
Curr size: 301
```

> wiki.pl.vec => line 22001 => napędowy
> wiki.fr.vec => line 1661 => »

These are the first error encountered, I expect other 'faulty lines'.

## SpaCy code:
```python
def load_vectors(self, file_):
        """
        Load vectors from a text-based file.
        Arguments:
            file_ (buffer): The file to read from. Entries should be separated by newlines,
        and each entry should be whitespace delimited. The first value of the entry
        should be the word string, and subsequent entries should be the values of the
        vector.
        Returns:
            vec_len (int): The length of the vectors loaded.
        """
        cdef LexemeC* lexeme
        cdef attr_t orth
        cdef int32_t vec_len = -1
        cdef double norm = 0.0

        whitespace_pattern = re.compile(r'\s', re.UNICODE)

        for line_num, line in enumerate(file_):
            pieces = line.split()
            word_str = " " if whitespace_pattern.match(line) else pieces.pop(0)
            if vec_len == -1:
                vec_len = len(pieces)
            elif vec_len != len(pieces):
                raise VectorReadError.mismatched_sizes(file_, line_num,
                                                        vec_len, len(pieces))
            orth = self.strings[word_str]
            lexeme = <LexemeC*><void*>self.get_by_orth(self.mem, orth)
            lexeme.vector = <float*>self.mem.alloc(vec_len, sizeof(float))
            for i, val_str in enumerate(pieces):
                lexeme.vector[i] = float(val_str)
            norm = 0.0
            for i in range(vec_len):
                norm += lexeme.vector[i] * lexeme.vector[i]
            lexeme.l2_norm = sqrt(norm)
        self.vectors_length = vec_len
        return vec_len
```

## Info about spaCy

* **spaCy version:** 1.9.0
* **Installed models:** en, en_vectors_glove_md
* **Python version:** 3.5.3
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit

**Comment by honnibal** [comment]
Thanks for the report. I'm puzzled about why this would be broken --- the code looks correct, and you're using Python 3, so everything should be in unicode. Ignore the Cython / memory management parts of that `load_vectors` function (thanks for quoting it!) --- the error must be in the regular expression splitting the whitespace.

In any case, you can work around this by writing your own function to set vectors into the vocab, one-by-one. Here's what you need to do:

    for word_str, vector_array in read_vectors(source):
        lexeme = vocab[word_str]
        lexeme.vector = vector_array

`word_str` should be a unicode string and `vector_array` should be a numpy array, of length equal to `vocab.vectors_length`.

I *think* that should work --- but I haven't tried it, and I haven't worked with the 1.x branch for a while.

**Comment by aurelien-clu** [comment]
Thank you for your quick answer, I will try doing that.

**Comment by aurelien-clu** [comment]
## Following issue

Actually I have another related issue, 
```python
nlp.vocab = new_vocab
```
is not enough when using a pipeline:
```python
def _process_texts(texts_, nlp, shape, settings):
    print("Processing texts...")
    Xs = []

    # debug
    print("vocabulary length: {}".format(len(nlp.vocab)))

    for texts in texts_:
        Xs.append(get_word_ids(list(nlp.pipe(texts, n_threads=20, batch_size=20000)),
                               max_length=shape[0],
                               rnn_encode=settings['gru_encode'],
                               tree_truncate=settings['tree_truncate']))
    return Xs
```

I get the following error (formatted into several lines):
```bash
tensorflow.python.framework.errors_impl.InvalidArgumentError: 
indices[0,1] = 316259 is not in [0, 102897)
[[
Node: embed_1/Gather = Gather[Tindices=DT_INT32, 
     Tparams=DT_FLOAT, 
     validate_indices=true, 
     _device="/job:localhost/replica:0/task:0/cpu:0"]
     (embed/embeddings/read, _arg_words2_0_4)
]]
```
So basically I am encoding my word with a given embedding, larger than the one I am using in my model.

My code is based on:
[keras_parikh_entailment](https://github.com/explosion/spaCy/tree/v1.9.0/examples/keras_parikh_entailment)

So after loading my specific word embeddings, calling it from my 'nlp' variable does work. 
(based on its length)

But when 'get_word_ids' is ran:
```python

def get_word_ids(docs, rnn_encode=False, tree_truncate=False, max_length=100, nr_unk=100):
    Xs = numpy.zeros((len(docs), max_length), dtype='int32')

    for i, doc in enumerate(docs):

        # todo: debug => incorrect length
        if i < 5:
            print("len(doc.vocab)={}".format(len(doc.vocab)))
       ########################################

        if tree_truncate:
            if isinstance(doc, Span):
                queue = [doc.root]
            else:
                queue = [sent.root for sent in doc.sents]
        else:
            queue = list(doc)
        words = []

        while len(words) <= max_length and queue:
            word = queue.pop(0)
            if rnn_encode or (not word.is_punct and not word.is_space):
                words.append(word)
            if tree_truncate:
                queue.extend(list(word.lefts))
                queue.extend(list(word.rights))
        words.sort()

        for j, token in enumerate(words):
            if token.has_vector:
                Xs[i, j] = token.rank + 1
            else:
                Xs[i, j] = (token.shape % (nr_unk - 1)) + 2
            j += 1
            if j >= max_length:
                break
        else:
            Xs[i, len(words)] = 1

    # todo: debug, should be < to embedding length
    print("max value in Xs: {}".format(Xs.max()))
    #############################
    return Xs
```

So basically it keeps the initial embedding (from a previous message):
```python
# Example args
language='en'
word_vectors_path='embedding.vec'
skip_header=True


nlp = spacy.load(language)
# using a new vocabulary
del nlp.vocab
new_vocab = Vocab()
new_vocab.resize_vectors(300)
```

## Question
Is there a nice way to tell the language to only use my new embedding?

## What I plan to try
### plan 1
For every language attribute, I will set my new vocabulary.
### plan 2
Trying to build my 'own' language by setting each attribute.

**Comment by aurelien-clu** [comment]
```python
nlp.vocab = new_vocab
new_tokenizer = Tokenizer(
    vocab=new_vocab,
    rules=dict(),  # nlp.tokenizer._rules,
    prefix_search=nlp.tokenizer.prefix_search,
    suffix_search=nlp.tokenizer.suffix_search,
    infix_finditer=nlp.tokenizer.infix_finditer,
    token_match=nlp.tokenizer.token_match
)
nlp.tokenizer = new_tokenizer
```
Seems to be enough for my problem.

I will close the issue after a bit more testing and time unless someone tells me how to properly set
```python
Tokenizer(rules=...) 
```
or to properly redefine the vocabulary.
