### ISSUE TITLE
chinese make_doc : expected spacy.vocab.Vocab, got str

### ISSUE THREAD

**Issue by vishnunekkanti** [explosion/spaCy#1430]
## Your Environment

* Operating System: Ubuntu 17.04
* Python Version Used: 3.5.3
* spaCy Version Used: V2.0.0a7
* Environment Information: -

make_doc for chinese fails with Error, the stack trace 
x = Chinese("可通過每頁左上角的連結隨時調整")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vishnu/.virtualEnvs/spacy2/lib/python3.5/site-packages/spacy/language.py", line 179, in __init__
    make_doc = factory(self, **meta.get('tokenizer', {}))
  File "/home/vishnu/.virtualEnvs/spacy2/lib/python3.5/site-packages/spacy/language.py", line 70, in create_tokenizer
    infix_finditer=infix_finditer, token_match=token_match)
TypeError: Argument 'vocab' has incorrect type (expected spacy.vocab.Vocab, got str)

**Comment by vishnunekkanti** [comment]
#invalid
