### ISSUE TITLE
How to Add languages with Arabic Letters to spaCy?

### ISSUE THREAD

**Issue by mosynaq** [explosion/spaCy#1478]
Hi!
I am trying to add Persin to spaCy I followed almost everything which was said [here](https://spacy.io/docs/usage/adding-languages). But when I issue the below command
`python -m spacy train  fa fa-model fa-ud-train.json fa-ud-dev.json --n-iter 25  --no-ner`
I get some error that I don't know how to fix.

```bash
$ python -m spacy train  fa fa-model fa-ud-train.json fa-ud-dev.json --n-iter 25  --no-ner
Itn.	N weight	N feats	UAS	NER F.	Tag %	Token %
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/spacy/__main__.py", line 133, in <module>
    plac.Interpreter.call(CLI)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 1142, in call
    print(out)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 53, in raise_
    raise exc.with_traceback(tb)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 53, in raise_
    raise exc.with_traceback(tb)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/spacy/__main__.py", line 95, in train
    not no_parser, not no_ner, parser_L1)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/spacy/cli/train.py", line 40, in train
    entity_cfg, n_iter)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/spacy/cli/train.py", line 62, in train_model
    pos=tagger_cfg, deps=parser_cfg, ner=entity_cfg) as trainer:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/spacy/language.py", line 234, in train
    self.vocab = self.Defaults.create_vocab(self)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/spacy/language.py", line 42, in create_vocab
    tag_map=cls.tag_map, lemmatizer=lemmatizer)
  File "spacy/vocab.pyx", line 89, in spacy.vocab.Vocab.load (spacy/vocab.cpp:4742)
  File "/usr/lib/python3.5/pathlib.py", line 1151, in open
    opener=self._opener)
  File "/usr/lib/python3.5/pathlib.py", line 1005, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'fa-model/vocab/strings.json'
```
I have Persian UniversalDependency treebanks and have converted them to spaCy's expected json format.
I have added fa language to spaCy in MY-PY-ENVIRON virtualenv.

## Your Environment

* **installed models:** en, en_default
* **Platform:** Linux-4.11.0-14-generic-x86_64-with-LinuxMint-18.2-sonya
* **Python version:** 3.5.2
* **spaCy version:** 1.9.0

**Comment by ines** [comment]
Hm, the above example looks like your model directory might not be set up correctly? Did you build a vocabulary as well an run [`python -m spacy model`](https://spacy.io/docs/usage/adding-languages#model-directory)?

Sorry about the messy workflow by the way. We've been working on fixing this in the upcoming spaCy v2.0. The current alpha version, `v2.0.0a18` is pretty stable now and if we don't come across any significant bugs, it will become the release candidate. So it's pretty safe to use by now.

[See here](https://alpha.spacy.io/usage/adding-languages) for the adding languages guide in v2.0. Not much has changed, so it should be quick to convert your language data. It just needs to be moved into `lang/fa`, and you'll have to edit a few things in the `Language` subclass.

You can then use the new commands for creating the vocabulary and training:
* [`spacy vocab`](https://alpha.spacy.io/api/cli#vocab): create a vocabulary from simple, JSON-formatted [lexical data](https://alpha.spacy.io/api/annotation#vocab-jsonl) (you can even add word vectors in this step if you want)
* [`spacy train`](https://alpha.spacy.io/api/cli#train) – train the NN model, now with hyperparameters available as environment variables
* [`spacy evaluate`](https://alpha.spacy.io/api/cli#evaluate) – evaluate your model's accuracy and speed (also supports exporting visualizations)

**Comment by mosynaq** [comment]
Thanks, Ines! I have a plan to explore spaCy 2, but before that, I want to learn how to train version 1.x.
This is what I do and what happens: I when I try to train vocabularies using  `word_freqs.py` script, an exception happens. I pass a large corpus as `input_loc` parameter, and a non-existing folder name for `freqs_dir` named `freq`, and a non-existing file name for `output_loc`. Here is what I get:
```bash
$ python word_freqs.py -n 25 fa fa_edited.txt freq out
Traceback (most recent call last):
  File "word_freqs.py", line 93, in <module>
    plac.call(main)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/PATH/TO/PROJECT/MY-PY-ENVIRON/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "word_freqs.py", line 82, in main
    if not output_path.exists() or not skip_existing:
  File "/usr/lib/python3.5/pathlib.py", line 1306, in exists
    self.stat()
  File "/usr/lib/python3.5/pathlib.py", line 1126, in stat
    return self._accessor.stat(self)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 36] File name too long: 'freq/معاون سازمان سنجش آموزش کشور با تشریح جزئیات کنکور کارشناسی ارشداز صدورهزار وکارت ورود به جلسه این آزمون خبر داد و گفت: کارتهای ورود به جلسهآزمون ازبهمن ماه بر روی سایت سازمان سنجش آموزش کشور قرار می گیرد.ابراهیم خدایی در گفتگو با خبرنگار مهر افزود: در آزمون کارشناسی ارشد ناپیوسته داخل سالبرایکد رشته شاملکد رشته امتحانی در گروه علوم انسانی،کد رشته امتحانی در گروه علوم پایه،کد رشته در گروه فنی ومهندسی،کد رشته در گروه کشاورزی،کد رشته در گروه هنر،کد رشته در گروه علوم پزشکی ( فقط برای دانشگاه تربیت مدرس)،کد رشته در گروه دامپزشکی دانشجو پذیرش می شود. هزار وداوطلب در کنکورکارشناسی ارشد ثبت نام کرده اندوی اظهار داشت: ثبت نام در آزمون برایکد رشته امتحانی ازکد رشته امتحانی و همچنین اولین مرحله آزمون پانزدهمین المپیاد علمی دانشجویی کشور بر اساس برنامه زمانی به صورت متمرکز و از طریق شبکه اینترنت انجام شد. در آزمونکد رشته و اولین مرحله المپیادهزار وداوطلب ثبت نام کرده اند که از این تعدادهزار ونفر زن وهزار ونفر مرد هستند. هزار ونفر متقاضی شرکت در آزمون کد رشته امتحانی دوم کارشناسی ارشدمعاون سازمان سنجش آموزش کشور به مهر گفت: نظر به اینکه بر اساس ضوابط داوطلبان می توانستند در صورت واجد شرایط و علاقه مند بودن از میانکد رشته امتحانی شناور مندرج در دفترچه راهنما یکی از کد رشته های مذکور را به عنوان کد رشته امتحانی دوم علاوه بر کد رشته امتحانی اصلی انتخاب کنندهزار ونفر نیز متقاضی شرکت در آزمون کد رشته امتحانی دوم شده اند.جزئیات توزیع کارت آزمون کارشناسی ارشد وی با اشاره توزیع کارت آزمون کارشناسی ارشداضافه کرد: با توجه به اینکه آزمون هر کد رشته بهطور جداگانه برگزار می شود و هر داوطلب برای شرکت در آزمون هر کد رشته باید کارت مربوط را داشته باشد برای داوطلبانی که در دو کد رشته امتحانی ثبت نام کرده اند دو کارت ورود به جلسه صادر می شود.صدورهزار وکارت ورود به جلسه آزمونخدایی ادامه داد: از این روهزار وکارت ورود به جلسه آزمون صادر خواهد شد که از این تعدادهزار وکارت مربوط به خواهران وهزار وکارت مربوط به برادران می شود.توزیع کارت ورود به جلسه آزمون ارشد ازبهمن ماهوی ادامه داد: بر اساس برنامه زمانی کارت ورود به جلسه آزمون از طریق شبکه اینترنت سازمان سنجش ازبهمن ماه تابهمن ماه در اختیار داوطلبان قرار می گیرد.معاون سازمان سنجش آموزش کشور گفت: اطلاعیه سازمان سنجش آموزش کشور در رابطه با توزیع کارت اینترنتی در نشریه دوشنبهبهمن ماه وبهمن ماه منتشر و همزمان بر روی سایت قرار داده می شود. همچنین به منظور آشنایی داوطلبان با نحوه برگزاری آزمون و نحوه علامتگذاری در پاسخنامه برگه راهنمای شرکت در آزمون ازبهمن ماه بر روی سایت سازمان سنجش قرار میگیرد تا داوطلبان با مراجعه به سایت سازمان نسبت به مطالعه آن اقدام کنند.میزان تاثیر معدل در کنکور کارشناسی ارشدخدایی در زمینه تاثیر معدل در کنکور کارشناسی ارشد به مهر گفت: معدل کارشناسی در کنکور کارشناسی ارشد به میزاندرصد تأثیرگذار خواهد بود.وی گفت: ایندرصد در کنکور امسال نیز مانند سال گذشته به صورت تراز شده اعمال می شود.معاون سازمان سنجش درباره زمان برگزاری این کنکور نیز به مهر گفت: آزمون کارشناسی ارشد سالدر صبح و بعدازظهر ،وبهمنماه برگزار می شود.'
```
I am sure there is something wrong with the way I do the stuff, but I have no idea what it is. I looked into the official tutorial and github to for some guides or the same error but it ended up with nothing.
What should do to make it work?

**Comment by ines** [comment]
Hm, are you sure you're passing in the arguments correctly and there's no naming conflict within your script? The error here looks like it's trying to compose the output path of `freq/` + text from your corpus: 

```
OSError: [Errno 36] File name too long: 'freq/معاون سازمان سنجش آموزش کشور با تشریح جزئیات کنکور کارشناسی ارشداز صدورهزار وکارت ورود به جلسه این آزمون خبر داد و گفت: کارتهای ورود به جلسهآزمون ازبهمن ماه بر روی سایت سازمان سنجش آموزش کشور قرار می گیرد.ابراهیم خدایی در گفتگو با خبرنگار مهر افزود: در آزمون کارشناسی ارشد ناپیوسته داخل سالبرایکد رشته شاملکد رشته امتحانی در گروه علوم انسانی،کد رشته امتحانی در گروه علوم پایه،کد رشته در گروه فنی ومهندسی،کد رشته در گروه کشاورزی،کد رشته در گروه هنر،کد رشته در گروه علوم پزشکی ( فقط برای دانشگاه تربیت مدرس)،کد رشته در گروه دامپزشکی دانشجو پذیرش می شود. هزار وداوطلب در کنکورکارشناسی ارشد ثبت نام کرده اندوی اظهار داشت: ثبت نام در آزمون برایکد رشته امتحانی ازکد رشته امتحانی و همچنین اولین مرحله آزمون پانزدهمین المپیاد علمی دانشجویی کشور بر اساس برنامه زمانی به صورت متمرکز و از طریق شبکه اینترنت انجام شد. در آزمونکد رشته و اولین مرحله المپیادهزار وداوطلب ثبت نام کرده اند که از این تعدادهزار ونفر زن وهزار ونفر مرد هستند. هزار ونفر متقاضی شرکت در آزمون کد رشته امتحانی دوم کارشناسی ارشدمعاون سازمان سنجش آموزش کشور به مهر گفت: نظر به اینکه بر اساس ضوابط داوطلبان می توانستند در صورت واجد شرایط و علاقه مند بودن از میانکد رشته امتحانی شناور مندرج در دفترچه راهنما یکی از کد رشته های مذکور را به عنوان کد رشته امتحانی دوم علاوه بر کد رشته امتحانی اصلی انتخاب کنندهزار ونفر نیز متقاضی شرکت در آزمون کد رشته امتحانی دوم شده اند.جزئیات توزیع کارت آزمون کارشناسی ارشد وی با اشاره توزیع کارت آزمون کارشناسی ارشداضافه کرد: با توجه به اینکه آزمون هر کد رشته بهطور جداگانه برگزار می شود و هر داوطلب برای شرکت در آزمون هر کد رشته باید کارت مربوط را داشته باشد برای داوطلبانی که در دو کد رشته امتحانی ثبت نام کرده اند دو کارت ورود به جلسه صادر می شود.صدورهزار وکارت ورود به جلسه آزمونخدایی ادامه داد: از این روهزار وکارت ورود به جلسه آزمون صادر خواهد شد که از این تعدادهزار وکارت مربوط به خواهران وهزار وکارت مربوط به برادران می شود.توزیع کارت ورود به جلسه آزمون ارشد ازبهمن ماهوی ادامه داد: بر اساس برنامه زمانی کارت ورود به جلسه آزمون از طریق شبکه اینترنت سازمان سنجش ازبهمن ماه تابهمن ماه در اختیار داوطلبان قرار می گیرد.معاون سازمان سنجش آموزش کشور گفت: اطلاعیه سازمان سنجش آموزش کشور در رابطه با توزیع کارت اینترنتی در نشریه دوشنبهبهمن ماه وبهمن ماه منتشر و همزمان بر روی سایت قرار داده می شود. همچنین به منظور آشنایی داوطلبان با نحوه برگزاری آزمون و نحوه علامتگذاری در پاسخنامه برگه راهنمای شرکت در آزمون ازبهمن ماه بر روی سایت سازمان سنجش قرار میگیرد تا داوطلبان با مراجعه به سایت سازمان نسبت به مطالعه آن اقدام کنند.میزان تاثیر معدل در کنکور کارشناسی ارشدخدایی در زمینه تاثیر معدل در کنکور کارشناسی ارشد به مهر گفت: معدل کارشناسی در کنکور کارشناسی ارشد به میزاندرصد تأثیرگذار خواهد بود.وی گفت: ایندرصد در کنکور امسال نیز مانند سال گذشته به صورت تراز شده اعمال می شود.معاون سازمان سنجش درباره زمان برگزاری این کنکور نیز به مهر گفت: آزمون کارشناسی ارشد سالدر صبح و بعدازظهر ،وبهمنماه برگزار می شود.'
```

So you're calling `.exists()` on  `Path('freq/') / 'suuuper long text...'`, which causes pathlib to raise an error.

**Comment by mosynaq** [comment]
I just downloaded the script from spacy's developers' resources from Github, which is located [here](https://github.com/explosion/spacy-dev-resources/blob/master/training/word_freqs.py) and I found it from [here](https://spacy.io/docs/usage/adding-languages#word-frequencies) . The command I issue is:
`python word_freqs.py -n 25 fa fa_edited.txt freq out`
The script is not mine, but the only line is edited is the line 14 where instead of
`from spacy.en import English`
I did put
`from spacy.fa import Persian`
