### ISSUE TITLE
Connection Error while installing nlp models

### ISSUE THREAD

**Issue by kavin26** [explosion/spaCy#1510]
I'm getting the following error when downloading nlp models
command: `python3 -m spacy download en_core_web_sm`
error : `Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/spacy/__main__.py", line 30, in <module>
    plac.call(commands[command])
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/spacy/cli/validate.py", line 17, in validate
    r = requests.get(about.__compatibility__)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

## Your Environment

Info about spaCy

    Models                            
    Python version     3.5.2          
    Location           /usr/local/lib/python3.5/dist-packages/spacy
    spaCy version      2.0.1          
    Platform           Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial

Kindly guide me for installing nlp models.

**Comment by ines** [comment]
The models are downloaded from a URL via GitHub – maybe your request timed out, or your firewall or proxy settings got in the way?

You can always download the model manually via your browser via the [GitHub release](https://github.com/explosion/spacy-models/releases/tag/en_core_web_sm-2.0.0) (see the "Downloads" section at the bottom), and then install it via pip:

```bash
pip install /path/to/en_core_web_sm-2.0.0.tar.gz
```

This does pretty much the exact same thing as the built-in `spacy download` command, and lets you use the model as `nlp = spacy.load('en_core_web_sm')`.
