### ISSUE TITLE
IndexError on hyphenated tokens in PoS tagger training

### ISSUE THREAD

**Issue by petterhh** [explosion/spaCy#1519]
First of all, congratulations on the release of spaCy 2.0, which looks like a huge improvement so far!

However, I'm getting an error pretty early on when trying to train a PoS tagger. If one of the tokens in an input sentence contains a hyphen, e.g. "Per-Otto" (a Norwegian first name), I'm getting the following error:

>Traceback (most recent call last):
  File "spacy_tagger.py", line 101, in <module>
    plac.call(main(lang='nb'))
  File "spacy_tagger.py", line 77, in main
    nlp.update([text], [annotations], sgd=optimizer, losses=losses)
  File "/Users/petterhohle/.pyenv/versions/spacy/lib/python3.5/site-packages/spacy/language.py", line 391, in update
    gold = GoldParse(doc, **gold)
  File "gold.pyx", line 454, in spacy.gold.GoldParse.__init__
IndexError: list index out of range

Example sentence:
```
- Domprost Per-Otto Gullaksen , Fredrikstad | 
{'tags': ['PUNCT', 'NOUN', 'PROPN', 'PROPN', 'PUNCT', 'PROPN', 'PUNCT']}
#tokens: 7
#tags: 7
```

## Your Environment
* Operating System: macOS High Sierra
* Python Version Used: 3.5.2
* spaCy Version Used: 2.0.1

**Comment by honnibal** [comment]
Thanks!

There's a subtlety here that hadn't occurred to me before, that we should figure out how to get into the docs. We could definitely raise a better error too.

If you pass a list `words`, the `GoldParse` class will figure out how to align the tokenization in the `Doc` object against the tokenization in `words`. But if you *don't* pass `words`, it has to assume that the tokenization in your POS tags matches the tokenization in the `Doc` object.

I think the tokenization doesn't match here, which is why you're getting this error. You can fix it by passing the gold-standard tokenization in a list `words`.

**Comment by petterhh** [comment]
Figured it was something like that. But as I'm calling `nlp.update()`, and not `GoldParse()` directly, I can't pass the tokenization in a list `words`, as that is not a valid parameter.
https://github.com/explosion/spaCy/blob/75d2a05c2938f412f0fae44748374e4de19cc2be/spacy/language.py#L359

**Comment by ines** [comment]
Ah, so the `words` would be a keyword argument on the `GoldParse` object. This lets you specify the gold-standard tokenization, if it doesn't match spaCy's tokenization. Assuming your input looks like this:

```python
text = 'helloworld'
words = ['hello', 'world']
tags = ['INTJ', 'NOUN']
```

You can do the following:

```python
doc = Doc(text)
gold = GoldParse(doc, words=words, tags=tags)
nlp.update([doc], [gold])
```

Alternatively, you can also use the new ["simple training style"](https://spacy.io/usage/training#training-simple-style) and just pass in the text as a string, and the annotations as a dictionary:

```python
nlp.update([text], [{'words': words, 'tags': tags}])
```

In general, we'd recommend using the simple style, as it removes one layer of abstraction, and lets you get rid of the `Doc` and `GoldParse` inputs. But ultimately, the style you choose depends on your personal preference.

**Comment by petterhh** [comment]
Ah, got it. That worked – somewhat. Onto the next error (at line 1337, no less):
>Traceback (most recent call last):
  File "spacy_tagger.py", line 105, in <module>
    plac.call(main(lang='nb'))
  File "spacy_tagger.py", line 81, in main
    nlp.update([text], [{'words': words, 'tags': tags}], sgd=optimizer, losses=losses)
  File "/Users/petterhohle/.pyenv/versions/spacy/lib/python3.5/site-packages/spacy/language.py", line 407, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "pipeline.pyx", line 445, in spacy.pipeline.Tagger.update
  File "/Users/petterhohle/.pyenv/versions/spacy/lib/python3.5/site-packages/thinc/api.py", line 67, in continue_update
    gradient = callback(gradient, sgd)
  File "/Users/petterhohle/.pyenv/versions/spacy/lib/python3.5/site-packages/thinc/api.py", line 284, in finish_update
    d_X = bp_layer(layer.ops.flatten(d_seqs_out, pad=pad), sgd=sgd)
  File "/Users/petterhohle/.pyenv/versions/spacy/lib/python3.5/site-packages/thinc/check.py", line 146, in checked_function
    return wrapped(*args, **kwargs)
  File "/Users/petterhohle/.pyenv/versions/spacy/lib/python3.5/site-packages/thinc/neural/_classes/softmax.py", line 26, in finish_update
    self.d_W += self.ops.batch_outer(grad__BO, input__BI)
  File "ops.pyx", line 302, in thinc.neural.ops.NumpyOps.batch_outer
  File "/Users/petterhohle/.pyenv/versions/spacy/lib/python3.5/site-packages/numpy/core/numeric.py", line 1337, in tensordot
    at = a.transpose(newaxes_a).reshape(newshape_a)
ValueError: cannot reshape array of size 0 into shape (0)
