### ISSUE TITLE
Replacing a parser with a new parser and name and reloading model throws KeyError

### ISSUE THREAD

**Issue by sidazad** [explosion/spaCy#1551]
This is a bug that can be recreated by simply running the example in https://github.com/explosion/spacy/blob/master/examples/training/train_intent_parser.py

The example writes the model to disk correctly but when trying to reload it using it fails since it cannot find "intent-parser" in self.factories:

Here is the stack trace:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/dev/gittest/nlp_trainer/spacy_trainer2.py", line 123, in <module>
    plac.call(main)
  File "C:\dev\gittest\nlp_trainer\env\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\dev\gittest\nlp_trainer\env\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:/dev/gittest/nlp_trainer/spacy_trainer2.py", line 108, in main
    nlp2 = spacy.load(output_dir)
  File "C:\dev\gittest\nlp_trainer\env\lib\site-packages\spacy\__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "C:\dev\gittest\nlp_trainer\env\lib\site-packages\spacy\util.py", line 117, in load_model
    return load_model_from_path(name, **overrides)
  File "C:\dev\gittest\nlp_trainer\env\lib\site-packages\spacy\util.py", line 155, in load_model_from_path
    component = nlp.create_pipe(name, config=config)
  File "C:\dev\gittest\nlp_trainer\env\lib\site-packages\spacy\language.py", line 215, in create_pipe
    raise KeyError("Can't find factory for '{}'.".format(name))
KeyError: u"Can't find factory for 'intent-parser'."

Process finished with exit code 1

Environment:
- Windows 7
- Python 2.7.12
- Spacy 2.0.2
* Environment Information:

**Comment by ines** [comment]
Ah, sorry – this is a mistake in the example we introduced when we renamed the `'parser'` component to `'intent-parser'`. So by trying to make the example less confusing, we actually broke it, damn.

The problem here is that when you save out the model, the pipeline component names are saved to the model meta – but the saved model has no way of knowing that the custom component name `'intent-parser'` is supposed to initialise a spaCy's parser. 

I'll change the example back to use the component name `'parser'`. This makes it work as expected again. 

(Btw, in a production scenario, you might still want the distinction between spaCy's built-in parser and your custom parser. So the solution here would be to ship the custom pipeline component with your model. A spaCy model package is just a regular Python package with an `__init__.py` which creates the language class, sets up the pipeline and loads in the data. So so you can include any code you like and create the `nlp` object however you want. [See here](https://spacy.io/usage/training#models-custom) for more details on this.)
