### ISSUE TITLE
Problem with 'import spacy' in Spyder

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spaCy#1559]
I installed using `conda install -c conda-forge spacy` and all went through properly. However, when I wanted to import in Spyder: `import spacy`, I got the error:

```
import spacy
Traceback (most recent call last):

  File "<ipython-input-3-c080f6458562>", line 1, in <module>
    import spacy

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/cli/link.py", line 7, in <module>
    from ..compat import symlink_to, path2str

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/compat.py", line 11, in <module>
    from thinc.neural.util import copy_array

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
    from ..train import Trainer

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/thinc/neural/train.py", line 3, in <module>
    from .optimizers import Adam, SGD, linear_decay

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 458, in load_module
    language_level=self.language_level)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 233, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)

  File "optimizers.pyx", line 13, in init thinc.neural.optimizers

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 458, in load_module
    language_level=self.language_level)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 233, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)

  File "ops.pyx", line 1, in init thinc.neural.ops

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 458, in load_module
    language_level=self.language_level)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 233, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 499, in build_extension
    depends=ext.depends)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
    raise CompileError, msg

ImportError: Building module thinc.neural.optimizers failed: ['ImportError: Building module thinc.neural.ops failed: [\'ImportError: Building module murmurhash.mrmr failed: ["CompileError: command \\\'gcc\\\' failed with exit status 1\\\\n"]\\n\']\n']

Traceback (most recent call last):

  File "<ipython-input-3-c080f6458562>", line 1, in <module>
    import spacy

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/cli/link.py", line 7, in <module>
    from ..compat import symlink_to, path2str

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/spacy/compat.py", line 11, in <module>
    from thinc.neural.util import copy_array

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
    from ..train import Trainer

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/thinc/neural/train.py", line 3, in <module>
    from .optimizers import Adam, SGD, linear_decay

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 458, in load_module
    language_level=self.language_level)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 233, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)

  File "optimizers.pyx", line 13, in init thinc.neural.optimizers

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 458, in load_module
    language_level=self.language_level)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 233, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)

  File "ops.pyx", line 1, in init thinc.neural.ops

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 458, in load_module
    language_level=self.language_level)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 233, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()

  File "/home/kormilitzin/anaconda2/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 499, in build_extension
    depends=ext.depends)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)

  File "/home/kormilitzin/anaconda2/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
    raise CompileError, msg

ImportError: Building module thinc.neural.optimizers failed: ['ImportError: Building module thinc.neural.ops failed: [\'ImportError: Building module murmurhash.mrmr failed: ["CompileError: command \\\'gcc\\\' failed with exit status 1\\\\n"]\\n\']\n']
```

**Any ideas?**

## My Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

spaCy v2.0.2

Python 2.7.14 :: Anaconda custom (64-bit)

**Comment by ines** [comment]
Thanks for the report! This looks very similar to #1395 – the solution was installing `python3.6-dev` to get the correct headers:

> @honnibal: Just ran into this while provisioning a new server. I installed python3.6, so I needed the python3.6-dev package to get the headers.

Could you try and see if this works for you?

**Comment by akilesh1995** [comment]
Same error while trying to import spacy on spyder on OSX. 

spaCy v2.0.2
Python 2.7.14 :: Anaconda custom (64-bit)

**Comment by fdokshin** [comment]
Facing the same issue here also using spyder on OS X. Any tips?

spaCy v2.0.3
Python 2.7.13 :: Anaconda custom (x86_64)

**Comment by barseghyanartur** [comment]
Not sure if this is anyhow helpful for other folks, but my use-case was that I couldn't import `spacy` from `ipython` shell (which I use prefer to standard python shell). That simply didn't work. However, I am able to import `spacy` with no problems from [ptpython](https://github.com/jonathanslenders/ptpython).

**Comment by ines** [comment]
Thanks for updating! From what you describe, it really sounds like a problem with your `$PATH` and what's available in the Python environment. (One indicator of this could be that `which ipython` and `which ptpython` both point to completely different locations.)

I was looking around for a good summary of solutions for this and found [this wiki entry](https://github.com/landlab/landlab/wiki/Correcting-Install-Paths) pretty useful (even though it's related to some other package).
