### ISSUE TITLE
massive memory usage (>35GB) and segfault when loading 2.9MB of text

### ISSUE THREAD

**Issue by james-daily** [explosion/spaCy#1600]
Attempting to load the text of a long piece of federal legislation (HR 2491-104) leads to a spike in memory usage (>35GB on a machine with 64GB) followed by a segfault.  Here is a Gist with the text of the bill.

https://gist.github.com/james-daily/d1be7d9a6754931e83cfd0d949e674f2

Code to replicate is simple:
```
import spacy

nlp = spacy.load(u'en_core_web_sm')

f = open('hr2491-104b.txt', 'r')

text = unicode(f.read())

doc = nlp(text)
```

Pre 2.x versions handled this data without a problem.

## Your Environment
* **Python version:** 2.7.14
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **spaCy version:** 2.0.3
* **Models:** en

**Comment by brendandc** [comment]
I am getting segmentation faults on some large text files too, I was going to create an issue until I saw this one. On the chance it will help debug the issue, here are the marginally different details that I was going to report .

2.4MB text file
https://gist.githubusercontent.com/brendandc/2c8449a026beb619a7bc89e68b00d6d4/raw/ec7500701c17b7765bb53061dbebe9c8bc18d1c3/big_doc.txt

```
import io
import spacy
nlp = spacy.load("en_core_web_lg")
doc_text = io.open("big_doc.txt", "r", encoding='utf-8').read()
nlp_doc = nlp(doc_text)
```

Your Environment
* Operating System: Ubuntu 16.04.3 64bit
* Python Version Used: 2.7.12
* spaCy Version Used: 2.0.3
* Environment Information: r4.2xlarge EC2 instance (61GB memory)

The memory also spikes for me before the seg fault, watching `top` , I see it hit around 35% memory usage.

**Comment by honnibal** [comment]
Thanks, I should've tested this.

This makes sense in hindsight: if we embed all words of the document, we end up using a lot of memory. Then temporaries might be around through the forward pass, causing even a large system to go OOM.

I think spaCy models should have an explicit memory budget, so we know how to size VMs. We can still process large documents by streaming the text, but this will take a little bit of implementation. For now the best workaround is to find places to cut your documents.

**Comment by wejradford** [comment]
Hi @honnibal and @ines, 

We're a somewhat impacted by large spaCy doc sizes (thankfully not a large as the ones above 😱). Our docs are large enough that they're taking a non-trivial amount of space. I've been hacking up a solution and just want to make sure that I know about all the implications and check that I've understood.

### Dumb solution: repack the serialised doc without `tensor`

From mentions in this ticket and #1636, my guess is that the space is taken largely by the embedded version of the document used to predict POS, entity and dependency labels -- i.e. `doc.tensor`.

If we want to trade lightweight serialised docs for utility, it __looks__ like we can simply trim them off. Digging around in the representation is almost always a **really bad idea**:tm:, but I seem to be able to deserialise the document again without too many ill-effects. 

#### Question

What downstream operations are blocked if I start arbitrarily nuking `tensor`? I can also imagine replacing the values from the model as you're calling `.from_bytes()`, but you'd need to ensure that you were using the same vocab, etc.

#### Example

```python
# Assumes nlp, raw and doc in scope.
import gzip
import humanfriendly
import msgpack

def remove_tensor(nlp, doc):
    payload = msgpack.loads(doc.to_bytes())
    payload['tensor'] = None
    thin_doc = Doc(nlp.vocab)
    thin_doc.from_bytes(msgpack.dumps(payload))
    return thin_doc

print('{:>10}\tRaw string ({} words)'.format(humanfriendly.format_size(len(raw)), len(doc)))
print('{:>10}\tDoc'.format(humanfriendly.format_size(len(doc.to_bytes()))))
print('{:>10}\tDoc.gzip'.format(humanfriendly.format_size(len(gzip.compress(doc.to_bytes())))))
print('{:>10}\tThin'.format(humanfriendly.format_size(len(remove_tensor(nlp, doc).to_bytes()))))
print('{:>10}\tThin.gzip'.format(humanfriendly.format_size(len(gzip.compress(remove_tensor(nlp, doc).to_bytes())))))
```

#### Output
```
  28.91 KB	Raw string (5588 words)
   9.17 MB	Doc
   8.16 MB	Doc.gzip
 589.65 KB	Thin
 137.38 KB	Thin.gzip
```

**Comment by honnibal** [comment]
@wejradford You can kill `tensor`. It's not read in by the other models -- we need a flag to get rid of it, it's not even very useful.

**Comment by wejradford** [comment]
Thanks @honnibal, this works well for me!

**Comment by honnibal** [comment]
No problem -- btw note that you could add an extension attribute to do custom serialization, e.g. `doc._.to_docrep()` or `doc._.from_docrep()`.

**Comment by robinarthur** [comment]
hey @wejradford ,

thank you for your solution. I want to use this workaround but i didnt get it to work.
i made this little example:
**Input**
`
# test the remove tensor function
import de_core_news_sm
import spacy
import msgpack

text = 'Der Zug, der am Montag gegen 15 Uhr aus Richtung Nordkorea.'

def remove_tensor(nlp, doc):
    # taken from here:
    # https://github.com/explosion/spaCy/issues/1600
    doc = doc.encode()
    payload = msgpack.loads(doc)
    payload['tensor'] = None
    thin_doc = Doc(nlp.vocab)
    print(5)
    thin_doc.from_bytes(msgpack.dumps(payload))
    return thin_doc

nlp = de_core_news_sm.load()
print("spacy load - Done")

doc = remove_tensor(nlp, text)
`

**Output**
and i get the following error:
`
ExtraData: unpack(b) received extra data.
`

**Comment by wejradford** [comment]
Hi @robinarthur, I think the formatting messed up your code example, but the when the `payload = msgpack.loads(doc)` statement is executed, `doc` is a `bytes` object rather than a spaCy `Doc` object.

For example:
```
>>> import msgpack
>>> msgpack.loads(b'Hello')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 208, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2717)
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

**Comment by bdewilde** [comment]
FWIW I recently implemented a function in `textacy` that splits a (long) text into more manageable chunks, runs each through a language pipeline, then concatenates the results at the end: https://chartbeat-labs.github.io/textacy/api_reference.html#textacy.spacier.utils.make_doc_from_text_chunks

**Comment by wejradford** [comment]
@honnibal one place I recently found this was problematic was loading up with displacy, where a token wasn't happy with a `None` vector IIRC.
