### ISSUE TITLE
Issue with the dill module

### ISSUE THREAD

**Issue by iethan** [explosion/spaCy#1628]
On importing the spacy module `import spacy` I receive the following error:

```
Traceback (most recent call last):
  File "keyword_matrix.py", line 401, in <module>
    import spacy
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/spacy/cli/__init__.py", line 6, in <module>
    from .train import train
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/spacy/cli/train.py", line 6, in <module>
    import dill
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dill/__init__.py", line 27, in <module>
    from .dill import dump, dumps, load, loads, dump_session, load_session, \
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dill/dill/__init__.py", line 59, in <module>
    from . import objtypes as types
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dill/dill/objtypes.py", line 18, in <module>
    from dill import objects
ImportError: cannot import name 'objects'
```
I've upgraded dill but still having the same issue.

## Your Environment

* Operating System: Mac OS SIerra
* Python Version Used: Python 3.4
* spaCy Version Used: spacy==2.0.3
* Environment Information: N/A

**Comment by honnibal** [comment]
Could you try again with the new version? I think it should be fixed. Python 3.4 might also be at fault.
