### ISSUE TITLE
spaCy 2.0 incompatible with PowerPC (needs numpy header update)

### ISSUE THREAD

**Issue by scheckley** [explosion/spaCy#1635]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "usr/local/python2/spacy/2.0.3/lib/python2.7/site-packages/spacy-2.0.3-py2.7-linux-ppc64le.egg/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "usr/local/apps/python2/spacy/2.0.3/lib/python2.7/site-packages/spacy-2.0.3-py2.7-linux-ppc64le.egg/spacy/cli/__init__.py", line 6, in <module>
    from .train import train
  File "usr/local/apps/python2/spacy/2.0.3/lib/python2.7/site-packages/spacy-2.0.3-py2.7-linux-ppc64le.egg/spacy/cli/train.py", line 13, in <module>
    from ..gold import GoldCorpus, minibatch
  File "morphology.pxd", line 25, in init spacy.gold
  File "vocab.pxd", line 27, in init spacy.morphology
  File "lexeme.pxd", line 14, in init spacy.vocab
  File "lexeme.pyx", line 8, in init spacy.lexeme
  File "__init__.pxd", line 989, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

## Environment
IBM Power8
* Operating System: Red Hat Enterprise Linux Server release 7.3 (Maipo), kernel: Red Hat Enterprise Linux Server release 7.3 (Maipo)
* Python Version Used: 2.7.8, gcc 4.8.5 20150623
* spaCy Version Used: latest version from pip

**Comment by scheckley** [comment]
Turns out there are some old Numpy headers in the package, the solution is to update them and is documented here: https://github.com/explosion/spaCy/issues/1592

**Comment by honnibal** [comment]
Trying to fix this: https://github.com/explosion/spaCy/pull/1842

**Comment by ines** [comment]
Merging this with #1592!
