### ISSUE TITLE
Error while installing English language model

### ISSUE THREAD

**Issue by pskanade** [explosion/spaCy#1641]
Hi There,
I am trying to install english language model on high-sierra but encountered some problem.
```
pskanade@Pranavs-MacBook-Air:~|⇒  python -m spacy download en
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/pskanade/DevEnv/DeepLearning/env/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Users/pskanade/DevEnv/DeepLearning/env/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Users/pskanade/DevEnv/DeepLearning/env/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/Users/pskanade/DevEnv/DeepLearning/env/lib/python3.6/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..util import prints
  File "/Users/pskanade/DevEnv/DeepLearning/env/lib/python3.6/site-packages/spacy/util.py", line 8, in <module>
    import regex as re
  File "/Users/pskanade/DevEnv/DeepLearning/env/lib/python3.6/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/Users/pskanade/DevEnv/DeepLearning/env/lib/python3.6/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/Users/pskanade/DevEnv/DeepLearning/env/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Users/pskanade/DevEnv/DeepLearning/env/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

I followed following commands to install :
```
- pip install -U spacy
- python -m spacy download en
```
am I missing something .. ?? 
please help..!

Thanks,
Pranav Kanade

**Comment by pskanade** [comment]
Got it, It's os problem:
added following lines to ~/.zshrc
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
