### ISSUE TITLE
Spacy installation is failing with pip

### ISSUE THREAD

**Issue by riemannzeta1191** [explosion/spaCy#1656]
Installation is failing with pip install.The trace is as follows:-

```
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/spacy
/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), 
file, 'exec'))" install --record /tmp/pip-euiwj5r4-record/install-record.txt 
--single-version-externally-managed --compile failed with error code -9 in 
/tmp/pip_build_root/spacy
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, args, *kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools,
 tokenize;__file__='/tmp/pip_build_root/spacy/setup.py';exec(compile(getattr(tokenize, 'open', 
open)(__file__).read().replace('\r\n', '\n'), file, 'exec'))" install --record 
/tmp/pip-euiwj5r4-record/install-record.txt --single-version-externally-managed 
--compile failed with error code -9 in /tmp/pip_build_root/spacy.
```

## 

* Operating System: Ubuntu 14.04
* Python Version Used: 3.4.3
* spaCy Version Used: 2.0.2
* Environment Information:

**Comment by psukys** [comment]
@riemannzeta1191 did you resolve your problems? For the same failure point I got the following error:

    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    error: command 'gcc' failed with exit status 1

Installing `gcc-c++` (on Fedora 27) solved the problem.

**Comment by boxabirds** [comment]
If it helps I ran into this error when I was running on a virtual machine with just 1GB RAM. Resizing to 2.5GB RAM solved the problem.
