### ISSUE TITLE
Replace  vectors file with another one created from fastText vectors cause an error

### ISSUE THREAD

**Issue by PricelessRabbit** [explosion/spaCy#1661]
Hi all. I've an issue with the vectors of the model.
I used the script in the spacy doc to import in the model the  fastText vectors (italian language). Then i saved the model with the to_disk() method.
If I recall the model with from_disk() and use it everything works fine (with the new vectors).
I also tried to load a model with nlp.load("it") and update the vectors and everything works.
But if I substitue the vectors and key2row files in the original model (it_core_news_sm) I get this error when I try to load the model:

```
Traceback (most recent call last):
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/spacy-test.py", line 4, in <module>
    nlp=spacy.load("it")
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/spacy/util.py", line 131, in load_model_from_link
    return cls.load(**overrides)
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/spacy/data/it/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/spacy/util.py", line 176, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/spacy/util.py", line 158, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/spacy/language.py", line 626, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/spacy/util.py", line 521, in from_disk
    reader(path / key)
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/spacy/language.py", line 622, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "nn_parser.pyx", line 896, in spacy.syntax.nn_parser.Parser.from_disk
  File "/home/mattia/Projects/Mine/progetto-chatbot/word2vec-test/env/local/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 351, in from_bytes
    dest = getattr(layer, name)
AttributeError: 'FunctionLayer' object has no attribute 'vectors'
```

To be more precise I'm working in a virtualenv with pip, after downloading the "it" package i updated the vectors with the script and save the vectors file in a folder.Then I copied the vectors file into env/python/....../it_core_news_sm/it_core_news_sm-2.0.0/vocab

I also tried to save all the model with the to_disk() method, but if i use spacy.load("./my_model") to load it i get the same error

UPDATE:
the problem seems to be in the vector file. if i copy all the other files the error doesn't appear.when i copy the vector file i get the error.

UPDATE 2: tried also to create a pip package with the cli script in the doc from the model I saved in the hd but nothing. Seems that if I use directly nlp.from_disk("model") is ok but if i use spacy.load("package") it crash 

## Your Environment

* Operating System: Linux Mint 
* Python Version Used: 3.5.2
* spaCy Version Used: 2.0.3

**Comment by honnibal** [comment]
I believe this should be fixed in the patch for #1727 . Thanks for reporting.
