### ISSUE TITLE
DependencyParser - TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by giullianomorroni** [explosion/spaCy#1702]
I'm trying to execute some tests, but I'm not able to go forward, this is my code...

``
from spacy.pipeline import DependencyParser
import spacy

nlp = spacy.load('pt_core_news_sm')
parser = DependencyParser(nlp.vocab)

doc = nlp(u"estava tentando encerrar minha conta e deu atendimento concluido.")
parser(doc)
``

And thats the error:

Traceback (most recent call last):
  File "/development/workspace/python/dependency.py", line 13, in <module>
    parser(doc)
  File "nn_parser.pyx", line 340, in spacy.syntax.nn_parser.Parser.__call__
  File "nn_parser.pyx", line 403, in spacy.syntax.nn_parser.Parser.parse_batch
  File "nn_parser.pyx", line 723, in spacy.syntax.nn_parser.Parser.get_batch_model
TypeError: 'bool' object is not iterable

## Info about spaCy
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **Python version:** 3.5.1
* **spaCy version:** 2.0.5

**Comment by honnibal** [comment]
The model for the parser is not initialized until you either load the weights (with `.from_disk()` or `.from_bytes()` methods, or initialize with `.begin_training()`.
