### ISSUE TITLE
Loading en_vectors_web_lg results in ValueError

### ISSUE THREAD

**Issue by geokat** [explosion/spaCy#1709]
```bash
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.load('en_vectors_web_lg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/geo/.python/local/lib/python2.7/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/home/geo/.python/local/lib/python2.7/site-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/geo/.python/local/lib/python2.7/site-packages/spacy/util.py", line 137, in load_model_from_package
    return cls.load(**overrides)
  File "/home/geo/.python/local/lib/python2.7/site-packages/en_vectors_web_lg/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/geo/.python/local/lib/python2.7/site-packages/spacy/util.py", line 176, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/geo/.python/local/lib/python2.7/site-packages/spacy/util.py", line 158, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/geo/.python/local/lib/python2.7/site-packages/spacy/language.py", line 629, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/geo/.python/local/lib/python2.7/site-packages/spacy/util.py", line 521, in from_disk
    reader(path / key)
  File "/home/geo/.python/local/lib/python2.7/site-packages/spacy/language.py", line 616, in <lambda>
    ('vocab', lambda p: self.vocab.from_disk(p)),
  File "vocab.pyx", line 376, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 369, in spacy.vectors.Vectors.from_disk
  File "/home/geo/.python/local/lib/python2.7/site-packages/spacy/util.py", line 521, in from_disk
    reader(path / key)
  File "vectors.pyx", line 362, in spacy.vectors.Vectors.from_disk.load_vectors
  File "/home/geo/.python/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 419, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/geo/.python/local/lib/python2.7/site-packages/numpy/lib/format.py", line 681, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 275667948 into shape (1070971,300)
```

## Info about spaCy

* **Python version:** 2.7.9
* **Platform:** Linux-4.9.0-4-amd64-x86_64-with-debian-9.2
* **spaCy version:** 2.0.5
* **Models:** en

**Comment by honnibal** [comment]
Could you run `spacy validate`? I just want to make sure you're using the correct version of the `en_vectors_web_lg` package

**Comment by geokat** [comment]
```$ spacy validate

    Installed models (spaCy v2.0.5)
    /home/geo/.python/local/lib/python2.7/site-packages/spacy

    TYPE        NAME                  MODEL                 VERSION                                   
    package     en-vectors-web-lg     en_vectors_web_lg     2.0.0    ✔      
    package     en-core-web-sm        en_core_web_sm        2.0.0    ✔      
    package     en-core-web-lg        en_core_web_lg        2.0.0    ✔      
    link        en                    en_core_web_sm        2.0.0    ✔      
```

**Comment by ai-claire** [comment]
Facing the same issue on python 3

**Comment by henninglebbaeus** [comment]
I trained a model for text classification based on **en-vectors-web-lg** and saved it to disk. 
When I try to load the module from the path, I get a similar error message like above. 

Environment:

- Python 3.5.4
- Spacy 2.0.4
- en_vectors_web_lg 2.0.0
- Windows

```
ValueError                                Traceback (most recent call last)
<ipython-input-18-f6161dc5b452> in <module>()
----> 1 nlp = spacy.load(model_path)

~\AppData\Local\Continuum\Miniconda3\envs\ai_env\lib\site-packages\spacy\__init__.py in load(name, **overrides)
     17             "to load. For example:\nnlp = spacy.load('{}')".format(depr_path),
     18             'error')
---> 19     return util.load_model(name, **overrides)
     20 
     21 

~\AppData\Local\Continuum\Miniconda3\envs\ai_env\lib\site-packages\spacy\util.py in load_model(name, **overrides)
    116             return load_model_from_path(Path(name), **overrides)
    117     elif hasattr(name, 'exists'):  # Path or Path-like to model data
--> 118         return load_model_from_path(name, **overrides)
    119     raise IOError("Can't find model '%s'" % name)
    120 

~\AppData\Local\Continuum\Miniconda3\envs\ai_env\lib\site-packages\spacy\util.py in load_model_from_path(model_path, meta, **overrides)
    156             component = nlp.create_pipe(name, config=config)
    157             nlp.add_pipe(component, name=name)
--> 158     return nlp.from_disk(model_path)
    159 
    160 

~\AppData\Local\Continuum\Miniconda3\envs\ai_env\lib\site-packages\spacy\language.py in from_disk(self, path, disable)
    627         if not (path / 'vocab').exists():
    628             exclude['vocab'] = True
--> 629         util.from_disk(path, deserializers, exclude)
    630         self._path = path
    631         return self

~\AppData\Local\Continuum\Miniconda3\envs\ai_env\lib\site-packages\spacy\util.py in from_disk(path, readers, exclude)
    519     for key, reader in readers.items():
    520         if key not in exclude:
--> 521             reader(path / key)
    522     return path
    523 

~\AppData\Local\Continuum\Miniconda3\envs\ai_env\lib\site-packages\spacy\language.py in <lambda>(p, proc)
    623             if not hasattr(proc, 'to_disk'):
    624                 continue
--> 625             deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
    626         exclude = {p: False for p in disable}
    627         if not (path / 'vocab').exists():

pipeline.pyx in spacy.pipeline.Pipe.from_disk()

~\AppData\Local\Continuum\Miniconda3\envs\ai_env\lib\site-packages\spacy\util.py in from_disk(path, readers, exclude)
    519     for key, reader in readers.items():
    520         if key not in exclude:
--> 521             reader(path / key)
    522     return path
    523 

pipeline.pyx in spacy.pipeline.Pipe.from_disk.load_model()

~\AppData\Local\Continuum\Miniconda3\envs\ai_env\lib\site-packages\thinc\neural\_classes\model.py in from_bytes(self, bytes_data)
    350                         name = name.decode('utf8')
    351                     dest = getattr(layer, name)
--> 352                     copy_array(dest, param[b'value'])
    353                 i += 1
    354             if hasattr(layer, '_layers'):

~\AppData\Local\Continuum\Miniconda3\envs\ai_env\lib\site-packages\thinc\neural\util.py in copy_array(dst, src, casting, where)
     46 def copy_array(dst, src, casting='same_kind', where=None):
     47     if isinstance(dst, numpy.ndarray) and isinstance(src, numpy.ndarray):
---> 48         dst[:] = src
     49     elif isinstance(dst, cupy.ndarray):
     50         src = cupy.array(src, copy=False)

ValueError: could not broadcast input array from shape (64) into shape (64,1)
```

**Comment by ines** [comment]
This should be fixed in the latest releases – if not, feel free to reopen!

**Comment by tippi76** [comment]
Hi, I'm facing the same issue with spacy==2.0.9, model being en_core_web_lg and python version 3.5.2. It's running fine on Windows 8.1 while running it inside a container with corresponding Linux dependencies gives the following error:

Traceback (most recent call last):
  File "/spacyner-env/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/spacyner-env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/spacyner-env/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/spacyner-env/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/spacyner-env/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/spacyner-env/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/spacyner-env/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/spacyner-env/lib/python3.5/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/spacyner-env/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/spacyner-env/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/spacyner-env/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/spacyner-env/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/spacyner-env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/dl-nlp/ner/urls.py", line 30, in <module>
    path('', include('spacyner.urls')),
  File "/spacyner-env/lib/python3.5/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/spacyner-env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/dl-nlp/spacyner/urls.py", line 11, in <module>
    from . import views
  File "/dl-nlp/spacyner/views.py", line 20, in <module>
    nlp= spacy.load(model_path)
  File "/spacyner-env/lib/python3.5/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/spacyner-env/lib/python3.5/site-packages/spacy/util.py", line 117, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/spacyner-env/lib/python3.5/site-packages/spacy/util.py", line 159, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/spacyner-env/lib/python3.5/site-packages/spacy/language.py", line 638, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/spacyner-env/lib/python3.5/site-packages/spacy/util.py", line 522, in from_disk
    reader(path / key)
  File "/spacyner-env/lib/python3.5/site-packages/spacy/language.py", line 625, in <lambda>
    ('vocab', lambda p: self.vocab.from_disk(p)),
  File "vocab.pyx", line 383, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 372, in spacy.vectors.Vectors.from_disk
  File "/spacyner-env/lib/python3.5/site-packages/spacy/util.py", line 522, in from_disk
    reader(path / key)
  File "vectors.pyx", line 365, in spacy.vectors.Vectors.from_disk.load_vectors
  File "/spacyner-env/lib/python3.5/site-packages/numpy/lib/npyio.py", line 421, in load
    pickle_kwargs=pickle_kwargs)
  File "/spacyner-env/lib/python3.5/site-packages/numpy/lib/format.py", line 688, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 161740780 into shape (684831,300)

**Comment by james-daily** [comment]
I get the same problem with spacy 2.0.11 and Python 2.7.14 on Linux.  `spacy validate` says en_core_web_lg 2.0.0 is fine.

I don't have the problem on OS X.
