### ISSUE TITLE
Problem with spacy.load('en')

### ISSUE THREAD

**Issue by jianzhengming** [explosion/spaCy#1721]
I have some related issues, I download the 'en' model,
$ python3 -m spacy download en $, yield
Linking sucessful
/home/abc/miniconda3/lib/python3.6/site-packages/en_core_web_sm -->
/home/abc/miniconda3/lib/python3.6/site-packages/spacy/data/en

You can now load the model via spacy.load('en')

However, when I use it
$nlp=spacy.load('en')$
I still get the information "OSError: Can't find model 'en'"

**Comment by sameerkumar16** [comment]
I am getting the same problem for every model .I can link every model to a string like 'en' ,'en_core_web_md' etc .But While loading it throws the following error .
`>>> nlp= spacy.load('en_core_web_md')
Traceback (most recent call last):
  File "/home/sameer/anaconda2/envs/py34/lib/python3.4/site-packages/spacy/util.py", line 126, in load_model_from_link
    cls = import_file(name, path)
  File "/home/sameer/anaconda2/envs/py34/lib/python3.4/site-packages/spacy/compat.py", line 118, in import_file
    module = importlib.util.module_from_spec(spec)
AttributeError: 'module' object has no attribute 'module_from_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sameer/anaconda2/envs/py34/lib/python3.4/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/home/sameer/anaconda2/envs/py34/lib/python3.4/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/sameer/anaconda2/envs/py34/lib/python3.4/site-packages/spacy/util.py", line 130, in load_model_from_link
    "points to a valid package (not just a data directory)." % name)
OSError: Cant' load 'en_core_web_md'. If you're using a shortcut link, make sure it points to a valid package (not just a data directory).
>>> 
`
Essentially It means I can't link the model even after creating links .What could be the problem .I am running my setup in a conda virtual environment

**Comment by bharathjatoth** [comment]
Please try to install this and see 
conda install spacy
python -m spacy.en.download
python -c "import spacy; spacy.load('en')"

**Comment by ines** [comment]
Looks like this is the same issue as #1761, so merging both to keep everything in one place. I also just submitted a fix that will hopefully solve the underlying problem – see #1792.

**Comment by Ashish-Gupta03** [comment]
Try this....
pip install spacy && python -m spacy download en

This worked for me.

**Comment by FrancescoSaverioZuppichini** [comment]
I have installed with `Python3`, if I try to run `python3 -m spacy download en` I get this error:

```
raceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/usr/local/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/usr/local/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/usr/local/lib/python3.6/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..util import prints
  File "/usr/local/lib/python3.6/site-packages/spacy/util.py", line 8, in <module>
    import regex as re
  File "/usr/local/lib/python3.6/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/usr/local/lib/python3.6/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Comment by bharathjatoth** [comment]
looks like the same issue  [https://github.com/explosion/spaCy/issues/1684](url). You can try this and post your results here

**Comment by soumendrak** [comment]
This worked for me.

`pip install spacy && python -m -U spacy download en`

**Comment by FrancescoSaverioZuppichini** [comment]
I can't, I have python3 and `python` does not exist as a command

**Comment by whyboris** [comment]
I think this might work with python3
`pip3 install spacy && python3 -m spacy download en`

**Comment by FrancescoSaverioZuppichini** [comment]
nope

**Comment by AlbertoTP** [comment]
Yea, try with conda
@whyboris  in Python3 works

and in python 2.7 have an error to download link
you can check, with this command, the install models:
python -m spacy validate
here, you can see the model "en":
type link, name en, model ..., ver...

try the command:
sudo python -m spacy download en
wait a moment and you can see:
You can now load the model via spacy.load('en')

if you see Error: Couldn't link model to 'en'
you use
nlp = spacy.load('en_core_web_sm')
and works

**Comment by bharathjatoth** [comment]
simple which worked for me is install the wheel packages which we get from https://www.lfd.uci.edu/~gohlke/pythonlibs/ 
search for relevant wheel package and install them just by "pip install <wheel package>"

**Comment by deenaik** [comment]
@FrancescoSaverioZuppichini 
If you have faced the error on MacOS X, here's the quick fix - add these lines to your ~/.bash_profile:

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you, it works!

**Comment by robertpknight** [comment]
I have updated both ~/.bash_profile and ~/.bash_profile.pysave. Still no luck, keep getting:

ValueError: unknown locale: UTF-8

Any other fixes?
