### ISSUE TITLE
Can't download language model

### ISSUE THREAD

**Issue by kuchenrolle** [explosion/spaCy#1722]
I just installed spacy 2.0.4 and tried to download the en_core_web_lg model, but I get an error message:

```
Installing collected packages: thinc
  Found existing installation: thinc 6.10.0
    Uninstalling thinc-6.10.0:
Exception:
Traceback (most recent call last):
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/site-packages/thinc' -> '/scratch/777201.1.rse.q/pip-ll9tu8ob-uninstall/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/site-packages/thinc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/shutil.py", line 556, in move
    rmtree(src)
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/kuchenrolle/.conda/envs/sharc/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs000000000008d2d1000000a6'

```

If I understand this right, then the problem is that the files for thinc are temporarily stored under /scratch, which is mounted, and then they cannot be moved to my local environment directory. I am working on a server with user and not admin right, how can I solve this?

## My Environment
* Operating System: Linux 
* Python Version Used: 3.6
* spaCy Version Used: 2.0.4
* Environment Information: conda (environment called "sharc")

**Comment by ines** [comment]
Just to confirm: The above happens when you install a model after installing spaCy, right? 

I think what might be happening here is that it tries to install the model's dependencies via pip when you run `spacy download`. This is because under the hood, the command uses pip to install a model package (a simple Python package) from a file. As a workaround, you could just download and install the models directly from a URL (see the [`spacy-models` releases](https://github.com/explosion/spacy-models/releases)). 

To be safe, you can also tell it to ignore the dependencies via `--no-deps`. For example:

```bash
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz --no-deps
```

Alternatively, you can also download the file first and then install it from a local directory. If you prefer to do things manually, you can also extract the archive, put the data directory wherever you want and create a shortcut link, or load the model from a path – see [this page in the docs](https://spacy.io/usage/models#download-manual) for more info.

**Comment by kuchenrolle** [comment]
Yes, the problem occurred when installing a model after installing spaCy. Installing it directly from the URL worked, though I had to install the dependencies as well (otherwise importing spaCy threw an error, complaining that it couldn't find 'thinc.extra._vendorized').

Thanks!

**Comment by ZVengin** [comment]
you can run `conda install regex` first and run `conda install thinc` and finally run `python -m spacy download en`
