### ISSUE TITLE
OSError: Cant' load 'en'. If you're using a shortcut link, make sure it points to a valid package (not just a data directory).

### ISSUE THREAD

**Issue by vinay1986** [explosion/spaCy#1770]
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load('en')
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/spacy/util.py", line 126, in load_model_from_link
    cls = import_file(name, path)
  File "/usr/local/lib/python3.4/dist-packages/spacy/compat.py", line 118, in import_file
    module = importlib.util.module_from_spec(spec)
AttributeError: 'module' object has no attribute 'module_from_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.4/dist-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/usr/local/lib/python3.4/dist-packages/spacy/util.py", line 130, in load_model_from_link
    "points to a valid package (not just a data directory)." % name)
OSError: Cant' load 'en'. If you're using a shortcut link, make sure it points to a valid package (not just a data directory).

## Environment

* Operating System: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

* Python version: 3.4.3
* Models: en
* Platform: Linux-4.9.17-c9-x86_64-with-Ubuntu-14.04-trusty
* spaCy version: 2.0.5

**Comment by ines** [comment]
Thanks – looks like this is the same issue as #1733. Merging this to keep things in one place!
