### ISSUE TITLE
spacy init-model not working

### ISSUE THREAD

**Issue by mosynaq** [explosion/spaCy#1810]
I have my brown cluster, frequency, and word vectors. When I issue the following
`$ python3 -m spacy init-model fa output freqs --vectors-loc fa_wiki.word2vec`
I get this:
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command])
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 324, in call
    parser = parser_from(obj)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 133, in parser_from
    parser.populate_from(obj)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 257, in populate_from
    a = Annotation.from_(ann)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 91, in from_
    return cls(*obj)
  File "/usr/local/lib/python3.5/dist-packages/plac_core.py", line 78, in __init__
    assert abbrev is None, abbrev
AssertionError: f
```

## Your Environment
* **Platform:** Linux-4.11.0-14-generic-x86_64-with-LinuxMint-18.3-sylvia
* **Models:** en, es
* **spaCy version:** 2.0.5
* **Python version:** 3.5.2

**Comment by ines** [comment]
Thanks and sorry about that. This has already been fixed in #1789 and will be included in the next release!
