### ISSUE TITLE
bug with Joblib example

### ISSUE THREAD

**Issue by wkerzendorf** [explosion/spaCy#1862]
## Info about spaCy

* **spaCy version:** 2.0.4
* **Platform:** Linux-2.6.32-642.11.1.el6.x86_64-x86_64-with-redhat-6.7-Carbon
* **Python version:** 3.6.4
* **Models:** en_core_web_lg

running the joblib example from the github repo results in the following problem:

```python
python multi_processing.py test_imdb en_core_web_lg
Loaded model 'en_core_web_lg'
Loading IMDB data...
Downloading data from http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
83836928/84125825 [============================>.] - ETA: 0sUntaring file...
Processing texts...
Traceback (most recent call last):
  File "multi_processing.py", line 78, in <module>
    plac.call(main)
  File "/home/wkerzend/miniconda2/envs/deepthought3/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/wkerzend/miniconda2/envs/deepthought3/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "multi_processing.py", line 42, in main
    executor(tasks)
  File "/home/wkerzend/miniconda2/envs/deepthought3/lib/python3.6/site-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/home/wkerzend/miniconda2/envs/deepthought3/lib/python3.6/site-packages/joblib/parallel.py", line 699, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/wkerzend/miniconda2/envs/deepthought3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/wkerzend/miniconda2/envs/deepthought3/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/home/wkerzend/miniconda2/envs/deepthought3/lib/python3.6/site-packages/joblib/pool.py", line 371, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'
```

**Comment by my-master** [comment]
Hi! I have the same issue when running the joblib example. My system info:
* **spaCy version**: 2.0.8
* **Python version**: 3.6.2
* **Platform**:  Linux 4.8.0-59-generic x86_64, Ubuntu 16.10
* **Model**: en_core_web_sm

```
% python multi_processing.py .                                      1:15:38 2018-02-22 !2121
Loaded model 'en_core_web_sm'
Loading IMDB data...
Downloading data from http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
84107264/84125825 [============================>.] - ETA: 0sUntaring file...
Processing texts...
Traceback (most recent call last):
  File "multi_processing.py", line 77, in <module>
    plac.call(main)
  File "/home/olga/soft/anaconda3/envs/drqa/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/olga/soft/anaconda3/envs/drqa/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "spacy_orig.py", line 41, in main
    executor(tasks)
  File "/home/olga/soft/anaconda3/envs/drqa/lib/python3.6/site-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/home/olga/soft/anaconda3/envs/drqa/lib/python3.6/site-packages/joblib/parallel.py", line 699, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/olga/soft/anaconda3/envs/drqa/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/olga/soft/anaconda3/envs/drqa/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/home/olga/soft/anaconda3/envs/drqa/lib/python3.6/site-packages/joblib/pool.py", line 371, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'
```

**Comment by ines** [comment]
Merging this with #1669!
