### ISSUE TITLE
python -m spacy init-model throws AttributeError: 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by mirfan899** [explosion/spaCy#1874]
I've created word2vec and brown clusters along with word freqs. I'm trying to build the model and getting following error:

```shell
Counting frequencies...
475883it [00:01, 254354.35it/s]
Reading vectors...
102454it [00:06, 15625.38it/s]
Reading clusters...
614342it [00:25, 24110.31it/s]
Creating model...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28668/28668 [00:01<00:00, 26873.24it/s]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mirfan/PycharmProjects/urdu/spaCy/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/mirfan/PycharmProjects/urdu/spaCy/.env2.7/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/mirfan/PycharmProjects/urdu/spaCy/.env2.7/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/mirfan/PycharmProjects/urdu/spaCy/spacy/cli/init_model.py", line 42, in init_model
    nlp = create_model(lang, probs, oov_prob, clusters, vectors_data, vector_keys, prune_vectors)
  File "/Users/mirfan/PycharmProjects/urdu/spaCy/spacy/cli/init_model.py", line 73, in create_model
    nlp.vocab.vectors = Vectors(data=vectors_data, keys=vector_keys)
  File "vectors.pyx", line 56, in spacy.vectors.Vectors.__init__
AttributeError: 'tuple' object has no attribute 'shape'
```

## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **spaCy version:** 2.0.5
* **Models:** en

**Comment by mirfan899** [comment]
Still same issue after cloning the spaCy today.

**Comment by mirfan899** [comment]
solution from @jarozajac related to #1832,
 `init_model.py` in `init_model() from vectors_data, vector_keys = read_vectors(vectors_loc) if vectors_loc else None, None` remove the last `, None` and in create_model() change `if vectors_data:` to `if len(vectors_data):`
