### ISSUE TITLE
Problem with init_model 

### ISSUE THREAD

**Issue by azarezade** [explosion/spaCy#1928]
I am trying to train a model for Persian (fa) language. I prepared the freqs, brown cluster and word2vec data using the instructions [here](https://github.com/explosion/spacy-dev-resources/tree/master/vocab). Then following the doc, I used:
```
python -m spacy init-model fa data/model/fa/ data/model/fa/fa_wiki.freqs -c data/model/fa/brown/paths -v data/model/fa/fa_wiki.word2vec
```
But it returns error:
```
usage: spacy init-model [-h] [-c None] [-v None] [-V -1]
                        lang output_dir freqs_loc
spacy init-model: error: unrecognized arguments: data/model/fa/fa_wiki.freqs
```
###  Environment
* Operating System: Mac OS X
* Python Version Used: 3.6
* spaCy Version Used: 2.0.5

**Comment by azarezade** [comment]
Sorry, I just found that it is resolved in #1789

**Comment by azarezade** [comment]
No `init-model` works but it returns another error :(
```
Counting frequencies...
923130it [00:03, 302459.31it/s]
Reading vectors...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/Documents/spacy-dev-resources/.venv/lib/python2.7/site-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command])
  File "/home/user/Documents/spacy-dev-resources/.venv/local/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/user/Documents/spacy-dev-resources/.venv/local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/user/Documents/spacy-dev-resources/.venv/local/lib/python2.7/site-packages/spacy/cli/init_model.py", line 40, in init_model
    vectors_data, vector_keys = read_vectors(vectors_loc) if vectors_loc else None, None
  File "/home/user/Documents/spacy-dev-resources/.venv/local/lib/python2.7/site-packages/spacy/cli/init_model.py", line 87, in read_vectors
    shape = tuple(int(size) for size in f.readline().split())
  File "/home/user/Documents/spacy-dev-resources/.venv/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x99 in position 12: invalid start byte
```

**Comment by azarezade** [comment]
I have solved the issue!
```
Counting frequencies...
923130it [00:02, 310215.81it/s]
data/model/fa/fa_wiki.word2vec
Reading vectors...
108821it [00:10, 10478.02it/s]
Creating model...
100%|███████████████████████| 36888/36888 [00:01<00:00, 24887.55it/s]

    Sucessfully compiled vocab
    36888 entries, 108821 vectors
```
