### ISSUE TITLE
Spacy is breaking when combining custom tokenizer's token_match with rule-based matching

### ISSUE THREAD

**Issue by jjtapia** [explosion/spaCy#1947]
I'm using the following custom tokenizer to force Spacy to recognize a pattern of form X.X as one entity
by using the `token_match` property (otherwise it will be splitted up as posted [here](https://stackoverflow.com/questions/48649480/merging-sentences-after-merging-spans))
```
reference_string = r'\w+\.\w+'

def custom_en_tokenizer(nlp):
    prefixes = list(English.Defaults.prefixes)
    prefix_re = spacy.util.compile_prefix_regex(tuple(prefixes))
    suffix_re = spacy.util.compile_suffix_regex(English.Defaults.suffixes)
    infix_re = spacy.util.compile_infix_regex(English.Defaults.infixes)
    pattern_re = re.compile(reference_string)
    return spacy.tokenizer.Tokenizer(nlp.vocab,
                                     English.Defaults.tokenizer_exceptions,
                                     prefix_re.search,
                                     suffix_re.search,
                                     infix_re.finditer,
                                     token_match=pattern_re.match)
```

And I'm using this as part of a larger pipeline where I add some custom flags and pattern based  matching. The custom flags are triggered on the same strings as the token_match based exception above.

```
from __future__ import unicode_literals, print_function
import en_core_web_sm
from spacy.matcher import Matcher
from spacy.lang.en import English
import spacy
import re



nlp = en_core_web_sm.load()
nlp.tokenizer = custom_en_tokenizer(nlp)

TEST_CODE = nlp.vocab.add_flag(re.compile(reference_string).match)
matcher = Matcher(nlp.vocab)
matcher.add('Test', None,
            [{TEST_CODE: True}]
            )


doc = nlp('Test A.A')


```

However when I try to run this my code breaks with the following problem

```
Traceback (most recent call last):
  File "untitled.py", line 36, in <module>
    doc = nlp('Test A.A')
  File "/.../venv2/local/lib/python2.7/site-packages/spacy/language.py", line 329, in __call__
    doc = self.make_doc(text)
  File "/.../venv2/local/lib/python2.7/site-packages/spacy/language.py", line 357, in make_doc
    return self.tokenizer(text)
  File "tokenizer.pyx", line 120, in spacy.tokenizer.Tokenizer.__call__
  File "tokenizer.pyx", line 161, in spacy.tokenizer.Tokenizer._tokenize
  File "tokenizer.pyx", line 236, in spacy.tokenizer.Tokenizer._attach_tokens
  File "vocab.pyx", line 134, in spacy.vocab.Vocab.get
  File "vocab.pyx", line 170, in spacy.vocab.Vocab._new_lexeme
TypeError: an integer is required
```

My pipeline has some more things but this is the most minimal example I could gather that still reproduced the issue.

## Info about spaCy

* **spaCy version:** 2.0.7
* **Platform:** Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18-sarah
* **Python version:** 3.6.1

edit: I noticed there was a new minor version so I tried updating spacy to 2.0.7, with the same effect

**Comment by jjtapia** [comment]
Ok, I was able to make a much smaller test case that isolates the issue. I will open another ticket that has a proper title
