### ISSUE TITLE
Cannot download en

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [explosion/spaCy#2041]
## Problem
I am trying to download the `en` languages, I am using python3 so I have to run

```
python3 -m spacy download en
```
Since `python` is linked to python 2.7. I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/usr/local/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/usr/local/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/usr/local/lib/python3.6/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..util import prints
  File "/usr/local/lib/python3.6/site-packages/spacy/util.py", line 8, in <module>
    import regex as re
  File "/usr/local/lib/python3.6/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/usr/local/lib/python3.6/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
```
Thank you in advance

## Your Environment

* Operating System:  MacOs 10.13.1
* Python Version Used: Python 3.6.2
* spaCy Version Used: Latest

**Comment by ines** [comment]
This looks like it might be similar to the problem described in #1684 (and [this StackOverflow thread](https://stackoverflow.com/questions/38916461/valueerror-unknown-locale-utf-8-when-importing-pandas-in-python-2-7/38917471#38917471)). Does adding the following the following to your `~/.bash_profile` help?

```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

Then run:

```bash
source ~/.bash_profile
```

**Comment by FrancescoSaverioZuppichini** [comment]
Working! Thank you ;)
