### ISSUE TITLE
ImportError: cannot import name copy_array when downloading English model

### ISSUE THREAD

**Issue by Devadath** [explosion/spaCy#2081]
I am getting this error when trying to download English model.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/usr/local/lib/python2.7/dist-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/usr/local/lib/python2.7/dist-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/usr/local/lib/python2.7/dist-packages/spacy/cli/link.py", line 7, in <module>
    from ..compat import symlink_to, path2str
  File "/usr/local/lib/python2.7/dist-packages/spacy/compat.py", line 11, in <module>
    from thinc.neural.util import copy_array
ImportError: cannot import name copy_array

## Your Environment

* Operating System:  Linux
* Python Version Used: 2.7
* spaCy Version Used: 2.0.8
* Environment Information:

**Comment by ines** [comment]
Could you check which version of Thinc you have installed in your environment?

```bash
pip list | grep thinc
```

If your version of Thinc doesn't match spaCy's requirements (`thinc>=6.10.1,<6.11.0`), does upgrading solve the problem?

```bash
pip install -U thinc
```

**Comment by Devadath** [comment]
@ines 
thinc version is compatible 
thinc (6.10.2)

**Comment by ines** [comment]
This should hopefully not be an issue anymore in the latest version. Could you try again with a fresh environment and install spaCy from scratch? If you still have problems, feel free to reopen.
