### ISSUE TITLE
ImportError: cannot import name 'load_model_from_init_py'

### ISSUE THREAD

**Issue by shicode** [explosion/spaCy#2093]
I installed spacy using pip install but I couldn't install the en package using the standard command, so I downloaded the 'en_core_web_md' package through pip by linking to the Github Repository. 

en package installation Command:

`pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz`

Code:

```
import en_core_web_md
nlp = en_core_web_md.load()
```

Error:
Traceback (most recent call last):

  File "<ipython-input-63-0a7ac9fb972a>", line 1, in <module>
    runfile('/Users/shilpasuresh/PycharmProjects/QuestionGeneration/DrQAAnswerSynth/prepro.py', wdir='/Users/shilpasuresh/PycharmProjects/QuestionGeneration/DrQAAnswerSynth')

  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/shilpasuresh/PycharmProjects/QuestionGeneration/DrQAAnswerSynth/prepro.py", line 2, in <module>
    import en_core_web_md

  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/en_core_web_md/__init__.py", line 5, in <module>
    from spacy.util import load_model_from_init_py, get_model_meta

ImportError: cannot import name 'load_model_from_init_py'

## Your Environment

* Operating System: Mac OS Sierra
* Python Version Used: 3.6
* spaCy Version Used: 2.0
* Environment Information:

**Comment by ines** [comment]
One possible explanation could be that the spaCy version you're executing isn't actually the correct one – which might also explain why you had problems installing the models before. For example, you might accidentally be running a system installation of spaCy v1.x instead of your environment's spaCy v2.x. So when you import the model, it loads the wrong spaCy and can't find the function it needs to load the data.

Before importing the model, you could check the following:

```python
import spacy
print(spacy.__version__)  # spaCy version
print(spacy.__file__)     # location of spaCy installation
```

If you've ended up in a weird state and the wrong executables on your path, it sometimes helps to just start from scratch with a fresh virtual environment.

**Comment by shicode** [comment]
I uninstalled all versions of spacy and reinstalled spacy version 2.0.9. However, the same issue is coming up and I am unable to download the English model from the command line. 

Commands used:

`pip install -U spacy
python -m spacy download en`

There doesn't seem to be any issue with the Spacy installation. However, this error arises when I try 
 to install the English model.

`Traceback (most recent call last):
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..util import prints
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/spacy/util.py", line 8, in <module>
    import regex as re
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Users/shilpasuresh/anaconda3/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8`

**Comment by shicode** [comment]
I managed to fix the issue. I used these two commands before installing the english model.

`export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
`

Thanks for your help ines!

**Comment by ines** [comment]
Thanks for updating with your solution 👍 (Locale stuff is always tricky – I remember coming across a similar issue before, so I feel your pain!)
