### ISSUE TITLE
SpaCy 1.x does `import pip` in `spacy/cli/link.py`, which is unsupported behavior.

### ISSUE THREAD

**Issue by pminervini** [explosion/spaCy#2112]
https://github.com/pypa/pip/issues/5081

```
$ python3 -m pip install --upgrade spacy==1.10.0
[..]
$ echo "import spacy" | python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/spacy/cli/download.py", line 9, in <module>
    from .link import link_package
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/spacy/cli/link.py", line 4, in <module>
    import pip
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/home/pasquale/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'
```

**Comment by honnibal** [comment]
Could you submit a patch against the 1.x branch? https://github.com/explosion/spaCy/tree/v1.x

Btw this goes for other types of changes you or others might want: obviously we'd like everyone to be on v2, and that's where we'll be putting our efforts. But we're definitely happy to merge pull requests, answer questions and make releases against 1.x so long as there are still people using it.

**Comment by pminervini** [comment]
@honnibal Sure! I'm on it.

**Comment by mdcclv** [comment]
I made a PR for this last night https://github.com/explosion/spaCy/pull/2110
