### ISSUE TITLE
NER training runs on cpu instead of gpu when updating a model

### ISSUE THREAD

**Issue by leloss** [explosion/spaCy#2161]
Hello, 

When resuming NER training (i.e., loading model "en" and training some extra samples), begin_training() seems to ignore the "device=0" flag and runs strictly on the cpu.
To replicate the problem, I added "device=0" to "begin_training()" in spacy/examples/training/train_new_entity_type.py. It runs fine on gpu (cpu 100%, gpu 40% utilization) when starting from a blank model, but it runs on the cpu (cpu 780%, gpu 2% utilization) when called with parameter "-m en".

Is that happening to anyone else?

My environment:
Ubuntu 17.10
Python 3.6.3
nvidia-390 driver
nvidia-cuda-toolkit 8.0
cupy 2.5.0
thinc 6.10.2
spacy 2.0.10

Thanks!

**Comment by honnibal** [comment]
First of all: you probably don't want `nlp.begin_training` here! That initializes the models, i.e. it zeros the weights.

Try running `spacy.util.use_gpu(0)` before calling `spacy.load()`, and then don't call `nlp.begin_training()`. That likely will do what you want.

**Comment by leloss** [comment]
Thanks for your help. The device=0 option was suggested in issue #1530. But now I understand that that's only suitable when starting from a blank model.

So per your suggestions, I changed the spacy/examples/training/train_new_entity_type.py code by adding spacy.util.use_gpu(0) before nlp = spacy.load(model). I also removed optimizer=begin_training(), and the "sgd=optimizer" option from nlp.update() when "-m en" is input. I removed device=0 from being_training() altogether.

The result is:
- Without "-m en"` all goes well, training runs on gpu.
- WIth "-m en" I now get the error:
```
sudo python3 scripts/train_new_entity_type.py -m en
Loaded model 'en'
Traceback (most recent call last):
  File "scripts/train_new_entity_type.py", line 137, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "scripts/train_new_entity_type.py", line 109, in main
    losses=losses)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 418, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 583, in spacy.syntax.nn_parser.Parser.update
  File "/usr/local/lib/python3.6/dist-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/thinc/check.py", line 146, in checked_function
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/affine.py", line 56, in begin_update
    output__BO = self.predict(input__BI)
  File "/usr/local/lib/python3.6/dist-packages/thinc/check.py", line 146, in checked_function
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/affine.py", line 52, in predict
    return self.ops.affine(self.W, self.b, input__BI)
  File "ops.pyx", line 195, in thinc.neural.ops.Ops.affine
  File "ops.pyx", line 183, in thinc.neural.ops.Ops.batch_dot
  File "/usr/local/lib/python3.6/dist-packages/cupy/linalg/product.py", line 34, in dot
    return a.dot(b, out)
  File "cupy/core/core.pyx", line 1381, in cupy.core.core.ndarray.__array__
  File "cupy/core/core.pyx", line 349, in cupy.core.core.ndarray.astype
  File "cupy/core/elementwise.pxi", line 826, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 603, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 171, in cupy.core.core._get_kernel_params
  File "cupy/core/elementwise.pxi", line 117, in cupy.core.core._get_typename
KeyError: <class 'numpy.object_'>
```

Others have reported problems with updating a model using a GPU (see #1782, #1806, #1938), but this seems to be a little different.

Thanks again.

**Comment by leloss** [comment]
I have an update on this issue:

The error seems to happen only when trying to learn new NER labels.
Example spacy/examples/training/train_new_entity_type.py, for instance, does not work when "-m en" option is on and the "spacy.util.use_gpu(0)" directive is added (which tells it to run it on the gpu).
However, if I replace ANIMAL in TRAIN_DATA by labels already in the model: PERSON, ORG, etc... then the code runs fine on the GPU.

Anyone else with similar issue?

**Comment by thebearer696** [comment]
@leloss I think I have a similar issue, attaching my stack trace below.
`  File "train_new_entity_type.py", line 148, in <module>
    plac.call(main)
  File "~/virt-py/local/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "~/virt-py/local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_new_entity_type.py", line 120, in main
    losses=losses)
  File "~/virt-py/local/lib/python2.7/site-packages/spacy/language.py", line 427, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 589, in spacy.syntax.nn_parser.Parser.update
  File "~/virt-py/local/lib/python2.7/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "~/virt-py/local/lib/python2.7/site-packages/thinc/check.py", line 146, in checked_function
    return wrapped(*args, **kwargs)
  File "~/virt-py/local/lib/python2.7/site-packages/thinc/neural/_classes/affine.py", line 56, in begin_update
    input__BI = self.ops.xp.ascontiguousarray(input__BI)
  File "~/virt-py/local/lib/python2.7/site-packages/cupy/creation/from_data.py", line 92, in ascontiguousarray
    return core.ascontiguousarray(a, dtype)
TypeError: Argument 'a' has incorrect type (expected cupy.core.core.ndarray, got numpy.ndarray)`

I tried to update in an already existing model, which I had created from scratch with new NER Labels.

**Comment by thebearer696** [comment]
@leloss  I think I have a similar issue, attaching my stack trace below.

File "train_new_entity_type.py", line 148, in 
plac.call(main)
File "/virt-py/local/lib/python2.7/site-packages/plac_core.py", line 328, in call
cmd, result = parser.consume(arglist)
File "/virt-py/local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
return cmd, self.func(*(args + varargs + extraopts), **kwargs)
File "train_new_entity_type.py", line 120, in main
losses=losses)
File "/virt-py/local/lib/python2.7/site-packages/spacy/language.py", line 427, in update
proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
File "nn_parser.pyx", line 589, in spacy.syntax.nn_parser.Parser.update
File "/virt-py/local/lib/python2.7/site-packages/thinc/api.py", line 61, in begin_update
X, inc_layer_grad = layer.begin_update(X, drop=drop)
File "/virt-py/local/lib/python2.7/site-packages/thinc/check.py", line 146, in checked_function
return wrapped(*args, **kwargs)
File "/virt-py/local/lib/python2.7/site-packages/thinc/neural/_classes/affine.py", line 56, in begin_update
input__BI = self.ops.xp.ascontiguousarray(input__BI)
File "~/virt-py/local/lib/python2.7/site-packages/cupy/creation/from_data.py", line 92, in ascontiguousarray
return core.ascontiguousarray(a, dtype)
TypeError: Argument 'a' has incorrect type (expected cupy.core.core.ndarray, got numpy.ndarray)

I tried to update in an already existing model, which I had created from scratch with new NER Labels.

**Comment by mlwelles** [comment]
I have this same one as well.  Followed 'the enabling CUDA' install instructions and build fine - the thinc.neural.gpu_ops import works  fine.   However,  training fails to run on the GPU.    Stepping through the code, I saw that in the call to use_gpu:

```
def use_gpu(gpu_id):
    try:
        import cupy.cuda.device
    except ImportError:
        return None
    from thinc.neural.ops import CupyOps
```
There's an import cupy.cudy.device that fails -- silently eating the exception (Arrgh! Why? Why not raise or at least warn? I lost so much time today blithely assuming stepping over this method call assuming it succeeded when it didn't fail.

There's no mention in the instructions that cupy is needed, but clearly it is, so I install,  but then my trainer immediately fails when it tries a test parse:
```
  File "/home/mlw/.virtualenvs/riverdrop-pipeline/lib/python3.6/site-packages/spacy/language.py", line 344, in __call__
    doc = proc(doc)
  File "nn_parser.pyx", line 337, in spacy.syntax.nn_parser.Parser.__call__
  File "nn_parser.pyx", line 415, in spacy.syntax.nn_parser.Parser.parse_batch
  File "/home/mlw/.virtualenvs/riverdrop-pipeline/lib/python3.6/site-packages/numpy/core/numeric.py", line 581, in ascontiguousarray
    return array(a, dtype, copy=False, order='C', ndmin=1)
ValueError: object __array__ method not producing an array
```
Which looks like one of the known issues feeding cupy arrays to numpy:

 https://github.com/cupy/cupy/issues/589

**Comment by honnibal** [comment]
This should now be fixed. If you try again with `spacy-nightly` and still have trouble, please open a new issue. The best way to enable the GPU now is to call `spacy.require_gpu()` before loading the model.
