### ISSUE TITLE
ImportError: cannot import name 'merge_noun_chunks'

### ISSUE THREAD

**Issue by Ahmid** [explosion/spaCy#2180]
I installed Spacy using the following:

```
pip install -U spacy
python -m spacy download en
```

But when I try to load the English language using the following code:
```
import spacy
nlp = spacy.load('en_core_web_sm', disable=['parser'])
```
or
`nlp = spacy.load('en', disable=['parser'])`

## I got the following error:

```
Traceback (most recent call last):
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\util.py", line 50, in get_lang_class
    module = importlib.import_module('.lang.%s' % lang, 'spacy')
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\lang\en\__init__.py", line 15, in <module>
    from ...language import Language
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\language.py", line 20, in <module>
    from .pipeline import merge_noun_chunks, merge_entities
ImportError: cannot import name 'merge_noun_chunks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Ahmadh/PycharmProjects/untitled/NER.py", line 4, in <module>
    nlp = spacy.load('en_core_web_sm', disable=['parser'])
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\util.py", line 113, in load_model
    return load_model_from_link(name, **overrides)
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\util.py", line 132, in load_model_from_link
    return cls.load(**overrides)
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\data\en_core_web_sm\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\util.py", line 177, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\util.py", line 146, in load_model_from_path
    cls = get_lang_class(meta['lang'])
  File "C:\Users\Ahmadh\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\util.py", line 53, in get_lang_class
    raise ImportError(msg % lang)
ImportError: Can't import language en from spacy.lang.

```

Below are the Spacy info I have:

## Info about spaCy

```
* **spaCy version:** 2.0.10
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.5
* **Models:** en, en_core_web_sm
```

**Comment by ines** [comment]
These import errors typically indicate that spaCy didn't compile properly – they're the first things that spaCy imports, so it fails to find the compiled files.

Were there any errors during installation? And do you have a compiler installed, i.e. the Visual C++ Build Tools? Alternatively, you can also install spaCy via conda, which should give you the binary wheel for Windows, which doesn't require you to compile spaCy locally.

**Comment by Ahmid** [comment]
Hi @ines 

There was no errors during installation. In fact, it was working fine and I tested some examples using nlp, but I don't know why it suddenly stopped working. 

Yes I have the Visual C++ Build Tools, I installed them so that Spacy can be installed without errors.

**Comment by ines** [comment]
Thanks for the quick update! Did you previously have an older version of spaCy installed? It explicitly fails on `merge_noun_chunks`, which was introduced in the latest version, so maybe you have some artifacts of the old installation in your environment that weren't overwritten correctly? (I find that one of the frustrating parts of working with Python and pip is that it's pretty easy to end up in a weird state – and sometimes, the only thing that helps is starting off with a fresh virtual environment.)

**Comment by Ahmid** [comment]
Hi @ines 

I just remembered that I installed spacy_nightly-2.0.0 (I was using Spacy [Rest interface](https://github.com/explosion/spacy-services) ), does that have something to do with the error?

**Comment by Ahmid** [comment]
Starting off with a fresh environment solved the issue. Thanks !
