### ISSUE TITLE
Pickle issues with the Language

### ISSUE THREAD

**Issue by DiplEng** [explosion/spaCy#2186]
Hi,

I recently attempted pickling a language model, and....

```
import pickle
nlp = spacy.load("de", tagger=False, entity=False, matcher=False, parser=False)
pickle.dumps(nlp)

Traceback (most recent call last):
  File "/data/libs/python/dl/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-54-28ffccf698b6>", line 1, in <module>
    pickle.dumps(nlp)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'

```
## ** Environment**:
**Spacy**: 2.0.8
**Python**: 3.6.4
**OS**: Ubuntu

**Comment by ines** [comment]
Thanks for the report and sorry about that – looks like this is the same problem as #2121. We've already fixed the underlying cause in Thinc – we just need to test and publish the point release.
