### ISSUE TITLE
ImportError after updating to v2

### ISSUE THREAD

**Issue by avissens** [explosion/spaCy#2217]
Hi,
I updated my spacy version from 1 to 2 but struggle to get it work. When I run `validate` I get this error:

```
Traceback (most recent call last):
  File "/Applications/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Applications/anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Applications/anaconda/lib/python2.7/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Applications/anaconda/lib/python2.7/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Applications/anaconda/lib/python2.7/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/Applications/anaconda/lib/python2.7/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..compat import symlink_to, path2str
  File "/Applications/anaconda/lib/python2.7/site-packages/spacy/compat.py", line 9, in <module>
    from thinc.neural.util import copy_array
  File "/Applications/anaconda/lib/python2.7/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/Applications/anaconda/lib/python2.7/site-packages/thinc/neural/_classes/model.py", line 11, in <module>
    from .. import util
  File "/Applications/anaconda/lib/python2.7/site-packages/thinc/neural/util.py", line 3, in <module>
    from preshed.maps import PreshMap
  File "cymem.pxd", line 1, in init preshed.maps (preshed/maps.cpp:5021)
ImportError: No module named cymem.cymem
```
When I try to import spacy in my Notebook I get this error instead: `ImportError: cannot import name util`

Could you guide me through this, please?

**Comment by ines** [comment]
Considering it fails on very basic imports, it's possible that you've ended up in a weird system/environment state. It's not the most satisfying answer, but one thing that usually helps is starting off with a fresh environment, to make sure there are no artifacts of an old installation that haven't been cleaned up properly when conda installed new versions of spaCy and its dependencies.

**Comment by avissens** [comment]
I didn't use a vertualenv, unfortunately... I managed to install the new version in a different environment now and it seems working ok. BUT I really want to clean the mess with the package which I previously upgraded without vertualenv. I tried to roll back and install my previous version (1.8.2) but I get the same error: `ImportError: No module named cymem.cymem`. 
`pip list` gives me: spacy (1.8.2) and cymem (1.31.2)
Should I try to install or upgrade cymem? Any suggestions, please?

**Comment by ines** [comment]
Sorry for only getting to this now... I definitely feel your pain! I don't think there's a perfect recipe for cleaning up messy environments and you just have to try and see what works best. You could definitely try uninstalling and reinstalling `cymem` (maybe it broke during the upgrade and just needs to recompile). Or you could do it the "radical" way, reinstall your old v1.8.2 configuration in a new virtualenv and then delete everything from your system installation.
