### ISSUE TITLE
can`t import spacy after installation!

### ISSUE THREAD

**Issue by AbelTan13** [explosion/spaCy#2265]
Hi,

I just installed spacy on windows 8, using anaconda:
I typed conda install -c conda-forge spacy
and got:

> 
> (base) C:\Users\Tan>conda install -c conda-forge spacy
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 4.4.10
>   latest version: 4.5.1
> 
> Please update conda by running
> 
>     $ conda update -n base conda
> ## Package Plan ##
> 
>   environment location: C:\Users\Tan\Anaconda3
> 
>   added / updated specs:
>     - spacy
> 
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     zlib-1.2.11                |           vc14_0         119 KB  conda-forge
>     certifi-2018.4.16          |           py36_0         143 KB  conda-forge
>     regex-2017.11.09           |           py36_0         319 KB  conda-forge
>     ca-certificates-2018.4.16  |                0         176 KB  conda-forge
>     termcolor-1.1.0            |           py36_1           7 KB  conda-forge
>     msgpack-numpy-0.4.1        |             py_0           8 KB  conda-forge
>     thinc-6.10.2               |      py36_vc14_0         1.3 MB  conda-forge
>     libxml2-2.9.8              |           vc14_0         3.2 MB  conda-forge
>     murmurhash-0.28.0          |      py36_vc14_0          17 KB  conda-forge
>     tqdm-4.23.1                |             py_0          35 KB  conda-forge
>     spacy-2.0.11               |      py36_vc14_0        33.7 MB  conda-forge
>     preshed-1.0.0              |      py36_vc14_0          54 KB  conda-forge
>     ujson-1.35                 |           py36_0          27 KB  conda-forge
>     msgpack-python-0.4.8       |           py36_0          73 KB  conda-forge
>     dill-0.2.7.1               |           py36_0          83 KB  conda-forge
>     pyreadline-2.1             |   py36h094d952_1         141 KB
>     cymem-1.31.2               |      py36_vc14_0          25 KB  conda-forge
>     openssl-1.0.2o             |           vc14_0         5.4 MB  conda-forge
>     plac-0.9.6                 |           py36_0          36 KB  conda-forge
>     cytoolz-0.8.2              |           py36_0         280 KB  conda-forge
>     ------------------------------------------------------------
>                                            Total:        45.0 MB
> 
> The following NEW packages will be INSTALLED:
> 
>     cymem:           1.31.2-py36_vc14_0    conda-forge [vc14]
>     dill:            0.2.7.1-py36_0        conda-forge
>     msgpack-numpy:   0.4.1-py_0            conda-forge
>     murmurhash:      0.28.0-py36_vc14_0    conda-forge [vc14]
>     plac:            0.9.6-py36_0          conda-forge
>     preshed:         1.0.0-py36_vc14_0     conda-forge [vc14]
>     pyreadline:      2.1-py36h094d952_1
>     regex:           2017.11.09-py36_0     conda-forge
>     spacy:           2.0.11-py36_vc14_0    conda-forge [vc14]
>     termcolor:       1.1.0-py36_1          conda-forge
>     thinc:           6.10.2-py36_vc14_0    conda-forge [vc14]
>     tqdm:            4.23.1-py_0           conda-forge
>     ujson:           1.35-py36_0           conda-forge
> 
> The following packages will be REMOVED:
> 
>     anaconda:        5.1.0-py36_2
> 
> The following packages will be UPDATED:
> 
>     ca-certificates: 2017.08.26-h94faf87_0             --> 2018.4.16-0      cond
> a-forge
>     certifi:         2018.1.18-py36_0                  --> 2018.4.16-py36_0 cond
> a-forge
>     libxml2:         2.9.7-h79bbb47_0                  --> 2.9.8-vc14_0     cond
> a-forge [vc14]
>     openssl:         1.0.2n-h74b6da3_0                 --> 1.0.2o-vc14_0    cond
> a-forge [vc14]
> 
> The following packages will be DOWNGRADED:
> 
>     cytoolz:         0.9.0-py36hfa6e2cd_0              --> 0.8.2-py36_0     cond
> a-forge
>     msgpack-python:  0.5.1-py36he980bc4_0              --> 0.4.8-py36_0     cond
> a-forge
>     zlib:            1.2.11-h8395fce_2                 --> 1.2.11-vc14_0    cond
> a-forge [vc14]
> 
> Proceed ([y]/n)? y
> 
> 
> Downloading and Extracting Packages
> zlib 1.2.11: ########################################################## | 100%
> certifi 2018.4.16: #################################################### | 100%
> regex 2017.11.09: ##################################################### | 100%
> ca-certificates 2018.4.16: ############################################ | 100%
> termcolor 1.1.0: ###################################################### | 100%
> msgpack-numpy 0.4.1: ################################################## | 100%
> thinc 6.10.2: ######################################################### | 100%
> libxml2 2.9.8: ######################################################## | 100%
> murmurhash 0.28.0: #################################################### | 100%
> tqdm 4.23.1: ########################################################## | 100%
> spacy 2.0.11: ######################################################### | 100%
> preshed 1.0.0: ######################################################## | 100%
> ujson 1.35: ########################################################### | 100%
> msgpack-python 0.4.8: ################################################# | 100%
> dill 0.2.7.1: ######################################################### | 100%
> pyreadline 2.1: ####################################################### | 100%
> cymem 1.31.2: ######################################################### | 100%
> openssl 1.0.2o: ####################################################### | 100%
> plac 0.9.6: ########################################################### | 100%
> cytoolz 0.8.2: ######################################################## | 100%
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> 
> (base) C:\Users\Tan>conda install -c conda-forge spacy
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 4.4.10
>   latest version: 4.5.1
> 
> Please update conda by running
> 
>     $ conda update -n base conda
> 
> # All requested packages already installed.
> 
> 
> 
> 
> 
> 

However, when I opened python 3.6,5 shell, I got:
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

>>> import spacy
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
>>> import spacy
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import spacy
**ModuleNotFoundError: No module named 'spacy'**

Is there anything I am doing wrong?

Thanks

## My Environment

* Operating System:  Windows 8
* Python Version Used: 3.6.5 64 bit
* spaCy Version Used:  2.0 (or at least I think this was the latest version as of 4/26/2018)
* Environment Information:

**Comment by AbelTan13** [comment]
my bad, it was 32 bit, sorry!
