### ISSUE TITLE
Creating custom word vectors for Portuguese

### ISSUE THREAD

**Issue by pvcastro** [explosion/spaCy#2298]
Hi there!

I was trying to load pre-trained Portuguese word vectors into spacy, because I'm trying to replicate @ines's **training an insults classifier** tutorial, but applying it to Portuguese language. I was following @honnibal's recommendation from #2189 and ran the following command, getting the error below. Any idea what could be the problem?

`python -m spacy init-model /tmp/pt_vectors_glove_lg -v /path/Glove/glove_s100.zip`

```
Traceback (most recent call last):
  File "/home/pedro/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pedro/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command])
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/plac_core.py", line 324, in call
    parser = parser_from(obj)
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/plac_core.py", line 133, in parser_from
    parser.populate_from(obj)
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/plac_core.py", line 257, in populate_from
    a = Annotation.from_(ann)
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/plac_core.py", line 91, in from_
    return cls(*obj)
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/plac_core.py", line 78, in __init__
    assert abbrev is None, abbrev
AssertionError: f
```

## Info about spaCy

* **spaCy version:** 2.0.5
* **Platform:** Linux-4.13.0-39-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.3
* **Models:** pt

Thanks!

**Comment by ines** [comment]
It looks like you're using an older version of spaCy that possibly contained a bug in the `init-model` command and also didn't yet support the vector loading from zip files. Could you try upgrading to the latest spaCy version and see if it works then?

**Comment by pvcastro** [comment]
Hi @ines , I updated it to 2.0.11 as you instructed, and now ran the following command, with the error below.

`python -m spacy init-model pt /tmp/pt_vectors_glove_lg -v /path/Glove/glove_100.txt`

```
Reading vectors from /media/discoD/embeddings/Glove/glove_100.txt
Traceback (most recent call last):
  File "/home/pedro/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pedro/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/spacy/cli/init_model.py", line 46, in init_model
    vectors_data, vector_keys = read_vectors(vectors_loc) if vectors_loc else (None, None)
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/spacy/cli/init_model.py", line 103, in read_vectors
    shape = tuple(int(size) for size in next(f).split())
  File "/home/pedro/virtualenv/machine-learning/lib/python3.6/site-packages/spacy/cli/init_model.py", line 103, in <genexpr>
    shape = tuple(int(size) for size in next(f).split())
ValueError: invalid literal for int() with base 10: ','
```

Here is the first line from glove_100.txt, which is the one I believe the error is referring to:

`, -0.392279 -0.383096 -0.163537 -1.615735 -0.500976 -0.007344 0.465154 -0.527951 -0.646091 -0.321491 1.002331 -0.087800 0.641722 -0.049970 -0.192054 -0.136509 -0.125559 0.175689 0.423102 0.372969 0.004964 0.304127 -0.527237 -0.821560 -0.077733 -0.117536 0.221912 -0.491307 0.426347 0.963038 -0.188195 -0.352566 0.517037 0.041755 0.419114 -0.036395 -0.041419 -0.178374 -0.426875 0.204201 1.168479 -0.201476 -1.180288 0.290288 -0.112032 0.006013 0.227758 0.009706 0.204799 -0.206002 0.163989 -0.174967 0.612155 -0.123464 -1.179910 -0.465190 0.028433 -0.192867 -0.394402 0.163425 -0.013171 0.291513 0.002794 -0.032286 -0.100530 -0.003712 0.397824 0.256725 0.102040 -0.829015 0.375783 0.553592 0.391063 0.859196 2.666478 -0.475499 0.887563 0.619419 0.035760 -0.415118 0.896760 -2.387111 -0.740849 -0.268416 0.132730 0.089813 -0.020695 -0.334298 -0.428773 -0.538492 -0.497059 1.318589 -0.233006 -0.156836 0.445024 0.582988 0.177718 0.774904 2.415028 -0.148173`

**Comment by ines** [comment]
Just had a look at the line that causes the error ([see here](https://github.com/explosion/spaCy/blob/9a1d3b63fbd8d90c41cbccac9f127950bbbb4c52/spacy/cli/init_model.py#L111)). I think what's happening here is that it expects the general word2vec format, where the first line is a string tuple of the shape. ([See this post](https://stackoverflow.com/a/29251943/6400719) for more details on the word vector format.)

Your file seems to start with the vocabulary entry plus vectors straight away. What happens if you add the shape (rows and dimensions) as the first line, e.g. something like `12345678 100`?

**Comment by pvcastro** [comment]
Hi @ines!

I had the following error before, so I thought that it would might be because of this shape line and had it removed. Now I've tested again with the zip file (containing the first row with shape), and got the error again:

```
$ python -m spacy init-model pt /tmp/pt_glove_vectors -v ~/Downloads/embeddings/Portuguese/Glove/glove_s100.zip
Reading vectors from /home/user/Downloads/embeddings/Portuguese/Glove/glove_s100.zip
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/virtualenv/machine-learning/lib/python3.6/site-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/user/virtualenv/machine-learning/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/user/virtualenv/machine-learning/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/user/virtualenv/machine-learning/lib/python3.6/site-packages/spacy/cli/init_model.py", line 46, in init_model
    vectors_data, vector_keys = read_vectors(vectors_loc) if vectors_loc else (None, None)
  File "/home/user/virtualenv/machine-learning/lib/python3.6/site-packages/spacy/cli/init_model.py", line 103, in read_vectors
    shape = tuple(int(size) for size in next(f).split())
  File "/home/user/virtualenv/machine-learning/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 12: invalid start byte
```

**Comment by ines** [comment]
Do any of the suggestion in [my reply here](https://github.com/explosion/spaCy/issues/2068#issuecomment-376856338) help? Especially changing the encoding when opening the file, as described [here](https://stackoverflow.com/questions/19699367/unicodedecodeerror-utf-8-codec-cant-decode-byte)? (If so, maybe we can include an encoding check in the `init-model` script – depending on what solves the problem.)

**Comment by ines** [comment]
Looks like you're getting closer to the solution here. The error indicates that you're trying to include the word (like `km²`) in the vector – but of course, that fails when numpy is trying to convert it to a float.

Are you sure that the specified shape (rows and especially dimension) is correct? If the number of dimensions set in the header is higher than the number of actual dimensions in the data, the word might be included in the slice of the data converted into an array (the vector).

**Comment by pvcastro** [comment]
I was training a NER model using a code that filtered invalid lines before feeding the embeddings to the model, maybe that's it. According to the validation, 2350 out of 934963 lines were invalid, maybe this km2 is the first invalid one. 

I'll try to create a new txt file excluding the invalid lines and will give it another try. I'll let you know when I'm done testing. 

Thanks!

**Comment by ines** [comment]
Cool, fingers crossed!

> 2350 out of 934963 lines were invalid

That's interesting, but definitely not impossible. You could also check if there's anything obvious that those lines have in common.

**Comment by pvcastro** [comment]
Thanks @ines, I got the training working after removing the invalid lines!
