### ISSUE TITLE
Cannot load en_core_web_lg

### ISSUE THREAD

**Issue by Tidaren** [explosion/spaCy#2312]
## How to reproduce the behaviour
```python
import spacy
spacy.load('en_core_web_lg')
```

## Your Environment

* **spaCy version:** 2.0.11
* **Platform:** Linux-4.13.0-1012-azure-x86_64-with-debian-stretch-sid (Ubuntu 16.04.4 LTS on Azure)
* **Python version:** 3.6.3 (on virtualenv)
* **Models:** en, en_core_web_lg, fr

## More details

I just downloaded the en_core_web_lg model (I was under spacy 2.0.5) and I couldn't load it. I tried to update spacy to 2.0.11 but it doesn't seem to be a spacy version issue.

Here's the trace:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/data/en_core_web_lg/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/language.py", line 641, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 380, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 391, in spacy.vectors.Vectors.from_disk
  File "/home/ubuntu/venv/lib/python3.6/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "vectors.pyx", line 384, in spacy.vectors.Vectors.from_disk.load_vectors
  File "/home/ubuntu/venv/lib/python3.6/site-packages/numpy/lib/npyio.py", line 421, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/numpy/lib/format.py", line 691, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 75026412 into shape (684831,300)
```

**Comment by ines** [comment]
Thanks for the detailed report! 👍 

Could you check which versions of Thinc and numpy you're running? (One possible explanation could be that spaCy was upgraded, but not all its dependencies.)

```bash
pip list | grep thinc
pip list | grep numpy
```

**Comment by Tidaren** [comment]
* **thinc**: 6.10.2
* **numpy**: 1.14.3

**Comment by Tidaren** [comment]
Unfortunately it still doesn't work.
It could be related to my environment, I'll try it on another one when I have time.

**Comment by ines** [comment]
Thanks for trying! And yes, if you have time to try a fresh install in a clean virtual environment, that would be helpful. It's possible you've ended up in a weird state – so it'd  be interesting to know if the problem still occurs if you install spaCy from scratch.

**Comment by Tidaren** [comment]
It seems to work on a clean environment, sorry about the inconvenience ^^'
I wonder why it happened though.
Should we close the issue?
