### ISSUE TITLE
Error while running evaluate on keras_parikh_entailment

### ISSUE THREAD

**Issue by Nitya05** [explosion/spaCy#2362]
## How to reproduce the behaviour
I am getting the following error when i try to run evaluate (after doing the training) with the below command:
python keras_parikh_entailment/ evaluate snli_1.0_train.jsonl snli_1.0_dev.jsonl

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ctg_nitya/venv_keras1.2.2/Workspace/spaCy/examples/keras_parikh_entailment/__main__.py", line 143, in <module>
    plac.call(main)
  File "/home/ctg_nitya/venv_keras1.2.2/local/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/ctg_nitya/venv_keras1.2.2/local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/ctg_nitya/venv_keras1.2.2/Workspace/spaCy/examples/keras_parikh_entailment/__main__.py", line 137, in main
    correct, total = evaluate(dev_loc)
  File "/home/ctg_nitya/venv_keras1.2.2/Workspace/spaCy/examples/keras_parikh_entailment/__main__.py", line 69, in evaluate
    if sim.argmax() == label.argmax():
AttributeError: 'float' object has no attribute 'argmax'

## Your Environment

* Operating System: Linux
* Python Version Used: 2.7.12
* spaCy Version Used: 2.0.11
* Environment Information:

**Comment by Nitya05** [comment]
Moreover, the documentation doesn't mention anything about using the test data set. All the possible options {train, demo, evaluate} require to pass the train and development location.
Can someone please brief me on how to test the model, once the training is done?

**Comment by Angefonce** [comment]
I am having the same issue.

**Comment by Nitya05** [comment]
Any leads for solving this issue?

**Comment by ines** [comment]
Merging this with #2758.
