### ISSUE TITLE
Connection refused downloading English models spaCy 1.6

### ISSUE THREAD

**Issue by lexotero** [explosion/spaCy#2365]
## Description

I'm getting an exception `urllib2.URLError` "Connection refused" when trying to download the English models using `spacy==1.6.0`

In a clean virtualenv I've only installed `spacy==1.6.0` and immediately after I've run:

```
python -m spacy.en.download all
```

This command raises an exception with the following stack trace:

```
➜  ~ python -m spacy.en.download all
Downloading parsing model
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "[...]/lib/python2.7/site-packages/spacy/en/download.py", line 25, in <module>
    plac.call(main)
  File "[...]/local/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "[...]/local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "[...]/lib/python2.7/site-packages/spacy/en/download.py", line 18, in main
    download('en', force=False, data_path=data_path)
  File "[...]/local/lib/python2.7/site-packages/spacy/download.py", line 36, in download
    about.__models__.get(lang, lang), data_path)
  File "[...]/local/lib/python2.7/site-packages/sputnik/__init__.py", line 37, in install
    index.update()
  File "[...]/local/lib/python2.7/site-packages/sputnik/index.py", line 84, in update
    index = json.load(session.open(request, 'utf8'))
  File "[...]/local/lib/python2.7/site-packages/sputnik/session.py", line 43, in open
    r = self.opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```

It looks like the server to download the models for this old version of spaCy is down.

## My Environment
* Operating System: Debian 8 64 bits
* Python Version Used: Python 2.7.9
* spaCy Version Used: 1.6.0

**Comment by ines** [comment]
Argh, not this server again 😭 I feel like there's always _something_ and we should probably set it all up again from scratch. Sorry about that. 

In the meantime, the models for `v1.6.0` and lower are also available attached to the release: https://github.com/explosion/spacy/releases/tag/v1.6.0

**Comment by lexotero** [comment]
Thanks @ines! I hope is not a big problem.

**Comment by parthshah86** [comment]
@ines I am also have the same issue. Any update on by when this will be fixed.

**Comment by ines** [comment]
Should be fixed now – sorry again!
http://index.spacy.io

**Comment by parthshah86** [comment]
@ines Thanks !!

**Comment by lexotero** [comment]
@ines It seems that is down again. I cannot get the models for the last two days.

**Comment by timjstewart** [comment]
Hi, I'm in the process of porting some older software that depends on spacy 0.101.0 and the connection refused error I'm getting when trying to download the en model is preventing me from making progress.

@ines linked to https://github.com/explosion/spacy/releases/tag/v1.6.0 but I'm not sure if that file is compatible with 0.101.0 or what I would do with that file if it was compatible.  Are there any instructions on manually installing the english model?  E.g. where would I extract it?  How would I link it into spacy?  Thanks!

**Comment by pfewzee** [comment]
Hi @timjstewart, did you have any luck figuring out how to link 1.1.0 models to v1.6.0? I can no longer download those models.
