### ISSUE TITLE
How to add a language model to spaCy (Urdu Model)?

### ISSUE THREAD

**Issue by mirfan899** [explosion/spaCy#2366]
I've build a model for Urdu language and want to contribute it to spaCy models, lookin for help on adding the models.

An issue occurred during training and building the model.
```shell
python -m spacy init-model ur /Users/mirfan/PycharmProjects/urdu/data/ur_model/ /Users/mirfan/PycharmProjects/urdu/data/ur/freqs/ur_word_freqs.freqs -c /Users/mirfan/PycharmProjects/urdu/data/ur/monolingual_doc-c500-p1.out/paths -v /Users/mirfan/PycharmProjects/urdu/data/ur/vectors/urdu_w2v.txt
Counting frequencies...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mirfan/PycharmProjects/urdu/spaCy/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/mirfan/PycharmProjects/urdu/spaCy/.env2.7/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/mirfan/PycharmProjects/urdu/spaCy/.env2.7/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "spacy/cli/init_model.py", line 48, in init_model
    probs, oov_prob = read_freqs(freqs_loc) if freqs_loc is not None else ({}, -20)
  File "spacy/cli/init_model.py", line 144, in read_freqs
    word = literal_eval(key)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    سِتم
    ^
SyntaxError: invalid syntax
```
After changing the line https://github.com/explosion/spaCy/blob/592834183ad0c8097f7290631681012d9b1bb39a/spacy/cli/init_model.py#L144
to 
```python
word = literal_eval(repr(key))
```
it works fine after that. I think `ast` package have some issues with `Urdu` characters.

## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **spaCy version:** 2.0.12.dev0
* **Models:** en

**Comment by mirfan899** [comment]
I've completed the scripts for Urdu language but have some issues with `char_classes.py`. Urdu is uncases language and when I try to add it in `char_classes.py` it throws following error.

```shell
pytest spacy/tests/lang/ur/test_text.py 
====================================================================================== test session starts ======================================================================================
platform darwin -- Python 2.7.13, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /Users/mirfan/PycharmProjects/urdu/spaCy, inifile:
collected 3 items                                                                                                                                                                               

spacy/tests/lang/ur/test_text.py EEE                                                                                                                                                      [100%]

============================================================================================ ERRORS =============================================================================================
______________________________________________________________________ ERROR at setup of test_tokenizer_handles_long_text _______________________________________________________________________

    @pytest.fixture
    def ur_tokenizer():
>       return util.get_lang_class('ur').Defaults.create_tokenizer()

spacy/tests/conftest.py:162: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
spacy/language.py:63: in create_tokenizer
    if cls.suffixes else None)
spacy/util.py:295: in compile_suffix_regex
    return re.compile(expression)
.env2.7/lib/python2.7/site-packages/regex.py:345: in compile
    return _compile(pattern, flags, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

pattern = '…$|……$|,$|:$|;$|\!$|\?$|¿$|؟$|¡$|\($|\)$|\[$|\]$|\{$|\}$|<$|>$|_$|#$|\*$|&$|。$|？$|！$|，$|、$|；$|：$|～$|·$|।$|،$|؛$|٪$|\....[[[\p{Lu}&&\p{Latin}]||[ЁА-Я]||[\p{L}&&\p{Bengali}]||[p{Hebrew}]||[\p{L}&&\p{Arabic}]||[\p{L}&&\p{Urdu}]]])\.$'
flags = 0, kwargs = {}

    def _compile(pattern, flags=0, kwargs={}):
        "Compiles a regular expression to a PatternObject."
    
        # We won't bother to cache the pattern if we're debugging.
        debugging = (flags & DEBUG) != 0
    
        # What locale is this pattern using?
        locale_key = (type(pattern), pattern)
        if _locale_sensitive.get(locale_key, True) or (flags & LOCALE) != 0:
            # This pattern is, or might be, locale-sensitive.
            pattern_locale = _getlocale()[1]
        else:
            # This pattern is definitely not locale-sensitive.
            pattern_locale = None
    
        if not debugging:
            try:
                # Do we know what keyword arguments are needed?
                args_key = pattern, type(pattern), flags
                args_needed = _named_args[args_key]
    
                # Are we being provided with its required keyword arguments?
                args_supplied = set()
                if args_needed:
                    for k, v in args_needed:
                        try:
                            args_supplied.add((k, frozenset(kwargs[k])))
                        except KeyError:
                            raise error("missing named list: {!r}".format(k))
    
                args_supplied = frozenset(args_supplied)
    
                # Have we already seen this regular expression and named list?
                pattern_key = (pattern, type(pattern), flags, args_supplied,
                  DEFAULT_VERSION, pattern_locale)
                return _cache[pattern_key]
            except KeyError:
                # It's a new pattern, or new named list for a known pattern.
                pass
    
        # Guess the encoding from the class of the pattern string.
        if isinstance(pattern, unicode):
            guess_encoding = UNICODE
        elif isinstance(pattern, str):
            guess_encoding = ASCII
        elif isinstance(pattern, _pattern_type):
            if flags:
                raise ValueError("cannot process flags argument with a compiled pattern")
    
            return pattern
        else:
            raise TypeError("first argument must be a string or compiled pattern")
    
        # Set the default version in the core code in case it has been changed.
        _regex_core.DEFAULT_VERSION = DEFAULT_VERSION
    
        global_flags = flags
    
        while True:
            caught_exception = None
            try:
                source = _Source(pattern)
                info = _Info(global_flags, source.char_type, kwargs)
                info.guess_encoding = guess_encoding
                source.ignore_space = bool(info.flags & VERBOSE)
                parsed = _parse_pattern(source, info)
                break
            except _UnscopedFlagSet:
                # Remember the global flags for the next attempt.
                global_flags = info.global_flags
            except error, e:
                caught_exception = e
    
            if caught_exception:
                raise error(caught_exception.msg, caught_exception.pattern,
>                 caught_exception.pos)
E               error: unknown property at position 801

.env2.7/lib/python2.7/site-packages/regex.py:490: error
_______________________________ ERROR at setup of test_tokenizer_handles_cnts[\u062a\u062d\u0631\u06cc\u0631 \u0628\u0627\u0633\u0637 \u062d\u0628\u06cc\u0628-3] _______________________________

    @pytest.fixture
    def ur_tokenizer():
>       return util.get_lang_class('ur').Defaults.create_tokenizer()

spacy/tests/conftest.py:162: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
spacy/language.py:63: in create_tokenizer
    if cls.suffixes else None)
spacy/util.py:295: in compile_suffix_regex
    return re.compile(expression)
.env2.7/lib/python2.7/site-packages/regex.py:345: in compile
    return _compile(pattern, flags, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

pattern = '…$|……$|,$|:$|;$|\!$|\?$|¿$|؟$|¡$|\($|\)$|\[$|\]$|\{$|\}$|<$|>$|_$|#$|\*$|&$|。$|？$|！$|，$|、$|；$|：$|～$|·$|।$|،$|؛$|٪$|\....[[[\p{Lu}&&\p{Latin}]||[ЁА-Я]||[\p{L}&&\p{Bengali}]||[p{Hebrew}]||[\p{L}&&\p{Arabic}]||[\p{L}&&\p{Urdu}]]])\.$'
flags = 0, kwargs = {}

    def _compile(pattern, flags=0, kwargs={}):
        "Compiles a regular expression to a PatternObject."
    
        # We won't bother to cache the pattern if we're debugging.
        debugging = (flags & DEBUG) != 0
    
        # What locale is this pattern using?
        locale_key = (type(pattern), pattern)
        if _locale_sensitive.get(locale_key, True) or (flags & LOCALE) != 0:
            # This pattern is, or might be, locale-sensitive.
            pattern_locale = _getlocale()[1]
        else:
            # This pattern is definitely not locale-sensitive.
            pattern_locale = None
    
        if not debugging:
            try:
                # Do we know what keyword arguments are needed?
                args_key = pattern, type(pattern), flags
                args_needed = _named_args[args_key]
    
                # Are we being provided with its required keyword arguments?
                args_supplied = set()
                if args_needed:
                    for k, v in args_needed:
                        try:
                            args_supplied.add((k, frozenset(kwargs[k])))
                        except KeyError:
                            raise error("missing named list: {!r}".format(k))
    
                args_supplied = frozenset(args_supplied)
    
                # Have we already seen this regular expression and named list?
                pattern_key = (pattern, type(pattern), flags, args_supplied,
                  DEFAULT_VERSION, pattern_locale)
                return _cache[pattern_key]
            except KeyError:
                # It's a new pattern, or new named list for a known pattern.
                pass
    
        # Guess the encoding from the class of the pattern string.
        if isinstance(pattern, unicode):
            guess_encoding = UNICODE
        elif isinstance(pattern, str):
            guess_encoding = ASCII
        elif isinstance(pattern, _pattern_type):
            if flags:
                raise ValueError("cannot process flags argument with a compiled pattern")
    
            return pattern
        else:
            raise TypeError("first argument must be a string or compiled pattern")
    
        # Set the default version in the core code in case it has been changed.
        _regex_core.DEFAULT_VERSION = DEFAULT_VERSION
    
        global_flags = flags
    
        while True:
            caught_exception = None
            try:
                source = _Source(pattern)
                info = _Info(global_flags, source.char_type, kwargs)
                info.guess_encoding = guess_encoding
                source.ignore_space = bool(info.flags & VERBOSE)
                parsed = _parse_pattern(source, info)
                break
            except _UnscopedFlagSet:
                # Remember the global flags for the next attempt.
                global_flags = info.global_flags
            except error, e:
                caught_exception = e
    
            if caught_exception:
                raise error(caught_exception.msg, caught_exception.pattern,
>                 caught_exception.pos)
E               error: unknown property at position 801

.env2.7/lib/python2.7/site-packages/regex.py:490: error
_____________________________________ ERROR at setup of test_tokenizer_handles_cnts[\u0645\u06cc\u0631\u0627 \u067e\u0627\u06a9\u0633\u062a\u0627\u0646-2] ______________________________________

    @pytest.fixture
    def ur_tokenizer():
>       return util.get_lang_class('ur').Defaults.create_tokenizer()

spacy/tests/conftest.py:162: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
spacy/language.py:63: in create_tokenizer
    if cls.suffixes else None)
spacy/util.py:295: in compile_suffix_regex
    return re.compile(expression)
.env2.7/lib/python2.7/site-packages/regex.py:345: in compile
    return _compile(pattern, flags, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

pattern = '…$|……$|,$|:$|;$|\!$|\?$|¿$|؟$|¡$|\($|\)$|\[$|\]$|\{$|\}$|<$|>$|_$|#$|\*$|&$|。$|？$|！$|，$|、$|；$|：$|～$|·$|।$|،$|؛$|٪$|\....[[[\p{Lu}&&\p{Latin}]||[ЁА-Я]||[\p{L}&&\p{Bengali}]||[p{Hebrew}]||[\p{L}&&\p{Arabic}]||[\p{L}&&\p{Urdu}]]])\.$'
flags = 0, kwargs = {}

    def _compile(pattern, flags=0, kwargs={}):
        "Compiles a regular expression to a PatternObject."
    
        # We won't bother to cache the pattern if we're debugging.
        debugging = (flags & DEBUG) != 0
    
        # What locale is this pattern using?
        locale_key = (type(pattern), pattern)
        if _locale_sensitive.get(locale_key, True) or (flags & LOCALE) != 0:
            # This pattern is, or might be, locale-sensitive.
            pattern_locale = _getlocale()[1]
        else:
            # This pattern is definitely not locale-sensitive.
            pattern_locale = None
    
        if not debugging:
            try:
                # Do we know what keyword arguments are needed?
                args_key = pattern, type(pattern), flags
                args_needed = _named_args[args_key]
    
                # Are we being provided with its required keyword arguments?
                args_supplied = set()
                if args_needed:
                    for k, v in args_needed:
                        try:
                            args_supplied.add((k, frozenset(kwargs[k])))
                        except KeyError:
                            raise error("missing named list: {!r}".format(k))
    
                args_supplied = frozenset(args_supplied)
    
                # Have we already seen this regular expression and named list?
                pattern_key = (pattern, type(pattern), flags, args_supplied,
                  DEFAULT_VERSION, pattern_locale)
                return _cache[pattern_key]
            except KeyError:
                # It's a new pattern, or new named list for a known pattern.
                pass
    
        # Guess the encoding from the class of the pattern string.
        if isinstance(pattern, unicode):
            guess_encoding = UNICODE
        elif isinstance(pattern, str):
            guess_encoding = ASCII
        elif isinstance(pattern, _pattern_type):
            if flags:
                raise ValueError("cannot process flags argument with a compiled pattern")
    
            return pattern
        else:
            raise TypeError("first argument must be a string or compiled pattern")
    
        # Set the default version in the core code in case it has been changed.
        _regex_core.DEFAULT_VERSION = DEFAULT_VERSION
    
        global_flags = flags
    
        while True:
            caught_exception = None
            try:
                source = _Source(pattern)
                info = _Info(global_flags, source.char_type, kwargs)
                info.guess_encoding = guess_encoding
                source.ignore_space = bool(info.flags & VERBOSE)
                parsed = _parse_pattern(source, info)
                break
            except _UnscopedFlagSet:
                # Remember the global flags for the next attempt.
                global_flags = info.global_flags
            except error, e:
                caught_exception = e
    
            if caught_exception:
                raise error(caught_exception.msg, caught_exception.pattern,
>                 caught_exception.pos)
E               error: unknown property at position 801

.env2.7/lib/python2.7/site-packages/regex.py:490: error
==================================================================================== 3 error in 0.37 seconds ====================================================================================
```

**Comment by ines** [comment]
Merging this with the master thread in #3056!
