### ISSUE TITLE
No such file or directory spacy/data/en/en_core_web_md-2.0.0/vocab/lexemes.bin

### ISSUE THREAD

**Issue by antoinecomp** [explosion/spaCy#2406]
## How to reproduce the behaviour

Any time I call for RasaNLUInterpreter: `nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')` I don't remeber the steps that led to that problem but I know it was after installing Flask.

And the error message is:
```

(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python run_app.py 
Traceback (most recent call last):
  File "run_app.py", line 6, in <module>
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/interpreter.py", line 221, in __init__
    self._load_interpreter()
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/interpreter.py", line 237, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/model.py", line 276, in load
    skip_validation)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/model.py", line 303, in create
    model_metadata, **context)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/components.py", line 398, in load_component
    cached_component, **context)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/registry.py", line 131, in load_component_by_name
    return component_clz.load(model_dir, metadata, cached_component, **kwargs)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/utils/spacy_utils.py", line 126, in load
    nlp = spacy.load(model_name, parser=False)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/language.py", line 641, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 377, in spacy.vocab.Vocab.from_disk
  File "/usr/lib/python3.5/pathlib.py", line 1151, in open
    opener=self._opener)
  File "/usr/lib/python3.5/pathlib.py", line 1005, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en/en_core_web_md-2.0.0/vocab/lexemes.bin'
```

It was an issue already faced [there](https://github.com/explosion/spaCy/issues/2007) but I don't understand how what I would have to uninstall, there haven't been any feedback and the issue was automatically closed as it is.

## Your Environment

* Operating System: Linux 16.04
* Python Version Used: python 3.5.2
* spaCy Version Used: 2.0.11
* Environment Information:

Here are my requirements: 

```
absl-py==0.2.2
apixu-client==0.0.1
APScheduler==3.3.1
astor==0.6.2
attrs==18.1.0
Automat==0.6.0
bleach==1.5.0
boto3==1.4.4
botocore==1.5.95
certifi==2018.4.16
chardet==3.0.4
click==6.7
cloudpickle==0.5.3
coloredlogs==7.3
colorhash==1.0.2
ConfigArgParse==0.12.0
constantly==15.1.0
cycler==0.10.0
cymem==1.31.2
cytoolz==0.8.2
decorator==4.3.0
dill==0.2.7.1
docopt==0.6.2
docutils==0.14
en-core-web-md==2.0.0
en-core-web-sm==1.2.0
fakeredis==0.8.2
fbmessenger==4.3.1
Flask==0.12
Flask-Cors==3.0.4
ftfy==4.4.3
future==0.16.0
gast==0.2.0
gevent==1.2.1
graphviz==0.7.1
greenlet==0.4.13
grpcio==1.12.0
h5py==2.7.0
html5lib==0.9999999
humanfriendly==4.12.1
hyperlink==18.0.0
idna==2.6
incremental==17.5.0
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
jsonpickle==0.9.4
jsonschema==2.6.0
Keras==2.0.8
kiwisolver==1.0.1
klein==17.2.0
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==1.5.3
mattermostwrapper==2.1
msgpack-numpy==0.4.1
msgpack-python==0.5.6
murmurhash==0.28.0
networkx==1.11
numpy==1.13.1
packaging==17.1
pandoc==1.0.0b2
pathlib==1.0.1
pkg-resources==0.0.0
plac==0.9.6
ply==3.11
preshed==1.0.0
protobuf==3.5.2.post1
PyJWT==1.6.4
pykwalify==1.6.0
pypandoc==1.4
pyparsing==2.2.0
PySocks==1.6.8
python-crfsuite==0.9.5
python-dateutil==2.7.3
python-telegram-bot==10.1.0
pytz==2018.4
PyYAML==3.12
rasa-core==0.9.0
rasa-nlu==0.12.3
redis==2.10.5
regex==2017.4.5
requests==2.14.2
ruamel.yaml==0.15.34
s3transfer==0.1.13
scikit-learn==0.19.1
scipy==1.1.0
simplejson==3.11.1
six==1.10.0
sklearn-crfsuite==0.3.5
slackclient==1.2.1
spacy==2.0.11
tabulate==0.8.2
tensorboard==1.8.0
tensorflow==1.8.0
termcolor==1.1.0
thinc==6.10.2
toolz==0.9.0
tqdm==4.11.2
twilio==6.14.3
Twisted==18.4.0
typing==3.5.3.0
tzlocal==1.5.1
ujson==1.35
urllib3==1.22
wcwidth==0.1.7
websocket-client==0.48.0
Werkzeug==0.14.1
wrapt==1.10.11
zope.interface==4.5.0
```

**Comment by antoinecomp** [comment]
Thank you for the answer ! I understand the error. Unfortunately, I reached to another error when following step by step your idea: 

It seems that I failed to load the native TensorFlow runtime because I didn't had the '_pywrap_tensorflow_internal' module. Yet when I tried to download it, it failed.

Indeed, linking was successful: 

```
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python -m spacy link en_core_web_md en --force

    Linking successful
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/en_core_web_md
    -->
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en

    You can now load the model via spacy.load('en')
```

But I had still the same problem:

```
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python run_app.py 
Traceback (most recent call last):
  File "run_app.py", line 6, in <module>
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/interpreter.py", line 221, in __init__
    self._load_interpreter()
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/interpreter.py", line 237, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/model.py", line 276, in load
    skip_validation)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/model.py", line 303, in create
    model_metadata, **context)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/components.py", line 398, in load_component
    cached_component, **context)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/registry.py", line 131, in load_component_by_name
    return component_clz.load(model_dir, metadata, cached_component, **kwargs)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/utils/spacy_utils.py", line 126, in load
    nlp = spacy.load(model_name, parser=False)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/language.py", line 641, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 377, in spacy.vocab.Vocab.from_disk
  File "/usr/lib/python3.5/pathlib.py", line 1151, in open
    opener=self._opener)
  File "/usr/lib/python3.5/pathlib.py", line 1005, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en/en_core_web_md-2.0.0/vocab/lexemes.bin'
```

So I did the following to delete the old en in spacy/data before creating the shortcut link again. Is it the right way to delete  `spacy/data` ?

```
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ pip uninstall en_core_web_md
Uninstalling en-core-web-md-2.0.0:
  Would remove:
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/en_core_web_md-2.0.0.egg-info
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/en_core_web_md/*
Proceed (y/n)? y
  Successfully uninstalled en-core-web-md-2.0.0
```

And I reinstalled the model:

```
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python -m spacy download en_core_web_md
Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz (120.8MB)
    100% |████████████████████████████████| 120.9MB 5.4MB/s 
Installing collected packages: en-core-web-md
  Running setup.py install for en-core-web-md ... done
Successfully installed en-core-web-md-2.0.0

    Linking successful
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/en_core_web_md
    -->
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en_core_web_md

    You can now load the model via spacy.load('en_core_web_md')

(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python -m spacy link en_core_web_md en --force

    Linking successful
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/en_core_web_md
    -->
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en

    You can now load the model via spacy.load('en')
```

Yet when launching the NLU Interpreter it lacked a module:

```
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python run_app.py 
/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from './models/nlu/default/weathernlu/entity_synonyms.json'
  "".format(entity_synonyms_file))
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "/usr/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_app.py", line 7, in <module>
    agent = Agent.load('./models/dialogue',interpreter = nlu_interpreter)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/agent.py", line 73, in load
    ensemble = PolicyEnsemble.load(path)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/policies/ensemble.py", line 194, in load
    policy = policy_cls.load(policy_path)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/policies/keras_policy.py", line 264, in load
    model_arch = cls._load_model_arch(path, meta)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/policies/keras_policy.py", line 238, in _load_model_arch
    from keras.models import model_from_json
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "/usr/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ImportError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python -m pip install _pywrap_tensorflow_internal
Invalid requirement: '_pywrap_tensorflow_internal'
Traceback (most recent call last):
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 2689, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 252, in from_line
    req = Requirement(req)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'_pywrap_'"
```

And I wasn't able to install it.

**Comment by ines** [comment]
Hmm, it looks like the other problems are related to Rasa or some other dependency – spaCy doesn't use TensorFlow at all. So I'm afraid I can't help you with that one. (It looks [common](https://github.com/tensorflow/tensorflow/issues/11571), though, and apparently related to environment and Python path stuff? So it's possible that you just ended up in a weird environment state.)

To check that spaCy and the models work correctly, you can try loading it independently – e.g. by calling `nlp = spacy.load('en')`. Alternatively, you can always just import the model package directly and then call its `load` method. Some users actually prefer this way of loading models, because it's more "native" and doesn't require symlinks (and if something goes wrong, it'll fail immediately on the `import` statement and not somewhere down the line).

```python
import en_core_web_md
nlp = en_core_web_md.load()
```

**Comment by antoinecomp** [comment]
Oh, you may be right !
Unfortunately I don't know how to use it more native in [my own code](https://github.com/antoinecomp/myflaskapp/tree/master/myFlaskAppenv) as far as I followed step by step [their tutorial](https://nlu.rasa.com/tutorial.html) and a [video tutorial](https://vimeo.com/254777331) and in both they seem to use these kind of linking.

**Comment by antoinecomp** [comment]
From [neustart47's answer](https://stackoverflow.com/questions/35953210/error-running-basic-tensorflow-example):

` pip install tensorflow --upgrade --force-reinstall`
