### ISSUE TITLE
ModuleNotFoundError: No module named 'cymem.cymem'

### ISSUE THREAD

**Issue by byorxyz** [explosion/spaCy#2455]
## How to reproduce the problem

Hi spacy community, 
I'm using python3 installed by Conda. It installs without a problem but I'm getting the error says: No module named 'cymem.cymem'. I tried many things like reinstall numpy, reinstall spacy, delete python2.7 numpy packages manually, etc.

There are very few posts related to cymem error. Can someone shed some light on this? Thank you so much.

```bash
aerin@aerin-HP-Z230-Tower-Workstation:~/Desktop/san_mrc$ conda install -c conda-forge spacy=1.9
Solving environment: done

## Package Plan ##

  environment location: /home/aerin/anaconda3

  added / updated specs: 
    - spacy=1.9


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.4                |           py36_0         621 KB  conda-forge
    certifi-2018.4.16          |           py36_0         142 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         763 KB

The following NEW packages will be INSTALLED:

    spacy:           1.9.0-np112py36_1 conda-forge

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0                  --> 2018.4.16-0      conda-forge
    certifi:         2018.4.16-py36_0              --> 2018.4.16-py36_0 conda-forge
    conda:           4.5.4-py36_0                  --> 4.5.4-py36_0     conda-forge
    openssl:         1.0.2o-h20670df_0             --> 1.0.2o-0         conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.5.4          |  621 KB | ########################################################## | 100% 
certifi-2018.4.16    |  142 KB | ########################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
 
aerin@aerin-HP-Z230-Tower-Workstation:~/Desktop/san_mrc$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
  File ".env/lib/python2.7/site-packages/cymem/cymem.pxd", line 1, in init spacy.gold (spacy/gold.cpp:23496)
ModuleNotFoundError: No module named 'cymem.cymem'
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()

```

## Your Environment

I can't run  `python -m spacy info --markdown` 

aerin@aerin-HP-Z230-Tower-Workstation:~/Desktop/san_mrc$ python -m spacy info --markdown
Traceback (most recent call last):
  File "/home/aerin/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/aerin/anaconda3/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/aerin/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
  File ".env/lib/python2.7/site-packages/cymem/cymem.pxd", line 1, in init spacy.gold (spacy/gold.cpp:23496)
ModuleNotFoundError: No module named 'cymem.cymem'

* Operating System: Ubuntu 16.04
* Python Version Used: Anaconda python 3.6
* spaCy Version Used: 1.9
* Environment Information:

**Comment by ines** [comment]
Merging this with #2456!
