### ISSUE TITLE
ner model building new entities  with GPU support

### ISSUE THREAD

**Issue by yatin-rxlogix** [explosion/spaCy#2484]
Hi,
     I am using spacy to Tag new Entities using GPU, 
But on the GPU it shows GPU-Util  as 0%  and GPU Memory as 350 Mb.
Can somebody help me how to correctly use spacy with GPU

Code:--
optimizer = nlp.begin_training(lambda: [], use_gpu=True, device=0)

## Your Environment

* **Platform:** Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid
* **Models:** en
* **spaCy version:** 2.0.11
* **Python version:** 3.5.5

**Comment by honnibal** [comment]
Could you check that the library was installed with GPU? You should check that the `cupy` library i installed, and that the `thinc.neural.gpu_ops` module is available.

If it's not, then you need to do:

```
pip uninstall thinc
pip install cupy
pip install thinc --no-binary :all: --no-cache-dir
```

Fingers crossed, this will build the GPU support correctly, which will let spaCy take advantage of it. Note that the GPU performance isn't wonderful currently --- it's maybe two or three times as fast as CPU.

**Comment by mlsmgit** [comment]
Added  spacy.util.use_gpu(0) Before doing spacy.load()
Still throws error when training new ent type with gpu support.

- spaCy version 2.0.12 
- thinc Version: 6.11.2
- cupy Version: 4.4.0
- cuda- 8.0
- import thinc.neural.gpu_ops"  and import cupy.cuda.device works

./train_new_entity_type.py -m en_core_web_sm
Loaded model 'en_core_web_sm'
Traceback (most recent call last):
  File "./train_new_entity_type.py", line 133, in <module>
    plac.call(main)
  File "/home/pi/nn_based_nlp_stuff/virtualenvs/py36/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/pi/nn_based_nlp_stuff/virtualenvs/py36/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "./train_new_ner_type.py", line 105, in main
    losses=losses)
  File "/home/pi/nn_based_nlp_stuff/virtualenvs/py36/lib/python3.6/site-packages/spacy/language.py", line 427, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 589, in spacy.syntax.nn_parser.Parser.update
  File "/home/pi/nn_based_nlp_stuff/virtualenvs/py36/lib/python3.6/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/home/pi/nn_based_nlp_stuff/virtualenvs/py36/lib/python3.6/site-packages/thinc/check.py", line 146, in checked_function
    return wrapped(*args, **kwargs)
  File "/home/pi/nn_based_nlp_stuff/virtualenvs/py36/lib/python3.6/site-packages/thinc/neural/_classes/affine.py", line 56, in begin_update
    input__BI = self.ops.xp.ascontiguousarray(input__BI)
  File "/home/pi/nn_based_nlp_stuff/virtualenvs/py36/lib/python3.6/site-packages/cupy/creation/from_data.py", line 91, in ascontiguousarray
    return core.ascontiguousarray(a, dtype)
TypeError: Argument 'a' has incorrect type (expected cupy.core.core.ndarray, got numpy.ndarray)

**Comment by honnibal** [comment]
Should now be fixed on `spacy-nightly`. I missed this issue -- apologies for not updating sooner.
