### ISSUE TITLE
Use spacy pretrained arabic ner model and then update the prodigy model with mixedin data.

### ISSUE THREAD

**Issue by YanLiang1102** [explosion/spaCy#2496]
## How to reproduce the behaviour

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/prodigy/__main__.py", line 259, in <module>
    controller = recipe(*args, use_plac=True)
  File "cython_src/prodigy/core.pyx", line 167, in prodigy.core.recipe.recipe_decorator.recipe_proxy
  File "/home/yan/.local/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/yan/.local/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/prodigy/recipes/ner.py", line 377, in batch_train
    nlp = spacy.load(input_model)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/util.py", line 116, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/util.py", line 142, in load_model_from_path
    meta = get_model_meta(model_path)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/util.py", line 187, in get_model_meta
    raise IOError(Errors.E053.format(path=meta_path))
OSError: [E053] Could not read meta.json from /meta.json
yan@yan-HP-ENVY-17-Notebook-PC:~/arabicNER/Arabic-NER/testmodel$ python3 -m prodigy ner.batch-train augmented_for_training /home/yan/arabicNER/Arabic-NER/testmodel/model8 --eval-split 0.2 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/prodigy/__main__.py", line 259, in <module>
    controller = recipe(*args, use_plac=True)
  File "cython_src/prodigy/core.pyx", line 167, in prodigy.core.recipe.recipe_decorator.recipe_proxy
  File "/home/yan/.local/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/yan/.local/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/prodigy/recipes/ner.py", line 377, in batch_train
    nlp = spacy.load(input_model)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/util.py", line 116, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/language.py", line 649, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "nn_parser.pyx", line 908, in spacy.syntax.nn_parser.Parser.from_disk
  File "nn_parser.pyx", line 260, in spacy.syntax.nn_parser.Parser.Model
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/_ml.py", line 278, in Tok2Vec
    glove = StaticVectors(pretrained_vectors, width, column=cols.index(ID))
  File "/usr/local/lib/python3.5/dist-packages/thinc-6.10.2-py3.5-linux-x86_64.egg/thinc/neural/_classes/static_vectors.py", line 41, in __init__
    vectors = self.get_vectors()
  File "/usr/local/lib/python3.5/dist-packages/thinc-6.10.2-py3.5-linux-x86_64.egg/thinc/neural/_classes/static_vectors.py", line 52, in get_vectors
    return get_vectors(self.ops, self.lang)
  File "/usr/local/lib/python3.5/dist-packages/thinc-6.10.2-py3.5-linux-x86_64.egg/thinc/extra/load_nlp.py", line 19, in get_vectors
    nlp = get_spacy(lang)
  File "/usr/local/lib/python3.5/dist-packages/thinc-6.10.2-py3.5-linux-x86_64.egg/thinc/extra/load_nlp.py", line 11, in get_spacy
    SPACY_MODELS[lang] = spacy.load(lang, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.5/dist-packages/spacy-2.0.12.dev0-py3.5-linux-x86_64.egg/spacy/util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'ar_model.vectors'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:
  Info about spaCy

    Platform           Linux-4.4.0-77-generic-x86_64-with-Ubuntu-16.04-xenial
    Location           /home/yan/spacyou/spaCy/spacy
    Models                            
    Python version     3.5.2          
    spaCy version      2.0.12.dev0   

This is the command I am using and the model8 is the arabic ner model I trained with spaCy.

```
python3 -m prodigy ner.batch-train augmented_for_training /home/yan/arabicNER/Arabic-NER/testmodel/model8 --eval-split 0.2
```
any sigguestion or idea? Thank you so much!

**Comment by YanLiang1102** [comment]
hey @ines  I look into the code when I am running 
```
prodigy ner.batch-train augmented_for_training /home/yan/arabicNER/Arabic-NER/testmodel/model8
```
Spacy did not load the model from the directory that I provided, I hard coded it and load in the source code it starts to run for like 30 mins I got an core segmentation error any idea?

also is there any option from command lien when you run ner.batch-train to let it know that my model is given by a path?

Thank you so much!

**Comment by ines** [comment]
Hi @YanLiang1102 – sorry for only getting to this now. For Prodigy-related questions, it's usually best if you post [on the Prodigy Forum](https://support.prodi.gy/) (unless you come across a bug or a problem with spaCy from within Prodigy).

> Spacy did not load the model from the directory that I provided

I'm not sure what you mean here – the second argument of `ner.batch-train` is the input model and will be passed directly to `spacy.load`. So in your example, this will result in:

```python
nlp = spacy.load('/home/yan/arabicNER/Arabic-NER/testmodel/model8')
```

If the model exists at that location (and there's no package or shortcut link with the same name – which is unlikely, because it's very clearly a path), spaCy will load the model from the path.

> it starts to run for like 30 mins I got an core segmentation error any idea?

Were you able to track it down and isolate the examples it fails on? If you have a look on the issue tracker or the Prodigy Forum, there are a few similar threads where we've posted some debugging tips and how to find the update that causes the segmentation fault. This would also make it a lot easier to get to the bottom of this!
