### ISSUE TITLE
Spacy training is not running on GPU

### ISSUE THREAD

**Issue by yenuka78** [explosion/spaCy#2499]
First of all, thanks for the great package!
Second, I would like to utilize my GPU (I have GeForce 1060). I followed the instruction and installed  CUDA-9.1, configured the path appropriately and checked that "import thinc.neural.gpu_ops" works without error. I also checked that "import cupy as cp" and then "x = cp.arange(6).reshape(2, 3).astype('f')" works properly. "nvcc" is found on the PATH. 
However, when I train the spacy model on new entity types as well as known entity types (e.g. PERSON) my GPU is not utilized. I tried to add "spacy.util.use_gpu(0)". Any suggestions?

Thanks!

## My Environment

* Operating System: Ubuntu 18.04 LTS
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.11
* thinc Version Used: 6.10.2
* Environment Information:

**Comment by yenuka78** [comment]
OK some updates:
I was running from inside IntelliJ and for some reason the cupy installation was not recognized... When the following is executed: 
```
def use_gpu(gpu_id):
    try:
        import cupy.cuda.device
    except ImportError:
        return None
    from thinc.neural.ops import CupyOps
```
It returns None and therefore the GPU is not used.
Anyway, running from the shell solved this problem and now when I train the model using `nlp.begin_training(use_gpu=True, device=0)` the GPU is utilized (didn't yet check the performance improvement). However, when I try to update an existing model (using `spacy.util.use_gpu(0)` and then `nlp.entity.create_optimizer()`) I get this error: 
Traceback (most recent call last):
  File "train_ner.py", line 129, in <module>
    plac.call(main)
  File "/home/yenuka/anaconda/envs/nlp36/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/yenuka/anaconda/envs/nlp36/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_ner.py", line 110, in main
    losses=losses)
  File "/home/yenuka/anaconda/envs/nlp36/lib/python3.6/site-packages/spacy/language.py", line 427, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 589, in spacy.syntax.nn_parser.Parser.update
  File "/home/yenuka/anaconda/envs/nlp36/lib/python3.6/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/home/yenuka/anaconda/envs/nlp36/lib/python3.6/site-packages/thinc/check.py", line 146, in checked_function
    return wrapped(*args, **kwargs)
  File "/home/yenuka/anaconda/envs/nlp36/lib/python3.6/site-packages/thinc/neural/_classes/affine.py", line 56, in begin_update
    output__BO = self.predict(input__BI)
  File "/home/yenuka/anaconda/envs/nlp36/lib/python3.6/site-packages/thinc/check.py", line 146, in checked_function
    return wrapped(*args, **kwargs)
  File "/home/yenuka/anaconda/envs/nlp36/lib/python3.6/site-packages/thinc/neural/_classes/affine.py", line 52, in predict
    return self.ops.affine(self.W, self.b, input__BI)
  File "ops.pyx", line 195, in thinc.neural.ops.Ops.affine
  File "ops.pyx", line 183, in thinc.neural.ops.Ops.batch_dot
  File "/home/yenuka/anaconda/envs/nlp36/lib/python3.6/site-packages/cupy/linalg/product.py", line 35, in dot
    return a.dot(b, out)
  File "cupy/core/core.pyx", line 1495, in cupy.core.core.ndarray.__array__
  File "cupy/core/core.pyx", line 380, in cupy.core.core.ndarray.astype
  File "cupy/core/elementwise.pxi", line 866, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 643, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 165, in cupy.core.core._get_kernel_params
  File "cupy/core/elementwise.pxi", line 111, in cupy.core.core._get_typename
KeyError: <class 'numpy.object_'>

Very similar to @leloss comment in [2161](https://github.com/explosion/spaCy/issues/2161)
Any suggestions?

**Comment by honnibal** [comment]
@yenuka78 I think this is the same issue as #2161 , so I'll close this to merge with that. Thanks for updating on the previous error.
