### ISSUE TITLE
name 'np_left_deps' is not defined in 'lang/es/syntax_iterators.py'

### ISSUE THREAD

**Issue by furas** [explosion/spaCy#2509]
```
import spacy

nlp = spacy.load('es')
doc = nlp("El auto rojo se detuvo enfrente")

for chunk in doc.noun_chunks:
    print(chunk)

```

SpaCy 2.0.11
Python 3.6.5
Linux Mint 

```
Traceback (most recent call last):
  File "<pyshell#9>", line 7, in <module>
    for chunk in doc.noun_chunks:
  File "doc.pyx", line 503, in __get__
  File "/usr/local/lib/python3.6/dist-packages/spacy/lang/es/syntax_iterators.py", line 19, in noun_chunks
    left, right = noun_bounds(token)
  File "/usr/local/lib/python3.6/dist-packages/spacy/lang/es/syntax_iterators.py", line 39, in noun_bounds
    if token.dep in np_left_deps:
NameError: name 'np_left_deps' is not defined
```

This code gives error in `spacy/lang/es/syntax_iterators.py` because function `noun_bounds()` want to use variables  `np_left_deps, np_right_deps, stop_deps` which are defined as local variables in another function  `noun_chunks()` and they are not sent to `noun_bounds()` as parameters.

**Comment by furas** [comment]
I found it corrected few days ago

[https://github.com/explosion/spaCy/issues/2210](https://github.com/explosion/spaCy/issues/2210)
