### ISSUE TITLE
Error 067: Invalid BILUO tag sequence mistakenly triggered

### ISSUE THREAD

**Issue by ValentinCalomme** [explosion/spaCy#2510]
## Bug

Seems related to #1907

I am training an NER model with multiple custom entities using the CLI. The model trains fine, and then when it tries to save, it throws the following error:

```
Traceback (most recent call last):
  File "c:\users\vca\appdata\local\continuum\anaconda3\envs\rocstar\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\vca\appdata\local\continuum\anaconda3\envs\rocstar\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\vca\appdata\local\continuum\anaconda3\envs\rocstar\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "c:\users\vca\appdata\local\continuum\anaconda3\envs\rocstar\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "c:\users\vca\appdata\local\continuum\anaconda3\envs\rocstar\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "c:\users\vca\appdata\local\continuum\anaconda3\envs\rocstar\lib\site-packages\spacy\cli\train.py", line 146, in train
    scorer = nlp_loaded.evaluate(dev_docs)
  File "c:\users\vca\appdata\local\continuum\anaconda3\envs\rocstar\lib\site-packages\spacy\language.py", line 495, in evaluate
    scorer.score(doc, gold, verbose=verbose)
  File "c:\users\vca\appdata\local\continuum\anaconda3\envs\rocstar\lib\site-packages\spacy\scorer.py", line 93, in score
    for annot in gold.orig_annot]))
  File "gold.pyx", line 33, in spacy.gold.tags_to_entities
ValueError: [E067] Invalid BILUO tag sequence: Got a tag starting with 'I' (inside an entity) without a preceding 'B' (beginning of an entity). Tag sequence:

['B-Kreditorenname', 'L-Kreditorenname', 'O', 'B-Strasse', 'L-Strasse', 'O', 'O', 'O', 'B-PlzStadt', 'L-PlzStadt', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-PlzStadt', 'L-PlzStadt', 'O', 'B-Kreditorenname', 'L-Kreditorenname', 'O', 'B-Strasse', 'I-Strasse', 'I-Strasse', 'L-Strasse', 'O', 'B-PlzStadt', 'L-PlzStadt', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Angebotsnummer', 'L-Angebotsnummer', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-Angebotdatum', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-Waehrung', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-Lieferanten_Mat_Nr', 'O', 'U-Preise', 'O', 'U-Preise', 'O', 'U-Preise', 'O', 'U-Menge']
```

However, when you look at the tag sequence that it returns, there is no I-ENTITY not preceded by a B-ENTITY.

## What I think

- Is the error message wrong?
- Should the error be raised at all?

**The error seems to be triggered in `spacy.gold.tags_to_entities`, which is triggered by `spacy.scorer`. Could it be that the model, trained as it is, doesn't return a valid sequence of tags, and therefore, when it tries to score that sequence, it breaks?**

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.4
* **Models:** de

**Comment by CYUlysses** [comment]
Same error encountered here. Mine outputs:
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-LOC']

**Comment by howl-anderson** [comment]
@CYUlysses @Anamay-Agnihotri @ValentinCalomme I had the same issue, but I found that is the problem of training corpus. Maybe it displays like this: ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-LOC'], but the whole tag maybe like this: ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-LOC', 'I-PERSON'], I will submit a PR to make it display more details.
