### ISSUE TITLE
Issue converting FastText for spacy

### ISSUE THREAD

**Issue by ctrado18** [explosion/spaCy#2538]
I tired: https://spacy.io/usage/vectors-similarity#converting

`python -m spacy init-model de /tmp/la_vectors_wiki_lg --vectors-loc wiki.de.vec`

For the FastText model ` wiki.de.vec`

and get:

```
Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\master\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Anaconda3\envs\master\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Anaconda3\envs\master\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\Anaconda3\envs\master\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\Anaconda3\envs\master\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\Anaconda3\envs\master\lib\site-packages\spacy\cli\init_model.py", line 46, in init_model
    vectors_data, vector_keys = read_vectors(vectors_loc) if vectors_loc else (None, None)
  File "C:\Users\Anaconda3\envs\master\lib\site-packages\spacy\cli\init_model.py", line 109, in read_vectors
    vectors_data[i] = numpy.asarray(pieces, dtype='f')
ValueError: could not broadcast input array from shape (299) into shape (300)
```

**Comment by honnibal** [comment]
Hi,

Which version of spaCy are you using? I thought I'd fixed that issue.

**Comment by ctrado18** [comment]
v2.0.9

**Comment by ines** [comment]
Could you try upgrading to the latest `v2.0.11`? This problem should be fixed in the latest version.

**Comment by ctrado18** [comment]
I will try it. I created the model now with the code. Does spacy then has the same attributes like has_vector or can you calc similiarity between two tokens with from fasttext?

**Comment by ctrado18** [comment]
I detected that some words are not contained in the spacy model after convertig from the FastText vectors! In FaststText there are many words which seem to get lost after converting them for spacy. I used this code:

```
#!/usr/bin/env python
# coding: utf8
"""Load vectors for a language trained using fastText
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md
Compatible with: spaCy v2.0.0+
"""
from __future__ import unicode_literals
import plac
import numpy

import spacy
from spacy.language import Language


@plac.annotations()
def main(lang=None):
    if lang is None:
        nlp = Language()
    else:
        # create empty language class – this is required if you're planning to
        # save the model to disk and load it back later (models always need a
        # "lang" setting). Use 'xx' for blank multi-language class.
        nlp = spacy.blank(lang)
    with open("./data/wiki.de.vec", 'rb') as file_:
        header = file_.readline()
        nr_row, nr_dim = header.split()
        nlp.vocab.reset_vectors(width=int(nr_dim))
        count = 0
        for line in file_:
            count += 1
            line = line.rstrip().decode('utf8')
            pieces = line.rsplit(' ', int(nr_dim))
            word = pieces[0]
            vector = numpy.asarray([float(v) for v in pieces[1:]], dtype='f')
            nlp.vocab.set_vector(word, vector)  # add the vectors to the vocab
    nlp.to_disk("./models/new_nlp/")


if __name__ == '__main__':
    plac.call(main)
```

**Comment by honnibal** [comment]
Is this using v2.0.9 still, or did you upgrade? If you upgrade, the `init-model` command you had at first should work.

**Comment by ctrado18** [comment]
Init works for v2.0.11. But still for as specific noun spcay gives has_vector False if this word is written in lower capital. But I saw in the strings file in vocab that this word exists in the two ways, one with upper and one with lower letter like other nouns. What is the problem?

**Comment by ctrado18** [comment]
Why is there a case sensitivity?

**Comment by ahalterman** [comment]
I've used the following code to make sure that title case words end up with a fasttext vector in spaCy:

```
string_list = [i.text for i in nlp.vocab]
for string in string_list:
    nlp.vocab.vectors.add(string.title(), row = nlp.vocab[string].rank)
```

This assigns the same vector to the lower case and title case words, so your embedding matrix won't actually get any bigger.

**Comment by ctrado18** [comment]
@ahalterman Thank you! But what files do you need to change (and what structure)? Have you then saved this as this `string.json`? Have no experience with spacy vocab structure.
