### ISSUE TITLE
CLI-spacy evaluate:  ValueError: [E067] 

### ISSUE THREAD

**Issue by eswar3** [explosion/spaCy#2661]
## How to reproduce the behaviour
I trained a NER model with training data in json format. The model got trained successfully and stored the best model under final_model. I was able to load it back and make prediction on test data.
But when I tried to evaluate using the below command 

**python -m spacy evaluate ./model-final/ ./testdata.json  -G**

I got E067 error shown below. I am pretty sure that there is no issue with the data formatting. To confirm the same, I tried re running the same command on train data on which the model was previously trained. It still gave me the same error message.

**ValueError: [E067] Invalid BILUO tag sequence: Got a tag starting with 'I' (inside an entity) without a preceding 'B' (beginning of an entity). Tag sequence:*[ ]

q1 )Is there any other way to evaluate the model ?
q2) The error doesn't show which document has the issue, Is there a way to find which document has the wrong tag sequence ?

## Your Environment

* Operating System: Ubuntu 16.04.4 LTS
* Python Version Used: Python 3.6.4 :: Anaconda, Inc.
* spaCy Version Used: 2.0.12
* Environment Information:

**Comment by eswar3** [comment]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/myenv/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/myenv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/myenv/lib/python3.6/site-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/ubuntu/anaconda3/envs/myenv/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/ubuntu/anaconda3/envs/myenv/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/ubuntu/anaconda3/envs/myenv/lib/python3.6/site-packages/spacy/cli/evaluate.py", line 44, in evaluate
    scorer = nlp.evaluate(dev_docs, verbose=False)
  File "/home/ubuntu/anaconda3/envs/myenv/lib/python3.6/site-packages/spacy/language.py", line 495, in evaluate
    scorer.score(doc, gold, verbose=verbose)
  File "/home/ubuntu/anaconda3/envs/myenv/lib/python3.6/site-packages/spacy/scorer.py", line 93, in score
    for annot in gold.orig_annot]))
  File "gold.pyx", line 33, in spacy.gold.tags_to_entities

**Comment by eswar3** [comment]
@ines  Could you please check this.

Thanks

**Comment by honnibal** [comment]
Hi @eswar3 , Sorry we didn't get to this sooner, but I believe the error is almost certainly in your data, which the error indicates is malformed. I'll close this since it's an old issue, and you've probably moved past it by now.
