### ISSUE TITLE
ModuleNotFoundError: No module named 'cymem'

### ISSUE THREAD

**Issue by RafaelDiasSilveira** [explosion/spaCy#2674]
## How to reproduce the problem

Whenever I try to run spaCy, I get the following error. I've tried installing using pip, using conda, reinstalling but always get the same error. Any idea what might be the solution for this?

```bash
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/anaconda3/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/root/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/anaconda3/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/root/anaconda3/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/root/anaconda3/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/root/anaconda3/lib/python3.6/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..compat import symlink_to, path2str
  File "/root/anaconda3/lib/python3.6/site-packages/spacy/compat.py", line 9, in <module>
    from thinc.neural.util import copy_array
  File "/root/anaconda3/lib/python3.6/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/root/anaconda3/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 11, in <module>
    from .. import util
  File "/root/anaconda3/lib/python3.6/site-packages/thinc/neural/util.py", line 3, in <module>
    from preshed.maps import PreshMap
  File "cymem.pxd", line 1, in init preshed.maps
ModuleNotFoundError: No module named 'cymem'
```

## Your Environment

* Operating System: CentOS Linux 7 (Core)
* Python Version Used: 3.6.5 - Using Anaconda
* spaCy Version Used: 2.0.12
* Environment Information:

**Comment by RafaelDiasSilveira** [comment]
I have `cymem` installed at 1.31.2. During installation I don't get any error. 

But now I got a fix on this. I removed anaconda and installed again and did a `conda update --all`.

Thanks for the help!
