### ISSUE TITLE
AssertionError CLI train NER

### ISSUE THREAD

**Issue by LizaKoz** [explosion/spaCy#2685]
Hi all, 

I try to train my own NER model. I use CLI train comand and I get this error. 

```
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command])
  File "C:\Users\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\cli\train.py", line 107, in train
    train_docs = list(train_docs)
  File "gold.pyx", line 207, in train_docs
  File "gold.pyx", line 221, in iter_gold_docs
  File "gold.pyx", line 235, in spacy.gold.GoldCorpus._make_docs
  File "doc.pyx", line 177, in spacy.tokens.doc.Doc.__init__
  File "doc.pyx", line 544, in spacy.tokens.doc.Doc.push_back
AssertionError
```

I use data in  spacy JSON format. 

Thanks a lot in advance. 

## Your Environment
* **spaCy version:** 2.0.5
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.5.4

**Comment by ines** [comment]
Could you try upgrading to the latest version? We've made a lot of updates to the error messages, so all naked `assert`s should be gone, and spaCy should show you a more meaningful message – for example, if the entity spans in your data don't match or something else is wrong. This should also make issues like this easier to debug.

If you still can't solve the problem with the improved errors, feel free to reopen!
