### ISSUE TITLE
ValueError: Could not find a gold-standard action to supervise the entity recognizer. The transition system has 61 actions.

### ISSUE THREAD

**Issue by LizaKoz** [explosion/spaCy#2714]
Hi all
 I'm trying to train my custom NER model by using CLI command
and I've got this issue: 
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command])
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\cli\train.py", line 117, in train
    drop=next(dropout_rates), losses=losses)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\language.py", line 407, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 558, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 679, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "transition_system.pyx", line 75, in spacy.syntax.transition_system.TransitionSystem.get_oracle_sequence
  File "transition_system.pyx", line 140, in spacy.syntax.transition_system.TransitionSystem.set_costs
ValueError: Could not find a gold-standard action to supervise the entity recognizer. The transition system has 61 actions

How can it be solved? Could it be the annotation issue?
Thanks in advance

**Comment by honnibal** [comment]
I do believe it's an annotation issue, yes. Could you find and paste the example it's failing on?
