### ISSUE TITLE
GPU training fails

### ISSUE THREAD

**Issue by ptamas88** [explosion/spaCy#2733]
Hello everyone,
I tried to create a new Named Entity model trained on GPU with 700k sentences. Modified the default code for my purposes, but the logic is the same. Still I get this output every time in the nlp.update() command.
```
Traceback (most recent call last):
  File ".../pydev/pydevd.py", line 1664, in <module>
    main()
  File ".../pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File ".../pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File ".../pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File ".../spacy/train.py", line 215, in <module>
    model = main(model=model,output_dir=output_dir,n_iter=n_iter,corpus=corpus, corpus_slice=corpus_slice)
  File ".../spacy/train.py", line 109, in main
    losses=losses)
  File "/usr/local/lib/python3.5/dist-packages/spacy/language.py", line 427, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 589, in spacy.syntax.nn_parser.Parser.update
  File "/usr/local/lib/python3.5/dist-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/usr/local/lib/python3.5/dist-packages/thinc/check.py", line 146, in checked_function
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/thinc/neural/_classes/affine.py", line 56, in begin_update
    input__BI = self.ops.xp.ascontiguousarray(input__BI)
  File "/usr/local/lib/python3.5/dist-packages/cupy/creation/from_data.py", line 91, in ascontiguousarray
    return core.ascontiguousarray(a, dtype)
TypeError: Argument 'a' has incorrect type (expected cupy.core.core.ndarray, got numpy.ndarray)
```
I have seen other issues about this one, but none of them solved my problem :(
Since it's not a complicated network, and i have a newer CPU I tried to train the model with the following changes:
`optimizer = nlp.begin_training(device=0)`
to
`optimizer = nlp.begin_training()`
On CPU i get a different error:
```
*** stack smashing detected ***: /usr/bin/python3 terminated
bash: line 1:   834 Aborted                 (core dumped)
```
Please help, how to train on GPU/CPU.
Thanks

## Info about Environment:

* **Python version:** 3.5.2
* **Platform:** Linux-4.15.0-33-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.12
* **CUDA version:**9.2
thinc (6.11.2)
numpy (1.15.1)
cupy (4.4.0)
chainer (4.4.0)
nvidia-driver:396

**Comment by honnibal** [comment]
This should now be resolved. Please open a new issue if you're still having problems on the new `spacy-nightly` version.
