### ISSUE TITLE
Spacy has completely stopped working: cupy.cuda.runtime.CUDARuntimeError: cudaErrorUnknown: unknown error

### ISSUE THREAD

**Issue by dkarmon** [explosion/spaCy#2778]
spaCy has suddenly stopped working completely. Even the simplest code encounters with a fatal error (see example below)
The reported error states that the problem has to do with with the integration with cuda.
Note that I did not upgrade spacy \ CUDA and up until yesterday it spacy flawlessly.
Please advise ASAP.

## How to reproduce the behaviour
```
import spacy
nlp = spacy.load("en")
doc = nlp("hello")
```
Error message:
```
Exception ignored in: <bound method Stream.__del__ of <cupy.cuda.stream.Stream object at 0x00000144738E6940>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 162, in cupy.cuda.stream.Stream.__del__
AttributeError: 'Stream' object has no attribute 'ptr'
Traceback (most recent call last):
  File "C:\Users\dakarmon\AppData\Local\Continuum\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-d63a3a0d7c00>", line 1, in <module>
    doc = nlp("hello")
  File "C:\Users\dakarmon\AppData\Local\Continuum\miniconda3\lib\site-packages\spacy\language.py", line 352, in __call__
    doc = proc(doc)
  File "nn_parser.pyx", line 338, in spacy.syntax.nn_parser.Parser.__call__
  File "nn_parser.pyx", line 400, in spacy.syntax.nn_parser.Parser.parse_batch
  File "C:\Users\dakarmon\AppData\Local\Continuum\miniconda3\lib\site-packages\spacy\util.py", line 238, in get_cuda_stream
    return CudaStream() if CudaStream is not None else None
  File "cupy\cuda\stream.pyx", line 159, in cupy.cuda.stream.Stream.__init__
  File "cupy\cuda\runtime.pyx", line 322, in cupy.cuda.runtime.streamCreate
  File "cupy\cuda\runtime.pyx", line 325, in cupy.cuda.runtime.streamCreate
  File "cupy\cuda\runtime.pyx", line 135, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorUnknown: unknown error

```

## Your Environment

* Operating System: Windows 10
* Python Version Used: Python 3.6.4
* spaCy Version Used: 2.0.12
* Environment Information:
-  CUDA 9.0

**Comment by honnibal** [comment]
Do other CUDA libraries work? Try loading up two matrices with cupy and multiplying them together.

Sometimes the GPU seems to get itself into a bad state. I don't understand this properly, but I occasionally have to reboot the machine, especially with geforce cards. The same doesn't seem to happen with the (hideously expensive) cloud cards.

If you figure out we're doing something wrong, we'd definitely like to fix it. If this is just how it is with GPU cards...I guess that sucks for everyone?

**Comment by DuyguA** [comment]
@dkarmon , is this error reproducible? What happens after rebooting? (cleaning all memory registers is always a solution, btw :laughing: )

**Comment by dkarmon** [comment]
@DuyguA and @honnibal, indeed rebooting the machine fixes the problem.
a small tip for Pycharm users, before running spacy using the IDE, run it via command line (i.e. "cmd run" -> "python" -> "import spacy ....")
