### ISSUE TITLE
Installing spaCy via `pip install spacy` on Windows 10 fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by lpq29743** [explosion/spaCy#2780]
## Problem
Installing spaCy via `pip install spacy` on Windows 10 fails with UnicodeDecodeError

```bash
Collecting spacy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/24/de/ac14cd453c98656d6738a5669f96a4ac7f668493d5e6b78227ac933c5fd4/spacy-2.0.12.tar.gz
Requirement already satisfied: numpy>=1.7 in d:\python\python36\lib\site-packages (from spacy)
Requirement already satisfied: murmurhash<0.29,>=0.28 in d:\python\python36\lib\site-packages (from spacy)
Requirement already satisfied: cymem<1.32,>=1.30 in d:\python\python36\lib\site-packages (from spacy)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in d:\python\python36\lib\site-packages (from spacy)
Collecting thinc<6.11.0,>=6.10.3 (from spacy)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/94/b1/47a88072d0a38b3594c0a638a62f9ef7c742b8b8a87f7b105f7ed720b14b/thinc-6.10.3.tar.gz
Requirement already satisfied: plac<1.0.0,>=0.9.6 in d:\python\python36\lib\site-packages (from spacy)
Requirement already satisfied: ujson>=1.35 in d:\python\python36\lib\site-packages (from spacy)
Requirement already satisfied: dill<0.3,>=0.2 in d:\python\python36\lib\site-packages (from spacy)
Requirement already satisfied: regex==2017.4.5 in d:\python\python36\lib\site-packages (from spacy)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in d:\python\python36\lib\site-packages (from spacy)
Requirement already satisfied: msgpack<1.0.0,>=0.5.6 in d:\python\python36\lib\site-packages (from thinc<6.11.0,>=6.10.3->spacy)
Requirement already satisfied: msgpack-numpy<1.0.0,>=0.4.1 in d:\python\python36\lib\site-packages (from thinc<6.11.0,>=6.10.3->spacy)
Requirement already satisfied: cytoolz<0.10,>=0.9.0 in d:\python\python36\lib\site-packages (from thinc<6.11.0,>=6.10.3->spacy)
Requirement already satisfied: wrapt<1.11.0,>=1.10.0 in d:\python\python36\lib\site-packages (from thinc<6.11.0,>=6.10.3->spacy)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in d:\python\python36\lib\site-packages (from thinc<6.11.0,>=6.10.3->spacy)
Requirement already satisfied: six<2.0.0,>=1.10.0 in d:\python\python36\lib\site-packages (from thinc<6.11.0,>=6.10.3->spacy)
Requirement already satisfied: pyreadline>=1.7.1 in d:\python\python36\lib\site-packages (from dill<0.3,>=0.2->spacy)

Requirement already satisfied: idna<2.8,>=2.5 in d:\python\python36\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in d:\python\python36\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in d:\python\python36\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy)
Requirement already satisfied: certifi>=2017.4.17 in d:\python\python36\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy)
Requirement already satisfied: msgpack-python>=0.3.0 in d:\python\python36\lib\site-packages (from msgpack-numpy<1.0.0,>=0.4.1->thinc<6.11.0,>=6.10.3->spacy)
Requirement already satisfied: toolz>=0.8.0 in d:\python\python36\lib\site-packages (from cytoolz<0.10,>=0.9.0->thinc<6.11.0,>=6.10.3->spacy)
Building wheels for collected packages: spacy, thinc
  Running setup.py bdist_wheel for spacy ... error
  Failed building wheel for spacy
  Running setup.py clean for spacy
  Running setup.py bdist_wheel for thinc ... error
  Failed building wheel for thinc
  Running setup.py clean for thinc
Failed to build spacy thinc
Installing collected packages: thinc, spacy
  Found existing installation: thinc 6.10.2
    Uninstalling thinc-6.10.2:
      Successfully uninstalled thinc-6.10.2
  Running setup.py install for thinc ... error
  Rolling back uninstall of thinc
Exception:
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\pip-9.0.3-py3.6.egg\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 25: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\pip-9.0.3-py3.6.egg\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\Python\Python36\lib\site-packages\pip-9.0.3-py3.6.egg\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "D:\Python\Python36\lib\site-packages\pip-9.0.3-py3.6.egg\pip\req\req_set.py", line 784, in install
    **kwargs
  File "D:\Python\Python36\lib\site-packages\pip-9.0.3-py3.6.egg\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "D:\Python\Python36\lib\site-packages\pip-9.0.3-py3.6.egg\pip\utils\__init__.py", line 676, in call_subprocess

    line = console_to_str(proc.stdout.readline())
  File "D:\Python\Python36\lib\site-packages\pip-9.0.3-py3.6.egg\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 25: invalid continuation byte
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

## Your Environment
* Operating System: Windows 10, 64 bit
* Python Version Used: 3.6.5

**Comment by BramVanroy** [comment]
Seems more like a pip issue than a spacy issue.

Did you try updating your pip? (cf. bottom of the trace)

**Comment by lpq29743** [comment]
@BramVanroy My origin version of pip is 9.0.3, I upgrade it to 10.0.1 and it works. Thank you very much.
