### ISSUE TITLE
problems with offline install

### ISSUE THREAD

**Issue by randomgambit** [explosion/spaCy#2863]
Hello there,

Because of my corporate firewall, I cant download the model with the built-in function. Therefore I went here https://spacy.io/models/en#en_core_web_sm and downloaded the latest model

Unfortunately, when I try to install it with `pip` it seems the program still tries to connect to the internet.

```
(base) C:\Users\John>pip install M://resources/en_core_web_sm-2.0.0.tar.gz
Processing m:\resources\en_core_web_sm-2.0.0.tar.gz
Collecting spacy>=2.0.0a18 (from en-core-web-sm==2.0.0)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/spacy/
```

How can I do that completely offline?
Thanks!

**Comment by randomgambit** [comment]
This is what I saw after the `--no-flags` install

```
(base) C:\Users\John>pip install M://resources/en_core_web_md-2.0.0.tar.gz --no-deps
Processing m:\resources\en_core_web_md-2.0.0.tar.gz
Building wheels for collected packages: en-core-web-md
  Running setup.py bdist_wheel for en-core-web-md ... done
  Stored in directory: C:\Users\John\AppData\Local\pip\Cache\wheels\3c\05\9e\jiojfre
Successfully built en-core-web-md
Installing collected packages: en-core-web-md
Successfully installed en-core-web-md-2.0.0
```

**Comment by randomgambit** [comment]
@ines however it seems the model was not installed correctly

```
import en_core_web_sm
Traceback (most recent call last):

  File "<ipython-input-56-8cbb41c39120>", line 1, in <module>
    import en_core_web_sm

  File "C:\Users\John\AppData\Local\Continuum\anaconda3\lib\site-packages\en_core_web_sm\__init__.py", line 5, in <module>
    from spacy.util import load_model_from_init_py, get_model_meta

ImportError: cannot import name 'load_model_from_init_py'
```
