### ISSUE TITLE
Setting up Spacy

### ISSUE THREAD

**Issue by cegprakash** [explosion/spaCy#2883]
## How to reproduce the behaviour
Just do `import spacy`

## Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.5.2
* spaCy Version Used: 2.0.16 
* Environment Information: Django 2.1.2

## Issues

`python -m spacy info --markdown` gives me

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/__init__.py", line 8, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
    from ..train import Trainer
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/train.py", line 3, in <module>
    from .optimizers import Adam, SGD, linear_decay
  File "optimizers.pyx", line 13, in init thinc.neural.optimizers
  File "cymem.pxd", line 4, in init thinc.neural.ops
AttributeError: module 'cymem.cymem' has no attribute 'PyMalloc'
```

When I do `python3  manage.py runserver` , I get

```
  File "/home/cegprakash/workspace/python-engine/keyword_strategy.py", line 4, in <module>
    import spacy
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/__init__.py", line 10, in <module>
    from .cli.info import info as cli_info
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/cli/download.py", line 11, in <module>
    from .link import link
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..compat import symlink_to, path2str
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/compat.py", line 32, in <module>
    from thinc.neural.optimizers import Optimizer
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
    from ..train import Trainer
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/train.py", line 3, in <module>
    from .optimizers import Adam, SGD, linear_decay
  File "optimizers.pyx", line 13, in init thinc.neural.optimizers
  File "stringsource", line 104, in init thinc.neural.ops
AttributeError: type object 'thinc.neural.ops.array' has no attribute '__reduce_cython__'

```

#2849 #2439

**Comment by coradek** [comment]
I also have this issue 
Operating system: OSX 10.14 (Mojave)
Python 3.6.3 :: Anaconda custom (64-bit)
spaCy Version: 2.0.16

```
$ python -m spacy
Traceback (most recent call last):
  File "/Users/i862304/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/i862304/anaconda3/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/i862304/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/i862304/anaconda3/lib/python3.6/site-packages/spacy/__init__.py", line 8, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/Users/i862304/anaconda3/lib/python3.6/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/Users/i862304/anaconda3/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 11, in <module>
    from .. import util
  File "/Users/i862304/anaconda3/lib/python3.6/site-packages/thinc/neural/util.py", line 3, in <module>
    from preshed.maps import PreshMap
  File "cymem.pxd", line 4, in init preshed.maps
AttributeError: module 'cymem.cymem' has no attribute 'PyMalloc'
```

**Comment by ines** [comment]
Yes, it sounds like you may have ended up with two incompatible versions. Uninstalling spaCy's dependencies and reinstalling everything should help. If you're using a virtual environment, you might also want to remove it and start again, if that's easier.
