### ISSUE TITLE
ImportError: cannot import name 'ADVERBS'

### ISSUE THREAD

**Issue by wn-gh** [explosion/spaCy#2898]
Checked #2093 for a similar issue which was resolved by setting Locale however mine seems not caused by Locale. (I could be wrong and appreciate your help)

Spacy and en were working well before today when I had the below issue. It was generally caused by "from ._adverbs import ADVERBS" with the error "ImportError: cannot import name 'ADVERBS'". Below are the details.

>> import Spacy
>> spacy.load('en')
```bash
Traceback (most recent call last):
  File "Anaconda3\lib\site-packages\spacy\util.py", line 50, in get_lang_class
    module = importlib.import_module('.lang.%s' % lang, 'spacy')
  File “\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "\Anaconda3\lib\site-packages\spacy\lang\en\__init__.py", line 10, in <module>
    from .lemmatizer import LEMMA_RULES, LEMMA_INDEX, LEMMA_EXC, LOOKUP
  File "\Anaconda3\lib\site-packages\spacy\lang\en\lemmatizer\__init__.py", line 7, in <module>
    from ._adverbs import ADVERBS
ImportError: cannot import name 'ADVERBS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File \Anaconda3\lib\site-packages\spacy\__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "\Anaconda3\lib\site-packages\spacy\util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "\Anaconda3\lib\site-packages\spacy\util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "\Anaconda3\lib\site-packages\spacy\data\en\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "\Anaconda3\lib\site-packages\spacy\util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "\Anaconda3\lib\site-packages\spacy\util.py", line 143, in load_model_from_path
    cls = get_lang_class(meta['lang'])
  File "\Anaconda3\lib\site-packages\spacy\util.py", line 52, in get_lang_class
    raise ImportError(Errors.E048.format(lang=lang))
ImportError: [E048] Can't import language en from spacy.lang.
```
I reinstalled spacy, re-downloaded the en_core_web_md and updated the linkage as below. But the issue remains.
python -m spacy download en
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en --force
    Linking successful
    \Anaconda3\lib\site-packages\en_core_web_md -->
    \Anaconda3\lib\site-packages\spacy\data\en
    You can now load the model via spacy.load('en')

## Your Environment

* Operating System: Win10
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.16
* Environment Information:  en_core_web_md

**Comment by wn-gh** [comment]
Issue resolved.
Found for unknown reason, the _adverbs under the language folder is totally empty. Don't know what had happened.
Copied the file from github and the issue was resolved.
