### ISSUE TITLE
Cannot download or validate 

### ISSUE THREAD

**Issue by HarveySummers** [explosion/spaCy#2907]
Prior issues checked.
Tried different proxies & ports
Read troubleshooting guide
Sacrificed a TI-99 calculator to the gods 

## How to reproduce the problem

python -m spacy download en
python -m spacy validate

Generate the same errors:

```bash
C:\Users\REDACTED>python -m spacy validate
Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 815, in _prepare_proxy
    conn.connect()
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 314, in connect
    conn = self._new_conn()
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000026C0DC44630>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000026C0DC44630>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\cli\validate.py", line 20, in validate
    r = requests.get(about.__compatibility__)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\REDACTED\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000026C0DC44630>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)))


```

## Info about spaCy
* **spaCy version:** 2.0.16
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.7
* Environment Information:
http=REDACTED:80
https=REDACTED:443
https_proxy=REDACTED:443
http_proxy=REDACTED:80
ftp_proxy=REDACTED:443
```bash
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0    defaults
_tflow_select             2.2.0                     eigen    defaults
absl-py                   0.6.1                    py36_0    defaults
alabaster                 0.7.12                   py36_0    defaults
anaconda                  custom           py36h363777c_0    defaults
anaconda-client           1.7.2                    py36_0    defaults
anaconda-navigator        1.9.2                    py36_0    defaults
anaconda-project          0.8.2                    py36_0    defaults
appdirs                   1.4.3            py36h28b3542_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astor                     0.7.1                    py36_0    defaults
astroid                   2.0.4                    py36_0    defaults
astropy                   3.0.5            py36he774522_0    defaults
atom                      0.4.1            py36h6538335_0    defaults
atomicwrites              1.2.1                    py36_0    defaults
attrs                     18.2.0           py36h28b3542_0    defaults
automat                   0.7.0                    py36_0    defaults
autopep8                  1.4.2                    py36_0    defaults
babel                     2.6.0                    py36_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0                      py36_1    defaults
backports.os              0.1.1                    py36_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py36_2    defaults
beautifulsoup4            4.6.3                    py36_0    defaults
bitarray                  0.8.3            py36hfa6e2cd_0    defaults
bkcharts                  0.2              py36h7e685f7_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py36_0    defaults
bleach                    3.0.2                    py36_0    defaults
blosc                     1.14.4               he51fdeb_0    defaults
bokeh                     1.0.1                    py36_0    defaults
boto                      2.49.0                   py36_0    defaults
bottleneck                1.2.1            py36h452e1ab_1    defaults
BoxInterface              0.2                       <pip>
bzip2                     1.0.6                hfa6e2cd_5    defaults
ca-certificates           2018.03.07                    0    defaults
cachetools                2.1.0                     <pip>
certifi                   2018.10.15               py36_0    defaults
cffi                      1.11.5           py36h74b6da3_1    defaults
chardet                   3.0.4                    py36_1    defaults
click                     7.0                      py36_0    defaults
cloudpickle               0.6.1                    py36_0    defaults
clyent                    1.2.2                    py36_1    defaults
colorama                  0.4.0                    py36_0    defaults
comtypes                  1.1.7                    py36_0    defaults
conda                     4.5.11                   py36_0    defaults
conda-build               3.16.2                   py36_0    defaults
conda-env                 2.6.0                         1    defaults
conda-verify              3.1.1                    py36_0    defaults
console_shortcut          0.1.1                         3    defaults
constantly                15.1.0           py36h28b3542_0    defaults
contextlib2               0.5.5            py36he5d52c0_0    defaults
cryptography              2.3.1            py36h74b6da3_0    defaults
cssselect                 1.0.3                    py36_0    defaults
curl                      7.62.0               h2a8f88b_0    defaults
cycler                    0.10.0           py36h009560c_0    defaults
cymem                     2.0.2            py36h74a9793_0    defaults
cython                    0.29             py36ha925a31_0    defaults
cytoolz                   0.9.0.1          py36hfa6e2cd_1    defaults
dash                      0.28.1                    <pip>
dash-core-components      0.30.2                    <pip>
dash-html-components      0.13.2                    <pip>
dash-renderer             0.14.1                    <pip>
dask                      0.20.0                   py36_0    defaults
dask-core                 0.20.0                   py36_0    defaults
datashape                 0.5.4                    py36_1    defaults
decorator                 4.3.0                    py36_0    defaults
dill                      0.2.8.2                  py36_0    defaults
distributed               1.24.0                   py36_0    defaults
docutils                  0.14             py36h6012d8f_0    defaults
en-core-web-sm            2.0.0                     <pip>
en-vectors-web-lg         2.0.0                     <pip>
enaml                     0.10.2           py36h6538335_0    defaults
entrypoints               0.2.3                    py36_2    defaults
et_xmlfile                1.0.1            py36h3d2d736_0    defaults
fastcache                 1.0.2            py36hfa6e2cd_2    defaults
filelock                  3.0.10                   py36_0    defaults
flask                     1.0.2                    py36_1    defaults
Flask-Compress            1.4.0                     <pip>
flask-cors                3.0.6                    py36_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
ftfy                      4.4.3                     <pip>
future                    0.17.1                   py36_0    defaults
gast                      0.2.0                    py36_0    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.3.7            py36he774522_1    defaults
glob2                     0.6                      py36_1    defaults
greenlet                  0.4.15           py36hfa6e2cd_0    defaults
grpcio                    1.14.1           py36h5c4b210_0    defaults
h5py                      2.8.0            py36h3bdd7fb_2    defaults
hdf5                      1.10.2               hac2f561_1    defaults
heapdict                  1.0.0                    py36_2    defaults
hide-code                 0.5.2                     <pip>
html5lib                  1.0.1                    py36_0    defaults
hyperlink                 18.0.0                   py36_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.7                      py36_0    defaults
ijson                     2.3                       <pip>
imageio                   2.4.1                    py36_0    defaults
imagesize                 1.1.0                    py36_0    defaults
importlib_metadata        0.6                      py36_0    defaults
incremental               17.5.0                   py36_0    defaults
intel-openmp              2019.0                      118    defaults
ipykernel                 5.1.0            py36h39e3cac_0    defaults
ipython                   7.1.1            py36h39e3cac_0    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
ipywidgets                7.4.2                    py36_0    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              1.1.0                    py36_0    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.13.1                   py36_0    defaults
jinja2                    2.10                     py36_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0            py36h7636477_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter-contrib-core      0.3.3                     <pip>
jupyter-contrib-nbextensions 0.5.0                     <pip>
jupyter-highlight-selected-word 0.2.0                     <pip>
jupyter-latex-envs        1.4.4                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyter_client            5.2.3                    py36_0    defaults
jupyter_console           6.0.0                    py36_0    defaults
jupyter_core              4.4.0                    py36_0    defaults
jupyterlab                0.35.3                   py36_0    defaults
jupyterlab_launcher       0.13.1                   py36_0    defaults
jupyterlab_server         0.2.0                    py36_0    defaults
keras                     2.2.4                         0    defaults
keras-applications        1.0.6                    py36_0    defaults
keras-base                2.2.4                    py36_0    defaults
keras-preprocessing       1.0.5                    py36_0    defaults
keyring                   16.0.0                   py36_0    defaults
kiwisolver                1.0.1            py36h6538335_0    defaults
lazy-object-proxy         1.3.1            py36hfa6e2cd_2    defaults
libarchive                3.3.3                h798a506_0    defaults
libcurl                   7.62.0               h2a8f88b_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.35               h2a8f88b_0    defaults
libprotobuf               3.6.1                h7bd577a_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libssh2                   1.8.0                hd619d38_4    defaults
libtiff                   4.0.9                h36446d0_2    defaults
libxml2                   2.9.8                hadb2253_1    defaults
libxslt                   1.1.32               hf6f1972_0    defaults
llvmlite                  0.25.0                   py36_0    defaults
locket                    0.2.0            py36hfed976d_1    defaults
lxml                      4.2.5            py36hef2cd61_0    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markdown                  3.0.1                    py36_0    defaults
markupsafe                1.0              py36hfa6e2cd_1    defaults
matplotlib                3.0.1            py36hc8f65d3_0    defaults
mccabe                    0.6.1                    py36_1    defaults
menuinst                  1.4.14           py36hfa6e2cd_0    defaults
mistune                   0.8.4            py36he774522_0    defaults
mkl                       2019.0                      118    defaults
mkl-service               1.1.2            py36hb217b18_5    defaults
mkl_fft                   1.0.6            py36hdbbee80_0    defaults
mkl_random                1.0.1            py36h77b88f5_1    defaults
more-itertools            4.3.0                    py36_0    defaults
mpmath                    1.0.0                    py36_2    defaults
msgpack-numpy             0.4.3.2                  py36_0    defaults
msgpack-python            0.5.6            py36he980bc4_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py36_0    defaults
murmurhash                1.0.1            py36h33f27b4_0    defaults
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.3.1                    py36_0    defaults
nbformat                  4.4.0            py36h3a5bc1b_0    defaults
networkx                  2.2                      py36_1    defaults
nltk                      3.3.0                    py36_0    defaults
nose                      1.3.7                    py36_2    defaults
notebook                  5.7.0                    py36_0    defaults
numba                     0.40.0           py36hf9181ef_0    defaults
numexpr                   2.6.8            py36h9ef55f4_0    defaults
numpy                     1.15.4           py36ha559c80_0    defaults
numpy-base                1.15.4           py36h8128ebf_0    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1            py36h7560279_0    defaults
olefile                   0.46                     py36_0    defaults
openpyxl                  2.5.9                    py36_0    defaults
openssl                   1.0.2p               hfa6e2cd_0    defaults
packaging                 18.0                     py36_0    defaults
pandas                    0.23.4           py36h830ac7b_0    defaults
pandas-profiling          1.4.1                     <pip>
pandas-profiling          1.4.1                    py36_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
parsel                    1.5.1                    py36_0    defaults
parso                     0.3.1                    py36_0    defaults
partd                     0.3.9                    py36_0    defaults
path.py                   11.5.0                   py36_0    defaults
pathlib2                  2.3.2                    py36_0    defaults
patsy                     0.5.1                    py36_0    defaults
pdfkit                    0.6.1                     <pip>
pep8                      1.7.1                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pillow                    5.3.0            py36hdc69c19_0    defaults
pip                       18.1                     py36_0    defaults
pip                       18.1                      <pip>
pkginfo                   1.4.2                    py36_1    defaults
plac                      0.9.6                    py36_0    defaults
plotly                    3.3.0                     <pip>
pluggy                    0.8.0                    py36_0    defaults
ply                       3.11                     py36_0    defaults
preshed                   2.0.1            py36h33f27b4_0    defaults
prometheus_client         0.4.2                    py36_0    defaults
prompt_toolkit            2.0.7                    py36_0    defaults
protobuf                  3.6.1            py36h33f27b4_0    defaults
psutil                    5.4.8            py36he774522_0    defaults
py                        1.7.0                    py36_0    defaults
pyasn1                    0.4.4            py36h28b3542_0    defaults
pyasn1-modules            0.2.2                    py36_0    defaults
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36hfa6e2cd_0    defaults
pycparser                 2.19                     py36_0    defaults
pycrypto                  2.6.1            py36hfa6e2cd_9    defaults
pycurl                    7.43.0.2         py36h74b6da3_0    defaults
pydispatcher              2.0.5                    py36_1    defaults
pyemd                     0.5.1                     <pip>
pyflakes                  2.0.0                    py36_0    defaults
pygments                  2.2.0            py36hb010967_0    defaults
pyhamcrest                1.9.0                    py36_2    defaults
pylint                    2.1.1                    py36_0    defaults
pyodbc                    4.0.24           py36h6538335_0    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pyparsing                 2.3.0                    py36_0    defaults
Pyphen                    0.9.5                     <pip>
pyqt                      5.9.2            py36h6538335_2    defaults
pyreadline                2.1                      py36_1    defaults
pyrfc                     0.1.2                     <pip>
pysocks                   1.6.8                    py36_0    defaults
pytables                  3.4.4            py36he6f6034_0    defaults
pytest                    3.10.0                   py36_0    defaults
pytest-arraydiff          0.2              py36h39e3cac_0    defaults
pytest-astropy            0.4.0                    py36_0    defaults
pytest-doctestplus        0.1.3                    py36_0    defaults
pytest-openfiles          0.3.0                    py36_0    defaults
pytest-remotedata         0.3.1                    py36_0    defaults
pytest-runner             4.2                      py36_0    defaults
python                    3.6.7                h33f27b4_1    defaults
python-dateutil           2.7.5                    py36_0    defaults
python-Levenshtein        0.12.0                    <pip>
python-libarchive-c       2.8                      py36_6    defaults
python-pptx               0.6.15                    <pip>
pytz                      2018.7                   py36_0    defaults
pywavelets                1.0.1            py36h8c2d366_0    defaults
pywin32                   223              py36hfa6e2cd_1    defaults
pywinpty                  0.5.4                    py36_0    defaults
pyyaml                    3.13             py36hfa6e2cd_0    defaults
pyzmq                     17.1.2           py36hfa6e2cd_0    defaults
qt                        5.9.6            vc14h1e9a669_2    defaults
qtawesome                 0.5.2                    py36_0    defaults
qtconsole                 4.4.2                    py36_0    defaults
qtpy                      1.5.2                    py36_0    defaults
queuelib                  1.5.0                    py36_0    defaults
regex                     2018.11.02       py36he774522_0    defaults
regex                     2017.04.05                <pip>
requests                  2.20.0                   py36_0    defaults
retrying                  1.3.3                     <pip>
rope                      0.11.0                   py36_0    defaults
ruamel_yaml               0.15.46          py36hfa6e2cd_0    defaults
scikit-image              0.14.0           py36h6538335_1    defaults
scikit-learn              0.20.0           py36heebcf9a_1    defaults
scipy                     1.1.0            py36h4f6bf74_1    defaults
scrapy                    1.5.1                    py36_0    defaults
seaborn                   0.9.0                    py36_0    defaults
selenium                  3.14.1           py36he774522_0    defaults
send2trash                1.5.0                    py36_0    defaults
service_identity          17.0.0           py36h28b3542_0    defaults
setuptools                40.5.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36h17d0c80_0    defaults
sip                       4.19.8           py36h6538335_0    defaults
six                       1.11.0                   py36_1    defaults
snappy                    1.1.7                h777316e_3    defaults
snowballstemmer           1.2.1            py36h763602f_0    defaults
sortedcollections         1.0.1                    py36_0    defaults
sortedcontainers          2.0.5                    py36_0    defaults
spacy                     2.0.16           py36hcce6980_0    defaults
sphinx                    1.8.1                    py36_0    defaults
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-websupport  1.1.0                    py36_1    defaults
spyder                    3.3.1                    py36_1    defaults
spyder-kernels            0.2.6                    py36_0    defaults
sqlalchemy                1.2.13           py36he774522_0    defaults
sqlite                    3.25.2               hfa6e2cd_0    defaults
statsmodels               0.9.0            py36h452e1ab_0    defaults
sympy                     1.3                      py36_0    defaults
tblib                     1.3.2            py36h30f5020_0    defaults
tensorboard               1.11.0           py36he025d50_0    defaults
tensorflow                1.11.0          eigen_py36h346fd36_0    defaults
tensorflow-base           1.11.0          eigen_py36h45df0d8_0    defaults
termcolor                 1.1.0                    py36_1    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.4.2                    py36_0    defaults
textacy                   0.6.2                     <pip>
thinc                     6.12.0           py36hb854c30_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   5.1.1            py36hfa6e2cd_0    defaults
tornado                   5.1.1                     <pip>
tqdm                      4.28.1           py36h28b3542_0    defaults
traitlets                 4.3.2            py36h096827d_0    defaults
twisted                   18.9.0           py36he774522_0    defaults
typed-ast                 1.1.0            py36hfa6e2cd_0    defaults
typing                    3.6.4                    py36_0    defaults
ujson                     1.35             py36hfa6e2cd_0    defaults
unicodecsv                0.14.1           py36h6450c06_0    defaults
Unidecode                 1.0.22                    <pip>
urllib3                   1.23                     py36_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
w3lib                     1.19.0                   py36_0    defaults
wcwidth                   0.1.7            py36h3d5aa90_0    defaults
webencodings              0.5.1                    py36_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.32.2                   py36_0    defaults
widgetsnbextension        3.4.2                    py36_0    defaults
win_inet_pton             1.0.1                    py36_1    defaults
win_unicode_console       0.5              py36hcdbd4b5_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py36hfa6e2cd_2    defaults
xlrd                      1.1.0                    py36_1    defaults
xlsxwriter                1.1.2                    py36_0    defaults
xlwings                   0.14.0                   py36_0    defaults
xlwt                      1.3.0            py36h1a4751e_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.2.5                he025d50_1    defaults
zict                      0.1.3                    py36_0    defaults
zlib                      1.2.11               h8395fce_2    defaults
zope                      1.0                      py36_1    defaults
zope.interface            4.6.0            py36he774522_0    defaults
zstd                      1.3.7                h508b16e_0    defaults
```

**Comment by HarveySummers** [comment]
spacy seems to use pip or the same mechanism as pip. setting the proxy to :443 solve one problem, but broke pip or urllib. setting it back to :80 seems to have resolved the problem, along with running it from a command with with admin privileges.

**Comment by HarveySummers** [comment]
Thanks all!
