### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/spacy/data/en_core_web_lg/en_core_web_lg-2.0.0/vocab/strings.json'

### ISSUE THREAD

**Issue by Diego999** [explosion/spaCy#2917]
## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('en_core_web_lg')
```

```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/diego/Github/SummarizationConcepts/kmeans_word2vec_preprocessed.py", line 21, in <module>
    nlp = spacy.load('en_core_web_lg')
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/data/en_core_web_lg/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 647, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 635, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 376, in spacy.vocab.Vocab.from_disk
  File "strings.pyx", line 212, in spacy.strings.StringStore.from_disk
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1165, in open
    opener=self._opener)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1019, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/spacy/data/en_core_web_lg/en_core_web_lg-2.0.0/vocab/strings.json'
```

Hi guys,

This was working 2 weeks ago and it doesn't anymore I don't know why. I tried re-installing spacy (v2.0.16) and the model with ```pip3.7 install https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.0.0/en_core_web_lg-2.0.0.tar.gz```

Here is my folder:
```
{18-11-09 19:38}ibm:/usr/local/lib/python3.7/site-packages/spacy/data diego% tree en_core_web_lg 
en_core_web_lg
├── __init__.py
├── __pycache__
│   └── __init__.cpython-37.pyc
├── en_core_web_lg-2.0.0
│   ├── accuracy.json
│   ├── meta.json
│   ├── ner
│   │   ├── cfg
│   │   ├── lower_model
│   │   ├── moves
│   │   ├── tok2vec_model
│   │   └── upper_model
│   ├── parser
│   │   ├── cfg
│   │   ├── lower_model
│   │   ├── moves
│   │   ├── tok2vec_model
│   │   └── upper_model
│   ├── tagger
│   │   ├── cfg
│   │   ├── model
│   │   └── tag_map
│   ├── tokenizer
│   └── vocab
│       ├── key2row
│       ├── lexemes.bin
│       └── vectors
└── meta.json

6 directories, 22 files
```

Do you have any idea why it doesn't work ?

Thanks 
## Your Environment

* Operating System: Mac OSX 10.14.1
* Python Version Used: 3.7
* spaCy Version Used: 2.0.16 (also happened with 2.0.12)
* Environment Information:

**Comment by ines** [comment]
Looks like this is the same issue as #2902 and probably #2910.

Are you running an antivirus program? If so, try disabling it temporarily and download the model again. For some reason, some tools have recently started falsely flagging the `strings.json` as malicious. Users have already reported it as a false positive, so I hope that this will be resolved soon.

**Comment by Diego999** [comment]
You are absolutely right, these are similar. I'm surprised I couldn't find these issues. Never mind.  Avast detects it as a virus. I set it up to consider this as a false positive and it works now. Thank you for your help !
