### ISSUE TITLE
Issue running spaCy after updating to latest build.

### ISSUE THREAD

**Issue by adwaraki** [explosion/spaCy#2918]
## How to reproduce the problem
I just happened to get back to using spaCy and Prodigy after a brief hiatus and saw that there were new versions for both. I have been using spaCy that is built from source, since I made some modifications to the tokenization schemes. I hadn't pulled in all the updated commits from the repo and spaCy and Prodigy 1.5.1 were working well.

When I received an email notifying me about the Prodigy 1.6 release, I went ahead and installed it into my virtual environment, Since Prodigy normally installs spaCy, which it did in my case since it wasn't present in site-packages (due to compiling from source), I had to uninstall spaCy with pip uninstall. Running spaCy then ended up with the Cymem error. 

I went through the issue tracker and saw that pip could be causing issues with states, so went ahead and created a new virtual environment. This time around, I pulled all the changes from the spaCy repo and compiled the spaCy sources again in the new environment, and ran the validate method. I am still getting the Cymem error and don't know how to fix this issue.

```bash
[Abhishek:~/Projects/Git-Repositories/spaCy] [Spacy-Prodigy] master(+0/-0)* 3s ± python -m spacy validate
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/Abhishek/Projects/Git-Repositories/spaCy/spacy/__init__.py", line 10, in <module>
    from .cli.info import info as cli_info
  File "/Users/Abhishek/Projects/Git-Repositories/spaCy/spacy/cli/__init__.py", line 6, in <module>
    from .train import train
  File "/Users/Abhishek/Projects/Git-Repositories/spaCy/spacy/cli/train.py", line 12, in <module>
    from ..gold import GoldCorpus, minibatch
  File "cymem.pxd", line 1, in init spacy.gold
ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48
```

Spacy and Prodigy installed using pip work fine, I have tested it and the validate methods clears everything. The problem is that I have made some modifications to the tokenizer.pyx file, to support my tokenization (which could not be accomplished using the methods specified in the docs) and hence have to compile from source. So my workflow would be to compile Spacy from source and use Prodigy in the same virtual environment. 

The first order of business would be to just get Spacy to work and that would be a great help.

@honnibal, please advise. 

## Your Environment
* macOS Mojave
* Python Version Used: Python 3.6
* spaCy Version Used: The latest build on the spaCy repo
* Environment Information: Not sure what other environment information is required. Would be happy to provide it.

**Comment by adwaraki** [comment]
For some reason, spaCy was not picking up the cleaned repo. The previously compiled thinc artifacts still persisted. Thoroughly cleaned out the repo, rebuilt it and it now works. Sorry about the confusion. Yet to test Prodigy though.
