### ISSUE TITLE
Import spacy fails in pydroid3 due to ujson strreverse error

### ISSUE THREAD

**Issue by InputMoe** [explosion/spaCy#2955]
## How to reproduce the behaviour

After successful installation: 

`python -m spacy download en`

or

`import spacy`

Do not work and produce the following error message:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>                                      
  start(fakepyfile,mainpyfile)                                     
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start                                         
  exec(open(mainpyfile).read(),  __main__.__dict__)                
  File "<string>", line 1, in <module>                               
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/spacy/__init__.py", line 10, in <module>    
  from .cli.info import info as cli_info                           
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>                                                                    
  from .download import download                                   
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/spacy/cli/download.py", line 11, in <module>                                                                   
  from .link import link                                           
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/spacy/cli/link.py", line 8, in <module>     
  from ..compat import symlink_to, path2str                        
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/spacy/compat.py", line 5, in <module>
    import ujson
ImportError: dlopen failed: cannot locate symbol "strreverse" referenced by "/data/data/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/ujson.cpython-36m.so"...

## Your Environment
* Operating System: executed on Android 8  in the app Pydroid 3
* Python Version Used: 3.6.2
* spaCy Version Used: 2.0.16
* Environment Information:

**Comment by honnibal** [comment]
This is unfortunate, but I'm not sure we'll be able to resolve this. So is that a system call that the platform is missing, or...?

Here's a suggestion for how you might be able to work around this. You could package a Python library called `ujson` that simply consists of a `__init__.py` that simply does `from json import *`. You'd then have to make sure this dummy `ujson` package has a version number within the range that spaCy expects. If you install this package before installing spaCy, pip should see that the ujson dependency is satisfied by your package, and won't install the real ujson from PyPi.

**Comment by ines** [comment]
One thing to note: I'm not 100% sure but it's possible that spaCy uses `ujson`-specific method arguments that the regular `json` module doesn't have. So if you see weird errors about unknown arguments, you might have to mock those (e.g. by making your fake `ujson` module expose a method that catches those arguments but does nothing). But fingers crossed everything works and you won't have to 🤞

**Comment by InputMoe** [comment]
Thx for your answers. I tried the following:

I replaced:
`import ujson`

in every file by:

`try:
    import ujson
except ImportError:
    import simplejson as ujson`

and amended the requirements.txt with `simplejson`. 

It worked for me and I could use it on android.

I didnt test it on other plattforms. But if no specific ujson methods are used, it should work fine on all other platforms.
