### ISSUE TITLE
Problem with saving retrained model to disk

### ISSUE THREAD

**Issue by arijit32** [explosion/spaCy#2958]
## Your Environment

* Operating System: Linux 4.4.0-1044-aws
* Python Version Used: Python 3.6.4 :: Anaconda, Inc.
* spaCy Version Used: 2.0
* Environment Information: Running Python from shell without any containerization or other stuff

## The issue
**Here is the code that I used to retrain a published model (large English):**

    with open('./train_data2.txt', 'rb') as fp:   # Unpickling
        train_data = pickle.load(fp)

    #train_data1 = train_data[:10]

    nlp = spacy.load('./LanguageModel')
    ner = nlp.get_pipe('ner')
    for _, annotations in train_data:
        for ent in annotations.get('entities'):
            ner.add_label(ent[2])

    n_iter = 20
    other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'ner']
    with nlp.disable_pipes(*other_pipes):  # only train NER
        i = 0
        optimizer = nlp.begin_training()
        for itn in range(n_iter):
            print('Epoch no: ' + str(i))
            i += 1
            random.shuffle(train_data)
            losses = {}
            # batch up the examples using spaCy's minibatch
            batches = minibatch(train_data, size=compounding(4., 32., 1.001))
            for batch in batches:
                texts, annotations = zip(*batch)
                nlp.update(
                    texts,  # batch of texts
                    annotations,  # batch of annotations
                    drop=0.5,  # dropout - make it harder to memorise data
                    sgd=optimizer,  # callable to update weights
                    losses=losses)

    nlp.to_disk('./LanguageModel7')

**The training process goes through the training epochs, and saves a bunch of files in the folder, but finally gives this error and exits:**

/home/adasgupta/anaconda3/bin/python3.6 /home/adasgupta/pycharm-community-2017.3.1/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 44778 --file /home/adasgupta/PycharmProjects/Research/spaCyModelUpdate3.py
pydev debugger: process 2057 is connecting

Connected to pydev debugger (build 173.3942.36)
/home/adasgupta/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/adasgupta/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)
2018-11-24 19:56:09.681472
Epoch no: 0
Epoch no: 1
Epoch no: 2
Epoch no: 3
Epoch no: 4
Epoch no: 5
Epoch no: 6
Epoch no: 7
Epoch no: 8
Epoch no: 9
Epoch no: 10
Epoch no: 11
Epoch no: 12
Epoch no: 13
Epoch no: 14
Epoch no: 15
Epoch no: 16
Epoch no: 17
Epoch no: 18
Epoch no: 19
Traceback (most recent call last):
  File "/home/adasgupta/pycharm-community-2017.3.1/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/home/adasgupta/pycharm-community-2017.3.1/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/adasgupta/pycharm-community-2017.3.1/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/adasgupta/pycharm-community-2017.3.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/adasgupta/PycharmProjects/Research/spaCyModelUpdate3.py", line 359, in <module>
    nlp.to_disk('./LanguageModel7')
  File "/home/adasgupta/anaconda3/lib/python3.6/site-packages/spacy/language.py", line 607, in to_disk
    util.to_disk(path, serializers, {p: False for p in disable})
  File "/home/adasgupta/anaconda3/lib/python3.6/site-packages/spacy/util.py", line 514, in to_disk
    writer(path / key)
  File "/home/adasgupta/anaconda3/lib/python3.6/site-packages/spacy/language.py", line 606, in <lambda>
    serializers['vocab'] = lambda p: self.vocab.to_disk(p)
  File "vocab.pyx", line 368, in spacy.vocab.Vocab.to_disk
  File "vectors.pyx", line 339, in spacy.vectors.Vectors.to_disk
  File "/home/adasgupta/anaconda3/lib/python3.6/site-packages/spacy/util.py", line 514, in to_disk
    writer(path / key)
  File "vectors.pyx", line 336, in spacy.vectors.Vectors.to_disk.lambda3
  File "vectors.pyx", line 331, in spacy.vectors.Vectors.to_disk.lambda1
  File "/home/adasgupta/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 521, in save
    pickle_kwargs=pickle_kwargs)
  File "/home/adasgupta/anaconda3/lib/python3.6/site-packages/numpy/lib/format.py", line 604, in write_array
    array.tofile(fp)
OSError: 205449300 requested and 60939232 written

Process finished with exit code 1

**Comment by honnibal** [comment]
It looks like you're out of disk space? You could try not saving the vectors and copying them in afterwards. I think setting `nlp.vocab.vectors = None` just before saving might work. Alternatively, you can make sure you're saving to a disk partition with more space.

**Comment by arijit32** [comment]
Thanks for your kindness, I appreciate the response.
