### ISSUE TITLE
spacy.tokens.doc.Doc object has no attribute 'txt'

### ISSUE THREAD

**Issue by CamilleSchr** [explosion/spaCy#2959]
Hello ! 

I install spacy (pip install spacy, then python -m spacy download en). To have spyder environment, I install wynpython (unforntunately I cannot install ananconda).

![help_spacy](https://user-images.githubusercontent.com/45320160/48973132-c9d7d480-f038-11e8-91e4-0dcc763cafc6.png)

This is my problem : 
In spyder, I create a script : 
import spacy
nlp=spacy.load('en')
doc=nlp(u"Please help me")
doc.txt

But in the console, I have this result : 
runfile('C:/Users/Camille/WPy-3702/settings/.spyder-py3/temp.py', wdir='C:/Users/Camille/WPy-3702/settings/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-8-8e9a4a203fa4>", line 1, in <module>
    runfile('C:/Users/Camille/WPy-3702/settings/.spyder-py3/temp.py', wdir='C:/Users/Camille/WPy-3702/settings/.spyder-py3')

  File "C:\Users\Camille\WPy-3702\python-3.7.0.amd64\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\Camille\WPy-3702\python-3.7.0.amd64\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Camille/WPy-3702/settings/.spyder-py3/temp.py", line 15, in <module>
    doc.txt

**AttributeError: 'spacy.tokens.doc.Doc' object has no attribute 'txt'**

Can you help me please ? :(

Thanks
Camille

##  Environment 
* Operating System:  windows
* Python Version Used: Python 3.7
* spaCy Version Used: Spacy-2.0.16

**Comment by CamilleSchr** [comment]
Problem solved !

instead of : 
doc.txt

put :
for token in doc:
    print(token.text, token.pos_, token.lemma_)
