### ISSUE TITLE
spacy v2.1.0a3 or v2.1.0a4  can't run script train_textcat.py

### ISSUE THREAD

**Issue by d5555** [explosion/spaCy#3040]
I'm trying to run this code to train model with text categories  
https://github.com/explosion/spacy/blob/master/examples/training/train_textcat.py
and getting error :

Created blank 'en' model
Loading IMDB data...
Using 2000 examples (1600 training, 400 evaluation)
Training the model...
LOSS      P       R       F
Traceback (most recent call last):
  File "C:\Users\WORK-PC\Desktop\train_textcat.py", line 133, in <module>
    plac.call(main)
  File "E:\.env\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "E:\.env\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\WORK-PC\Desktop\train_textcat.py", line 67, in main
    losses=losses)
  File "E:\.env\lib\site-packages\spacy\language.py", line 439, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "pipeline.pyx", line 1101, in spacy.pipeline.TextCategorizer.update
  File "E:\.env\lib\site-packages\thinc\neural\_classes\feed_forward.py", line 42, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "E:\.env\lib\site-packages\thinc\api.py", line 118, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "E:\.env\lib\site-packages\thinc\api.py", line 118, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "E:\.env\lib\site-packages\thinc\api.py", line 200, in wrap
    output = func(*args, **kwargs)
  File "E:\.env\lib\site-packages\thinc\neural\_classes\feed_forward.py", line 42, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "linear.pyx", line 38, in thinc.linear.linear.LinearModel.begin_update
  File "linear.pyx", line 54, in thinc.linear.linear.LinearModel._begin_cpu_update
ValueError: operands could not be broadcast together with shapes (890,) (890,0,0,0,0,0,0,0)

It didn't work properly with spacy 2.1.0a0 either . I couldn't load pretrained model.

* Operating System: Windows 10
* Python Version Used: 3.6
* spaCy Version Used: v2.1.0a3 nightly
* Environment Information:

**Comment by d5555** [comment]
Any help on how to fix it?

**Comment by ines** [comment]
Just tested it with the current nightly released yesterday, which includes simplifications and improvements of the text categorizer. Just tested the example and it works fine for me, both with a blank language class and the `en_core_web_sm` model.

So try again with the new version and models. If there's still a problem, feel free to repopen!
