### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by swagat-panda** [explosion/spaCy#3108]
nlp=spacy.load("en")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/language.py", line 649, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "pipeline.pyx", line 643, in spacy.pipeline.Tagger.from_disk
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "pipeline.pyx", line 626, in spacy.pipeline.Tagger.from_disk.load_model
  File "pipeline.pyx", line 627, in spacy.pipeline.Tagger.from_disk.load_model
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 335, in from_bytes
    data = msgpack.loads(bytes_data, encoding='utf8')
  File "/home/swagat_panda/.local/lib/python3.5/site-packages/msgpack_numpy.py", line 214, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 187, in msgpack._cmsgpack.unpackb
ValueError: 1792000 exceeds max_bin_len(1048576)

**Comment by AndriyMulyar** [comment]
See #2996
