### ISSUE TITLE
ModuleNotFoundError: No module named 'thinc.neural'

### ISSUE THREAD

**Issue by zaibacu** [explosion/spaCy#3111]
## How to reproduce the behaviour
`python -m spacy download en`

or just 
```
import spacy
```

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/share/anaconda/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/share/anaconda/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/share/anaconda/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "../lambda/.chalice/venv/lib/python3.6/site-packages/spacy/__init__.py", line 8, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
ModuleNotFoundError: No module named 'thinc.neural'
```

## Your Environment
* Operating System: OpenSuse Tumbleweed, Kernel: 4.18.9-1-default
* Python Version Used: Python 3.6.3 :: Anaconda, Inc.
* spaCy Version Used: 2.0.18 (spacy-2.0.18-cp36-cp36m-manylinux1_x86_64.whl)
* Environment Information:

**Comment by zaibacu** [comment]
Reinstalling `thinc` solved issue.
