### ISSUE TITLE
Not able to train new entity using CLI train command

### ISSUE THREAD

**Issue by santhoshsridhar0304** [explosion/spaCy#3127]
The data is as mentioned here:
[https://spacy.io/api/annotation#json-input](url)
`python -m spacy train en ./ train.json train.json -n 100  -T -P -G`

### Output:

dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 1 by default
batch_to = 16 by default
batch_compound = 1.001 by default
max_doc_len = 5000 by default
Traceback (most recent call last):
  File "C:\Users\Ziffity\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ziffity\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ziffity\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\Ziffity\AppData\Local\Programs\Python\Python37\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\Ziffity\AppData\Local\Programs\Python\Python37\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\Ziffity\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\train.py", line 91, in train
    n_train_words = corpus.count_train()
  File "gold.pyx", line 191, in spacy.gold.GoldCorpus.count_train
  File "gold.pyx", line 171, in train_tuples
  File "gold.pyx", line 312, in read_json_file
TypeError: string indices must be integers

Note: I'm using a large dataset. Please suggest me if there is another way to train a new entity through code which would be efficient and fast.

* Operating System: Windows 8.1
* Python Version Used: 3.7.1
* spaCy Version Used: 2.0.18

**Comment by ines** [comment]
> The data is as mentioned here: https://spacy.io/api/annotation#json-input

Are you using the exact data, or your own data formatted in the same style?

The error, which occurs [here](https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L312), indicates that the documents you're reading in from the JSON file are strings and not dictionaries with a key `"paragraphs"`, as expected.

**Comment by santhoshsridhar0304** [comment]
I'm using my own data in the same style.

FYI,
I'm attaching the train.json file
[train.zip](https://github.com/explosion/spaCy/files/2736476/train.zip)

**Comment by santhoshsridhar0304** [comment]
I'm using my own data formatted in the same style.
But i'm able to access the data from the json file:

`with open('train.json', 'r', encoding='utf8') as json_file:
        data = json.load(json_file)
n_sentences = len(data['paragraphs'][0]['sentences'])`

**Comment by santhoshsridhar0304** [comment]
Found the issue:

My training set was missing intitial [] in the json file
{
    "id": int,                     
    "paragraphs": [{         
        "raw": string,          
        "sentences": [{        
            "tokens": [{         
                "id": int,          
                "dep": string,  
                "head": int,     
                "tag": string,   
                "orth": string,  
                "ner": string    
            }]
        }]
    }]
}

Thanks @ines for replying instantly!
