### ISSUE TITLE
Conversion to IOB2 failing

### ISSUE THREAD

**Issue by IzzyHibbert** [explosion/spaCy#3128]
Hi,

following the closure of a previous request (#2970), for the conversion of the format IOB2, I was attempting a conversion with Spacy Version: 2.0.18 and Python 3.
The error message is ValueError: too many values to unpack (expected 2), below a detail.

The test is done with the same IOB2 file content of #2970  
Alex|I-PER
is|O
going|O
to|O
Los|B-LOC
Angeles|I-LOC

Any help is appreciated.

MyMac-iMac:Spacy itsme$ python3 -m spacy convert my_test.iob2 . -c iob
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/cli/convert.py", line 47, in convert
    n_sents=n_sents, use_morphology=morphology)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/cli/converters/iob2json.py", line 16, in iob2json
    sentences = read_iob(file_)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/cli/converters/iob2json.py", line 35, in read_iob
    words, iob = zip(*tokens)
ValueError: too many values to unpack (expected 2)

**Comment by gavrieltal** [comment]
I ran an identical command on an identical input file and had no issue. If you figure out how your IOB file is different than the one given in #2970 please let us know!

**Comment by IzzyHibbert** [comment]
Correct..
unfortunately I missed up the file extension and content.
Ticket closed.
Thanks guys!
