### ISSUE TITLE
Doc.print_tree(flat=True) broken in spacy 2.0.18

### ISSUE THREAD

**Issue by xrmx** [explosion/spaCy#3150]
## How to reproduce the behaviour

```
$ python
Python 3.7.2 (default, Jan  3 2019, 02:55:40) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load('en_core_web_sm')
>>> doc = nlp('Alice ate the pizza')
>>> doc.print_tree(flat=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "doc.pyx", line 983, in spacy.tokens.doc.Doc.print_tree
  File "/venv/lib/python3.7/site-packages/spacy/tokens/printers.py", line 74, in parse_tree
    for sent in doc_clone.sents]
  File "/venv/lib/python3.7/site-packages/spacy/tokens/printers.py", line 74, in <listcomp>
    for sent in doc_clone.sents]
  File "/venv/lib/python3.7/site-packages/spacy/tokens/printers.py", line 41, in POS_tree
    subtree["modifiers"].append(POS_tree(c))
KeyError: 'modifiers'
```

doc.print_tree() is the following:

```
[{'NE': '',
  'POS_coarse': 'VERB',
  'POS_fine': 'VBD',
  'arc': 'ROOT',
  'lemma': 'eat',
  'modifiers': [{'NE': '',
                 'POS_coarse': 'PROPN',
                 'POS_fine': 'NNP',
                 'arc': 'nsubj',
                 'lemma': 'alice',
                 'modifiers': [],
                 'word': 'Alice'},
                {'NE': '',
                 'POS_coarse': 'NOUN',
                 'POS_fine': 'NN',
                 'arc': 'dobj',
                 'lemma': 'pizza',
                 'modifiers': [{'NE': '',
                                'POS_coarse': 'DET',
                                'POS_fine': 'DT',
                                'arc': 'det',
                                'lemma': 'the',
                                'modifiers': [],
                                'word': 'the'}],
                 'word': 'pizza'}],
  'word': 'ate'}]
```

## Your Environment
* **spaCy version:** 2.0.18
* **Platform:** Linux-4.19.0-1-amd64-x86_64-with-debian-buster-sid
* **Python version:** 3.7.2
* **Models:** en_core_web_sm

**Comment by ines** [comment]
Yes, a PR would be nice!

One thing to note re `Doc.print_tree`: At the moment, we've deprecated `Doc.print_tree` for `spacy-nightly`, because `2.1.x` will introduce a new `Doc.to_json()` method that's also used for training and will output data that exactly matches spaCy's new training format (see #2928).

However, `Doc.to_json` won't actually cover everything that `Doc.print_tree` covered, so maybe we do want to bring that one back. I'm not 100% sure if people actually use it much, or whether it makes more sense for users to build their own logic that's more specific to their application.
