### ISSUE TITLE
spaCy issues since numpy upgrade to 1.16.0

### ISSUE THREAD

**Issue by sardinois** [explosion/spaCy#3162]
Since upgrading from numpy 1.15.0 to 1.16.0 I am getting errors with spaCy.
Every spaCy command fails with folllowing error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/databricks/python/lib/python3.5/site-packages/spacy/__init__.py", line 8, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/databricks/python/lib/python3.5/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/databricks/python/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 2, in <module>
    from numpy import prod
  File "/databricks/python/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/databricks/python/lib/python3.5/site-packages/numpy/core/__init__.py", line 57, in <module>
    from . import numerictypes as nt
  File "/databricks/python/lib/python3.5/site-packages/numpy/core/numerictypes.py", line 111, in <module>
    from ._type_aliases import (
  File "/databricks/python/lib/python3.5/site-packages/numpy/core/_type_aliases.py", line 63, in <module>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
  File "/databricks/python/lib/python3.5/site-packages/numpy/core/_type_aliases.py", line 63, in <setcomp>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
AttributeError: 'tuple' object has no attribute 'type'
```

This is running spaCy 2.0.18 on python 3.5 together with numpy 1.1.6.0
when I rollback to numpy 1.15.0 there are no issues.

**Comment by sreeharibs** [comment]
I was also having the same issue. 
The following workaround fixed it.

`pip uninstall numpy`
`pip install numpy`

Thanks
