### ISSUE TITLE
Bug when multi-threading spaCy/examples/deep_learning_keras.py

### ISSUE THREAD

**Issue by demongolem** [explosion/spaCy#3168]
## How to reproduce the behaviour

I have the most unfortunate example of combinations of multiple packages.  I have a Flask app, which uses the deep_learning_keras.py example of spacy which of course uses keras which in turn uses Tensorflow.

So there is a setting in Flask, threaded, which can be set to True of False.  When False, my Flask application reports back a value for sentiment.  When True, I get an error.  So first, here is the line of code I am talking about:
`application.run(port='8086', threaded=True)`

So then the stack trace:

>   Traceback (most recent call last):
  File "Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "MultilevelSentiment\Entry.py", line 66, in get_spacy_sentiment
    return str(compute_spacy_sentiment(text))
  File "MultilevelSentiment\Entry.py", line 70, in compute_spacy_sentiment
    return SpacySentiment.evaluate_without_labels(nlp, text)
  File "MultilevelSentiment\SpacySentiment.py", line 176, in evaluate_without_labels
    for doc in nlp.pipe(texts, batch_size=1000, n_threads=4):
  File "Python36\lib\site-packages\spacy\language.py", line 572, in pipe
    for doc in docs:
  File "MultilevelSentiment\SpacySentiment.py", line 73, in pipe
    ys = self._model.predict(Xs)
  File "Python36\lib\site-packages\keras\engine\training.py", line 1164, in predict
    self._make_predict_function()
  File "Python36\lib\site-packages\keras\engine\training.py", line 554, in _make_predict_function
    **kwargs)
  File "Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2744, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2546, in __init__
    with tf.control_dependencies(self.outputs):
  File "Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 5004, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 4543, in control_dependencies
    c = self.as_graph_element(c)
  File "Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3569, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("dense_2/Sigmoid:0", shape=(?, 1), dtype=float32) is not an element of this graph.
INFO:werkzeug:127.0.0.1 - - [16/Jan/2019 13:14:44] "[1m[35mPOST /spacy HTTP/1.1[0m" 500 -

I actually have 9 different sentiment programs in my Flask application and the other 8 work correctly in Threaded=True mode, it is only this particular code using Spacy (which in turn uses Keras and then Tensorflow) which does this.

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6.1
* spaCy Version Used: 2.0.16
* Environment Information: Again, Flask application which calls this code.  So I make POST requests to a URL and it is supposed to return the requested information, which would be spaCy sentiment analysis in this case

**Comment by honnibal** [comment]
Ultimately Tensorflow is delegating its matrix multiplication calls to a library like numpy, which I think isn't thread safe. After much effort we managed to resolve this problem for v2.1. There's probably a setting in Tensorflow that helps as well. Maybe try:

```
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
```
