### ISSUE TITLE
Saving model Trailing data error

### ISSUE THREAD

**Issue by m0a0k0s** [explosion/spaCy#3184]
ValueError: Trailing data for both spacy and spacy-nightly on first iterration:

dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 1 by default
batch_to = 16 by default
batch_compound = 1.001 by default
max_doc_len = 5000 by default
Load vectors model en_vectors_web_lg
beam_width = 1 by default
beam_density = 0.0 by default
learn_rate = 0.001 by default
optimizer_B1 = 0.9 by default
optimizer_B2 = 0.999 by default
optimizer_eps = 1e-08 by default
L2_penalty = 1e-06 by default
grad_norm_clip = 1.0 by default
parser_hidden_depth = 1 by default
parser_maxout_pieces = 2 by default
token_vector_width = 128 by default
hidden_width = 200 by default
embed_size = 7000 by default
history_feats = 0 by default
history_width = 0 by default
Itn.  Dep Loss  NER Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %  CPU WPS  GPU WPS
Saving model...
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\PythonVirtEnv\email-signature-parser\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\PythonVirtEnv\email-signature-parser\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\PythonVirtEnv\email-signature-parser\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\PythonVirtEnv\email-signature-parser\lib\site-packages\spacy\cli\train.py", line 144, in train
    gold_preproc=gold_preproc))
  File "gold.pyx", line 213, in dev_docs
  File "gold.pyx", line 218, in iter_gold_docs
  File "gold.pyx", line 182, in dev_tuples
  File "gold.pyx", line 304, in read_json_file
  File "gold.pyx", line 305, in spacy.gold.read_json_file
ValueError: Trailing data

**Comment by m0a0k0s** [comment]
Ok, it was a problem in evaluation data file format
