### ISSUE TITLE
Issue in loading spacy.load('en_core_web_lg'). Tried many options, but no use.Please help.

### ISSUE THREAD

**Issue by joshuasirasapalli** [explosion/spaCy#3238]
## KIndly please help, i am getting error while loading spacy.load('en_core_web_lg')

Traceback (most recent call last):
  File "C:\Users\joshua\Desktop\NLP\python programs\nlp1.py", line 4, in <module>
    spacy.load('en_core_web_lg')
  File "C:\Python37\lib\site-packages\spacy\__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "C:\Python37\lib\site-packages\spacy\util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "C:\Python37\lib\site-packages\spacy\util.py", line 135, in load_model_from_package
    return cls.load(**overrides)
  File "C:\Python37\lib\site-packages\en_core_web_lg\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Python37\lib\site-packages\spacy\util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "C:\Python37\lib\site-packages\spacy\util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "C:\Python37\lib\site-packages\spacy\language.py", line 647, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "C:\Python37\lib\site-packages\spacy\util.py", line 511, in from_disk
    reader(path / key)
  File "C:\Python37\lib\site-packages\spacy\language.py", line 635, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 380, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 391, in spacy.vectors.Vectors.from_disk
  File "C:\Python37\lib\site-packages\spacy\util.py", line 511, in from_disk
    reader(path / key)
  File "vectors.pyx", line 384, in spacy.vectors.Vectors.from_disk.load_vectors
  File "C:\Python37\lib\site-packages\numpy\lib\npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "C:\Python37\lib\site-packages\numpy\lib\format.py", line 704, in read_array
    array = numpy.fromfile(fp, dtype=dtype, count=count)
MemoryError

## Your Environment

* Operating System:Windows
* Python Version Used:Python 3.7.2
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by theudas** [comment]
You are using probably 32 bit Python and need to switch to 64 bit.

**Comment by joshuasirasapalli** [comment]
Thank you. There are many versions of 64 bit. please give me the link which i have to install.

**Comment by ines** [comment]
This depends on your platform. In your case, you need the 64bit version for Windows. See here for how to download Python: https://www.python.org/downloads/

See here for the Windows releases: https://www.python.org/downloads/windows/ 3.8.0a1 is an alpha, so you probably want to go for 3.7.2 (the same as your currently have).
