### ISSUE TITLE
Error while downloading model

### ISSUE THREAD

**Issue by rajesh15mhatre** [explosion/spaCy#3271]
## How to reproduce the problem
I have installed successfully spaCy using below command and able to import spacy
```
conda config --add channels conda-forge
conda install spacy
```
But i am facing issues while downloading model. 1st I used below command 

`python -m spacy download en`

```bash
(myclone) C:\Users\user>python -m spacy download en
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\urllib3\contrib\pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\OpenSSL\SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\OpenSSL\SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\urllib3\contrib\pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\spacy\cli\download.py", line 31, in download
    shortcuts = get_json(about.__shortcuts__, "available shortcuts")
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\spacy\cli\download.py", line 54, in get_json
    r = requests.get(url)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user\AppData\Local\conda\conda\envs\myclone\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
```

Then I tried downloading models locally and try to install it using pip but I got another error

`pip install E:\Spacy\spacy-models-en_core_web_sm-2.0.0.zip`

```bash
(myclone) C:\Users\user>pip install E:\Spacy\spacy-models-en_core_web_sm-2.0.0.zip
Processing e:\spacy\spacy-models-en_core_web_sm-2.0.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\user\appdata\local\conda\conda\envs\myclone\lib\tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-1hv2_j43\\setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-req-build-1hv2_j43\
```
Please suggest me how I can bypass this error

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6.4 
* spaCy Version Used: 2.0.13
* Environment Information:

**Comment by rajesh15mhatre** [comment]
I was referring to wrong tar file now I am able to download and install model.

Correct URL : https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz
