### ISSUE TITLE
require_gpu() from spacy nightly build doesn't work when training new NER labels

### ISSUE THREAD

**Issue by peidaqi** [explosion/spaCy#3295]
## 
## 
import spacy
spacy.require_gpu()
nlp = spacy.load('en')
ner = nlp.get_pipe("ner")
ner.add_label('test')

And I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "nn_parser.pyx", line 167, in spacy.syntax.nn_parser.Parser.add_label
  File "_parser_model.pyx", line 219, in spacy.syntax._parser_model.ParserModel.resize_output
  File "cupy/core/core.pyx", line 1689, in cupy.core.core.ndarray.__setitem__
  File "cupy/core/core.pyx", line 3588, in cupy.core.core._scatter_op
  File "cupy/core/core.pyx", line 527, in cupy.core.core.ndarray.fill
ValueError: non-scalar numpy.ndarray cannot be used for fill
non-scalar numpy.ndarray cannot be used for fill

* Operating System: Ubuntu 17.04
* Python Version Used: 3.6
* spaCy Version Used: Spacy-nightly 2.1.0a7
* Environment Information: thinc 7.0.1, thinc-gpu-ops 0.0.4, cupy 5.2.0, cuda 9

**Comment by peidaqi** [comment]
Running some further tests I think the problem is linked to #2161 , where if I use 

> pip install -U spacy[cuda90]

instead of the nightly build, I get the same KeyError: <class 'numpy.object_'> message.

Again, there'd be no problem if I use a blank model. I assume this might have something to do with when a previous model was trained and saved using numpy, cupy cannot load that correctly.

**Comment by honnibal** [comment]
I believe this was the same issue as #3112 , which should now be fixed on develop (and should be released shortly). Thanks for the report.
