### ISSUE TITLE
Could not find suitable distribution for requirement.parse('wheel(0.33.0,)=0.32.0')

### ISSUE THREAD

**Issue by daxaxelrod** [explosion/spaCy#3316]
My distribution of wheel isn't being picked up.
```bash
$ pip --version
pip 19.0.3
```
```bash
$ pip show wheel
Name: wheel
Version: 0.33.1
Summary: A built-package format for Python.
```

Installing spacy in a pipenv environment.
The artifactory that I use is an up to date mirror of pypi's index.

```bash
Collecting spacy
  Downloading https://artifactory.xxxxxxx/artifactory/api/pypi/pypi/packages/67/5e/63283836960c97283ad20ae58ef62767e232fc351564a22a85df598fd794/spacy-2.0.18.tar.gz (24.9MB)
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/wheel/: [Errno 11004] getaddrinfo failed -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/: [Errno 11004] getaddrinfo failed -- Some packages may not be found!
    No local packages or working download links found for wheel<0.33.0,>=0.32.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\da56338\AppData\Local\Temp\pip-install-7twmxesa\spacy\setup.py", line 237, in <module>
        setup_package()
      File "C:\Users\da56338\AppData\Local\Temp\pip-install-7twmxesa\spacy\setup.py", line 232, in setup_package
        'build_ext': build_ext_subclass},
      File "c:\users\da56338\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "c:\users\da56338\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\da56338\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\da56338\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "c:\users\da56338\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "c:\users\da56338\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 1069, in obtain
        return installer(requirement)
      File "c:\users\da56338\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\da56338\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('wheel<0.33.0,>=0.32.0')

```

## Your Environment

* Operating System: windows x86
* Python Version Used: 3.7.0
* spaCy Version Used:  2.0.18
* Environment Information: Fresh pipenv environment. Installed rasa_nlu which told me to install spacy.

## Code References
Line 201 of ~/setup.py
```python
            setup_requires=['wheel>=0.32.0,<0.33.0'],
```

**Comment by daxaxelrod** [comment]
I found the issue. Something so simple. My wheel version was 0.33 which was released a couple of days ago. Was out of the .32<=x<.33 range. I uninstalled wheel and reinstalled .32.0 and it worked
