### ISSUE TITLE
Unable to convert Fasttext Danish to spacy

### ISSUE THREAD

**Issue by sojohan** [explosion/spaCy#3321]
Hi 

I am trying to do the following

```
python -m spacy init-model en /Wordvec --vectors-loc cc.da.300.vec.gz
```

I get the following error message:

```
Sucessfully compiled vocab
    1999286 entries, 2000000 vectors

Traceback (most recent call last):
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\spacy\cli\init_model.py", line 54, in init_model
    nlp.to_disk(output_dir)
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\spacy\language.py", line 615, in to_disk
    util.to_disk(path, serializers, {p: False for p in disable})
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\spacy\util.py", line 503, in to_disk
    writer(path / key)
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\spacy\language.py", line 614, in <lambda>
    serializers['vocab'] = lambda p: self.vocab.to_disk(p)
  File "vocab.pyx", line 365, in spacy.vocab.Vocab.to_disk
  File "vectors.pyx", line 358, in spacy.vectors.Vectors.to_disk
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\spacy\util.py", line 503, in to_disk
    writer(path / key)
  File "vectors.pyx", line 355, in spacy.vectors.Vectors.to_disk.lambda3
  File "vectors.pyx", line 350, in spacy.vectors.Vectors.to_disk.lambda1
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\numpy\lib\npyio.py", line 521, in save
    pickle_kwargs=pickle_kwargs)
  File "C:\Users\sojohans\AppData\Local\Continuum\miniconda3\pythonsdk\envs\text\lib\site-packages\numpy\lib\format.py", line 604, in write_array
    array.tofile(fp)
OSError: 600000000 requested and 0 written
```

## Your Environment

* Operating System: Windows
* Python Version Used: 3.6
* spaCy Version Used: spacy 2.0
* Environment Information:

**Comment by ines** [comment]
Do you have enough free space on your drive? I looked around for reports of similar errors in numpy and found [this thread](https://stackoverflow.com/questions/37657939/oserror-269892000-requested-and-269188084-written) and the following comment:

> This issue arises when you are reading in data using variations of numpy.load but you don't have enough space in your drive.

**Comment by sojohan** [comment]
Hi Ines Yes that worked. spun a vm in Azure and did it.
