### ISSUE TITLE
Failing to load the blank Ukrainian model

### ISSUE THREAD

**Issue by BLKSerene** [explosion/spaCy#3343]
Hi, when trying to initialize the Ukrainian blank model, the following error is raised.
`spacy-nightly` is installed via `pip install spacy-nightly`, while I know how to fix this, I'm wondering is this a packaging issue?
```
import spacy
>>> spacy.blank('uk')

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    spacy.blank('uk')
  File "D:\Python\lib\site-packages\spacy\__init__.py", line 26, in blank
    LangClass = util.get_lang_class(name)
  File "D:\Python\lib\site-packages\spacy\util.py", line 55, in get_lang_class
    module = importlib.import_module(".lang.%s" % lang, "spacy")
  File "D:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Python\lib\site-packages\spacy\lang\uk\__init__.py", line 13, in <module>
    from .lemmatizer import UkrainianLemmatizer
  File "D:\Python\lib\site-packages\spacy\lang\uk\lemmatizer.py", line 18
    "The Ukrainian lemmatizer requires the pymorphy2 library and
                                                               ^
SyntaxError: EOL while scanning string literal
```

* Operating System: Windows 10 64-bit
* Python Version Used: 3.7.2 64-bit
* spaCy Version Used: 2.1.0a9

**Comment by ines** [comment]
Ugh, looks like this was a merge error that happened when syncing `master` with `develop` 😞 (And it's not caught by our default CI, because we can't easily test the languages with external dependencies, at least not on each build.) Fixing!
