### ISSUE TITLE
python -m spacy download en failing every time with read timeout

### ISSUE THREAD

**Issue by shshankar1** [explosion/spaCy#3377]
I am trying to download spacy en_core_web_sm-2.0.0 model but every time it fails with read timeout.
 
## How to reproduce the problem
E:\python_projects\venv\Scripts>python -m spacy download en_core_web_sm-2.0.0 --direct
Collecting en_core_web_sm-2.0.0 from https://github.com/explosion/spacy-models/r
eleases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_we
b_sm-2.0.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_cor
e_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz (37.4MB)
    2% |█                               | 798kB 7.6kB/s eta 1:20:40Exception:
Traceback (most recent call last):
  File "E:\python_projects\venv\lib\site-packages\pip\_vendor\urllib3\response.p
y", line 360, in _error_catcher
    yield
  File "E:\python_projects\venv\lib\site-packages\pip\_vendor\urllib3\response.p
y", line 442, in read
    data = self._fp.read(amt)
  File "C:\Users\shashi\Anaconda3\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Users\shashi\Anaconda3\lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\shashi\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\shashi\Anaconda3\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\shashi\Anaconda3\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\shashi\Anaconda3\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\cli\base_command
.py", line 179, in main
    status = self.run(options, args)
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\commands\install
.py", line 315, in run
    resolver.resolve(requirement_set)
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\resolve.py", lin
e 131, in resolve
    self._resolve_one(requirement_set, req)
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\resolve.py", lin
e 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\resolve.py", lin
e 242, in _get_abstract_dist_for
    self.require_hashes
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\operations\prepa
re.py", line 334, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\download.py", li
ne 878, in unpack_url
    progress_bar=progress_bar
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\download.py", li
ne 702, in unpack_http_url
    progress_bar)
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\download.py", li
ne 946, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\download.py", li
ne 641, in _download_url
    consume(downloaded_chunks)
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\utils\misc.py",
line 914, in consume
    deque(iterator, maxlen=0)
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\download.py", li
ne 607, in written_chunks
    for chunk in chunks:
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\utils\ui.py", li
ne 159, in iter
    for x in it:
  File "E:\python_projects\venv\lib\site-packages\pip\_internal\download.py", li
ne 596, in resp_read
    decode_content=False):
  File "E:\python_projects\venv\lib\site-packages\pip\_vendor\urllib3\response.p
y", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "E:\python_projects\venv\lib\site-packages\pip\_vendor\urllib3\response.p
y", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\shashi\Anaconda3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\python_projects\venv\lib\site-packages\pip\_vendor\urllib3\response.p
y", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='githu
b-production-release-asset-2e65be.s3.amazonaws.com', port=443): Read timed out.
## Your Environment

* Operating System: Windows 7
* Python Version Used: 3.4.4
* spaCy Version Used: 2.0.0
* Environment Information:

**Comment by honnibal** [comment]
I'm fairly sure you'll find this is either a transient connection issue, or some sort of local firewall.

If problems persist, you can also download the models directly from https://github.com/explosion/spacy-models/releases
