### ISSUE TITLE
spacy.load('en') fails with "sre_constants.error: bad character range"

### ISSUE THREAD

**Issue by cdg720** [explosion/spaCy#3424]
## How to reproduce the behaviour

import spacy
from spacy_readability import Readability
nlp = spacy.load('en')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/spacy/__init__.py", line 22, in load
    return util.load_model(name, **overrides)
  File "/Library/Python/2.7/site-packages/spacy/util.py", line 129, in load_model
    return load_model_from_link(name, **overrides)
  File "/Library/Python/2.7/site-packages/spacy/util.py", line 146, in load_model_from_link
    return cls.load(**overrides)
  File "/Library/Python/2.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/Library/Python/2.7/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/Library/Python/2.7/site-packages/spacy/util.py", line 161, in load_model_from_path
    nlp = cls(meta=meta, **overrides)
  File "/Library/Python/2.7/site-packages/spacy/language.py", line 163, in __init__
    make_doc = factory(self, **meta.get("tokenizer", {}))
  File "/Library/Python/2.7/site-packages/spacy/language.py", line 64, in create_tokenizer
    util.compile_prefix_regex(cls.prefixes).search if cls.prefixes else None
  File "/Library/Python/2.7/site-packages/spacy/util.py", line 343, in compile_prefix_regex
    return re.compile(expression)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range

## Your Environment

* Operating System: macOS (10.14.3)
* Python Version Used: 2.7
* spaCy Version Used: v2.1.0
* Environment Information:

python -m spacy validate
✔ Loaded compatibility table

====================== Installed models (spaCy v2.1.0) ======================
ℹ spaCy installation: /Library/Python/2.7/site-packages/spacy

TYPE      NAME             MODEL            VERSION                            
package   en-core-web-sm   en_core_web_sm   2.1.0   ✔
link      en               en_core_web_sm   2.1.0   ✔

**Comment by ines** [comment]
See #3424 for details – pretty sure this should be fixed by using a wide unicode build!

**Comment by woctezuma** [comment]
What is a wide unicode build?
