### ISSUE TITLE
Error installing spacy in miniconda docker

### ISSUE THREAD

**Issue by rulai-huajunzeng** [explosion/spaCy#3436]
## How to reproduce the behavior
1. Create the following Dockerfile
```
FROM continuumio/miniconda:4.5.12

RUN apt-get update && apt-get -y install build-essential python-dev
RUN pip install spacy
RUN spacy download en_core_web_sm
```
2. Run `docker build -t my_image .`
3. Got the following error:
```sh
...
Step 4/4 : RUN spacy download en_core_web_sm
 ---> Running in 5f5fefddf3d4
Collecting en_core_web_sm==2.1.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm==2.1.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz (11.1MB)
Installing collected packages: en-core-web-sm
  Running setup.py install for en-core-web-sm: started
    Running setup.py install for en-core-web-sm: finished with status 'done'
Successfully installed en-core-web-sm-2.1.0
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/conda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/conda/lib/python2.7/site-packages/spacy/__main__.py", line 38, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/opt/conda/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/opt/conda/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/spacy/cli/download.py", line 46, in download
    "You can now load the model via spacy.load('{}')".format(model_name),
  File "/opt/conda/lib/python2.7/site-packages/wasabi/printer.py", line 73, in good
    return self._get_msg(title, text, style=MESSAGES.GOOD, show=show, exits=exits)
  File "/opt/conda/lib/python2.7/site-packages/wasabi/printer.py", line 214, in _get_msg
    return self.text(title, text, color=style, icon=style, show=show, exits=exits)
  File "/opt/conda/lib/python2.7/site-packages/wasabi/printer.py", line 123, in text
    print(title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 9: ordinal not in range(128)
The command '/bin/sh -c spacy download en_core_web_sm' returned a non-zero code: 1
```

## Your Environment

* Operating System: Linux
* Python Version Used: Miniconda 4.5.12 python 2.7
* spaCy Version Used: 2.1.0

**Comment by ines** [comment]
See [my comment here](https://github.com/explosion/spaCy/issues/3432#issuecomment-474587352) for a workaround – merging this with #3432.
