### ISSUE TITLE
`spacy pretrain` errors when trying to pretrain on a small dataset

### ISSUE THREAD

**Issue by tokestermw** [explosion/spaCy#3469]
## How to reproduce the behaviour

```
spacy pretrain ./dummy.jsonl en_core_web_sm here -bs 10
```

Let's say I have this file called `dummy.jsonl`

```
{"text": "Can I ask where you work now and what you do, and if you enjoy it?"}
{"text": "They may just pull out of the Seattle market completely, at least until they have autonomous vehicles."}
{"text": "My cynical view on this is that it will never be free to the public. Reason: what would be the draw of joining the military? Right now their selling point is free Healthcare and Education. Ironically both are run horribly and most, that I've talked to, come out wishing they never went in."}
```

I get the following error.

```
  File ".../venv/lib/python3.6/site-packages/thinc/neural/_classes/affine.py", line 67, in finish_update
    self.ops.gemm(grad__BO, input__BI, trans1=True, out=self.d_W)
  File "ops.pyx", line 404, in thinc.neural.ops.NumpyOps.gemm
ValueError: Buffer and memoryview are not contiguous in the same dimension.
```

When `dummy.jsonl` looks like this:

```
{"text": "Hello there"}
```

I get this error

```
  File ".../venv/lib/python3.6/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File ".../venv/lib/python3.6/site-packages/thinc/api.py", line 340, in uniqued_fwd
    keys = X[:, column]
IndexError: too many indices for array
```

## Your Environment
`spacy==2.1.1`
`thinc==7.0.4`
`thinc==0.0.4`

**Comment by honnibal** [comment]
Thanks. I haven't looked into this but I think there's a bug in the `spacy.util.minibatch` function. I think it doesn't handle the tail of the sequence properly? We had errors in Prodigy where it was raising an uncaught `StopIteration`, so I think something's wrong there. Might not be the problem here, but I think it'd make sense as an explanation.

**Comment by tokestermw** [comment]
I've tried changing the batch size, changing the size of the data, deduping the data with no luck 😅 

```
git checkout v2.1.0
python setup.py build_ext --inplace
```

I'd love to debug but cythonizing seems to be error-ing out.

```
Processing matcher.pyx
[Errno 2] No such file or directory: '/Users/mwu/github/spaCy/spacy/matcher.pyx'
Traceback (most recent call last):
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 169, in <module>
    run(args.root)
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 158, in run
    process(base, filename, db)
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 124, in process
    preserve_cwd(base, process_pyx, root + ".pyx", root + ".cpp")
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 87, in preserve_cwd
    func(*args)
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 63, in process_pyx
    raise Exception("Cython failed")
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 275, in <module>
    setup_package()
  File "setup.py", line 208, in setup_package
    generate_cython(root, "spacy")
  File "setup.py", line 131, in generate_cython
    raise RuntimeError("Running cythonize failed")
RuntimeError: Running cythonize failed
```

**Comment by tokestermw** [comment]
Oh I just have to set `-nw 1` (or something small) 😅

https://github.com/explosion/spaCy/issues/3442

**Comment by gustavengstrom** [comment]
I don't understand why this issue is closed? Adding the command -nw 1 just changes one error message for another. I am still can't get rid of the first error message:

  File ".../venv/lib/python3.6/site-packages/thinc/neural/_classes/affine.py", line 67, in finish_update
    self.ops.gemm(grad__BO, input__BI, trans1=True, out=self.d_W)
  File "ops.pyx", line 404, in thinc.neural.ops.NumpyOps.gemm
ValueError: Buffer and memoryview are not contiguous in the same dimension.

@tokestermw  how did you fix this?

**Comment by gustavengstrom** [comment]
For anybody else that comes across the same error as me. I realised after some testing that the error message came from accidentally trying to pretrain on the "en_core_web_sm" model which fails since since this model does not contain any word vectors...
