### ISSUE TITLE
TextCategorizer: TypeError: Only cupy arrays can be concatenated (Training on GPU)

### ISSUE THREAD

**Issue by Tpt** [explosion/spaCy#3473]
## How to reproduce the behaviour

Sorry for bothering you again with the nearly same problem. After upgrading to Spacy 2.1.3, if I try to train a text categorizer with CUDA enabled, I get back the error `TypeError: Only cupy arrays can be concatenated `. It seems to be the same problem as #3355

I purged my venv and made a `pip install --upgrade 'spacy[cuda100]'`, so it's probably not because an old library version is kept in my environment.

Backtrace:

```
Traceback (most recent call last):
...
    nlp.update(texts, annotations, sgd=optimizer, drop=0.5, losses=losses)
  File "venv/lib/python3.7/site-packages/spacy/language.py", line 452, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "pipes.pyx", line 931, in spacy.pipeline.pipes.TextCategorizer.update
  File "venv/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "venv/lib/python3.7/site-packages/thinc/api.py", line 132, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "venv/lib/python3.7/site-packages/thinc/api.py", line 132, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "venv/lib/python3.7/site-packages/thinc/api.py", line 225, in wrap
    output = func(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "venv/lib/python3.7/site-packages/spacy/_ml.py", line 138, in begin_update
    keys = self.ops.xp.concatenate(ngrams)
  File "venv/lib/python3.7/site-packages/cupy/manipulation/join.py", line 49, in concatenate
    return core.concatenate_method(tup, axis)
  File "cupy/core/_routines_manipulation.pyx", line 561, in cupy.core._routines_manipulation.concatenate_method
  File "cupy/core/_routines_manipulation.pyx", line 574, in cupy.core._routines_manipulation.concatenate_method
TypeError: Only cupy arrays can be concatenated
```

## Your Environment

* spaCy version    2.1.3                     
* Platform         Linux-5.0.3-arch1-1-ARCH-x86_64-with-arch
* Python version   3.7.2

**Comment by honnibal** [comment]
Argh. Thanks for the report. We still don't have a CI server running the GPU paths, so it's really hard to prevent this reliably. For now you could edit your `spacy/_ml.py` file to make the following patch:

```
613 def build_bow_text_classifier(nr_class, ngram_size=1, exclusive_classes=False,
614         no_output_layer=False, **cfg):
615     with Model.define_operators({">>": chain}):
616         model = (
617             with_cpu(Model.ops,
618                 extract_ngrams(ngram_size, attr=ORTH)
619                 >> LinearModel(nr_class)
620             )
621         )
622         if not no_output_layer:
623             model = model >> (cpu_softmax if exclusive_classes else logistic)
624     model.nO = nr_class
625     return model
626
```

Thanks for your help reporting.

**Comment by Tpt** [comment]
Thank you for maintaining this amazing library and for the hot fix!
