### ISSUE TITLE
OOM while loading text with nlp(text)

### ISSUE THREAD

**Issue by eawer** [explosion/spaCy#3503]
I'm trying to load a relatively small text (~130kb), using spacy in GPU mode, and for some reason I'm seeing OOM (for sm, md and lg allocation numbers are different). 
Here https://github.com/cupy/cupy/issues/2098 I was pointed to the possible cause: https://github.com/explosion/spaCy/blob/40d33261d62fb5faabd7288843e46f935fad14b4/spacy/_ml.py#L149 
I believe 130kb is way to small to cause OOM, so can you please tell if it's a bug or am I doing something wrong?

## How to reproduce the behaviour
```python
import spacy
from bs4 import BeautifulSoup
import urllib.request as request

spacy.prefer_gpu()
nlp = spacy.load("en_core_web_lg")

def test(url):
    html = request.urlopen(url).read()
    soup = BeautifulSoup(html, 'html.parser')
    text = soup.find(class_='mw-parser-output').get_text()
    doc = nlp(text)

if __name__ == '__main__':
    test('https://en.wikipedia.org/wiki/New_Zealand')
```

```
Traceback (most recent call last):
  File "processData.py", line 36, in <module>
    test('https://en.wikipedia.org/wiki/New_Zealand')
  File "processData.py", line 29, in test
    doc = nlp(text)
  File "anaconda3/envs/py37/lib/python3.7/site-packages/spacy/language.py", line 346, in __call__
    doc = proc(doc)
  File "nn_parser.pyx", line 338, in spacy.syntax.nn_parser.Parser.__call__
  File "nn_parser.pyx", line 401, in spacy.syntax.nn_parser.Parser.parse_batch
  File "nn_parser.pyx", line 729, in spacy.syntax.nn_parser.Parser.get_batch_model
  File "anaconda3/envs/py37/lib/python3.7/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "anaconda3/envs/py37/lib/python3.7/site-packages/thinc/api.py", line 280, in begin_update
    drop=drop)
  File "anaconda3/envs/py37/lib/python3.7/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "anaconda3/envs/py37/lib/python3.7/site-packages/thinc/neural/_classes/resnet.py", line 18, in begin_update
    y, bp_y = self._layers[0].begin_update(X, drop=drop)
  File "anaconda3/envs/py37/lib/python3.7/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "anaconda3/envs/py37/lib/python3.7/site-packages/thinc/neural/_classes/convolution.py", line 28, in begin_update
    X__bo = self.ops.seq2col(X__bi, self.nW)
  File "ops.pyx", line 781, in thinc.neural.ops.CupyOps.seq2col
  File "ops.pyx", line 162, in thinc.neural.ops.Ops.allocate
  File "anaconda3/envs/py37/lib/python3.7/site-packages/cupy/creation/basic.py", line 147, in zeros
    a = cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 151, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1065, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1086, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 900, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 921, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 695, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 41284608 bytes (total 1179552256 bytes)
```

## Your Environment
* **spaCy version:** 2.0.18
* **Platform:** Linux-4.4.0-142-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.7.1
* **Models:** en_core_web_lg, en_core_web_md, en_core_web_sm
* CuPy Version          : 5.3.0
* CUDA Root             : /usr/local/cuda
* CUDA Build Version    : 10000
* CUDA Driver Version   : 10010
* CUDA Runtime Version  : 10000
* cuDNN Build Version   : 7402
* cuDNN Version         : 7402
* NCCL Build Version    : 2307
* NCCL Runtime Version  : 2307
* GeForce 1060 3Gb

**Comment by honnibal** [comment]
Unfortunately a single 130kb text could be causing OOM on your card. The vectors are already take 1gb, and the intermediate representations can get pretty big. For instance, a single convolutional layer has to build a matrix of shape `(n, 3, 3, 96)` where `n` is the number of words in the batch. There are several of these layers, and then the parser's hidden layer ends up large as well.

There are lots of places in the forward pass I think I can save memory if the backward pass isn't being run. But currently it can take a surprising amount of temporary memory during parsing. This is especially true on GPU, as the cupy library has its own allocator.
