### ISSUE TITLE
Unable to load spacy

### ISSUE THREAD

**Issue by AshishDhadwal** [explosion/spaCy#3504]
## How to reproduce the behaviour
pip install -U spacy 

## Your Environment
import spacy
Traceback (most recent call last):

  File "<ipython-input-1-76a01d9c502b>", line 1, in <module>
    import spacy

  File "D:\Movie_Review_Sentiment_Analysis\Textrics V1.0.0.6\spacy\__init__.py", line 10, in <module>
    from .cli.info import info as cli_info

  File "D:\Movie_Review_Sentiment_Analysis\Textrics V1.0.0.6\spacy\cli\__init__.py", line 1, in <module>
    from .download import download

  File "D:\Movie_Review_Sentiment_Analysis\Textrics V1.0.0.6\spacy\cli\download.py", line 11, in <module>
    from .link import link

  File "D:\Movie_Review_Sentiment_Analysis\Textrics V1.0.0.6\spacy\cli\link.py", line 9, in <module>
    from ..util import prints

  File "D:\Movie_Review_Sentiment_Analysis\Textrics V1.0.0.6\spacy\util.py", line 27, in <module>
    from thinc.neural._classes.model import msgpack

ImportError: cannot import name 'msgpack'
* Operating System:Windows 10 64 bit
* Python Version Used:3.6
* spaCy Version Used:v2.1.3
* Environment Information:Spyder

**Comment by ines** [comment]
It looks like your environment didn't get updated correctly and you still have an old version of `thinc`. Or the `spacy` on your Python path you're loading here (located in `Textrics V1.0.0.6\spacy`) isn't actually the same `spacy` you installed via pip, but an old version.

**Comment by AshishDhadwal** [comment]
yes it is resolved now by copying the new spacy version .

**Comment by AshishDhadwal** [comment]
yes it is resolved now by copying the new spacy version .
