### ISSUE TITLE
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('wheel<0.33.0,>=0.32.0')

### ISSUE THREAD

**Issue by kamal2222ahmed** [explosion/spaCy#3600]
## How to reproduce the problem

```bash
11:41 $ sudo pip install spacy
Password:
The directory '/Users/syedahmed/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/syedahmed/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting spacy
  Downloading https://files.pythonhosted.org/packages/77/f3/eb5aece989ecca541c4b5a439cb8a86fe5254b1521925b547609fb3aaf64/spacy-2.1.3.tar.gz (27.7MB)
    100% |████████████████████████████████| 27.7MB 1.7MB/s
  Installing build dependencies ... error
  Complete output from command /Users/syedahmed/anaconda3/bin/python /Users/syedahmed/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-wbsm_fxp/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel>0.32.0.<0.33.0 Cython cymem>=2.0.2,<2.1.0 preshed>=2.0.1,<2.1.0 murmurhash>=0.28.0,<1.1.0 thinc==7.0.0.dev6:
  The directory '/Users/syedahmed/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  The directory '/Users/syedahmed/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  Collecting setuptools
    Downloading https://files.pythonhosted.org/packages/c8/b0/cc6b7ba28d5fb790cf0d5946df849233e32b8872b6baca10c9e002ff5b41/setuptools-41.0.0-py2.py3-none-any.whl (575kB)
  Collecting wheel>0.32.0.<0.33.0
    Downloading https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl
  Collecting Cython
    Downloading https://files.pythonhosted.org/packages/86/b2/2b21477eefec3fc96325ddc1424b844aa948129441991bc400d8bce0432b/Cython-0.29.7-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.9MB)
  Collecting cymem<2.1.0,>=2.0.2
    Downloading https://files.pythonhosted.org/packages/d7/11/37da628920bf2999bd8c4ffc40908413622486d5dbc4e60d87a58c428367/cymem-2.0.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (52kB)
  Collecting preshed<2.1.0,>=2.0.1
    Downloading https://files.pythonhosted.org/packages/48/fe/2f2e8c91541785f2abe0d51f37eb00356513b9ff3d24fb27fd5b59e18264/preshed-2.0.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (145kB)
  Collecting murmurhash<1.1.0,>=0.28.0
    Downloading https://files.pythonhosted.org/packages/b9/bd/faace403086ee922afc74e5615cb8c21020fcf5d5667314e943c08f71fde/murmurhash-1.0.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
  Collecting thinc==7.0.0.dev6
    Downloading https://files.pythonhosted.org/packages/2a/3a/2641736ef8c5f380bfc432dd0d3706c44083eb4f6d6d9f37f9640731d4c4/thinc-7.0.0.dev6-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.8MB)
  Collecting blis<0.3.0,>=0.2.1 (from thinc==7.0.0.dev6)
    Downloading https://files.pythonhosted.org/packages/36/41/9e934e2b8a2cdae447ed1923a94f98c2d70c898b65af6635f5fe55f7ed4d/blis-0.2.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.0MB)
  Collecting srsly<1.1.0,>=0.0.5 (from thinc==7.0.0.dev6)
    Downloading https://files.pythonhosted.org/packages/c8/b2/d2cc9f5aa5a458aca45d8689279b41d4b42ba4e8c63b0cb6a9f009340fd0/srsly-0.0.5-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (270kB)
  Collecting numpy>=1.7.0 (from thinc==7.0.0.dev6)
    Downloading https://files.pythonhosted.org/packages/a6/6f/cb20ccd8f0f8581e0e090775c0e3c3e335b037818416e6fa945d924397d2/numpy-1.16.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
  Collecting plac<1.0.0,>=0.9.6 (from thinc==7.0.0.dev6)
    Downloading https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl
  Collecting tqdm<5.0.0,>=4.10.0 (from thinc==7.0.0.dev6)
    Downloading https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl (48kB)
  Collecting wasabi<1.1.0,>=0.0.9 (from thinc==7.0.0.dev6)
    Downloading https://files.pythonhosted.org/packages/76/6c/0376977df1ba9f0ec27835d80456d9284c79737cb5205649451db1181f01/wasabi-0.2.1-py3-none-any.whl
  Collecting thinc-gpu-ops<0.1.0,>=0.0.1 (from thinc==7.0.0.dev6)
    Downloading https://files.pythonhosted.org/packages/a4/ad/11ab80a24bcedd7dd0cfabaedba2ceaeca11f1aaeeff432a3d2e63ca7d02/thinc_gpu_ops-0.0.4.tar.gz (483kB)
      Complete output from command python setup.py egg_info:
      Download error on https://pypi.org/simple/wheel/: unknown error (_ssl.c:3946) -- Some packages may not be found!
      Download error on https://pypi.org/simple/: unknown error (_ssl.c:3946) -- Some packages may not be found!
      No local packages or working download links found for wheel<0.33.0,>=0.32.0
      Warning: The nvcc binary could not be located in your $PATH. For GPU capability, either add it to your path, or set $CUDA_HOME
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/tmp/pip-install-axi4zhqg/thinc-gpu-ops/setup.py", line 260, in <module>
          setup_package()
        File "/private/tmp/pip-install-axi4zhqg/thinc-gpu-ops/setup.py", line 257, in setup_package
          'build_ext': build_ext_subclass},
        File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in setup
          _install_setup_requires(attrs)
        File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 134, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
          replace_conflicting=True,
        File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
          replace_conflicting=replace_conflicting
        File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1060, in best_match
          return self.obtain(req, installer)
        File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1072, in obtain
          return installer(requirement)
        File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
          return cmd.easy_install(req)
        File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 670, in easy_install
          raise DistutilsError(msg)
      distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('wheel<0.33.0,>=0.32.0')

      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-axi4zhqg/thinc-gpu-ops/

  ----------------------------------------
Command "/Users/syedahmed/anaconda3/bin/python /Users/syedahmed/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-wbsm_fxp/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel>0.32.0.<0.33.0 Cython cymem>=2.0.2,<2.1.0 preshed>=2.0.1,<2.1.0 murmurhash>=0.28.0,<1.1.0 thinc==7.0.0.dev6" failed with error code 1 in None
(base) ✘-1 ~/BG-REPOS/RULES/bg [master|✔]
```

## Your Environment

* Operating System: OSX 10.14.2
* Python Version Used: Python 3.7.0
* spaCy Version Used: spacy-2.1.3.tar.gz
* Environment Information:

**Comment by kamal2222ahmed** [comment]
```$pip install wheel
Requirement already satisfied: wheel in /Users/syedahmed/anaconda3/lib/python3.7/site-packages (0.31.1)```

```$ pip install wheel 0.32.0
Requirement already satisfied: wheel in /Users/syedahmed/anaconda3/lib/python3.7/site-packages (0.31.1)
Collecting 0.32.0
  Could not find a version that satisfies the requirement 0.32.0 (from versions: )
No matching distribution found for 0.32.0```

```$ pip install wheel 0.33.0
Requirement already satisfied: wheel in /Users/syedahmed/anaconda3/lib/python3.7/site-packages (0.31.1)
Collecting 0.33.0
  Could not find a version that satisfies the requirement 0.33.0 (from versions: )
No matching distribution found for 0.33.0```

**Comment by htebmal** [comment]
Looks like the user doesn't have write access to /Users/syedahmed/Library/Caches/pip/ - either use a venv or check that root can access the folder? You might want to consider installing as non-root (i.e. syedahmed).

Separately, "$ pip install wheel 0.33.0" should be "pip install wheel>=0.33.0".
