### ISSUE TITLE
displacy visualizer error

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#3638]
I tried to generate a visualization of dependency parser output, but I received an error.  My code is run in a jupyter-notebook

spacy version = 2.0.18

```
import os
path = os.path.abspath("D:\SOURCECODE\PYTHON\models\parser");
path

import spacy
from spacy import displacy
​
nlp_preTrain = spacy.load("en_core_web_lg")
doc_preTrain = nlp_preTrain(u"Autonomous cars shift insurance liability toward manufacturers")
    
displacy.serve(doc_preTrain, style="dep")    


    Serving on port 5000...
    Using the 'dep' visualizer


127.0.0.1 - - [25/Apr/2019 17:02:40] "GET / HTTP/1.1" 200 5402
Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 258, in send_preamble
    self._write(('Server: %s\r\n' % self.server_software).encode('iso-8859-1'))
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "D:\Anaconda\envs\spacy\lib\socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
127.0.0.1 - - [25/Apr/2019 17:02:40] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50648)
Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 258, in send_preamble
    self._write(('Server: %s\r\n' % self.server_software).encode('iso-8859-1'))
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "D:\Anaconda\envs\spacy\lib\socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy\lib\socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "D:\Anaconda\envs\spacy\lib\socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "D:\Anaconda\envs\spacy\lib\socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Anaconda\envs\spacy\lib\socketserver.py", line 724, in __init__
    self.handle()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "D:\Anaconda\envs\spacy\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "D:\Anaconda\envs\spacy\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'


```

**Comment by ines** [comment]
Are youu sure you want to start a web server *within* a Jupyter notebook, which is already served on a web server?

If you only want to show the visualization, you can use `displacy.render` instead and set `jupyter=True`. If you upgrade to spaCy v2.1, the Jupyter environment should be detected automatically again, and you'll also see a warning when you run `displacy.serve` from within a notebook.
