### ISSUE TITLE
Training new model with "Inception" based JSON data- throws  File "gold.pyx", line 177, in train_tuples ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by ParthBarot-BoTreeConsulting** [explosion/spaCy#3645]
## How to reproduce the behaviour
1. I am using [Inception](https://inception-project.github.io) to create annotations, exporting it with "conll corenlp" format.
2. After successfully changing the exported files as required by `convert` cli, able to convert them to `jsonl` format.
3. Then again I have to put whole content inside `[...]` to be a valid JSON. It looks like below. Each `paragraph` does not have the `"raw": string` key. 
```
[
  {
    "id": 0,
    "paragraphs": [
      {
        "sentences": [
          {
            "tokens": [
              {
                "id": 0,
                "orth": "FRESH",
                "tag": "O",
                "head": 0,
                "dep": "_",
                "ner": "O"
              },
             ...
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 3,
    "paragraphs": [
      {
        "sentences": [
          {
            "tokens": [
              {
                "id": 0,
                "orth": ".",
                "tag": "O",
                "head": 0,
                "dep": "_",
                "ner": "O"
              }
            ]
          }
        ]
      }
    ]
  }
]
``` 
4. When I am trying to execute `python -m spacy train en ./output ./train/ar13.1.jsonl ./dev/ar10.1.jsonl -T -G -VV`, it shows the following log,
```
> python -m spacy train en ./output ./train/ar13.1.jsonl ./dev/ar10.1.jsonl -T -G -VV 

dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 100.0 by default
batch_to = 1000.0 by default
batch_compound = 1.001 by default
Training pipeline: ['tagger', 'parser', 'ner']
Starting with blank model 'en'
beam_width = 1 by default
beam_density = 0.0 by default
beam_update_prob = 1.0 by default
beam_width = 1 by default
beam_density = 0.0 by default
beam_update_prob = 1.0 by default
Counting training words (limit=0)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/testuser/.env/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/testuser/.env/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/testuser/.env/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/testuser/.env/lib/python3.6/site-packages/spacy/cli/train.py", line 197, in train
    n_train_words = corpus.count_train()
  File "gold.pyx", line 177, in train_tuples
ValueError: too many values to unpack (expected 2)

```

## Your Environment
* **spaCy version:** 2.1.3
* **Platform:** Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.7

**Comment by ParthBarot-BoTreeConsulting** [comment]
Just to add,

When I am using compressed JSON it throws the error logged in description but when I am using prettyfied JSON, it throws,
```
$ python -m spacy train en ./output ./train/ar13.1.jsonl ./dev/ar10.1.jsonl -T -G -VV 
dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 100.0 by default
batch_to = 1000.0 by default
batch_compound = 1.001 by default
Training pipeline: ['tagger', 'parser', 'ner']
Starting with blank model 'en'
beam_width = 1 by default
beam_density = 0.0 by default
beam_update_prob = 1.0 by default
beam_width = 1 by default
beam_density = 0.0 by default
beam_update_prob = 1.0 by default
Counting training words (limit=0)
Traceback (most recent call last):
  File "/home/testuser/.env/lib/python3.6/site-packages/srsly/_json_api.py", line 128, in _yield_json_lines
    yield ujson.loads(line)
ValueError: Expected object or value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/testuser/.env/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/testuser/.env/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/testuser/.env/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/testuser/.env/lib/python3.6/site-packages/spacy/cli/train.py", line 196, in train
    corpus = GoldCorpus(train_path, dev_path, limit=n_examples)
  File "gold.pyx", line 112, in spacy.gold.GoldCorpus.__init__
  File "gold.pyx", line 123, in spacy.gold.GoldCorpus.write_msgpack
  File "gold.pyx", line 163, in read_tuples
  File "/home/testuser/.env/lib/python3.6/site-packages/srsly/_json_api.py", line 85, in read_jsonl
    for line in _yield_json_lines(f, skip=skip):
  File "/home/testuser/.env/lib/python3.6/site-packages/srsly/_json_api.py", line 132, in _yield_json_lines
    raise ValueError("Invalid JSON on line {}: {}".format(line_no, line))
ValueError: Invalid JSON on line 1: [

```

**Comment by ParthBarot-BoTreeConsulting** [comment]
Anyway, I found the solution to this - https://github.com/explosion/spaCy/issues/3523 - As per this we need to convert conll to json and not jsonl.

**Comment by ines** [comment]
Sorry about that – the default will be fixed in the next release!
