### ISSUE TITLE
"illegal type for path parameter" on Linux when using CLI train

### ISSUE THREAD

**Issue by fizban99** [explosion/spaCy#3713]
## How to reproduce the behaviour
After running the train CLI tool, I get an error on Linux:

```
File "[...]/lib/python3.5/site-packages/spacy/cli/train.py", line 382, in _collate_best_model
    shutil.copytree(output_path / "model-final", best_dest)
  File "[...]/lib/python3.5/shutil.py", line 309, in copytree
    names = os.listdir(src)
TypeError: argument should be string, bytes or integer, not PosixPath
Exception ignored in: <bound method GoldCorpus.__del__ of <spacy.gold.GoldCorpus object at 0x7f6e53d262b0>>
Traceback (most recent call last):
  File "gold.pyx", line 116, in spacy.gold.GoldCorpus.__del__
  File "[...]/lib/python3.5/shutil.py", line 471, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "[...]/lib/python3.5/shutil.py", line 469, in rmtree
    orig_st = os.lstat(path)
TypeError: lstat: illegal type for path parameter

```
It looks like in lines 381-382 of train.py `copytree` is used with a PosixPath and it fails on Linux.

```
    best_dest = output_path / "model-best"
    shutil.copytree(output_path / "model-final", best_dest)
```

This works fine on Windows. Shouldn't the paths be coerced to string with `str()`?

## Your Environment

* **Platform:** Linux-4.4.0-145-generic-x86_64-with-centos-7.6.1810-Core
* **spaCy version:** 2.1.3
* **Python version:** 3.5.5

**Comment by honnibal** [comment]
Thanks. I've been testing this on 3.6, where the standard library supports `PosixPath` objects. A PR would be welcome.

**Comment by fizban99** [comment]
Thank you. You are right. I had 3.7 on Windows. 

I tried the new version of the train.py file modified by Ines and, although the model-best version is created, I still get the following:

```
Exception ignored in: <bound method GoldCorpus.__del__ of <spacy.gold.GoldCorpus object at 0x7f08792459e8>>
Traceback (most recent call last):
  File "gold.pyx", line 116, in spacy.gold.GoldCorpus.__del__
  File "[...]/lib/python3.5/shutil.py", line 471, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "[...]/lib/python3.5/shutil.py", line 469, in rmtree
    orig_st = os.lstat(path)
TypeError: lstat: illegal type for path parameter
```

**Comment by fizban99** [comment]
Strangely, I do not get that error anymore...
