### ISSUE TITLE
Spacy convert CLI fails to convert jsonl to json.

### ISSUE THREAD

**Issue by gauravnbcu** [explosion/spaCy#3762]
spaCy cli convert fails to convert jsonl to json. Due to _sentencizer_ component failure.
 
Just run  below command
` $ spacy convert eval.jsonl --lang en `
JSONL has about 35k lines.

Example:
```
{"text":"Tyson Foods sold its minority stake in Beyond because it wants to sell its own plant-based proteins, according to Axios.","spans":[{"start":0,"end":11,"label":"ORG"}]}
{"text":"So far, Disney has confirmed sequels to \"Black Panther\" and \"Doctor Strange\" as well as a third installment of \"The Guardians of the Galaxy\" franchise.","spans":[{"start":8,"end":14,"label":"ORG"}]} 
```

**Stack trace**
`Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_2/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_2/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_2/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_2/lib/python3.6/site-packages/spacy/cli/convert.py", line 80, in convert
    data = func(input_data, n_sents=n_sents, use_morphology=morphology, lang=lang)
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_2/lib/python3.6/site-packages/spacy/cli/converters/jsonl2json.py", line 31, in ner_jsonl2json
    json_docs.append(docs_to_json(docs, id=i))
  File "gold.pyx", line 616, in spacy.gold.docs_to_json
  File "doc.pyx", line 595, in sents
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.`

## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
* **Python version:** 3.6.7
* **Models:** en

**Comment by BreakBB** [comment]
I can't reproduce this issue an Windows with spaCy 2.1.4 and Python 3.7.3. Tried with around 36k JSON lines

**Comment by gauravnbcu** [comment]
I even made a fresh setup with spaCy 2.1.4, python 3.6  on linux . Still same issue

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_4/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_4/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_4/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_4/lib/python3.6/site-packages/spacy/cli/convert.py", line 80, in convert
    data = func(input_data, n_sents=n_sents, use_morphology=morphology, lang=lang)
  File "/efs/nn_based_nlp_stuff/venv_spacy_2_1_4/lib/python3.6/site-packages/spacy/cli/converters/jsonl2json.py", line 31, in ner_jsonl2json
    json_docs.append(docs_to_json(docs, id=i))
  File "gold.pyx", line 616, in spacy.gold.docs_to_json
  File "doc.pyx", line 595, in sents
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.

## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
* **Python version:** 3.6.7
* **Models:** en

**Comment by gauravnbcu** [comment]
To narrow down the problem I tried to convert few sample sentences instead.

Conversion fails when jsonl has sentence like following:
` {"text":"DirecTV","spans":[{"start":0,"end":7,"label":"ORG"}]}
`
So, I created a jsonl file with just one sentence mentioned above.
And it fails in conversion. Stack-trace and environment is same as in previous comment.
## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
* **Python version:** 3.6.7
* **Models:** en

However, conversion works with spacy version 2.1.2 
spaCy 2.1.2 output
`spacy convert slim.jsonl --lang en -t json`
```
[
  {
    "id":0,
    "paragraphs":[
      {
        "raw":"DirecTV",
        "sentences":[
          {
            "tokens":[
              {
                "id":0,
                "orth":"DirecTV",
                "ner":"U-ORG"
              }
            ],
            "brackets":[

            ]
          }
        ]
      }
    ]
  }
]
```
Hope this helps in reproducing the issue.

**Comment by BreakBB** [comment]
Okay with `{"text":"DirecTV","spans":[{"start":0,"end":7,"label":"ORG"}]}` I can reproduce your error and the problem is that it is just one word.

**Comment by gauravnbcu** [comment]
I think `is_sentence` should be `True` for single word. As there could be valid sentences with just one words. 
[Here](https://github.com/explosion/spaCy/blob/4d550a3055587cd8a440e6dcd6d52b351efb6103/spacy/tokens/doc.pyx#L241)  first token always marks `sent_start` but it's being ignored when determining is_sentence.
 
Anyhow when we use parser for sentence segmentation is_sentence is True for sentences with one word ?

**Comment by honnibal** [comment]
In v2.1.5, we've changed `doc.is_sentenced` to be `True` for single-word `Doc` objects. I think that should resolve this. Thanks for the report!
