### ISSUE TITLE
error in tokenizer.pyx

### ISSUE THREAD

**Issue by sjm1992st** [explosion/spaCy#3781]
* Operating System:
win7 x64
* Python Version Used: 
3.5
* spaCy Version Used:
2.1.4
I get error when i used spacy,like:
```
Traceback (most recent call last):
  File "D:/My Documents/Downloads/Chinese_models_for_SpaCy-master/Chinese_models_for_SpaCy-master/test.py", line 7, in <module>
    nlp = zh_core_web_sm.load()
  File "D:\Ssoftware\anaconda3\envs\py35\lib\site-packages\zh_core_web_sm\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\site-packages\spacy\util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\site-packages\spacy\util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\site-packages\spacy\language.py", line 791, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\site-packages\spacy\util.py", line 630, in from_disk
    reader(path / key)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\site-packages\spacy\language.py", line 781, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
  File "tokenizer.pyx", line 391, in spacy.tokenizer.Tokenizer.from_disk
    self.from_bytes(bytes_data, **kwargs)
  File "tokenizer.pyx", line 439, in spacy.tokenizer.Tokenizer.from_bytes
    self.suffix_search = re.compile(data["suffix_search"]).search
  File "D:\Ssoftware\anaconda3\envs\py35\lib\re.py", line 224, in compile
    return _compile(pattern, flags)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\sre_compile.py", line 540, in compile
    code = _code(p, flags)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\sre_compile.py", line 525, in _code
    _compile(code, p.data, flags)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\sre_compile.py", line 185, in _compile
    _compile(code, av, flags)
  File "D:\Ssoftware\anaconda3\envs\py35\lib\sre_compile.py", line 158, in _compile
    raise error("look-behind requires fixed-width pattern")
sre_constants.error: look-behind requires fixed-width pattern
```
tokenizer.pyx
I find that used 'import regex as re' in the version of 2.0.3 ,but now use 'import re',  So is some wrongs in that ?

**Comment by ines** [comment]
Not sure where your `zh_core_web_sm` model comes from, but it's likely out of date. If it was trained and created with spaCy v2.0.x, it won't work on v2.1.x. One reason is that the tokenizer now uses `re` and no variable-width lookbehinds, which makes it 2-3 times faster.

So you'll either have to retrain / repackage that model, or load it with spaCy v2.0.x.

**Comment by BreakBB** [comment]
The model comes from [here](https://github.com/howl-anderson/Chinese_models_for_SpaCy) and as stated in [an issue](https://github.com/howl-anderson/Chinese_models_for_SpaCy/issues/16) there are currently no plans to update the model for spaCy v2.1.
