### ISSUE TITLE
Could not find a transition with the name 'O' in the NER model

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#3782]
When I train an NER model and start from en_vectors_web_lg (instead of (en_core_web_lg)
(I passed it as the argument -m which is probably wrong because its not a model file)

So I get this error

```
Loaded model 'en_vectors_web_lg'
Process Process-6:
Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Anaconda\envs\spacy\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\TEMP\_train_ner_multi.py", line 106, in worker
    losses=losses,
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\language.py", line 421, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 564, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 681, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "ner.pyx", line 118, in spacy.syntax.ner.BiluoPushDown.preprocess_gold
  File "ner.pyx", line 177, in spacy.syntax.ner.BiluoPushDown.lookup_transition
KeyError: "[E022] Could not find a transition with the name 'O' in the NER model."

```

If I'm using it wrong, how do we use this set of vectors instead of the ones provided with en_core_web_lg?

Documentation https://spacy.io/usage/vectors-similarity says

> " If your application will benefit from a large vocabulary with more vectors, you should consider using one of the larger models or loading in a full vector package, for example, en_vectors_web_lg, which includes over 1 million unique vectors."

But doesn't really describe how to do it.

Using the train_ner.py script provided.  
Spacy version 2.0.18
python 3.6.8 (Anaconda 3)

**Comment by honnibal** [comment]
Could you try again with v2.1.4? I think your problem should be fixed there.

**Comment by erotavlas** [comment]
@honnibal 

I am getting the following error with 2.1.4

> ValueError: [E109] Model for component 'ner' not initialized. Did you forget to
> load a model, or forget to call begin_training()?

Also found someone else had the same issue
https://stackoverflow.com/q/55612157/1462656

If it helps my train method looks like this

```
def worker(model=None, input_file=None, output_dir=None, n_iter=100, dropout=0.5, batchsize=32.0):
	print("begin worker")
	if output_dir is not None:
		output_dir = os.path.join(output_dir, input_file.name.rstrip("\\").rstrip("/"))

	if input_file is None:
		print("No input file - exiting")
		return
	else:
		# training data
		path = input_file.as_posix()
		print("Load training data: " , path)

		with open(path, 'r') as myfile:
			data = myfile.read()
		  
		TRAIN_DATA = eval(data)

		# """Load the model, set up the pipeline and train the entity recognizer."""
		if model is not None:
			nlp = spacy.load(model)  # load existing spaCy model
			print("Loaded model '%s'" % model)
		else:
			nlp = spacy.blank("en")  # create blank Language class
			nlp.vocab.vectors.name = 'spacy_pretrained_vectors' #added this to solve error Unnamed vectors -- this won't allow multiple vectors models to be loaded
			print("Created blank 'en' model")

		# create the built-in pipeline components and add them to the pipeline
		# nlp.create_pipe works for built-ins that are registered with spaCy
		if "ner" not in nlp.pipe_names:
			ner = nlp.create_pipe("ner")
			nlp.add_pipe(ner, last=True)
		# otherwise, get it so we can add labels
		else:
			ner = nlp.get_pipe("ner")

		# add labels
		for _, annotations in TRAIN_DATA:
			for ent in annotations.get("entities"):
				ner.add_label(ent[2])

		# get names of other pipes to disable them during training
		other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]
		with nlp.disable_pipes(*other_pipes):  # only train NER
			# reset and initialize the weights randomly – but only if we're
			# training a new model
			if model is None:
				nlp.begin_training()
			for itn in range(n_iter):
				random.shuffle(TRAIN_DATA)
				losses = {}
				# batch up the examples using spaCy's minibatch
				size=compounding(2.0, batchsize, 1.005)
				batches = minibatch(TRAIN_DATA, size)
				for batch in batches:
					texts, annotations = zip(*batch)
					nlp.update(
						texts,  # batch of texts
						annotations,  # batch of annotations
						drop=dropout,  # dropout - make it harder to memorise data
						losses=losses,
					)
				count = itn + 1
				print("Losses", losses, " Iteration: ", count, " of ", n_iter, " Fold: " , input_file)
				sys.stdout.flush()

		# save model to output directory
		if output_dir is not None:
			output_dir = Path(output_dir)
			if not output_dir.exists():
				output_dir.mkdir()
			nlp.to_disk(output_dir)
			print("Saved model to", output_dir)
```

**Comment by erotavlas** [comment]
Is there a way to determine if the supplied model contains pre-trained weights? (without relying on folder name)

If not, I'll just have to add a new argument to indicate whether I want to start training from scratch and force a call to begin_training() (in the case I supply vectors only)

**Comment by ines** [comment]
> Is there a way to determine if the supplied model contains pre-trained weights? (without relying on folder name)

You can look at `nlp.pipeline` and `nlp.pipe_names` – if they're empty, there are no pipeline components, so no weights. See `if "ner" not in nlp.pipe_names` in your script for an example of this.

So maybe you could do something like this:

```diff
+       reset_weights = False
        if "ner" not in nlp.pipe_names:
			ner = nlp.create_pipe("ner")
			nlp.add_pipe(ner, last=True)
+           reset_weights = True
		# otherwise, get it so we can add labels
		else:
			ner = nlp.get_pipe("ner")
```

... and then later:

```diff
-			if model is None:
+           if model is None or reset_weights:
				nlp.begin_training()
```

If you later want an argument on the command line to reset the weights, it'd then also be easy to implement (by adding a `reset_weights` argument you can toggle).

**Comment by erotavlas** [comment]
Thank you! That works.
