### ISSUE TITLE
use spacy with hug result in missing dependencies

### ISSUE THREAD

**Issue by dtsonov** [explosion/spaCy#3817]
with this have a simple HUG code:

```python
import hug
import spacy

@hug.get("/happy_birthday")
def happy_birthday(name, age:hug.types.number=1):
    """Says happy birthday to a user"""
    return "Happy {age} Birthday {name}!".format(**locals())
```

I have problem with the line: "import spacy"

Both SPACY and HUG separately were installed successfully and work fine.

But when I run the this file with hug "hug -f file.py" it generates a bunch of errors:

I saw spacy examples with hug, there spacy is used exatly the same way: "import spacy"
and directly referencing spacy. 

What is wrong in my case, how I can resolve these problems?

Traceback (most recent call last):
  File "C:\Users\dtsonov\AppData\Local\Continuum\anaconda3\Scripts\hug-script.py", line 10, in <module>
    sys.exit(development_runner.hug.interface.cli())
  File "C:\Users\dtsonov\AppData\Local\Continuum\anaconda3\lib\site-packages\hug\interface.py", line 551, in __call__
    raise exception
  File "C:\Users\dtsonov\AppData\Local\Continuum\anaconda3\lib\site-packages\hug\interface.py", line 547, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "C:\Users\dtsonov\AppData\Local\Continuum\anaconda3\lib\site-packages\hug\interface.py", line 100, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "C:\Users\dtsonov\AppData\Local\Continuum\anaconda3\lib\site-packages\hug\development_runner.py", line 59, in hug
    api_module = importlib.machinery.SourceFileLoader(file.split(".")[0], file).load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "bott_rest_api.py", line 8, in <module>
    import spacy
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\thinc\__init__.py", line 5, in <module>
    import numpy  # noqa: F401
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

**Comment by ines** [comment]
This looks like it's not an issue with spaCy, but with numpy / Anaconda and your Python environment and PYthon path. As you can see, spaCy and its dependency Thinc are installed and available, and their code is executed. But when it hits `numpy`, it fails with that error.

It's possible that when you run `hug` on the command line, it actually executes a different Python environment or doesn't have everything on the Python path?  Also, if you google the error, you'll be able to find various threads on the same problem, so maybe some of those help?

* https://github.com/ContinuumIO/anaconda-issues/issues/10628
* https://stackoverflow.com/questions/54063285/numpy-is-already-installed-with-anaconda-but-i-get-an-importerror-dll-load-fail
* https://www.google.com/search?q=numpy++ImportError%3A+DLL+load+failed%3A+The+specified+module+could+not+be+found
