### ISSUE TITLE
Error while running docker with spacy

### ISSUE THREAD

**Issue by dchankova** [explosion/spaCy#3832]
I am running windows docker with spacy and this error appears

docker run --rm -it test

> Traceback (most recent call last):
>   File "application.py", line 4, in <module>
>     import spacy_test
>   File "C:\app\spacy_test.py", line 11, in <module>
>     import spacy
>   File "C:\app\venv\lib\site-packages\spacy\__init__.py", line 12, in <module>
>     from .cli.info import info as cli_info
>   File "C:\app\venv\lib\site-packages\spacy\cli\__init__.py", line 6, in <module>
>     from .train import train  # noqa: F401
>   File "C:\app\venv\lib\site-packages\spacy\cli\train.py", line 18, in <module>
>     from ..gold import GoldCorpus
>   File "strings.pxd", line 23, in init spacy.gold
> ImportError: DLL load failed: The specified module could not be found.

**Comment by ines** [comment]
>  ImportError: DLL load failed: The specified module could not be found.

This sounds like spaCy either didn't install or didn't compile properly. It's difficult to debug this without more specifics, but I think the solution probably comes down to the installation / compilation / Python environment.

I'm no Docker expert, but how does your configuration look and how are you installing spaCy?

**Comment by bugdom** [comment]
Hello,

i'm having a similar problem. I installed spacy for the first time (using pip), and i'm getting this:

```bash
C:\Users\u>python -m spacy validate
Traceback (most recent call last):
  File "C:\Users\u\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\u\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\u\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\u\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__init__.py", line 12, in <module>
    from .cli.info import info as cli_info
  File "C:\Users\u\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\__init__.py", line 6, in <module>
    from .train import train  # noqa: F401
  File "C:\Users\u\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\train.py", line 18, in <module>
    from ..gold import GoldCorpus
  File "strings.pxd", line 23, in init spacy.gold
ImportError: DLL load failed: The specified module could not be found.
```
I tried reinstalling a few times with pip and conda, but that didn't help.

## Your Environment
* Operating System: Windows 10 64-Bit
* Python Version Used: 3.7.3 64-Bit
