### ISSUE TITLE
Failing to install spaCy 2.1 AND 2.0 on some architectures

### ISSUE THREAD

**Issue by Impelon** [explosion/spaCy#3861]
Currently it is impossible to install spaCy 2.1+ on some architectures due to it's dependency on [blis](https://github.com/explosion/cython-blis). This is related to #3451, but goes beyond that.
This is because blis is not supposed to support the 32-bit operating systems discussed in #3451 (raspbian and ubuntu for the raspberry pi 3), but I have failed installing spaCy even with [Arch Linux ARM's 64-bit OS for the Raspberry Pi 3](https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3), because blis cannot compile.

I would like to use some of spaCy-2.1's new features, but was going to be happy with spaCy 2.0 for now. The problem is, I have other installation issues with spaCy 2.0.18.

Do you see yourselves fixing this in the coming weeks/month?
Please tell me if there is any additional information or clarification I could provide to you, that would help you.

## How to reproduce the problem

_I should mention that I use a virtualenv to install spacy and its dependencies._
I tried both `pip3 install spacy==2.1.4` and building blis from source (and planning to build spacy after). Both these methods failed, because blis 0.2.4 (as required by spaCy on pip) always assumes `x86_64` architecture on linux environments (also does not support any other architecture on linux) and blis 0.3+ (which would not work with spacy anyways, according to pip) cannot be built from source, because of the problems mentioned in explosion/cython-blis#9, explosion/cython-blis#6 and similar. Setting `BLIS_ARCH` to `generic` does not help.

This is the error I get, building blis 0.2.4 (and therefore spaCy 2.1.4) with pip (aka. `pip3 install blis==0.2.4`).
```bash
  [...]
  copying blis/__init__.pxd -> build/lib.linux-aarch64-3.7/blis
  running build_ext
  unix
  py_compiler gcc
  {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'HOSTTYPE': 'x86_64', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LANG': 'C.UTF-8', 'OLDPWD': '/home/matt/repos/flame-blis', 'VIRTUAL_ENV': '/home/matt/repos/wheelwright/env3.6', 'USER': 'matt', 'PWD': '/home/matt/repos/cython-blis', 'HOME': '/home/matt', 'NAME': 'LAPTOP-OMKOB3VM', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'SHLVL': '1', 'LOGNAME': 'matt', 'PATH': '/home/matt/repos/wheelwright/env3.6/bin:/tmp/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu:/mnt/c/Python37/Scripts:/mnt/c/Python37:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/LLVM/bin:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/nodejs:/mnt/c/Users/matt/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/matt/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/matt/AppData/Roaming/npm:/snap/bin:/mnt/c/Program Files/Oracle/VirtualBox', 'PS1': '(env3.6) \\[\\e]0;\\u@\\h: \\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ', 'VAGRANT_HOME': '/home/matt/.vagrant.d/', 'OMP_NUM_THREADS': '1', 'LESSOPEN': '| /usr/bin/lesspipe %s', '_': '/home/matt/repos/wheelwright/env3.6/bin/python'}
  gcc -c /tmp/pip-install-ucphfa1p/blis/blis/_src/config/generic/bli_cntx_init_generic.c -o /tmp/tmp6gss7sd1/bli_cntx_init_generic.o -O3 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ucphfa1p/blis/blis/_src/include/linux-x86_64
  gcc -c /tmp/pip-install-ucphfa1p/blis/blis/_src/config/haswell/bli_cntx_init_haswell.c -o /tmp/tmp6gss7sd1/bli_cntx_init_haswell.o -O3 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ucphfa1p/blis/blis/_src/include/linux-x86_64
  gcc -c /tmp/pip-install-ucphfa1p/blis/blis/_src/config/penryn/bli_cntx_init_penryn.c -o /tmp/tmp6gss7sd1/bli_cntx_init_penryn.o -O2 -fomit-frame-pointer -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ucphfa1p/blis/blis/_src/include/linux-x86_64
  gcc -c /tmp/pip-install-ucphfa1p/blis/blis/_src/config/piledriver/bli_cntx_init_piledriver.c -o /tmp/tmp6gss7sd1/bli_cntx_init_piledriver.o -O2 -fomit-frame-pointer -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ucphfa1p/blis/blis/_src/include/linux-x86_64
  gcc -c /tmp/pip-install-ucphfa1p/blis/blis/_src/config/sandybridge/bli_cntx_init_sandybridge.c -o /tmp/tmp6gss7sd1/bli_cntx_init_sandybridge.o -O3 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ucphfa1p/blis/blis/_src/include/linux-x86_64
  gcc -c /tmp/pip-install-ucphfa1p/blis/blis/_src/config/steamroller/bli_cntx_init_steamroller.c -o /tmp/tmp6gss7sd1/bli_cntx_init_steamroller.o -O2 -fomit-frame-pointer -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ucphfa1p/blis/blis/_src/include/linux-x86_64
  gcc -c /tmp/pip-install-ucphfa1p/blis/blis/_src/kernels/zen/1/bli_amaxv_zen_int.c -o /tmp/tmp6gss7sd1/bli_amaxv_zen_int.o -O3 -mavx2 -mfma -mfpmath=sse -march=core-avx2 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ucphfa1p/blis/blis/_src/include/linux-x86_64
  gcc: error: unrecognized command line option '-mavx2'
  gcc: error: unrecognized command line option '-mfma'
  gcc: error: unrecognized command line option '-mfpmath=sse'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ucphfa1p/blis/setup.py", line 266, in <module>
      'Topic :: Scientific/Engineering'
    File "/home/pi/project-2/env/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/pi/project-2/env/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-ucphfa1p/blis/setup.py", line 105, in build_extensions
      objects = self.compile_objects(compiler.split('-')[0], arch, OBJ_DIR)
    File "/tmp/pip-install-ucphfa1p/blis/setup.py", line 184, in compile_objects
      objects.append(self.build_object(env=env, **spec))
    File "/tmp/pip-install-ucphfa1p/blis/setup.py", line 198, in build_object
      subprocess.check_call(command, cwd=BLIS_DIR)
    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['gcc', '-c', '/tmp/pip-install-ucphfa1p/blis/blis/_src/kernels/zen/1/bli_amaxv_zen_int.c', '-o', '/tmp/tmp6gss7sd1/bli_amaxv_zen_int.o', '-O3', '-mavx2', '-mfma', '-mfpmath=sse', '-march=core-avx2', '-fPIC', '-std=c99', '-D_POSIX_C_SOURCE=200112L', '-DBLIS_VERSION_STRING="0.5.0-6"', '-DBLIS_IS_BUILDING_LIBRARY', '-Iinclude/linux-x86_64', '-I./frame/3/', '-I./frame/ind/ukernels/', '-I./frame/1m/', '-I./frame/1f/', '-I./frame/1/', '-I./frame/include', '-I/tmp/pip-install-ucphfa1p/blis/blis/_src/include/linux-x86_64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for blis
```
The error one gets from building blis directly from the cloned master-branch from github is, as mentioned in explosion/cython-blis#9 (by using `BLIS_ARCH=generic python -m setup.py`):

```bash
  [...]
  gcc: error: blis/cy.c: No such file or directory
  gcc: fatal error: no input files
  [...]
```

As mentioned before I, afterwards I tried installing spacy 2.0.18.

```bash
  [...]
  building 'spacy.parts_of_speech' extension
  creating build/temp.linux-aarch64-3.7
  creating build/temp.linux-aarch64-3.7/spacy
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/spacy/include -I/usr/include/python3.7m -c spacy/parts_of_speech.cpp -o build/temp.linux-aarch64-3.7/spacy/parts_of_speech.o -O2 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-aarch64-3.7/spacy/parts_of_speech.o -L/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/spacy/parts_of_speech.cpython-37m-aarch64-linux-gnu.so
  building 'spacy.strings' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/spacy/include -I/usr/include/python3.7m -c spacy/strings.cpp -o build/temp.linux-aarch64-3.7/spacy/strings.o -O2 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  spacy/strings.cpp: In function 'int __pyx_pf_5spacy_7strings_11StringStore_8__contains__(__pyx_obj_5spacy_7strings_StringStore*, PyObject*)':
  spacy/strings.cpp:3682:29: warning: comparison of integer expressions of different signedness: '__pyx_t_5spacy_8typedefs_hash_t' {aka 'long unsigned int'} and 'Py_ssize_t' {aka 'long int'} [-Wsign-compare]
     __pyx_t_1 = ((__pyx_v_key < __pyx_t_6) != 0);
                   ~~~~~~~~~~~~^~~~~~~~~~~
  spacy/strings.cpp: In function 'PyObject* __pyx_gb_5spacy_7strings_11StringStore_12generator(__pyx_CoroutineObject*, PyThreadState*, PyObject*)':
  spacy/strings.cpp:3836:33: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<long unsigned int>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
     for (__pyx_t_2 = 0; __pyx_t_2 < __pyx_t_1; __pyx_t_2+=1) {
                         ~~~~~~~~~~^~~~~~~~~~~
  g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-aarch64-3.7/spacy/strings.o -L/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/spacy/strings.cpython-37m-aarch64-linux-gnu.so
  building 'spacy.lexeme' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/spacy/include -I/usr/include/python3.7m -c spacy/lexeme.cpp -o build/temp.linux-aarch64-3.7/spacy/lexeme.o -O2 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  In file included from /tmp/pip-install-lvepk9hx/spacy/include/numpy/ndarraytypes.h:1728,
                   from /tmp/pip-install-lvepk9hx/spacy/include/numpy/ndarrayobject.h:17,
                   from /tmp/pip-install-lvepk9hx/spacy/include/numpy/arrayobject.h:15,
                   from spacy/lexeme.cpp:547:
  /tmp/pip-install-lvepk9hx/spacy/include/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
    ^~~~~~~
  {standard input}: Assembler messages:
  {standard input}:111820: Warning: end of file not at end of a line; newline inserted
  {standard input}:112658: Error: unknown pseudo-op: `.lbb'
  {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
  gcc: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for spacy
```
A few moments later `thinc` also fails:
```bash
  [...]
  building 'thinc.linalg' extension
  creating build/temp.linux-aarch64-3.7
  creating build/temp.linux-aarch64-3.7/thinc
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/thinc/include -I/usr/include/python3.7m -c thinc/linalg.cpp -o build/temp.linux-aarch64-3.7/thinc/linalg.o -O3 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-aarch64-3.7/thinc/linalg.o -L/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/thinc/linalg.cpython-37m-aarch64-linux-gnu.so
  building 'thinc.structs' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/thinc/include -I/usr/include/python3.7m -c thinc/structs.cpp -o build/temp.linux-aarch64-3.7/thinc/structs.o -O3 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-aarch64-3.7/thinc/structs.o -L/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/thinc/structs.cpython-37m-aarch64-linux-gnu.so
  building 'thinc.typedefs' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/thinc/include -I/usr/include/python3.7m -c thinc/typedefs.cpp -o build/temp.linux-aarch64-3.7/thinc/typedefs.o -O3 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-aarch64-3.7/thinc/typedefs.o -L/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/thinc/typedefs.cpython-37m-aarch64-linux-gnu.so
  building 'thinc.linear.avgtron' extension
  creating build/temp.linux-aarch64-3.7/thinc/linear
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/thinc/include -I/usr/include/python3.7m -c thinc/linear/avgtron.cpp -o build/temp.linux-aarch64-3.7/thinc/linear/avgtron.o -O3 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-aarch64-3.7/thinc/linear/avgtron.o -L/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/thinc/linear/avgtron.cpython-37m-aarch64-linux-gnu.so
  building 'thinc.linear.features' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/thinc/include -I/usr/include/python3.7m -c thinc/linear/features.cpp -o build/temp.linux-aarch64-3.7/thinc/linear/features.o -O3 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-aarch64-3.7/thinc/linear/features.o -L/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/thinc/linear/features.cpython-37m-aarch64-linux-gnu.so
  building 'thinc.linear.serialize' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/thinc/include -I/usr/include/python3.7m -c thinc/linear/serialize.cpp -o build/temp.linux-aarch64-3.7/thinc/linear/serialize.o -O3 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-aarch64-3.7/thinc/linear/serialize.o -L/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/thinc/linear/serialize.cpython-37m-aarch64-linux-gnu.so
  building 'thinc.linear.sparse' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/thinc/include -I/usr/include/python3.7m -c thinc/linear/sparse.cpp -o build/temp.linux-aarch64-3.7/thinc/linear/sparse.o -O3 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-aarch64-3.7/thinc/linear/sparse.o -L/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/thinc/linear/sparse.cpython-37m-aarch64-linux-gnu.so
  building 'thinc.linear.linear' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -I/tmp/pip-install-lvepk9hx/thinc/include -I/usr/include/python3.7m -c thinc/linear/linear.cpp -o build/temp.linux-aarch64-3.7/thinc/linear/linear.o -O3 -Wno-strict-prototypes -Wno-unused-function
  cc1plus: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
  In file included from /tmp/pip-install-lvepk9hx/thinc/include/numpy/ndarraytypes.h:1728,
                   from /tmp/pip-install-lvepk9hx/thinc/include/numpy/ndarrayobject.h:17,
                   from /tmp/pip-install-lvepk9hx/thinc/include/numpy/arrayobject.h:15,
                   from thinc/linear/linear.cpp:628:
  /tmp/pip-install-lvepk9hx/thinc/include/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
    ^~~~~~~
  {standard input}: Assembler messages:
  {standard input}:296793: Warning: end of file not at end of a line; newline inserted
  gcc: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for thinc
```

I have also tried `pip3 install spacy==2.0.15` with the same results.

## Your Environment

I ran the code used in `spacy info` manually to get these results:
* Operating System: Linux-5.1.9-1-ARCH-aarch64-with-arch
* Python Version Used: 3.7.3

**Comment by ccarnero** [comment]
Same problem here, trying to install it on Jetson Nano.

**Comment by honnibal** [comment]
Thanks for your patience on this. Just pushed blis v0.3.1, which should allow installation (even if with not the most ideal workflow). See here: https://github.com/explosion/cython-blis/issues/9

@ccarnero @Impelon

**Comment by Impelon** [comment]
As mentioned in explosion/cython-blis#9 I will try to find the time to try these things out and keep you updated!

**Comment by bertelschmitt** [comment]
I have successfully installed Spacy on a Jetson Nano (Ubuntu) using
`BLIS_ARCH="generic" pip3.6 install spacy --no-binary blis`

Attempting to

``BLIS_ARCH="generic" pip3.6 install spacy[cuda100] --no-binary blis``

resulted in

``ERROR: Could not find a version that satisfies the requirement cupy-cuda100>=5.0.0b4; extra == "cuda100" (from spacy[cuda100]) (from versions: none)
ERROR: No matching distribution found for cupy-cuda100>=5.0.0b4; extra == `"cuda100"`

**Comment by agent001** [comment]
The below step worked for me

```
$ pip3 install cupy
$ BLIS_ARCH="generic" pip3 --no-cache-dir install spacy[cuda] --no-binary blis

$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
>>> import spacy
>>> spacy.prefer_gpu()
True

$ jetson_release
 - NVIDIA Jetson NANO/TX1
   * Jetpack UNKNOWN [L4T 32.4.2]
   * CUDA GPU architecture 5.3
   * NV Power Mode: MAXN - Type: 0
 - Libraries:
   * CUDA 10.2.89
   * cuDNN 8.0.0.145-1+cuda10.2
   * TensorRT 7.1.0.16-1+cuda10.2
   * Visionworks 1.6.0.501
   * OpenCV 4.1.1 compiled CUDA: NO
 - Jetson Performance: inactive
```
