### ISSUE TITLE
Using spacy download command via pipenv

### ISSUE THREAD

**Issue by marinswk** [explosion/spaCy#3910]
Hello, 

I'm trying to run spacy on a jenkins instance via a pipenv and i'm having troubles doing that both locally and on the jenkins installation.

I need to be able to run the command:
spacy download xx

via pipenv cause that's the way in which i'm installing the virtual environment.

In both cases (jenkins and local, with the same exact pipfile) i get the following error when running:
pipenv run spacy download xx

```bash
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 408, in run
    command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2328, in do_run
    do_run_posix(script, command=command)
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2297, in do_run_posix
    command_path, command_path, *[os.path.expandvars(arg) for arg in script.args]
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 539, in execl
    execv(file, args)
OSError: [Errno 8] Exec format error
```
is there any solution to that?

## Info about spaCy

* **spaCy version:** 2.0.12
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.7.3
* **Models:** xx

**Comment by BreakBB** [comment]
The basic command is:

```bash
python -m spacy download xx
```

So with pipenv you probably just want to add the `pipenv run` at the beginning to get:

```bash
pipenv run python -m spacy download xx
```

**Comment by marinswk** [comment]
Thank you very much for the reply, locally it worked as you said, on jenkins i needed to make a bit of a weird commands play to get it to work but in the end it does work as well:

`python3 -u -m pipenv run python3 -u -m spacy download xx`

**Comment by BreakBB** [comment]
Looks really hacky, but as long as it solves your issue, great. You may close the issue if you think your problem is resolved.
