### ISSUE TITLE
Can't use Gpu under k8s

### ISSUE THREAD

**Issue by jmvizcainoio** [explosion/spaCy#3966]
## How to reproduce the problem

We are trying to use spacy using gpu under kubernetes environment. We have already nvidia drivers and docker installed and i can see the gpu.

```bash
nvidia-smi
Mon Jul 15 07:40:10 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   52C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

But when we try to use we got and error. 
```
ValueError: GPU is not accessible. Was the library installed correctly?
```

I think that the problem is related with thinc_gpu_ops library but i'm not sure.
 

```bash
pip install cupy-cuda90
pip install -U spacy[cuda90]
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.prefer_gpu()
False
>>> spacy.require_gpu()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/myownenv/lib/python3.6/site-packages/thinc/neural/util.py", line 74, in require_gpu
    raise ValueError("GPU is not accessible. Was the library installed correctly?")
ValueError: GPU is not accessible. Was the library installed correctly?
```

## Your Environment

* Operating System: Debian buster/sid 
* Python Version Used: 3.6.7
* spaCy Version Used: 2.1.6
* Environment Information: Kubernetes

**Comment by BreakBB** [comment]
I am not familiar with spaCy running on GPU, but did you install the [CUDA toolkit](https://developer.nvidia.com/cuda-downloads) as well?

**Comment by svlandeg** [comment]
Could you run `nvcc --version` in a console and check the cuda version?

**Comment by jmvizcainoio** [comment]
@BreakBB Hi

I think is correctly installed. 

```
dpkg -l | grep cuda
ii  cuda-cublas-9-1               9.1.85.3-1                        amd64        CUBLAS native runtime libraries
ii  cuda-cublas-dev-9-1           9.1.85.3-1                        amd64        CUBLAS native dev links, headers
ii  cuda-cudart-9-1               9.1.85-1                          amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-9-1           9.1.85-1                          amd64        CUDA Runtime native dev links, headers
ii  cuda-cufft-9-1                9.1.85-1                          amd64        CUFFT native runtime libraries
ii  cuda-cufft-dev-9-1            9.1.85-1                          amd64        CUFFT native dev links, headers
ii  cuda-curand-9-1               9.1.85-1                          amd64        CURAND native runtime libraries
ii  cuda-curand-dev-9-1           9.1.85-1                          amd64        CURAND native dev links, headers
ii  cuda-cusolver-9-1             9.1.85-1                          amd64        CUDA solver native runtime libraries
ii  cuda-cusolver-dev-9-1         9.1.85-1                          amd64        CUDA solver native dev links, headers
ii  cuda-cusparse-9-1             9.1.85-1                          amd64        CUSPARSE native runtime libraries
ii  cuda-cusparse-dev-9-1         9.1.85-1                          amd64        CUSPARSE native dev links, headers
ii  cuda-driver-dev-9-1           9.1.85-1                          amd64        CUDA Driver native dev stub library
ii  cuda-libraries-dev-9-1        9.1.85-1                          amd64        CUDA Libraries 9.1 development meta-package
ii  cuda-license-9-1              9.1.85-1                          amd64        CUDA licenses
ii  cuda-misc-headers-9-1         9.1.85-1                          amd64        CUDA miscellaneous headers
ii  cuda-npp-9-1                  9.1.85-1                          amd64        NPP native runtime libraries
ii  cuda-npp-dev-9-1              9.1.85-1                          amd64        NPP native dev links, headers
ii  cuda-nvcc-9-1                 9.1.85.2-1                        amd64        CUDA nvcc
ii  cuda-nvgraph-9-1              9.1.85-1                          amd64        NVGRAPH native runtime libraries
ii  cuda-nvgraph-dev-9-1          9.1.85-1                          amd64        NVGRAPH native dev links, headers
ii  cuda-nvml-dev-9-1             9.1.85-1                          amd64        NVML native dev links, headers
ii  cuda-nvrtc-9-1                9.1.85-1                          amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-dev-9-1            9.1.85-1                          amd64        NVRTC native dev links, headers
ii  libcudnn7                     7.6.1.34-1+cuda10.1               amd64        cuDNN runtime libraries
```

@svlandeg Sofie, this is the output

````
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
````

Thanks

**Comment by svlandeg** [comment]
Considering that's `cuda` version 9.1 (and not 9.0), can you try installing with `spacy[cuda91]` instead? cf [docs](https://spacy.io/usage/#gpu)

**Comment by jmvizcainoio** [comment]
@svlandeg Hi Sofie

Sorry, i try to install spacy[cuda91] and the same result. 

This is the libraries installed.

```
pip3 freeze
asn1crypto==0.24.0
blis==0.2.4
certifi==2019.6.16
chardet==3.0.4
cryptography==2.1.4
cupy-cuda91==7.0.0b1
cymem==2.0.2
fastrlock==0.4
idna==2.8
keyring==10.6.0
keyrings.alt==3.0
murmurhash==1.0.2
numpy==1.16.4
plac==0.9.6
preshed==2.0.1
pycrypto==2.6.1
pygobject==3.26.1
pyxdg==0.25
requests==2.22.0
SecretStorage==2.3.1
six==1.12.0
spacy==2.1.6
srsly==0.0.7
thinc==7.0.8
thinc-gpu-ops==0.0.4
tqdm==4.32.2
urllib3==1.25.3
wasabi==0.2.2
```

Juanma

**Comment by honnibal** [comment]
Do you have the `LD_LIBRARY_PATH` and `CUDA_HOME` environment variables set? It's probably easiest to try to import `cupy` directly, and make sure you can allocate and multiple arrays on the GPU using cupy. If you can get that working and still can't get `spacy.prefer_gpu()` working, let us know.
