### ISSUE TITLE
Getting a RuntimeError: Running cythonize failed when compiling Spacy

### ISSUE THREAD

**Issue by almoslmi** [explosion/spaCy#3997]
I am trying to build SpaCy from the source but I got "RuntimeError: Running cythonize failed". I tried to do "pip install cython" and found that it has been installed already 

(base) C:\Users\tareq\PycharmProjects\spaCy>pip install cython
Requirement already satisfied: cython in c:\users\tareq\anaconda3\lib\site-packages (0.29.12)

Any idea how to solve this issue, please?

```
============
(base) C:\Users\tareq\PycharmProjects\spaCy>python setup.py build_ext --inplace
Cythonizing sources
Processing kb.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    cdef hash_t alias_hash
    cdef float prior_prob


cdef class KnowledgeBase:
    cdef Pool mem
        ^
------------------------------------------------------------

kb.pxd:30:9: 'Pool' is not a type identifier
Traceback (most recent call last):
  File "C:\Users\tareq\PycharmProjects\spaCy\bin\cythonize.py", line 169, in <module>
    run(args.root)
  File "C:\Users\tareq\PycharmProjects\spaCy\bin\cythonize.py", line 158, in run
    process(base, filename, db)
  File "C:\Users\tareq\PycharmProjects\spaCy\bin\cythonize.py", line 124, in process
    preserve_cwd(base, process_pyx, root + ".pyx", root + ".cpp")
  File "C:\Users\tareq\PycharmProjects\spaCy\bin\cythonize.py", line 87, in preserve_cwd
    func(*args)
  File "C:\Users\tareq\PycharmProjects\spaCy\bin\cythonize.py", line 63, in process_pyx
    raise Exception("Cython failed")
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 276, in <module>
    setup_package()
  File "setup.py", line 209, in setup_package
    generate_cython(root, "spacy")
  File "setup.py", line 132, in generate_cython
    raise RuntimeError("Running cythonize failed")
RuntimeError: Running cythonize failed
==============
```

Environment
* **spaCy version:** 2.1.6
* **Platform:** Windows-10-10.0.17763-SP0
* **Python version:** 3.7.1

**Comment by svlandeg** [comment]
@almoslmi : is this issue still occurring or were you able to fix it?

**Comment by almoslmi** [comment]
@svlandeg Unfortunately, still occurring

**Comment by honnibal** [comment]
@almoslmi Is it still occurring? We definitely build from source frequently, so I would expect it to work.

**Comment by naveenjafer** [comment]
I am facing this same issue, does anyone else have it happening for them too?

**Comment by hyzhan** [comment]
install cython>=0.29
