### ISSUE TITLE
Connection refused when downloading English models for spacy-2.1.4 and spacy-2.1.6

### ISSUE THREAD

**Issue by vostrosablin** [explosion/spaCy#4017]
## How to reproduce the problem
When trying to install spacy english models with `python -m spacy download en` getting a connection refused error. Probably the server is down.

Tried with versions 2.1.4 and 2.1.6

```bash
Traceback (most recent call last):
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x11df5dd50>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11df5dd50>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/cli/download.py", line 37, in download
    shortcuts = get_json(about.__shortcuts__, "available shortcuts")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/cli/download.py", line 73, in get_json
    r = requests.get(url)
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/vostrosa/Library/Python/3.7/lib/python/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11df5dd50>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

## Environment

* **spaCy version:** 2.1.6
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.7.4
* **Operating system:** Mac OS Mojave 10.14.5

**Comment by vostrosablin** [comment]
Probably was a temporary downtime. Now it works
