### ISSUE TITLE
Problem training a new model TypeError: Could not determine the signature of None

### ISSUE THREAD

**Issue by DanielFLopez** [explosion/spaCy#4043]
## Problem when I'm trying to train a model

I have this error when trying to run the algorithm  [https://spacy.io/usage/examples#training-ner](url) to train a new model.

```
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    plac.call(main('en_core_web_sm', Path.cwd(), 100))
  File "C:\ProgramData\Anaconda3\lib\site-packages\plac_core.py", line 324, in call
    parser = parser_from(obj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plac_core.py", line 133, in parser_from
    parser.populate_from(obj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plac_core.py", line 248, in populate_from
    self._set_func_argspec(func)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plac_core.py", line 240, in _set_func_argspec
    self.argspec = getargspec(obj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plac_core.py", line 38, in getargspec
    str(callableobj))
TypeError: Could not determine the signature of None
```
Just add the base model and the path in the main()

```
if __name__ == "__main__":
    plac.call(main('en_core_web_sm', Path.cwd(), 100))
```
## Environment
* Operating System:  Windows 10
* Python Version Used:  3.7
* spaCy Version Used:  2.1.6

**Comment by ines** [comment]
> Just add the base model and the path in the main()

Ahhh, you don't have to do that. The Plac wrapper exists so you can call the script from the command line with the arguments, like this:

```bash
python train_ner.py en_core_web_sm /path
```

If you want to call it from within Python, remove the `plac` wrapper and just execute the function:

```python
main('en_core_web_sm', Path.cwd(), 100)
```
