### ISSUE TITLE
Init-model doeesn't work for some languages

### ISSUE THREAD

**Issue by Xargonus** [explosion/spaCy#4048]
Init-model doesn't work for some languages with less features. So far I have found that cs and bg don't work, but there are probably more. The problem is I think init-model expecting non-empty vocab.

## Error

python -m spacy init-model bg test
[2K✔ Counted frequencies
[2K✔ Read clusters
0it [00:00, ?it/s]

Traceback (most recent call last):
  File "C:\Users\xargo\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\xargo\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xargo\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\xargo\AppData\Local\Programs\Python\Python36\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\xargo\AppData\Local\Programs\Python\Python36\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\xargo\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\cli\init_model.py", line 78, in init_model
    nlp = create_model(lang, lex_attrs)
  File "C:\Users\xargo\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\cli\init_model.py", line 146, in create_model
    oov_prob = min(lex.prob for lex in nlp.vocab)
ValueError: min() arg is an empty sequence

## How to reproduce the behaviour

`python -m spacy init-model cs test`

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6.7
* spaCy Version Used: 2.1.6
* Environment Information:

**Comment by ines** [comment]
Thanks for the report – fixed in #4048. 

In the meantime, if you just want an empty blank model saved to a directory (no vectors etc.), you can also use this one-liner:

```bash
python -c "import spacy;spacy.blank('cs').to_disk('/path/to/model')"
```
