### ISSUE TITLE
Cannot load BERT uncased 

### ISSUE THREAD

**Issue by kernelmachine** [explosion/spaCy#4076]
## How to reproduce the behaviour

```
$ python -m spacy download en_pytt_bertbaseuncased_lg
✔ Download and installation successful
You can now load the model via spacy.load('en_pytt_bertbaseuncased_lg')
$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.load('en_pytt_bertbaseuncased_lg')
Traceback (most recent call last):
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/spacy/util.py", line 70, in get_lang_class
    module = importlib.import_module(".lang.%s" % lang, "spacy")
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'spacy.lang.pytt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/spacy/util.py", line 134, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/spacy/util.py", line 155, in load_model_from_package
    return cls.load(**overrides)
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/en_pytt_bertbaseuncased_lg/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/spacy/util.py", line 196, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/spacy/util.py", line 166, in load_model_from_path
    cls = get_lang_class(lang)
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/spacy/util.py", line 72, in get_lang_class
    raise ImportError(Errors.E048.format(lang=lang, err=err))
ImportError: [E048] Can't import language pytt from spacy.lang: No module named 'spacy.lang.pytt'
```

## Your Environment

* **spaCy version:** 2.1.7
* **Platform:** Linux-4.15.0-45-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.3

**Comment by honnibal** [comment]
You need to install the wrapper: `pip install spacy-pytorch-transformers`. We decided to avoid allowing model packages to trigger downloading dependencies.

**Comment by kernelmachine** [comment]
oh, I overlooked the pip install. thanks!
