### ISSUE TITLE
unable to download spacy models by cli commands

### ISSUE THREAD

**Issue by adalisan** [explosion/spaCy#4135]
## How to reproduce the behaviour
install conda package

`conda install -c conda-forge spacy=2.0`

Download models 
```
> conda activate base
> python -m spacy download en
> 
```

```

Traceback (most recent call last):
  File "/nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5/lib/python3.6/site-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5/lib/python3.6/site-packages/spacy/cli/download.py", line 31, in download
    shortcuts = get_json(about.__shortcuts__, "available shortcuts")
  File "/nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5/lib/python3.6/site-packages/spacy/cli/download.py", line 58, in get_json
    return r.json()
  File "/nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
AttributeError: module 'simplejson' has no attribute 'loads'

```

## Info about spaCy

* **spaCy version:** 2.0.18
* **Platform:** Linux-2.6.32-504.8.1.el6_lustre.x86_64-x86_64-with-redhat-6.6-Carbon
* **Python version:** 3.6.8
* **Models:** en

**Comment by ines** [comment]
That's weird... I don't think this is related to or caused by spaCy, though. Looks like there's something wrong with the `requests` package installed in your environment:

```
 File "/nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
AttributeError: module 'simplejson' has no attribute 'loads'
```

It sounds pretty similar to psf/requests#4842, which describes a problem if `simplejson` is installed. Maybe just try uninstalling `simplejson`?

**Comment by svlandeg** [comment]
I would also add: I see you're using `base` environment - can you try first creating a new environment from scratch, `activate` that, and retry the commands?

**Comment by adalisan** [comment]
Regarding the conda env, the problem was for another environment. I just wrote source activate base for brevity
I don't think if I installed simplejson explicitly (only ujson was explicitly specified), maybe it was installed by a requirement.
I resolved the issue by a python one liner and made the call by plac.
