### ISSUE TITLE
Problems loading the English module when running SpaCy in python 2.7

### ISSUE THREAD

**Issue by simonedu** [explosion/spaCy#416]
Hi. We need to run the parser in a server using mod_python running python 2.7. We managed to install SpaCy in python 2.7, but we are not able to load the English module. When we try it, it returns a syntax error. So, are there any problems with running SpaCy in python 2.7? If so, how can we solve it? We installed the parser using pip2.7.

Thank you very much.

**Comment by honnibal** [comment]
This is related to https://github.com/spacy-io/spaCy/issues/414

The root cause is a missing pin on the version of plac. You can fix your installation by doing `pip install plac==0.9.1` until the packages are updated.

**Comment by simonedu** [comment]
Thank you!

**Comment by ggilling** [comment]
I'm also having problems on a fresh install on an EC2 instance.

I've tried installing plac 0.9.1 and the result is the following:

>>> import spacy
>>> spacy.load("en")
Killed

OR:

>>> from spacy import English
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name English

Any suggestions?

**Comment by ggilling** [comment]
Similarly, if I try downloading the German module, importing it yields the following:

Python 2.7.10 (default, Dec  8 2015, 18:25:23) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.load("de")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python2.7/site-packages/spacy/__init__.py", line 27, in load
    serializer=serializer)
  File "/usr/local/lib64/python2.7/site-packages/spacy/language.py", line 178, in __init__
    vocab = self.default_vocab(package, vectors_package=vectors_package)
  File "/usr/local/lib64/python2.7/site-packages/spacy/de/__init__.py", line 13, in default_vocab
    vocab = super(German,cls).default_vocab(package,get_lex_attr,vectors_package)
  File "/usr/local/lib64/python2.7/site-packages/spacy/language.py", line 112, in default_vocab
    vectors_package=vectors_package)
  File "spacy/vocab.pyx", line 64, in spacy.vocab.Vocab.from_package (spacy/vocab.cpp:3680)
  File "spacy/vocab.pyx", line 65, in spacy.vocab.Vocab.from_package (spacy/vocab.cpp:3624)
  File "spacy/strings.pyx", line 176, in spacy.strings.StringStore.load (spacy/strings.cpp:3663)
  File "spacy/strings.pyx", line 144, in spacy.strings.StringStore.intern (spacy/strings.cpp:3082)
  File "spacy/strings.pyx", line 157, in spacy.strings.StringStore._intern_utf8 (spacy/strings.cpp:3243)
  File "preshed/maps.pyx", line 66, in preshed.maps.PreshMap.set (preshed/maps.cpp:2570)
  File "preshed/maps.pyx", line 107, in preshed.maps.map_set (preshed/maps.cpp:3059)
  File "preshed/maps.pyx", line 170, in preshed.maps._resize (preshed/maps.cpp:3674)
  File "cymem/cymem.pyx", line 42, in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1091)
MemoryError: Error assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytesError assigning 8388608 bytes

**Comment by ggilling** [comment]
Aha - it turns out to have been that Spacy doesn't have enough memory to run on a micro ec2 instance. Upgrading to medium made everything better!

**Comment by akshay-1993** [comment]
Traceback (most recent call last):
  File "C:/Users/AkshayC/spacyNew/newSpacy.py", line 3, in <module>
    import spacy, time,SpacyUtils
  File "C:\Program Files\Python36\lib\site-packages\spacy\__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "C:\Program Files\Python36\lib\site-packages\spacy\cli\__init__.py", line 1, in <module>
    from .download import download
  File "C:\Program Files\Python36\lib\site-packages\spacy\cli\download.py", line 10, in <module>
    from .link import link
  File "C:\Program Files\Python36\lib\site-packages\spacy\cli\link.py", line 7, in <module>
    from ..compat import symlink_to, path2str
  File "C:\Program Files\Python36\lib\site-packages\spacy\compat.py", line 11, in <module>
    from thinc.neural.util import copy_array
ImportError: cannot import name 'copy_array'

Facing this issue when running english model 'en_core_web_sm'

**Comment by grahammorehead** [comment]
I'm having this same problem -- on a large instance.  memory is not the problem.

**Comment by ddofer** [comment]
Same issue, Anaconda, Python 3.6, latest spacy from Pip. 

`$ python -m spacy.en.download
Traceback (most recent call last):
  File "/Users/USER/anaconda/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/USER/anaconda/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/USER/anaconda/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Users/USER/anaconda/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Users/USER/anaconda/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/Users/USER/anaconda/lib/python3.6/site-packages/spacy/cli/link.py", line 7, in <module>
    from ..compat import symlink_to, path2str
  File "/Users/USER/anaconda/lib/python3.6/site-packages/spacy/compat.py", line 11, in <module>
    from thinc.neural.util import copy_array
ImportError: cannot import name 'copy_array'`
