### ISSUE TITLE
 sre_constants.error: bad escape \p at position 257

### ISSUE THREAD

**Issue by saurabhchandrapatel** [explosion/spaCy#4261]
## How to reproduce the behaviour
import spacy
nlp = spacy.load("en_core_web_md")

## Your Environment
 
spaCy version    2.1.6
Location         /srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy
Platform         Linux-3.10.0-327.el7.x86_64-x86_64-with-centos-7.2.1511-Core
Python version   3.6.3
Models           en, en_core_web_md ( 2.1.0 )

* Operating System:centos
* Python Version Used: 3.6.3
* spaCy Version Used: 2.1.6
* Environment Information: 
offline installation with pip  , python running in vertualenv 
can not run `python -m spacy validate` (its offline installation )
can not run `python -m spacy download en_core_web_md `
Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy/util.py", line 132, in load_model
    return load_model_from_link(name, **overrides)
  File "/srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy/util.py", line 149, in load_model_from_link
    return cls.load(**overrides)
  File "/srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy/util.py", line 193, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy/util.py", line 176, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy/language.py", line 811, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy/util.py", line 633, in from_disk
    reader(path / key)
  File "/srv/yoga-chat-bot/env36/lib/python3.6/site-packages/spacy/language.py", line 801, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
  File "tokenizer.pyx", line 391, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 437, in spacy.tokenizer.Tokenizer.from_bytes
  File "/srv/yoga-chat-bot/env36/lib64/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/srv/yoga-chat-bot/env36/lib64/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/srv/yoga-chat-bot/env36/lib64/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/srv/yoga-chat-bot/env36/lib64/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/srv/yoga-chat-bot/env36/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/srv/yoga-chat-bot/env36/lib64/python3.6/sre_parse.py", line 527, in _parse
    code1 = _class_escape(source, this)
  File "/srv/yoga-chat-bot/env36/lib64/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \p at position 257
```

**Comment by ines** [comment]
It sounds like your model is out-of-date- and incompatible. The version looks correct, but maybe you have a stale symlink somewhere? Try starting with a fresh environment and install the model from scratch.

If you can't run any of the built-in automated commands, can always check the compatibility manually: https://github.com/explosion/spacy-models/blob/master/compatibility.json This table tells you which model versions are compatible with your version of spaCy. You can then go to the "Releases" tab and download the compatible version for your installation.

**Comment by saurabhchandrapatel** [comment]
i have already check spacy and model version from 
https://github.com/explosion/spacy-models/blob/master/compatibility.json  
and its same .

spaCy Version Used: 2.1.6
and 
 "en_core_web_md": ["2.1.0"],

model meta json
```

{
  "accuracy":{
    "ents_f":86.5604666816,
    "ents_p":86.8772166864,
    "ents_r":86.2460179959,
    "las":89.9815852978,
    "tags_acc":96.9231617736,
    "token_acc":99.0697323163,
    "uas":91.7829981935
  },
  "author":"Explosion AI",
  "description":"English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl. Assigns word vectors, context-specific token vectors, POS tags, dependency parse and named entities.",
  "email":"contact@explosion.ai",
  "lang":"en",
  "license":"MIT",
  "name":"core_web_md",
  "parent_package":"spacy",
  "pipeline":[
    "tagger",
    "parser",
    "ner"
  ],
  "sources":[
    "OntoNotes 5",
    "Common Crawl"
  ],
  "spacy_version":">=2.1.0",
  "speed":{
    "cpu":7170.1448289297,
    "gpu":null,
    "nwords":291314
  },
  "url":"https://explosion.ai",
  "vectors":{
    "keys":684830,
    "name":"en_model.vectors",
    "vectors":20000,
    "width":300
  },
  "version":"2.1.0"

```

**Comment by ines** [comment]
According to your traceback, the model is loaded from a symlink (i.e. a shortcut link), not from the model Python package. 

So maybe you have a stale symlink for `en_core_web_sm` that's loaded instead and points to an old model? Can you check the `spacy/data` directory of your spaCy installation and see what's in there, and delete all symlinks?
