### ISSUE TITLE
Memory error while loading en_core_web_lg model.

### ISSUE THREAD

**Issue by balavenkatesh3322** [explosion/spaCy#4271]
I got below error while loading the spacy model.

> spacy.load('en_core_web_lg')

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 64, in _inner
    return f(*args, **kwargs)
  File "/phraze/recording/tasks.py", line 92, in notes_aws_transcribe_audio_and_medical_data_task
    followup.FollowUp().save_follow_up(appointment_id, transcript_text)
  File "/phraze/recording/followUp.py", line 76, in save_follow_up
    numeric, unit, utterance, full_utterance_array = self.extract_follow_up(data)
  File "/phraze/recording/followUp.py", line 27, in extract_follow_up
    nlp = spacy.load('en_core_web_lg')
  File "/usr/local/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.6/site-packages/spacy/util.py", line 134, in load_model
    return load_model_from_package(name, **overrides)
  File "/usr/local/lib/python3.6/site-packages/spacy/util.py", line 155, in load_model_from_package
    return cls.load(**overrides)
  File "/usr/local/lib/python3.6/site-packages/en_core_web_lg/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python3.6/site-packages/spacy/util.py", line 196, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python3.6/site-packages/spacy/util.py", line 179, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/usr/local/lib/python3.6/site-packages/spacy/language.py", line 836, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/usr/local/lib/python3.6/site-packages/spacy/util.py", line 636, in from_disk
    reader(path / key)
  File "/usr/local/lib/python3.6/site-packages/spacy/language.py", line 820, in <lambda>
    p
  File "vocab.pyx", line 453, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 431, in spacy.vectors.Vectors.from_disk
  File "/usr/local/lib/python3.6/site-packages/spacy/util.py", line 636, in from_disk
    reader(path / key)
  File "vectors.pyx", line 424, in spacy.vectors.Vectors.from_disk.load_vectors
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/format.py", line 738, in read_array
    array = numpy.fromfile(fp, dtype=dtype, count=count)
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (205449300,) and data type float32`

* Operating System:Ubuntu
* Python Version Used:3.5
* spaCy Version Used:2.1.8
* Environment Information:AWS

**Comment by BramVanroy** [comment]
You say Python 3.5, but your code reads `/usr/local/lib/python3.6/site-packages/en_core_web_lg/__init__.py`. Perhaps you're running out of memory? The model itself is 788MB so if your AWS instance only has 1GB you might run into issues. Another possibility is when you are running too many spaCy pipelines in parallel.

**Comment by balavenkatesh3322** [comment]
Thanks for responding. How much RAM size want to run the Spacy model in AWS?

**Comment by BramVanroy** [comment]
It depends on the amount of data you want to put through simultaneous, I guess. You can try with a number of different sizes. But 4Gb should be enough for texts that are not too large. (<10MB)
