### ISSUE TITLE
GreekLemmatizer has no attribute lookup

### ISSUE THREAD

**Issue by adrianeboyd** [explosion/spaCy#4272]
## How to reproduce the behaviour

```
import spacy
nlp = spacy.load('el')
doc = nlp.make_doc('Χθες')
print(doc[0].lemma_)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "token.pyx", line 860, in spacy.tokens.token.Token.lemma_.__get__
AttributeError: 'GreekLemmatizer' object has no attribute 'lookup'
```

## Your Environment

* **spaCy version:** 2.1.8
* **Platform:** Linux-4.19.0-5-amd64-x86_64-with-debian-10.0
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
It probably never worked.

Wouldn't it be better to have GreekLemmatizer extend Lemmatizer? I think that was the original problem.

```
class GreekLemmatizer(Lemmatizer):
```
