### ISSUE TITLE
Efficient GPU support for Entity Linking pipe

### ISSUE THREAD

**Issue by svlandeg** [explosion/spaCy#4281]
The new Entity Linking code has not been tested/adapted to GPU yet, cf Matt's comment [here](https://github.com/explosion/spaCy/pull/3864#issuecomment-504370194).

**Comment by zainbnv** [comment]
Yes I tried with GPU, but following error occurred:

020-03-05 03:50:46,682 - ERROR - __main__ - Error updating batch:Unsupported type <class 'numpy.ndarray'>
2020-03-05 03:50:46,694 - ERROR - __main__ - Error updating batch:Unsupported type <class 'numpy.ndarray'>
2020-03-05 03:50:46,696 - ERROR - __main__ - Error updating batch:Unsupported type <class 'numpy.ndarray'>
2020-03-05 03:50:46,707 - ERROR - __main__ - Error updating batch:Unsupported type <class 'numpy.ndarray'>
2020-03-05 03:50:46,714 - ERROR - __main__ - Error updating batch:Unsupported type <class 'numpy.ndarray'>
2020-03-05 03:50:46,723 - ERROR - __main__ - Error updating batch:Unsupported type <class 'numpy.ndarray'>
Traceback (most recent call last):
  File "./all_wiki/wikidata_train_entity_linker.py", line 194, in <module>
    plac.call(main)
  File "/home/administrator/anaconda3/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/administrator/anaconda3/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "./all_wiki/wikidata_train_entity_linker.py", line 146, in main
    logging.info("Epoch {}, train loss {}".format(itn, round(losses["entity_linker"] / batchnr, 2)))
TypeError: type cupy.core.core.ndarray doesn't define __round__ method

**Comment by svlandeg** [comment]
Update: the core EL code (i.e. not the wikipedia scripts which are outside the main library) have been tested and run on GPU, but probably not very efficiently yet. Cf https://github.com/explosion/spaCy/pull/5236
