### ISSUE TITLE
SSL error when downloading models

### ISSUE THREAD

**Issue by yutingwum** [explosion/spaCy#4297]
## Situation
I tired to download Spacy models on virtual environment with Python 3.6.5. After successfully download Spacy with the line `pip install rasa[spacy]`, I tried to download the English model with `python -m spacy download en_core_web_md`. But an SSLErrorr was raised. I looked into other similar issues including [#3066](https://github.com/explosion/spaCy/issues/3066), [#2248](https://github.com/explosion/spaCy/issues/2248), [#2212](https://github.com/explosion/spaCy/pull/2212)

I tried the following line `python3 -m spacy download en_core_web_md-2.1.8 --direct` but did not work and threw the same error as well.

Please see the below output. 

```
File "/Users/yuwu/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/Users/yuwu/venv/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yuwu/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/yuwu/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/yuwu/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/yuwu/venv/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/spacy/cli/download.py", line 38, in download
    shortcuts = get_json(about.__shortcuts__, "available shortcuts")
  File "/Users/yuwu/venv/lib/python3.6/site-packages/spacy/cli/download.py", line 84, in get_json
    r = requests.get(url)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yuwu/venv/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))
```

## Your Environment
* Anaconda is installed
* Operating System: MacOS Mojave 10.14.6
* Python Version Used: 3.6.6
* spaCy Version Used: 2.1.8 
* Environment Information: Virtual environment in Python 3.6.5. Please see the below list for packages installed and version.
```
absl-py==0.8.0
aiofiles==0.4.0
aiohttp==3.6.0
alembic==1.0.11
APScheduler==3.6.1
asn1crypto==0.24.0
astor==0.8.0
async-generator==1.10
async-timeout==3.0.1
attrs==19.1.0
blis==0.2.4
boto3==1.9.228
botocore==1.12.228
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
colorclass==2.2.0
coloredlogs==10.0
colorhash==1.0.2
ConfigArgParse==0.14.0
cryptography==2.7
cycler==0.10.0
cymem==2.0.2
decorator==4.4.0
docopt==0.6.2
docutils==0.15.2
fakeredis==1.0.5
fbmessenger==6.0.0
Flask==1.1.1
Flask-Cors==3.0.8
future==0.17.1
gast==0.3.2
gevent==1.4.0
greenlet==0.4.15
grpcio==1.23.0
h5py==2.10.0
httptools==0.0.13
humanfriendly==4.18
idna==2.8
idna-ssl==1.1.0
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.10.1
jmespath==0.9.4
jsonpickle==1.2
jsonschema==2.6.0
kafka-python==1.4.6
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Mako==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mattermostwrapper==2.1
mitie==0.7.0
mock==3.0.5
multidict==4.5.2
murmurhash==1.0.2
networkx==2.3
numpy==1.17.2
packaging==19.1
pika==1.0.1
plac==0.9.6
preshed==2.0.1
prompt-toolkit==2.0.9
protobuf==3.9.1
pycparser==2.19
pydot==1.4.1
PyJWT==1.7.1
pykwalify==1.7.0
pymongo==3.9.0
pyparsing==2.4.2
PySocks==1.7.0
python-crfsuite==0.9.6
python-dateutil==2.8.0
python-editor==1.0.4
python-engineio==3.9.3
python-socketio==4.3.1
python-telegram-bot==11.1.0
pytz==2019.2
PyYAML==5.1.2
questionary==1.3.0
rasa==1.2.8
rasa-sdk==1.2.0
rasa-x==0.20.2
redis==3.3.8
requests==2.22.0
requests-toolbelt==0.9.1
rocketchat-API==0.6.34
ruamel.yaml==0.15.100
s3transfer==0.2.1
sanic==19.3.1
Sanic-Cors==0.9.9.post1
sanic-jwt==1.3.2
Sanic-Plugins-Framework==0.8.2
scikit-learn==0.20.4
scipy==1.3.1
setuptools-scm==3.3.3
simplejson==3.16.0
six==1.12.0
sklearn-crfsuite==0.3.6
slackclient==1.3.2
sortedcontainers==2.1.0
spacy==2.1.8
SQLAlchemy==1.3.8
srsly==0.1.0
tabulate==0.8.3
tensorboard==1.13.1
tensorflow==1.13.2
tensorflow-estimator==1.13.0
termcolor==1.1.0
terminaltables==3.1.0
thinc==7.0.8
tqdm==4.35.0
twilio==6.30.0
typing-extensions==3.7.4
tzlocal==2.0.0
ujson==1.35
urllib3==1.25.3
uvloop==0.13.0
wasabi==0.2.2
wcwidth==0.1.7
webexteamssdk==1.1.1
websocket-client==0.54.0
websockets==6.0
Werkzeug==0.15.6
yarl==1.3.0
```

**Comment by ines** [comment]
Are you behind a proxy? The problem here is likely this one and happens in `requests` when spaCy is trying to fetch the shortcuts and compatibility table from GitHub over SSL. https://stackoverflow.com/questions/46604114/python-requests-ssl-error-certificate-verify-failed

I think the easiest workaround is to just download the `.tar.gz` manually via your browser and then `pip install` that file. See the [model releases](https://github.com/explosion/spacy-models) and the [models directory](https://spacy.io/models/en) (each model has a "release details" button).

Now that the `download` command is back to using `requests`, we could consider adding a `--cert` option that's passed to both `requests` (to download shortcuts and compatibility JSON files) and `pip` in the subprocess (to actually download and install the model). I'm just not sure how to best test this.

**Comment by yutingwum** [comment]
@ines  Hi Ines, thank you for your reply. I am using a corporate laptop so I guess it is behind proxy. For downloading the package to a directory, if I am using a virtual environment, what directory should I download to? Currently the Spacy folder itself is in venv/lib/spacy

**Comment by ines** [comment]
@yutingwum spaCy models are regular Python packages and the `.tar.gz` archive you download is the installer. So you can download the file to any directory. In your virtual environment, you can then `pip install` the model from the local path:

```bash
pip install /local/path/to/en_core_web_sm-2.1.0.tar.gz
```

This will automatically install the model in your Python environment, like any other package. You'll them be able to load it via `spacy.load("en_core_web_sm")`.
