### ISSUE TITLE
Getting IndexError: list index out of range

### ISSUE THREAD

**Issue by AbhayGodbole** [explosion/spaCy#4348]
Hi
I am trying to train the new NER model.  Getting following error while calling " nlp.update(texts, annotations, sgd=optimizer, drop=0.35,
				                   losses=losses)"
```
INFO : Created blank 'en' model
ERROR : Unable to process 
Error = list index out of range
Traceback (most recent call last):
  File "..\entityextractor\model.py", line 84, in trainModel
    losses=losses)
  File "c:\abhay\ai\ris-auditsupport\virris-auditsupport\lib\site-packages\spacy\language.py", line 475, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "nn_parser.pyx", line 418, in spacy.syntax.nn_parser.Parser.update
  File "_parser_model.pyx", line 214, in spacy.syntax._parser_model.ParserModel.begin_update
  File "_parser_model.pyx", line 262, in spacy.syntax._parser_model.ParserStepModel.__init__
  File "c:\abhay\ai\ris-auditsupport\virris-auditsupport\lib\site-packages\thinc\neural\_classes\feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "c:\abhay\ai\ris-auditsupport\virris-auditsupport\lib\site-packages\thinc\api.py", line 295, in begin_update
    X, bp_layer = layer.begin_update(layer.ops.flatten(seqs_in, pad=pad), drop=drop)
  File "ops.pyx", line 113, in thinc.neural.ops.Ops.flatten
IndexError: list index out of range
In [ ]:
```

I am following a standard process, which worked for my earlier project.
1. I have .tsv annotated fie, which currently have only one Entity annotated and rest is marked as "O"
2. converting this tsv to json
3. converting this json to spacy required format.
4. passing this file to train the model.

Looks like, there is some issue with the data, which I am not able to figure out, as if I provide my previous json, its working fine.

Please help 

## Info about spaCy
* **spaCy version:** 2.1.8
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.7.1

**Comment by svlandeg** [comment]
Thanks for the report! We'll look into this. Just a quick question: are you training on GPU or CPU?

**Comment by AbhayGodbole** [comment]
I am training on CPU

**Comment by AbhayGodbole** [comment]
Hi
It got solved. The issue was in Data. There were multiple full stops as part of the tokens like:
.  O
.  O
.  O
So it might be generating blank sentences while converting this to Json. When I removed this multiple occurrences, the error got fixed. 
In same use case I have one problem, which I will open another ticket for. This can be closed.

**Comment by svlandeg** [comment]
Hi @AbhayGodbole - happy to hear you got it solved. A recent patch to spacy now should also prevent this error from happening (it will automatically ignore empty batches). Thanks again for the helpful report!

**Comment by AbhayGodbole** [comment]
Great!  Thanks for the update
