### ISSUE TITLE
OverflowError 

### ISSUE THREAD

**Issue by JeremyGibson** [explosion/spaCy#436]
Version: spacy-0.101.0
Platform: Windows and Linux
Python: 2.7.10
Test File: about 14 MB text full of email text

Code:
```python

from spacy.en import English
import codecs


nlp = English()

text = codecs.open("E:\\Ubuntu\\guest_share\\test.txt", encoding='utf-8').read()
doc = nlp(text, parse=False, tag=False)

for chunk in doc.ents:
    print chunk.label_ + " :: " + chunk.orth_
```

Error:

```
Connected to pydev debugger (build 145.1617)
Traceback (most recent call last):
  File "C:\Users\jgibson\.IntelliJIdea2016.1\config\plugins\python\helpers\pydev\pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\jgibson\.IntelliJIdea2016.1\config\plugins\python\helpers\pydev\pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Development\Python\SpacyTest\spacy_test.py", line 13, in <module>
    doc = nlp(text, parse=False, tag=False)
  File "E:\pythonvenvs\NLTK\lib\site-packages\spacy\language.py", line 225, in __call__
    tokens = self.tokenizer(text)
  File "spacy/tokenizer.pyx", line 116, in spacy.tokenizer.Tokenizer.__call__ (spacy/tokenizer.cpp:4644)
    cache_hit = self._try_cache(key, tokens)
  File "spacy/tokenizer.pyx", line 147, in spacy.tokenizer.Tokenizer._try_cache (spacy/tokenizer.cpp:5290)
    tokens.push_back(cached.data.lexemes[i], False)
  File "spacy/tokens/doc.pyx", line 274, in spacy.tokens.doc.Doc.push_back (spacy/tokens/doc.cpp:8508)
    self._realloc(self.length * 2)
  File "spacy/tokens/doc.pyx", line 362, in spacy.tokens.doc.Doc._realloc (spacy/tokens/doc.cpp:9737)
    data_start = <TokenC*>self.mem.realloc(data_start, n * sizeof(TokenC))
  File "cymem/cymem.pyx", line 60, in cymem.cymem.Pool.realloc (cymem/cymem.cpp:1323)
    cdef void* new_ptr = self.alloc(1, new_size)
  File "cymem/cymem.pyx", line 42, in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1077)
    raise MemoryError("Error assigning %d bytes" % number * elem_size)
OverflowError: repeated string is too long
```

Is there a way to increase memory allocation at runtime if  this is indeed the problem?

**Comment by syllog1sm** [comment]
Sorry for not getting to this before.

It looks to me like you're asking spaCy to load all the email text as a single document. It looks like this ends up making a large allocation, due to the large number of tokens, which causes it to die.

First --- are you running 32 bit, rather than 64 bit?

Second, can you cut up your file into multiple texts, so that you can make successive calls to spaCy?

**Comment by jmgibson71** [comment]
Thanks for getting back to me.  
1) I'm running 64bit.
2) I refactored the code to feed in chunks.
