### ISSUE TITLE
SpaCy 2.2. fails to load Greek and French data models

### ISSUE THREAD

**Issue by ericmclachlan** [explosion/spaCy#4366]
SpaCy 2.2. fails to load Greek and French data models on WSL.
```python
greek = spacy.load('el_core_news_sm')
french = spacy.load('fr_core_news_sm')
```

## How to reproduce the behaviour:

```python

import spacy

print(spacy.info())

greek = spacy.load('el_core_news_sm')
french = spacy.load('fr_core_news_sm')

print("Done.")
```

Running this code via Windows Susbsytem for Linux (WSL) produces the following error output:

```
python test2.py

============================== Info about spaCy ==============================

spaCy version    2.2.0
Location         /home/ericm/.local/lib/python3.7/site-packages/spacy
Platform         Linux-4.19.67-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic
Python version   3.7.3
Models

{'spaCy version': '2.2.0', 'Location': '/home/ericm/.local/lib/python3.7/site-packages/spacy', 'Platform': 'Linux-4.19.67-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic', 'Python version': '3.7.3', 'Models': ''}
Traceback (most recent call last):
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 80, in get_lang_class
    module = importlib.import_module(".lang.%s" % lang, "spacy")
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/lang/el/__init__.py", line 9, in <module>
    from .lemmatizer import GreekLemmatizer
ImportError: cannot import name 'GreekLemmatizer' from 'spacy.lang.el.lemmatizer' (/home/ericm/.local/lib/python3.7/site-packages/spacy/lang/el/lemmatizer/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test2.py", line 6, in <module>
    greek = spacy.load('el_core_news_sm')
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 166, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 187, in load_model_from_package
    return cls.load(**overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/el_core_news_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 198, in load_model_from_path
    cls = get_lang_class(lang)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 82, in get_lang_class
    raise ImportError(Errors.E048.format(lang=lang, err=err))
ImportError: [E048] Can't import language el from spacy.lang: cannot import name 'GreekLemmatizer' from 'spacy.lang.el.lemmatizer' (/home/ericm/.local/lib/python3.7/site-packages/spacy/lang/el/lemmatizer/__init__.py)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 80, in get_lang_class
    module = importlib.import_module(".lang.%s" % lang, "spacy")
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/lang/el/__init__.py", line 9, in <module>
    from .lemmatizer import GreekLemmatizer
ImportError: cannot import name 'GreekLemmatizer' from 'spacy.lang.el.lemmatizer' (/home/ericm/.local/lib/python3.7/site-packages/spacy/lang/el/lemmatizer/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test2.py", line 6, in <module>
    greek = spacy.load('el_core_news_sm')
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 166, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 187, in load_model_from_package
    return cls.load(**overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/el_core_news_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 198, in load_model_from_path
    cls = get_lang_class(lang)
  File "/home/ericm/.local/lib/python3.7/site-packages/spacy/util.py", line 82, in get_lang_class
    raise ImportError(Errors.E048.format(lang=lang, err=err))
ImportError: [E048] Can't import language el from spacy.lang: cannot import name 'GreekLemmatizer' from 'spacy.lang.el.lemmatizer' (/home/ericm/.local/lib/python3.7/site-packages/spacy/lang/el/lemmatizer/__init__.py)
```

## Your Environment

*Windows Subsystem for Linux (WSL):*

```
spaCy version    2.2.0
Location         /home/ericm/.local/lib/python3.7/site-packages/spacy
Platform         Linux-4.19.67-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic
Python version   3.7.3
Models

{'spaCy version': '2.2.0', 'Location': '/home/ericm/.local/lib/python3.7/site-packages/spacy', 'Platform': 'Linux-4.19.67-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic', 'Python version': '3.7.3', 'Models': ''}
```

*Interestingly*, the same code running on Windows itself, does not report this error:

```sh
python .\test2.py

============================== Info about spaCy ==============================

spaCy version    2.2.0
Location         C:\Python37\lib\site-packages\spacy
Platform         Windows-10-10.0.18990-SP0
Python version   3.7.4
Models

{'spaCy version': '2.2.0', 'Location': 'C:\\Python37\\lib\\site-packages\\spacy', 'Platform': 'Windows-10-10.0.18990-SP0', 'Python version': '3.7.4', 'Models': ''}
Done.
```

**Comment by adrianeboyd** [comment]
Can you check the model versions with `spacy validate`?

**Comment by ines** [comment]
> `site-packages/spacy/lang/el/lemmatizer/__init__.py`

Hmm, I think you might have stale files in your installation? This file shouldn't exist in v2.0. Did you try reinstalling the new version in a fresh virtual environment?

**Comment by ericmclachlan** [comment]
When I ran spacy validate, all the models seemed to be 2.2.

What I'll do is I'll reset my WSL installation (it's not hard) and reinstall the required components. This should give me a more-or-less easy way to confirm whether the problem is local. I'll let you know how it goes.

**Comment by ericmclachlan** [comment]
After resetting my environment, the problem seems to have disappeared leading me to conclude that my environment must have become corrupted, somehow.

Thank you for your help. Please feel free to close the issue if you feel it's appropriate.
