### ISSUE TITLE
Bug in convert iob file to ner json format, no character after 'U' tag as entity

### ISSUE THREAD

**Issue by m-idasa** [explosion/spaCy#4385]
## Fix ner convertor for tag 'U' 
I executed the following command:
```
python3 -m spacy train fa ./model ./data/part1.json ./data/part2.json -p 'ner'
```
but it returns this error:
```
⚠ Output directory is not empty
This can lead to unintended side effects when saving the model. Please use an
empty directory or a different path instead. If the specified output path
doesn't exist, the directory will be created for you.
Training pipeline: ['ner']
Starting with blank model 'fa'
Counting training words (limit=0)

Itn  NER Loss   NER P   NER R   NER F   Token %  CPU WPS
---  ---------  ------  ------  ------  -------  -------
✔ Saved model to output directory                                               
model/model-final

Traceback (most recent call last):
  File "/home/ali/.local/lib/python3.6/site-packages/spacy/cli/train.py", line 365, in train
    losses=losses,
  File "/home/ali/.local/lib/python3.6/site-packages/spacy/language.py", line 516, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "nn_parser.pyx", line 419, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 524, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "transition_system.pyx", line 93, in spacy.syntax.transition_system.TransitionSystem.get_oracle_sequence
  File "transition_system.pyx", line 154, in spacy.syntax.transition_system.TransitionSystem.set_costs
ValueError: [E024] Could not find an optimal move to supervise the parser. Usually, this means that the model can't be updated in a way that's valid and satisfies the correct annotations specified in the GoldParse. For example, are all labels added to the model? If you're training a named entity recognizer, also make sure that none of your annotated entity spans have leading or trailing whitespace. You can also use the experimental `debug-data` command to validate your JSON-formatted training data. For details, run:
python -m spacy debug-data --help

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ali/.local/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/ali/.local/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/ali/.local/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/ali/.local/lib/python3.6/site-packages/spacy/cli/train.py", line 486, in train
    best_model_path = _collate_best_model(meta, output_path, nlp.pipe_names)
  File "/home/ali/.local/lib/python3.6/site-packages/spacy/cli/train.py", line 548, in _collate_best_model
    bests[component] = _find_best(output_path, component)
  File "/home/ali/.local/lib/python3.6/site-packages/spacy/cli/train.py", line 567, in _find_best
    accs = srsly.read_json(epoch_model / "accuracy.json")
  File "/home/ali/.local/lib/python3.6/site-packages/srsly/_json_api.py", line 50, in read_json
    file_path = force_path(location)
  File "/home/ali/.local/lib/python3.6/site-packages/srsly/util.py", line 21, in force_path
    raise ValueError("Can't read file: {}".format(location))
ValueError: Can't read file: model/model-best/accuracy.json
 ```

so I debug my data:
```
python3 -m spacy debug-data fa ./data/part1.json ./data/part2.json -p 'ner'
```
and it returns:
```
=========================== Data format validation ===========================
✔ Corpus is loadable

=============================== Training stats ===============================
Training pipeline: ner
Starting with blank model 'fa'
5 training docs
2 evaluation docs
✔ No overlap between training and evaluation data
✘ Low number of examples to train from a blank model (5)

============================== Vocab & Vectors ==============================
ℹ 14502 total words in the data (3204 unique)
ℹ No word vectors present in the model

========================== Named Entity Recognition ==========================
ℹ 6 new labels, 0 existing labels
0 missing values (tokens with '-' label)
⚠ Low number of examples for new label '' (2)
✔ Examples without occurrences available for all labels
✔ No entities consisting of or starting/ending with whitespace

================================== Summary ==================================
✔ 4 checks passed
⚠ 1 warning
✘ 1 error
``` 
and I had ')' and '،' as label too in other input data. Then I checked out library and guess maybe there is a 'B' tag without entity label but there was no wrong sample in input data too.

I have also used large data, but it returns the same warning.

* Operating System: ubuntu 18.04.3 LTS
* Python Version Used: 3.6
* spaCy Version Used: 2.2.1

**Comment by adrianeboyd** [comment]
Can you provide an example from your original data that leads to this problem (anonymized if needed, of course) and the command that you used to convert the data? There definitely shouldn't be an empty label like `''` in the data.

**Comment by m-idasa** [comment]
you can see my input files here:
[part1.txt](https://github.com/explosion/spaCy/files/3749292/part1.txt)
[part2.txt](https://github.com/explosion/spaCy/files/3749293/part2.txt)

There is no empty label in them.

**Comment by adrianeboyd** [comment]
Thanks, example data makes it a lot easier to figure out what's going on. I think the problem is spaces in some of the tokens like `: "` on line 7126 of `part1.txt`. The converter splits columns on whitespace (since this format can potentially have space or tab delimiters), so it aligns the `"` with the column of IOB tags, leading to the ill-formed `U-` tag here.

It would be possible to modify the converter to detect tabs vs. spaces and only split on tabs if there are tabs present, but I'm not sure I want to make it more complicated.

Are the spaces in the tokens present in the original data or just a formatting issue in your annotated data?

In any case, the IOB->BILUO converter should definitely produce an error here rather than `U-`.
