### ISSUE TITLE
spacy.load('en_biobio') error

### ISSUE THREAD

**Issue by dhwani2410** [explosion/spaCy#4400]
>>> import spacy
>>> nlp = spacy.load('en_biobio')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dhwani/.local/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/dhwani/.local/lib/python3.6/site-packages/spacy/util.py", line 131, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/dhwani/.local/lib/python3.6/site-packages/spacy/util.py", line 152, in load_model_from_package
    return cls.load(**overrides)
  File "/usr/local/lib/python3.6/dist-packages/en_biobio/__init__.py", line 58, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/dhwani/.local/lib/python3.6/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/dhwani/.local/lib/python3.6/site-packages/spacy/util.py", line 171, in load_model_from_path
    component = nlp.create_pipe(name, config=config)
  File "/home/dhwani/.local/lib/python3.6/site-packages/spacy/language.py", line 256, in create_pipe
    raise KeyError(Errors.E108.format(name=name))
KeyError: "[E108] As of spaCy v2.1, the pipe name `sbd` has been deprecated in favor of the pipe name `sentencizer`, which does the same thing. For example, use `nlp.create_pipeline('sentencizer')`"

* **spaCy version:** 2.1.4
* **Platform:** Linux-4.15.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.8

**Comment by svlandeg** [comment]
It looks like you may be trying to load an `nlp` model that was created on an older version of spaCy? `en_biobio` is calling `nlp.create_pipeline('sbd')`  but that is deprecated now, and should become `nlp.create_pipeline('sentencizer')`.

Unfortunately across major releases you usually need to update your models.

While you're at it, I would suggest upgrading to spaCy 2.2.1 which was released recently!

**Comment by dhwani2410** [comment]
Even after the update, I am getting the same error. Can you please suggest how to update the model

**Comment by svlandeg** [comment]
Yes, so after updating spaCy itself, you'll actually have to recreate / retrain your models as well. I'm assuming at some point someone created a model called `en_biobio` and wrote that to file, which is what you're trying to reuse now. So you'll have to create a new version of that `en_biobio` pipeline.
