### ISSUE TITLE
KeyError: 'labels'  using textcat on the train CLI

### ISSUE THREAD

**Issue by louisguitton** [explosion/spaCy#4504]
## How to reproduce the behaviour

I've searched the repo for similar issues and I couldn't find anything so here comes nothing:
I've read #4038 and #4226 and am very eager to use that feature. But when I try it, I get an error.

- download the example data from the PR
```bash
curl https://raw.githubusercontent.com/adrianeboyd/spaCy/50179e19ae5b600eeb959ee71d102fdf859aada8/examples/training/textcat_example_data/cooking.json > data/cooking.json
``` 
- use the train CLI to train a textcat model
```bash
→ python -m spacy train en data/rules_investigation/output data/rules_investigation/cooking.json data/rules_investigation/cooking.json --base-model en_core_web_md --pipeline textcat --textcat-arch ensemble
Training pipeline: ['textcat']
Starting with base model 'en_core_web_md'
Counting training words (limit=0)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/louis.guitton/workspace/my-secret-project/venv/lib/python3.7/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/louis.guitton/workspace/my-secret-project/venv/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/louis.guitton/workspace/my-secret-project/venv/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/louis.guitton/workspace/my-secret-project/venv/lib/python3.7/site-packages/spacy/cli/train.py", line 251, in train
    textcat_labels = nlp.get_pipe("textcat").cfg["labels"]
KeyError: 'labels
```

From what I understand, the code is missing the step that you would do usually with:
```python
textcat = nlp.get_pipe("textcat")
for cat in ALL_LABELS:
    textcat.add_label(cat)
```
so because `labels` are never set, `textcat_labels = nlp.get_pipe("textcat").cfg["labels"]` is failing.
Am I missing something ? 
(PS: I was able to train the textcat model writing some python basically adapting [this](https://spacy.io/usage/training#textcat) but I'd love to use that CLI feature)

## Your Environment

* Operating System: MacOS
* Python Version Used: Python 3.7.4
* spaCy Version Used: 2.2.1
* Environment Information:

```bash
→ python -m spacy info                                                                                                                                                       
============================== Info about spaCy ==============================

spaCy version    2.2.1
Location         /Users/louis.guitton/workspace/my-secret-project/venv/lib/python3.7/site-packages/spacy
Platform         Darwin-18.7.0-x86_64-i386-64bit
Python version   3.7.4
Models
```

**Comment by adrianeboyd** [comment]
This error message could be better! The problem is that the base model doesn't already contain a textcat model, so when it tries to read the existing textcat labels from the base model, it fails.

You probably want to use `-v` to load the vectors from the model, but you don't want `-b`, since you're not extending an existing model component.

**Comment by louisguitton** [comment]
That's exactly it. Thanks for the quick response and for the work on that feature.
