### ISSUE TITLE
Model linked but not available

### ISSUE THREAD

**Issue by jimbudarz** [explosion/spaCy#4545]
## How to reproduce the behaviour

Hello, due to work network restrictions, I cannot use `python -m download...`, so I use a downloaded model and just try to link it. However, although it links successfully, it is not available in my environment (and isn't reflected in SpaCy info).

$ python -m spacy link ./en_core_web_md-2.1.0.tar.gz en

    Linking successful
    Documents/SPACY_en_Models/en_core_web_md-2.1.0.tar.gz
    --> /Users/username/anaconda3/lib/python3.7/site-packages/spacy/data/en

    You can now load the model via spacy.load('en')

$ python -m spacy info

    Info about spaCy

    spaCy version      2.0.12         
    Location           /Users/username/anaconda3/lib/python3.7/site-packages/spacy
    Platform           Darwin-18.7.0-x86_64-i386-64bit
    Python version     3.7.3          
    Models                            

## Your Environment

* Operating System: Mac OSX Mojave
* Python Version Used: 3.7.3
* spaCy Version Used: 2.0.12
* Environment Information:

**Comment by ines** [comment]
I think the problem here might be that you've linked the `.tar.gz` archive instead of the package name of the installed model (e.g. `en_core_web_md`), or the model data directory [see here](https://spacy.io/usage/models#download-manual).

spaCy should probably check this and complain when you run the `link` command (I thought it already did this, but apparently not).

**Comment by jimbudarz** [comment]
Thanks for the help. After pip installing the model, then linking the package name works.

$ python -m spacy link en_core_web_md en --force

    Linking successful
    /Users/jbudarz/anaconda3/lib/python3.7/site-packages/en_core_web_md -->
    /Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/data/en

    You can now load the model via spacy.load('en')

python -m spacy info

    Info about spaCy

    spaCy version      2.0.12         
    Location           /Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy
    Platform           Darwin-18.7.0-x86_64-i386-64bit
    Python version     3.7.3          
    Models             en

**Comment by jimbudarz** [comment]
However, when trying to load the model with Python I still get an error:

`import spacy`

`nlp = spacy.load("en_core_web_md")`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 116, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 143, in load_model_from_path
    cls = get_lang_class(meta['lang'])
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 50, in get_lang_class
    module = importlib.import_module('.lang.%s' % lang, 'spacy')
  File "/Users/username/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/lang/en/__init__.py", line 15, in <module>
    from ...language import Language
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 18, in <module>
    from .pipeline import DependencyParser, Tensorizer, Tagger, EntityRecognizer
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/pipeline/__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 1, in init spacy.pipeline.pipes
ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject
>>> nlp = spacy.load("en_core_web_md")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 126, in load_model_from_link
    cls = import_file(name, path)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/spacy/compat.py", line 118, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/anaconda3/lib/python3.7/site-packages/spacy/data/en_core_web_md/__init__.py'
`

**Comment by jimbudarz** [comment]
Thinking I should use "en" as the model name, I'm trying `spacy.load("en")`, but that gives a different error:

```
nlp = spacy.load("en")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 143, in load_model_from_path
    cls = get_lang_class(meta['lang'])
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 50, in get_lang_class
    module = importlib.import_module('.lang.%s' % lang, 'spacy')
  File "/Users/jbudarz/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/lang/en/__init__.py", line 15, in <module>
    from ...language import Language
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 18, in <module>
    from .pipeline import DependencyParser, Tensorizer, Tagger, EntityRecognizer
  File "/Users/jbudarz/anaconda3/lib/python3.7/site-packages/spacy/pipeline/__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 1, in init spacy.pipeline.pipes
ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject
```
