### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by miguelwon** [explosion/spaCy#4552]
I have two files (train and test) in conll format and converted to spacy json format with `python -m convert`:

```
python -m spacy convert train.conll . -c ner
python -m spacy convert train.conll . -c ner
```

I show bellow the content of `train.conll` and `test.conll`. 

Then I upload these files with `GoldCorpus`:

```
import spacy 
nlp = spacy.load('pt_core_news_sm')
from spacy.gold import GoldCorpus

goldcorpus = GoldCorpus("train.json","teste.json")
train_docs = corpus.train_docs(nlp,gold_preproc = True)
```

and now if I try to loop over `train_docs`, I get an error:

```
>>> train_docs = list(train_docs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gold.pyx", line 222, in train_docs
  File "gold.pyx", line 240, in iter_gold_docs
  File "gold.pyx", line 258, in spacy.gold.GoldCorpus._make_docs
ValueError: need more than 0 values to unpack
```

## Info about spaCy
* **spaCy version:** 2.2.1
* **Platform:** Linux-4.4.0-140-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.7

## train.conll
```
-DOCSTART- -X- O O

- PNT _ O
« PNT _ O
A DA _ O
menina CN _ O
dos PREP+DA _ O
rouxinóis CN _ O
? PNT _ O

A DA _ O
Leasimpor PNM _ O
- PNT _ O
Companhia PNM _ O
de PREP _ O
Locação PNM _ O
Financeira PNM _ O
Imobiliária PNM _ O
, PNT _ O
vai V _ O
distribuir INF _ O
um UM _ O
juro CN _ O
líquido ADJ _ O
no PREP+DA _ O
valor CN _ O
de PREP _ O
158 DGT _ O
$ SYB _ O
75 DGT _ O
, PNT _ O
referente ADJ _ O
ao PREP+DA _ O
pagamento CN _ O
do PREP+DA _ O
cupão CN _ O
Nº CN _ O
1 DGT _ O
do PREP+DA _ O
empréstimo CN _ O
Obrigações PNM _ O
de PREP _ O
Caixa PNM _ O
Leasimpor PNM _ O
96 DGT _ O
. PNT _ O

Os DA _ O
centros CN _ O
de PREP _ O
diálise CN _ O
privados PPA _ O
tratam V _ O
cerca ADV _ O
de PREP _ O
4500 DGT _ O
dos PREP+DA _ O
5500 DGT _ O
insuficientes ADJ _ O
renais ADJ _ O
crónicos ADJ _ O
existentes ADJ _ O
em PREP _ O
Portugal PNM _ O
. PNT _ O

As DA _ O
infecções CN _ O
nos PREP+DA _ O
frutos CN _ O
são V _ O
frequentes ADJ _ O
quando CJ _ O
chuvas CN _ O
antecedem V _ O
a DA _ O
colheita CN _ O
. PNT _ O
```

## test.conll
```
 -DOCSTART- -X- O O

" PNT _ O
Tenho V _ O
dois CARD _ O
irmãos CN _ O
mais ADV _ O
novos ADJ _ O
e CJ _ O
raramente ADV _ O
os CL _ O
vejo V _ O
, PNT _ O
porque CJ _ O
estou V _ O
quase ADV _ O
sempre ADV _ O
fora ADV _ O
. PNT _ O

Faça V _ O
de PREP _ O
conta CN _ O
que CJ _ O
eu PRS _ O
sou V _ O
uma UM _ O
desgraçada PPA _ O
, PNT _ O
que REL _ O
vai V _ O
ganhar INF _ O
seis CARD _ O
vinténs CN _ O
com PREP _ O
este DEM _ O
baú CN _ O
à PREP+DA _ O
cabeça CN _ O
. PNT _ O

- PNT _ O
Não ADV _ O
, PNT _ O
não ADV _ O
está V _ O
enganado PPA _ O
. PNT _ O

Minha POSS _ O
irmã CN _ O
, PNT _ O
que REL _ O
eu PRS _ O
deixara V _ O
viçosa ADJ _ O
e CJ _ O
bela ADJ _ O
com PREP _ O
duas CARD _ O
crianças CN _ O
a PREP _ O
brincarem INF _ O
brincarem-lhe INF _ O
no PREP+DA _ O
regaço CN _ O
, PNT _ O
mostrou V _ O
mostrou-me V _ O
a DA _ O
filha CN _ O
em PREP _ O
projectos CN _ O
de PREP _ O
casamento CN _ O
, PNT _ O
e CJ _ O
o DA _ O
filho CN _ O
, PNT _ O
pouco ADV _ O
depois PREP _ O
, PNT _ O
académico CN _ O
do PREP+DA _ O
primeiro ORD _ O
ano CN _ O
jurídico ADJ _ O
. PNT _ O
```

**Comment by adrianeboyd** [comment]
This is a bug related to `gold_preproc`. (See #4402.) There's a fix already applied to master, but if you don't want compile spacy from source, the latest release where this is working is v2.1.9.

Based on your sample data, you probably don't want to use `gold_preproc`, though. If you don't have the raw texts in your data, `gold_preproc` isn't a very useful option and training without `gold_preproc` should work fine with v2.2.1.
