### ISSUE TITLE
error on debug-data

### ISSUE THREAD

**Issue by ramilrg** [explosion/spaCy#4558]
## How to reproduce the behaviour

sometimes I am getting an error when running a spacy debug-data check, how to fix it?

> ============ Data format validation ===============
⠴ Loading corpus...
Traceback (most recent call last):
  File "G:\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "G:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\Python35\lib\site-packages\spacy\__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "G:\Python35\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "G:\Python35\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "G:\Python35\lib\site-packages\spacy\cli\debug_data.py", line 83, in debug_data
    train_docs = list(corpus.train_docs(nlp))
  File "gold.pyx", line 222, in train_docs
  File "gold.pyx", line 243, in iter_gold_docs
  File "gold.pyx", line 266, in spacy.gold.GoldCorpus._make_golds
  File "gold.pyx", line 541, in spacy.gold.GoldParse.from_annot_tuples
  File "gold.pyx", line 621, in spacy.gold.GoldParse.__init__
  File "nonproj.pyx", line 123, in spacy.syntax.nonproj.projectivize
  File "nonproj.pyx", line 172, in spacy.syntax.nonproj._get_smallest_nonproj_arc
  File "nonproj.pyx", line 58, in spacy.syntax.nonproj.is_nonproj_arc
  File "nonproj.pyx", line 26, in ancestors
IndexError: list index out of range

 

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.5
* spaCy Version Used: 2.2.1
* Environment Information:

**Comment by svlandeg** [comment]
Hi @ramilrg, sorry to hear you're running into troubles!

We recently made some patches to this functionality. Could you try building `spaCy` [from source](https://github.com/explosion/spaCy#compile-from-source) and verify whether the error is still there? 

If that's not an option for you, you could either wait until the next minor release and check with that, or you could create a minimal working code snippet (with example data) that produces this error on your system, and then we can check whether our recent patches fixes it.
