### ISSUE TITLE
Training NER fails

### ISSUE THREAD

**Issue by sudeshna-d** [explosion/spaCy#4575]
## How to reproduce the behaviour
I am trying to train spacy on CoNLL 2003 NER data. I used the CLI convertor to convert from conll to spacy format.

`python -m spacy convert eng.train . -c ner` for all 3 files: train, dev and test and renamed the files to .json

To train, I am using this command:
`python -m spacy train en scner/ engtrain.json engtesta.json -p ner -VV -D`

```
Itn  NER Loss   NER P   NER R   NER F   Token %  CPU WPS
---  ---------  ------  ------  ------  -------  -------
✔ Saved model to output directory
scner3/model-final
```

I am getting this error:

```
Traceback (most recent call last):
  File "/home/su/.env/lib/python3.5/site-packages/spacy/cli/train.py", line 397, in train
    scorer = nlp_loaded.evaluate(dev_docs, verbose=verbose)
  File "/home/su/.env/lib/python3.5/site-packages/spacy/language.py", line 672, in evaluate
    docs, golds = zip(*docs_golds)
ValueError: not enough values to unpack (expected 2, got 0)
```

Running the debug-data command
`python3 -m spacy debug-data en engtrain.json engtesta.json`

gives me this:

```
=========================== Data format validation ===========================
✔ Corpus is loadable

=============================== Training stats ===============================
Training pipeline: tagger, parser, ner
Starting with blank model 'en'
946 training docs
0 evaluation docs
✔ No overlap between training and evaluation data
⚠ Low number of examples to train from a blank model (946)

============================== Vocab & Vectors ==============================
ℹ 203621 total words in the data (23623 unique)
ℹ No word vectors present in the model

========================== Named Entity Recognition ==========================
ℹ 4 new labels, 0 existing labels
0 missing values (tokens with '-' label)
✔ Good amount of examples for all labels
✔ Examples without occurrences available for all labels
✔ No entities consisting of or starting/ending with whitespace

=========================== Part-of-speech Tagging ===========================
ℹ 45 labels in data (57 labels in tag map)
✘ Label ')' not found in tag map for language 'en'
✘ Label '(' not found in tag map for language 'en'
✘ Label 'NN|SYM' not found in tag map for language 'en'
✘ Label '"' not found in tag map for language 'en'

============================= Dependency Parsing =============================
ℹ Found 203621 sentences with an average length of 1.0 words.
ℹ 1 label in train data
ℹ 1 label in projectivized train data

================================== Summary ==================================
✔ 5 checks passed
⚠ 2 warnings
✘ 4 errors
```

## Your Environment

* **Models:** en_core_web_lg
* **Python version:** 3.5.2
* **Platform:** Linux-4.15.0-58-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.2.2

I am trying to train the model only on NER, not on POS.

**Comment by adrianeboyd** [comment]
If the conversion with `spacy convert` works correctly you shouldn't have to rename the files to `.json`, so maybe something isn't configured correctly there. It should be the default, but you can also try explicitly adding `-t json`.

The NER summary from `debug-data` looks okay, but this is your immediate problem:

```
0 evaluation docs
```

There should be a clear error in `debug-data` for this case, since it will cause the problem with the evaluation above.
