### ISSUE TITLE
importing a binary word vectoring model complains abouy unicoding

### ISSUE THREAD

**Issue by VahidTehrani** [explosion/spaCy#4586]
## How to reproduce the behaviour

python -m spacy init-model en /tmp/BioWordVec --vectors-loc /home/vahid/Downloads/BioWordVec_PubMed_MIMICIII_d200.bin

✔ Successfully created model
⠙ Reading vectors from /home/vahid/Downloads/BioWordVec_PubMed_MIMICIII_d200.bin
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vahid/myProgs/python-venvs/python3.6/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/vahid/myProgs/python-venvs/python3.6/lib/python3.6/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/home/vahid/myProgs/python-venvs/python3.6/lib/python3.6/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/vahid/myProgs/python-venvs/python3.6/lib/python3.6/site-packages/spacy/cli/init_model.py", line 90, in init_model
    add_vectors(nlp, vectors_loc, prune_vectors, vectors_name)
  File "/home/vahid/myProgs/python-venvs/python3.6/lib/python3.6/site-packages/spacy/cli/init_model.py", line 184, in add_vectors
    vectors_data, vector_keys = read_vectors(vectors_loc)
  File "/home/vahid/myProgs/python-venvs/python3.6/lib/python3.6/site-packages/spacy/cli/init_model.py", line 209, in read_vectors
    shape = tuple(int(size) for size in next(f).split())
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

## Info about spaCy

* **spaCy version:** 2.2.2
* **Platform:** Linux-4.15.0-64-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.8

Does it mean init-model doesn't support binary models? or something else?

**Comment by adrianeboyd** [comment]
`init-model` only supports text format at this point. From the docs (https://spacy.io/api/cli#init-model):

"Should be a file where the first row contains the  dimensions of the vectors, followed by a space-separated Word2Vec table.  File can be provided in .txt format or as a zipped text file in .zip or .tar.gz format."
