### ISSUE TITLE
TypeError: Model() takes exactly 1 positional argument (0 given) in from_disk for Parser

### ISSUE THREAD

**Issue by kabirkhan** [explosion/spaCy#4658]
## How to reproduce the behaviour

Running

```python
import spacy

nlp = spacy.load('my_custom_ner_model')
```

Gets the following traceback

```
Traceback (most recent call last):
  File "evaluate_model.py", line 28, in <module>
    plac.call(evaluate)
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/.spacy2.2-venv/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/.spacy2.2-venv/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "evaluate_model.py", line 16, in evaluate
    skills_model = EntityRecognizer(model_path=model, input_text_col="text", input_id_col="id")
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/src/skills_ner/pipeline.py", line 40, in __init__
    self.nlp = self.load_model()
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/src/skills_ner/pipeline.py", line 111, in load_model
    nlp = spacy.load(read_folder)
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/.spacy2.2-venv/lib/python3.6/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/.spacy2.2-venv/lib/python3.6/site-packages/spacy/util.py", line 217, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/.spacy2.2-venv/lib/python3.6/site-packages/spacy/util.py", line 262, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/.spacy2.2-venv/lib/python3.6/site-packages/spacy/language.py", line 940, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/.spacy2.2-venv/lib/python3.6/site-packages/spacy/util.py", line 733, in from_disk
    reader(path / key)
  File "/mnt/c/Users/kakh/Documents/CognitiveServices/API-TextAnalytics-NER.CloudServices/.spacy2.2-venv/lib/python3.6/site-packages/spacy/language.py", line 935, in <lambda>
    p, exclude=["vocab"]
  File "nn_parser.pyx", line 657, in spacy.syntax.nn_parser.Parser.from_disk
  File "nn_parser.pyx", line 55, in spacy.syntax.nn_parser.Parser.Model
TypeError: Model() takes exactly 1 positional argument (0 given)
```

The parser from_disk method doesn't initialize the Model with the nr_class argument.
Looks like: https://github.com/explosion/spaCy/issues/3221 is essentially the same issue.

I'd fix this myself in a PR but the default arg of 1 seems obvious for textcat, less obvious what it should be for the parser since it might be different between the Parser and EntityRecognizer. 

## Your Environment

* Operating System: Windows Subsystem Linux (18.04)
* Python Version Used: 3.6
* spaCy Version Used: 2.2.2
* Environment Information:

**Comment by adrianeboyd** [comment]
I'm not sure whether this is a bug or more of a usage issue, since I don't understand why we wouldn't have ever seen this error with our provided NER models.

How did you train and save your model? What does `cfg` look like in your saved model? I would have expected the `cfg` for an NER model to always include `nr_class`.
