### ISSUE TITLE
Packing spacy console application using Pyinstaller throws error?

### ISSUE THREAD

**Issue by AbhishekKargawal** [explosion/spaCy#4683]
I have trained a spacy ner model and using the trained model in console application to predict the entities.
When I run the application from IDE(PyCharm), it runs smoothly no error, properly loads the Spacy model predict the entities and all. But when I convert this application to executable file and try to run it. It throws me an error. I have attached screenshot of the error.

I believe that https://github.com/explosion/spaCy/issues/2536 this issue is similar to mine. But not able to resolve it.

Operating system: Windows
Python: 3.7
Spacy: 2.2.1

![1](https://user-images.githubusercontent.com/19729714/69260393-b7df3200-0bb7-11ea-9c5b-427687448ca5.PNG)

**Comment by balaa** [comment]
Do you  have  the  hook  file for srsly package ?

**Comment by AbhishekKargawal** [comment]
> Do you have the hook file for srsly package ?

Yes I have tried adding hook code as well. But then I get different error.

Error after hook code:
Traceback (most recent call last):
  File "Demo.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/abhishekkargawal/Documents/WorkPlace - Primority/Temp/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "PyInstaller/__init__.py", line 66, in <module>
  File "setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 472, in get_distribution
  File "setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 344, in get_provider
  File "setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 892, in require
  File "setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 778, in resolve
pkg_resources.DistributionNotFound: The 'PyInstaller' distribution was not found and is required by the application
[5573] Failed to execute script Demo

----------------------------------------------------------------------------
Full code is here:

from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files("en_core_web_sm")

import spacy
# spacy.prefer_gpu()
nlp = spacy.load("en_core_web_sm")

doc = nlp('London is a city.')
print("Entities", [(ent.text, ent.label_) for ent in doc.ents])

**Comment by ines** [comment]
> ```
> pkg_resources.DistributionNotFound: The 'PyInstaller' distribution was not found and is required by the application
> ```

This looks more like a problem with `PyInstaller` and how it's configured? People have definitely managed to successfully package spaCy with PyInstaller, so I think it just comes down to the configuration.

**Comment by BLKSerene** [comment]
You need to configure the hidden imports for spaCy and add data files manually for spaCy and its models. The settings differs for each new version of spaCy, so you need to update your packaging script every time as well, or you may refer to [my packaging script](https://github.com/BLKSerene/Wordless/blob/master/wordless_packaging.spec) (currently for spaCy 2.2.3) used in my project.

**Comment by AbhishekKargawal** [comment]
@BLKSerene Seems like the perfect solution. I will update here if this works.
