### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by ahmedbr** [explosion/spaCy#4733]
The error occurs after installation and running the following command for checking the validation:
`python -m spacy validate`

```bash
(venv) C:\Users\user_profile\Desktop\new_pro>python -m spacy validate
Traceback (most recent call last):
  File "C:\Users\user_profile\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\user_profile\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\user_profile\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\user_profile\Desktop\new_pro\venv\lib\site-packages\spacy\__init__.py", line 12, in <module>
    from . import pipeline
  File "C:\Users\user_profile\Desktop\new_pro\venv\lib\site-packages\spacy\pipeline\__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 1, in init spacy.pipeline.pipes
ImportError: DLL load failed: The specified module could not be found.

```

## Your Environment

* Operating System: Windows 10 Pro N
* Python Version Used: 3.6.6
* spaCy Version Used: 2.2.3
* Environment Information: The result of running `python -m spacy info --markdown` is the same error message included above.

**Comment by adrianeboyd** [comment]
Hi, it looks like spacy didn't get installed correctly, but it's hard to debug without knowing more details. Our best advice is to try installing spacy again in a new virtual environment. If you see any error messages while installing, copy the install commands and errors below and that can help us figure out what might be going on.

**Comment by ahmedbr** [comment]
> Hi, it looks like spacy didn't get installed correctly, but it's hard to debug without knowing more details. Our best advice is to try installing spacy again in a new virtual environment. If you see any error messages while installing, copy the install commands and errors below and that can help us figure out what might be going on.

Actually I'm already working on a virtual environment as you can see. 
There are no errors occur during the installation phase. Current error message appears right after typing the command of validation. It also appears when trying to use spacy in the code. I've uninstalled and re-installed spacy over and over again but without any positive results.

**Comment by adrianeboyd** [comment]
Have you tried installing in a new virtual environment? Often that avoids conflicts with older installations / other packages.

**Comment by ahmedbr** [comment]
> Have you tried installing in a new virtual environment? Often that avoids conflicts with older installations / other packages.

I'm ALREADY doing so as I clarified in replies above.

**Comment by adrianeboyd** [comment]
It is hard to help without more information. The only other common problem I can think of is to check that you have 64-bit python and not 32-bit python.

If that's not the issue, please provide more information about how you are installing spacy, the complete install logs, and which packages / version are installed (`pip list`).

**Comment by ahmedbr** [comment]
**Python Version User:**
```
(venv) C:\Users\user_profile\Desktop\spaCy-RFQ-text-extraction>python --version
Python 3.6.6

```

**spacy installation message:**
```
(venv) C:\Users\user_profile\Desktop\spaCy-RFQ-text-extraction>pip install -U spacy
Collecting spacy
  Using cached https://files.pythonhosted.org/packages/6b/51/49ebcacc4d33330402c0827297780e2cbd0bb5354652093f83dc57247eef/spacy-2.2.3-cp36-cp36m-win_amd64.whl
Requirement already satisfied, skipping upgrade: requests<3.0.0,>=2.13.0 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (2.22.0)
Requirement already satisfied, skipping upgrade: cymem<2.1.0,>=2.0.2 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (2.0.3)
Requirement already satisfied, skipping upgrade: setuptools in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages\setuptools-40.8.0-py3.6.egg (from spacy) (40.8.
0)
Requirement already satisfied, skipping upgrade: numpy>=1.15.0 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (1.17.4)
Requirement already satisfied, skipping upgrade: srsly<1.1.0,>=0.1.0 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (0.2.0)
Requirement already satisfied, skipping upgrade: preshed<3.1.0,>=3.0.2 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (3.0.2)
Requirement already satisfied, skipping upgrade: catalogue<1.1.0,>=0.0.7 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (0.0.8)
Requirement already satisfied, skipping upgrade: plac<1.2.0,>=0.9.6 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied, skipping upgrade: thinc<7.4.0,>=7.3.0 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (7.3.1)
Requirement already satisfied, skipping upgrade: blis<0.5.0,>=0.4.0 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied, skipping upgrade: murmurhash<1.1.0,>=0.28.0 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (1.0.2)
Requirement already satisfied, skipping upgrade: wasabi<1.1.0,>=0.4.0 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from spacy) (0.4.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (
2019.11.28)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.8)

Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy
) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from requests<3.0
.0,>=2.13.0->spacy) (1.25.7)
Requirement already satisfied, skipping upgrade: importlib-metadata>=0.20; python_version < "3.8" in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from cat
alogue<1.1.0,>=0.0.7->spacy) (0.23)
Requirement already satisfied, skipping upgrade: tqdm<5.0.0,>=4.10.0 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from thinc<7.4.0,>=7.3.0->spacy) (4.3
9.0)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from importlib-metadata>=0.20; python_version <
 "3.8"->catalogue<1.1.0,>=0.0.7->spacy) (0.6.0)
Requirement already satisfied, skipping upgrade: more-itertools in c:\users\user_profile\desktop\spacy-rfq-text-extraction\venv\lib\site-packages (from zipp>=0.5->importlib-metadata>=0.20;
python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy) (7.2.0)
Installing collected packages: spacy
Successfully installed spacy-2.2.3
```

**spacy validation:**

```
(venv) C:\Users\user_profile\Desktop\spaCy-RFQ-text-extraction>python -m spacy validate
Traceback (most recent call last):
  File "C:\Users\user_profile\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\user_profile\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\user_profile\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\user_profile\Desktop\spaCy-RFQ-text-extraction\venv\lib\site-packages\spacy\__init__.py", line 12, in <module>
    from . import pipeline
  File "C:\Users\user_profile\Desktop\spaCy-RFQ-text-extraction\venv\lib\site-packages\spacy\pipeline\__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 1, in init spacy.pipeline.pipes
ImportError: DLL load failed: The specified module could not be found.

```

**pip list:**

(venv) C:\Users\user_profile\Desktop\spaCy-RFQ-text-extraction>pip list
Package            Version
------------------ ----------
blis               0.4.1
catalogue          0.0.8
certifi            2019.11.28
chardet            3.0.4
cymem              2.0.3
idna               2.8
importlib-metadata 0.23
more-itertools     7.2.0
murmurhash         1.0.2
numpy              1.17.4
pandas             0.25.3
pip                19.0.3
plac               1.1.3
preshed            3.0.2
python-dateutil    2.8.1
pytz               2019.3
requests           2.22.0
setuptools         40.8.0
six                1.13.0
spacy              2.2.3
srsly              0.2.0
thinc              7.3.1
tqdm               4.39.0
urllib3            1.25.7
wasabi             0.4.0
zipp               0.6.0

I'm using python 3.6.6 64-bit on another windows machine too and everything is okay there. But I'm running into troubles on the new 64-bit windows machine.

**Comment by ahmedbr** [comment]
It seems that the problem has been solved after the nth time of uninstallation and re-installation, without any knowing the main reason of this failure at the beginning.
Thanks :)
