### ISSUE TITLE
cupy.cuda.cublas.CUBLASError: CUBLAS_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#4798]
After installing spacy 2.2.3 using this command `pip install -U spacy[cuda90]` I get the following error when I run my training script

## Error

Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy223\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Anaconda\envs\spacy223\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\SOURCECODE\GitRepositories\Named Entity Recognition\ner_train.py", line 95, in worker
    nlp.begin_training()
  File "D:\Anaconda\envs\spacy223\lib\site-packages\spacy\language.py", line 624, in begin_training
    **kwargs
  File "nn_parser.pyx", line 632, in spacy.syntax.nn_parser.Parser.begin_training
  File "_parser_model.pyx", line 276, in spacy.syntax._parser_model.ParserModel.begin_training
  File "D:\Anaconda\envs\spacy223\lib\site-packages\thinc\check.py", line 156, in checked_function
    return wrapped(*args, **kwargs)
  File "D:\Anaconda\envs\spacy223\lib\site-packages\thinc\neural\_classes\model.py", line 124, in begin_training
    hook(self, train_X, train_y)
  File "D:\Anaconda\envs\spacy223\lib\site-packages\spacy\_ml.py", line 151, in <lambda>
    _set_dimensions_if_needed, lambda model, X, y: model.init_weights(model)
  File "D:\Anaconda\envs\spacy223\lib\site-packages\spacy\_ml.py", line 270, in init_weights
    acts1 = predict(ids, tokvecs)
  File "D:\Anaconda\envs\spacy223\lib\site-packages\spacy\_ml.py", line 250, in predict
    hiddens = model(tokvecs[:-1])  # (nW, f, o, p)
  File "D:\Anaconda\envs\spacy223\lib\site-packages\thinc\neural\_classes\model.py", line 169, in __call__
    return self.predict(x)
  File "D:\Anaconda\envs\spacy223\lib\site-packages\thinc\neural\_classes\model.py", line 133, in predict
    y, _ = self.begin_update(X, drop=None)
  File "D:\Anaconda\envs\spacy223\lib\site-packages\spacy\_ml.py", line 179, in begin_update
    X, self.W.reshape((self.nF * self.nO * self.nP, self.nI)), trans2=True
  File "ops.pyx", line 986, in thinc.neural.ops.CupyOps.gemm
  File "D:\Anaconda\envs\spacy223\lib\site-packages\cupy\linalg\product.py", line 35, in dot
    return a.dot(b, out)
  File "cupy\core\core.pyx", line 1364, in cupy.core.core.ndarray.dot
  File "cupy\core\core.pyx", line 2250, in cupy.core.core.dot
  File "cupy\core\core.pyx", line 2619, in cupy.core.core.tensordot_core
  File "cupy\cuda\device.pyx", line 44, in cupy.cuda.device.get_cublas_handle
  File "cupy\cuda\device.pyx", line 45, in cupy.cuda.device.get_cublas_handle
  File "cupy\cuda\device.pyx", line 204, in cupy.cuda.device.Device.cublas_handle.__get__
  File "cupy\cuda\device.pyx", line 191, in cupy.cuda.device.Device._get_handle
  File "cupy\cuda\device.pyx", line 192, in cupy.cuda.device.Device._get_handle
  File "cupy\cuda\cublas.pyx", line 318, in cupy.cuda.cublas.create
  File "cupy\cuda\cublas.pyx", line 322, in cupy.cuda.cublas.create
  File "cupy\cuda\cublas.pyx", line 311, in cupy.cuda.cublas.check_status
cupy.cuda.cublas.CUBLASError: CUBLAS_STATUS_NOT_INITIALIZED
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\SOURCECODE\GitRepositories\Named Entity Recognition\ner_kfoldcv.py", line 247, in <module>
    plac.call(main)
  File "D:\Anaconda\envs\spacy223\lib\site-packages\plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "D:\Anaconda\envs\spacy223\lib\site-packages\plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "D:\SOURCECODE\GitRepositories\Named Entity Recognition\ner_kfoldcv.py", line 86, in main
    results = pool.starmap(ner_train.worker, args)
  File "D:\Anaconda\envs\spacy223\lib\multiprocessing\pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "D:\Anaconda\envs\spacy223\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
cupy.cuda.cublas.CUBLASError: CUBLAS_STATUS_NOT_INITIALIZED

## Your Environment

* Operating System: Windows 10 Pro x64
* Python Version Used: 3.6
* spaCy Version Used: 2.2.3 gpu version installed using pip install -U spacy[cuda90]
* Environment Information: 

name: spacy22
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - certifi=2019.11.28=py36_0
  - pip=19.3.1=py36_0
  - python=3.6.9=h5500b2f_0
  - setuptools=42.0.2=py36_0
  - sqlite=3.30.1=hfa6e2cd_0
  - vc=14.1=h21ff451_3
  - vs2015_runtime=15.5.2=3
  - wheel=0.33.6=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - blis==0.4.1
    - catalogue==0.0.8
    - chardet==3.0.4
    - cupy-cuda92==7.0.0
    - cymem==2.0.3
    - fastrlock==0.4
    - idna==2.8
    - importlib-metadata==1.3.0
    - more-itertools==8.0.2
    - murmurhash==1.0.2
    - numpy==1.17.4
    - plac==1.1.3
    - preshed==3.0.2
    - requests==2.22.0
    - six==1.13.0
    - spacy==2.2.3
    - srsly==0.2.0
    - thinc==7.3.1
    - tqdm==4.40.2
    - urllib3==1.25.7
    - wasabi==0.4.2
    - zipp==0.6.0
prefix: D:\Anaconda\envs\spacy22

**Comment by adrianeboyd** [comment]
Hi, I'm not sure, I think you might accidentally have conflicting versions of cupy installed or the incorrect CUDA version with cupy. The pip output lists cuda92 but your pip install command is for cuda90, so I'm not sure which version is correct?

I would suggest starting in a new virtual environment, verifying the CUDA version from your system (check with `nvcc --version`), and installing the right cupy package again from scratch. Here's their install guide: https://docs-cupy.chainer.org/en/stable/install.html . Then you can install spacy with `pip install spacy`.
