### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'use_params' when training using a base model 

### ISSUE THREAD

**Issue by erip** [explosion/spaCy#4813]
## How to reproduce the behaviour

I have trained an NER model with which I am happy and I'd like to use it as the base model for a core model. Below shows my script to kick off training and the resulting error.

```sh
(farsi-redo)
~/farsi_full/Farsi_models_for_SpaCy on  master! ⌚ 9:45:31
$ cat ./train_model.bash
#!/bin/bash

python -m spacy train fa depedency_model2 corpus/spacy/fa_seraji-ud-train.json corpus/spacy/fa_seraji-ud-dev.json -v fa_model -b ./ner_model/model-best --pipeline='tagger,parser'
(farsi-redo)
~/farsi_full/Farsi_models_for_SpaCy on  master! ⌚ 9:45:34
$ ./train_model.bash
Training pipeline: ['tagger', 'parser']
Starting with base model './ner_model/model-best'
Loading vector from model 'fa_model'
Counting training words (limit=0)

Itn  Tag Loss    Tag %    Dep Loss    UAS     LAS    Token %  CPU WPS
---  ---------  --------  ---------  ------  ------  -------  -------
Traceback (most recent call last):
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/site-packages/spacy/cli/train.py", line 368, in train
    losses=losses,
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/site-packages/spacy/language.py", line 515, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "nn_parser.pyx", line 423, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 262, in spacy.syntax.nn_parser.Parser.require_model
ValueError: [E109] Model for component 'parser' not initialized. Did you forget to load a model, or forget to call begin_training()?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/site-packages/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/site-packages/spacy/cli/train.py", line 492, in train
    with nlp.use_params(optimizer.averages):
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/erippeth/miniconda3/envs/farsi-redo/lib/python3.6/site-packages/spacy/language.py", line 716, in use_params
    next(context)
  File "pipes.pyx", line 577, in use_params
AttributeError: 'bool' object has no attribute 'use_params'
```

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.2.0-x86_64-i386-64bit
* **Python version:** 3.6.7

**Comment by erip** [comment]
As a note: I can train these models individually, but then combining the resulting models because unclear (i.e., `meta.json`, `vocab/*`, etc.).

**Comment by adrianeboyd** [comment]
See this comment: https://github.com/explosion/spaCy/issues/4306#issuecomment-533471516

What I said about the vocab isn't correct (the vectors need to be the same, but the vocab can differ because each component can have some its own vocab like model-specific labels and that should be handled when by each model when it is loaded). For spacy's provided models, each component is trained separately and they are combined by copying the model directories and merging `meta.json`, where the most important thing to get right is `pipeline` so that the components can be loaded.

It would make sense to have a CLI command to do this, see #4342. We do have internal scripts, but they're missing a lot of the compatibility checks that would be needed if you started trying to combine models willy nilly.

**Comment by erip** [comment]
@adrianeboyd ok, thanks so much. I ran a `diff` on the `vocab/*` and I saw some differences but I can double check. As for the `meta.json` - some of the fields are computed (e.g., CPU WPS); I guess these are mostly documentation, though? If they're "wrong", that won't impact anything at runtime, I suppose.

**Comment by svlandeg** [comment]
This is a very late follow-up, apologies, but I think these issues should be sorted out in the [pre-release of spaCy v3](https://github.com/explosion/spaCy/releases/tag/v3.0.0rc1). In the new [config system](https://nightly.spacy.io/usage/training#config), you can [source](https://nightly.spacy.io/usage/processing-pipelines#sourced-components) components similar to how the "base model" worked previously, but you have more flexibility. You can also define [frozen components](https://nightly.spacy.io/usage/training#config-components) that will be run, but not updated.

Sorry we never got round to fixing your original problem, but I hope you'll find spaCy v3 more robust and flexible! I'll tentatively close this, but feel free to reopen a new issue if you run into any trouble.

**Comment by erip** [comment]
Thanks, @svlandeg - looking forward to digging into spaCy v3! 💥
