### ISSUE TITLE
Shape mismatch when trying to follow provided pretrain_kb.py script

### ISSUE THREAD

**Issue by JohnGiorgi** [explosion/spaCy#4876]
## How to reproduce the behaviour

Simply run the provided [`pretrain_kb.py`](https://github.com/explosion/spaCy/blob/master/examples/training/pretrain_kb.py) script. Here is my exact setup:

```
conda create -n spacy python=3.7 -y
conda activate spacy
pip install spacy==2.2.3
python -m spacy download en_core_web_sm 
wget https://raw.githubusercontent.com/explosion/spaCy/master/examples/training/pretrain_kb.py
python pretrain_kb.py -m en_core_web_sm -n 1 -o ./tmp
```

During the execution, a Shape mismatch is raised with the following traceback

```
Loaded model 'en_core_web_sm'
Traceback (most recent call last):
  File "pretrain_kb.py", line 131, in <module>
    plac.call(main)
  File "/Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "pretrain_kb.py", line 77, in main
    encoder.train(description_list=descriptions, to_print=True)
  File "/Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/bin/wiki_entity_linking/train_descriptions.py", line 61, in train
    processed, loss = self._train_model(description_list)
  File "/Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/bin/wiki_entity_linking/train_descriptions.py", line 95, in _train_model
    loss = self._update(batch)
  File "/Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/bin/wiki_entity_linking/train_descriptions.py", line 143, in _update
    np.asarray(vectors), drop=self.DROP
  File "/Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/thinc/check.py", line 155, in checked_function
    check(arg_id, fix_args, kwargs)
  File "/Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/thinc/check.py", line 74, in has_shape_inner
    raise ShapeMismatchError(arg.shape, shape_values, shape)
thinc.exceptions.ShapeMismatchError: 

  Shape mismatch: input (2, 0) not compatible with [None, 300].

  Traceback:
  ├─ train in /Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/bin/wiki_entity_linking/train_descriptions.py:61
  ├─── _train_model in /Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/bin/wiki_entity_linking/train_descriptions.py:95
  └───── _update in /Users/johngiorgi/miniconda3/envs/spacy/lib/python3.7/site-packages/bin/wiki_entity_linking/train_descriptions.py:143
         >>> np.asarray(vectors), drop=self.DROP
```

## Your Environment

* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.2.0-x86_64-i386-64bit
* **Python version:** 3.7.5

**Comment by svlandeg** [comment]
Hi  @JohnGiorgi, the script should be run with a model that has pretrained vectors such as `en_core_web_lg`. If you run it with `en_core_web_sm` it will throw this error. Admittedly the error could be a little more user-friendly ;-)

**Comment by JohnGiorgi** [comment]
@svlandeg 

Ah, that makes sense. Thanks a lot

**Comment by JohnGiorgi** [comment]
@svlandeg 

Quick question (let me know if I should open a separate issue). But what if we trained our own NER model?

I did this using [the provided script](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py) (I modified it to load my train data, not shown here), e.g.

```
python train_new_entity_type.py -nm cui -o ./cui -n 1 
```

But, when I try to pass this model as an argument to the `pretrain_kb.py` script, I run into the new error you have just added

```
Loaded model './cui'
Traceback (most recent call last):
  File "scripts/pretrain_kb.py", line 131, in <module>
    plac.call(main)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "scripts/pretrain_kb.py", line 55, in main
    "The `nlp` object should have access to pretrained word vectors, "
ValueError: The `nlp` object should have access to pretrained word vectors,  cf. https://spacy.io/usage/models#languages.
```

Am I doing something wrong? Does a NER model trained with this script not create word vectors? I can see a `vectors` file under the `vocab` directory of my NER model

```
cui
├── meta.json
├── ner
│   ├── cfg
│   ├── lower_model
│   ├── model
│   ├── moves
│   ├── tok2vec_model
│   └── upper_model
├── tokenizer
└── vocab
    ├── key2row
    ├── lexemes.bin
    ├── strings.json
    └── vectors

2 directories, 12 files
```

Any help is appreciated!

**Comment by svlandeg** [comment]
Hm I think this will work if you run `train_new_entity_type.py` with `-m` and specify e.g. `en_core_web_lg`, because otherwise it starts from a blank `English()` model.

**Comment by JohnGiorgi** [comment]
Awesome, that makes sense. Thank you!
