### ISSUE TITLE
Why spacy is not installing?

### ISSUE THREAD

**Issue by mcp111** [explosion/spaCy#4893]
Gives following error

Microsoft Windows [Version 10.0.18362.535]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\admin>pip install spacy
Collecting spacy
  Using cached https://files.pythonhosted.org/packages/b7/f2/052bfe5861761599b5421916aba3eb0064d83145ff3072390ecdc5a836de/spacy-2.2.3.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\admin\appdata\local\programs\python\python38-32\python.exe' 'c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-6sjxrq37\normal' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'cython>=0.25' 'murmurhash<1.1.0,>=0.28.0' wheel 'thinc<7.4.0,>=7.3.0' 'cymem<2.1.0,>=2.0.2' 'preshed<3.1.0,>=3.0.2'
       cwd: None
  Complete output (111 lines):
  Collecting cython>=0.25
    Downloading https://files.pythonhosted.org/packages/22/03/510503cfbf20f62810a9548c9be13ab86181f00cca9a3a56717c4595d952/Cython-0.29.14-cp38-cp38-win32.whl (1.6MB)
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached https://files.pythonhosted.org/packages/22/e9/411be1845f1ac07ae3bc40a4b19ba401819baed4fa63b4f5ef28b2300eb4/murmurhash-1.0.2.tar.gz
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
  Collecting thinc<7.4.0,>=7.3.0
    Using cached https://files.pythonhosted.org/packages/d4/38/f79bb496ced36f8d69cdbdfe57a322205582ed9508bda5bd0227969d5a77/thinc-7.3.1.tar.gz
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\admin\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-8hmutbpz\\thinc\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-8hmutbpz\\thinc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\admin\AppData\Local\Temp\pip-install-8hmutbpz\thinc\pip-egg-info'
           cwd: C:\Users\admin\AppData\Local\Temp\pip-install-8hmutbpz\thinc\
      Complete output (97 lines):
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\mtrand.pyx
      Traceback (most recent call last):
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\tools\cythonize.py", line 61, in process_pyx
          from Cython.Compiler.Version import version as cython_version
      ModuleNotFoundError: No module named 'Cython'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\tools\cythonize.py", line 238, in <module>
          main()
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\tools\cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\tools\cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\tools\cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\tools\cythonize.py", line 66, in process_pyx
          raise OSError('Cython needs to be installed in Python as a module')
      OSError: Cython needs to be installed in Python as a module
      Running from numpy source directory.
      C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      Traceback (most recent call last):
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
          yield saved
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
          yield
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\setup.py", line 488, in <module>
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\setup.py", line 469, in setup_package
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\setup.py", line 275, in generate_cython
      RuntimeError: Running cythonize failed!

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\admin\AppData\Local\Temp\pip-install-8hmutbpz\thinc\setup.py", line 263, in <module>
          setup_package()
        File "C:\Users\admin\AppData\Local\Temp\pip-install-8hmutbpz\thinc\setup.py", line 201, in setup_package
          setup(
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
          dist = best[req.key] = env.best_match(
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
          return installer(requirement)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
          return cmd.easy_install(req)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
          run_setup(setup_script, args)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
          raise
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
          yield
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
          saved_exc.resume()
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 141, in resume
          six.reraise(type, exc, self._tb)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
          yield saved
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
          yield
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\setup.py", line 488, in <module>
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\setup.py", line 469, in setup_package
        File "C:\Users\admin\AppData\Local\Temp\easy_install-rlk2rdhi\numpy-1.18.1\setup.py", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      Cythonizing sources
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\admin\appdata\local\programs\python\python38-32\python.exe' 'c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\admin\AppData\Local\Temp\pip-build-env-6sjxrq37\normal' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'cython>=0.25' 'murmurhash<1.1.0,>=0.28.0' wheel 'thinc<7.4.0,>=7.3.0' 'cymem<2.1.0,>=2.0.2' 'preshed<3.1.0,>=3.0.2' Check the logs for full command output.

C:\Users\admin>

**Comment by adrianeboyd** [comment]
Hi, it looks like something is wrong related to the installation of `numpy`. Can you try installing spacy in a new virtual enviroment?
