### ISSUE TITLE
error while using spacy on docker

### ISSUE THREAD

**Issue by RajatChaudhari** [explosion/spaCy#4897]
Hello,

I am facing issues while running my docker image built with python 3.7 and spacy 2.2.1,
getting the below error:
Traceback (most recent call last):
  File "./app.py", line 2, in <module>
    import spacy
  File "C:\Python\lib\site-packages\spacy\__init__.py", line 12, in <module>
    from .cli.info import info as cli_info
  File "C:\Python\lib\site-packages\spacy\cli\__init__.py", line 6, in <module>
    from .train import train  # noqa: F401
  File "C:\Python\lib\site-packages\spacy\cli\train.py", line 17, in <module>
    from ..gold import GoldCorpus
  File "strings.pxd", line 23, in init spacy.gold
ImportError: DLL load failed: The specified module could not be found.

my docker file is - 

FROM python:3.7-windowsservercore-ltsc2016

COPY ./* /app/

WORKDIR /app

RUN pip install --upgrade setuptools

RUN pip install -r ./requirements.txt

CMD [ "python", "./app.py" ]

the build is successful but I get error when I do docker run

**Comment by svlandeg** [comment]
Hm, it looks like spaCy was not compiled properly for some reason. Can you show the output logs of the installation commands?
