### ISSUE TITLE
Error when trying to train NER component with CLI starting from a base model

### ISSUE THREAD

**Issue by JohnGiorgi** [explosion/spaCy#4902]
## How to reproduce the behaviour

I am trying to train the NER component using the CLI, starting from a base model. I first convert my data to the spaCy `json` format, then use `debug-data` to make sure it is ready for training:

```
python -m spacy debug-data en ./train.json ./test.json -b en_core_web_lg -p ner -V

=========================== Data format validation ===========================
✔ Corpus is loadable

=============================== Training stats ===============================
Training pipeline: ner
Starting with base model 'en_core_web_lg'
50 training docs
50 evaluation docs
✔ No overlap between training and evaluation data

============================== Vocab & Vectors ==============================
ℹ 54993 total words in the data (6899 unique)
10 most common words: ' ' (5087), '.' (3259), ',' (2269), ':' (1223), 'and'
(1104), 'was' (1015), 'the' (999), 'of' (796), 'to' (737), 'patient' (653)
ℹ 684831 vectors (684830 unique keys, 300 dimensions)

========================== Named Entity Recognition ==========================
ℹ 1 new label, 0 existing labels
0 missing values (tokens with '-' label)
New: 'CUI' (6554)
✔ Good amount of examples for all labels
✔ Examples without occurrences available for all labels
✔ No entities consisting of or starting/ending with whitespace

================================== Summary ==================================
✔ 5 checks passed
```

Then, I try to train it with the following command:

```
python -m spacy train en ./cui train.json test.json -b en_core_web_lg -p ner -n 10
```

But training errors out before the first epoch. The traceback is: 

```
Training pipeline: ['ner']
Starting with base model 'en_core_web_lg'
Counting training words (limit=0)

Itn  NER Loss   NER P   NER R   NER F   Token %  CPU WPS
---  ---------  ------  ------  ------  -------  -------
✔ Saved model to output directory                                                                                                   
cui/model-final
⠏ Creating best model...
Traceback (most recent call last):
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/cli/train.py", line 368, in train
    losses=losses,
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/language.py", line 515, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "nn_parser.pyx", line 445, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 547, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "ner.pyx", line 107, in spacy.syntax.ner.BiluoPushDown.preprocess_gold
  File "ner.pyx", line 165, in spacy.syntax.ner.BiluoPushDown.lookup_transition
KeyError: "[E022] Could not find a transition with the name 'B-CUI' in the NER model."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/cli/train.py", line 497, in train
    best_model_path = _collate_best_model(meta, output_path, nlp.pipe_names)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/cli/train.py", line 565, in _collate_best_model
    path2str(best_component_src / component), path2str(best_dest / component)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
```

Any help as to why this happens is appreciated!

## Your Environment

* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.2.0-x86_64-i386-64bit
* **Python version:** 3.7.6

**Comment by jack-rory-staunton** [comment]
What does debug-data report when you try with en_core_web_lg ? It looks like you're debugging and training two different models there.

**Comment by JohnGiorgi** [comment]
@jack-rory-staunton 

My apologies, there were a couple copy/paste errors in my issue. Those have been corrected, but I get the same error when training.

**Comment by jack-rory-staunton** [comment]
I'm not sure, but in spite of passing debug I suspect it is because your are giving it a different-than-expected format (it seems to expect BILOU from the error) . Could you paste in some of the train.json?

**Comment by JohnGiorgi** [comment]
It is formatted as BILOU, as far as I can tell. Here are two segments of `train.json`

```json
...
              {
                "id":434,
                "orth":"No",
                "ner":"B-CUI"
              },
              {
                "id":435,
                "orth":"known",
                "ner":"I-CUI"
              },
              {
                "id":436,
                "orth":"drug",
                "ner":"I-CUI"
              },
              {
                "id":437,
                "orth":"allergies",
                "ner":"L-CUI"
              },
...
```

and

```json
...
              {
                "id":445,
                "orth":"Aspirin",
                "ner":"U-CUI"
              },
...
```

**Comment by adrianeboyd** [comment]
I think this is the same issue as in #4465. Since you have plenty of instances (more than for some of the less frequent default types), I wonder if there's a bug when a new entity type is being added to an existing model and not just problems related to really infrequent types. I haven't dug into the code enough to be sure at this point, however:

Given the `debug-data` output for your training data, which only shows one tag in it, I think it would be better for you to train a new NER model rather than to try to extend the NER model from a default English model. You'll run into the "catastrophic forgetting" problem if you don't have any of the existing NER labels in your data.

Is the reason to use `en_core_web_lg` mainly to have word vectors? If so, use `-v en_core_web_lg` instead of `-b`, which just uses the vectors without trying to extend the existing NER model.

Given that the small sample text looks like it could be from a biomedical domain, you might want to look at the scispacy models (some `md` models have vectors) instead of the default spacy models, too. The vectors or other components may be a better fit for your task.

**Comment by JohnGiorgi** [comment]
Thanks for the detailed response @adrianeboyd,

> I think it would be better for you to train a new NER model rather than to try to extend the NER model from a default English model

In fact, this is what I want, but I couldn't figure out how to do it with the spaCy `train` cli. I was able to do it by modifying the [`train_ner.py`](https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py) script:

```python
# Create new EntityRecognizer component. Replace the existing EntityRecognizer model with this randomly
# initialized component if it exists.
# nlp.create_pipe works for built-ins that are registered with spaCy
ner = nlp.create_pipe("ner")
if "ner" not in nlp.pipe_names:
    nlp.add_pipe(ner, last=True)
else:
    nlp.replace_pipe("ner", ner)
```

Any idea of how I might do it with spaCy `train`? It would be great if there was some kind of command-line argument for replacing existing components.

> Is the reason to use en_core_web_lg mainly to have word vectors? If so, use -v en_core_web_lg instead of -b, which just uses the vectors without trying to extend the existing NER model

I have tried this and it works. However, the reason I am using an existing model is both for its word vectors and for the tagger/parser so that these can be used to improve tokenization/sentence boundary detection (they are used for that purpose, right?)

> you might want to look at the scispacy models

Thanks for the suggestion! This actually is the plan, I just wanted to get things working with  `en_core_web_lg`. I actually get a different error when trying to use the scispaCy models with `-v` that I was going to ask about in a separate issue, but I might as well explain that here.

Here is the output from `debug-data`:

```
python -m spacy debug-data en ./train.json ./test.json -b en_core_sci_lg -p ner -V                                        ✔ 

=========================== Data format validation ===========================
✔ Corpus is loadable

=============================== Training stats ===============================
Training pipeline: ner
Starting with base model 'en_core_sci_lg'
50 training docs
50 evaluation docs
✔ No overlap between training and evaluation data

============================== Vocab & Vectors ==============================
ℹ 54258 total words in the data (6807 unique)
⚠ 244 misaligned tokens in the training data
⚠ 247 misaligned tokens in the dev data
10 most common words: ' ' (5087), '.' (3246), ',' (2269), ':' (1223), 'and'
(1104), 'was' (1015), 'the' (999), 'of' (796), 'to' (735), 'patient' (653)
ℹ 600000 vectors (667864 unique keys, 200 dimensions)

========================== Named Entity Recognition ==========================
ℹ 1 new label, 0 existing labels
0 missing values (tokens with '-' label)
New: 'CUI' (6469)
✔ Good amount of examples for all labels
✔ Examples without occurrences available for all labels
✔ No entities consisting of or starting/ending with whitespace

================================== Summary ==================================
✔ 5 checks passed
⚠ 2 warnings
```

Error when calling with `-v`:

```
python -m spacy train en ./cui train.json test.json -v en_core_sci_lg -p ner -n 10                                        ✔ 
Training pipeline: ['ner']
Starting with blank model 'en'
Loading vector from model 'en_core_sci_lg'
Traceback (most recent call last):
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/cli/train.py", line 213, in train
    _load_vectors(nlp, vectors)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/cli/train.py", line 530, in _load_vectors
    util.load_model(vectors, vocab=nlp.vocab)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/util.py", line 164, in load_model
    return load_model_from_package(name, **overrides)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/util.py", line 185, in load_model_from_package
    return cls.load(**overrides)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/en_core_sci_lg/__init__.py", line 10, in load
    nlp = load_model_from_init_py(__file__, **overrides)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/util.py", line 211, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/language.py", line 941, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/util.py", line 654, in from_disk
    reader(path / key)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/language.py", line 936, in <lambda>
    p, exclude=["vocab"]
  File "pipes.pyx", line 661, in spacy.pipeline.pipes.Tagger.from_disk
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/util.py", line 654, in from_disk
    reader(path / key)
  File "pipes.pyx", line 640, in spacy.pipeline.pipes.Tagger.from_disk.load_model
  File "pipes.pyx", line 548, in spacy.pipeline.pipes.Tagger.Model
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/_ml.py", line 586, in build_tagger_model
    pretrained_vectors=pretrained_vectors,
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/_ml.py", line 323, in Tok2Vec
    return _legacy_tok2vec.Tok2Vec(width, embed_size, **kwargs)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/ml/_legacy_tok2vec.py", line 44, in Tok2Vec
    glove = StaticVectors(pretrained_vectors, width, column=cols.index(ID))
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/thinc/neural/_classes/static_vectors.py", line 43, in __init__
    vectors = self.get_vectors()
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/thinc/neural/_classes/static_vectors.py", line 55, in get_vectors
    return get_vectors(self.ops, self.lang)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/thinc/extra/load_nlp.py", line 26, in get_vectors
    nlp = get_spacy(lang)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/thinc/extra/load_nlp.py", line 14, in get_spacy
    SPACY_MODELS[lang] = spacy.load(lang, **kwargs)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_sci_lg_vectors'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

Error when calling with `-b` (same error as with `en_core_web_lg`):

```
python -m spacy train en ./cui train.json test.json -b en_core_sci_lg -p ner -n 10                                        ✔ 
Training pipeline: ['ner']
Starting with base model 'en_core_sci_lg'
Counting training words (limit=0)

Itn  NER Loss   NER P   NER R   NER F   Token %  CPU WPS
---  ---------  ------  ------  ------  -------  -------
✔ Saved model to output directory                                                                                                                                                          
cui/model-final
⠏ Creating best model...
Traceback (most recent call last):
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/cli/train.py", line 368, in train
    losses=losses,
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/language.py", line 515, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "nn_parser.pyx", line 445, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 547, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "ner.pyx", line 107, in spacy.syntax.ner.BiluoPushDown.preprocess_gold
  File "ner.pyx", line 165, in spacy.syntax.ner.BiluoPushDown.lookup_transition
KeyError: "[E022] Could not find a transition with the name 'B-CUI' in the NER model."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/cli/train.py", line 497, in train
    best_model_path = _collate_best_model(meta, output_path, nlp.pipe_names)
  File "/Users/johngiorgi/miniconda3/envs/drspacy/lib/python3.7/site-packages/spacy/cli/train.py", line 565, in _collate_best_model
    path2str(best_component_src / component), path2str(best_dest / component)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
```

**Comment by adrianeboyd** [comment]
This is a problem with `spacy train` that I've wanted to address for a while, see #4342. Could you have a look at this PR: #4911?

(You can just replace `spacy/cli/train.py` with the modified file from that branch in your spacy installation: https://github.com/adrianeboyd/spaCy/blob/feature/train-cli-extend-base-models-4342/spacy/cli/train.py if you're not installing from source.)

This should make it possible to add, extend, or replace (with the new flag `-R`) components in a base model. After training, the full pipeline is restored and saved in `model-best` so that you have the full model available.

The merging/updating of information in `meta.json` is probably not quite 100%, plus some of the information is impossible to update correctly (like speed, since from this training we only know the speed for the components we trained), but I think the basics should work.

I'd appreciate it if you could test it with your setup and let me know if you run into any issues? There are so many options to `spacy train` that it's hard to test everything thoroughly.

**Comment by JohnGiorgi** [comment]
@adrianeboyd Awesome, it works for me :)

Here is the exact command:

```
python -m spacy train en ./cui train.json test.json -b en_core_sci_lg -p ner -R -n 10
```

Loss goes down, NER performance goes up, and after training the model I can load it with `spacy.load()` and use it to process some documents.
