### ISSUE TITLE
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by LizMcQuillan** [explosion/spaCy#4915]
I've gone through the troubleshooting steps in previous issues (like #4756 and #4577), but have been unable to resolve the error. 

I'm attempting to import and use version 2.2.3, which seems to be installed. Meaning, I installed it and previously everything worked fine. I haven't made any changes to my machine, just started a new script. and attempted to use:

```
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from spacy.lang.en import English
parser = English()
import en_core_web_sm
nlp = spacy.load("en_core_web_sm")
```

which yields

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

## Your Environment
* **spaCy version:** 2.2.3
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.7.3
Mac OS

I've also tried the following:

```
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from spacy.lang.en import English
parser = English()
from spacy.lang.en import en_core_web_sm
```

Which yields: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'en_core_web_sm' from 'spacy.lang.en' (/usr/local/lib/python3.7/site-packages/spacy/lang/en/__init__.py)
>>> nlp = spacy.load("en_core_web_sm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

If I run each line separately, the errors I get are:
```
>>> from spacy.lang.en import en_core_web_sm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'en_core_web_sm' from 'spacy.lang.en' (/usr/local/lib/python3.7/site-packages/spacy/lang/en/__init__.py)
>>> nlp = spacy.load("en_core_web_sm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

**Comment by LizMcQuillan** [comment]
Solved with:

```
from spacy.cli.download import download
download('en_core_web_sm')
```

Not sure why this was required, but it did fix the issue.
