### ISSUE TITLE
Sentence that pulls an assertion error. Mixed languages

### ISSUE THREAD

**Issue by awhillas** [explosion/spaCy#498]
This killed it dead

> Yes.......come here....viens pres moi...

Taken from a movie dialog corpus. Gave me:
```
>>> nlp(u"Yes.......come here....viens pres moi...")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python2.7/site-packages/spacy/language.py", line 225, in __call__
    tokens = self.tokenizer(text)
  File "spacy/tokenizer.pyx", line 118, in spacy.tokenizer.Tokenizer.__call__ (spacy/tokenizer.cpp:4664)
  File "spacy/tokenizer.pyx", line 159, in spacy.tokenizer.Tokenizer._tokenize (spacy/tokenizer.cpp:5409)
  File "spacy/tokenizer.pyx", line 231, in spacy.tokenizer.Tokenizer._attach_tokens (spacy/tokenizer.cpp:6444)
  File "spacy/tokens/doc.pyx", line 282, in spacy.tokens.doc.Doc.push_back (spacy/tokens/doc.cpp:8356)
AssertionError
```
FYI

**Comment by honnibal** [comment]
I think this is fixed in 0.101.0. Are you using 0.100.7?
