### ISSUE TITLE
measure_performance() got an unexpected keyword argument 'dev_limit'

### ISSUE THREAD

**Issue by kurodenjiro** [explosion/spaCy#4983]
2020-02-08 09:32:05,139 - INFO - __main__ - Creating Entity Linker with Wikipedia and WikiData
2020-02-08 09:32:05,139 - INFO - __main__ - STEP 1a: Loading model from kb-data\nlp_kb
2020-02-08 09:32:20,549 - INFO - __main__ - Original NLP pipeline has following pipeline components: ['tagger', 'parser', 'ner']
2020-02-08 09:33:04,116 - INFO - __main__ - STEP 1b: Loading KB from kb-data\kb
2020-02-08 09:33:04,305 - INFO - __main__ - STEP 2: Reading training & dev dataset from kb-data\gold_entities.jsonl
2020-02-08 09:33:24,192 - INFO - __main__ - Training set has 1589406 articles, limit set to roughly all articles per epoch
2020-02-08 09:33:24,192 - INFO - __main__ - Dev set has 177028 articles, limit set to rougly all articles for evaluation
2020-02-08 09:33:24,192 - INFO - __main__ - STEP 3: Creating and training an Entity Linking pipe for 10 epochs
2020-02-08 09:33:25,827 - INFO - __main__ - Dev Baseline Accuracies:
Traceback (most recent call last):
  File "wikidata_train_entity_linker.py", line 173, in <module>
    plac.call(main)
  File "C:\Users\Admin\Anaconda3\envs\spacy_nlu\lib\site-packages\plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\Admin\Anaconda3\envs\spacy_nlu\lib\site-packages\plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "wikidata_train_entity_linker.py", line 117, in main
    measure_performance(dev_data, kb, el_pipe, baseline=True, context=False, dev_limit=len(dev_indices))
TypeError: measure_performance() got an unexpected keyword argument 'dev_limit'

**Comment by svlandeg** [comment]
Merging with Issue https://github.com/explosion/spaCy/issues/4982 as this is likely caused by the same problem, an incompatibility between the script you're running and the spaCy version. `measure_performance` was gained its `dev_limit` argument also in PR https://github.com/explosion/spaCy/pull/4811.
