### ISSUE TITLE
Command line trained tagger model for Greek does not fill token.pos attribute

### ISSUE THREAD

**Issue by pdimiel** [explosion/spaCy#4996]
Hello everyone.
I am trying to train a Greek model and now I am focusing on the tagger.
My training data has been converted to spacy json format and the model seems to be trained correctly.
I use very fine grained tags like "NoCmFePlAc", 
When I test on a sentence, while the fine grained tag is correct, the general pos is always X.

Looking around I read about the tagger tag_map and thought my tagset was too fine grained for the Greek language tag_map.

But checking the entries in https://github.com/explosion/spaCy/blob/master/spacy/lang/el/tag_map.py I see that for example, "NoCmFePlAc" that is one of the attributed tags, exists in the tag_map. But the token still has X in the POS attribute.

The train command I use is 

> python -m spacy train el models train.json test.json

Any suggestions on what I am doing wrong?

Thanks in advance

**Comment by adrianeboyd** [comment]
Hmm, the Greek setup here is a little non-standard. It's actually loading https://github.com/explosion/spaCy/blob/master/spacy/lang/el/tag_map_general.py as the tag map because the training data for the `el` model only has UD POS tags and not the fine-grained ones, but the filenames don't follow the same pattern as the other languages.

In order to get `spacy train el` to use the right tag map you'll need to edit `lang/el/__init__.py` to load the other tag map. Here's where it loads `tag_map_general.py`:

https://github.com/explosion/spaCy/blob/e1f777b15171fef086c20a5d2415f9f2154e1544/spacy/lang/el/__init__.py#L6

Instead you would want:

```
from .tag_map import TAG_MAP
```

The tag map is saved inside the model, so the people using your model can use it with a standard spacy installation and they don't need to make any modifications.

I'll fix this for the next version so that it's loading the generic UD `TAG_MAP` from `lang/tag_map.py` and rename `lang/el/tag_map.py` so that this is less confusing.

(I've already added a `--tag_map_path` option to `spacy train` in an upcoming version of spacy where you can provide the tag map as a JSON dict because the tag map always depends on your training data, not just the language, and you shouldn't have to edit the source to set this easily.)

**Comment by pdimiel** [comment]
I modified the `lang/el/__init__.py` file as you suggest but now I get an error after the first train iteration while the model is being evaluated. 
`ValueError: [E167] Unknown morphological feature: 'Person' (2313063860588076218)...`

There are mentions on such an error being related to non updated language models but I am trying to train a blank "el" model.
I am using spaCy 2.2.3.

The full traceback is:
```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\spacy\cli\train.py", line 396, in train
    scorer = nlp_loaded.evaluate(dev_docs, verbose=verbose)
  File "C:\Program Files\Python37\lib\site-packages\spacy\language.py", line 684, in evaluate
    for doc, gold in zip(docs, golds):
  File "nn_parser.pyx", line 248, in pipe
  File "C:\Program Files\Python37\lib\site-packages\spacy\util.py", line 481, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
  File "nn_parser.pyx", line 248, in pipe
  File "C:\Program Files\Python37\lib\site-packages\spacy\util.py", line 481, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
  File "pipes.pyx", line 404, in pipe
  File "pipes.pyx", line 442, in spacy.pipeline.pipes.Tagger.set_annotations
  File "morphology.pyx", line 312, in spacy.morphology.Morphology.assign_tag_id
  File "morphology.pyx", line 200, in spacy.morphology.Morphology.add
ValueError: [E167] Unknown morphological feature: 'Person' (2313063860588076218). This can happen if the tagger was trained with a different set of morphological features. If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\lib\site-packages\spacy\__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Program Files\Python37\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Program Files\Python37\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\spacy\cli\train.py", line 497, in train
    best_model_path = _collate_best_model(meta, output_path, nlp.pipe_names)
  File "C:\Program Files\Python37\lib\site-packages\spacy\cli\train.py", line 559, in _collate_best_model
    bests[component] = _find_best(output_path, component)
  File "C:\Program Files\Python37\lib\site-packages\spacy\cli\train.py", line 578, in _find_best
    accs = srsly.read_json(epoch_model / "accuracy.json")
  File "C:\Program Files\Python37\lib\site-packages\srsly\_json_api.py", line 50, in read_json
    file_path = force_path(location)
  File "C:\Program Files\Python37\lib\site-packages\srsly\util.py", line 21, in force_path
    raise ValueError("Can't read file: {}".format(location))
ValueError: Can't read file: models\model0\accuracy.json
```

Should I modify the tag_map.py and remove all morphological information?

**Comment by adrianeboyd** [comment]
You can remove all the morphological information if you don't need it.

If you'd like to keep it, I think you just need to change the `"Person"` values from `1 / 2 / 3` to `one / two / three`. You may run into other similar errors, since this file wasn't loaded / tested previously while training Greek models on our end. There's a list of supported features+values here:

https://github.com/explosion/spaCy/blob/e1f777b15171fef086c20a5d2415f9f2154e1544/spacy/morphology.pyx#L848-L1103

(The morphology implementation is in an awkward in-between state in v2 with a hard-coded list of features+values and other similar issues. In v3 there's going to be a morphologizer component that allows any features+values and will predict POS rather than just mapping it from the fine-grained tags.)

**Comment by pdimiel** [comment]
Renaming the Person value to one/two/three leads to the following exception that seems of a different type. 
I removed the morphological information form tag_map.py and the model training worked like a charm.
I can use the original tag_map morphological information to load it after the spaCy processing and use it as a side explanation if needed.

Thanks a lot for your help.
Looking forward to v3.

I attach the latest exception in case you or someone wants to look into it or for someone that comes accross the same. 

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\spacy\cli\train.py", line 396, in train
    scorer = nlp_loaded.evaluate(dev_docs, verbose=verbose)
  File "C:\Program Files\Python37\lib\site-packages\spacy\language.py", line 684, in evaluate
    for doc, gold in zip(docs, golds):
  File "nn_parser.pyx", line 248, in pipe
  File "C:\Program Files\Python37\lib\site-packages\spacy\util.py", line 481, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
  File "nn_parser.pyx", line 248, in pipe
  File "C:\Program Files\Python37\lib\site-packages\spacy\util.py", line 481, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
  File "pipes.pyx", line 404, in pipe
  File "pipes.pyx", line 442, in spacy.pipeline.pipes.Tagger.set_annotations
  File "morphology.pyx", line 307, in spacy.morphology.Morphology.assign_tag_id
  File "morphology.pyx", line 240, in spacy.morphology.Morphology.lemmatize
  File "strings.pyx", line 152, in spacy.strings.StringStore.as_string
  File "strings.pyx", line 120, in spacy.strings.StringStore.__getitem__
TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\lib\site-packages\spacy\__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Program Files\Python37\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Program Files\Python37\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\spacy\cli\train.py", line 497, in train
    best_model_path = _collate_best_model(meta, output_path, nlp.pipe_names)
  File "C:\Program Files\Python37\lib\site-packages\spacy\cli\train.py", line 559, in _collate_best_model
    bests[component] = _find_best(output_path, component)
  File "C:\Program Files\Python37\lib\site-packages\spacy\cli\train.py", line 578, in _find_best
    accs = srsly.read_json(epoch_model / "accuracy.json")
  File "C:\Program Files\Python37\lib\site-packages\srsly\_json_api.py", line 50, in read_json
    file_path = force_path(location)
  File "C:\Program Files\Python37\lib\site-packages\srsly\util.py", line 21, in force_path
    raise ValueError("Can't read file: {}".format(location))
ValueError: Can't read file: models\model0\accuracy.json
```

**Comment by adrianeboyd** [comment]
Glad it's working!

Sorry, I didn't have any training data to really test the tag map with. Here are the updates from a future version that may still have some unsupported individual features or values (like the annoying `Person: one` mapping), but removes the nested dict features, which is what leads to that error:

https://github.com/adrianeboyd/spaCy/blob/9151f59aae39c0bd5a5caa3552aef744a1f22c27/spacy/lang/el/tag_map.py
