### ISSUE TITLE
Packaging a Windows application

### ISSUE THREAD

**Issue by victor-dumitrescu** [explosion/spaCy#502]
I am having difficult packaging a Python project which includes spaCy as a Windows executable. I have tried py2exe, PyInstaller and cx_Freeze. With all 3 of these tools, the application is successfully built, but when I try to run it, I get this error:

>Traceback (most recent call last):
>  File "gui.py", line 2, in <module>
  File "c:\users\victor\appdata\local\temp\pip-build-3qf9y1\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "entities.py", line 4, in <module>
  File "c:\users\victor\appdata\local\temp\pip-build-3qf9y1\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\spacy\__init__.py", line 3, in <module>
  File "c:\users\victor\appdata\local\temp\pip-build-3qf9y1\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\spacy\en\__init__.py", line 5, in <module>
  File "c:\users\victor\appdata\local\temp\pip-build-3qf9y1\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\spacy\language.py", line 11, in <module>
  File "c:\users\victor\appdata\local\temp\pip-build-3qf9y1\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 546, in load_module
  File ".build/lib/python2.7/site-packages/cymem/cymem.pxd", line 1, in init spacy.tokenizer (spacy/tokenizer.cpp:10477)
ImportError: No module named cymem.cymem

**Comment by honnibal** [comment]
I think there are a lot of steps at which this could go wrong. You'll need to figure out which one it fails at.

Have you tried packaging a toy Cython project? And if that works, have you tried packaging a project that uses only cymem? And if that works, have you tried packaging a project that uses cymem as a Cython dependency?

**Comment by victor-dumitrescu** [comment]
Thanks for the quick reply. I've tried packaging a project which only imports cymem and that seemed to work. Since I don't really have any experience with packaging Python projects for Windows, I was wondering if you think that, in principle, spaCy can be packaged as part of a Windows application.

**Comment by victor-dumitrescu** [comment]
Update: I've solved the problem. It was a matter of PyInstaller not detecting the correct imports.

**Comment by sonil2212** [comment]
@victor-dumitrescu can you let me know how you solved the problem, I am getting the same error.

**Comment by sonil2212** [comment]
I am getting following error 

Traceback (most recent call last):
  File "smart_search_php.py", line 12, in <module>
  File "/tmp/pip-build-epGrVk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "clean_text_and_process.py", line 9, in <module>
  File "/tmp/pip-build-epGrVk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "lemmatization.py", line 2, in <module>
  File "/tmp/pip-build-epGrVk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "spacy/__init__.py", line 5, in <module>
  File "/tmp/pip-build-epGrVk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "spacy/deprecated.py", line 8, in <module>
  File "/tmp/pip-build-epGrVk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "spacy/cli/__init__.py", line 5, in <module>
  File "/tmp/pip-build-epGrVk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "spacy/cli/train.py", line 7, in <module>
  File "/tmp/pip-build-epGrVk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "spacy/scorer.py", line 4, in <module>
  File "/tmp/pip-build-epGrVk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 546, in load_module
  File ".env/lib/python3.6/site-packages/cymem/cymem.pxd", line 1, in init spacy.gold (spacy/gold.cpp:23496)
ImportError: No module named cymem.cymem
Failed to execute script smart_search_php

**Comment by sonil2212** [comment]
although my code is in python 2.7
