### ISSUE TITLE
msgpacks map key ValueError when loading model

### ISSUE THREAD

**Issue by tylergibbs2** [explosion/spaCy#5033]
## How to reproduce the problem
I can't reproduce this on my local machine. This error only occurs when I deploy my project to Heroku. Oddly enough, this occurred randomly. I was able to deploy my project before, but suddenly when I deployed again (with no code changes) this error occurred. I've checked the versions that were downloaded for msgpacks, spaCy, and the model between the different deploys and I could not find a different.

```bash
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/app/utils/keyword_extract.py", line 10, in <module>
    nlp = spacy.load('en_core_web_sm')
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/data/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/language.py", line 647, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/language.py", line 636, in <lambda>
    ('tokenizer', lambda p: self.tokenizer.from_disk(p, vocab=False)),
  File "tokenizer.pyx", line 367, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 402, in spacy.tokenizer.Tokenizer.from_bytes
  File "/app/.heroku/python/lib/python2.7/site-packages/spacy/util.py", line 490, in from_bytes
    msg = msgpack.loads(bytes_data, raw=False)
  File "/app/.heroku/python/lib/python2.7/site-packages/msgpack_numpy.py", line 184, in unpackb
    return _unpackb(packed, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/msgpack/fallback.py", line 129, in unpackb
    ret = unpacker._unpack()
  File "/app/.heroku/python/lib/python2.7/site-packages/msgpack/fallback.py", line 670, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/app/.heroku/python/lib/python2.7/site-packages/msgpack/fallback.py", line 670, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/app/.heroku/python/lib/python2.7/site-packages/msgpack/fallback.py", line 643, in _unpack
    ret.append(self._unpack(EX_CONSTRUCT))
  File "/app/.heroku/python/lib/python2.7/site-packages/msgpack/fallback.py", line 666, in _unpack
    "%s is not allowed for map key" % str(type(key))
ValueError: <type 'int'> is not allowed for map key
```

## keyword_extract.py
```py
# -*- coding: utf-8 -*-

from collections import OrderedDict

import numpy as np
import spacy
from spacy.lang.en.stop_words import STOP_WORDS

try:
    nlp = spacy.load('en_core_web_sm')
except IOError:
    print("spacy model not found. Attempting download.")
    spacy.cli.download('en_core_web_sm')
    nlp = spacy.load('en_core_web_sm')

...
```

## Your Environment
**Models:** en_core_web_sm
**Python version:** 2.7.15
**Platform:** Linux-4.4.0-1057-aws-x86_64-with-debian-buster-sid
**spaCy version:** 2.0.16
**Environment Information:** Heroku

![image](https://user-images.githubusercontent.com/1884865/74781861-f7292780-5267-11ea-8ace-5f84d33322d0.png)

**Comment by honnibal** [comment]
Try updating the version (and also the Python version)? I suspect the problem will be resolved.
