### ISSUE TITLE
Installation fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by thomaskern** [explosion/spaCy#505]
I am on OSX (10.11.6).
```
(keras3)--- programming/hackathon-context-spotlight » python --version
Python 3.5.1
(keras3)--- programming/hackathon-context-spotlight » pip install spacy
Downloading/unpacking spacy
  Downloading spacy-0.101.0.tar.gz (2.3MB): 2.3MB downloaded
  Running setup.py (path:/Users/thomaskern/.virtualenvs/keras3/build/spacy/setup.py) egg_info for package spacy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/thomaskern/.virtualenvs/keras3/build/spacy/setup.py", line 225, in <module>
        setup_package()
      File "/Users/thomaskern/.virtualenvs/keras3/build/spacy/setup.py", line 160, in setup_package
        readme = f.read()
      File "/Users/thomaskern/.virtualenvs/keras3/bin/../lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2680: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/thomaskern/.virtualenvs/keras3/build/spacy/setup.py", line 225, in <module>

    setup_package()

  File "/Users/thomaskern/.virtualenvs/keras3/build/spacy/setup.py", line 160, in setup_package

    readme = f.read()

  File "/Users/thomaskern/.virtualenvs/keras3/bin/../lib/python3.5/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2680: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/thomaskern/.virtualenvs/keras3/build/spacy
Storing debug log for failure in /Users/thomaskern/.pip/pip.log
```

**Comment by bob-nclouds** [comment]
I am also getting the same error, while installing in docker container. Is there an workaround for this issue?

**Comment by honnibal** [comment]
Hmm. What's your system encoding? Can you do:

```
echo $LC_ALL
echo $LANG
```

And tell me what it says?

**Comment by thomaskern** [comment]
Both are empty for me.

**Comment by honnibal** [comment]
Try `export LANG=en_US.UTF-8`

**Comment by thomaskern** [comment]
That worked for me.

**Comment by honnibal** [comment]
Thanks. I'll make sure the encoding is explicit in the next release.
