### ISSUE TITLE
spaCy wiki_entity_linking OSError: Invalid data stream

### ISSUE THREAD

**Issue by kprice-aktors** [explosion/spaCy#5098]
I am encountering an unexpected error `OSerror: invalid data stream` when trying to use [wiki_entity_linker](https://github.com/explosion/spaCy/tree/master/bin/wiki_entity_linking) to create a knowledge base for training a Named Entity Linking model.  I followed all the steps in the README. I find this really annoying since it takes about an hour and a half to run before I encounter this error. I have read similar issues, but they seem to be for training different models, and I am not sure the solutions presented are relevant to the specific task I am trying to do. 

## How to reproduce the behavior
```
user@server$ python3 ./bin/wiki_entity_linking/wikidata_pretrain_kb.py -la en latest-all.json.bz2  enwiki-latest-pages-articles-multistream.xml.bz2  knowledge-base/en/ en_core_web_lg
2020-03-04 11:56:40,012 - INFO - __main__ - Creating KB with Wikipedia and WikiData
2020-03-04 11:56:40,013 - INFO - __main__ - STEP 1: Loading NLP model en_core_web_lg
2020-03-04 11:56:54,400 - INFO - __main__ - STEP 2: Writing prior probabilities to knowledge-base/en/prior_prob.csv
2020-03-04 12:06:29,408 - INFO - bin.wiki_entity_linking.wikipedia_processor - processed 25000000 lines of Wikipedia XML dump
2020-03-04 12:15:25,684 - INFO - bin.wiki_entity_linking.wikipedia_processor - processed 50000000 lines of Wikipedia XML dump
 . . . . . . . . . . 
 . . . . . . . . . .
2020-03-04 13:33:52,502 - INFO - bin.wiki_entity_linking.wikipedia_processor - processed 350000000 lines of Wikipedia XML dump
Traceback (most recent call last):
  File "../.local/lib/python3.7/site-packages/bin/wiki_entity_linking/wikidata_pretrain_kb.py", line 179, in <module>
    plac.call(main)
  File "/home/user/.local/lib/python3.7/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/home/user/.local/lib/python3.7/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "../.local/lib/python3.7/site-packages/bin/wiki_entity_linking/wikidata_pretrain_kb.py", line 99, in main
    wp.read_prior_probs(wp_xml, prior_prob_path, limit=limit_prior)
  File "/home/user/.local/lib/python3.7/site-packages/bin/wiki_entity_linking/wikipedia_processor.py", line 100, in read_prior_probs
    line = file.readline()
  File "/usr/lib/python3.7/bz2.py", line 215, in readline
    return self._buffer.readline(size)
  File "/usr/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.7/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream
```

The README also provides instructions for testing the code using a limited number of lines. I was able to do this and did not seem to encounter any of the above errors. 

```
user@server$ python3 ./bin/wiki_entity_linking/wikidata_pretrain_kb.py -lt 20000 -lp 2000 -lw 3000 -f 1  latest-all.json.bz2  enwiki-latest-pages-articles-multistream.xml.bz2  knowledge-base/en/ en_core_web_lg
2020-03-04 13:51:39,148 - INFO - __main__ - Creating KB with Wikipedia and WikiData
2020-03-04 13:51:39,148 - INFO - __main__ - STEP 1: Loading NLP model en_core_web_lg
2020-03-04 13:51:52,418 - INFO - __main__ - STEP 2: Writing prior probabilities to knowledge-base/en/prior_prob.csv
2020-03-04 13:51:52,418 - WARNING - __main__ - Warning: reading only 2000 lines of Wikipedia dump
2020-03-04 13:51:52,488 - INFO - bin.wiki_entity_linking.wikipedia_processor - processed 2000 lines of Wikipedia XML dump
2020-03-04 13:51:52,489 - INFO - bin.wiki_entity_linking.wikipedia_processor - Finished. processed 2000 lines of Wikipedia XML dump
2020-03-04 13:51:52,493 - INFO - __main__ - STEP 3: Calculating and writing entity frequencies to knowledge-base/en/entity_freq.csv
2020-03-04 13:51:52,495 - INFO - __main__ - STEP 4: Parsing and writing Wikidata entity definitions to knowledge-base/en/entity_defs.csv
2020-03-04 13:51:52,496 - WARNING - __main__ - Warning: reading only 3000 lines of Wikidata dump
2020-03-04 13:52:00,875 - INFO - bin.wiki_entity_linking.wikidata_processor - Finished. Processed 3000 lines of WikiData JSON dump
2020-03-04 13:52:00,878 - INFO - __main__ - STEP 4b: Writing Wikidata entity aliases to knowledge-base/en/entity_alias.csv
2020-03-04 13:52:00,882 - INFO - __main__ - STEP 4c: Writing Wikidata entity descriptions to knowledge-base/en/entity_descriptions.csv
2020-03-04 13:52:00,885 - INFO - __main__ - STEP 5: Parsing and writing Wikipedia gold entities to knowledge-base/en/gold_entities.jsonl
2020-03-04 13:52:00,886 - WARNING - __main__ - Warning: reading only 20000 lines of Wikipedia dump
2020-03-04 13:55:26,294 - INFO - bin.wiki_entity_linking.wikipedia_processor - Processed 10000 articles
2020-03-04 13:58:28,323 - INFO - bin.wiki_entity_linking.wikipedia_processor - Processed 20000 articles
2020-03-04 13:58:28,323 - INFO - bin.wiki_entity_linking.wikipedia_processor - Finished. Processed 20000 articles
2020-03-04 13:58:28,326 - INFO - __main__ - STEP 6: Creating the KB at knowledge-base/en/kb
2020-03-04 13:58:28,334 - INFO - bin.wiki_entity_linking.kb_creator - Loaded pretrained vectors of size 300
2020-03-04 13:58:28,334 - INFO - bin.wiki_entity_linking.kb_creator - Filtering entities with fewer than 1 mentions
2020-03-04 13:58:28,336 - INFO - bin.wiki_entity_linking.kb_creator - Kept 2 entities from the set of 2760
2020-03-04 13:58:28,336 - INFO - bin.wiki_entity_linking.kb_creator - Training entity encoder
2020-03-04 13:58:28,479 - INFO - bin.wiki_entity_linking.train_descriptions - loss: 0.9442245960235596
2020-03-04 13:58:28,515 - INFO - bin.wiki_entity_linking.train_descriptions - loss: 0.842606782913208
2020-03-04 13:58:28,550 - INFO - bin.wiki_entity_linking.train_descriptions - loss: 0.7469222545623779
2020-03-04 13:58:28,590 - INFO - bin.wiki_entity_linking.train_descriptions - loss: 0.6605334281921387
2020-03-04 13:58:28,626 - INFO - bin.wiki_entity_linking.train_descriptions - loss: 0.5846852660179138
2020-03-04 13:58:28,626 - INFO - bin.wiki_entity_linking.train_descriptions - Trained entity descriptions on 10 (non-unique) descriptions across 5 epochs
2020-03-04 13:58:28,626 - INFO - bin.wiki_entity_linking.train_descriptions - Final loss: 0.5846852660179138
2020-03-04 13:58:28,626 - INFO - bin.wiki_entity_linking.kb_creator - Getting entity embeddings
2020-03-04 13:58:28,646 - INFO - bin.wiki_entity_linking.train_descriptions - Encoded: 2 entities
2020-03-04 13:58:28,647 - INFO - bin.wiki_entity_linking.kb_creator - Adding 2 entities
2020-03-04 13:58:28,647 - INFO - bin.wiki_entity_linking.kb_creator - Adding aliases from Wikipedia and Wikidata
2020-03-04 13:58:28,647 - INFO - bin.wiki_entity_linking.kb_creator - Adding WP aliases
2020-03-04 13:58:28,649 - INFO - __main__ - kb entities: 2
2020-03-04 13:58:28,650 - INFO - __main__ - kb aliases: 0
2020-03-04 13:58:33,069 - INFO - __main__ - Done!
```

## Info about spaCy
* **spaCy version:** 2.2.3
* **Platform:** Linux-5.3.0-40-generic-x86_64-with-Ubuntu-19.10-eoan
* **Python version:** 3.7.5
* **Models:** en

**Comment by svlandeg** [comment]
Hm, that is annoying indeed. It looks like the IO runs into a corrupt line in the Wikipedia dump. When did you download the dump, and how big is it (packed) on file?

At this point I'm not sure whether the culprit is with Wikipedia, the file system (download gone corrupt) or the NEL script. So I'll have a look and see whether I can replicate this. 

Thanks for trying with the limited parameters! Good to see that works at least.

**Comment by kprice-aktors** [comment]
Thanks for responding so quickly! The compressed Wikipedia dump is 16.7 GB on the disk, and was downloaded at 16:44 (Helsinki Time) on March 3rd 2020.

**Comment by svlandeg** [comment]
I just ran this for an hour and a half, and got passed 650 000 000 lines without crashing, so well over your point of failure at 350 000 000. I had downloaded a new Wikipedia distribution today. On a previous run with an older version of WP, it took me less than 3 hours to process 1 094 894 680 lines of Wikipedia XML dump. As I can't replicate your issue, I'm not sure how to proceed. Your script crashed on ` file.readline()` which does seem to imply trouble with the file/IO itself, and not this specific parsing script...

Can you try rerunning with the new dump you downloaded? 

Just as an FYI, there's also a new version of this module available if you download & install spaCy from source. Then you'll have the changes from [this recent PR](https://github.com/explosion/spaCy/pull/4811). If you can wait or don't want to install from source, this will also be released as part of our upcoming 2.4 patch release. 
To be honest, I don't think that should influence your current problems, though it doesn't hurt to try. The downstream NEL training itself would definitely run more smoothly with the new version though.

**Comment by kprice-aktors** [comment]
Alright, I'm re-running everything using the new dump. So far it seems to have been able to read 375 000 000 lines without crashing. So the older dump may have been corrupted after all. I am not sure what could have caused that. I did download a bunch of different language dumps consecutively (136). I am not sure if making that many requests to a server would affect the data or not.

**Comment by svlandeg** [comment]
Honestly, no idea. At least the file size you mentioned seemed to be correct. Let me know if the run finishes!

**Comment by kprice-aktors** [comment]
Alright, I encountered the same error again, but this time it seems to have occurred while processing the WikiData JSON dump.


```
2020-03-05 13:28:50,699 - INFO - bin.wiki_entity_linking.wikipedia_processor - processed 1150000000 lines of Wikipedia XML dump
2020-03-05 13:29:55,144 - INFO - bin.wiki_entity_linking.wikipedia_processor - processed 1154673507 lines of Wikipedia XML dump
2020-03-05 13:29:55,144 - INFO - bin.wiki_entity_linking.wikipedia_processor - Finished. processed 1154673507 lines of Wikipedia XML dump
2020-03-05 13:33:54,128 - INFO - __main__ - STEP 3: Calculating and writing entity frequencies to knowledge-base/en/entity_freq.csv
2020-03-05 13:35:46,791 - INFO - __main__ - STEP 4: Parsing and writing Wikidata entity definitions to knowledge-base/en/entity_defs.csv
2020-03-05 13:43:22,211 - INFO - bin.wiki_entity_linking.wikidata_processor - processed 500000 lines of WikiData JSON dump
Traceback (most recent call last):
  File "../.local/lib/python3.7/site-packages/bin/wiki_entity_linking/wikidata_pretrain_kb.py", line 179, in <module>
    plac.call(main)
  File "/home/ihsai/.local/lib/python3.7/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/home/ihsai/.local/lib/python3.7/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "../.local/lib/python3.7/site-packages/bin/wiki_entity_linking/wikidata_pretrain_kb.py", line 121, in main
    parse_descr=(not descr_from_wp),
  File "/home/ihsai/.local/lib/python3.7/site-packages/bin/wiki_entity_linking/wikidata_processor.py", line 45, in read_wikidata_entities_json
    for cnt, line in enumerate(file):
  File "/usr/lib/python3.7/bz2.py", line 215, in readline
    return self._buffer.readline(size)
  File "/usr/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.7/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream
```
This dump was downloaded on March 3rd 2020 at 14:33 Helsinki Time.  The compressed dump is 47.4 GB. Once again, I will try downloading this dump again, but I am very annoyed to have to go run all this code again.

**Comment by svlandeg** [comment]
>but I am very annoyed to have to go run all this code again.

You shouldn't have to - if you run the exact same command, the script will find the intermediary files and rerun from those.

It looks like there was indeed some corruption going on either on your disk or with the network connection when downloading all of these files originally. It doesn't look like a bug in the script on our end, so I'll close this issue for now. If you run into other problems with the NEL scripts, feel free to open another issue.
