### ISSUE TITLE
OutOfMemoryError - spacy pretrain

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5173]
I have a large file of text (jsonl file) with approximately 1.6 million examples and tried to run the spacy pretrain on it I get this error.

Any suggestions for dealing with this many samples? 

```
============== Pre-training tok2vec layer - starting at epoch 0 ==============[0m
  #      # Words   Total Loss     Loss    w/s
Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda\envs\spacy\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "D:\Anaconda\envs\spacy\lib\site-packages\plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "D:\Anaconda\envs\spacy\lib\site-packages\plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\cli\pretrain.py", line 239, in pretrain
    model, docs, optimizer, objective=loss_func, drop=dropout
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\cli\pretrain.py", line 268, in make_update
    backprop(gradients, sgd=optimizer)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\_ml.py", line 839, in mlm_backward
    return backprop(d_output, sgd=sgd)
  File "D:\Anaconda\envs\spacy\lib\site-packages\thinc\neural\_classes\feed_forward.py", line 53, in continue_update
    gradient = callback(gradient, sgd)
  File "ops.pyx", line 128, in thinc.neural.ops.Ops.dropout.wrap_backprop.finish_update
  File "D:\Anaconda\envs\spacy\lib\site-packages\thinc\neural\_classes\layernorm.py", line 73, in finish_update
    dist, sum_dy, sum_dy_dist = _get_d_moments(self.ops, dy, X, mu)
  File "D:\Anaconda\envs\spacy\lib\site-packages\thinc\neural\_classes\layernorm.py", line 124, in _get_d_moments
    ops.xp.sum(dy * dist, axis=1, keepdims=True),
  File "cupy\core\core.pyx", line 990, in cupy.core.core.ndarray.__mul__
  File "cupy\core\_kernel.pyx", line 1006, in cupy.core._kernel.ufunc.__call__
  File "cupy\core\_kernel.pyx", line 510, in cupy.core._kernel._get_out_args
  File "cupy\core\core.pyx", line 136, in cupy.core.core.ndarray.__init__
  File "cupy\cuda\memory.pyx", line 557, in cupy.cuda.memory.alloc
  File "cupy\cuda\memory.pyx", line 1246, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy\cuda\memory.pyx", line 1267, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy\cuda\memory.pyx", line 941, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy\cuda\memory.pyx", line 961, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy\cuda\memory.pyx", line 1206, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 209,794,048 bytes (allocated so far: 5,224,376,320 bytes).
```

**Comment by erotavlas** [comment]
I was able to overcome this by specifying the `--batch-size, -bs` parameter with a smaller size like 1000.  It seems to use GPU by default and I only have 6GB.  I was also able to run it on a system with 96GB RAM without the GPU and default batch size.  So far it seems to be working.  Will post again if it doesn't.
