### ISSUE TITLE
KeyError: 'speed'

### ISSUE THREAD

**Issue by mirfan899** [explosion/spaCy#5242]
When I try to train the Urdu language model it throws the following error. I had trained the model with spacy 2.0 and there was no issue. I've compiled the spacy from the source using the master branch and getting the following error.

```shell
python -m spacy train ur models data/universal_dependencies_urdu/ur-ud-train.json data/universal_dependencies_urdu/ur-ud-dev.json -p 'tagger,parser' -v models
Training pipeline: ['tagger', 'parser']
Starting with blank model 'ur'
Loading vector from model 'models'
Counting training words (limit=0)
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py:193: UserWarning: [W022] Training a new part-of-speech tagger using a model with no lemmatization rules or data. This means that the trained model may not be able to lemmatize correctly. If this is intentional or the language you're using doesn't have lemmatization data, you can ignore this warning by setting SPACY_WARNING_IGNORE=W022. If this is surprising, make sure you have the spacy-lookups-data package installed.
  "__main__", mod_spec)

Itn  Tag Loss    Tag %    Dep Loss    UAS     LAS    Token %  CPU WPS
---  ---------  --------  ---------  ------  ------  -------  -------
⚠ Aborting and saving the final best model. Encountered exception:                                                                                                                                   
[E167] Unknown morphological feature: 'ConjType' (9141427322507498425). This can
happen if the tagger was trained with a different set of morphological features.
If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mirfan/PycharmProjects/urdu-resources/spaCy/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/mirfan/PycharmProjects/urdu-resources/spaCy/spacy/cli/train.py", line 573, in train
    final_meta["speed"].update(meta["speed"])
KeyError: 'speed'
```

## Your Environment

* Operating System: macOS
* Python Version Used: 3.7.4
* spaCy Version Used: 2.2.4 (master branch)

**Comment by adrianeboyd** [comment]
The `speed` error is a secondary/minor bug (fixed in #5186) and the actual error is the one shown first:

```
⚠ Aborting and saving the final best model. Encountered exception:                                                                                                                                   
[E167] Unknown morphological feature: 'ConjType' (9141427322507498425). This can
happen if the tagger was trained with a different set of morphological features.
If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate
```

By default, it's using the tag map from https://github.com/explosion/spaCy/blob/d107afcffbf50aff63a7e15ecb3cf3f5a6fedbb7/spacy/lang/ur/tag_map.py, which has some morphological tags that aren't supported in v2.2 and it probably doesn't contain the right fine-grained tags from your corpus, either. (The support for morphological tags has been under development and the tag maps for languages where we don't provide models haven't been tested and updated as frequently as the others.)

Use the `--tag-map-path` with `spacy train` to specify a JSON-formatted tag map that maps the XPOS tags in your corpus to UPOS tags. It should look like this:

```
{
  "NNP":{
    "POS":"PROPN"
  },
  "PSP":{
    "POS":"ADP"
  },
  ...
}
```

You can check whether your tag map contains all the fine-grained tags by using `spacy debug-data` with the same `--tag-map-path` option. I don't think it checks the validity of the morphological features, but it will show an error if a fine-grained tag is found without a UPOS mapping.

**Comment by mirfan899** [comment]
Yes, you are right. I checked it with `debug-data` and shows errors related to tags not found in spacy `ur` tag map.

**Comment by mirfan899** [comment]
I'm using the Universal dependencies dataset for training the model. 
https://github.com/UniversalDependencies/UD_Urdu-UDTB/tree/master

**Comment by mirfan899** [comment]
After updating the tag it throws the same error before. Here is `debug-data` output. 
```shell

=========================== Data format validation ===========================
✔ Corpus is loadable

=============================== Training stats ===============================
Training pipeline: tagger, parser
Starting with blank model 'ur'
4043 training docs
552 evaluation docs
✔ No overlap between training and evaluation data

============================== Vocab & Vectors ==============================
ℹ 108690 total words in the data (9547 unique)
ℹ No word vectors present in the model

=========================== Part-of-speech Tagging ===========================
ℹ 40 labels in data (90 labels in tag map)
✔ All labels present in tag map for language 'ur'

============================= Dependency Parsing =============================
ℹ Found 4043 sentences with an average length of 26.9 words.
⚠ The training data contains 1.04 sentences per document. When there
are very few documents containing more than one sentence, the parser will not
learn how to segment longer texts into sentences.
ℹ Found 931 nonprojective train sentences
ℹ Found 127 nonprojective dev sentences
ℹ 25 labels in train data
ℹ 182 labels in projectivized train data
⚠ Low number of examples for label 'vocative' (15)
⚠ Low number of examples for 142 labels in the projectivized dependency
trees used for training. You may want to projectivize labels such as punct
before training in order to improve parser performance.

================================== Summary ==================================
✔ 3 checks passed
⚠ 5 warnings

```

**Comment by mirfan899** [comment]
It seems I've to remove all the morph features form `tag_map.py` file

**Comment by mirfan899** [comment]
Okay, after removing the morph rules from `tag_map.py` and adding the missing tags fixed the 
 issue.
