### ISSUE TITLE
Is it possible to Run wikidata_train_entity_linker.py on GPU

### ISSUE THREAD

**Issue by ramialbatal** [explosion/spaCy#5270]
I am trying to train the entity linker on wikidata/wikipedia, but would like to run the wikidata_train_entity_linker.py on GPU.

I have tried to tried to follow the advise mentioned here to install [spacy[cuda100]](https://github.com/explosion/spaCy/issues/3682#issuecomment-489917991).

And I added `spacy.require_gpu()` at the top of the wikidata_train_entity_linker.py code.

But when I run the training, I am getting this error:

```
2020-04-03 21:16:25,045 - INFO - __main__ - Creating Entity Linker with Wikipedia and WikiData
2020-04-03 21:16:25,046 - INFO - __main__ - STEP 1a: Loading model from kb/nlp_kb
2020-04-03 21:16:39,886 - INFO - __main__ - Original NLP pipeline has following pipeline components: ['tagger', 'parser', 'ner']
2020-04-03 21:16:39,886 - INFO - __main__ - STEP 1b: Loading KB from kb/kb
2020-04-03 21:16:43,806 - INFO - __main__ - STEP 2: Reading training & dev dataset from kb/gold_entities.jsonl
2020-04-03 21:18:53,030 - INFO - __main__ - Training set has 6099890 articles, limit set to roughly 50000 articles per epoch
2020-04-03 21:18:53,030 - INFO - __main__ - Dev set has 678808 articles, limit set to rougly 10000 articles for evaluation
2020-04-03 21:18:53,045 - INFO - __main__ - STEP 3: Creating and training an Entity Linking pipe for 10 epochs
2020-04-03 21:18:53,592 - INFO - __main__ - Dev Baseline Accuracies:
Traceback (most recent call last):                            
  File "wikidata_train_entity_linker.py", line 173, in <module>
    plac.call(main)
  File "/home/myhome/.local/share/virtualenvs/spaCy-A-7uhj7q/lib/python3.6/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/home/myhome/.local/share/virtualenvs/spaCy-A-7uhj7q/lib/python3.6/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "wikidata_train_entity_linker.py", line 117, in main
    measure_performance(dev_data, kb, el_pipe, baseline=True, context=False, dev_limit=len(dev_indices))
  File "/home/myhome/.local/share/virtualenvs/spaCy-A-7uhj7q/lib/python3.6/site-packages/bin/wiki_entity_linking/entity_linker_evaluation.py", line 103, in measure_performance
    for doc, gold in tqdm(dev_data, total=dev_limit, leave=False, desc='Processing dev data'):
  File "/home/myhome/.local/share/virtualenvs/spaCy-A-7uhj7q/lib/python3.6/site-packages/tqdm/std.py", line 1127, in __iter__
    for obj in iterable:
  File "/home/myhome/.local/share/virtualenvs/spaCy-A-7uhj7q/lib/python3.6/site-packages/bin/wiki_entity_linking/wikipedia_processor.py", line 501, in read_el_docs_golds
    for doc, entities in zip(docs, entities_list):
  File "/home/myhome/.local/share/virtualenvs/spaCy-A-7uhj7q/lib/python3.6/site-packages/spacy/language.py", line 819, in pipe
    for doc in docs:
  File "pipes.pyx", line 1290, in pipe
  File "pipes.pyx", line 1369, in spacy.pipeline.pipes.EntityLinker.predict
TypeError: list indices must be integers or slices, not cupy.core.core.ndarray
```

I wonder if I am missing something or training on GPU is not an option?

## Your Environment
* **spaCy version:** 2.2.4
* **Platform:** Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.9

**Comment by svlandeg** [comment]
Unfortunately, these example Wikipedia scripts are not yet supporting GPU... But pull requests are welcome! ;-)

**Comment by svlandeg** [comment]
Unfortunately we won't really be able to maintain these Wikipedia-parsing scripts. They were never really part of the core library, and mainly served to show-case how an Entity Linking module could work in practice. However, for most use-cases it makes sense to prune the Knowledge base according to the project requirements, as the data sizes quickly become unnecessarily large. So some custom adaptations of these scripts might always be necessary and it's difficult to cater for all use-cases with just one version of them.

Because this was really just an example use-case, we've moved the code to https://github.com/explosion/projects/tree/master/nel-wikipedia and I'll go ahead and close this issue.
