### ISSUE TITLE
AttributeError when trying to import spacy

### ISSUE THREAD

**Issue by DanielSegal1** [explosion/spaCy#5301]
## How to reproduce the behaviour
`import spacy`

## Your Environment

* **spaCy version:** 2.2.4
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.8.2
* Environment Information: PyCharm CE 3.1.4

I'm getting the following error when trying to import spacy:
`AttributeError: 'WindowsPath' object has no attribute 'read_text'`
I treid installing new python but that didnt help, I reinstalled spacy which didn't help either.

The full stack trace:

``` 
Traceback (most recent call last):
  File "E:/realProject/ttt.py", line 1, in <module>
    import spacy
  File "C:\Users\sbhtk\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "C:\Users\sbhtk\AppData\Local\Programs\Python\Python38\lib\site-packages\thinc\__init__.py", line 8, in <module>
    from ._registry import registry
  File "C:\Users\sbhtk\AppData\Local\Programs\Python\Python38\lib\site-packages\thinc\_registry.py", line 1, in <module>
    import catalogue
  File "C:\Users\sbhtk\AppData\Local\Programs\Python\Python38\lib\site-packages\catalogue.py", line 18, in <module>
    AVAILABLE_ENTRY_POINTS = importlib_metadata.entry_points()
  File "C:\Users\sbhtk\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 542, in entry_points
    ordered = sorted(eps, key=by_group)
  File "C:\Users\sbhtk\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 540, in <genexpr>
    dist.entry_points for dist in distributions())
  File "C:\Users\sbhtk\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 240, in entry_points
    return EntryPoint._from_text(self.read_text('entry_points.txt'))
  File "C:\Users\sbhtk\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 491, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
AttributeError: 'WindowsPath' object has no attribute 'read_text'
```

**Comment by svlandeg** [comment]
Hi @DanielSegal1, could you paste the full error stack trace?

**Comment by DanielSegal1** [comment]
@svlandeg Added, I would like to mention that when installing spacy I got 3 warnings regarding paths I dont have on my PATH and recommended me to add them to my PATH

**Comment by svlandeg** [comment]
It looks like you're not running this in an isolated environment, so maybe there are some interactions with previously installed packages?

In general, it's a good idea to start a clean virtual environment `venv` (or new `conda` env). Then try installing spacy from scratch. If you still get errors during install, could you paste them here as well?
