### ISSUE TITLE
TypeError: '>' not supported between instances of 'dict' and 'dict'

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5305]
spacy version: `2.2.4`

command: `python -m spacy train`

Error: TypeError: '>' not supported between instances of 'dict' and 'dict'
When saving best model

```
 98    157.185  93.324  94.212  93.766  100.000    26623    31692
 99    133.271  93.464  94.286  93.873  100.000    26254    32800
100    148.529  93.455  94.139  93.796  100.000    25557    32948
✔ Saved model to output directory
G:\train3\models\model-final
⠼ Creating best model...
Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda\envs\spacy\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "D:\Anaconda\envs\spacy\lib\site-packages\plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "D:\Anaconda\envs\spacy\lib\site-packages\plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\cli\train.py", line 583, in train
    best_model_path = _collate_best_model(final_meta, output_path, best_pipes)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\cli\train.py", line 643, in _collate_best_model
    bests[component] = _find_best(output_path, component)
  File "D:\Anaconda\envs\spacy\lib\site-packages\spacy\cli\train.py", line 666, in _find_best
    return max(accuracies)[1]
TypeError: '>' not supported between instances of 'dict' and 'dict'
```

**Comment by adrianeboyd** [comment]
This is fixed in #5186.

**Comment by erotavlas** [comment]
@adrianeboyd  How can I overcome this?  Do you have a nightly release I can install with the mentioned fix? I tried `pip install spacy-nightly` but it says version 2.1.

**Comment by svlandeg** [comment]
We don't have a current spacy-nightly available right now, I'm afraid. But you have two other options:
- Build the current `master` branch from source (I don't think this is necessary - it may be a bit of overhead if you haven't done this before)
- Apply the [changes](https://github.com/explosion/spaCy/pull/5186/files) linked by Adriane to your local `spacy/cli/train.py` file. This should hopefully be quite straightforward: just make sure to add these 5 lines to the correct places.
