### ISSUE TITLE
 CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5336]
Installed spacy to new conda environment using

`pip install -U spacy[cuda80]`

Then tried running pretraining but it complained no module named `torch` so I install pytorch but had to install an earlier version for cuda 8.0

`conda install pytorch=0.4.1 cuda80 -c pytorch`

Then tried to run pretrain again and got this error

```
(spacygpu) E:\>python -m spacy pretrain E:\trainingdata\rawtext_p
reprocessed.jsonl "E:\spacy_word2vecmodel_1.0.0.5" "E:\spacypret
rained" --use-vectors
? Using GPU
? Saved settings to config.json
←[2K? Loaded input texts
←[2K? Loaded model 'E:\spacy_word2vecmodel_1.0.0.5'
Traceback (most recent call last):
  File "C:\Users\username\.conda\envs\spacygpu\lib\runpy.py", line 193, in _ru
n_module_as_main
    "__main__", mod_spec)
  File "C:\Users\username\.conda\envs\spacygpu\lib\runpy.py", line 85, in _run
_code
    exec(code, run_globals)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\spacy\__main_
_.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\plac_core.py"
, line 367, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\plac_core.py"
, line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\spacy\cli\pre
train.py", line 175, in pretrain
    cnn_maxout_pieces=cnn_pieces,  # If set to 1, use Mish activation.
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\spacy\cli\pre
train.py", line 348, in create_pretraining_model
    model.begin_training([nlp.make_doc("Give it a doc to infer shapes")])
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\check.p
y", line 156, in checked_function
    return wrapped(*args, **kwargs)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\neural\
_classes\model.py", line 122, in begin_training
    hook(self, train_X, train_y)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 353, in on_data
    hook(child, X, y)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\neural\
_classes\feed_forward.py", line 11, in _run_child_hooks
    hook(layer, X, y)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 324, in _with_flatten_on_data
    hook(layer, X, y)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\neural\
_classes\feed_forward.py", line 11, in _run_child_hooks
    hook(layer, X, y)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 353, in on_data
    hook(child, X, y)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\neural\
_classes\feed_forward.py", line 12, in _run_child_hooks
    X = layer(X)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\neural\
_classes\model.py", line 167, in __call__
    return self.predict(x)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\neural\
_classes\model.py", line 131, in predict
    y, _ = self.begin_update(X, drop=None)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 163, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 163, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 256, in wrap
    output = func(*args, **kwargs)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 163, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 163, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 256, in wrap
    output = func(*args, **kwargs)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 163, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 163, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 256, in wrap
    output = func(*args, **kwargs)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 163, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 163, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\api.py"
, line 256, in wrap
    output = func(*args, **kwargs)
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\thinc\neural\
_classes\static_vectors.py", line 73, in begin_update
    dotted = self.ops.gemm(vectors, self.W, trans2=True)
  File "ops.pyx", line 986, in thinc.neural.ops.CupyOps.gemm
  File "C:\Users\username\.conda\envs\spacygpu\lib\site-packages\cupy\linalg\p
roduct.py", line 35, in dot
    return a.dot(b, out)
  File "cupy\core\core.pyx", line 1381, in cupy.core.core.ndarray.dot
  File "cupy\core\core.pyx", line 2267, in cupy.core.core.dot
  File "cupy\core\core.pyx", line 2663, in cupy.core.core.tensordot_core
  File "cupy\cuda\cublas.pyx", line 930, in cupy.cuda.cublas.sgemmEx
  File "cupy\cuda\cublas.pyx", line 311, in cupy.cuda.cublas.check_status
cupy.cuda.cublas.CUBLASError: CUBLAS_STATUS_EXECUTION_FAILED
```

OS = Windows 7
spacy version = 2.2.4

**Comment by adrianeboyd** [comment]
The `spacy pretrain` script is still a bit rough around the edges. I think if you're not using `bilstm_depth` you can safely comment out the lines that import torch.
