### ISSUE TITLE
local model does not link/package properly

### ISSUE THREAD

**Issue by koaning** [explosion/spaCy#5338]
## How to reproduce the behaviour

I am creating a model with a pattern matcher. These are the rules;

```json
{"label":"PROGLANG","pattern":[{"LOWER":"golang"}]}
{"label":"PROGLANG","pattern":[{"LOWER":"go", "POS": {"NOT_IN": "VERB"}}]}
{"label":"PROGLANG","pattern":[{"LOWER":"sql"}]}
{"label":"PROGLANG","pattern":[{"LOWER":"python"}]}
{"label":"PROGLANG","pattern":[{"LOWER":{"REGEX":"(python\\d+\\.?\\d*.?\\d*)"}}]}
{"label":"PROGLANG","pattern":[{"LOWER":"python"}, {"TEXT":{"REGEX":"(\\d+\\.?\\d*.?\\d*)"}}]}
{"label":"PROGLANG","pattern":[{"LOWER": {"IN": ["node", "nodejs", "js", "javascript"]}}]}
{"label":"PROGLANG","pattern":[{"LOWER": {"IN": ["node", "nodejs", "js", "javascript"]}}, {"TEXT": {"REGEX": "(\\d+\\.?\\d*.?\\d*)"}}]}
```

This is the script that creates the model and saves it to disk. 

```python
import pathlib

import spacy
from spacy.lang.en import English
from spacy.pipeline import EntityRuler


if __name__ == "__main__":
    path = pathlib.Path('matcher-rules/proglang.jsonl')
    # note that we could have also used `English()` as a starting point
    # if our matching rules weren't using part of speech 
    nlp = spacy.load("en_core_web_sm")

    # create a new rule based NER detector loading in settings from disk
    ruler = EntityRuler(nlp).from_disk(path)
    print(f"Will now create model for {path}.")

    # add the detector to the model
    nlp.add_pipe(ruler, name="proglang-detector")

    # save the model to disk
    nlp.meta["name"] = "custom-proglang-model"
    nlp.to_disk(nlp.meta["name"])
    print(f"spaCy model saved over at {nlp.meta['name']}.")
```

I now create this model and link it, because linking feels like the formal thing to do. 

```
> python mkmodel.py
Will now create model for matcher-rules/proglang.jsonl.
spaCy model saved over at custom-proglang-model.
> python -m spacy link custom-proglang-model proglang-model --force
✔ Linking successful
You can now load the model via spacy.load('proglang-model')
```

However, when I now load the model, stuff starts breaking. 

```
(venv) ➜  rasa-spacy-integration git:(master) ✗ python
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.load("proglang-model") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/util.py", line 162, in load_model
    return load_model_from_link(name, **overrides)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/util.py", line 176, in load_model_from_link
    cls = import_file(name, path)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/compat.py", line 157, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/data/proglang-model/__init__.py'
```

The irony is that if I directly point to the folder (which isn't what you'd want to recommend to folks for production ... I think) then it works just fine. 

```
>>> spacy.load("custom-proglang-model")
<spacy.lang.en.English object at 0x1221314e0>
```

This is independant of the `nlp.meta["name"] = "custom-proglang-model"` line in `mkmodel.py`. 

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Darwin-19.3.0-x86_64-i386-64bit
* **Python version:** 3.6.8

**Comment by adrianeboyd** [comment]
Hmm, yeah, `spacy link` is definitely not working as advertised here.

I would actually recommend against using links. We're planning to get rid of them entirely because adding symlinks within the spacy install directory can be problematic due to permissions issues and without them, the spacy package could be zip safe. (I think those are the main points anyway, Ines is the expert here.)

You can use `spacy package` to create a model packages that you can install with like any other package (and then link, if you really want).

There's nothing wrong with loading from a path with `spacy.load()`, but for production using model packages is probably the better option.

**Comment by koaning** [comment]
Ah. I was afraid it was something like that. I tried packages too but it had similar issues. Will fetch that code now.

**Comment by koaning** [comment]
It's showing some other strange behavior now. 

```
> python mkmodel.py
Will now create model for matcher-rules/proglang.jsonl.
spaCy model saved over at custom-proglang-model.
> python -m spacy package custom-proglang-model . --force
✔ Loaded meta.json from file
custom-proglang-model/meta.json
✔ Successfully created package 'en_custom-proglang-model-2.2.5'
en_custom-proglang-model-2.2.5
To build the package, run `python setup.py sdist` in this directory.
> cd en_custom-proglang-model-2.2.5
> python setup.py sdist
> cd .. 
```

This should install everything. But now when I import it via python. 

```
> python
(venv) ➜  rasa-spacy-integration git:(master) ✗ python
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.load("en_custom-proglang-model-2.2.5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/util.py", line 166, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/util.py", line 211, in load_model_from_path
    return nlp.from_disk(model_path, exclude=disable)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/language.py", line 947, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/util.py", line 654, in from_disk
    reader(path / key)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/language.py", line 934, in <lambda>
    p, exclude=["vocab"]
  File "tokenizer.pyx", line 526, in spacy.tokenizer.Tokenizer.from_disk
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'en_custom-proglang-model-2.2.5/tokenizer'
```

I can confirm that there is no `tokenizer` folder. But is this something I need to manually do? I'd assumed that `nlp.to_disk` would take care of that.

**Comment by adrianeboyd** [comment]
`nlp.to_disk()` should definitely save the tokenizer. I think you're accidentally loading a local directory from the package rather than the model package itself and I think you're missing a step where you install the model. There shouldn't be a version number or dashes in the model you're loading.

Try this: pick a new model name without dashes, package it as you did before (this creates an archive in `dist/`), and then install the model package from the `dist` directory with pip.

**Comment by koaning** [comment]
I now run this script to create the model. 

```python
import pathlib

import spacy
from spacy.lang.en import English
from spacy.pipeline import EntityRuler


if __name__ == "__main__":
    path = pathlib.Path('matcher-rules/proglang.jsonl')
    # note that we could have also used `English()` as a starting point
    # if our matching rules weren't using part of speech 
    nlp = spacy.load("en_core_web_sm")

    # create a new rule based NER detector loading in settings from disk
    ruler = EntityRuler(nlp).from_disk(path)
    print(f"Will now create model for {path}.")

    # add the detector to the model
    nlp.add_pipe(ruler, name="proglang")

    # save the model to disk
    nlp.meta["name"] = "proglang"
    nlp.to_disk(nlp.meta["name"])
    print(f"spaCy model saved over at {nlp.meta['name']}.")
```

This creates the `proglang` folder. When I now run this; 

```
> python -m spacy package proglang . --force
✔ Loaded meta.json from file
proglang/meta.json
✔ Successfully created package 'en_proglang-2.2.5'
en_proglang-2.2.5
To build the package, run `python setup.py sdist` in this directory.
```

It seems to add `en` to it. Let's check the folders.

```
> tree en_proglang-2.2.5
en_proglang-2.2.5
├── MANIFEST.in
├── dist
│   └── en_proglang-2.2.5.tar.gz
├── en_proglang
│   ├── __init__.py
│   └── en_proglang-2.2.5
│       ├── meta.json
│       ├── ner
│       │   ├── cfg
│       │   ├── model
│       │   └── moves
│       ├── parser
│       │   ├── cfg
│       │   ├── model
│       │   └── moves
│       ├── proglang
│       │   ├── cfg
│       │   └── patterns.jsonl
│       ├── tagger
│       │   ├── cfg
│       │   ├── model
│       │   └── tag_map
│       ├── tokenizer
│       └── vocab
│           ├── key2row
│           ├── lexemes.bin
│           ├── lookups.bin
│           ├── strings.json
│           └── vectors
├── en_proglang.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── not-zip-safe
│   ├── requires.txt
│   └── top_level.txt
├── meta.json
└── setup.py
```

Ok. Then I run `pip` to package. 

```
> python -m pip install en_proglang-2.2.5/dist/en_proglang-2.2.5.tar.gz
Processing ./en_proglang-2.2.5/dist/en_proglang-2.2.5.tar.gz
Requirement already satisfied: spacy>=2.2.2 in ./venv/lib/python3.6/site-packages (from en-proglang==2.2.5) (2.2.4)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (1.0.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (3.0.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (4.45.0)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (1.0.2)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (1.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (2.23.0)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (0.4.1)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (0.6.0)
Requirement already satisfied: numpy>=1.15.0 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (1.18.2)
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (46.1.3)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (1.1.3)
Requirement already satisfied: thinc==7.4.0 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (7.4.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./venv/lib/python3.6/site-packages (from spacy>=2.2.2->en-proglang==2.2.5) (2.0.3)
Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in ./venv/lib/python3.6/site-packages (from catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->en-proglang==2.2.5) (1.6.0)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->en-proglang==2.2.5) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->en-proglang==2.2.5) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->en-proglang==2.2.5) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->en-proglang==2.2.5) (2020.4.5.1)
Requirement already satisfied: zipp>=0.5 in ./venv/lib/python3.6/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->en-proglang==2.2.5) (3.1.0)
Building wheels for collected packages: en-proglang
  Running setup.py bdist_wheel for en-proglang ... done
  Stored in directory: /Users/vincent/Library/Caches/pip/wheels/37/80/f5/1190457030b0cd85c181cac24cd78ffd52784071faee93b219
Successfully built en-proglang
Installing collected packages: en-proglang
  Found existing installation: en-proglang 2.2.5
    Uninstalling en-proglang-2.2.5:
      Successfully uninstalled en-proglang-2.2.5
Successfully installed en-proglang-2.2.5
```

It seems that `python -m spacy validate` does not detect it though. And unfortunately;

```
> python
>>> import spacy 

>>> spacy.load("en-proglang-2.2.5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en-proglang-2.2.5'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

>>> spacy.load("en-proglang")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Users/vincent/Development/rasa-spacy-integration/venv/lib/python3.6/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en-proglang'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
>>> exit()

```

**Comment by koaning** [comment]
Ah. But this does work: 

```
import spacy
spacy.load("proglang")
```

**Comment by koaning** [comment]
I *can* load in the model this way; 

```python
import spacy
spacy.load("proglang") 
```

But that is because I am directly pointing to the folder that is saved on disk, **not** the package.

**Comment by koaning** [comment]
More strange behavior. I figured removing all folders and starting from scratch might be a good "reset". 

This is `mkmodel.py` now; 

```python
import pathlib

import spacy
from spacy.lang.en import English
from spacy.pipeline import EntityRuler


if __name__ == "__main__":
    path = pathlib.Path('matcher-rules/proglang.jsonl')
    # note that we could have also used `English()` as a starting point
    # if our matching rules weren't using part of speech 
    nlp = spacy.load("en_core_web_sm")

    # create a new rule based NER detector loading in settings from disk
    ruler = EntityRuler(nlp).from_disk(path)
    print(f"Will now create model for {path}.")

    # add the detector to the model
    nlp.add_pipe(ruler, name="proglang")

    # save the model to disk
    nlp.meta["name"] = "proglang"
    nlp.to_disk(nlp.meta["name"])
    print(f"spaCy model saved over at {nlp.meta['name']}.")
```

And now when I run this; 

```
> python mkmodel.py; python -m spacy package proglang . --force; tree en_proglang-2.2.5
Will now create model for matcher-rules/proglang.jsonl.
spaCy model saved over at proglang.
✔ Loaded meta.json from file
proglang/meta.json
✔ Successfully created package 'en_proglang-2.2.5'
en_proglang-2.2.5
To build the package, run `python setup.py sdist` in this directory.
en_proglang-2.2.5
├── MANIFEST.in
├── en_proglang
│   ├── __init__.py
│   └── en_proglang-2.2.5
│       ├── meta.json
│       ├── ner
│       │   ├── cfg
│       │   ├── model
│       │   └── moves
│       ├── parser
│       │   ├── cfg
│       │   ├── model
│       │   └── moves
│       ├── proglang
│       │   ├── cfg
│       │   └── patterns.jsonl
│       ├── tagger
│       │   ├── cfg
│       │   ├── model
│       │   └── tag_map
│       ├── tokenizer
│       └── vocab
│           ├── key2row
│           ├── lexemes.bin
│           ├── lookups.bin
│           ├── strings.json
│           └── vectors
├── meta.json
└── setup.py

7 directories, 22 files
```

There's no `dist` folder anymore.

**Comment by adrianeboyd** [comment]
I think the installed package will be called `en_proglang`. After running `pip install dist/model.tar.gz` you should be able to find the directory for the installed package in `venv/lib/python3.x/site-packages` to double-check the name, too.

```
spacy.load("en_proglang")
```

As an alternative, you can also try importing the package directly:

```
import en_proglang
nlp = en_proglang.load()
```

You have to run `python setup.py sdist` to regenerate the dist folder.

**Comment by koaning** [comment]
That seems to work! Thanks! 

Is there a reason why `python -m spacy validate` still does not recognise it? 

I wonder if this process could be made easier though. If I don't include the `python mkmodel.py` needed to save to disk I need to run 5 commands. 

```
python -m spacy package proglang . --force
cd en_proglang-2.2.5
python setup.py sdist 
cd .. 
python -m pip install en_proglang-2.2.5/dist/sdist 
```

Does it make sense to add a flag to `spacy package`, such that the command becomes; 

```
python -m spacy package proglang . --force --install
```

**Comment by adrianeboyd** [comment]
To do this, `spacy validate` would have to search through every installed package to check whether it's a model or not. It looks like if you add it as a link it does check because the directory with the symlinks is easy to go through, but it doesn't search through every single python package. It does search for all the default/provided models as packages since it can refer to compatibility table with all the names.

I think `spacy package` should really just package. I think more typically people are packaging for release/distribution, not to install locally right then.

**Comment by koaning** [comment]
Fair enough. This work is part of a guide on how to get a custom spaCy pipeline to work inside of [Rasa](https://rasa.com/docs/) and I'll make sure I mention that final comment. 

The original error with `spacy link` is still an issue but the approach listed here will work for my usecase. I'll close the issue because it seems like `link` will eventually be deprecated. If anybody thinks this issue should remain open; feel free to re-open. 

@adrianeboyd thanks :) !
