### ISSUE TITLE
Potential bug: Pickling Error when reloading spacy en_core_web_sm 

### ISSUE THREAD

**Issue by clementyeehw** [explosion/spaCy#5353]
Hi, 

I have recently upgraded my spaCy from v2.1.6 to v2.2.4. When I tried to run sample codes for the first time using Spyder 3.7.3, the sample codes were executed successfully. When I re-ran the same sample codes, an exception is raised:

Reloaded modules: pkg_resources, pkg_resources.extern, pkg_resources._vendor, pkg_resources.extern.six, pkg_resources._vendor.six, pkg_resources.py31compat, pkg_resources.extern.appdirs, pkg_resources._vendor.packaging.__about__, pkg_resources.extern.packaging, pkg_resources.extern.packaging.version, pkg_resources.extern.packaging._structures, pkg_resources.extern.packaging.specifiers, pkg_resources.extern.packaging._compat, pkg_resources.extern.packaging.requirements, pkg_resources.extern.pyparsing, pkg_resources.extern.packaging.markers, pkg_resources.py2_warn, thinc, thinc.about, thinc._registry, catalogue, importlib_metadata, zipp, importlib_metadata._compat, thinc.neural, thinc.neural._classes, thinc.neural._classes.model, srsly, srsly._json_api, srsly.ujson, srsly.ujson.ujson, srsly.util, srsly._msgpack_api, srsly.msgpack, srsly.msgpack._version, srsly.msgpack.exceptions, srsly.msgpack._packer, srsly.msgpack._ext_type, srsly.msgpack.util, srsly.msgpack._unpacker, srsly.msgpack._msgpack_numpy, srsly._pickle_api, srsly.cloudpickle, srsly.cloudpickle.cloudpickle, thinc.neural.util, thinc.neural.train, thinc.neural.optimizers, thinc.neural.ops, thinc.linalg, blis, blis.cy, blis.py, thinc.neural._custom_kernels, thinc.neural._aligned_alloc, thinc.compat, thinc.neural.mem, thinc.check, thinc.extra, thinc.extra.wrapt, thinc.extra.wrapt.wrappers, thinc.extra.wrapt._wrappers, thinc.extra.wrapt.decorators, thinc.extra.wrapt.importer, thinc.exceptions, wasabi, wasabi.printer, wasabi.tables, wasabi.util, wasabi.traceback, thinc.v2v, thinc.neural._classes.affine, thinc.describe, thinc.neural._classes.relu, thinc.neural._classes.maxout, thinc.neural._classes.softmax, thinc.neural._classes.selu, thinc.neural._classes.mish, thinc.t2t, thinc.neural._classes.convolution, thinc.neural._classes.attention, thinc.neural._classes.rnn, thinc.api, thinc.neural._classes.function_layer, thinc.neural._classes.feed_forward, thinc.neural._lsuv, thinc.neural._classes.multiheaded_attention, thinc.t2v, thinc.neural.pooling, thinc.i2v, thinc.neural._classes.hash_embed, thinc.neural._classes.embed, thinc.neural._classes.static_vectors, thinc.extra.load_nlp, thinc.misc, thinc.neural._classes.batchnorm, thinc.neural._classes.layernorm, thinc.neural._classes.resnet, thinc.neural._classes.feature_extracter, thinc.linear, thinc.linear.linear, thinc.extra.search, thinc.neural._classes.difference, OpenSSL, OpenSSL.crypto, OpenSSL._util, OpenSSL.SSL, OpenSSL.version, thinc.extra.datasets, thinc.extra._vendorized, thinc.extra._vendorized.keras_data_utils, thinc.extra._vendorized.keras_generic_utils
Traceback (most recent call last):

  File "<ipython-input-5-26155a2c6d0a>", line 1, in <module>
    runfile('C:/Users/C_YEE/Dropbox/ESG Research/Energy Extractives/MarketLine/MarketLine.py', wdir='C:/Users/C_YEE/Dropbox/ESG Research/Energy Extractives/MarketLine')

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/C_YEE/Dropbox/ESG Research/Energy Extractives/MarketLine/MarketLine.py", line 585, in <module>
    nlp = spacy.load('en_core_web_sm')

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py", line 164, in load_model
    return load_model_from_package(name, **overrides)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py", line 185, in load_model_from_package
    return cls.load(**overrides)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\en_core_web_sm\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py", line 211, in load_model_from_path
    return nlp.from_disk(model_path, exclude=disable)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\language.py", line 947, in from_disk
    util.from_disk(path, deserializers, exclude)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py", line 654, in from_disk
    reader(path / key)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\language.py", line 942, in <lambda>
    p, exclude=["vocab"]

  File "pipes.pyx", line 661, in spacy.pipeline.pipes.Tagger.from_disk

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py", line 654, in from_disk
    reader(path / key)

  File "pipes.pyx", line 640, in spacy.pipeline.pipes.Tagger.from_disk.load_model

  File "pipes.pyx", line 548, in spacy.pipeline.pipes.Tagger.Model

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\_ml.py", line 585, in build_tagger_model
    pretrained_vectors=pretrained_vectors,

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\_ml.py", line 322, in Tok2Vec
    return _legacy_tok2vec.Tok2Vec(width, embed_size, **kwargs)

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\ml\_legacy_tok2vec.py", line 84, in Tok2Vec
    embed >> convolution ** conv_depth, pad=conv_depth

  File "C:\Users\C_YEE\AppData\Roaming\Python\Python37\site-packages\thinc\check.py", line 136, in checker
    return wrapped(*args, **kwargs)

  File "C:\Users\C_YEE\AppData\Roaming\Python\Python37\site-packages\thinc\neural\_classes\model.py", line 305, in __pow__
    return self._thread_local.operators["**"](self, other)

  File "C:\Users\C_YEE\AppData\Roaming\Python\Python37\site-packages\thinc\api.py", line 148, in clone
    layers.append(copy.deepcopy(orig))

  File "C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)

  File "C:\Users\C_YEE\AppData\Roaming\Python\Python37\site-packages\thinc\neural\_classes\model.py", line 98, in __getstate__
    return srsly.pickle_dumps(self.__dict__)

  File "C:\Users\C_YEE\AppData\Roaming\Python\Python37\site-packages\srsly\_pickle_api.py", line 14, in pickle_dumps
    return cloudpickle.dumps(data, protocol=protocol)

  File "C:\Users\C_YEE\AppData\Roaming\Python\Python37\site-packages\srsly\cloudpickle\cloudpickle.py", line 1125, in dumps
    cp.dump(obj)

  File "C:\Users\C_YEE\AppData\Roaming\Python\Python37\site-packages\srsly\cloudpickle\cloudpickle.py", line 486, in dump
    raise pickle.PicklingError(msg)

PicklingError: Could not pickle object as excessively deep recursion required.

Please assist.

**Comment by svlandeg** [comment]
Did you update your models when you updated the version of spaCy?

Can you share the output of running `python -m spacy validate` ?

**Comment by clementyeehw** [comment]
Yes I updated the models. Currently, I am using the English model. The outputs of the validation are as follows:

====================== Installed models (spaCy v2.2.4) ======================
ℹ spaCy installation:
C:\Users\C_YEE\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy

TYPE      NAME              MODEL             VERSION
package   es-core-news-sm   es_core_news_sm   2.2.5     ✔
package   en-core-web-sm    en_core_web_sm    2.2.5     ✔

**Comment by svlandeg** [comment]
Ok so basically you can't run `nlp = spacy.load('en_core_web_sm')` anymore? It used to work with spaCy v2.1.6 and now crashes with v2.2.4 ?

It looks like you're running in the base conda environment, is that correct? So you basically installed the new version "on top" of the old one? Were there any warnings when doing so?

Could you try installing spaCy (& the model) from scratch in an entirely new environment? It could be that some interdependencies are causing trouble here.

**Comment by clementyeehw** [comment]
Yes, your understanding is correct. The English model used to work in spaCy v2.1.6 (i.e. no errors despite repeated executions). However, this is causing an issue in v2.2.4. I am running it from my base conda environment and the upgrade was executed successfully from the get-go using pip install --U spacy

I tried running the same sample codes on Jupyter Notebook and the codes were run repeatedly with no errors detected. I also tried installing v2.2.4 from scratch in another machine and the codes ran in Spyder with no issues. Would you happen to have a copy of spaCy's requirements.txt so that I can investigate the dependencies in my current machine?

**Comment by svlandeg** [comment]
Sure, [here](https://github.com/explosion/spaCy/blob/26a90f011b8c21dfc06940579479aaff8006ff74/requirements.txt) is the version of `requirements.txt` that got shipped with 2.2.4.

Sorry that the upgrade is causing you trouble, but at least I'm happy to hear you got it working in a clean environment. I think in general it's probably a better idea to keep separate environments for different projects etc.

**Comment by clementyeehw** [comment]
Thanks for sending the requirements.txt.

It turns out that the latest release of cloudpickle v1.4.0 (27 Apr 2020) requires my Spyder IDE to be running on pyqt5 <= v5.12. Downgrading my existing pyqt5 version resolves the issue I have experienced in spaCy..

**Comment by svlandeg** [comment]
Ah, happy to hear it, and thanks for providing the details here! It may help other users encountering the same issue in the future :-)
