### ISSUE TITLE
ERROR: CUDA could not be found on your system.

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5368]
I double checked my CUDA installation is working, I'm able to access GPU from pytorch and `nvcc --version` command reports back correct version of CUDA (10.1)

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243
```

I also double checked my environment variables and they are all there.

However when I try and install spacy to my conda env using `pip install -U spacy[cuda] I get the following error

I even tried to install the visual studio redistributable package for C++ (v 14) because part of th error says that it might be missing.  And restarted the system but still same error

Not sure where to go from here

OS = Windows 10 x64

```
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\username\Miniconda3\envs\spacy\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER~1\\AppData\\Local\\Temp\\pip-install-6zcfise6\\cupy\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER~1\\AppData\\Local\\Temp\\pip-install-6zcfise6\\cupy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER~1\AppData\Local\Temp\pip-install-6zcfise6\cupy\pip-egg-info'
         cwd: C:\Users\USER~1\AppData\Local\Temp\pip-install-6zcfise6\cupy\
    Complete output (43 lines):
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'wheel_includes': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False, 'use_hip': False}

    -------- Configuring Module: cuda --------
    Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************

    Build Environment:
      Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\include', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\include']
      Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\lib\\x64', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\lib\\x64']
      nvcc command       : ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin/nvcc.exe']

    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
      NVTOOLSEXT_PATH : C:\Program Files\NVIDIA Corporation\NvToolsExt\
      NVCC            : (none)
      ROCM_HOME       : (none)

    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.

    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html

    ************************************************************

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER~1\AppData\Local\Temp\pip-install-6zcfise6\cupy\setup.py", line 128, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "C:\Users\USER~1\AppData\Local\Temp\pip-install-6zcfise6\cupy\cupy_setup_build.py", line 752, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "C:\Users\USER~1\AppData\Local\Temp\pip-install-6zcfise6\cupy\cupy_setup_build.py", line 500, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**EDIT:**

I tried specifying the exact version of cuda in the command `pip install -U spacy[cuda101]` and it seemed to install everything correctly (not errors) and I also installed pytorch after that with no problems but when I `import spacy` and do `spacy.require_gpu()` I get the following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\Miniconda3\envs\spacygpu\lib\site-packages\thinc\neural\util.py", line 87, in require_gpu
    raise ValueError("GPU is not accessible. Was the library installed correctly?")
ValueError: GPU is not accessible. Was the library installed correctly?
```
Everything checks out regarding CUDA, I even tried reinstalling CUDA and spacy and made sure antivirus was disabled.

**Comment by adrianeboyd** [comment]
Installing `cupy` through `spacy[cuda]` doesn't always end up with the right version in my experience. I checked and I see that the specific `spacy[cuda101]` and `spacy[cuda102]` are missing, we should add those, since I think otherwise the option is just ignored.

But all spacy needs is for you to have the correct version of `cupy` installed, so try installing `cupy-cuda101` directly. You can install spacy normally with `pip install spacy` either before or after installing `cupy` and spacy will automatically detect whether the `cupy` library is available when you try to enable the GPU.

**Comment by erotavlas** [comment]
Installation worked after, but wasn't able to access GPU because the machine (a VM) wasn't configured to expose the GPU correctly.
