### ISSUE TITLE
AttributeError: module 'cupy' has no attribute 'scatter_add'

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5380]
I tried running spacy pretrain on an Azure Ubuntu VM and am getting the following error.  

```
(spacy) username@testVM:~/Documents$ python -m spacy pretrain rawtext_preprocessed.jsonl spacy_word2vecmodel_1.0.0.5 models --n-iter 1000 --use-vectors
ℹ Using GPU
✔ Created output directory: models
✔ Saved settings to config.json
✔ Loaded input texts
✔ Loaded model 'spacy_word2vecmodel_1.0.0.5'

============== Pre-training tok2vec layer - starting at epoch 0 ==============
  #      # Words   Total Loss     Loss    w/s
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/spacy/cli/pretrain.py", line 239, in pretrain
    model, docs, optimizer, objective=loss_func, drop=dropout
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/spacy/cli/pretrain.py", line 268, in make_update
    backprop(gradients, sgd=optimizer)
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/spacy/_ml.py", line 839, in mlm_backward
    return backprop(d_output, sgd=sgd)
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/thinc/neural/_classes/feed_forward.py", line 53, in continue_update
    gradient = callback(gradient, sgd)
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/thinc/api.py", line 300, in finish_update
    d_X = bp_layer(layer.ops.flatten(d_seqs_out, pad=pad), sgd=sgd)
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/thinc/neural/_classes/feed_forward.py", line 53, in continue_update
    gradient = callback(gradient, sgd)
  File "/home/username/miniconda3/envs/spacy/lib/python3.6/site-packages/thinc/api.py", line 384, in uniqued_bwd
    layer.ops.scatter_add(dY_uniq, layer.ops.asarray(inv, dtype="i"), dY)
  File "ops.pyx", line 1087, in thinc.neural.ops.CupyOps.scatter_add
AttributeError: module 'cupy' has no attribute 'scatter_add'
```

**Comment by erotavlas** [comment]
I uninstalled `cupy` and reinstalled it according to recommendation from this issue https://github.com/explosion/spaCy/issues/5368 

and then the error went away.

**Comment by svlandeg** [comment]
Ok, good to know, thanks for posting a link to the solution !

**Comment by umarbutler** [comment]
I had the same error and was able to solve it using the solution provided in #5193 (the solution in #5368 did not solve my problem).
