### ISSUE TITLE
size confusion when loading custom vectors

### ISSUE THREAD

**Issue by michaelcapizzi** [explosion/spaCy#544]
This is a follow up to [this issue](https://github.com/explosion/spaCy/issues/448) which still persists.

I am not confident that `spacy` is housing my vectors after loading.

First of all, I have created a `bin` of my vectors using `vocab.write_binary_vectors()`.  They are 200-dimensions, but after successfully loading them into my existing instance of `English()`, they still appear to be 300-dimensions.

```
>>> nlp = English(vectors=lambda vocab: vocab.load_vectors_from_bin_loc("/path/to/my/binary/vectors/w2v.bin"))
>>> nlp.vocab.__getitem__("this").vector.shape
(300,)
```

The weirdest thing, though, is that these vectors are *not* the "original" vectors loaded by `spacy` (`GloVe 200-dimensions`):

```
>>> nlp2 = English()
>>> nlp2.vocab.__getitem__("this").vector.shape
(300,)
>>> nlp.vocab.__getitem__("this").vector == nlp2.vocab.__getitem__("this").vector
array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False], dtype=bool)
```

So this vector is different from the "original", preloaded vector for "this", but it's still 300 dimensions.

The same thing happens if I use `vocab.load_vectors()` instead of `vocab.load_vectors_from_bin_loc()`:

```
>>> nlp3 = English(vectors=lambda vocab: vocab.load_vectors("/path/to/my/vectors/in/text/format/w2v.txt"))
>>> nlp3.vocab.__getitem__("this").vector.shape
(300,)
>>> nlp3.vocab.__getitem__("this").vector == nlp.vocab.__getitem__("this").vector
array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False], dtype=bool)
```

At least, however, they are the *same* as the vectors that were loaded from the `bin` file:

```
>>> nlp3.vocab.__getitem__("this").vector == nlp2.vocab.__getitem__("this").vector
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True], dtype=bool)
```

**Comment by honnibal** [comment]
I need to update the docs — this was indeed broken at the 1.0 release (actually the GloVe loading was also broken). Can you try again with v1.0.5, using the keyword `add_vectors` instead of `vectors`?

**Comment by michaelcapizzi** [comment]
Sure thing.  But, I'm sorry, I'm a bit unclear.  I'm not sure what command to use and where `add_vectors` comes in.  

So I tried to load vectors from a text file in `1.0.5` using `vocab.add_vectors(path/to/vectors.txt)`:

```>>> from spacy.en import English
>>> nlp = English()
>>> this_vector = nlp.vocab.__getitem__("this").vector
>>> this_vector.shape
(300,)
>>> nlp2 = English(vectors=lambda vocab: vocab.add_vectors("/Users/mcapizzi/Github/nlp-pipeline/jupyter_notebooks/data/sample_w2v.txt"))
>>> this_vector_2 = nlp2.vocab.__getitem__("this").vector
>>> this_vector_2.shape
(300,)
>>> this_vector == this_vector_2
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True], dtype=bool)
```

So now it appears that the vectors did *not* get loaded in as the vector for "this" didn't change.

Then I tried `vocab.add_vectors(path/to/binary/vectors.bin)`:

```
>>> nlp3 = English(vectors=lambda vocab: vocab.add_vectors("/Users/mcapizzi/Github/nlp-pipeline/jupyter_notebooks/data/sample_w2v.bin"))
>>> this_vector_3 = nlp3.vocab.__getitem__("this").vector
>>> this_vector_3.shape
(300,)
>>> this_vector == this_vector_3
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True], dtype=bool)
```

Same result.

If I misunderstood what you wanted me to try, please clarify and I'll happily test it out.

**Comment by honnibal** [comment]
Sorry, I meant like this:

```python
nlp2 = English(add_vectors=lambda vocab: vocab.load_vectors("/Users/mcapizzi/Github/nlp-pipeline/jupyter_notebooks/data/sample_w2v.txt"))
```

**Comment by michaelcapizzi** [comment]
Got it.

Unfortunately, a new error (again, I'm in `1.0.5`:

```
>>> nlp = English(add_vectors=lambda vocab: vocab.load_vectors("/Users/mcapizzi/Github/nlp-pipeline/jupyter_notebooks/data/sample_w2v.txt")
... )
>>> nlp.vocab.__getitem__("this").vector.shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spacy/lexeme.pyx", line 105, in spacy.lexeme.Lexeme.vector.__get__ (spacy/lexeme.cpp:4614)
ValueError: Word vectors set to length 0. This may be because the data is not installed. If you haven't already, run
python -m spacy.en.download all
to install the data.
```

And it does the same thing when trying to load a `bin` file:

```
>>> nlp = English(add_vectors=lambda vocab: vocab.load_vectors("/Users/mcapizzi/Github/nlp-pipeline/jupyter_notebooks/data/sample_w2v.bin"))
>>> nlp.vocab.__getitem__("this").vector.shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spacy/lexeme.pyx", line 105, in spacy.lexeme.Lexeme.vector.__get__ (spacy/lexeme.cpp:4614)
ValueError: Word vectors set to length 0. This may be because the data is not installed. If you haven't already, run
python -m spacy.en.download all
to install the data.
```

**Comment by honnibal** [comment]
Hmm. Thanks for your patience.

**Comment by honnibal** [comment]
I really should've slowed down and tested this more carefully — I'm trying to do too many things at once.

I've added a method `vocab.resize_vectors(new_size)`, to support the workflow where you want to assign the new vectors on `lexeme.vector = new_vector`. I think I fixed the vector loading too.

If you want to try this out, you can do:

```bash

pip install cython==0.23
pip install https://github.com/explosion/spaCy/archive/master.zip
```

**Comment by honnibal** [comment]
This should be fixed in 1.1.0. Please reopen if it's not!

**Comment by michaelcapizzi** [comment]
Thanks @honnibal .  It indeed works in `1.1.0`.  

One clarification for anyone who may be having trouble:  the argument to `vocab.load_vectors()` must be a *buffer* not a *path to a file*:

```
f = open("path/to/vectors.txt", "r")
p.vocab.load_vectors(f)
f.close()
```

**Comment by andrei-constantin** [comment]
Hello, I have the same problem using Anaconda 4.4.0 (64-bit) when running this code

```
from spacy import load
nlp = load('en')
doc1 = nlp(u'Hello hi there!')
doc2 = nlp(u'Hello hi there!')
doc3 = nlp(u'Hey whatsup?')

print (doc1.similarity(doc2)) # 0.999999954642
print (doc2.similarity(doc3)) # 0.699032527716
print (doc1.similarity(doc3)) # 0.699032527716
```

with the response 

>  runfile('C:/Users/andre/.spyder-py3/temp.py', wdir='C:/Users/andre/.spyder-py3')
> 
>  Warning: no model found for 'en'
> 
>  Only loading the 'en' tokenizer.
> 
> Traceback (most recent call last):
> 
>   File "<ipython-input-5-d9d60d5586d6>", line 1, in <module>
>     runfile('C:/Users/andre/.spyder-py3/temp.py', wdir='C:/Users/andre/.spyder-py3')
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/andre/.spyder-py3/temp.py", line 7, in <module>
>     print (doc1.similarity(doc2)) # 0.999999954642
> 
>   File "spacy/tokens/doc.pyx", line 246, in spacy.tokens.doc.Doc.similarity (spacy/tokens/doc.cpp:6540)
> 
>   File "spacy/tokens/doc.pyx", line 287, in spacy.tokens.doc.Doc.vector_norm.__get__ (spacy/tokens/doc.cpp:7588)
> 
>   File "spacy/tokens/doc.pyx", line 271, in spacy.tokens.doc.Doc.vector.__get__ (spacy/tokens/doc.cpp:7279)
> 
>   File "spacy/tokens/doc.pyx", line 271, in genexpr (spacy/tokens/doc.cpp:7102)
> 
>   File "spacy/tokens/token.pyx", line 239, in spacy.tokens.token.Token.vector.__get__ (spacy/tokens/token.cpp:7244)
> 
> ValueError: Word vectors set to length 0. This may be because the data is not installed. If you haven't already, run
> python -m spacy download en
> to install the data


I must mention I am pretty new to python.
