### ISSUE TITLE
Issue With Deploying Flask Web App to Heroku Due to Spacy Model 'en' error

### ISSUE THREAD

**Issue by mmoore7** [explosion/spaCy#5484]
* Operating System: Arch Linux 5.6.11-arch1-1
* Python Version Used: 3.8.3
* spaCy Version Used: 2.1.9

I'm deploying a chatbot to Heroku, using Flask and Chatterbot, and app crashes when I try to start it. In the heroku logs I see this error:
```
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```
I came across the "can't find model 'en'" when I initially attempted to run it locally. I discovered the solution was to run this command: `python -m spacy download en` to get the missing packages and it has worked fine. However, it appears this package doesn't get downloaded when pushing the repo to Heroku's remote repository. I found this issue [1129](https://github.com/explosion/spaCy/issues/1129) and read the documentation here: [docs page](https://spacy.io/usage/models#models-download). I tried the solution and I unfortunately still get the same error. Please help!

Here's my requirements.txt:
```
-i https://pypi.org/simple
-e git+https://github.com/gunthercox/ChatterBot.git@b5bf32a10bb68a0ffca566f429ff0261c9bb65eb#egg=chatterbot
bcrypt==3.1.7
blis==0.2.4
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cymem==2.0.3
dnspython==1.16.0
flask-bcrypt==0.7.1
flask-login==0.5.0
flask-wtf==0.14.3
flask==1.1.2
gunicorn==20.0.4
idna==2.9
itsdangerous==1.1.0
jinja2==2.11.2
joblib==0.15.1
markupsafe==1.1.1
mathparse==0.1.2
murmurhash==1.0.2
nltk==3.5
numpy==1.18.4
pint==0.11
plac==0.9.6
preshed==2.0.1
pycparser==2.20
pymongo==3.10.1
python-dateutil==2.8.1
pytz==2020.1
pyyaml==5.3.1
regex==2020.5.14
requests==2.23.0
six==1.15.0
spacy==2.1.9
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm
sqlalchemy==1.3.17
srsly==1.0.2
thinc==7.0.8
tqdm==4.46.0
urllib3==1.25.9
wasabi==0.6.0
werkzeug==1.0.1
wtforms==2.3.1
```

Here's the log of the deployment:
```
$ git push heroku -u master
Enumerating objects: 297, done.
Counting objects: 100% (297/297), done.
Delta compression using up to 12 threads
Compressing objects: 100% (277/277), done.
Writing objects: 100% (297/297), 5.15 MiB | 572.00 KiB/s, done.
Total 297 (delta 126), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote: -----> Installing python-3.8.3
remote: -----> Installing pip
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        Obtaining chatterbot from git+https://github.com/gunthercox/ChatterBot.git@b5bf32a10bb68a0ffca566f429ff0261c9bb65eb#egg=chatterbot (from -r /tmp/build_a156f9cb580c26db25f3288de63ae52b/requirements.txt (line 2))
remote:          Cloning https://github.com/gunthercox/ChatterBot.git (to revision b5bf32a10bb68a0ffca566f429ff0261c9bb65eb) to /app/.heroku/src/chatterbot
remote:          Running command git clone -q https://github.com/gunthercox/ChatterBot.git /app/.heroku/src/chatterbot
remote:        Collecting bcrypt==3.1.7
remote:          Downloading bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl (56 kB)
remote:        Collecting blis==0.2.4
remote:          Downloading blis-0.2.4.tar.gz (1.5 MB)
remote:        Collecting certifi==2020.4.5.1
remote:          Downloading certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
remote:        Collecting cffi==1.14.0
remote:          Downloading cffi-1.14.0-cp38-cp38-manylinux1_x86_64.whl (409 kB)
remote:        Collecting chardet==3.0.4
remote:          Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
remote:        Collecting click==7.1.2
remote:          Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
remote:        Collecting cymem==2.0.3
remote:          Downloading cymem-2.0.3-cp38-cp38-manylinux1_x86_64.whl (33 kB)
remote:        Collecting dnspython==1.16.0
remote:          Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
remote:        Collecting flask-bcrypt==0.7.1
remote:          Downloading Flask-Bcrypt-0.7.1.tar.gz (5.1 kB)
remote:        Collecting flask-login==0.5.0
remote:          Downloading Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB)
remote:        Collecting flask-wtf==0.14.3
remote:          Downloading Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
remote:        Collecting flask==1.1.2
remote:          Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
remote:        Collecting gunicorn==20.0.4
remote:          Downloading gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
remote:        Collecting idna==2.9
remote:          Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
remote:        Collecting itsdangerous==1.1.0
remote:          Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
remote:        Collecting jinja2==2.11.2
remote:          Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
remote:        Collecting joblib==0.15.1
remote:          Downloading joblib-0.15.1-py3-none-any.whl (298 kB)
remote:        Collecting markupsafe==1.1.1
remote:          Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
remote:        Collecting mathparse==0.1.2
remote:          Downloading mathparse-0.1.2-py3-none-any.whl (7.2 kB)
remote:        Collecting murmurhash==1.0.2
remote:          Downloading murmurhash-1.0.2-cp38-cp38-manylinux1_x86_64.whl (19 kB)
remote:        Collecting nltk==3.5
remote:          Downloading nltk-3.5.zip (1.4 MB)
remote:        Collecting numpy==1.18.4
remote:          Downloading numpy-1.18.4-cp38-cp38-manylinux1_x86_64.whl (20.7 MB)
remote:        Collecting pint==0.11
remote:          Downloading Pint-0.11-py2.py3-none-any.whl (186 kB)
remote:        Collecting plac==0.9.6
remote:          Downloading plac-0.9.6-py2.py3-none-any.whl (20 kB)
remote:        Collecting preshed==2.0.1
remote:          Downloading preshed-2.0.1.tar.gz (113 kB)
remote:        Collecting pycparser==2.20
remote:          Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
remote:        Collecting pymongo==3.10.1
remote:          Downloading pymongo-3.10.1-cp38-cp38-manylinux2014_x86_64.whl (480 kB)
remote:        Collecting python-dateutil==2.8.1
remote:          Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
remote:        Collecting pytz==2020.1
remote:          Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
remote:        Collecting pyyaml==5.3.1
remote:          Downloading PyYAML-5.3.1.tar.gz (269 kB)
remote:        Collecting regex==2020.5.14
remote:          Downloading regex-2020.5.14-cp38-cp38-manylinux2010_x86_64.whl (689 kB)
remote:        Collecting requests==2.23.0
remote:          Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
remote:        Collecting six==1.15.0
remote:          Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
remote:        Collecting spacy==2.1.9
remote:          Downloading spacy-2.1.9.tar.gz (30.7 MB)
remote:          Installing build dependencies: started
remote:          Installing build dependencies: still running...
remote:          Installing build dependencies: still running...
remote:          Installing build dependencies: still running...
remote:          Installing build dependencies: still running...
remote:          Installing build dependencies: finished with status 'done'
remote:          Getting requirements to build wheel: started
remote:          Getting requirements to build wheel: finished with status 'done'
remote:            Preparing wheel metadata: started
remote:            Preparing wheel metadata: finished with status 'done'
remote:        Collecting en_core_web_sm
remote:          Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz (11.1 MB)
remote:        Collecting sqlalchemy==1.3.17
remote:          Downloading SQLAlchemy-1.3.17-cp38-cp38-manylinux2010_x86_64.whl (1.3 MB)
remote:        Collecting srsly==1.0.2
remote:          Downloading srsly-1.0.2-cp38-cp38-manylinux1_x86_64.whl (185 kB)
remote:        Collecting thinc==7.0.8
remote:          Downloading thinc-7.0.8.tar.gz (1.9 MB)
remote:        Collecting tqdm==4.46.0
remote:          Downloading tqdm-4.46.0-py2.py3-none-any.whl (63 kB)
remote:        Collecting urllib3==1.25.9
remote:          Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
remote:        Collecting wasabi==0.6.0
remote:          Downloading wasabi-0.6.0-py3-none-any.whl (20 kB)
remote:        Collecting werkzeug==1.0.1
remote:          Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
remote:        Collecting wtforms==2.3.1
remote:          Downloading WTForms-2.3.1-py2.py3-none-any.whl (169 kB)
remote:        Building wheels for collected packages: blis, flask-bcrypt, nltk, preshed, pyyaml, spacy, en-core-web-sm, thinc
remote:          Building wheel for blis (setup.py): started
remote:          Building wheel for blis (setup.py): still running...
remote:          Building wheel for blis (setup.py): still running...
remote:          Building wheel for blis (setup.py): still running...
remote:          Building wheel for blis (setup.py): finished with status 'done'
remote:          Created wheel for blis: filename=blis-0.2.4-cp38-cp38-linux_x86_64.whl size=4317193 sha256=050e30b8cbd4eb640bf140d328ff3d35dee13a149f3b5a45d5660d0913b21535
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-gt5ca66z/wheels/eb/c3/92/dd0802ed4a0b14a1534ab4f38d05578d7fa73e8445f3e9d2f2
remote:          Building wheel for flask-bcrypt (setup.py): started
remote:          Building wheel for flask-bcrypt (setup.py): finished with status 'done'
remote:          Created wheel for flask-bcrypt: filename=Flask_Bcrypt-0.7.1-py3-none-any.whl size=5010 sha256=1f3ebe35bdfce7a45fb401ccf8efba3014fcc3071afea69a26145f5812ba23c4
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-gt5ca66z/wheels/8a/d9/0e/dc762c4ebc76f581397a2e25991db6efd148640b5616ab9210
remote:          Building wheel for nltk (setup.py): started
remote:          Building wheel for nltk (setup.py): finished with status 'done'
remote:          Created wheel for nltk: filename=nltk-3.5-py3-none-any.whl size=1434674 sha256=0b01a64f192bafd5aabcaab4114f087332e03ddd2773d23874c27ec102935539
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-gt5ca66z/wheels/ff/d5/7b/f1fb4e1e1603b2f01c2424dd60fbcc50c12ef918bafc44b155
remote:          Building wheel for preshed (setup.py): started
remote:          Building wheel for preshed (setup.py): finished with status 'done'
remote:          Created wheel for preshed: filename=preshed-2.0.1-cp38-cp38-linux_x86_64.whl size=351834 sha256=8a4fcbff3ca34cc588904dfe1f2b19896e1d3dea4530a766d8c5355c2f7ae6c1
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-gt5ca66z/wheels/5a/d0/29/7f6993a759349eae3d0ecca7e2fbc88acdd8650b25e6c6ad8a
remote:          Building wheel for pyyaml (setup.py): started
remote:          Building wheel for pyyaml (setup.py): finished with status 'done'
remote:          Created wheel for pyyaml: filename=PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl size=464569 sha256=6edb857f48369f7394c1e9f03abe33fd7248c3dac054d451fe198e66fb99bcd3
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-gt5ca66z/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c
remote:          Building wheel for spacy (PEP 517): started
remote:          Building wheel for spacy (PEP 517): still running...
remote:          Building wheel for spacy (PEP 517): still running...
remote:          Building wheel for spacy (PEP 517): still running...
remote:          Building wheel for spacy (PEP 517): still running...
remote:          Building wheel for spacy (PEP 517): finished with status 'done'
remote:          Created wheel for spacy: filename=spacy-2.1.9-cp38-cp38-linux_x86_64.whl size=43511344 sha256=e35a07e035874dc816ffc1277a7bce6c326fedf100c8ff9f3fc86f5610ec7e4e
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-gt5ca66z/wheels/50/c2/73/989e659e83b30a74acdfcb825e632b1a7dc12f39d58fe37dd6
remote:          Building wheel for en-core-web-sm (setup.py): started
remote:          Building wheel for en-core-web-sm (setup.py): finished with status 'done'
remote:          Created wheel for en-core-web-sm: filename=en_core_web_sm-2.1.0-py3-none-any.whl size=11074433 sha256=1d0084f4b7b236c4cd181da50d0bf1993ce0e13c7b9874954b436a7a765f948e
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-gt5ca66z/wheels/83/63/50/6467284e1c2d50ffcf02e6582680fd16c6375748a94f75c1a0
remote:          Building wheel for thinc (setup.py): started
remote:          Building wheel for thinc (setup.py): finished with status 'done'
remote:          Created wheel for thinc: filename=thinc-7.0.8-cp38-cp38-linux_x86_64.whl size=4711109 sha256=3837acf9f8de1395d29eb8e64d697267a4555967b3d315aab78c24ac14eeb1c8
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-gt5ca66z/wheels/f4/5b/cc/8a96be826c5d22ca28e3c30f785b22edc57ffb2d349fa780be
remote:        Successfully built blis flask-bcrypt nltk preshed pyyaml spacy en-core-web-sm thinc
remote:        Installing collected packages: mathparse, click, joblib, regex, tqdm, nltk, pint, six, python-dateutil, pyyaml, srsly, numpy, plac, blis, cymem, preshed, murmurhash, urllib3, certifi, chardet, idna, requests, wasabi, thinc, spacy, sqlalchemy, pytz, chatterbot, pycparser, cffi, bcrypt, dnspython, markupsafe, jinja2, werkzeug, itsdangerous, flask, flask-bcrypt, flask-login, wtforms, flask-wtf, gunicorn, pymongo, en-core-web-sm
remote:          Running setup.py develop for chatterbot
remote:        Successfully installed bcrypt-3.1.7 blis-0.2.4 certifi-2020.4.5.1 cffi-1.14.0 chardet-3.0.4 chatterbot click-7.1.2 cymem-2.0.3 dnspython-1.16.0 en-core-web-sm-2.1.0 flask-1.1.2 flask-bcrypt-0.7.1 flask-login-0.5.0 flask-wtf-0.14.3 gunicorn-20.0.4 idna-2.9 itsdangerous-1.1.0 jinja2-2.11.2 joblib-0.15.1 markupsafe-1.1.1 mathparse-0.1.2 murmurhash-1.0.2 nltk-3.5 numpy-1.18.4 pint-0.11 plac-0.9.6 preshed-2.0.1 pycparser-2.20 pymongo-3.10.1 python-dateutil-2.8.1 pytz-2020.1 pyyaml-5.3.1 regex-2020.5.14 requests-2.23.0 six-1.15.0 spacy-2.1.9 sqlalchemy-1.3.17 srsly-1.0.2 thinc-7.0.8 tqdm-4.46.0 urllib3-1.25.9 wasabi-0.6.0 werkzeug-1.0.1 wtforms-2.3.1
remote: -----> Downloading NLTK corpora…
remote:  !     'nltk.txt' not found, not downloading any corpora
remote:  !     Learn more: https://devcenter.heroku.com/articles/python-nltk
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 185.5M
remote: -----> Launching...
remote:        Released v3
remote:        https://captain-hp-bot.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/captain-hp-bot.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'heroku'.
```

Here's the Heroku log:
```
$ heroku logs --tail
 ›   Warning: heroku update available from 7.40.0 to 7.41.1.
2020-05-22T03:00:24.188722+00:00 app[web.1]: [2020-05-22 03:00:24 +0000] [9] [INFO] Booting worker with pid: 9
2020-05-22T03:00:24.275949+00:00 app[web.1]: [2020-05-22 03:00:24 +0000] [10] [INFO] Booting worker with pid: 10
2020-05-22T03:00:24.684104+00:00 heroku[web.1]: State changed from starting to up
2020-05-22T03:00:25.457241+00:00 app[web.1]: [2020-05-22 03:00:25 +0000] [10] [ERROR] Exception in worker process
2020-05-22T03:00:25.457293+00:00 app[web.1]: Traceback (most recent call last):
2020-05-22T03:00:25.457294+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-05-22T03:00:25.457294+00:00 app[web.1]: worker.init_process()
2020-05-22T03:00:25.457295+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-05-22T03:00:25.457295+00:00 app[web.1]: self.load_wsgi()
2020-05-22T03:00:25.457295+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-05-22T03:00:25.457296+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-05-22T03:00:25.457296+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-05-22T03:00:25.457297+00:00 app[web.1]: self.callable = self.load()
2020-05-22T03:00:25.457297+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-05-22T03:00:25.457297+00:00 app[web.1]: return self.load_wsgiapp()
2020-05-22T03:00:25.457297+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-05-22T03:00:25.457298+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-05-22T03:00:25.457298+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2020-05-22T03:00:25.457299+00:00 app[web.1]: mod = importlib.import_module(module)
2020-05-22T03:00:25.457299+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-05-22T03:00:25.457300+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-05-22T03:00:25.457300+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-05-22T03:00:25.457301+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-05-22T03:00:25.457301+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-05-22T03:00:25.457301+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-05-22T03:00:25.457302+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-05-22T03:00:25.457302+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-05-22T03:00:25.457303+00:00 app[web.1]: File "/app/run.py", line 1, in <module>
2020-05-22T03:00:25.457303+00:00 app[web.1]: from captain_hp_bot import app
2020-05-22T03:00:25.457303+00:00 app[web.1]: File "/app/captain_hp_bot/__init__.py", line 13, in <module>
2020-05-22T03:00:25.457304+00:00 app[web.1]: from captain_hp_bot import routes
2020-05-22T03:00:25.457304+00:00 app[web.1]: File "/app/captain_hp_bot/routes.py", line 13, in <module>
2020-05-22T03:00:25.457304+00:00 app[web.1]: chatbot = ChatBot(
2020-05-22T03:00:25.457305+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/chatterbot.py", line 28, in __init__
2020-05-22T03:00:25.457305+00:00 app[web.1]: self.storage = utils.initialize_class(storage_adapter, **kwargs)
2020-05-22T03:00:25.457306+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/utils.py", line 33, in initialize_class
2020-05-22T03:00:25.457306+00:00 app[web.1]: return Class(*args, **kwargs)
2020-05-22T03:00:25.457308+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/storage/mongodb.py", line 21, in __init__
2020-05-22T03:00:25.457309+00:00 app[web.1]: super().__init__(**kwargs)
2020-05-22T03:00:25.457309+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/storage/storage_adapter.py", line 22, in __init__
2020-05-22T03:00:25.457309+00:00 app[web.1]: self.tagger = Tagger(language=kwargs.get(
2020-05-22T03:00:25.457310+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/tagging.py", line 26, in __init__
2020-05-22T03:00:25.457310+00:00 app[web.1]: self.nlp = spacy.load(self.language.ISO_639_1.lower())
2020-05-22T03:00:25.457310+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/spacy/__init__.py", line 27, in load
2020-05-22T03:00:25.457311+00:00 app[web.1]: return util.load_model(name, **overrides)
2020-05-22T03:00:25.457311+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/spacy/util.py", line 139, in load_model
2020-05-22T03:00:25.457312+00:00 app[web.1]: raise IOError(Errors.E050.format(name=name))
2020-05-22T03:00:25.457312+00:00 app[web.1]: OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
2020-05-22T03:00:25.457435+00:00 app[web.1]: [2020-05-22 03:00:25 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-05-22T03:00:25.465390+00:00 app[web.1]: [2020-05-22 03:00:25 +0000] [9] [ERROR] Exception in worker process
2020-05-22T03:00:25.465391+00:00 app[web.1]: Traceback (most recent call last):
2020-05-22T03:00:25.465392+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-05-22T03:00:25.465392+00:00 app[web.1]: worker.init_process()
2020-05-22T03:00:25.465393+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-05-22T03:00:25.465393+00:00 app[web.1]: self.load_wsgi()
2020-05-22T03:00:25.465394+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-05-22T03:00:25.465394+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-05-22T03:00:25.465394+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-05-22T03:00:25.465395+00:00 app[web.1]: self.callable = self.load()
2020-05-22T03:00:25.465395+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-05-22T03:00:25.465396+00:00 app[web.1]: return self.load_wsgiapp()
2020-05-22T03:00:25.465397+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-05-22T03:00:25.465397+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-05-22T03:00:25.465397+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2020-05-22T03:00:25.465398+00:00 app[web.1]: mod = importlib.import_module(module)
2020-05-22T03:00:25.465398+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-05-22T03:00:25.465399+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-05-22T03:00:25.465399+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-05-22T03:00:25.465399+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-05-22T03:00:25.465400+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-05-22T03:00:25.465400+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-05-22T03:00:25.465401+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-05-22T03:00:25.465401+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-05-22T03:00:25.465401+00:00 app[web.1]: File "/app/run.py", line 1, in <module>
2020-05-22T03:00:25.465402+00:00 app[web.1]: from captain_hp_bot import app
2020-05-22T03:00:25.465402+00:00 app[web.1]: File "/app/captain_hp_bot/__init__.py", line 13, in <module>
2020-05-22T03:00:25.465402+00:00 app[web.1]: from captain_hp_bot import routes
2020-05-22T03:00:25.465403+00:00 app[web.1]: File "/app/captain_hp_bot/routes.py", line 13, in <module>
2020-05-22T03:00:25.465403+00:00 app[web.1]: chatbot = ChatBot(
2020-05-22T03:00:25.465404+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/chatterbot.py", line 28, in __init__
2020-05-22T03:00:25.465404+00:00 app[web.1]: self.storage = utils.initialize_class(storage_adapter, **kwargs)
2020-05-22T03:00:25.465404+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/utils.py", line 33, in initialize_class
2020-05-22T03:00:25.465405+00:00 app[web.1]: return Class(*args, **kwargs)
2020-05-22T03:00:25.465405+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/storage/mongodb.py", line 21, in __init__
2020-05-22T03:00:25.465405+00:00 app[web.1]: super().__init__(**kwargs)
2020-05-22T03:00:25.465406+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/storage/storage_adapter.py", line 22, in __init__
2020-05-22T03:00:25.465406+00:00 app[web.1]: self.tagger = Tagger(language=kwargs.get(
2020-05-22T03:00:25.465406+00:00 app[web.1]: File "/app/.heroku/src/chatterbot/chatterbot/tagging.py", line 26, in __init__
2020-05-22T03:00:25.465407+00:00 app[web.1]: self.nlp = spacy.load(self.language.ISO_639_1.lower())
2020-05-22T03:00:25.465436+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/spacy/__init__.py", line 27, in load
2020-05-22T03:00:25.465437+00:00 app[web.1]: return util.load_model(name, **overrides)
2020-05-22T03:00:25.465437+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/spacy/util.py", line 139, in load_model
2020-05-22T03:00:25.465438+00:00 app[web.1]: raise IOError(Errors.E050.format(name=name))
2020-05-22T03:00:25.465439+00:00 app[web.1]: OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
2020-05-22T03:00:25.465595+00:00 app[web.1]: [2020-05-22 03:00:25 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-05-22T03:00:25.996290+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/" host=captain-hp-bot.herokuapp.com request_id=31dfec2e-35b9-4902-9e13-2e1db0f4b1e6 fwd="98.171.83.146" dyno=web.1 connect=5001ms service=715ms status=503 bytes=0 protocol=https
2020-05-22T03:00:26.096495+00:00 app[web.1]: [2020-05-22 03:00:26 +0000] [4] [INFO] Shutting down: Master
2020-05-22T03:00:26.096573+00:00 app[web.1]: [2020-05-22 03:00:26 +0000] [4] [INFO] Reason: Worker failed to boot.
2020-05-22T03:00:26.179693+00:00 heroku[web.1]: Process exited with status 3
```

Why am I still getting the error?

**Comment by mmoore7** [comment]
I noticed another error:
```
remote: -----> Downloading NLTK corpora…
remote:  !     'nltk.txt' not found, not downloading any corpora
remote:  !     Learn more: https://devcenter.heroku.com/articles/python-nltk
```

I added an nltk.txt file with a few corpora and it downloaded successfully, but I'm still getting the E050 error.

**Comment by adrianeboyd** [comment]
If you install the model directly by URL, the symlink `en` isn't added. This is a second step run by `spacy download en` for shortcut model names but not by `pip install model.tar.gz`. If you refer to the full model/package name `en_core_web_sm` in your code, I think it should work.

(The NLTK error is outside the scope of the spacy issue tracker, sorry!)

**Comment by mmoore7** [comment]
@adrianeboyd thanks for your reply. I'm using the chatterbot framework: [ChatterBot](https://github.com/gunthercox/ChatterBot), so my code does not explicitly load the spacy model. Is there any way for me to add the symlink?

**Comment by adrianeboyd** [comment]
You can add a link with `spacy link` (https://spacy.io/api/cli#link), which is a simple CLI script that you could also probably adapt as needed if it's not practical to call it directly: https://github.com/explosion/spaCy/blob/844f840826e07555795e896141c57c644a18417e/spacy/cli/link.py

**Comment by mmoore7** [comment]
@adrianeboyd thanks for the info. I'm not quite sure how I would create the symlink in the heroku repo, since it runs on a virtual machine that likely refreshes daily. 

What I ended up doing was forking Gunther's chatterbot library and updating line 26 in the tagging.py module so that it explicitly loads "en_core_web_sm" instead of "en".

Before
`self.nlp = spacy.load(self.language.ISO_639_1.lower())`

After
`self.nlp = spacy.load('en_core_web_sm')`

Probably not the most elegant solution, but now the website works! I don't intend to use languages other than English. Thank you for your help.
