### ISSUE TITLE
Entity linking error - ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by danplae** [explosion/spaCy#5621]
Hey, there!
Hello, I am facing a problem and hope you can help me. When I run wikidata_train_entity_linker.py I get "ValueError: not enough values to unpack (expected 2, got 0)" error. 

- The files generated by wikidata_pretrain_kb.py seem to be ok (entity_descriptions 159.5M, entity_alias 213.1M, entity_defs 174.4M, entity_freq 466.4M, nlp_kb (directory) 1.05G, kb 367.5M, prior_prob 1.47G, gold_entities 3,07 GB).

- Here is the command I ran and the full output log:

python wikidata_train_entity_linker.py /entity_linking_data/ -o /entity_linking_data/EL_50000/ -t 50000 -d 100 -l CARDINAL,DATE,MONEY,ORDINAL,QUANTITY,TIME,PERCENT -e 5
2020-06-21 13:04:08,709 - INFO - __main__ - Creating Entity Linker with Wikipedia and WikiData
2020-06-21 13:04:08,710 - INFO - __main__ - STEP 1a: Loading model from /entity_linking_data/nlp_kb
2020-06-21 13:04:27,659 - INFO - __main__ - Original NLP pipeline has following pipeline components: ['tagger', 'parser', 'ner']
2020-06-21 13:04:27,660 - INFO - __main__ - STEP 1b: Loading KB from /entity_linking_data/kb
2020-06-21 13:04:37,325 - INFO - __main__ - STEP 2: Reading training & dev dataset from /entity_linking_data/gold_entities.jsonl
2020-06-21 13:07:05,646 - INFO - __main__ - Training set has 96857 articles, limit set to roughly 50000 articles per epoch
2020-06-21 13:07:05,647 - INFO - __main__ - Dev set has 10857 articles, limit set to rougly 100 articles for evaluation
2020-06-21 13:07:05,650 - INFO - __main__ - STEP 3: Creating and training an Entity Linking pipe for 5 epochs
2020-06-21 13:07:05,650 - INFO - __main__ - Discarding 7 NER types: ['CARDINAL', 'DATE', 'MONEY', 'ORDINAL', 'QUANTITY', 'TIME', 'PERCENT']
2020-06-21 13:07:06,360 - INFO - __main__ - Dev Baseline Accuracies:
2020-06-21 13:08:28,044 - INFO - bin.wiki_entity_linking.entity_linker_evaluation - Counts: {}                                                                                                              
2020-06-21 13:08:28,045 - INFO - bin.wiki_entity_linking.entity_linker_evaluation - Random: F-score = 0.0 | Recall = 0.0 | Precision = 0.0 | F-score by label = {}
2020-06-21 13:08:28,045 - INFO - bin.wiki_entity_linking.entity_linker_evaluation - Prior: F-score = 0.0 | Recall = 0.0 | Precision = 0.0 | F-score by label = {}
2020-06-21 13:08:28,045 - INFO - bin.wiki_entity_linking.entity_linker_evaluation - Oracle: F-score = 0.0 | Recall = 0.0 | Precision = 0.0 | F-score by label = {}
Traceback (most recent call last):                                                                                                                                                                          
  File "wikidata_train_entity_linker.py", line 172, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.7/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.7/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "wikidata_train_entity_linker.py", line 137, in main
    docs, golds = zip(*train_batch)
ValueError: not enough values to unpack (expected 2, got 0)

Thanks in advance!

## Your Environment
* Operating System: MacOS
* Python Version Used: 3.7.7
* spaCy Version Used: 2.2.4
* Environment Information: Darwin-18.7.0-x86_64-i386-64bit

**Comment by svlandeg** [comment]
Hi @danplae. As the precision and recall scores are both 0, it looks like the parsing of the entities is not succeeding. Maybe this is because no entities are matched against the gold data in your `gold_entities.jsonl`?

You probably want to run this on a small portion of the data and check internally what happens and why you're not getting matches.

What was the problem & solution for your issue https://github.com/explosion/spaCy/issues/5390? I'm guessing this will be related ...
