### ISSUE TITLE
spacy train , line 631, in evaluate docs, golds = zip(*docs_golds) ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by pythonBerg** [explosion/spaCy#5628]
I have been using spacy for years now to train custom ner provisions using simple training format sourced from relational db. I am attempted to move this to command line training given additional information and ability to more easily run in cloud. Like users in past, I have struggled with understanding the nuances of documentation but I am hopeful my json format is now correct. When attempting to train ner from command line, it is obvious something is still off. Any guidance people can offer is much appreciated. I'm probably doing something stupid, but can't see it right now

spacy==2.1.8

```
Pseudo code to create training json. Format of result in text editor appears to match specification

  

doc = nlp(text)
ents = biluo_tags_from_offsets(doc,annotations)  ##annotations represented as list[(start,end,label)...]
doc.ents = spans_from_biluo_tags(doc, ents)
jsonDocs.append(doc)
  
 random.shuffle(jsonDocs)
 tcount = int(.85* len(jsonDocs))
 tdocs = jsonDocs[:tcount]
 ddocs = jsonDocs[tcount:]

 dj = docs_to_json(tdocs)
 nerfile = os.path.join(BASEDIR,'trainingData','ner-training-'+provision_type.lower()+'.json')
 with open(nerfile, 'w') as f:  # writing JSON object
       json.dump(dj, f)

 dj = docs_to_json(ddocs)
 nerfile = os.path.join(BASEDIR,'trainingData','ner-testing-'+provision_type.lower()+'.json')
 with open(nerfile, 'w') as f:  # writing JSON object
      json.dump(dj, f)

Command to train model using spacy train

python -m spacy train en C:/home/testModels/loan/devModel C:/home/trainingData/ner-training-widget.json c:/home/trainingData/ner-testing-widget.json -p ner

Result:

Created blank 'en' model Training pipeline: ['ner'] Starting with blank model 'en' Counting training words (limit=0)

Itn Dep Loss NER Loss UAS NER P NER R NER F Tag % Token % CPU WPS GPU WPS

[+] Saved model to output directory C:\home\testModels\widget\devModel\model-final

Traceback (most recent call last): File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\cli\train.py", line 281, in train scorer = nlp_loaded.evaluate(dev_docs, debug) File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\language.py", line 631, in evaluate docs, golds = zip(*docs_golds) ValueError: not enough values to unpack (expected 2, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in run_code exec(code, run_globals) File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy_main.py", line 35, in plac.call(commands[command], sys.argv[1:]) File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\plac_core.py", line 328, in call cmd, result = parser.consume(arglist) File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\plac_core.py", line 207, in consume return cmd, self.func(*(args + varargs + extraopts), **kwargs) File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\cli\train.py", line 368, in train best_model_path = _collate_best_model(meta, output_path, nlp.pipe_names) File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\cli\train.py", line 425, in _collate_best_model bests[component] = _find_best(output_path, component) File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\cli\train.py", line 444, in _find_best accs = srsly.read_json(epoch_model / "accuracy.json") File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\srsly_json_api.py", line 49, in read_json file_path = force_path(location) File "c:\Users\MPC-LAPTOP01\AppData\Local\Programs\Python\Python36\lib\site-packages\srsly\util.py", line 11, in force_path raise ValueError("Can't read file: {}".format(location)) ValueError: Can't read file: C:\home\testModels\loan\devModel\model0\accuracy.json
```

**Comment by adrianeboyd** [comment]
The training format is very frustrating to work with and we're working on improving this for spacy v3.

It's hard to know for sure without seeing the data, but a common mistake is that you need to wrap the output from `docs_to_json` in a list:

```
import srsly
srsly.write_json([docs_to_json(docs)], "file.json")
```

I ran into the same problem myself and suggested changing this, but there are internal reasons to have `docs_to_json` work like this (see #4013 if you're interested in the gory details).

**Comment by pythonBerg** [comment]
Thanks. Your suggestion was the fix. I am past the original error..Agree the json training format is confusing but some additional documentation would really help. NER training examples use simple training format, command line training is mentioned as recommended, some github and stack examples highlight parts of how to convert. For such a terrific platform, understanding some basic transformations really take too much time.

Thanks for the help Adriane
