### ISSUE TITLE
issue to "spacy.load('fr')" even if the installation was a sucess (with conda)

### ISSUE THREAD

**Issue by Nathberrebi** [explosion/spaCy#5654]
Hello,
I have installed spacy on anaconda windows with 
conda install tqdm
conda install spacy 
all was good, then i run an administrator anaconda prompt to do :
python -m spacy download fr

the installation was a success but when i try to do nlp = spacy.load('fr') (like on the image) there is a problem.
Can you help me to solve it ? 

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by Nathberrebi** [comment]
![spacy](https://user-images.githubusercontent.com/38182600/85844488-19492e00-b7a3-11ea-8067-7b5957c0f63b.PNG)

**Comment by adrianeboyd** [comment]
Hi, the latest versions of spacy are available through the channel `conda-forge`. Unless you have a particular reason to prefer spacy v2.0, we'd recommend uninstalling this version (it's over two years old now) and then installing the latest release from `conda-forge` like this:

```
conda uninstall spacy
conda install -c conda-forge spacy
```

If you see new errors, please cut and paste the error as plaintext in a code block (like the first example here: https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks). It's much easier for us to read than an image.

**Comment by Nathberrebi** [comment]
Hi, thanks you for your fast answer. I do exactly what you said and after i opened python on the prompt and i did :
'' (base) C:\WINDOWS\system32>python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load('fr')
C:\Users\natha\Anaconda3\lib\site-packages\spacy\util.py:271: UserWarning: [W031] Model 'fr_core_news_sm' (2.0.0) requires spaCy v2.0 and is incompatible with the current spaCy version (2.3.0). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\natha\Anaconda3\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\natha\Anaconda3\lib\site-packages\spacy\util.py", line 168, in load_model
    return load_model_from_link(name, **overrides)
  File "C:\Users\natha\Anaconda3\lib\site-packages\spacy\util.py", line 185, in load_model_from_link
    return cls.load(**overrides)
  File "C:\Users\natha\Anaconda3\lib\site-packages\spacy\data\fr\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\natha\Anaconda3\lib\site-packages\spacy\util.py", line 235, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "C:\Users\natha\Anaconda3\lib\site-packages\spacy\util.py", line 218, in load_model_from_path
    return nlp.from_disk(model_path, exclude=disable)
  File "C:\Users\natha\Anaconda3\lib\site-packages\spacy\language.py", line 971, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "C:\Users\natha\Anaconda3\lib\site-packages\spacy\util.py", line 686, in from_disk
    reader(path / key)
  File "C:\Users\natha\Anaconda3\lib\site-packages\spacy\language.py", line 958, in <lambda>
    p, exclude=["vocab"]
  File "tokenizer.pyx", line 558, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 606, in spacy.tokenizer.Tokenizer.from_bytes
  File "C:\Users\natha\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\Users\natha\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\natha\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\natha\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\natha\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Users\natha\Anaconda3\lib\sre_parse.py", line 536, in _parse
    code1 = _class_escape(source, this)
  File "C:\Users\natha\Anaconda3\lib\sre_parse.py", line 337, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 257
'''

Thanks !

**Comment by adrianeboyd** [comment]
Don't miss the warning at the top of the traceback above:

> UserWarning: [W031] Model 'fr_core_news_sm' (2.0.0) requires spaCy v2.0 and is incompatible with the current spaCy version (2.3.0). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate

You need to run `python -m spacy download fr` to download an updated version of `fr_core_news_sm` that is compatible with spacy 2.3.0.
