### ISSUE TITLE
NLP Tagger is of NoneType

### ISSUE THREAD

**Issue by kendricktan** [explosion/spaCy#568]
So after upgrading to spaCy v1.1.2, I got this error when I'm trying to call the nlp tagger:

```bash
Original exception was:
 Traceback (most recent call last):
  File "/home/kendricktan/.virtualenvs/laice/lib/python3.5/site-packages/rest_framework/serializers.py", line 873, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/home/kendricktan/.virtualenvs/laice/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/kendricktan/.virtualenvs/laice/lib/python3.5/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/kendricktan/.virtualenvs/laice/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/kendricktan/.virtualenvs/laice/lib/python3.5/site-packages/django/db/models/base.py", line 820, in save_base
    update_fields=update_fields)
  File "/home/kendricktan/.virtualenvs/laice/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/kendricktan/Development/Python/laice/stories/signals.py", line 21, in parse_ner
    spacy_ner.get_query(instance)
  File "/home/kendricktan/Development/Python/laice/laice/utils/spacy_ner.py", line 93, in get_query
    nlp.tagger( doc )
TypeError: 'NoneType' object is not callable
```

Code was basically the same from the example:

```python
# Initialize Spacy modules
nlp = spacy.load('en', parser=False, entity=False, add_vectors=False)
ner = EntityRecognizer( nlp.vocab, entity_types=ENTITY_LIST )

doc = nlp.make_doc( "Ben is in Japan" )
nlp.tagger( doc ) # <- Error occurs here, nlp.tagger is of NoneType
ner( doc )
```

Any ideas?

**Comment by honnibal** [comment]
Did you install the data?

**Comment by kendricktan** [comment]
Turns out all I had to do was run

```
python -m spacy.en.download –force all
```

Thanks @honnibal
