### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by zifeishan** [explosion/spaCy#589]
With latest master branch (d563f1eadb965de5dc09536cc8c6263277b864fe) I am getting following error:

```
  File ".../spaCy/spacy/language.py", line 304, in __call__
    doc = self.make_doc(text)
  File ".../spaCy/spacy/language.py", line 279, in <lambda>
    self.make_doc = lambda text: self.tokenizer(text)
  File "spacy/tokenizer.pyx", line 155, in spacy.tokenizer.Tokenizer.__call__ (spacy/tokenizer.cpp:5527)
  File "spacy/tokenizer.pyx", line 196, in spacy.tokenizer.Tokenizer._tokenize (spacy/tokenizer.cpp:6272)
  File "spacy/tokenizer.pyx", line 259, in spacy.tokenizer.Tokenizer._attach_tokens (spacy/tokenizer.cpp:7144)
  File "spacy/vocab.pyx", line 201, in spacy.vocab.Vocab.get (spacy/vocab.cpp:6492)
  File "spacy/vocab.pyx", line 222, in spacy.vocab.Vocab._new_lexeme (spacy/vocab.cpp:6747)
OverflowError: Python int too large to convert to C long
```

**Comment by honnibal** [comment]
Thanks! Steps to reproduce appreciated if you have time.

**Comment by zifeishan** [comment]
A minimal example to reproduce this:
(related: https://github.com/explosion/spaCy/issues/285)

```
import spacy
nlp = spacy.en.English()
# this is the motivation I am using latest master.. to try out the fix suggested by #285
nlp.vocab.strings.set_frozen(True)

nlp('Whata')  # a new lexeme
```

**Comment by honnibal** [comment]
Fixed. The fix isn't wonderful, though — we end up with only a 32 bit hash for the OOV words. If the store isn't flushed regularly, we'll get clashes quite often. Something to consider when designing the rest of the solution here.

**Comment by huajunzeng** [comment]
This issue is still there. Was the fix pushed to the released version?
```
~/my_dir $ pip show spacy
Name: spacy
Version: 1.8.2
Summary: Industrial-strength Natural Language Processing (NLP) with Python and Cython
Home-page: https://spacy.io
Author: Matthew Honnibal
Author-email: matt@explosion.ai
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires: numpy, murmurhash, cymem, preshed, thinc, plac, six, pathlib, ujson, dill, requests, regex, ftfy
~/my_dir $ python
Python 2.7.13 (default, Dec 22 2016, 09:22:15) 
[GCC 6.2.1 20160822] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.en.English()
>>> nlp.vocab.strings.set_frozen(True)
>>> nlp(u'Whataasdfsdaf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/spacy/language.py", line 320, in __call__
    doc = self.make_doc(text)
  File "/usr/lib/python2.7/site-packages/spacy/language.py", line 293, in <lambda>
    self.make_doc = lambda text: self.tokenizer(text)
  File "spacy/tokenizer.pyx", line 165, in spacy.tokenizer.Tokenizer.__call__ (spacy/tokenizer.cpp:5486)
  File "spacy/tokenizer.pyx", line 205, in spacy.tokenizer.Tokenizer._tokenize (spacy/tokenizer.cpp:6060)
  File "spacy/tokenizer.pyx", line 279, in spacy.tokenizer.Tokenizer._attach_tokens (spacy/tokenizer.cpp:7129)
  File "spacy/vocab.pyx", line 246, in spacy.vocab.Vocab.get (spacy/vocab.cpp:6986)
  File "spacy/vocab.pyx", line 269, in spacy.vocab.Vocab._new_lexeme (spacy/vocab.cpp:7249)
OverflowError: value too large to convert to int32_t

```

**Comment by apierleoni** [comment]
Having same problem here following instructions from #285.

**Comment by huajunzeng** [comment]
@honnibal. We need your help to reopen the issue and see if there is way to solve this.
