### ISSUE TITLE
Python 2.7 support issues

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#5896]
I am need to use Spacy in a python 2 environment, and installed it in a virtual environment. I have been using Mac for development. For  a quick test, it reports the following error:

```
# -*- coding: utf-8 -*-

import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Autonomous cars shift insurance liability toward manufacturers")
for token in doc:
    print(token.text, token.dep_, token.head.text, token.head.pos_,
          [child for child in token.children])
```

The error messages:
```
Traceback (most recent call last):
  File "/Users/congminmin/nlp/wb2/spaCy/test.py", line 3, in <module>
    import spacy
  File "/Users/congminmin/nlp/wb2/spaCy/spacy/__init__.py", line 12, in <module>
    from . import pipeline
  File "/Users/congminmin/nlp/wb2/spaCy/spacy/pipeline/__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 25, in init spacy.pipeline.pipes
  File "/Users/congminmin/nlp/wb2/spaCy/spacy/pipeline/functions.py", line 4, in <module>
    from ..language import component
  File "/Users/congminmin/nlp/wb2/spaCy/spacy/language.py", line 31, in <module>
    from .lang.tokenizer_exceptions import TOKEN_MATCH, URL_MATCH
  File "/Users/congminmin/nlp/wb2/spaCy/spacy/lang/tokenizer_exceptions.py", line 62, in <module>
    URL_MATCH = re.compile("(?u)" + URL_PATTERN).match
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range

```
The Spacy is compatible with python 2.7. Right?

**Comment by honnibal** [comment]
The most recent versions haven't been well tested with Python2.7. Which version are you using?

**Comment by lingvisa** [comment]
This is in Spacy 2.3. And yes, I have to compile from the source.

**Comment by honnibal** [comment]
Why do you need to compile from source? Would it be possible to use an older version?

**Comment by lingvisa** [comment]
I slightly modified Spacy for my application. I will see whether I can find an earlier version that works with Python2.

**Comment by adrianeboyd** [comment]
I can't replicate this in linux with python2.7, but it's possible that the changes in #5972 address this problem? I came across a warning related to this elsewhere and noticed that the raw strings were incorrect.

**Comment by lingvisa** [comment]
I tested on Mac and it was the same. I don't really need this piece of code for URL pattern, so I can comment it out temporarily.

**Comment by svlandeg** [comment]
Does that mean it's working again for you, @lingvisa?

**Comment by lingvisa** [comment]
Yes, I can close.
