### ISSUE TITLE
spaCy broken after conda update (not possible to remove)

### ISSUE THREAD

**Issue by U0M0Z** [explosion/spaCy#5913]
I did a conda update and it ran smoothly. Afterwards spaCy stopped working and started signalling an error linked to importlib-metadata. I have tried to install the importlib-metadata again, but the error is not solved. I have tried to remove spacy through:

conda remove spacy 

And it is not working either. Conda tries to resolve the environment but it is not working. I cannot uninstall/reinstall the package and solve the dependencies issue. I installed spacy last week through the conda forge channel, and it has worked without problems until today.

Finally, on a side note FYI: I was using the 'en-core-web-lg' with my team and the vocabulary shows only 489 words instead of the 1million plus suggested in the documentation.

## How to reproduce the behaviour
import spacy

## Your Environment
Traceback (most recent call last):
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/catalogue.py", line 8, in <module>
    import importlib.metadata as importlib_metadata
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommaso/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/tommaso/anaconda3/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/tommaso/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/thinc/__init__.py", line 8, in <module>
    from ._registry import registry
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/thinc/_registry.py", line 1, in <module>
    import catalogue
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/catalogue.py", line 10, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'

* Operating System: MacOS Mojave 10.14.6 (18G103)
* Python Version Used: 3.7.3
* spaCy Version Used: **not possible to retrieve** (I believe it is 2)

**Comment by svlandeg** [comment]
In general, we'd advice to work in separate virtual environments for different projects, and starting a new clean environment from scratch rather than trying to install/reinstall/update stuff in the same global environment. 

Could you create a new conda environment and try installing spaCy from scratch there?
