### ISSUE TITLE
ImportError: preshed.maps does not export expected C function map_clear

### ISSUE THREAD

**Issue by johann-petrak** [explosion/spaCy#5976]
Just upgrade Spacy to version 2.3.2 to evoid the bug in 2.2.4 where token.morph.__repr__() returns a list instead of a str. Now when I `import spacy` I get the following exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/conda/anaconda3/envs/femdwell-debug/lib/python3.6/site-packages/spacy/__init__.py", line 12, in <module>
    from . import pipeline
  File "/home/conda/anaconda3/envs/femdwell-debug/lib/python3.6/site-packages/spacy/pipeline/__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 25, in init spacy.pipeline.pipes
  File "/home/conda/anaconda3/envs/femdwell-debug/lib/python3.6/site-packages/spacy/pipeline/functions.py", line 5, in <module>
    from ..matcher import Matcher
  File "/home/conda/anaconda3/envs/femdwell-debug/lib/python3.6/site-packages/spacy/matcher/__init__.py", line 5, in <module>
    from .phrasematcher import PhraseMatcher
  File "phrasematcher.pyx", line 1, in init spacy.matcher.phrasematcher
ImportError: preshed.maps does not export expected C function map_clear
```
This only appears on one of my computers, but unfortunately it is the one where I need to develop.

The computer is a 64bit intel and is running Ubuntu 18.04.5 LTS . Spacy was installed into a conda (version 4.7.10) environment using "pip install -U spacy".

**Comment by adrianeboyd** [comment]
Hmm, what version of `preshed` is installed? It's possible manually updating `preshed` to the newest version would fix this.

As an alternative to try, does it work if you create a new conda env and install spacy with conda from the `conda-forge` channel instead?

```
conda install -c conda-forge spacy
```

**Comment by johann-petrak** [comment]
Thanks!

I was never able to understand what the difference of installing via pip and via conda is for the user and if it is supposed to make any difference. 

However, I did the equivalent of power-off and on again in the meantime and completely removed Spacy and then reinstalled and after that it worked. I guess I  the pip dependency resolution mechanism was to blame. 

Therefore closing this.
