### ISSUE TITLE
Cannot convert 'TokenC *' to Python object

### ISSUE THREAD

**Issue by hsali** [explosion/spaCy#602]
I was installing spacy from source. When I executed the last command .

    pip install -e .

this error log appeared. 
`
pip install -e .
Obtaining file:///home/shehbaz/Documents/practice/spacy/spaCy
    Complete output from command python setup.py egg_info:
    warning: vocab.pyx:397:26: local variable 'orth' referenced before assignment
    warning: vocab.pyx:397:49: local variable 'lexeme' referenced before assignment
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef int assign_tag(self, TokenC* token, tag) except -1:
            if isinstance(tag, basestring):
                tag_id = self.reverse_index[self.strings[tag]]
            else:
                tag_id = self.reverse_index[tag]
            self.assign_tag_id(token, tag_id)
                                   ^
    ------------------------------------------------------------
    
    morphology.pyx:42:32: Cannot convert 'TokenC *' to Python object
    Processing lexeme.pyx
    Processing typedefs.pyx
    Processing vocab.pyx
    Processing attrs.pyx
    Processing gold.pyx
    Processing morphology.pyx
    Traceback (most recent call last):
      File "/home/shehbaz/Documents/practice/spacy/spaCy/bin/cythonize.py", line 156, in <module>
        run(args.root)
      File "/home/shehbaz/Documents/practice/spacy/spaCy/bin/cythonize.py", line 147, in run
        process(base, filename, db)
      File "/home/shehbaz/Documents/practice/spacy/spaCy/bin/cythonize.py", line 113, in process
        preserve_cwd(base, process_pyx, root + '.pyx', root + '.cpp')
      File "/home/shehbaz/Documents/practice/spacy/spaCy/bin/cythonize.py", line 78, in preserve_cwd
        func(*args)
      File "/home/shehbaz/Documents/practice/spacy/spaCy/bin/cythonize.py", line 60, in process_pyx
        raise Exception('Cython failed')
    Exception: Cython failed
    Cythonizing sources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/shehbaz/Documents/practice/spacy/spaCy/setup.py", line 229, in <module>
        setup_package()
      File "/home/shehbaz/Documents/practice/spacy/spaCy/setup.py", line 180, in setup_package
        generate_cython(root, 'spacy')
      File "/home/shehbaz/Documents/practice/spacy/spaCy/setup.py", line 122, in generate_cython
        raise RuntimeError('Running cythonize failed')
    RuntimeError: Running cythonize failed
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/shehbaz/Documents/practice/spacy/spaCy/

`

If you're looking for help with your code, consider posting a question on StackOverflow instead:
http://stackoverflow.com/questions/tagged/spacy -->

## Your Environment

* **Operating System: Ubuntu 16.04 LTS** 
* **  Used: first time.** 
* **spaCy  Used: latest from this repository** 
* **Environment Information: virtual environment, python 2.7.12**

**Comment by honnibal** [comment]
I was hacking on master and broke the build :(. Sorry folks.
