### ISSUE TITLE
MemoryError on spacy.load('en')

### ISSUE THREAD

**Issue by vpekar** [explosion/spaCy#610]
The parser model fails to load with the error:
```
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    nlp = spacy.load('en')
  File "C:\Python27\lib\site-packages\spacy\__init__.py", line 47, in load
    return cls(path=path, **overrides)
  File "C:\Python27\lib\site-packages\spacy\language.py", line 274, in __init__
    if 'parser' not in overrides \
  File "C:\Python27\lib\site-packages\spacy\language.py", line 102, in create_parser
    return DependencyParser.load(nlp.path / 'deps', nlp.vocab)
  File "spacy/syntax/parser.pyx", line 99, in spacy.syntax.parser.Parser.load (spacy/syntax/parser.cpp:5322)
    self.model.load(str(path / 'model'))
  File "thinc/linear/avgtron.pyx", line 89, in thinc.linear.avgtron.AveragedPerceptron.load (thinc/linear/avgtron.cpp:3092)
    self.weights = PreshMap(reader.nr_feat)
  File "preshed/maps.pyx", line 23, in preshed.maps.PreshMap.__init__ (preshed/maps.cpp:1200)
    map_init(self.mem, self.c_map, initial_size)
  File "preshed/maps.pyx", line 90, in preshed.maps.map_init (preshed/maps.cpp:2876)
    map_.cells = <Cell*>mem.alloc(length, sizeof(Cell))
  File "cymem/cymem.pyx", line 42, in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1091)
    raise MemoryError("Error assigning %d bytes" % number * elem_size)
MemoryError: Error assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytes
```

## Your Environment

* **Operating System:** Windows 7
* **Python Version Used:** Python 2.7.12
* **spaCy Version Used:** 1.2.0
* **Environment Information:** a virtual environment with only spacy and its dependencies

**Comment by honnibal** [comment]
How much memory do you have?

**Comment by vpekar** [comment]
16 Gb

**Comment by honnibal** [comment]
Hmm. Troubling.

**Comment by honnibal** [comment]
Does it still fail if you do:

```python

import spacy

nlp = spacy.load('en', parser=False)
```

**Comment by vpekar** [comment]
No, it loads fine without the parser.

**Comment by honnibal** [comment]
Would you mind trying:

```python

pip install spacy==0.101.0
```

To help bisect the problem?

**Comment by vpekar** [comment]
Yes, this loads without problems.

**Comment by alonsegal** [comment]
I get the same error with v1.2.0 on Windows with 8GB.
I guess it's an issue with the latest release according to the other comments.

Any ideas?

**Comment by ines** [comment]
Glad you got it to work – thanks for sharing your solution!
At the moment, we only support 64bit architectures.

**Comment by Shudipta** [comment]
I'm using
Operating System: Ubuntu 14.04(64-bit) and 2GB memory
Python Version Used: Python 2.7.6
spaCy Version Used: 1.9.0
No virtual environment set up before.
And I have this problem in loading model 'en'

**Comment by bufferbob** [comment]
same problem, still exists, using Python 2.7 32bits for some reasons, will 32bits Python ever be supported ?
