### ISSUE TITLE
Error while using pretrained transformer model on CLI train 

### ISSUE THREAD

**Issue by danielvasic** [explosion/spaCy#6251]
## How to reproduce the behaviour

Hello, wanted to use pretrained BERT vectors from PyTorch and fine tune those vectors for tagger, ner and parser. I have converted my conllu files into jsonl format sucessfully. Also I have coverted PyTorch pretrained model into SpaCy model using this script:

```
from spacy_transformers import TransformersLanguage, TransformersWordPiecer, TransformersTok2Vec
from pathlib import Path

pytorch_path = "bert-pytorch-crosloengual"
spacy_path = "bert-spacy-crosloengual"
name = "bert_hr_crosloengual_cased"

nlp = TransformersLanguage(trf_name=name, meta={"lang": "hr"})
nlp.add_pipe(nlp.create_pipe("sentencizer"))
nlp.add_pipe(TransformersWordPiecer.from_pretrained(nlp.vocab, pytorch_path))
nlp.add_pipe(TransformersTok2Vec.from_pretrained(nlp.vocab, pytorch_path))

nlp.to_disk(spacy_path)
```
And sucessfully started the training using spaCy CLI:

`python -m spacy train hr models/hr/joint train.json dev.json -b models/hr/CroSloEngualBERT/ -p tagger,ner,parser,trf_tok2vec,trf_wordpiecer -g 1`

But mid training this error occures:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/spacy/cli/train.py", line 430, in train
    losses=losses,
  File "/usr/local/lib/python3.6/dist-packages/spacy_transformers/language.py", line 97, in update
    docs, drop=drop, **component_cfg.get(PIPES.tok2vec, {})
  File "/usr/local/lib/python3.6/dist-packages/spacy_transformers/pipeline/tok2vec.py", line 130, in begin_update
    outputs, backprop = self.model.begin_update(docs, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/spacy_transformers/model_registry.py", line 402, in sentence_fwd
    return layer.begin_update([d[:] for d in docs], drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/spacy_transformers/model_registry.py", line 337, in apply_model_to_batches
    return model.begin_update(inputs, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/spacy_transformers/wrapper.py", line 101, in begin_update
    y_var = self._model(**model_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_bert.py", line 783, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_bert.py", line 174, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1814, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```
I'm also using [spaCy transformers](https://spacy.io/universe/project/spacy-transformers) package to convert PyTorch model. Seems to be a problem with the vocabulary size.

## Your Environment

* spaCy version    2.3.2                         
* Location         /usr/local/lib/python3.6/dist-packages/spacy
* Platform         Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
* Python version   3.6.9

**Comment by adrianeboyd** [comment]
I think the short answer is that this is not really going to work in v2. You can train with `-p tagger,parser,ner` (no transformers) or with transformers for `trf_textcat`. The components `tagger`/`parser`/`ner` won't be supported until spacy v3, with a new rewrite of `spacy-transformers` (v1.0.0rc0 was just published). We're at the point where we're preparing transformers models for an official `spacy-nightly` release, which is coming soon.

**Comment by danielvasic** [comment]
Dear @adrianeboyd thank you for the update. 😊Looking forward for the new releases.

BR, 
Daniel
