### ISSUE TITLE
migrating from version 2 to version 3 (installation issue first)

### ISSUE THREAD

**Issue by myeghaneh** [explosion/spaCy#6357]
## How to reproduce the problem
 I used a clean env to install spacy 3, 

```
python -m venv .env
.env\Scripts\activate
pip install -U pip setuptools wheel
pip install -U spacy-nightly --pre
python -m spacy download en_core_web_sm
```

```bash
 from .tokenizations import (
(testenv04) C:\Users\moha>python -m spacy download en_core_web_sm
Traceback (most recent call last):
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\site-packages\spacy\__init__.py", line 13, in <module>
    from . import pipeline  # noqa: F401
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\site-packages\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\site-packages\spacy\pipeline\attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy\\pipeline\\pipe.pyx", line 8, in init spacy.pipeline.pipe
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\site-packages\spacy\training\__init__.py", line 1, in <module>
    from .corpus import Corpus  # noqa: F401
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\site-packages\spacy\training\corpus.py", line 8, in <module>
    from .augment import dont_augment
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\site-packages\spacy\training\augment.py", line 10, in <module>
    from .example import Example
  File "spacy\\training\\example.pyx", line 10, in init spacy.training.example
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\site-packages\spacy\training\align.py", line 5, in <module>
    import tokenizations
  File "C:\Users\moha\Anaconda3\envs\testenv04\lib\site-packages\tokenizations\__init__.py", line 2, in <module>
    from .tokenizations import (
ModuleNotFoundError: No module named 'tokenizations.tokenizations'

(testenv04) C:\Users\moha>

```

## Your Environment

* Operating System:
win 10
* Python Version Used:
(testenv04) C:\Users\moha>python --version
Python 3.9.0
* spaCy Version Used:
try to have the version 3
* Environment Information:

 I have also written my other question here

https://support.prodi.gy/t/updating-training-pipline-of-ner-from-spacy-2-to-spacy-3/3592

**Comment by adrianeboyd** [comment]
Please use python 3.8 instead of python 3.9 for now. We are working on it, but don't have binary wheels for python 3.9 published yet.
