### ISSUE TITLE
 [Errno 2] No such file or directory: '/tmp/pip-req-build-vljn__of/setup.py'

### ISSUE THREAD

**Issue by eliasyin** [explosion/spaCy#6365]
## How to reproduce the problem
I have installed spacy 2.3.1 in linux server. When I install language model, I get the error:

Due to network problems, I download the model and plan to install it offline:
```bash
pip install en_core_web_sm-2.3.1.tar.gz
```
After run the command, I get the error message:
```bash
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing ./en_core_web_sm-2.3.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/ycf19/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vljn__of/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vljn__of/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lk4jkesa
         cwd: /tmp/pip-req-build-vljn__of/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ycf19/anaconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-vljn__of/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## Info about spaCy

* **spaCy version:** 2.3.1
* **Platform:** Linux-4.15.0-72-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.0

**Comment by eliasyin** [comment]
I finally find the tar.gz file I downloaded is broken.
I re-download the tar.gz file, and there isn't any errors any more.
