### ISSUE TITLE
Spacy Nightly crashes if i dont import torch first

### ISSUE THREAD

**Issue by p-sodmann** [explosion/spaCy#6387]
## How to reproduce the behaviour
if i import spacy i get the error

```Traceback (most recent call last):
  File "pathToAnaconda\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
    |                          |                   |         -> <class 'runpy._Error'>
    |                          |                   -> 'spacy'
    |                          -> <function _get_module_details at 0x000001FDB80B73A8>
    -> 'spacy'
  File "pathToAnaconda\Anaconda3\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
           |                   |              -> <class 'runpy._Error'>
           |                   -> 'spacy.__main__'
           -> <function _get_module_details at 0x000001FDB80B73A8>
  File "pathToAnaconda\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
               -> 'spacy'
  File "pathToAnaconda\Anaconda3\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.api import prefer_gpu, require_gpu  # noqa: F401
  File "pathToAnaconda\Anaconda3\lib\site-packages\thinc\api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "pathToAnaconda\Anaconda3\lib\site-packages\thinc\initializers.py", line 4, in <module>
    from .backends import Ops
  File "pathToAnaconda\Anaconda3\lib\site-packages\thinc\backends\__init__.py", line 6, in <module>
    from .ops import Ops
  File "pathToAnaconda\Anaconda3\lib\site-packages\thinc\backends\ops.py", line 10, in <module>
    from ..util import get_array_module, is_xp_array, to_numpy
  File "pathToAnaconda\Anaconda3\lib\site-packages\thinc\util.py", line 27, in <module>
    import torch
  File "pathToAnaconda\Anaconda3\lib\site-packages\torch\__init__.py", line 117, in <module>
    raise err
          -> OSError(22, 'Die angegebene Prozedur wurde nicht gefunden.', None, 127)
OSError: [WinError 127] Die angegebene Prozedur wurde nicht gefunden. Error loading "pathToAnaconda\Anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.```

It does work when I import torch first.
I am running Pytorch 1.7 with cuda 10.1

## Your Environment
* Operating System: Windows 10
* Python Version Used: 3.7.4
* spaCy Version Used: Nightly
* Environment Information:

**Comment by svlandeg** [comment]
I recently ran into the same issue, I think it indicates a corrupt environment. Some files may not have been updated properly. When I started in a new, fresh env, it did work.

**Comment by p-sodmann** [comment]
I will try to install a fresh conda environment and update this.

**Comment by honnibal** [comment]
Just to elaborate a little on how this happens:

`pip install --upgrade` doesn't know how to clean the directory it's installing over, because it needs to be careful not to delete additional files. Unfortunately, this means that additional modules or other files might be present for C extensions, if some module has been renamed or removed in between versions. These extra files can then cause problems.

The net effect of this is, due to really old design decisions, upgrading a package with pip is not guaranteed to leave you with a usable state. This is one of the reasons virtualenvs are important: you may need to install packages from scratch, rather than updating them.
