### ISSUE TITLE
since macOS Big Sur: Spacy not installable

### ISSUE THREAD

**Issue by tbrodbeck** [explosion/spaCy#6425]
## How to reproduce the problem

after `pip install spacy` and `python -m spacy validate` I get this output:
```
python3(1833,0x10437de00) malloc: can't allocate region
:*** mach_vm_map(size=18446744072576753664, flags: 100) failed (error code=3)
python3(1833,0x10437de00) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "/Users/tillmann/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/tillmann/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/tillmann/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/tillmann/dev/summarization-toolbox/.direnv/python-3.7.9/lib/python3.7/site-packages/spacy/__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/Users/tillmann/dev/summarization-toolbox/.direnv/python-3.7.9/lib/python3.7/site-packages/thinc/__init__.py", line 5, in <module>
    import numpy  # noqa: F401
  File "/Users/tillmann/dev/summarization-toolbox/.direnv/python-3.7.9/lib/python3.7/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

## Your Environment

* Operating System: macOS 11.0.1
* Python Version Used: I tried `3.7.9`, `3.9.0`
* spaCy Version Used: I tried `2.3` and `2.0`
* Environment Information: Host: MacBookPro 15,1 Shell: `zsh` `5.8`

**Comment by adrianeboyd** [comment]
This is a problem with `numpy` and not `spacy` itself, most likely related to how `pip` detects whether a binary wheel is compatible. Here's the relevant numpy issue: https://github.com/numpy/numpy/issues/17784

It looks like there are some working solutions in that thread, you'll have to see what makes sense for your setup and try some of the alternatives. I'm not entirely sure, but from reading the related threads I think the next version of `pip` may fix this problem.

I'm not sure from that thread which solutions actually worked (if renaming the wheel works, I think that would be the easiest workaround, but I can't tell for sure), so I'd probably suggest this option, which builds numpy from source with an appropriate BLAS library:

https://github.com/numpy/numpy/issues/17784#issuecomment-729950525

You can test your numpy install by running its test suite after installing:

```bash
python -c 'import numpy; numpy.test()'
```
