### ISSUE TITLE
ModuleNotFoundError: No module named 'tokenizations.tokenizations'

### ISSUE THREAD

**Issue by bwholman** [explosion/spaCy#6427]
## How to reproduce the problem
Working in Visual Studio Code terminal window.  New Python project, new virtual env:

python -m venv .env
.env\Scripts\activate
pip install -U pip setuptools wheel
pip install -U spacy-nightly --pre
python -m spacy validate

## output from spacy validate
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python39\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\bruce\source\repos\edith_functions\.env\lib\site-packages\spacy\__init__.py", line 13, in <module>
    from . import pipeline  # noqa: F401
  File "C:\Users\bruce\source\repos\edith_functions\.env\lib\site-packages\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "C:\Users\bruce\source\repos\edith_functions\.env\lib\site-packages\spacy\pipeline\attributeruler.py", line 6, in <module>       
    from .pipe import Pipe
  File "spacy\pipeline\pipe.pyx", line 8, in init spacy.pipeline.pipe
  File "C:\Users\bruce\source\repos\edith_functions\.env\lib\site-packages\spacy\training\__init__.py", line 1, in <module>
    from .corpus import Corpus  # noqa: F401
  File "C:\Users\bruce\source\repos\edith_functions\.env\lib\site-packages\spacy\training\corpus.py", line 8, in <module>
    from .augment import dont_augment
  File "C:\Users\bruce\source\repos\edith_functions\.env\lib\site-packages\spacy\training\augment.py", line 10, in <module>
    from .example import Example
  File "spacy\training\example.pyx", line 10, in init spacy.training.example
  File "C:\Users\bruce\source\repos\edith_functions\.env\lib\site-packages\spacy\training\align.py", line 5, in <module>
    import tokenizations
  File "C:\Users\bruce\source\repos\edith_functions\.env\lib\site-packages\tokenizations\__init__.py", line 2, in <module>
    from .tokenizations import (
ModuleNotFoundError: No module named 'tokenizations.tokenizations'

## Your Environment
* Operating System: Windows 10
* Python Version Used: 3.9.0 64-bit
* spaCy Version Used: spacy-nightly-3.0.0rc2

**Comment by solarmist** [comment]
Doesn't work on Python 3.9 yet. Use 3.8.

See this issue
https://github.com/explosion/spaCy/issues/6357

**Comment by adrianeboyd** [comment]
Yes, using python <=3.8 is the right solution for now.

In case others come across this in the future:

We're dropping this dependency for the next spacy v3 rc release (will be `v3.0.0rc3`), so this particular problem shouldn't be an issue for the final v3 release.

We still have some outstanding issues related to other dependencies for python 3.9, so I'm not sure when we'll have python 3.9 wheels for v3 at this point, though.
