### ISSUE TITLE
Building from source: undeclared name not builtin: PY_VERSION_HEX

### ISSUE THREAD

**Issue by grwlf** [explosion/spaCy#648]
Hi. I am packaging Spacy for NixOS and issued an error (see below). Does it look familiar? What should I do to fix it?

Thanks!

```
Error compiling Cython file:
------------------------------------------------------------

cdef dict __Pyx_globals = globals()
if PY_VERSION_HEX >= 0x03040000:
                 ^
------------------------------------------------------------

EnumType:51:18: undeclared name not builtin: PY_VERSION_HEX
Traceback (most recent call last):
  File "/nix/store/iz9xmfqca3g1hn3pd7r0wqsfhwy3ali5-python2.7-Cython-0.24.1/bin/.cython-wrapped", line 12, in <module>
    sys.exit(setuptools_main())
  File "/nix/store/iz9xmfqca3g1hn3pd7r0wqsfhwy3ali5-python2.7-Cython-0.24.1/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 698, in setuptools_main
    return main(command_line = 1)
  File "/nix/store/iz9xmfqca3g1hn3pd7r0wqsfhwy3ali5-python2.7-Cython-0.24.1/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 715, in main
    result = compile(sources, options)
  File "/nix/store/iz9xmfqca3g1hn3pd7r0wqsfhwy3ali5-python2.7-Cython-0.24.1/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 690, in compile
    return compile_multiple(source, options)
  File "/nix/store/iz9xmfqca3g1hn3pd7r0wqsfhwy3ali5-python2.7-Cython-0.24.1/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 668, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/nix/store/iz9xmfqca3g1hn3pd7r0wqsfhwy3ali5-python2.7-Cython-0.24.1/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 495, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/nix/store/iz9xmfqca3g1hn3pd7r0wqsfhwy3ali5-python2.7-Cython-0.24.1/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 365, in run_pipeline
    data = phase(data)
  File "/nix/store/iz9xmfqca3g1hn3pd7r0wqsfhwy3ali5-python2.7-Cython-0.24.1/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 130, in inject_utility_code_stage
    tree = utilcode.get_tree(cython_scope=context.cython_scope)
  File "/nix/store/iz9xmfqca3g1hn3pd7r0wqsfhwy3ali5-python2.7-Cython-0.24.1/lib/python2.7/site-packages/Cython/Compiler/UtilityCode.py", line 167, in get_tree
    assert not err, err
```

## Your Environment

* **Operating System:** NixOS
* **Python Version Used:** 2.7
* **spaCy Version Used:** 1.2.0
* **Environment Information:**

**Comment by aborsu** [comment]
PY_VERSION_HEX is the CPYTHON version as defined here. 
https://docs.python.org/3/c-api/apiabiversion.html

What is wierd is that it should only fail for python above 3.4 and you are using python2.7

**Comment by pquentin** [comment]
`PY_VERSION_HEX` is defined in patchlevel.h, which is included from Python.h. See https://hg.python.org/cpython/file/tip/Include/patchlevel.h. Probably not spaCy's fault?

**Comment by honnibal** [comment]
I think this is a Cython version problem. Could you try with cython<0.24?

**Comment by grwlf** [comment]
Thanks! I'll investigate this. Closing the issue for now.

**Comment by Eddy-zheng** [comment]
I update my cython to latest version. Bug fix~
