### ISSUE TITLE
Cannot initialize tagger in spacy train or debug data.

### ISSUE THREAD

**Issue by JudSchneider** [explosion/spaCy#6567]
## How to reproduce the behaviour

Hello!

I am not sure if this is a bug in `spacy train` or `spacy convert`.  I am migrating data from 2.3 to 3.0 to test out NER accuracy.  While running `spacy train` or `spacy debug data`, i get the same error.  `spacy debug config` passes just fine.  I migrated the data from `.jsonl` in 2.2 collected with prodigy, to 3.0 using `spacy convert`.

```
python3 -m spacy convert /host/prodigy/data/3-0_spacy/training_data/train.json /host/prodigy/data/3-0_spacy/training_data/train/ -c json -n 1 -l en

python3 -m spacy convert /host/prodigy/data/3-0_spacy/training_data/eval.json /host/prodigy/data/3-0_spacy/training_data/eval/ -c json -n 1 -l en

python3 -m spacy train /host/prodigy/data/3-0_spacy/training_data/config.cfg --output /host/prodigy/data/3-0_spacy/models/ --paths.train /host/prodigy/data/3-0_spacy/training_data/train.spacy --paths.dev /host/prodigy/data/3-0_spacy/training_data/eval.spacy --verbose
Config overrides from CLI: ['paths.train', 'paths.dev']
ℹ Using CPU

=========================== Initializing pipeline ===========================
Set up nlp object from config
Loading corpus from path: /host/prodigy/data/3-0_spacy/training_data/eval.spacy
Loading corpus from path: /host/prodigy/data/3-0_spacy/training_data/train.spacy
Pipeline: ['tok2vec', 'tagger', 'parser', 'ner']
Created vocabulary
Added vectors: en_core_web_lg
Finished initializing nlp object
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/usr/local/lib/python3.8/dist-packages/spacy/cli/_util.py", line 65, in setup_cli
    command(prog_name=COMMAND)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/usr/local/lib/python3.8/dist-packages/spacy/training/initialize.py", line 55, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/usr/local/lib/python3.8/dist-packages/spacy/language.py", line 1232, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "spacy/pipeline/tagger.pyx", line 301, in spacy.pipeline.tagger.Tagger.initialize
  File "/usr/local/lib/python3.8/dist-packages/thinc/model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "/usr/local/lib/python3.8/dist-packages/thinc/layers/chain.py", line 90, in init
    curr_input = layer.predict(curr_input)
  File "/usr/local/lib/python3.8/dist-packages/thinc/model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "/usr/local/lib/python3.8/dist-packages/thinc/layers/with_array.py", line 41, in forward
    return _list_forward(cast(Model[List2d, List2d], model), Xseq, is_train)
  File "/usr/local/lib/python3.8/dist-packages/thinc/layers/with_array.py", line 79, in _list_forward
    Yf, get_dXf = layer(Xf, is_train)
  File "/usr/local/lib/python3.8/dist-packages/thinc/model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "/usr/local/lib/python3.8/dist-packages/thinc/layers/softmax.py", line 35, in forward
    Y = model.ops.softmax(Y)
 File "/usr/local/lib/python3.8/dist-packages/thinc/backends/ops.py", line 585, in softmax
    maxes = self.xp.max(x, axis=axis, keepdims=True)
  File "<__array_function__ internals>", line 5, in amax
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

I get the same error when running `spacy debug data`.

## Your Environment

* Operating System:
* Python Version Used: 3.8
* spaCy Version Used: 3.0.0rc2
* Environment Information:
local docker container Ubuntu 20.04 base image, with python 3.8 and `pip install -U spacy-nightly[lookups,transformers] --pre`

**Comment by svlandeg** [comment]
Does your training dataset contain gold-standard tagging information? Because you mention NER - but your config also defines a tagger and a parser. 

If that's not the problem - would you be able to share a small snippet of `train.json` and of `eval.json`?

**Comment by svlandeg** [comment]
I've been able to replicate this - will look into a fix!

**Comment by svlandeg** [comment]
The error message is improved by PR https://github.com/explosion/spaCy/pull/6580 - let us know if you still into trouble! I'll close this in the meantime.

**Comment by JudSchneider** [comment]
Thanks Sophie!  Sorry for the delayed response. I was able to train by
removing the tokenizer.

**Comment by svlandeg** [comment]
Happy to hear it!
