### ISSUE TITLE
Value Error after Update with no precise reason

### ISSUE THREAD

**Issue by Mintbach** [explosion/spaCy#6675]
I try to run the following code 
```
nlp = spacy.load("en_core_web_trf", exclude='ner')

default_model = """
[model]
@architectures = "spacy.TransitionBasedParser.v1"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = false
nO = null

[model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
"""

config = Config().from_str(default_model)

data_filtered = filter_relevant(data)

TRAIN_DATA = create_dataset(data_filtered[:32], LABEL)

nlp.add_pipe("ner", config=config)

ner = nlp.get_pipe("ner")

ner.add_label(LABEL)

ner.initialize(lambda: TRAIN_DATA)

pipe_exceptions = ["ner"]
unaffected_pipes = [pipe for pipe in nlp.pipe_names if pipe not in pipe_exceptions]

for iteration in range(30):
    

    losses = {}
    nlp.update([TRAIN_DATA[2]],
               drop=0.5,  
               losses=losses,
               exclude=unaffected_pipes)

```

I want to train a custom Entity Recognition Pipe. The whole code is running through, when i use the debugger. Losses are returned in language.py, as far as i can see it calls update with the right configuration of the pipe. But when the debugger is returning to my code the program throws this error. I reckon there is happening something odd with configurations, as the default configuration of the NER Pipe is not listening to the needed Transformer output. 
Here is the error text + big thank you for this great library:

```
Traceback (most recent call last):
  File "/snap/pycharm-professional/228/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/228/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/stephan/Classification/get_important_words.py", line 108, in <module>
    exclude=unaffected_pipes)
  File "/home/stephan/.local/lib/python3.6/site-packages/spacy/language.py", line 1096, in update
    proc.update(examples, sgd=None, losses=losses, **component_cfg[name])
  File "spacy/pipeline/transition_parser.pyx", line 284, in spacy.pipeline.transition_parser.Parser.update
  File "/home/stephan/.local/lib/python3.6/site-packages/thinc/model.py", line 306, in begin_update
    return self._func(self, X, is_train=True)
  File "/home/stephan/.local/lib/python3.6/site-packages/spacy/ml/tb_framework.py", line 34, in forward
    has_upper=model.attrs["has_upper"],
  File "spacy/ml/parser_model.pyx", line 216, in spacy.ml.parser_model.ParserStepModel.__init__
  File "/home/stephan/.local/lib/python3.6/site-packages/thinc/model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/stephan/.local/lib/python3.6/site-packages/thinc/layers/chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "/home/stephan/.local/lib/python3.6/site-packages/thinc/model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/stephan/.local/lib/python3.6/site-packages/thinc/layers/chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "/home/stephan/.local/lib/python3.6/site-packages/thinc/model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/stephan/.local/lib/python3.6/site-packages/spacy_transformers/layers/listener.py", line 58, in forward
    model.verify_inputs(docs)
  File "/home/stephan/.local/lib/python3.6/site-packages/spacy_transformers/layers/listener.py", line 47, in verify_inputs
    raise ValueError
ValueError
```
 

## Your Environment

- Operating System:
Ubuntu 18.04 LTS
- Python Version Used:
Python 3.6
- spaCy Version Used:
spaCy Nightly 
- Environment Information:
--

**Comment by svlandeg** [comment]
So what happens in the [`TransformerListener`](https://nightly.spacy.io/api/architectures#TransformerListener), is that it fetches the results that were previously obtained by the [`Transformer`](https://nightly.spacy.io/api/transformer) in the pipeline. However with the `exclude` argument you basically freeze the Transformer, so the listener can't get the required results, nor update the transformer in the process.

You have a few options:
- Reuse the transformer from the trained pipeline, as you intend to do, but make sure the `transformer` component can be updated by excluding it from the exclude list ;-). Note that the pretrained (and frozen) `parser` and `tagger` will not be accurately trained anymore after this, because the shared transformer will be changed.
- Create a new transformer or Tok2Vec layer specific to your NER instance. This means you'd basically mix and match the two strategies explained here: https://nightly.spacy.io/usage/embeddings-transformers#embedding-layers. Then you can train your NER model separately, and afterwards combine it with the pretrained tagger/parser if you'd want. You can have multiple transformer components in the pipeline, just give them different names, and set the listener's `upstream` argument(s) appropriately.
