### ISSUE TITLE
ImportError: DLL load failed while importing nn_parser: The specified module could not be found.

### ISSUE THREAD

**Issue by thisisSisam** [explosion/spaCy#6697]
when I try to download models or Validate or use info --markdown I get this error.
```
Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\MSI\Desktop\py\nlps\lib\site-packages\spacy\__init__.py", line 12, in <module>
    from . import pipeline
  File "C:\Users\MSI\Desktop\py\nlps\lib\site-packages\spacy\pipeline\__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 1, in init spacy.pipeline.pipes
ImportError: DLL load failed while importing nn_parser: The specified module could not be found.`
```

I've tried it with python 3.8.6 64-bit, 3.9.0 64-bit and with virtual env. I get the same error.

Here is my pip list for vitual env. 
```
blis       0.7.4
catalogue  1.0.0
certifi    2020.12.5
chardet    4.0.0
cymem      2.0.5
idna       2.10
murmurhash 1.0.5
numpy      1.19.5
pip        20.3.3
plac       1.1.3
preshed    3.0.5
requests   2.25.1
setuptools 49.2.1
spacy      2.3.5
srsly      1.0.5
thinc      7.4.5
tqdm       4.55.1
urllib3    1.26.2
wasabi     0.8.0
```

The message I get when I install spacy 
```
(nlps) C:\Users\MSI\Desktop\py>pip install spacy
Collecting spacy
  Using cached spacy-2.3.5-cp39-cp39-win_amd64.whl (9.4 MB)
Requirement already satisfied: setuptools in c:\users\msi\desktop\py\nlps\lib\site-packages (from spacy) (49.2.1)
Collecting blis<0.8.0,>=0.4.0
  Using cached blis-0.7.4-cp39-cp39-win_amd64.whl (6.5 MB)
Collecting catalogue<1.1.0,>=0.0.7
  Using cached catalogue-1.0.0-py2.py3-none-any.whl (7.7 kB)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.5-cp39-cp39-win_amd64.whl (36 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.5-cp39-cp39-win_amd64.whl (21 kB)
Collecting numpy>=1.15.0
  Using cached numpy-1.19.5-cp39-cp39-win_amd64.whl (13.3 MB)
Collecting plac<1.2.0,>=0.9.6
  Using cached plac-1.1.3-py2.py3-none-any.whl (20 kB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.5-cp39-cp39-win_amd64.whl (112 kB)
Collecting requests<3.0.0,>=2.13.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting srsly<1.1.0,>=1.0.2
  Using cached srsly-1.0.5-cp39-cp39-win_amd64.whl (177 kB)
Collecting thinc<7.5.0,>=7.4.1
  Using cached thinc-7.4.5-cp39-cp39-win_amd64.whl (904 kB)
Collecting tqdm<5.0.0,>=4.38.0
  Downloading tqdm-4.55.1-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 138 kB/s
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting wasabi<1.1.0,>=0.4.0
  Using cached wasabi-0.8.0-py3-none-any.whl (23 kB)
Installing collected packages: numpy, murmurhash, cymem, wasabi, urllib3, tqdm, srsly, preshed, plac, idna, chardet, certifi, catalogue, blis, thinc, requests, spacy
Successfully installed blis-0.7.4 catalogue-1.0.0 certifi-2020.12.5 chardet-4.0.0 cymem-2.0.5 idna-2.10 murmurhash-1.0.5 numpy-1.19.5 plac-1.1.3 preshed-3.0.5 requests-2.25.1 spacy-2.3.5 srsly-1.0.5 thinc-7.4.5 tqdm-4.55.1 urllib3-1.26.2 wasabi-0.8.0
```

**Comment by svlandeg** [comment]
Hm, that's weird. Could you try creating a new virtual environment with Python 3.8 and run the following in that env:
```
pip install -U pip setuptools wheel
pip install --no-cache-dir spacy
```

**Comment by thisisSisam** [comment]
Thank you. I tried what you told but got the same error. 

```(nlps00) C:\Users\MSI\Desktop\py>python -m spacy de_core_news_sm
Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\MSI\Desktop\py\nlps00\lib\site-packages\spacy\__init__.py", line 12, in <module>
    from . import pipeline
  File "C:\Users\MSI\Desktop\py\nlps00\lib\site-packages\spacy\pipeline\__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 1, in init spacy.pipeline.pipes
ImportError: DLL load failed while importing nn_parser: The specified module could not be found.```

I did get a error on `pip install -U pip setuptools wheel`  but that got resolved (I think). here's the log
```(nlps00) C:\Users\MSI\Desktop\py>py --version
Python 3.8.6

(nlps00) C:\Users\MSI\Desktop\py>pip install -U pip setuptools wheel
Collecting pip
  Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
Collecting setuptools
  Using cached setuptools-51.1.1-py3-none-any.whl (2.0 MB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: pip, setuptools, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.2.1
    Uninstalling pip-20.2.1:
      Successfully uninstalled pip-20.2.1
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\MSI\\AppData\\Local\\Temp\\pip-uninstall-g8kh44ae\\pip.exe'
Consider using the `--user` option or check the permissions.


(nlps00) C:\Users\MSI\Desktop\py>pip install -U --user pip setuptools wheel
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

(nlps00) C:\Users\MSI\Desktop\py>pip install -U pip setuptools wheel
Requirement already satisfied: pip in c:\users\msi\desktop\py\nlps00\lib\site-packages (20.3.3)
Requirement already satisfied: setuptools in c:\users\msi\desktop\py\nlps00\lib\site-packages (49.2.1)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools
  Using cached setuptools-51.1.1-py3-none-any.whl (2.0 MB)
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
Successfully installed setuptools-51.1.1 wheel-0.36.2 ```

**Comment by svlandeg** [comment]
Hm, and what does the log for `pip install --no-cache-dir spacy` look like?

**Comment by thisisSisam** [comment]
here's it.
```
(nlps00) C:\Users\MSI\Desktop\py>pip install -U pip setuptools wheel
Requirement already satisfied: pip in c:\users\msi\desktop\py\nlps00\lib\site-packages (20.3.3)
Requirement already satisfied: setuptools in c:\users\msi\desktop\py\nlps00\lib\site-packages (49.2.1)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools
  Using cached setuptools-51.1.1-py3-none-any.whl (2.0 MB)
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
Successfully installed setuptools-51.1.1 wheel-0.36.2

(nlps00) C:\Users\MSI\Desktop\py>pip install --no-cache-dir spacy
Collecting spacy
  Downloading spacy-2.3.5-cp38-cp38-win_amd64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 437 kB/s
Requirement already satisfied: setuptools in c:\users\msi\desktop\py\nlps00\lib\site-packages (from spacy) (51.1.1)
Collecting blis<0.8.0,>=0.4.0
  Downloading blis-0.7.4-cp38-cp38-win_amd64.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 61 kB/s
Collecting catalogue<1.1.0,>=0.0.7
  Downloading catalogue-1.0.0-py2.py3-none-any.whl (7.7 kB)
Collecting cymem<2.1.0,>=2.0.2
  Downloading cymem-2.0.5-cp38-cp38-win_amd64.whl (36 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Downloading murmurhash-1.0.5-cp38-cp38-win_amd64.whl (21 kB)
Collecting numpy>=1.15.0
  Downloading numpy-1.19.5-cp38-cp38-win_amd64.whl (13.3 MB)
     |████████████████████████████████| 13.3 MB 64 kB/s
Collecting plac<1.2.0,>=0.9.6
  Downloading plac-1.1.3-py2.py3-none-any.whl (20 kB)
Collecting preshed<3.1.0,>=3.0.2
  Downloading preshed-3.0.5-cp38-cp38-win_amd64.whl (112 kB)
     |████████████████████████████████| 112 kB 93 kB/s
Collecting requests<3.0.0,>=2.13.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 85 kB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 72 kB/s
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 69 kB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 140 kB/s
Collecting srsly<1.1.0,>=1.0.2
  Downloading srsly-1.0.5-cp38-cp38-win_amd64.whl (178 kB)
     |████████████████████████████████| 178 kB 168 kB/s
Collecting thinc<7.5.0,>=7.4.1
  Downloading thinc-7.4.5-cp38-cp38-win_amd64.whl (910 kB)
     |████████████████████████████████| 910 kB 96 kB/s
Collecting tqdm<5.0.0,>=4.38.0
  Downloading tqdm-4.55.1-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 195 kB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 65 kB/s
Collecting wasabi<1.1.0,>=0.4.0
  Downloading wasabi-0.8.0-py3-none-any.whl (23 kB)
Installing collected packages: numpy, murmurhash, cymem, wasabi, urllib3, tqdm, srsly, preshed, plac, idna, chardet, certifi, catalogue, blis, thinc, requests, spacy
Successfully installed blis-0.7.4 catalogue-1.0.0 certifi-2020.12.5 chardet-4.0.0 cymem-2.0.5 idna-2.10 murmurhash-1.0.5 numpy-1.19.5 plac-1.1.3 preshed-3.0.5 requests-2.25.1 spacy-2.3.5 srsly-1.0.5 thinc-7.4.5 tqdm-4.55.1 urllib3-1.26.2 wasabi-0.8.0
```

**Comment by thisisSisam** [comment]
here's it.
```
(nlps00) C:\Users\MSI\Desktop\py>pip install --no-cache-dir spacy
Collecting spacy
  Downloading spacy-2.3.5-cp38-cp38-win_amd64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 437 kB/s
Requirement already satisfied: setuptools in c:\users\msi\desktop\py\nlps00\lib\site-packages (from spacy) (51.1.1)
Collecting blis<0.8.0,>=0.4.0
  Downloading blis-0.7.4-cp38-cp38-win_amd64.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 61 kB/s
Collecting catalogue<1.1.0,>=0.0.7
  Downloading catalogue-1.0.0-py2.py3-none-any.whl (7.7 kB)
Collecting cymem<2.1.0,>=2.0.2
  Downloading cymem-2.0.5-cp38-cp38-win_amd64.whl (36 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Downloading murmurhash-1.0.5-cp38-cp38-win_amd64.whl (21 kB)
Collecting numpy>=1.15.0
  Downloading numpy-1.19.5-cp38-cp38-win_amd64.whl (13.3 MB)
     |████████████████████████████████| 13.3 MB 64 kB/s
Collecting plac<1.2.0,>=0.9.6
  Downloading plac-1.1.3-py2.py3-none-any.whl (20 kB)
Collecting preshed<3.1.0,>=3.0.2
  Downloading preshed-3.0.5-cp38-cp38-win_amd64.whl (112 kB)
     |████████████████████████████████| 112 kB 93 kB/s
Collecting requests<3.0.0,>=2.13.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 85 kB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 72 kB/s
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 69 kB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 140 kB/s
Collecting srsly<1.1.0,>=1.0.2
  Downloading srsly-1.0.5-cp38-cp38-win_amd64.whl (178 kB)
     |████████████████████████████████| 178 kB 168 kB/s
Collecting thinc<7.5.0,>=7.4.1
  Downloading thinc-7.4.5-cp38-cp38-win_amd64.whl (910 kB)
     |████████████████████████████████| 910 kB 96 kB/s
Collecting tqdm<5.0.0,>=4.38.0
  Downloading tqdm-4.55.1-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 195 kB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 65 kB/s
Collecting wasabi<1.1.0,>=0.4.0
  Downloading wasabi-0.8.0-py3-none-any.whl (23 kB)
Installing collected packages: numpy, murmurhash, cymem, wasabi, urllib3, tqdm, srsly, preshed, plac, idna, chardet, certifi, catalogue, blis, thinc, requests, spacy
Successfully installed blis-0.7.4 catalogue-1.0.0 certifi-2020.12.5 chardet-4.0.0 cymem-2.0.5 idna-2.10 murmurhash-1.0.5 numpy-1.19.5 plac-1.1.3 preshed-3.0.5 requests-2.25.1 spacy-2.3.5 srsly-1.0.5 thinc-7.4.5 tqdm-4.55.1 urllib3-1.26.2 wasabi-0.8.0
```

**Comment by svlandeg** [comment]
I'm grasping at straws here, but what if you downgrade pip to something like `20.2.4` (and restart in a fresh env etc...)

**Comment by thisisSisam** [comment]
yes I did, downgraded to `20.2.3` tried both `3.9` & `3.8`  but got the same error

**Comment by svlandeg** [comment]
I don't really understand what's going on. It should just work (I just tested myself with Python 3.7 and had no issues, but 3.8 should be fine as well, and we recently added the support for 3.9 so...)

In the past when we've seen this type of error (also on other libraries), it was typically an issue with `pip`, and the errors you got while upgrading seem to enforce that idea. Other than that I don't really know, maybe someone else has an idea?

**Comment by svlandeg** [comment]
Hi @thisisSisam, just wondering, have you been able to get this to work?

**Comment by thisisSisam** [comment]
I had another pc too so I gave up a day after that. Thanks for your help though @svlandeg !

**Comment by svlandeg** [comment]
Oh ok ;-) Well, at least you had an alternative. Sorry we couldn't get to the bottom of this!

I guess I'll close this in the meantime.
