### ISSUE TITLE
OSError on load_vectors_from_bin_loc()

### ISSUE THREAD

**Issue by petterhh** [explosion/spaCy#671]
I have a word2vec model (binary) that I want to load into the vocab before training with `train_ud.py`. Unfortunately, I'm met by an `OSError` when running `load_vectors_from_bin_loc()`. 

```python
Traceback (most recent call last):
  File "spacy/bin/parser/train_ud.py", line 112, in <module>
    plac.call(main)
  File "/Users/petterhohle/.pyenv/versions/spacy/lib/python3.5/site-packages/plac_core.py", line 326, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/Users/petterhohle/.pyenv/versions/spacy/lib/python3.5/site-packages/plac_core.py", line 209, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "spacy/bin/parser/train_ud.py", line 78, in main
    vocab.load_vectors_from_bin_loc('/Users/petterhohle/coding/spacy-nor/nak_nowac.bin')
  File "spacy/vocab.pyx", line 528, in spacy.vocab.Vocab.load_vectors_from_bin_loc (spacy/vocab.cpp:10682)
  File "spacy/cfile.pyx", line 41, in spacy.cfile.CFile.alloc_read (spacy/cfile.cpp:1420)
  File "spacy/cfile.pyx", line 32, in spacy.cfile.CFile.read_into (spacy/cfile.cpp:1279)
OSError
```
The error message is not exactly descriptive, so I'm wondering what might be the issue here?

**Comment by honnibal** [comment]
Agree that the error messaging could be improved. It's difficult because we're reporting from a C error. I need to look into checking the error message properly.

Have you checked the obvious, like whether the file exists, whether you have enough memory...?

**Comment by petterhh** [comment]
Yeah, the file exists - for non-existing files the error is more precise; ```OSError: Could not open binary file b'<filename>'```.

I have 8 GB memory and more than 2 GB available, which should suffice?

**Comment by ines** [comment]
Closing this and making #1046 the master issue. Work in progress for spaCy v2.0!
