### ISSUE TITLE
spaCy en_core_web_trf model does not load in 3.0.0rc3

### ISSUE THREAD

**Issue by forgetso** [explosion/spaCy#6756]
## How to reproduce the behaviour
Install spacy 3.0.0rc3 and the en transformer model. Then try to load the model.
```
python -m spacy download en_core_web_trf
...
Successfully installed catalogue-2.0.1 pydantic-1.7.3 thinc-8.0.0rc4
✔ Download and installation successful
```
```
Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 05:05:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.load('en_core_web_trf')
```
## Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/dev/spaCy/spacy/__init__.py", line 48, in load
    return util.load_model(name, disable=disable, exclude=exclude, config=config, shared=shared)
  File "/home/user/dev/spaCy/spacy/util.py", line 323, in load_model
    return load_model_from_package(name, **kwargs)
  File "/home/user/dev/spaCy/spacy/util.py", line 357, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)
  File "/home/user/anaconda3/envs/package/lib/python3.8/site-packages/en_core_web_trf/__init__.py", line 9, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/user/dev/spaCy/spacy/util.py", line 505, in load_model_from_init_py
    return load_model_from_path(
  File "/home/user/dev/spaCy/spacy/util.py", line 392, in load_model_from_path
    nlp = load_model_from_config(config, vocab=vocab, disable=disable, exclude=exclude, shared=shared)
  File "/home/user/dev/spaCy/spacy/util.py", line 430, in load_model_from_config
    nlp = lang_cls.from_config(
  File "/home/user/dev/spaCy/spacy/language.py", line 1623, in from_config
    nlp.add_pipe(
  File "/home/user/dev/spaCy/spacy/language.py", line 768, in add_pipe
    pipe_component = self.create_pipe(
  File "/home/user/dev/spaCy/spacy/language.py", line 659, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "/home/user/anaconda3/envs/package/lib/python3.8/site-packages/thinc/config.py", line 721, in resolve
    resolved, _ = cls._make(
  File "/home/user/anaconda3/envs/package/lib/python3.8/site-packages/thinc/config.py", line 770, in _make
    filled, _, resolved = cls._fill(
  File "/home/user/anaconda3/envs/package/lib/python3.8/site-packages/thinc/config.py", line 825, in _fill
    filled[key], validation[v_key], final[key] = cls._fill(
  File "/home/user/anaconda3/envs/package/lib/python3.8/site-packages/thinc/config.py", line 896, in _fill
    result = schema.parse_obj(validation)
  File "pydantic/main.py", line 520, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 360, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 960, in pydantic.main.validate_model
pydantic.errors.ConfigError: field "nlp" not yet prepared so type is still a ForwardRef, you might need to call ArgModel.update_forward_refs().

```

</details>

## Info about spaCy

- **spaCy version:** 3.0.0rc3
- **Platform:** Linux-4.15.0-128-generic-x86_64-with-glibc2.10
- **Python version:** 3.8.6
- **Pipelines:** en_core_web_trf (3.0.0a0)

I was previously able to get around this issue by running the commands listed in [this](https://github.com/explosion/spaCy/issues/5932) issue but they don't seem to be helping this time. Other models created with command line init are loading ok.

**Comment by adrianeboyd** [comment]
Due to config changes, the `3.0.0a0` models published for rc2 won't be compatible with rc3, so you'll have to update `spacy-nightly` and your models at the same time. We'll publish `3.0.0a1` models at the same time as the rc3 release.
