### ISSUE TITLE
TypeError: <lambda>() takes 0 positional arguments but 1 was given when loading a model after creating factories

### ISSUE THREAD

**Issue by arthurthlee** [explosion/spaCy#6787]
Hello, I retrained a SciSpacy model (en_core_sci_lg) and I want to load it from disk and run predictions. However, after I create the custom factory necessary for the model (such as "ent_linker"), when I call load_model_from_path, I get an error saying 
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/appuser/src/prediction/prediction_session.py", line 45, in <module>
    session.run()
  File "/home/appuser/src/prediction/prediction_session.py", line 21, in run
    self.predictor = self.create_predictor()
  File "/home/appuser/src/prediction/prediction_session.py", line 34, in create_predictor
    return Predictor(self.args)
  File "/home/appuser/src/prediction/predictor.py", line 85, in __init__
    self.base_model = load_model_from_path(config["base_model_path"])
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 220, in load_model_from_path
    component = nlp.create_pipe(factory, config=config)
  File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 312, in create_pipe
    return factory(self, **config)
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

The code I have for setting the factory and loading the model is here:
```        
def __init__(self, args: PredictorArgs = None, config=None):
        self.args = args
        if self.args is None:
            self.args = PredictorArgs()

        if config is None:
            config = load_json_from_disk(self.args.predict_config)
        self.config = config
        Language.factories["ent_linker"] = lambda **kwargs: EntityLinker(**kwargs)
        self.base_model = load_model_from_path(config["base_model_path"])
```

The meta.json file for my retrained model is below. I've checked the source code for both SciSpacy's EntityLinker class (https://github.com/allenai/scispacy/blob/ac54389574a6c32e0ffa1dcfb8a03ea00d429e1e/scispacy/linking.py), and the load_model_from_path function in Spacy's language.py class, but I can't figure out why it's throwing this error. What am I doing wrong? Thanks

```{
  "lang":"en",
  "name":"core_sci_lg",
  "version":"0.2.5",
  "spacy_version":">=2.3.0",
  "description":"Spacy Models for Biomedical Text.",
  "author":"Allen Institute for Artificial Intelligence",
  "email":"ai2-info@allenai.org",
  "url":"https://allenai.github.io/SciSpaCy/",
  "license":"CC BY-SA 3.0",
  "vectors":{
    "width":200,
    "vectors":600000,
    "keys":667864,
    "name":"en_core_sci_lg_vectors"
  },
  "pipeline":[
    "tagger",
    "parser",
    "ner",
    "ent_linker"
  ],
  "factories":{
    "tagger":"tagger",
    "parser":"parser",
    "ner":"ner",
    "ent_linker":"ent_linker"
  },
  "labels":{
    "tagger":[
      "$",
      "''",
      ",",
      "-LRB-",
      "-RRB-",
      ".",
      ":",
      "ADD",
      "AFX",
      "CC",
      "CD",
      "DT",
      "EX",
      "FW",
      "HYPH",
      "IN",
      "JJ",
      "JJR",
      "JJS",
      "LS",
      "MD",
      "NFP",
      "NN",
      "NNP",
      "NNPS",
      "NNS",
      "PDT",
      "POS",
      "PRP",
      "PRP$",
      "RB",
      "RBR",
      "RBS",
      "RP",
      "SYM",
      "TO",
      "UH",
      "VB",
      "VBD",
      "VBG",
      "VBN",
      "VBP",
      "VBZ",
      "WDT",
      "WP",
      "WP$",
      "WRB",
      "XX",
      "_SP",
      "``"
    ],
    "parser":[
      "ROOT",
      "acl",
      "acl:relcl",
      "acomp",
      "advcl",
      "advmod",
      "agent",
      "amod",
      "appos",
      "attr",
      "aux",
      "auxpass",
      "case",
      "cc",
      "cc:preconj",
      "ccomp",
      "compound",
      "conj",
      "cop",
      "csubj",
      "csubjpass",
      "dative",
      "dep",
      "det",
      "det:predet",
      "dobj",
      "expl",
      "intj",
      "mark",
      "meta",
      "mwe",
      "neg",
      "nmod",
      "nmod:npmod",
      "nmod:poss",
      "npadvmod",
      "nsubj",
      "nsubjpass",
      "nummod",
      "oprd",
      "parataxis",
      "pcomp",
      "pobj",
      "poss",
      "preconj",
      "predet",
      "prep",
      "prt",
      "punct",
      "quantmod",
      "relcl",
      "xcomp"
    ],
    "ner":[
      "ENTITY"
    ]
  },
  "sources":[
    "OntoNotes 5",
    "Common Crawl",
    "GENIA 1.0"
  ],
  "speed":{
    "gpu":null,
    "nwords":35639,
    "cpu":9196.7511461515
  },
  "spacy_git_version":"1d4b1dea2"
}


## Your Environment

Operating System: Mac OS Catalina 10.15.3
Python Version Used: 3.7.4
spaCy Version Used: 2.3.2
Environment Information: Darwin-19.3.0-x86_64-i386-64bit

**Comment by arthurthlee** [comment]
Fixed it by changing 
```Language.factories["ent_linker"] = lambda **kwargs: EntityLinker(**kwargs)```
to 
```Language.factories["ent_linker"] = lambda _, **kwargs: EntityLinker(**kwargs)```
