### ISSUE TITLE
KeyError("[E900] Could not run the full pipeline for evaluation in rc4 (not in rc3)

### ISSUE THREAD

**Issue by ttasovac** [explosion/spaCy#6803]
After upgrading to rc4, our experimental pipeline for training our own Serbian model started aborting with this error message:

```
⚠ Aborting and saving the final best model. Encountered exception:
KeyError("[E900] Could not run the full pipeline for evaluation. If you
specified frozen components, make sure they were already initialized and
trained. Full pipeline: ['lemmatizer', 'tok2vec', 'tagger', 'parser']")

```

I will attach a full error stack at the end of this issue.

Our base config doesn't specify any frozen components:

```
[paths]
train = "srp_training_data/srp_set-ud-train.spacy"
dev = "srp_training_data/srp_set-ud-dev.spacy"

[system]
gpu_allocator = null

[nlp]
lang = "srp"
pipeline = ["tok2vec","tagger","parser","lemmatizer"]
tokenizer = {"@tokenizers": "spacy.Tokenizer.v1"}
batch_size = 1000

[components]

[components.tok2vec]
factory = "tok2vec"

[components.tok2vec.model]
@architectures = "spacy.Tok2Vec.v2"

[components.tok2vec.model.embed]
@architectures = "spacy.MultiHashEmbed.v1"
width = ${components.tok2vec.model.encode.width}
attrs = ["ORTH", "SHAPE"]
rows = [5000, 2500]
include_static_vectors = false

[components.tok2vec.model.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 96
depth = 4
window_size = 1
maxout_pieces = 3

[components.lemmatizer]
factory = "srp_lemmatizer"

# There are no recommended transformer weights available for language 'sr'
# yet, so the pipeline described here is not transformer-based.

[components.tagger]
factory = "tagger"

[components.tagger.model]
@architectures = "spacy.Tagger.v1"
nO = null

[components.parser]
factory = "parser"

[components.parser.model]
@architectures = "spacy.TransitionBasedParser.v1"
tok2vec=${components.tok2vec.model}
state_type = "parser"
extra_state_tokens = false
hidden_width = 128
maxout_pieces = 3
use_upper = true
nO = null

[corpora]

[corpora.train]
@readers = "spacy.Corpus.v1"
path = "${paths.train}"
#max_length = 2000
max_length = 500
#max_steps = 20000
# lowered this to speed up while testing
max_steps = 600

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0

[training]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"

[training.optimizer]
@optimizers = "Adam.v1"

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001

[initialize]
```

We train with:

```
  python3 -m spacy init fill-config base_config.cfg config.cfg
  python3 -m spacy train config.cfg --output models/srp
```

## Info about spaCy

- **spaCy version:** 3.0.0rc4
- **Platform:** macOS-11.1-x86_64-i386-64bit
- **Python version:** 3.8.7

I am _not_ getting this error in rc3. I suppose this is somewhat mystifying considering that rc4 was a tiny update in toc2vec only.

## Full error

```
(env) ⋊> ~/D/B/spacy-serbian-pipeline on binder-fish ⨯ python3 -m spacy train config.cfg --output models/srp
ℹ Using CPU

=========================== Initializing pipeline ===========================
Set up nlp object from config
Pipeline: ['lemmatizer', 'tok2vec', 'tagger', 'parser']
Created vocabulary
Finished initializing nlp object
Initialized pipeline components: ['lemmatizer', 'tok2vec', 'tagger', 'parser']
✔ Initialized pipeline

============================= Training pipeline =============================
ℹ Pipeline: ['lemmatizer', 'tok2vec', 'tagger', 'parser']
ℹ Initial learn rate: 0.001
E    #       LOSS TOK2VEC  LOSS TAGGER  LOSS PARSER  LEMMA_ACC  TAG_ACC  DEP_UAS  DEP_LAS  SENTS_F  SCORE
---  ------  ------------  -----------  -----------  ---------  -------  -------  -------  -------  ------
⚠ Aborting and saving the final best model. Encountered exception:
KeyError("[E900] Could not run the full pipeline for evaluation. If you
specified frozen components, make sure they were already initialized and
trained. Full pipeline: ['lemmatizer', 'tok2vec', 'tagger', 'parser']")
Traceback (most recent call last):
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/training/loop.py", line 261, in evaluate
    scores = nlp.evaluate(dev_corpus(nlp))
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/language.py", line 1319, in evaluate
    for doc, eg in zip(
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/util.py", line 1433, in _pipe
    doc = proc(doc, **kwargs)
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/srp/__init__.py", line 37, in __call__
    lemma = lookup.get(t.text, None)
  File "spacy/tokens/token.pyx", line 263, in spacy.tokens.token.Token.text.__get__
  File "spacy/tokens/token.pyx", line 806, in spacy.tokens.token.Token.orth_.__get__
  File "spacy/strings.pyx", line 132, in spacy.strings.StringStore.__getitem__
KeyError: "[E018] Can't retrieve string for hash '8737485628806624168'. This usually refers to an issue with the `Vocab` or `StringStore`."

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/cli/_util.py", line 65, in setup_cli
    command(prog_name=COMMAND)
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/cli/train.py", line 59, in train_cli
    train(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/training/loop.py", line 113, in train
    raise e
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/training/loop.py", line 98, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/training/loop.py", line 210, in train_while_improving
    score, other_scores = evaluate()
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/env/lib/python3.8/site-packages/spacy/training/loop.py", line 263, in evaluate
    raise KeyError(Errors.E900.format(pipeline=nlp.pipe_names)) from e
KeyError: "[E900] Could not run the full pipeline for evaluation. If you specified frozen components, make sure they were already initialized and trained. Full pipeline: ['lemmatizer', 'tok2vec', 'tagger', 'parser']"
```

I'm not sure how to proceed.

**Comment by svlandeg** [comment]
Thanks for the report!

It looks like the short error message is misleading here. We catch a `KeyError` which usually involves missing/frozen components in the pipeline, but this time there's actually a problem with the vocab, as seen in your stacktrace:
```
  File "/Users/ttasovac/Development/BCDH/spacy-serbian-pipeline/srp/__init__.py", line 37, in __call__
    lemma = lookup.get(t.text, None)
  File "spacy/tokens/token.pyx", line 263, in spacy.tokens.token.Token.text.__get__
  File "spacy/tokens/token.pyx", line 806, in spacy.tokens.token.Token.orth_.__get__
  File "spacy/strings.pyx", line 132, in spacy.strings.StringStore.__getitem__
KeyError: "[E018] Can't retrieve string for hash '8737485628806624168'. This usually refers to an issue with the `Vocab` or `StringStore`."
```
By the way - there are a few more differences between rc3 and rc4 than just the tok2vec change, cf https://github.com/explosion/spaCy/compare/v3.0.0rc3...v3.0.0rc4

Anyway, we've internally stumbled upon a possibly related problem with rc4, and are [looking into it](https://github.com/explosion/spaCy/pull/6804). So for now I'd advice to roll back to rc3.

**Comment by adrianeboyd** [comment]
My other question looking at this: what is going on with the lemmatizer being reordered before the other components in the pipeline? The order in the error message vs. the config doesn't make sense?

**Comment by honnibal** [comment]
Just yanked rc4, as it's pretty broken. Thanks for the report!

**Comment by ttasovac** [comment]
> My other question looking at this: what is going on with the lemmatizer being reordered before the other components in the pipeline? The order in the error message vs. the config doesn't make sense?

Oops, sorry, that was my bad —  I kept working on things after downgrading to rc3 and I put the lemmatizer after the tagger and parser so that I can use the predicted POS as a consideration in lemma lookups... in some languages, like Serbian, you can have tokens that on the surface level seem indistinguishable but are actually have different POSes and different lemmas... so it's helpful to use the POS value when performing lookups...
