### ISSUE TITLE
Problem with TypeError

### ISSUE THREAD

**Issue by cumironin** [explosion/spaCy#6821]
i had copy from here : 

https://github.com/lukigarazus/automatic-paraphrase/blob/master/automatic_paraphrase.py

all requirement has been installed.

```
import spacy

test_cases = [
    "This tree looks beautiful!",
    "I am very tired.",
    "You should buy a new shirt.",
    "Nancy ate 20 hot dogs yesterday.",
]

handled_poss = ["NOUN", "ADJ", 'ADV']

spacy.prefer_gpu()
nlp = spacy.load("en_core_web_lg")

def get_lemma_from_lexeme(lexeme):
    return nlp(lexeme.orth_)[0].lemma

def avoid_token_plurals_in_lexemes(lexemes, token):
    return filter( lambda x: get_lemma_from_lexeme(x) != token.lemma, lexemes )

def filter_lexemes_by_similarity_to_token(lexemes, token, treshold):
    return filter( lambda x: x.similarity(token) > treshold, lexemes )

def same_cluster(word):
    queries = [w for w in word.vocab if w.is_lower == word.is_lower and w.prob >= -15]
    return queries

def most_similar(word):
    cluster = same_cluster(word)
    by_similarity = sorted(cluster, key=lambda w: word.similarity(w), reverse=True)
    return [w.orth_ for w in avoid_token_plurals_in_lexemes(filter_lexemes_by_similarity_to_token(by_similarity[:10], word, 0.5), word)]

def get_synonim(token):
    if token.pos_ in handled_poss:
        synonim = next((x for x in most_similar(token) if x != token.orth_), False)
        synonim_doc = nlp(synonim) # Avoid plurals
        synonim_token = synonim_doc[0]
        if synonim and synonim_token.lemma != token.lemma:
            return synonim
    return token.orth_ # If nothing found return the same token

def get_paraphrase(sentence):
    doc = nlp(sentence)
    para = ' '.join(map(get_synonim, doc))
    para_doc = nlp(para)
    # print("Paraphrase similarity by document:", para_doc.similarity(doc))
    return para


while True:
    test_results = []

    for test in test_cases:
        test_results.append([test, get_paraphrase(test)])

    print("Test cases")
    for result in test_results:
        print("Case: ", result[0])
        print("Result: ", result[1])
    
    sent = input('Give me a sentence to paraphrase:   ')
    print(get_paraphrase(sent))

```

no problem with pylint when i copy to visual studio code, but when i run this problems raise : 

`TypeError: object of type 'bool' has no len()`

```
Traceback (most recent call last):
  File "/Users/user/Documents/2_AGC/PYTHON/paraphrase/automatic_paraphrase.py", line 62, in <module>
    para = get_paraphrase(coba)
  File "/Users/user/Documents/2_AGC/PYTHON/paraphrase/automatic_paraphrase.py", line 56, in get_paraphrase
    para = ' '.join(map(get_synonim, doc))
  File "/Users/user/Documents/2_AGC/PYTHON/paraphrase/automatic_paraphrase.py", line 47, in get_synonim
    synonim_doc = nlp(synonim)  # Avoid plurals
  File "/Users/user/Documents/2_AGC/PYTHON/paraphrase/env/lib/python3.9/site-packages/spacy/language.py", line 437, in __call__
    doc = self.make_doc(text)
  File "/Users/user/Documents/2_AGC/PYTHON/paraphrase/env/lib/python3.9/site-packages/spacy/language.py", line 463, in make_doc
    if len(text) > self.max_length:
TypeError: object of type 'bool' has no len()
```

any clue about this ?

**Comment by adrianeboyd** [comment]
Hi, we don't really have the resources to help debug code from 3rd party scripts or packages that use spacy. You could try contacting the original author, but it's also possible the project is no longer maintained.

Since we're trying to keep the issue tracker focused on bug reports, we'll convert this to a post on our new GitHub Discussions board, which is a good place for usage questions and help with code.
