### ISSUE TITLE
Training NER causes an proper sample data bug in spaCy 3.0

### ISSUE THREAD

**Issue by nomisjon** [explosion/spaCy#6932]
## How to reproduce the behaviour

I'm trying to train my model with spaCy's new version. Therefore, I have converted all files to the new .spacy format. Debug Data work, however, train causes an  error:

`AssertionError: [E923] It looks like there is no proper sample data to initialize the Model of component 'tok2vec'. This is likely a bug in spaCy, so feel free to open an issue: https://github.com/explosion/spaCy/issues`

I have setup a new venv and installed spaCy's new version.
When I delete tok2vec in the config file it raises the same error but with ner.

Here's the entire error:
```
=========================== Initializing pipeline ===========================
Set up nlp object from config
Pipeline: ['tok2vec', 'ner']
Created vocabulary
Added vectors: en_core_web_lg
Finished initializing nlp object
C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\training\corpus.py:76: UserWarning: [W090] Could not locate any .spacy files in path 'train'.
  warnings.warn(Warnings.W090.format(path=orig_path, format=file_type))
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\cli\_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\cli\train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\training\initialize.py", line 70, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\language.py", line 1246, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\pipeline\tok2vec.py", line 214, in initialize
    assert doc_sample, Errors.E923.format(name=self.name)
AssertionError: [E923] It looks like there is no proper sample data to initialize the Model of component 'tok2vec'. This is likely a bug in spaCy, so feel free to open an issue: https://github.com/explosion/spaCy/issues
```

I'm using the following config:

```
[paths]
train = "training"
dev = "validation"
vectors = null
init_tok2vec = null

[system]
gpu_allocator = null
seed = 0

[nlp]
lang = "en"
pipeline = ["tok2vec","ner"]
batch_size = 1000
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = true
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}
upstream = "*"

[components.tok2vec]
factory = "tok2vec"

[components.tok2vec.model]
@architectures = "spacy.Tok2Vec.v2"

[components.tok2vec.model.embed]
@architectures = "spacy.MultiHashEmbed.v1"
width = ${components.tok2vec.model.encode.width}
attrs = ["NORM","PREFIX","SUFFIX","SHAPE"]
rows = [5000,2500,2500,2500]
include_static_vectors = false

[components.tok2vec.model.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 256
depth = 8
window_size = 1
maxout_pieces = 3

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 2000
gold_preproc = false
limit = 0
augmenter = null

[training]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]
ents_per_type = null
ents_f = 1.0
ents_p = 0.0
ents_r = 0.0

[pretraining]

[initialize]
vectors = "en_core_web_lg"
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```
``

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.8.3
* spaCy Version Used: 3
* Environment Information: python .venv

**Comment by nomisjon** [comment]
Hi @adrianeboyd and thank you very much for answering,
I have downgraded to spaCy 2.3.5, then upgraded spaCy 3 and downloaded en_core_web_lg again.
Not the problem doesn't occur anymore.

**Comment by christopherorea** [comment]
I would like to reopen the threat.

I'm trying to train a custom model with spaCy 3. I just did all the before configuration and got nothing.
I will add my setup.

-> English model from Universal dependencies English conllu train and dev.  [Here you can find the files](https://github.com/UniversalDependencies/UD_English-GUM/tree/master)
-> Config.cfg file from quickstart spaCy [Taken from here](https://spacy.io/usage/training#quickstart )


now in my file I ended doing:
-> `pip install spacy -U`
-> `python -m spacy download en_core_web_lg`

As soon all the config just finished I did:
-> `python -m spacy train config.cfg --paths.train en_gum-ud-train.conllu --paths.dev en_gum-ud-test.conllu`

Which led me with these error message:
```
ℹ Using CPU

=========================== Initializing pipeline ===========================
Set up nlp object from config
Pipeline: ['tok2vec', 'tagger', 'parser']
Created vocabulary
Added vectors: en_core_web_lg
Finished initializing nlp object
/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/training/corpus.py:76: UserWarning: [W090] Could not locate any .spacy files in path 'en_gum-ud-train.conllu'.
  warnings.warn(Warnings.W090.format(path=orig_path, format=file_type))
Traceback (most recent call last):
  File "/Users/MrOrea/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/MrOrea/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/cli/_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/training/initialize.py", line 70, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/language.py", line 1246, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/pipeline/tok2vec.py", line 214, in initialize
    assert doc_sample, Errors.E923.format(name=self.name)
AssertionError: [E923] It looks like there is no proper sample data to initialize the Model of component 'tok2vec'. This is likely a bug in spaCy, so feel free to open an issue: https://github.com/explosion/spaCy/issues
```

**Comment by nomisjon** [comment]
Hi @christopherorea ,

I'm not an expert so I'll just describe how I fixed the problem.

Your using
`python -m spacy train config.cfg --paths.train en_gum-ud-train.conllu --paths.dev en_gum-ud-test.conllu`

for training. Just use
`python -m spacy train config.cfg`

and insert the training and deviation path in the config file:
```
[paths]
train = "training/"
dev = "validation/"
vectors = null
init_tok2vec = null
```
As my data neither has tok2vec information, I have deleted in the nlp section where the pipelines for training is specified and I've deleted all tok2vec sections bellow. 

With these config I was able to train NER.

**Comment by adrianeboyd** [comment]
@christopherorea: This warning at the top is the more relevant one:

```none
UserWarning: [W090] Could not locate any .spacy files in path 'en_gum-ud-train.conllu'.
```

`spacy train` looks for files that end in `.spacy` (in `DocBin` format, https://spacy.io/api/docbin/), not `.conllu` files. You have to convert `.conllu` files with `spacy convert`, see: https://spacy.io/api/cli#convert
