### ISSUE TITLE
TextCatEnsemble not working with TransformerListener

### ISSUE THREAD

**Issue by reneoctavio** [explosion/spaCy#6946]
## How to reproduce the behavior
Hi, I came across another issue. When using TransformerListener with TextCatEnsemble occurs the following error:
```
=========================== Initializing pipeline ===========================
Set up nlp object from config
Pipeline: ['transformer', 'textcat']
Created vocabulary
Finished initializing nlp object
Traceback (most recent call last):
  File "/home/reneoctavio/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/reneoctavio/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/reneoctavio/Projects/git/fixes/spaCy/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/reneoctavio/Projects/git/fixes/spaCy/spacy/cli/_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/reneoctavio/Projects/git/fixes/spaCy/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/home/reneoctavio/Projects/git/fixes/spaCy/spacy/training/initialize.py", line 70, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/home/reneoctavio/Projects/git/fixes/spaCy/spacy/language.py", line 1246, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "/home/reneoctavio/Projects/git/fixes/spaCy/spacy/pipeline/textcat_multilabel.py", line 168, in initialize
    self.model.initialize(X=doc_sample, Y=label_sample)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/reneoctavio/Projects/git/fixes/spaCy/spacy/ml/models/textcat.py", line 110, in init_ensemble_textcat
    init_chain(model, X, Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/layers/concatenate.py", line 132, in init
    layer.initialize(X=X, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/layers/residual.py", line 57, in init
    first_layer.initialize(X=X, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/layers/layernorm.py", line 49, in init
    model.set_dim("nI", Y_width)
  File "/home/reneoctavio/.pyenv/versions/spacy/lib/python3.8/site-packages/thinc/model.py", line 188, in set_dim
    raise ValueError(err)
ValueError: Attempt to change dimension 'nI' for model 'layernorm' from 768 to 35
```

This is part of the config file.
```
[nlp]
lang = "en"
pipeline = ["transformer","textcat"]
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
batch_size = 32

[components]

[components.transformer]
factory = "transformer"

[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "roberta-base"
tokenizer_config = {"use_fast": true}

[components.transformer.model.get_spans]
@span_getters = "spacy-transformers.strided_spans.v1"
window = 128
stride = 96

[components.textcat]
factory = "textcat_multilabel"
threshold = 0.5

[components.textcat.model]
@architectures = "spacy.TextCatEnsemble.v2"
nO = null

[components.textcat.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"

[components.textcat.model.linear_model]
@architectures = "spacy.TextCatBOW.v1"
exclusive_classes = false
ngram_size = 1
no_output_layer = false
```

I might have found the problem. The value for `layernorm` `nI` is set, but the `nO` should've been set too.

https://github.com/explosion/spaCy/blob/433835d9b0a5b7b933698dbaf2dcf3a57a566d92/spacy/ml/models/textcat.py#L104-L111

This is what happens: before the layer initializes, it checks if `nO` dim is `None`, if so, it passes `X` and `Y`.
https://github.com/explosion/thinc/blob/3d5ab7420209cf087dd2611dc843a3e06998b75b/thinc/layers/chain.py#L83-L88

When passing both `X` and `Y`, it first sets `nO` and `nI` to `X_width`, then it tries to set both to `Y_width`. This is when the error occurs.
https://github.com/explosion/thinc/blob/3d5ab7420209cf087dd2611dc843a3e06998b75b/thinc/layers/layernorm.py#L43-L51

I tried adding `model.get_ref("norm_layer").set_dim("nO", tok2vec_width)` before `init_chain`; and it worked. 
If I am not missing anything, I can do a PR fixing this.

## Your Environment
- **spaCy version:** 3.0.1
- **Platform:** Linux-5.8.0-41-generic-x86_64-with-glibc2.10
- **Python version:** 3.8.5
- **Pipelines:** en_core_web_trf (3.0.0), pt_core_news_sm (3.0.0), en_core_web_lg (3.0.0), pt_core_news_lg (3.0.0)

**Comment by svlandeg** [comment]
Thanks for the report and the digging!

Thinc attempts to make some clever decisions to support automated shape inference, but it gets quite complex and I'm sure there are small things we can improve still. Your analysis looks correct to me.

The solution you're proposing is a good one to fix the immediate issue. `Layernorm` should have the same `nI` and `nO` (cf https://github.com/explosion/thinc/blob/master/thinc/layers/layernorm.py#L19) and so it makes sense to add that line you propose specifically. A PR would be appreciated!

**Comment by svlandeg** [comment]
That said, I also think that perhaps we should look into some of the code in the `init` function for `LayerNorm`: https://github.com/explosion/thinc/blob/master/thinc/layers/layernorm.py#L40

```
    if X is not None:
        X_width = get_width(X)
        model.set_dim("nI", X_width)
        model.set_dim("nO", X_width)
    if Y is not None:
        Y_width = get_width(Y)
        model.set_dim("nI", Y_width)
        model.set_dim("nO", Y_width)
```
In general we should never get an error that says that you tried changing a dimension. It means that fundamentally we're calling a `set_dim` with a value that's not appropriate. So we probably need to look into this, too.

**Comment by reneoctavio** [comment]
Yes. I noticed that this fix works because we got 'lucky'. First, we `set_dim` in the `init_ensemble_textcat` function (using `tok2vec_width`), then it `set_dim` again when initializing (using `X_width`). An error is not thrown because both are the same. 
https://github.com/explosion/thinc/blob/3d5ab7420209cf087dd2611dc843a3e06998b75b/thinc/model.py#L188

There is also a possibility of adding a third clause here, checking if both `dims` are set, we initialize it without `X` and `Y`.
But I'm not sure this is the optimal way.
```
    for layer in model.layers:
        if layer.has_dim("nO") is None:
            layer.initialize(X=curr_input, Y=Y)
        #
        elif layer.has_dim("nO") and layer.has_dim("nI"):
            layer.initialize()
        #
        else:
            layer.initialize(X=curr_input)
```
https://github.com/explosion/thinc/blob/3d5ab7420209cf087dd2611dc843a3e06998b75b/thinc/layers/chain.py#L83-L88

**Comment by svlandeg** [comment]
I see what you mean, but I don't think that's necessary, because I don't think there's usually any trouble with passing onwards `X`. This piece of code in `chain` is tricky because it tries to use `Y` to set output dimensions on layers that may not necessarily be the last one. And so the `Y` might not actually be applicable to them. It's a little hacky, as the comment suggests, but we haven't found a better way for now to make some other shape inference bits work.

I did add this small PR to Thinc that should help prevent your original issue as well: https://github.com/explosion/thinc/pull/466

**Comment by reneoctavio** [comment]
Fair enough, thanks!
