### ISSUE TITLE
AssertionError: [E923] It looks like there is no proper sample data to initialize the Model of component 'tok2vec'.

### ISSUE THREAD

**Issue by christopherorea** [explosion/spaCy#6954]
I come from [this Issue](https://github.com/explosion/spaCy/issues/6932) but it looks like it's closed. 

I'm trying to train a custom model with spaCy 3. I just did all the before configuration and got nothing.
I will add my setup.

-> English model from Universal dependencies English conllu train and dev.  [Here you can find the files](https://github.com/UniversalDependencies/UD_English-GUM/tree/master)
-> Config.cfg file from quickstart spaCy [Taken from here](https://spacy.io/usage/training#quickstart )

now in my file I ended doing:
-> `pip install spacy -U`
-> `python -m spacy download en_core_web_lg`

As soon all the config just finished I did:
-> `python -m spacy train config.cfg --paths.train en_gum-ud-train.conllu --paths.dev en_gum-ud-test.conllu`

Which led me with these error message:
```
ℹ Using CPU

=========================== Initializing pipeline ===========================
Set up nlp object from config
Pipeline: ['tok2vec', 'tagger', 'parser']
Created vocabulary
Added vectors: en_core_web_lg
Finished initializing nlp object
/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/training/corpus.py:76: UserWarning: [W090] Could not locate any .spacy files in path 'en_gum-ud-train.conllu'.
  warnings.warn(Warnings.W090.format(path=orig_path, format=file_type))
Traceback (most recent call last):
  File "/Users/MrOrea/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/MrOrea/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/cli/_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/training/initialize.py", line 70, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/language.py", line 1246, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "/Users/MrOrea/miniconda3/lib/python3.7/site-packages/spacy/pipeline/tok2vec.py", line 214, in initialize
    assert doc_sample, Errors.E923.format(name=self.name)
AssertionError: [E923] It looks like there is no proper sample data to initialize the Model of component 'tok2vec'. This is likely a bug in spaCy, so feel free to open an issue: https://github.com/explosion/spaCy/issues
```

Any Ideas?

**Comment by ahalterman** [comment]
`spacy train` needs files in the binary spaCy training format, but luckily there are built in converters for conllu formatted text. Here's the documentation: https://spacy.io/api/cli#convert

Once you convert them to `.spacy` files, you can use the `debug data` command to make sure all the data is in the right format.

**Comment by jeromemassot** [comment]
Hi all,

I have got the same issue despite the convert  operation has been correctly done.
I am starting from a Spacy V2 jsonl file obtained from prodigy.
As mentioned in other posts, I have selected the same .spacy file for both train and dev.
But I have the message about the tokenizer.
Thanks for help

Best regards

Jerome
