### ISSUE TITLE
download failed due to ProxyError

### ISSUE THREAD

**Issue by as754770178** [explosion/spaCy#6962]
When I exec `python -m spacy download en`, report error:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    self._tunnel()
  File "/opt/conda/lib/python3.7/http/client.py", line 921, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:
... ...
File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

```

**Comment by as754770178** [comment]
spacy version:
```
python -m spacy info

============================== Info about spaCy ==============================

spaCy version    3.0.1                         
Location         /root/.local/lib/python3.7/site-packages/spacy
Platform         Linux-3.10.0-1062.el7.x86_64-x86_64-with-debian-buster-sid
Python version   3.7.7                         
Pipelines                                      

```

**Comment by svlandeg** [comment]
Hm, I'm not sure what is causing this. Are you perhaps behind a firewall at work, or something such?

To avoid using the `download` command, you can download the model directly by locating the release on the [models](https://spacy.io/models/) documentation page, for instance https://spacy.io/models/en, click on "release details" and copy the link location of the `tar.gz` file. Then do:

```
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz
```
Does that work for you?
