### ISSUE TITLE
Error downloading spacy: wrong architecture

### ISSUE THREAD

**Issue by tanzeelak** [explosion/spaCy#706]
I'm running on a Macbook Air 10.5. I have python 2.7 installed. Trying to use spacy for the first time but looks like there's architecture incompatibility.

$ pip install -U spacy //worked fine
$ python2.7-32 -m spacy.en.download all
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cymem/cymem.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cymem/cymem.so: mach-o, but wrong architecture

Suggestions? Very new to this.

**Comment by honnibal** [comment]
Any particular reason you're executing `python2.7-32`? I'm guessing your `pip` command refers to a different version of Python. (You can think of pip as a shortcut for `python -m pip`. Except, the `python` you're running there is a different version from the one you're later trying to use to run the library. I think. Maybe.)

**Comment by shengc** [comment]
sorry to comment on a closed issue, but I have exactly the same error ...

```
shengc@Shengs-MBP-2: python 564 $ sudo python -m pip install -U virtualenv
The directory '/Users/shengc/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/shengc/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting virtualenv
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 616kB/s
Installing collected packages: virtualenv
Successfully installed virtualenv-15.1.0
shengc@Shengs-MBP-2: python 565 $ virtualenv .env
New python executable in /Users/shengc/Documents/workspace/python/.env/bin/python
Installing setuptools, pip, wheel...done.
shengc@Shengs-MBP-2: python 566 $ source .env/bin/activate
(.env) shengc@Shengs-MBP-2: python 567 $ pip install -U spacy
Collecting spacy
Collecting plac<1.0.0,>=0.9.6 (from spacy)
  Using cached plac-0.9.6-py2.py3-none-any.whl
Collecting requests<3.0.0,>=2.13.0 (from spacy)
  Using cached requests-2.18.2-py2.py3-none-any.whl
Collecting six (from spacy)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pathlib (from spacy)
Collecting ftfy<5.0.0,>=4.4.2 (from spacy)
Collecting preshed<2.0.0,>=1.0.0 (from spacy)
Collecting cymem<1.32,>=1.30 (from spacy)
  Using cached cymem-1.31.2-cp27-cp27m-macosx_10_6_intel.whl
Collecting thinc<6.6.0,>=6.5.0 (from spacy)
Collecting numpy>=1.7 (from spacy)
  Using cached numpy-1.13.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting dill<0.3,>=0.2 (from spacy)
Collecting ujson>=1.35 (from spacy)
Collecting regex<2017.12.1,>=2017.4.1 (from spacy)
Requirement already up-to-date: pip<10.0.0,>=9.0.0 in ./.env/lib/python2.7/site-packages (from spacy)
Collecting murmurhash<0.27,>=0.26 (from spacy)
  Using cached murmurhash-0.26.4-cp27-cp27m-macosx_10_6_intel.whl
Collecting idna<2.6,>=2.5 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting html5lib (from ftfy<5.0.0,>=4.4.2->spacy)
  Using cached html5lib-0.999999999-py2.py3-none-any.whl
Collecting wcwidth (from ftfy<5.0.0,>=4.4.2->spacy)
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting cytoolz<0.9,>=0.8 (from thinc<6.6.0,>=6.5.0->spacy)
Collecting termcolor (from thinc<6.6.0,>=6.5.0->spacy)
Collecting wrapt (from thinc<6.6.0,>=6.5.0->spacy)
Collecting tqdm<5.0.0,>=4.10.0 (from thinc<6.6.0,>=6.5.0->spacy)
  Using cached tqdm-4.15.0-py2.py3-none-any.whl
Requirement already up-to-date: setuptools>=18.5 in ./.env/lib/python2.7/site-packages (from html5lib->ftfy<5.0.0,>=4.4.2->spacy)
Collecting webencodings (from html5lib->ftfy<5.0.0,>=4.4.2->spacy)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl
Collecting toolz>=0.8.0 (from cytoolz<0.9,>=0.8->thinc<6.6.0,>=6.5.0->spacy)
Installing collected packages: plac, idna, chardet, certifi, urllib3, requests, six, pathlib, webencodings, html5lib, wcwidth, ftfy, cymem, preshed, toolz, cytoolz, termcolor, numpy, wrapt, dill, murmurhash, tqdm, thinc, ujson, regex, spacy
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 cymem-1.31.2 cytoolz-0.8.2 dill-0.2.7.1 ftfy-4.4.3 html5lib-0.999999999 idna-2.5 murmurhash-0.26.4 numpy-1.13.1 pathlib-1.0.1 plac-0.9.6 preshed-1.0.0 regex-2017.7.28 requests-2.18.2 six-1.10.0 spacy-1.9.0 termcolor-1.1.0 thinc-6.5.2 toolz-0.8.2 tqdm-4.15.0 ujson-1.35 urllib3-1.22 wcwidth-0.1.7 webencodings-0.5.1 wrapt-1.10.10
(.env) shengc@Shengs-MBP-2: python 568 $ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shengc/Documents/workspace/python/.env/lib/python2.7/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/Users/shengc/Documents/workspace/python/.env/lib/python2.7/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/Users/shengc/Documents/workspace/python/.env/lib/python2.7/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/Users/shengc/Documents/workspace/python/.env/lib/python2.7/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/Users/shengc/Documents/workspace/python/.env/lib/python2.7/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ImportError: dlopen(/Users/shengc/Documents/workspace/python/.env/lib/python2.7/site-packages/spacy/gold.so, 2): no suitable image found.  Did find:
	/Users/shengc/Documents/workspace/python/.env/lib/python2.7/site-packages/spacy/gold.so: mach-o, but wrong architecture
```
