### ISSUE TITLE
Custom pipeline component initialization fails with "KeyError: 'python_code'"

### ISSUE THREAD

**Issue by aajanki** [explosion/spaCy#7224]
When I try to train a pipeline with a custom component defined in an external Python file with `python -m spacy train test.cfg --code mycode.py`, the training fails with `KeyError: 'python_code'` (the full stack trace below). The same exception is raised also on `spacy debug data test.cfg --code-path mycode.py`.

More specifically, the failure occurs only if the `initialize()` function of the custom component has additional parameters besides `get_examples` and `nlp`. In the code below, `this_parameter_breaks_spacy` is the problematic parameter. If it is removed, training works as expected. The name or type of the parameter does seem to have an effect.

[Full config file for reproduction](https://gist.github.com/aajanki/3f0ac171caadcdc3b71cdcba5bc8113a)
A simple one document corpus I used for testing: [data/sample.spacy](https://paste.c-net.org/ResultedHomer) (I'm quite sure that this happens with any corpus.)

The relevant part of the config is below:
```
[nlp]
pipeline = ["lemmatizer"]

[components.lemmatizer]
factory = "my_lemmatizer"

[initialize.components]

[initialize.components.lemmatizer]
```

I have defined a custom lemmatizer in my_code.py as follows:
```python
from spacy.language import Language
from spacy.lookups import Lookups
from spacy.pipeline.lemmatizer import Lemmatizer
from spacy.training import Example
from thinc.api import Model
from typing import Callable, Iterable, Optional

class MyLemmatizer(Lemmatizer):
    def initialize(
        self,
        get_examples: Optional[Callable[[], Iterable[Example]]] = None,
        *,
        nlp: Optional[Language] = None,
        this_parameter_breaks_spacy: int = 0,
    ):
        lookups = Lookups()
        lookups.add_table("lemma_lookup")
        super().initialize(get_examples, nlp=nlp, lookups=lookups)


@Language.factory(
    "my_lemmatizer",
    assigns=["token.lemma"],
    default_config={"model": None, "mode": "lookup", "overwrite": False},
    default_score_weights={"lemma_acc": 1.0},
)
def make_lemmatizer(
    nlp: Language, model: Optional[Model], name: str, mode: str, overwrite: bool = False
):
    return MyLemmatizer(nlp.vocab, model, name, mode=mode, overwrite=overwrite)
```

Output from my train attempt:
```
$ python -m spacy train test.cfg --code mycode.py           
ℹ Using CPU

=========================== Initializing pipeline ===========================
Set up nlp object from config
Pipeline: ['lemmatizer']
Created vocabulary
Finished initializing nlp object
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/spacy/cli/_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/spacy/training/initialize.py", line 70, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/spacy/language.py", line 1243, in initialize
    p_settings = validate_init_settings(
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/spacy/schemas.py", line 128, in validate_init_settings
    schema = get_arg_model(func, exclude=exclude, name="InitArgModel")
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/spacy/schemas.py", line 100, in get_arg_model
    default_empty = None if is_cython_func(func) else ...
  File "/home/antti/spacy-custom-code/.venv/lib/python3.9/site-packages/spacy/util.py", line 1458, in is_cython_func
    cls_func = vars(sys.modules[func.__module__])[func.__qualname__.split(".")[0]]
KeyError: 'python_code'
```

My guess is that `is_cython_func` doesn't know how to handle registered custom functions. The function registry seems to load custom functions under a fake "pyton_code" module name but `is_cython_func` tries to access "python_code" as if it were a real Python module.

* Operating System: Debian unstable
* Python Version Used: 3.9.1
* spaCy Version Used: 3.0.3

**Comment by adrianeboyd** [comment]
Thanks for the detailed report, that does look like a bug. We'll look into it!
