### ISSUE TITLE
error when loading config for pretraining

### ISSUE THREAD

**Issue by moyid** [explosion/spaCy#7289]
I'm working on pretraining a tok2vec model in spacy v3, and I set up my config file with `python -m spacy init fill-config configs/config.cfg configs/config_pretrain.cfg --pretraining` 

When I try to load the model from config, I get this error: 
script run:
```
config_path = Path('./configs/config_pretrain.cfg')
config = util.load_config(config_path, interpolate = False)
nlp = init_nlp(config, use_gpu=0)
```
error:

```
Config validation error
pretraining -> optimizer      instance of Optimizer expected
pretraining -> objective      Promise(registry='architectures', name='spacy.PretrainCharacters.v1', args=[], kwargs={'maxout_pieces': 3, 'hidden_size': 300, 'n_characters': 4}) is not callable
pretraining -> batcher        extra fields not permitted    
pretraining -> component      extra fields not permitted    
pretraining -> corpus         extra fields not permitted    
pretraining -> dropout        extra fields not permitted    
pretraining -> layer          extra fields not permitted    
pretraining -> max_epochs     extra fields not permitted    
pretraining -> n_save_every   extra fields not permitted    
pretraining -> objective      extra fields not permitted    
pretraining -> optimizer      extra fields not permitted    
```

**Comment by polm** [comment]
I guess this is related to #7285. Looks like something is weird with your config, can you run this on it and check the output?

    python -m spacy debug data ./configs/config_pretrain.cfg

It would also help if you could post your training config.

**Comment by moyid** [comment]
`python -m spacy debug data ./configs/config_pretrain.cfg` output:

```
============================ Data file validation ============================
✔ Corpus is loadable
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jupyter/spaCy/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/jupyter/spaCy/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/home/jupyter/NEL_pipeline/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jupyter/NEL_pipeline/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jupyter/NEL_pipeline/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jupyter/NEL_pipeline/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jupyter/NEL_pipeline/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jupyter/NEL_pipeline/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jupyter/NEL_pipeline/env/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/jupyter/spaCy/spacy/cli/debug_data.py", line 69, in debug_data_cli
    silent=False,
  File "/home/jupyter/spaCy/spacy/cli/debug_data.py", line 106, in debug_data
    nlp.initialize(lambda: train_dataset)
  File "/home/jupyter/spaCy/spacy/language.py", line 1228, in initialize
    init_tok2vec(self, P, I)
  File "/home/jupyter/spaCy/spacy/training/initialize.py", line 150, in init_tok2vec
    if P["objective"].get("type") == "vectors" and not I["vectors"]:
AttributeError: 'function' object has no attribute 'get'

```

my whole config:

```
[paths]
train = "corpus/training.spacy"
dev = "corpus/eval.spacy"
init_tok2vec = "assets/tok2vec_cd8_model289.bin"
vectors = "en_core_web_lg"
raw_text = "assets/data.jsonl"

[system]
gpu_allocator = "pytorch"
seed = 0

[nlp]
lang = "en"
pipeline = ["tok2vec","ner"]
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}
before_creation = null
after_creation = null
after_pipeline_creation = null
disabled = []
batch_size = 1000

[components]

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v1"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = true
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}
upstream = "*"

[components.tok2vec]
factory = "tok2vec"

[components.tok2vec.model]
@architectures = "spacy.Tok2Vec.v1"

[components.tok2vec.model.embed]
@architectures = "spacy.MultiHashEmbed.v1"
width = ${components.tok2vec.model.encode.width}
rows = [2000,1000,1000,1000]
attrs = ["NORM","PREFIX","SUFFIX","SHAPE"]
include_static_vectors = false

[components.tok2vec.model.encode]
@architectures = "spacy.MaxoutWindowEncoder.v1"
width = 300
depth = 4
window_size = 1
maxout_pieces = 3

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.pretrain]
@readers = "spacy.JsonlCorpus.v1"
path = ${paths.raw_text}
min_length = 5
max_length = 500
limit = 0

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 2000
gold_preproc = false
limit = 0
augmenter = null

[training]
train_corpus = "corpora.train"
dev_corpus = "corpora.dev"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001

[training.optimizer.learn_rate]
@schedules = "warmup_linear.v1"
warmup_steps = 250
total_steps = 20000
initial_rate = 0.00005

[training.score_weights]
ents_per_type = null
ents_f = 1.0
ents_p = 0.0
ents_r = 0.0

[pretraining]
max_epochs = 1000
dropout = 0.2
n_save_every = null
component = "tok2vec"
layer = ""
corpus = "corpora.pretrain"

[pretraining.batcher]
@batchers = "spacy.batch_by_words.v1"
size = 3000
discard_oversize = false
tolerance = 0.2
get_length = null

[pretraining.objective]
@architectures = "spacy.PretrainCharacters.v1"
maxout_pieces = 3
hidden_size = 300
n_characters = 4

[pretraining.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = true
eps = 0.00000001
learn_rate = 0.001

[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```

**Comment by moyid** [comment]
following up on this, please help :)

**Comment by polm** [comment]
Thanks for the detailed config, I was able to reproduce this. Changing `init_tok2vec` to `null` in `[paths]` allowed training to start. 

This is the line in your config:

    init_tok2vec = "assets/tok2vec_cd8_model289.bin" 

How did you initialize that? 

This also might be related to https://github.com/explosion/spaCy/issues/6952.

**Comment by svlandeg** [comment]
Hi @moyid, it turns out that the spaCy v3 pretraining functionality was a bit broken. The config you used here is probably fine, but there was an issue with schema validation for the `pretraining` part.  PR #7342 should fix this.

**Comment by moyid** [comment]
Thank you for the responses! @polm You're right that I can run it with init_tok2vec to null, I can pretrain. I was hoping to keep pretraining from an already pretrained model (the one that spacy had pretrained from reddit)

 @svlandeg I have tried pretraining with the PR you made, but I get this new error: `ValueError: Trying to read a Model that was created with an incompatible version of Thinc` -- probably an issue with the tok2vec model I'm using.

**Comment by moyid** [comment]
It is actually the model pretrained on reddit you guys did which can be found here: https://github.com/explosion/projects/tree/master/ner-food-ingredients

I figured that I would add my own pretraining on top of it instead of starting fresh. If it is too old, then I guess that won't work and I'll just start fresh, which is fine!

As a follow up question, I left my pretraining to train overnight on a Volta GPU, and it is still not finished yet. I thought that it would only take 4-6 hours. Will it just stop automatically when it is done? Is there anyway to tell its progress? Thank you!

**Comment by moyid** [comment]
Hi, my pretraining is still going, and it has been 3 days. My configs were filled with fill-config, and it looks like it has max_epochs = 1000 under [pretraining]. 

the outputs on my screen look something like this:

```
349   11927597311   10137550627    10071   30724
349   11927609276   10137559619     8992   35578
349   11927621218   10137568724     9105   35331
349   11927633138   10137581074    12350   34991
349   11927645058   10137592086    11011   33242
349   11927656979   10137602828    10742   28904
349   11927668923   10137613247    10418   32730
349   11927680859   10137623685    10438   35425
```

Is the number on the first column the epoch? Do I have to wait for this to go to 1000? Does it always stop at the max epoch, or does it also look for other metrics, such as when validation error starts going up? This is a bit unexpected since I read that the pretraining should take 4-6 hours on a gpu.

**Comment by polm** [comment]
@moyid The number in the first column is epochs, and depending on your settings training might not stop until it reaches 1000. You can read more about when training stops here.

https://github.com/explosion/spaCy/discussions/7465

How long training takes depends on the size of your data and what training you're doing. If you want it to finish sooner, I would set a `patience` score to enable early stopping, and also enable frequent checkpoint saving. You can test checkpoints along the way to see if they're "good enough", and early stopping will end training if your model stops improving.

**Comment by moyid** [comment]
thank you, that helps!
