### ISSUE TITLE
KeyError: 'python_code' when initializing a custom component

### ISSUE THREAD

**Issue by zoebutatwork** [explosion/spaCy#7310]
## How to reproduce the behaviour

I'm trying out [the example for initializing a custom component](https://spacy.io/usage/processing-pipelines#component-data-initialization), using "Option 2: Save data with the pipeline and load it in once on initialization" to load in the initial data. When I go to train it, I'm getting a KeyError: 'python_code'. 

Python code for the custom component "acronyms" :
```python
@Language.factory("acronyms", default_config={"case_sensitive": False})
def create_acronym_component(nlp: Language, name: str, case_sensitive: bool):
    return AcronymComponent(nlp, case_sensitive)

class AcronymComponent:
    def __init__(self, nlp: Language, case_sensitive: bool):
        pass

    def __call__(self, doc: Doc) -> Doc:
        return doc

    def initialize(self, get_examples=None, nlp=None, data={}):
        self.data = data

    def to_disk(self, path, exclude=tuple()):
        srsly.write_json(path / "data.json", self.data)

    def from_disk(self, path, exclude=tuple()):
        self.data = srsly.read_json(path / "data.json")
        return self
```

Relevant model configs:
```yaml
[components]

[components.acronyms]
factory = "acronyms"

[initialize.components]

[initialize.components.acronyms]

# The error happens whether or not this bit is is commented out
# [initialize.components.acronyms.data]
# @readers = "srsly.read_jsonl.v1"
# path = ${paths.acronyms}
```

Train command:
```bash
python -m spacy train configs/config.cfg --code scripts/acronyms.py --output training/ --paths.train corpus/training.spacy --paths.dev corpus/eval.spacy --paths.acronyms assets/acronyms.jsonl
```

Full error: 
```bash
Finished initializing nlp object
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/usr/local/lib/python3.8/site-packages/spacy/cli/_util.py", line 65, in setup_cli
    command(prog_name=COMMAND)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/usr/local/lib/python3.8/site-packages/spacy/training/initialize.py", line 67, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/usr/local/lib/python3.8/site-packages/spacy/language.py", line 1237, in initialize
    p_settings = validate_init_settings(
  File "/usr/local/lib/python3.8/site-packages/spacy/schemas.py", line 128, in validate_init_settings
    schema = get_arg_model(func, exclude=exclude, name="InitArgModel")
  File "/usr/local/lib/python3.8/site-packages/spacy/schemas.py", line 100, in get_arg_model
    default_empty = None if is_cython_func(func) else ...
  File "/usr/local/lib/python3.8/site-packages/spacy/util.py", line 1405, in is_cython_func
    cls_func = vars(sys.modules[func.__module__])[func.__qualname__.split(".")[0]]
KeyError: 'python_code'
```

## Environment

- **spaCy version:** 3.0.0rc5
- **Platform:** Linux-4.19.121-linuxkit-x86_64-with-glibc2.2.5
- **Python version:** 3.8.8

**Comment by svlandeg** [comment]
Hi, thanks for the report!

This looks like the same issue as https://github.com/explosion/spaCy/issues/7224, and I think this should be fixed by the recently merged https://github.com/explosion/spaCy/pull/7237. In that case, the fix should be available in the next release of spaCy (3.0.4 I'd guess). I'll tentaviely mark this as "resolved", but it would be great if you could try this out again when we next release is ready!
