### ISSUE TITLE
spaCy project benchmarks/ud_benchmark

### ISSUE THREAD

**Issue by ronaldluc** [explosion/spaCy#7348]
## How to reproduce the behaviour

Run
```sh
python -m spacy project clone benchmarks/ner_conll03
python -m spacy project assets
python -m spacy project run all   # works as intended
```
update the `project.yml` as follows to use `train-with-vectors`:

```yml
title: "Universal Dependencies v2.5 Benchmarks"
description: "This project template lets you train a part-of-speech tagger, a morphologizer and a dependency parser from a [Universal Dependencies](https://universaldependencies.org/) corpus (v2.5). It takes care of downloading the treebank, converting it to spaCy's format and training and evaluating the model. The template uses the [`UD_English-EWT`](https://github.com/UniversalDependencies/UD_English-EWT) treebank by default, but you can swap it out for any other available treebank. Just make sure to adjust the `ud_treebank`, `ud_prefix` and `spacy_lang` settings in the config. Use `xx` (multi-language) for `spacy_lang` if no language-specific tokenizer is available in spaCy."

# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  ud_treebank: "UD_English-EWT"
  ud_prefix: "en_ewt"
  spacy_lang: "en"
  # spacy model with vectors by name or path: "en_core_web_lg"
  # if used, switch from train to train-with-vectors
  vectors: "en_core_web_lg"  # CHANGE
  gpu: 0
  package_name: "ud_en_ewt"
  package_version: "0.0.0"

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["assets", "training", "metrics", "configs", "packages"]

assets:
  - dest: "assets/ud-treebanks-v2.5.tgz"
    url: "https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-3105/ud-treebanks-v2.5.tgz?sequence=1&isAllowed=y"
    checksum: "388456892760ada0db8e20ce58501025"

workflows:
  all:
    - extract
    - convert
    - generate-config
    #- train
    - train-with-vectors   # CHANGE
    - evaluate
    - package

commands:
  - name: extract
    help: "Extract the data"
    script:
      - "tar xf assets/ud-treebanks-v2.5.tgz -C assets/"
    deps:
      - "assets/ud-treebanks-v2.5.tgz"
    outputs:
      - "assets/ud-treebanks-v2.5/"

  - name: convert
    help: "Convert the data to spaCy's format"
    script:
      - "mkdir -p corpus/${vars.ud_treebank}"
      - "python -m spacy convert assets/ud-treebanks-v2.5/${vars.ud_treebank}/${vars.ud_prefix}-ud-train.conllu corpus/${vars.ud_treebank}/ --converter conllu -n 10 -T"
      - "python -m spacy convert assets/ud-treebanks-v2.5/${vars.ud_treebank}/${vars.ud_prefix}-ud-dev.conllu corpus/${vars.ud_treebank}/ --converter conllu -n 10 -T"
      - "python -m spacy convert assets/ud-treebanks-v2.5/${vars.ud_treebank}/${vars.ud_prefix}-ud-test.conllu corpus/${vars.ud_treebank}/ --converter conllu -n 10 -T"
      - "mv corpus/${vars.ud_treebank}/${vars.ud_prefix}-ud-train.spacy corpus/${vars.ud_treebank}/train.spacy"
      - "mv corpus/${vars.ud_treebank}/${vars.ud_prefix}-ud-dev.spacy corpus/${vars.ud_treebank}/dev.spacy"
      - "mv corpus/${vars.ud_treebank}/${vars.ud_prefix}-ud-test.spacy corpus/${vars.ud_treebank}/test.spacy"
    deps:
      - "assets/ud-treebanks-v2.5/"
    outputs:
      - "corpus/${vars.ud_treebank}/train.spacy"
      - "corpus/${vars.ud_treebank}/dev.spacy"
      - "corpus/${vars.ud_treebank}/test.spacy"

  - name: generate-config
    help: "Generate config"
    script:
      - "python -m spacy init config -l ${vars.spacy_lang} -p morphologizer,tagger,parser -o accuracy configs/${vars.ud_treebank}.cfg -F"   # CHANGE
    outputs:
      - "configs/${vars.ud_treebank}.cfg"

  - name: train
    help: "Train without vectors"
    script:
      - "python -m spacy train configs/${vars.ud_treebank}.cfg -o training/${vars.ud_treebank} --gpu-id ${vars.gpu} --paths.train corpus/${vars.ud_treebank}/train.spacy --paths.dev corpus/${vars.ud_treebank}/dev.spacy --training.max_steps=0 --initialize.vectors=null --components.tok2vec.model.embed.include_static_vectors=false"
    deps:
      - "corpus/${vars.ud_treebank}/train.spacy"
      - "corpus/${vars.ud_treebank}/dev.spacy"
      - "configs/${vars.ud_treebank}.cfg"
    outputs:
      - "training/${vars.ud_treebank}/model-best"

  - name: train-with-vectors
    help: "Train with vectors"
    script:
      - "python -m spacy train configs/${vars.ud_treebank}.cfg -o training2/${vars.ud_treebank} --gpu-id ${vars.gpu} --paths.train corpus/${vars.ud_treebank}/train.spacy --paths.dev corpus/${vars.ud_treebank}/dev.spacy --training.max_steps=0 --initialize.vectors=${vars.vectors}"
    deps:
      - "corpus/${vars.ud_treebank}/train.spacy"
      - "corpus/${vars.ud_treebank}/dev.spacy"
      - "configs/${vars.ud_treebank}.cfg"
    outputs:
      - "training/${vars.ud_treebank}/model-best"

  - name: evaluate
    help: "Evaluate on the test data and save the metrics"
    script:
      # not on GPU because you'd need to handle batching for treebanks withouts
      # paragraph breaks
      - "python scripts/evaluate.py training/${vars.ud_treebank}/model-best assets/ud-treebanks-v2.5/${vars.ud_treebank}/${vars.ud_prefix}-ud-test.conllu --output metrics/${vars.ud_treebank}.txt --text assets/ud-treebanks-v2.5/${vars.ud_treebank}/${vars.ud_prefix}-ud-test.txt"
    deps:
      - "training/${vars.ud_treebank}/model-best"
      - "assets/ud-treebanks-v2.5/${vars.ud_treebank}/${vars.ud_prefix}-ud-test.conllu"
      - "assets/ud-treebanks-v2.5/${vars.ud_treebank}/${vars.ud_prefix}-ud-test.txt"
    outputs:
      - "metrics/${vars.ud_treebank}.txt"

  - name: package
    help: "Package the trained model so it can be installed"
    script:
      - "python -m spacy package training/${vars.ud_treebank}/model-best packages --name ${vars.package_name} --version ${vars.package_version} --force"
    deps:
      - "training/${vars.ud_treebank}/model-best"
    outputs_no_cache:
      - "packages/${vars.package_name}-${vars.package_version}/dist/${vars.package_name}-${vars.package_version}.tar.gz"

  - name: clean
    help: "Remove intermediate files"
    script:
      - "rm -rf training/*"
      - "rm -rf metrics/*"
      - "rm -rf corpus/*"
```
Run modified:
```sh
python -m spacy project run all -F
```
Throws an error:
```sh
=========================== Initializing pipeline ===========================
Set up nlp object from config
Pipeline: ['tok2vec', 'morphologizer', 'tagger', 'parser']
Created vocabulary
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/cli/_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "/home/ai/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ai/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ai/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ai/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ai/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ai/.local/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/training/initialize.py", line 70, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/language.py", line 1222, in initialize
    init_vocab(
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/training/initialize.py", line 112, in init_vocab
    load_vectors_into_model(nlp, vectors)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/training/initialize.py", line 122, in load_vectors_into_model
    vectors_nlp = load_model(name)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/util.py", line 322, in load_model
    return load_model_from_package(name, **kwargs)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/util.py", line 355, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)
  File "/home/ai/.local/lib/python3.8/site-packages/en_core_web_lg/__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/util.py", line 514, in load_model_from_init_py
    return load_model_from_path(
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/util.py", line 390, in load_model_from_path
    return nlp.from_disk(model_path, exclude=exclude)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/language.py", line 1851, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/util.py", line 1174, in from_disk
    reader(path / key)
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/language.py", line 1845, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(
  File "spacy/pipeline/trainable_pipe.pyx", line 336, in spacy.pipeline.trainable_pipe.TrainablePipe.from_disk
  File "/home/ai/.local/lib/python3.8/site-packages/spacy/util.py", line 1174, in from_disk
    reader(path / key)
  File "spacy/pipeline/trainable_pipe.pyx", line 327, in spacy.pipeline.trainable_pipe.TrainablePipe.from_disk.load_model
  File "/home/ai/.local/lib/python3.8/site-packages/thinc/model.py", line 526, in from_bytes
    return self.from_dict(msg)
  File "/home/ai/.local/lib/python3.8/site-packages/thinc/model.py", line 549, in from_dict
    node.set_dim(dim, value)
  File "/home/ai/.local/lib/python3.8/site-packages/thinc/model.py", line 182, in set_dim
    raise KeyError(
KeyError: "Cannot set unknown dimension 'nO' for model 'layernorm'."
```

I've run into the same error when changing to 
```yml
    name: init-config
    help: "Generate a default English NER config"
    script:
      - "python -m spacy init config --lang en --pipeline ner --optimize efficiency --gpu -F configs/${vars.config}.cfg"

## Your Environment
<!-- Include details of your environment. If you're using spaCy 1.7+, you can also type `python -m spacy info --markdown` and copy-paste the result here.-->
* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by ronaldluc** [comment]
Indeed thinc was not up to date:
```sh
Installing collected packages: thinc
  Attempting uninstall: thinc
    Found existing installation: thinc 8.0.0
    Uninstalling thinc-8.0.0:
      Successfully uninstalled thinc-8.0.0
Successfully installed thinc-8.0.1
```
**The project now runs as intended**
```sh
python -m spacy project run all -F
```

Thank you for a quick resolution!

Would it be possible for spacy to force-upgrade its dependencies when installing/upgrading? I've run into SpaCy/Hugging transformer/SpaCy downloaded models version issues many times. Even a Warning would be really helpful for newcomers to the SpaCy ecosystem.

**Comment by adrianeboyd** [comment]
Yes, we should have excluded this older version of thinc in the next release of spacy. Now spacy v3.0.5 should upgrade thinc correctly with bugfixes.
