### ISSUE TITLE
Error in spacy/serialize/huffman.pxd when running python -m spacy.en.download all

### ISSUE THREAD

**Issue by ankitarya10** [explosion/spaCy#735]
I am trying to install spacy in a docker container. The docker is based on debian, the image I am using as base is through anaconda : https://github.com/ContinuumIO/docker-images/blob/master/anaconda3/Dockerfile

Spacy installation is successful.

It fails here:
**python -m spacy.en.download all**
 ---> Running in 32eea90f5df4
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/lib/python3.5/site-packages/spacy/__init__.py", line 6, in <module>
    from . import en
  File "/opt/conda/lib/python3.5/site-packages/spacy/en/__init__.py", line 8, in <module>
    from ..language import Language
  File "/opt/conda/lib/python3.5/site-packages/spacy/language.py", line 17, in <module>
    from .tokenizer import Tokenizer
  File "spacy/morphology.pxd", line 25, in init spacy.tokenizer (spacy/tokenizer.cpp:11781)
  File "spacy/vocab.pxd", line 27, in init spacy.morphology (spacy/morphology.cpp:10725)
  File "spacy/serialize/packer.pxd", line 4, in init spacy.vocab (spacy/vocab.cpp:17911)
  File "spacy/serialize/huffman.pxd", line 15, in init spacy.serialize.packer (spacy/serialize/packer.cpp:23899)
ImportError: /opt/conda/lib/python3.5/site-packages/spacy/serialize/huffman.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

Any help is appreciated !

**Comment by AdrianLoer** [comment]
````
conda update --all
````
does it for me

**Comment by ankitarya10** [comment]
Agreed, that works. No idea however what specific package caused the issue.
