### ISSUE TITLE
Installation of spacy 3.0.X leads to an error

### ISSUE THREAD

**Issue by InputMoe** [explosion/spaCy#7545]
## How to reproduce the behaviour

`pip install spacy -U`

```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: spacy in ./.local/lib/python3.7/site-packages (2.3.5)
Collecting spacy
  Using cached spacy-3.0.5.tar.gz (7.0 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/pi/.local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wbltwgvw/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'preshed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=8.0.2,<8.1.0' 'blis>=0.4.0,<0.8.0' pathy 'numpy>=1.15.0'
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/pi/.local/lib/python3.7/site-packages/pip/__main__.py", line 24, in <module>
      sys.exit(_main())
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 71, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
      module = importlib.import_module(module_path)
    File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 15, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 16, in <module>
      from pip._vendor import html5lib, requests
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 123, in <module>
      from . import utils
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/usr/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/home/pi/.local/lib/python3.7/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/home/pi/.local/lib/python3.7/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/65/01/fd65769520d4b146d92920170fd00e01e826cda39a366bde82a87ca249db/spacy-3.0.5.tar.gz#sha256=9f7a09fbad53aac2a3cb7696a902de62b94575a15d249dd5e26a98049328060e (from https://pypi.org/simple/spacy/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/bin/python3 /home/pi/.local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wbltwgvw/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'preshed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=8.0.2,<8.1.0' 'blis>=0.4.0,<0.8.0' pathy 'numpy>=1.15.0' Check the logs for full command output.
```

## Your Environment
Raspberry Pi 4
* Operating System: 
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

* Python Version Used: 3.7
* spaCy Version Used: 2.5
* Environment Information: 
```
Hardware	: BCM2835
Revision	: c03130
Serial		: 10000000bdabc733
Model		: Raspberry Pi 400 Rev 1.0
```

**Comment by adrianeboyd** [comment]
Hi, it looks like the solution is to uninstall `typing` in your env (`pip uninstall typing`).

In general, we'd recommend installing spacy a new virtual environment, select the "virtual env" checkbox in the quickstart here for instructions: https://spacy.io/usage

**Comment by adrianeboyd** [comment]
Let me move this to the "install questions" section of our new discussions board. This issue will be locked, but the new thread will remain open.
