### ISSUE TITLE
Error while ```sudo python -m spacy.en.download```

### ISSUE THREAD

**Issue by erogol** [explosion/spaCy#757]
```
Downloading parsing model
Continue downloading...
Traceback (most recent call last):eta 90m 41s           
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/spacy/en/download.py", line 25, in <module>
    plac.call(main)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spacy/en/download.py", line 18, in main
    download('en', force=False, data_path=data_path)
  File "/usr/local/lib/python2.7/dist-packages/spacy/download.py", line 36, in download
    about.__models__.get(lang, lang), data_path)
  File "/usr/local/lib/python2.7/dist-packages/sputnik/__init__.py", line 44, in install
    archive = cache.fetch(package_name)
  File "/usr/local/lib/python2.7/dist-packages/sputnik/cache.py", line 67, in fetch
    checksum_header=util.s3_header('md5'))
  File "/usr/local/lib/python2.7/dist-packages/sputnik/uget.py", line 219, in download
    write_func=write)
  File "/usr/local/lib/python2.7/dist-packages/sputnik/uget.py", line 169, in read_request
    chunk = response.read(default.CHUNK_SIZE)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 602, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
```

**Comment by mattmacy** [comment]
The only bug is that spacy doesn't handle and report the connection reset gracefully. You can try restarting the download.
