### ISSUE TITLE
Can't train second textcat component in a pipeline with another frozen textcat component (with different labels)

### ISSUE THREAD

**Issue by themrmax** [explosion/spaCy#7689]
## How to reproduce the behaviour

Apologies for the long example, this is the simplest way I can put it. It looks like the bug is in the evaluation code encountering a mismatch of textcat labels .... is there a way to selectively disable some components during the model evaluation?

The following example based on the textcat_demo pipeline first trains a textcat model and then attempts to source it as a frozen component in a subsequent model.

```
git clone https://github.com/explosion/projects
cd projects/pipelines/textcat_demo

# create config file for second training run
echo '
[paths]
train = null
dev = null
vectors = null
init_tok2vec = null

[system]
seed = 0
gpu_allocator = null

[nlp]
lang = "en"
pipeline = ["textcat", "textcat2"]
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
batch_size = 1000
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.textcat]
source = "training/model-best"
threshold = 0.5

[components.textcat2]
factory = "textcat"
threshold = 0.5

[components.textcat2.model]
@architectures = "spacy.TextCatEnsemble.v2"
nO = null

[components.textcat2.model.linear_model]
@architectures = "spacy.TextCatBOW.v1"
exclusive_classes = true
ngram_size = 1
no_output_layer = false
nO = null

[components.textcat2.model.tok2vec]
@architectures = "spacy.Tok2Vec.v2"

[components.textcat2.model.tok2vec.embed]
@architectures = "spacy.MultiHashEmbed.v1"
width = 64
rows = [2000,2000,1000,1000,1000,1000]
attrs = ["ORTH","LOWER","PREFIX","SUFFIX","SHAPE","ID"]
include_static_vectors = false

[components.textcat2.model.tok2vec.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 64
window_size = 1
maxout_pieces = 3
depth = 2

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
gold_preproc = false
max_length = 0
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
gold_preproc = false
max_length = 0
limit = 0
augmenter = null

[training]
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1000
max_epochs = 0
max_steps = 1000
eval_frequency = 100
frozen_components = ["textcat"]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]
cats_score_desc = null
cats_micro_p = null
cats_micro_r = null
cats_micro_f = null
cats_macro_p = null
cats_macro_r = null
cats_macro_f = null
cats_macro_auc = null
cats_f_per_type = null
cats_macro_auc_per_type = null
cats_score = 1.0

[pretraining]

[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
' > configs/config2.cfg


spacy project run convert       
spacy project run train       

# change labels for second training run
sed -i -e 's/DOCUMENTATION/LABEL1/g'  assets/docs_issues_training.jsonl
sed -i -e 's/OTHER/LABEL2/g'  assets/docs_issues_training.jsonl
sed -i -e 's/DOCUMENTATION/LABEL1/g'  assets/docs_issues_eval.jsonl
sed -i -e 's/OTHER/LABEL2/g'  assets/docs_issues_eval.jsonl

spacy project run convert       
python -m spacy train configs/config2.cfg --output training2/ --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy --nlp.lang en --gpu-id -1

```

Output:
```

ℹ Using CPU

=========================== Initializing pipeline ===========================
[2021-04-07 21:18:30,045] [INFO] Set up nlp object from config
[2021-04-07 21:18:30,054] [INFO] Pipeline: ['textcat', 'textcat2']
[2021-04-07 21:18:30,061] [INFO] Created vocabulary
[2021-04-07 21:18:30,062] [INFO] Finished initializing nlp object
[2021-04-07 21:18:34,945] [INFO] Initialized pipeline components: ['textcat2']
✔ Initialized pipeline

============================= Training pipeline =============================
ℹ Pipeline: ['textcat', 'textcat2']
ℹ Frozen components: ['textcat']
ℹ Initial learn rate: 0.001
E    #       LOSS TEXTCAT2  CATS_SCORE  SCORE
---  ------  -------------  ----------  ------
⚠ Aborting and saving the final best model. Encountered exception:
KeyError("[E900] Could not run the full pipeline for evaluation. If you
specified frozen components, make sure they were already initialized and
trained. Full pipeline: ['textcat', 'textcat2']")
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/training/loop.py", line 267, in evaluate
    scores = nlp.evaluate(dev_corpus(nlp))
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 1362, in evaluate
    results = scorer.score(examples)
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/scorer.py", line 129, in score
    scores.update(component.score(examples, **self.cfg))
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/pipeline/textcat.py", line 368, in score
    **kwargs,
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/scorer.py", line 439, in score_cats
    auc_per_type[label].score_set(pred_score, gold_score)
KeyError: 'LABEL2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/cli/train.py", line 59, in train_cli
    train(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/training/loop.py", line 114, in train
    raise e
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/training/loop.py", line 98, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/training/loop.py", line 212, in train_while_improving
    score, other_scores = evaluate()
  File "/opt/anaconda3/lib/python3.7/site-packages/spacy/training/loop.py", line 269, in evaluate
    raise KeyError(Errors.E900.format(pipeline=nlp.pipe_names)) from e
KeyError: "[E900] Could not run the full pipeline for evaluation. If you specified frozen components, make sure they were already initialized and trained. Full pipeline: ['textcat', 'textcat2']"

```

## Your Environment

- **spaCy version:** 3.0.5
- **Platform:** Darwin-20.3.0-x86_64-i386-64bit
- **Python version:** 3.7.4
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_sm (3.0.0)

**Comment by themrmax** [comment]
Doh ... just found what I was looking for, the above code runs fine with `disabled = ["textcat"]` 🦆
