### ISSUE TITLE
TypeError: load() got an unexpected keyword argument 'vocab'

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#7702]
I get this error when I specify the word2vec vectors in the config file (config file at end of post)
Word2 vec was created using gensim then I ran the following command to conver t to spacy format 

`python -m spacy init vectors en "spacy_word2vecmodel_1.0.0.8.txt.gz" "spacy"`

Spacy version - 3.0.5

```
(spacy3.0) PS D:\training\spacy> python -m spacy train config.cfg --output output --gpu-id 0
ℹ Using GPU: 0

=========================== Initializing pipeline ===========================
[2021-04-08 21:59:04,214] [INFO] Set up nlp object from config
[2021-04-08 21:59:04,222] [INFO] Pipeline: ['transformer', 'ner']
[2021-04-08 21:59:04,225] [INFO] Created vocabulary
Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy3.0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\spacy3.0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\cli\train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\training\initialize.py", line 71, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\language.py", line 1224, in initialize
    init_vocab(
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\training\initialize.py", line 113, in init_vocab
    load_vectors_into_model(nlp, vectors)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\training\initialize.py", line 123, in load_vectors_into_model
    vectors_nlp = load_model(name)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\util.py", line 322, in load_model
    return load_model_from_package(name, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\util.py", line 355, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)
TypeError: load() got an unexpected keyword argument 'vocab'
```

**Config file** 

```
[paths]
train = "finaltrain.spacy"
dev = "finaltest.spacy"
vectors =  "spacy"
init_tok2vec = null

[system]
seed = 0
gpu_allocator = "pytorch"

[nlp]
lang = "en"
pipeline = ["transformer","ner"]
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
batch_size = 128
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = false
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"

[components.transformer]
factory = "transformer"
max_batch_items = 4096
set_extra_annotations = {"@annotation_setters":"spacy-transformers.null_annotation_setter.v1"}

[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "roberta-base"

[components.transformer.model.get_spans]
@span_getters = "spacy-transformers.strided_spans.v1"
window = 128
stride = 96

[components.transformer.model.tokenizer_config]
use_fast = true

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 500
gold_preproc = false
limit = 0
augmenter = null

[training]
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
accumulate_gradient = 3
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
dropout = 0.1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_padded.v1"
discard_oversize = true
size = 2000
buffer = 256
get_length = null

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001

[training.optimizer.learn_rate]
@schedules = "warmup_linear.v1"
warmup_steps = 250
total_steps = 20000
initial_rate = 0.00005

[training.score_weights]
ents_per_type = null
ents_f = 1.0
ents_p = 0.0
ents_r = 0.0

[pretraining]

[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```

**Comment by adrianeboyd** [comment]
Because of how python handles imports, `spacy` is not going to be a good choice for the name of the vectors model directory. It thinks `spacy` is an existing package and is trying to load the local directory as a package, or something along those lines. 

Whatever you provide as the vectors should be something that can be loaded with `spacy.load()`, either a package name or a path. You can test this in your working directory by running `spacy.load()` to check that it works as expected.

It would be much easier if you use a non-conflicting name like `en_vectors_word2vecmodel_1.0.0.8`.

**Comment by adrianeboyd** [comment]
Let me move this to the discussion board...
