### ISSUE TITLE
Error when using the Spacy 3 project template for finetuning BIONLP13cg model

### ISSUE THREAD

**Issue by balachander1964** [explosion/spaCy#7739]
Hi, I get an error saying that tokenizer is missing when I use the new spacy project template for fine tuning a SCISPACY model. I am trying to fine tune using the data sets from the Flair NLP corpus. Could you please let me know how to fix this? The following is the error text:
Starting the project workflow.
ℹ Fetching 2 asset(s)
✔ Asset already exists:
D:\Projects2017\helpers\spacy3_model_trainer\spacy3_model_trainer\assets\train.json
✔ Asset already exists:
D:\Projects2017\helpers\spacy3_model_trainer\spacy3_model_trainer\assets\dev.json
Converting the data sets to spacy doc format

================================== convert ==================================
ℹ Skipping 'convert': nothing changed
Converted the data sets to spacy doc format
Writing the configuration

=============================== create-config ===============================
ℹ Skipping 'create-config': nothing changed
Wrote the configuration information
Started the trainer.

=================================== train ===================================
Running command: 'D:\python\3_7\python.exe' -m spacy train configs/config.cfg --output training/ --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy --training.eval_frequency 10 --training.max_steps 100 --gpu-id -1
Traceback (most recent call last):
  File "D:\Projects2017\helpers\spacy3_model_trainer\spacy3_model_trainer\test_project_ner_demo_update.py", line 31, in <module>
    test_trainer_project()
  File "D:\Projects2017\helpers\spacy3_model_trainer\spacy3_model_trainer\test_project_ner_demo_update.py", line 21, in test_trainer_project
    project_run(root, "train", capture=True)
  File "D:\python\3_7\lib\site-packages\spacy\cli\project\run.py", line 91, in project_run
    run_commands(cmd["script"], dry=dry, capture=capture)
  File "D:\python\3_7\lib\site-packages\spacy\cli\project\run.py", line 174, in run_commands
    run_command(command, capture=capture)
  File "D:\python\3_7\lib\site-packages\spacy\util.py", line 842, in run_command
    raise error
subprocess.SubprocessError: Error running command:

D:\python\3_7\python.exe -m spacy train configs/config.cfg --output training/ --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy --training.eval_frequency 10 --training.max_steps 100 --gpu-id -1

Subprocess exited with status 1

Process log (stdout and stderr):

[2021-04-10 13:05:29,698] [INFO] Set up nlp object from config
[2021-04-10 13:05:29,789] [INFO] Pipeline: ['tok2vec', 'tagger', 'attribute_ruler', 'lemmatizer', 'parser', 'ner']
[2021-04-10 13:05:29,789] [INFO] Resuming training for: ['ner']
Traceback (most recent call last):
  File "D:\python\3_7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\3_7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python\3_7\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "D:\python\3_7\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "D:\python\3_7\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\python\3_7\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\python\3_7\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\python\3_7\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\python\3_7\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\python\3_7\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\python\3_7\lib\site-packages\spacy\cli\train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "D:\python\3_7\lib\site-packages\spacy\training\initialize.py", line 71, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "D:\python\3_7\lib\site-packages\spacy\language.py", line 1219, in initialize
    I = registry.resolve(config["initialize"], schema=ConfigSchemaInit)
  File "D:\python\3_7\lib\site-packages\thinc\config.py", line 723, in resolve
    config, schema=schema, overrides=overrides, validate=validate, resolve=True
  File "D:\python\3_7\lib\site-packages\thinc\config.py", line 772, in _make
    config, schema, validate=validate, overrides=overrides, resolve=resolve
  File "D:\python\3_7\lib\site-packages\thinc\config.py", line 825, in _fill
    promise_schema = cls.make_promise_schema(value, resolve=resolve)
  File "D:\python\3_7\lib\site-packages\thinc\config.py", line 1016, in make_promise_schema
    func = cls.get(reg_name, func_name)
  File "D:\python\3_7\lib\site-packages\spacy\util.py", line 141, in get
    ) from None
catalogue.RegistryError: [E893] Could not find function 'replace_tokenizer' in function registry 'callbacks'. If you're using a custom function, make sure the code is available. If the function is provided by a third-party package, e.g. spacy-transformers, make sure the package is installed in your environment.

Available names: none
[i] Using CPU

=========================== Initializing pipeline ===========================

**Comment by adrianeboyd** [comment]
The scispacy developers use custom callbacks to set up the tokenizers for their models initially. Since you're extending a model, you want to do something like this to copy the vocab and the tokenizer from the model: https://github.com/explosion/spaCy/discussions/7582

We should figure out a good way to incorporate this kind of callback into the main library and maybe add an option to `init config` to make this easier.

**Comment by adrianeboyd** [comment]
Let me convert this to a discussion thread...
