### ISSUE TITLE
Unable to install spacy via pip

### ISSUE THREAD

**Issue by mitchellspryn** [explosion/spaCy#7744]
## How to reproduce the behaviour
When attempting to install spacy via pip (both CUDA and non-CUDA) on ubuntu 18.04, there are lots of compilation errors:

```
$ pip3 install spacy[cuda102]
Collecting spacy[cuda102]
  Using cached https://files.pythonhosted.org/packages/65/01/fd65769520d4b146d92920170fd00e01e826cda39a366bde82a87ca249db/spacy-3.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    """Knowledge-base for entity or concept linking."""
    from cymem.cymem cimport Pool
    ^
    ------------------------------------------------------------
    
    spacy/kb.pxd:2:0: 'cymem/cymem.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    """Knowledge-base for entity or concept linking."""
    from cymem.cymem cimport Pool
    ^
    ------------------------------------------------------------
    
    spacy/kb.pxd:2:0: 'cymem/cymem/Pool.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    """Knowledge-base for entity or concept linking."""
    from cymem.cymem cimport Pool
    from preshed.maps cimport PreshMap
    ^
    ------------------------------------------------------------
    
    spacy/kb.pxd:3:0: 'preshed/maps.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    """Knowledge-base for entity or concept linking."""
    from cymem.cymem cimport Pool
    from preshed.maps cimport PreshMap
    ^
    ------------------------------------------------------------
    
    spacy/kb.pxd:3:0: 'preshed/maps/PreshMap.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from libcpp.vector cimport vector
    from preshed.maps cimport PreshMap
    from cymem.cymem cimport Pool
    from murmurhash.mrmr cimport hash64
    ^
    ------------------------------------------------------------
    
    spacy/vocab.pxd:4:0: 'murmurhash/mrmr.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from libcpp.vector cimport vector
    from preshed.maps cimport PreshMap
    from cymem.cymem cimport Pool
    from murmurhash.mrmr cimport hash64
    ^
    ------------------------------------------------------------
    
    spacy/vocab.pxd:4:0: 'murmurhash/mrmr/hash64.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        unsigned char[8] s
        unsigned char* p
    
    
    cdef class StringStore:
        cdef Pool mem
            ^
    ------------------------------------------------------------
    
    spacy/strings.pxd:23:9: 'Pool' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    cdef class StringStore:
        cdef Pool mem
    
        cdef vector[hash_t] keys
        cdef public PreshMap _map
                   ^
    ------------------------------------------------------------
    
    spacy/strings.pxd:26:16: 'PreshMap' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    cdef class StringStore:
        cdef Pool mem
    
        cdef vector[hash_t] keys
        cdef public PreshMap _map
                            ^
    ------------------------------------------------------------
    
    spacy/strings.pxd:26:25: C attribute of type '<error>' cannot be accessed from Python
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from cymem.cymem cimport Pool
    from preshed.maps cimport PreshMap, PreshMapArray
    ^
    ------------------------------------------------------------
    
    spacy/morphology.pxd:2:0: 'preshed/maps/PreshMapArray.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from cymem.cymem cimport Pool
    from preshed.maps cimport PreshMap, PreshMapArray
    from libc.stdint cimport uint64_t
    from murmurhash cimport mrmr
    ^
    ------------------------------------------------------------
    
    spacy/morphology.pxd:4:0: 'murmurhash.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from .parts_of_speech cimport univ_pos_t
    from . cimport symbols
    
    
    cdef class Morphology:
        cdef readonly Pool mem
                     ^
    ------------------------------------------------------------
    
    spacy/morphology.pxd:15:18: 'Pool' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from .parts_of_speech cimport univ_pos_t
    from . cimport symbols
    
    
    cdef class Morphology:
        cdef readonly Pool mem
                          ^
    ------------------------------------------------------------
    
    spacy/morphology.pxd:15:23: C attribute of type '<error>' cannot be accessed from Python
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    
    cdef class Morphology:
        cdef readonly Pool mem
        cdef readonly StringStore strings
        cdef PreshMap tags # Keyed by hash, value is pointer to tag
            ^
    ------------------------------------------------------------
    
    spacy/morphology.pxd:17:9: 'PreshMap' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef public object lemmatizer
        cdef readonly object tag_map
        cdef readonly object tag_names
        cdef readonly object reverse_index
        cdef readonly object _exc
        cdef readonly PreshMapArray _cache
                     ^
    ------------------------------------------------------------
    
    spacy/morphology.pxd:24:18: 'PreshMapArray' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef public object lemmatizer
        cdef readonly object tag_map
        cdef readonly object tag_names
        cdef readonly object reverse_index
        cdef readonly object _exc
        cdef readonly PreshMapArray _cache
                                   ^
    ------------------------------------------------------------
    
    spacy/morphology.pxd:24:32: C attribute of type '<error>' cannot be accessed from Python
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        bint is_lex
        int length
    
    
    cdef class Vocab:
        cdef Pool mem
            ^
    ------------------------------------------------------------
    
    spacy/vocab.pxd:27:9: 'Pool' is not a type identifier
    warning: spacy/vocab.pxd:28:10: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
    warning: spacy/vocab.pxd:29:10: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
    warning: spacy/vocab.pxd:30:10: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
    warning: spacy/vocab.pxd:31:10: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
    warning: spacy/vocab.pxd:32:10: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
    warning: spacy/vocab.pxd:33:10: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef readonly int length
        cdef public object data_dir
        cdef public object lex_attr_getters
        cdef public object cfg
    
        cdef const LexemeC* get(self, Pool mem, unicode string) except NULL
                                     ^
    ------------------------------------------------------------
    
    spacy/vocab.pxd:39:34: 'Pool' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef public object data_dir
        cdef public object lex_attr_getters
        cdef public object cfg
    
        cdef const LexemeC* get(self, Pool mem, unicode string) except NULL
        cdef const LexemeC* get_by_orth(self, Pool mem, attr_t orth) except NULL
                                             ^
    ------------------------------------------------------------
    
    spacy/vocab.pxd:40:42: 'Pool' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef const LexemeC* get(self, Pool mem, unicode string) except NULL
        cdef const LexemeC* get_by_orth(self, Pool mem, attr_t orth) except NULL
        cdef const TokenC* make_fused_token(self, substrings) except NULL
    
        cdef const LexemeC* _new_lexeme(self, Pool mem, unicode string) except NULL
                                             ^
    ------------------------------------------------------------
    
    spacy/vocab.pxd:43:42: 'Pool' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef const LexemeC* get_by_orth(self, Pool mem, attr_t orth) except NULL
        cdef const TokenC* make_fused_token(self, substrings) except NULL
    
        cdef const LexemeC* _new_lexeme(self, Pool mem, unicode string) except NULL
        cdef int _add_lex_to_vocab(self, hash_t key, const LexemeC* lex) except -1
        cdef const LexemeC* _new_lexeme(self, Pool mem, unicode string) except NULL
                                             ^
    ------------------------------------------------------------
    
    spacy/vocab.pxd:45:42: 'Pool' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef const LexemeC* _new_lexeme(self, Pool mem, unicode string) except NULL
        cdef int _add_lex_to_vocab(self, hash_t key, const LexemeC* lex) except -1
        cdef const LexemeC* _new_lexeme(self, Pool mem, unicode string) except NULL
    
        cdef PreshMap _by_orth
            ^
    ------------------------------------------------------------
    
    spacy/vocab.pxd:47:9: 'PreshMap' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef hash_t alias_hash
        cdef float prior_prob
    
    
    cdef class KnowledgeBase:
        cdef Pool mem
            ^
    ------------------------------------------------------------
    
    spacy/kb.pxd:30:9: 'Pool' is not a type identifier
    warning: spacy/kb.pxd:31:10: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        # This maps 64bit keys (hash of unique entity string)
        # to 64bit values (position of the _KBEntryC struct in the _entries vector).
        # The PreshMap is pretty space efficient, as it uses open addressing. So
        # the only overhead is the vacancy rate, which is approximately 30%.
        cdef PreshMap _entry_index
            ^
    ------------------------------------------------------------
    
    spacy/kb.pxd:38:9: 'PreshMap' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        # Storing 1m entries would take 41.6mb under this scheme.
        cdef entry_vec _entries
    
        # This maps 64bit keys (hash of unique alias string)
        # to 64bit values (position of the _AliasC struct in the _aliases_table vector).
        cdef PreshMap _alias_index
            ^
    ------------------------------------------------------------
    
    spacy/kb.pxd:48:9: 'PreshMap' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        DOCS: https://spacy.io/api/kb
        """
    
        def __init__(self, Vocab vocab, entity_vector_length):
            """Create a KnowledgeBase."""
            self.mem = Pool()
                      ^
    ------------------------------------------------------------
    
    spacy/kb.pyx:89:19: 'Pool' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        def __init__(self, Vocab vocab, entity_vector_length):
            """Create a KnowledgeBase."""
            self.mem = Pool()
            self.entity_vector_length = entity_vector_length
            self._entry_index = PreshMap()
                               ^
    ------------------------------------------------------------
    
    spacy/kb.pyx:91:28: 'PreshMap' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __init__(self, Vocab vocab, entity_vector_length):
            """Create a KnowledgeBase."""
            self.mem = Pool()
            self.entity_vector_length = entity_vector_length
            self._entry_index = PreshMap()
            self._alias_index = PreshMap()
                               ^
    ------------------------------------------------------------
    
    spacy/kb.pyx:92:28: 'PreshMap' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cpdef set_entities(self, entity_list, freq_list, vector_list):
            if len(entity_list) != len(freq_list) or len(entity_list) != len(vector_list):
                raise ValueError(Errors.E140)
    
            nr_entities = len(set(entity_list))
            self._entry_index = PreshMap(nr_entities+1)
                               ^
    ------------------------------------------------------------
    
    spacy/kb.pyx:147:28: 'PreshMap' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            cdef int64_t nr_entities
            cdef int64_t entity_vector_length
            reader.read_header(&nr_entities, &entity_vector_length)
    
            self.entity_vector_length = entity_vector_length
            self._entry_index = PreshMap(nr_entities+1)
                               ^
    ------------------------------------------------------------
    
    spacy/kb.pyx:408:28: 'PreshMap' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            assert nr_entities == self.get_size_entities()
    
            # STEP 3: load aliases
            cdef int64_t nr_aliases
            reader.read_alias_length(&nr_aliases)
            self._alias_index = PreshMap(nr_aliases+1)
                               ^
    ------------------------------------------------------------
    
    spacy/kb.pyx:448:28: 'PreshMap' is not a constant, variable or function identifier
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c4i1ptrk/spacy/setup.py", line 224, in <module>
        setup_package()
      File "/tmp/pip-build-c4i1ptrk/spacy/setup.py", line 211, in setup_package
        ext_modules = cythonize(ext_modules, compiler_directives=COMPILER_DIRECTIVES)
      File "/home/mitchell/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
        cythonize_one(*args)
      File "/home/mitchell/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: spacy/kb.pyx
    Copied /tmp/pip-build-c4i1ptrk/spacy/setup.cfg -> /tmp/pip-build-c4i1ptrk/spacy/spacy/tests/package
    Copied /tmp/pip-build-c4i1ptrk/spacy/pyproject.toml -> /tmp/pip-build-c4i1ptrk/spacy/spacy/tests/package
    Cythonizing sources
    Compiling spacy/training/example.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/strings.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/lexeme.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/vocab.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/kb.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/ml/parser_model.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/morphology.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/dep_parser.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/morphologizer.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/multitask.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/ner.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/pipe.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/trainable_pipe.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/sentencizer.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/senter.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/tagger.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/transition_parser.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/_parser_internals/arc_eager.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/_parser_internals/ner.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/_parser_internals/nonproj.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/_parser_internals/_state.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/_parser_internals/stateclass.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/_parser_internals/transition_system.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/pipeline/_parser_internals/_beam_utils.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/tokenizer.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/tokens/doc.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/tokens/span.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/tokens/token.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/tokens/span_group.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/tokens/graph.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/tokens/morphanalysis.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/tokens/_retokenize.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/matcher/matcher.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/matcher/phrasematcher.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/matcher/dependencymatcher.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    Compiling spacy/vectors.pyx because it depends on /home/mitchell/.local/lib/python3.6/site-packages/Cython/Includes/libcpp/vector.pxd.
    [ 1/36] Cythonizing spacy/kb.pyx
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c4i1ptrk/spacy/
```

## Your Environment
* Operating System: Ubuntu 18.04; cuda 10.2
* Python Version Used: 3.6.9
* spaCy Version Used: 3.0.5
* Environment Information: Additional packages already installed:
```
absl-py==0.9.0
actionlib==1.12.1
angles==1.9.12
apturl==0.5.2
asn1crypto==0.24.0
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
bleach==3.1.4
bondpy==1.8.5
Brlapi==0.6.6
cached-property==1.5.2
cachetools==4.0.0
camera-calibration==1.15.0
camera-calibration-parsers==1.11.13
catkin==0.7.29
catkin-pkg==0.4.16
certifi==2018.1.18
chardet==3.0.4
chrome-gnome-shell==0.0.0
click==7.1.2
colorama==0.4.3
command-not-found==0.3
controller-manager==0.18.2
controller-manager-msgs==0.18.2
cryptography==2.1.4
cupshelpers==1.0
cv-bridge==1.13.0
cycler==0.10.0
Cython==0.29.22
dataclasses==0.8
decorator==4.4.2
defer==1.0.6
defusedxml==0.6.0
diagnostic-analysis==1.9.7
diagnostic-common-diagnostics==1.9.7
diagnostic-updater==1.9.7
distro==1.5.0
distro-info===0.18ubuntu0.18.04.1
docutils==0.16
dynamic-reconfigure==1.6.3
empy==3.3.4
entrypoints==0.3
Flask==1.1.2
gast==0.2.2
gazebo-plugins==2.8.7
gazebo-ros==2.8.7
gencpp==0.6.5
geneus==2.2.6
genlisp==0.4.16
genmsg==0.5.16
gennodejs==2.0.1
genpy==0.6.14
gensim==4.0.1
gnupg==2.3.1
google-auth==1.13.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
greenlet==0.4.12
grpcio==1.28.1
h5py==3.1.0
httplib2==0.9.2
idna==2.6
image-geometry==1.13.0
importlib-metadata==1.6.0
interactive-markers==1.11.5
ipykernel==5.2.1
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jedi==0.17.0
Jinja2==2.11.2
joblib==1.0.1
joint-state-publisher==1.12.15
json5==0.9.4
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
jupyterlab==2.0.1
jupyterlab-server==1.0.7
kdl-parser-py==1.13.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.2.0
language-selector==0.1
laser-geometry==1.6.5
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
linecache2==1.0.0
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.2.1
message-filters==1.14.10
mistune==0.8.4
mpmath==1.1.0
msgpack==0.5.6
nbconvert==5.6.1
nbformat==5.0.6
neovim==0.2.0
netifaces==0.10.4
nltk==3.6.1
nose==1.3.7
notebook==6.0.3
numpy==1.19.5
oauth==1.0.1
oauthlib==3.1.0
olefile==0.45.1
open3d==0.9.0.0
opt-einsum==3.2.0
pandas==1.0.3
pandocfilters==1.4.2
parso==0.7.0
pbr==5.4.4
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
pptk==0.1.0
prometheus-client==0.7.1
prompt-toolkit==3.0.5
protobuf==3.11.3
psutil==5.7.0
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycrypto==2.6.1
pycryptodomex==3.9.7
pycups==1.9.73
Pygments==2.6.1
pygobject==3.26.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyparsing==2.4.7
pyRFC3339==1.0
pyrsistent==0.16.0
python-apt==1.6.5+ubuntu0.5
python-dateutil==2.8.1
python-debian==0.1.32
python-qt-binding==0.4.3
pytz==2019.3
pywikibot==6.0.1
pyxdg==0.25
PyYAML==5.3.1
pyzmq==19.0.0
qt-dotgraph==0.4.2
qt-gui==0.4.2
qt-gui-cpp==0.4.2
qt-gui-py-common==0.4.2
regex==2021.4.4
reportlab==3.4.0
requests==2.23.0
requests-oauthlib==1.3.0
requests-unixsocket==0.1.5
resource-retriever==1.12.6
roman==2.0.0
rosbag==1.14.10
rosboost-cfg==1.14.9
rosclean==1.14.9
roscreate==1.14.9
rosgraph==1.14.10
roslaunch==1.14.10
roslib==1.14.9
roslint==0.11.2
roslz4==1.14.10
rosmake==1.14.9
rosmaster==1.14.10
rosmsg==1.14.10
rosnode==1.14.10
rosparam==1.14.10
rospkg==1.2.4
rospy==1.14.10
rosservice==1.14.10
rostest==1.14.10
rostopic==1.14.10
rosunit==1.14.9
roswtf==1.14.10
rqt-action==0.4.9
rqt-bag==0.4.14
rqt-bag-plugins==0.4.14
rqt-console==0.4.9
rqt-dep==0.4.9
rqt-graph==0.4.11
rqt-gui==0.5.2
rqt-gui-py==0.5.2
rqt-image-view==0.4.16
rqt-launch==0.4.8
rqt-logger-level==0.4.8
rqt-moveit==0.5.7
rqt-msg==0.4.8
rqt-nav-view==0.5.7
rqt-plot==0.4.9
rqt-pose-view==0.5.8
rqt-publisher==0.4.8
rqt-py-common==0.5.2
rqt-py-console==0.4.8
rqt-reconfigure==0.5.3
rqt-robot-dashboard==0.5.7
rqt-robot-monitor==0.5.13
rqt-robot-steering==0.5.10
rqt-runtime-monitor==0.5.7
rqt-rviz==0.6.0
rqt-service-caller==0.4.8
rqt-shell==0.4.9
rqt-srv==0.4.8
rqt-tf-tree==0.6.0
rqt-top==0.4.8
rqt-topic==0.4.11
rqt-web==0.4.8
rsa==4.0
rviz==1.13.14
scikit-learn==0.22.2.post1
scipy==1.5.4
SecretStorage==2.3.1
Send2Trash==1.5.0
sensor-msgs==1.12.7
SexMachine==0.1.1
Shapely==1.7.1
simplejson==3.13.2
six==1.14.0
smach==2.0.1
smach-ros==2.0.1
smart-open==5.0.0
smclib==1.8.5
sympy==1.5.1
system-service==0.3
systemd-python==234
tensorboard==2.1.1
tensorflow==2.1.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
testresources==2.0.1
tf==1.12.1
tf-conversions==1.12.1
tf2-geometry-msgs==0.6.5
tf2-kdl==0.6.5
tf2-py==0.6.5
tf2-ros==0.6.5
topic-tools==1.14.10
torch==1.8.1
torchaudio==0.8.1
torchvision==0.9.1
tornado==6.0.4
tqdm==4.60.0
traceback2==1.4.0
traitlets==4.3.3
typing-extensions==3.7.4.3
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
unittest2==1.1.0
urdfdom-py==0.4.4
urllib3==1.22
usb-creator==0.3.3
wadllib==1.3.2
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wikitextparser==0.47.4
wrapt==1.12.1
xacro==1.13.9
xkit==0.0.0
zipp==3.1.0
zope.interface==4.3.2
```

**Comment by adrianeboyd** [comment]
Hi, you probably just need to upgrade pip and related tools before installing spacy:

```bash
pip install -U pip setuptools wheel
```

After upgrading pip, it should install binary wheels on x86_64, so you probably won't need to compile anything. And even if you do, the newer pip will be able to compile the package correctly.

We would also strongly recommend using a virtual env. You can see general install instructions here, click "virtual env" to add the additional instructions for that:

https://spacy.io/usage

**Comment by adrianeboyd** [comment]
Let me move this to installation section of the new discussion board...
