### ISSUE TITLE
ValueError: [E967] No factory meta information found for 'tagger'. This is likely a bug in spaCy.

### ISSUE THREAD

**Issue by safteinzz** [explosion/spaCy#7763]
## What i did
```
pip install spacy
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz
pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download en_core_web_sm
```

## Your Environment
![image](https://user-images.githubusercontent.com/49436581/114550010-033d2900-9c62-11eb-92fe-adacb91bea79.png)

* Operating System: win7 home
* Python Version Used: 3.7.4
* spaCy Version Used: 3.0.5
* Environment Information: Anaconda Spyder

```
Traceback (most recent call last):

  File "<ipython-input-18-d52ecac8edc0>", line 1, in <module>
    runfile('C:/Users/SaFteiNZz/Documents/GitHub/Web-Scrapping-Python/webScrap.py', wdir='C:/Users/SaFteiNZz/Documents/GitHub/Web-Scrapping-Python')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/SaFteiNZz/Documents/GitHub/Web-Scrapping-Python/webScrap.py", line 39, in <module>
    sp = spacy.load('en_core_web_sm')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\__init__.py", line 47, in load
    return util.load_model(name, disable=disable, exclude=exclude, config=config)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 322, in load_model
    return load_model_from_package(name, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 355, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)

  File "C:\ProgramData\Anaconda3\lib\site-packages\en_core_web_sm\__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 520, in load_model_from_init_py
    config=config,

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 389, in load_model_from_path
    nlp = load_model_from_config(config, vocab=vocab, disable=disable, exclude=exclude)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 432, in load_model_from_config
    validate=validate,

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 1667, in from_config
    raw_config=raw_config,

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 773, in add_pipe
    validate=validate,

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 640, in create_pipe
    pipe_meta = self.get_factory_meta(factory_name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 383, in get_factory_meta
    raise ValueError(Errors.E967.format(meta="factory", name=name))

ValueError: [E967] No factory meta information found for 'tagger'. This is likely a bug in spaCy.
```

**Comment by adrianeboyd** [comment]
Hi, this line is installing an incompatible model for spacy v3 (it's only compatible with spacy v2.2.x):

```
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz
```

Skip this line and just use `python -m spacy download en_core_web_sm` to the right version of the model automatically.

**Comment by adrianeboyd** [comment]
Let me move this to the installation section of the discussion board...
