### ISSUE TITLE
Windows 10 Anaconda Python 2.7 SSL Certificate verify failed

### ISSUE THREAD

**Issue by chrisormandy** [explosion/spaCy#784]
`C:\Users\chris>python -m spacy.en.download all
Downloading parsing model
Traceback (most recent call last):
  File "D:\Anaconda\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Anaconda\lib\site-packages\spacy\en\download.py", line 25, in <module>
    plac.call(main)
  File "D:\Anaconda\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "D:\Anaconda\lib\site-packages\plac_core.py", line 211, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "D:\Anaconda\lib\site-packages\spacy\en\download.py", line 18, in main
    download('en', force=False, data_path=data_path)
  File "D:\Anaconda\lib\site-packages\spacy\download.py", line 36, in download
    about.__models__.get(lang, lang), data_path)
  File "D:\Anaconda\lib\site-packages\sputnik\__init__.py", line 37, in install
    index.update()
  File "D:\Anaconda\lib\site-packages\sputnik\index.py", line 84, in update
    index = json.load(session.open(request, 'utf8'))
  File "D:\Anaconda\lib\site-packages\sputnik\session.py", line 43, in open
    r = self.opener.open(request)
  File "D:\Anaconda\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Anaconda\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Anaconda\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Anaconda\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "D:\Anaconda\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>`

## My Environment

* Operating System:  Windows 10
* Python Version Used: 2.7.12
* spaCy Version Used: 1.6
* Environment Information: Anaconda setup.

I can download the archive manually.

Could somebody in the know point out how we can manually download and unpack the data if a fix isn't possible.

Thanks!

**Comment by ines** [comment]
Try updating the `certifi` package, as described in [this comment](https://github.com/explosion/spaCy/issues/507#issuecomment-274473950) on #507. The solution there is for Mac, but it should probably be quite similar on Windows.

**Comment by chrisormandy** [comment]
Thanks for the reply - I did upgrade to latest -  certifi 2017.1.23. before posting as I had seen that solution on SO. This didn't fix the issue though.

**Comment by ines** [comment]
Hmm, okay, that's weird. So from comparing at the error messages people have been reporting, it looks like it's somehow related to Python + SSL, though (which seems to be a recurring source of problems, see @yakudzam's latest comment in #507).

I hope it's okay if I close this issue and we move the discussion to #507. Sorry I can't offer more help at the moment – we'll look into this in more detail, and it'll definitely be fixed in spaCy v2.0. The plan is to attach the models as binary data to the GitHub releases and finally retire the sputnik package manager.
