### ISSUE TITLE
SpaCy CLI converter issues with conll2003 NER dataset in the Latvian language

### ISSUE THREAD

**Issue by Rolands-Laucis** [explosion/spaCy#7869]
I am using spaCy for training a custom NER centered pipeline. I have 4k .conll2003 files for the Latvian language from [this repo](https://github.com/LUMII-AILab/FullStack/tree/master/NamedEntities) . It states that its file format is: 

> Format: a version of CoNLL-2003 on top of a subset of CoNLL-U
> Fields: [ID, FORM, LEMMA, UPOS, XPOS, FEATS] + [BIOTAG1, BIOTAG2, WIKI1, WIKI2]
> BIOTAG1, WIKI1: outer entity
> BIOTAG2, WIKI2: inner entity
> Tagset: person, GPE, organization, location, event, product, time, money, entity
> Wikification: experimental
They each have about 4 sentences in them.

## How to reproduce the behaviour
Using the CLI command `python -m spacy convert ..\..\datasets\NER\data\ ..\..\datasets\NER\data\` i get the error:

> Traceback (most recent call last):
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\cli\convert.py", line 78, in convert_cli
    convert(
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\cli\convert.py", line 120, in convert
    func = CONVERTERS[converter]
KeyError: 'conll2003'

In the[ spaCy CLI docs](https://spacy.io/api/cli#convert) it says "Supports CoNLL 2003 NER format." with the `--c conll` argument. Doing this gives this error:

> ✘ No input files in directory
..\..\datasets\NER\data

Using `-c ner`:

> ⚠ Can't automatically detect NER format. Conversion may not succeed. See
https://spacy.io/api/cli#convert
ℹ Grouping every 1 sentences into a document.
⚠ To generate better training data, you may want to group sentences into
documents with `-n 10`.
Traceback (most recent call last):
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\cli\convert.py", line 78, in convert_cli
    convert(
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\cli\convert.py", line 141, in convert
    db = DocBin(docs=docs, store_user_data=True)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\tokens\_serialize.py", line 79, in __init__
    for doc in docs:
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\converters\conll_ner_to_docs.py", line 109, in conll_ner_to_docs
    biluo_tags.extend(iob_to_biluo(cols[-1]))
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py", line 13, in iob_to_biluo
    out.extend(_consume_ent(tags))
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py", line 46, in _consume_ent
    raise ValueError(Errors.E177.format(tag=tag))
ValueError: [E177] Ill-formed IOB input detected: =

Then i also tried to edit the .conll2003 files and concatinate them all into 1 file. I removed the # comments in the files that were "newdoc" and "newpar". Doing this for a single or first few .conll2003 files fixes the above issue, but then gives this error:

> ⚠ Can't automatically detect NER format. Conversion may not succeed. See
https://spacy.io/api/cli#convert
ℹ Grouping every 1 sentences into a document.
⚠ To generate better training data, you may want to group sentences into
documents with `-n 10`.
Traceback (most recent call last):
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\cli\convert.py", line 78, in convert_cli
    convert(
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\cli\convert.py", line 141, in convert
    db = DocBin(docs=docs, store_user_data=True)
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\tokens\_serialize.py", line 79, in __init__
    for doc in docs:
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\converters\conll_ner_to_docs.py", line 109, in conll_ner_to_docs
    biluo_tags.extend(iob_to_biluo(cols[-1]))
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py", line 13, in iob_to_biluo
    out.extend(_consume_ent(tags))
  File "C:\Users\Experimenter\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py", line 46, in _consume_ent
    raise ValueError(Errors.E177.format(tag=tag))
ValueError: [E177] Ill-formed IOB input detected: No

After digging around, i found that in the 5th file there is this sentence, that is causing the problem:

sent_id = a-c15-p10s5
text = No tīra sudraba ir rati, no tīra zelta ir riteņi, bet riteņu spieķi mirdz varā kalti.
1	No	no	ADP	spsg	_	O	O	_	_
2	tīra	tīrs	ADJ	afmsgnp	Case=Gen|Definite=Ind|Degree=Pos|Gender=Masc|Number=Sing	O	O	_	_
3	sudraba	sudrabs	NOUN	ncmsg1	Case=Gen|Gender=Masc|Number=Sing	O	O	_	_
4	ir	būt	AUX	vcnipii30an	Evident=Fh|Mood=Ind|Person=3|Polarity=Pos|Tense=Pres|VerbForm=Fin|Voice=Act	O	O	_	_
5	rati	rats	NOUN	ncmpn1	Case=Nom|Gender=Masc|Number=Plur	O	O	_	_
6	,	,	PUNCT	zc	_	O	O	_	_
7	no	no	ADP	spsg	_	O	O	_	_
8	tīra	tīrs	ADJ	affsgnp	Case=Gen|Definite=Ind|Degree=Pos|Gender=Fem|Number=Sing	O	O	_	_
9	zelta	zelts	NOUN	ncmvg1	Case=Gen|Gender=Masc|Number=Coll	O	O	_	_
10	ir	būt	AUX	vcnipii30an	Evident=Fh|Mood=Ind|Person=3|Polarity=Pos|Tense=Pres|VerbForm=Fin|Voice=Act	O	O	_	_
11	riteņi	ritenis	NOUN	ncmpn2	Case=Nom|Gender=Masc|Number=Plur	O	O	_	_
12	,	,	PUNCT	zc	_	O	O	_	_
13	bet	bet	CCONJ	cc	_	O	O	_	_
14	riteņu	ritenis	NOUN	ncmpg2	Case=Gen|Gender=Masc|Number=Plur	O	O	_	_
15	spieķi	spieķis	NOUN	ncmpn2	Case=Nom|Gender=Masc|Number=Plur	O	O	_	_
16	mirdz	mirdzēt	VERB	vmnipi330an	Evident=Fh|Mood=Ind|Person=3|Polarity=Pos|Tense=Pres|VerbForm=Fin|Voice=Act	O	O	_	_
17	varā	vara	NOUN	ncfsl4	Case=Loc|Gender=Fem|Number=Sing	O	O	_	_
18	kalti	kalt	VERB	vmnpdmpnpsnpn	Aspect=Perf|Case=Nom|Definite=Ind|Degree=Pos|Gender=Masc|Number=Plur|Polarity=Pos|Tense=Past|VerbForm=Part|Voice=Pass	O	O	_	_
19	.	.	PUNCT	zs	_	O	O	_	_

Removing this sentence from the file resolves the issue. But just a few files more, there is another sentence that begins with "Ja" and raises the same error as above, but with this word. These are normal words in my language. My dataset for NER is already small, i do not wish to cut out large chunks of sentences and also have to do this manually.

Why is spaCy having an issue with these words? What could i do about it? I also tried lower casing all words, which resolved both of these issues, but again failed for a "_5" and also lower casing i believe would ruin the data.

## Your Environment

* Operating System: win 10 x64
## Info about spaCy
- **spaCy version:** 3.0.5
- **Platform:** Windows-10-10.0.19041-SP0
- **Python version:** 3.9.4
* Environment Information: almost fresh install of windows, not a lot of python packages or other programs.

**Comment by adrianeboyd** [comment]
Sorry, this isn't one the supported formats. You can see examples of the supported formats here:

https://github.com/explosion/spaCy/tree/df3444421aba611d4ad1238610ce189df158d85a/extra/example_data/ner_example_data

You'll either need to convert your data to a supported format or write a custom converter. Converting the data by extracting the right columns is probably the easiest choice, but if you do want to write a converter instead, here are the provided converters as examples:

https://github.com/explosion/spaCy/tree/df3444421aba611d4ad1238610ce189df158d85a/spacy/training/converters

**Comment by adrianeboyd** [comment]
Let me move this to the discussion board...
