### ISSUE TITLE
Unable to resume pretraining

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#7877]
I was running pretraining on a machine that crashed so I wanted to resume where the training left off.  However when I attempt to do so I get this error in spacy 3.0.5 
(in a conda environment on windows 10 machine)

```

(spacy3) PS C:\users\username\documents> python -m spacy pretrain config_pretrain.cfg output_pretrain --paths.raw_text rawtext_preprocessed.jsonl -r "C:\Users\username\Documents\output_pretrain" --epoch-resume 219 --gpu-id 0 --code tokenizer_rules.py
⚠ Output directory is not empty.
If you're resuming a run in this directory, the old weights for the consecutive
epochs will be overwritten with the new ones.
ℹ Using GPU: 0
ℹ Loading config from: config_pretrain.cfg
✔ Saved config file in the output directory
ℹ Resume training tok2vec from: C:\Users\username\Documents\output_pretrain
Traceback (most recent call last):
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
    command(prog_name=COMMAND)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy\cli\pretrain.py", line 70, in pretrain_cli
    pretrain(
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy\training\pretrain.py", line 44, in pretrain
    _resume_model(model, resume_path, epoch_resume, silent=silent)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy\training\pretrain.py", line 99, in _resume_model
    with resume_path.open("rb") as file_:
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\username\\Documents\\output_pretrain'
```

So then I tried to move the output files to another directory in C:\temp folder, but I got the same error.  The last file that was written is `model219.bin` so I thought maybe I have to start at 220 instead of 219, but that failed with the same error as well.  Then I decided to upgrade to spacy 3.0.0 in case it was an issue that was fixed in the most recent release.  But then after upgrade I tried again and get a different error

```
(spacy3) PS C:\users\username\documents> python -m spacy pretrain config_pretrain.cfg output_pretrain --paths.raw_text rawtext_preprocessed.jsonl -r C:\temp\resume --epoch-resume 219 --gpu-id 0 --code tokenizer_rules.py
⚠ Output directory is not empty.
If you're resuming a run in this directory, the old weights for the consecutive
epochs will be overwritten with the new ones.
ℹ Using GPU: 0
ℹ Loading config from: config_pretrain.cfg
✔ Saved config file in the output directory
Traceback (most recent call last):
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy\cli\pretrain.py", line 70, in pretrain_cli
    pretrain(
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy\training\pretrain.py", line 40, in pretrain
    model = create_pretraining_model(nlp, P)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy\training\pretrain.py", line 149, in create_pretraining_model
    tok2vec.initialize(X=[nlp.make_doc("Give it a doc to infer shapes")])
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\thinc\model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\thinc\layers\chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\thinc\model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\thinc\layers\chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\thinc\model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\thinc\layers\concatenate.py", line 132, in init
    layer.initialize(X=X, Y=Y)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\thinc\model.py", line 296, in initialize
    self.init(self, X=X, Y=Y)
  File "C:\Users\username\Miniconda3\envs\spacy3\lib\site-packages\spacy_legacy\layers\staticvectors_v1.py", line 89, in init
    model.set_param("W", init_W(model.ops, (nO, nM)))
TypeError: do_registration() takes 1 positional argument but 2 were given
```

**Comment by polm** [comment]
Moving this to discussions...
