### ISSUE TITLE
ValueError: Mismatched IDs! 57406478778838888474 vs 4311360199468911749078

### ISSUE THREAD

**Issue by mashagua** [explosion/spaCy#7885]
the error occured when i run these code:

```
with nlp.disable_pipes(*other_pipes) :

  # sizes = compounding(1.0, 4.0, 1.001)
  # Training for 30 iterations
  for itn in range(35):
    # shuffle examples before training
    random.shuffle(TRAIN_DATA)
    # batch up the examples using spaCy's minibatch
    batches = minibatch(TRAIN_DATA, size=2)
    # ictionary to store losses
    losses = {}
    for batch in batches:
        for text, annotations in batch:
            doc = nlp.make_doc(text)
            example = Example.from_dict(doc, annotations)
            # Update the model
            nlp.update([example], losses=losses, drop=0.4)
            print("Losses", losses)
```

the terminial 

```
Traceback (most recent call last):
  File "D:/all_rasa_2.5.X/spacy_related/data_utils_v2.py", line 115, in <module>
    nlp.update([example], losses=losses, drop=0.4)
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\spacy\language.py", line 1107, in update
    proc.update(examples, sgd=None, losses=losses, **component_cfg[name])
  File "spacy\pipeline\transition_parser.pyx", line 358, in spacy.pipeline.transition_parser.Parser.update
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\thinc\model.py", line 306, in begin_update
    return self._func(self, X, is_train=True)
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\spacy\ml\tb_framework.py", line 31, in forward
    step_model = ParserStepModel(
  File "spacy\ml\parser_model.pyx", line 216, in spacy.ml.parser_model.ParserStepModel.__init__
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\thinc\model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\thinc\model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\thinc\model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\spacy_transformers\layers\listener.py", line 58, in forward
    model.verify_inputs(docs)
  File "D:\all_rasa_2.5.X\venv\lib\site-packages\spacy_transformers\layers\listener.py", line 51, in verify_inputs
    raise ValueError(f"Mismatched IDs! {batch_id} vs {self._batch_id}")
ValueError: Mismatched IDs! 57406478778838888474 vs 4311360199468911749078
```

Operating System::
spacy 3.0
python 3.8
transformers 4.5
model: zh_core_web_trf

* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by svlandeg** [comment]
Hi! As a maintenance note: this is a good question for the discussions forum, so I'll move it there. The original issue will be closed and will link through to the open discussion thread.
