### ISSUE TITLE
How to train a custom entity linker?

### ISSUE THREAD

**Issue by amirj** [explosion/spaCy#7952]
I'm following [this video](https://www.youtube.com/watch?v=8u57WSXVpmw) and [this notebook](https://github.com/explosion/projects/blob/v3/tutorials/nel_emerson/notebooks/notebook_video.ipynb) to train an entity linker. It seems that they are not based on SpaCy v3. Currently, I created my KB and also prepared the training dataset in structured tuple format. Now, I'm going to train with the following script:

```python
    def train(self, epoches=1):
        """Train Entity Linker"""
        other_pipes = [pipe for pipe in self.nlp.pipe_names if pipe != "entity_linker"]
        with self.nlp.disable_pipes(*other_pipes):  # train only the entity_linker
            optimizer = self.nlp.begin_training()
            for epoch in range(epoches):
                train_dataset = self.get_doc_bin(split="trng", shuffle=True)
                batches = minibatch(
                    train_dataset, size=compounding(4.0, 32.0, 1.001)
                )  # increasing batch sizes
                losses = {}
                for batch in batches:
                    texts, annotations = zip(*batch)
                    self.nlp.update(
                        texts,
                        annotations,
                        drop=0.2,  # prevent overfitting
                        losses=losses,
                        sgd=optimizer,
                    )
                print(f"#{epoch} losses: {losses}")

```

I'm getting the following error:

```
Traceback (most recent call last):
  File "aiml_entity_linker/models/spacy_entity_linker.py", line 144, in <module>
    spacy_entity_linker.train(epoches=1)
  File "aiml_entity_linker/models/spacy_entity_linker.py", line 102, in train
    optimizer = self.nlp.begin_training()
  File "/home/amir/.conda/envs/entity-linker/lib/python3.8/site-packages/spacy/language.py", line 1192, in begin_training
    return self.initialize(get_examples, sgd=sgd)
  File "/home/amir/.conda/envs/entity-linker/lib/python3.8/site-packages/spacy/language.py", line 1224, in initialize
    I = registry.resolve(config["initialize"], schema=ConfigSchemaInit)
  File "/home/amir/.conda/envs/entity-linker/lib/python3.8/site-packages/thinc/config.py", line 727, in resolve
    resolved, _ = cls._make(
  File "/home/amir/.conda/envs/entity-linker/lib/python3.8/site-packages/thinc/config.py", line 776, in _make
    filled, _, resolved = cls._fill(
  File "/home/amir/.conda/envs/entity-linker/lib/python3.8/site-packages/thinc/config.py", line 830, in _fill
    promise_schema = cls.make_promise_schema(value, resolve=resolve)
  File "/home/amir/.conda/envs/entity-linker/lib/python3.8/site-packages/thinc/config.py", line 1021, in make_promise_schema
    func = cls.get(reg_name, func_name)
  File "/home/amir/.conda/envs/entity-linker/lib/python3.8/site-packages/spacy/util.py", line 139, in get
    raise RegistryError(
catalogue.RegistryError: [E893] Could not find function 'replace_tokenizer' in function registry 'callbacks'. If you're using a custom function, make sure the code is available. If the function is provided by a third-party package, e.g. spacy-transformers, make sure the package is installed in your environment.

Available names: spacy.copy_from_base_model.v1

```

- Operating System: MacOs
- Python Version Used: 3.8
- spaCy Version Used: 3.0.6

**Comment by amirj** [comment]
It seems that I have to use "[initialize](https://spacy.io/api/language#initialize)" instead of "begin_training" in v3 and it needs "[get_examples](https://spacy.io/api/example)" function. May I ask you to provide a sample of this function for entity linking task please?

**Comment by svlandeg** [comment]
Hi @amirj,

> I'm following this video and this notebook to train an entity linker. It seems that they are not based on SpaCy v3.

This has been an oversight on our part. The example code over at https://github.com/explosion/projects should be v3-compatible (the v2 versions are in https://github.com/explosion/projects/tree/master), but I seem to have forgotten to update the notebook in this specific repository. Since v3, there are two main ways to train your pipeline:

- Using the new [config system](https://spacy.io/usage/training#config). This is shown with the example [project](https://spacy.io/usage/projects) at https://github.com/explosion/projects/tree/v3/tutorials/nel_emerson
- Using a custom training loop, similar to how it was done in v2. I've [updated](https://github.com/explosion/projects/pull/56) the notebook to make it compatible with v3.

I will soon merge the updated notebook code into the `projects` repo, so you'll be able to check it out. In the meantime:

> It seems that I have to use "initialize" instead of "begin_training" in v3 and it needs "get_examples" function. May I ask you to provide a sample of this function for entity linking task please?

The v3 training requires `Example` objects, so the code now has something like this:
```
TRAIN_EXAMPLES = []
for text, annotation in train_dataset:
    example = Example.from_dict(nlp.make_doc(text), annotation)
    TRAIN_EXAMPLES.append(example)
```
and then you can do:
```
from spacy.ml.models import load_kb

entity_linker = nlp.add_pipe("entity_linker", config={"incl_prior": False}, last=True)
entity_linker.initialize(get_examples=lambda: TRAIN_EXAMPLES, kb_loader=load_kb(output_dir / "my_kb"))
```
or, alternatively:
```
entity_linker = nlp.add_pipe("entity_linker", config={"incl_prior": False}, last=True)
entity_linker.set_kb(your_kb_loader)
entity_linker.initialize(get_examples=lambda: TRAIN_EXAMPLES)
```
To start the training loop, you'd have:
```
with nlp.select_pipes(enable=["entity_linker"]):   # train only the entity_linker
    optimizer = nlp.resume_training()
    ...
```

There's more information in the notebook comments, but let me know if something is still unclear.

**Comment by svlandeg** [comment]
(The PR automatically closed this issue, but I'll still be following up if you have questions! Or you can start a new thread on the [forum](https://github.com/explosion/spaCy/discussions/categories/help-coding-implementations) :-))
