### ISSUE TITLE
Using pre-trained tok2vec weights runs out of memory

### ISSUE THREAD

**Issue by mbrunecky** [explosion/spaCy#8121]
## How to reproduce the behaviour
I am trying to add using pre-trained tok2vec weights to my NER training. Unfortunately, my training runs out of memory during the first iteration, trying to allocate 1.9 GB of memory after the process size exceeded ~50 GB on machine with 64 GB memory.

```
(Spacy3) C:\Work\ML\Spacy3\deploy>python -m spacy train C:\Work\ML\Spacy3\dataset\ca_placer_dee_10000_sel_7en/config_ner_pre.cfg  --output  C:\Work\ML\Spacy3\dataset\ca_placer_dee_10000_sel_7en/model_pre --paths.train C:\Work\ML\Spacy3\dataset\ca_placer_dee_10000_sel_7en/train  --paths.dev C:\Work\ML\Spacy3\dataset\ca_placer_dee_10000_sel_7en/valid --paths.raw_text C:\Work\ML\Spacy3\dataset\ca_placer_dee_10000_sel_7en/pretr --paths.init_tok2vec C:\Work\ML\Spacy3\dataset\ca_placer_dee_10000_sel_7en\pre_train\model_best.bin
ℹ Using CPU
ℹ To switch to GPU 0, use the option: --gpu-id 0
←[1m
=========================== Initializing pipeline ===========================←[0m
[2021-05-17 09:19:48,453] [INFO] Set up nlp object from config
[2021-05-17 09:19:48,469] [INFO] Pipeline: ['tok2vec', 'ner']
[2021-05-17 09:19:48,469] [INFO] Created vocabulary
[2021-05-17 09:19:51,172] [INFO] Added vectors: en_core_web_lg
[2021-05-17 09:19:51,172] [INFO] Finished initializing nlp object
[2021-05-17 09:22:13,394] [INFO] Loaded pretrained weights from C:\Work\ML\Spacy3\dataset\ca_placer_dee_10000_sel_7en\pre_train\model_best.bin
[2021-05-17 09:22:13,396] [INFO] Initialized pipeline components: ['tok2vec', 'ner']
✔ Initialized pipeline

============================= Training pipeline =============================
ℹ Pipeline: ['tok2vec', 'ner']
ℹ Initial learn rate: 0.001
E    #       LOSS TOK2VEC  LOSS NER  ENTS_F  ENTS_P  ENTS_R  SCORE
---  ------  ------------  --------  ------  ------  ------  ------
⚠ Aborting and saving the final best model. Encountered exception:
MemoryError((665364, 768), dtype('float32'))
Traceback (most recent call last):
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\training\loop.py", line 115, in train
    raise e
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\training\loop.py", line 98, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\training\loop.py", line 213, in train_while_improving
    score, other_scores = evaluate()
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\training\loop.py", line 268, in evaluate
    scores = nlp.evaluate(dev_corpus(nlp))
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\language.py", line 1355, in evaluate
    for doc, eg in zip(
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\util.py", line 1484, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy\pipeline\trainable_pipe.pyx", line 79, in pipe
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\util.py", line 1503, in raise_error
    raise e
  File "spacy\pipeline\trainable_pipe.pyx", line 75, in spacy.pipeline.trainable_pipe.TrainablePipe.pipe
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\pipeline\tok2vec.py", line 121, in predict
    tokvecs = self.model.predict(docs)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\layers\with_array.py", line 40, in forward
    return _list_forward(cast(Model[List2d, List2d], model), Xseq, is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\layers\with_array.py", line 76, in _list_forward
    Yf, get_dXf = layer(Xf, is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\layers\residual.py", line 40, in forward
    Y, backprop_layer = model.layers[0](X, is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Work\ML\Spacy3\lib\site-packages\thinc\layers\expand_window.py", line 23, in forward
    Y = model.ops.seq2col(X, nW)
  File "thinc\backends\numpy_ops.pyx", line 191, in thinc.backends.numpy_ops.NumpyOps.seq2col
  File "thinc\backends\numpy_ops.pyx", line 78, in thinc.backends.numpy_ops.NumpyOps.alloc
numpy.core._exceptions.MemoryError: Unable to allocate 1.90 GiB for an array with shape (665364, 768) and data type float32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Work\ML\Spacy3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Work\ML\Spacy3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Work\ML\Spacy3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Work\ML\Spacy3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Work\ML\Spacy3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Work\ML\Spacy3\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\cli\train.py", line 59, in train_cli
    train(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\training\loop.py", line 119, in train
    save_checkpoint(False)
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\training\loop.py", line 67, in save_checkpoint
    before_to_disk(nlp).to_disk(output_path / DIR_MODEL_LAST)
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\language.py", line 1833, in to_disk
    util.to_disk(path, serializers, exclude)
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\util.py", line 1163, in to_disk
    writer(path / key)
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\language.py", line 1832, in <lambda>
    serializers["vocab"] = lambda p: self.vocab.to_disk(p)
  File "spacy\vocab.pyx", line 464, in spacy.vocab.Vocab.to_disk
  File "spacy\vectors.pyx", line 396, in spacy.vectors.Vectors.to_disk
  File "C:\Work\ML\Spacy3\lib\site-packages\spacy\util.py", line 1163, in to_disk
    writer(path / key)
  File "spacy\vectors.pyx", line 393, in spacy.vectors.Vectors.to_disk.lambda3
  File "spacy\vectors.pyx", line 389, in spacy.vectors.Vectors.to_disk.save_vectors
  File "spacy\vectors.pyx", line 390, in spacy.vectors.Vectors.to_disk.save_vectors
  File "spacy\vectors.pyx", line 381, in spacy.vectors.Vectors.to_disk.lambda1
  File "<__array_function__ internals>", line 5, in save
  File "C:\Work\ML\Spacy3\lib\site-packages\numpy\lib\npyio.py", line 529, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File "C:\Work\ML\Spacy3\lib\site-packages\numpy\lib\format.py", line 687, in write_array
    array.tofile(fp)
OSError: 205449000 requested and 0 written
Done C:\Work\ML\Spacy3\dataset\ca_placer_dee_10000_sel_7en
"Start  9:19:45.57 stop  9:25:25.95"

```

On a minor note, I do NOT understand why (when running with -paths.init_tok2vec modelNN.bin) I am required to also provide path for rawtext=--paths.raw_text raw_text_dir. Else the corpus.pretrain initialization fails, despite running just the **training**, not pretrain.

I am afraid the problem is triggered by my OCR-generated data. My raw_text (7800 files, 22.6 MB = 2,900 chars/file) contains very frequent OOV 'words': various OCR miss-spelling and/or outright 'garbage'. Per my count, this training data set contains about 5,130,000 'words', where 178,380 are 'distinct' but out of that only 16,775 has a frequency 5 or higher.
My pre-training run would never end (I let it run for several days, and stopped after epoch 46):
```
{"nr_word":5129976,"loss":7426313.0900878906,"epoch_loss":7426313.0900878906,"epoch":0}
...
{"nr_word":241108872,"loss":141515257.969909668,"epoch_loss":2612238.9136352539,"epoch":46}
```
The resulting modelNN,bin files are pretty stable at about 28,591 KB.

Unfortunately, looking at the relevant section of config.cfg, I do not see **what I could do to eliminate the OOV words from the training**:

```
[corpora.pretrain]
@readers = "spacy.JsonlCorpus.v1"
path = ${paths.raw_text}
min_length = 5
max_length = 0
limit = 0

[pretraining]
max_epochs = 1000
dropout = 0.2
n_save_every = null
component = "tok2vec"
layer = ""
corpus = "corpora.pretrain"

[pretraining.batcher]
@batchers = "spacy.batch_by_words.v1"
size = 3000
discard_oversize = false
tolerance = 0.2
get_length = null

[pretraining.objective]
@architectures = "spacy.PretrainCharacters.v1"
maxout_pieces = 3
hidden_size = 300
n_characters = 4

[pretraining.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = true
eps = 0.00000001
learn_rate = 0.001 

```

## Your Environment
* Operating System:      Windows 10
* Python Version Used:  3.8
* spaCy Version Used:    3.0.6
* Environment Information:   20 core CPU, 64 GB memory

**Comment by mbrunecky** [comment]
It turns out to be a plain resource issue:
Changing batch_size=1000 down to batch_size=400 solves the problem for me. With this dataset, I can probably go higher, 600 or more, because the max process size reaches about 22GB (for batch_size=400).

On the 'misc' issue of having to supply a non-Null  -paths.raw_text for spacy train (when using config.cfg generated including pre-training) along with -paths.init_tok2vec:
_I would assume it is an oversight - the check for non-Null raw_text should be skipped in regular training run.
I can specify a bogus (non-existent directory) paths.raw_text and it makes spacy train command happy._
