### ISSUE TITLE
spacy ray missing max_epochs argument.

### ISSUE THREAD

**Issue by Julia-Penfield** [explosion/spaCy#8137]
I am trying to use spacy ray to train an NER model - eventually I will be using more vCPU cores as well as GPUs.

Without the use of ray, I can successfully train the NER model using:

!python -m spacy train config.cfg --output ./output

I have installed ray and tested it using "!python -m spacy ray --help" which returns:

    Usage: python -m spacy ray [OPTIONS] COMMAND [ARGS]...

      CLI for parallel and distributed computing via Ray. See the Ray
      documentation for details: https://ray.io.

    Options:
      --help  Show this message and exit.

    Commands:
      train  Train a spaCy pipeline using Ray for parallel training.
    ​
So far so good. Then I use the following to train the model, this time using 2 vCPU cores:

!python -m spacy ray train config.cfg --n-workers 2 --output ./output

Below is the error message:

    ℹ Using CPU
    ℹ To switch to GPU 0, use the option: --gpu-id 0
    2021-05-18 18:29:29,031	INFO resource_spec.py:231 -- Starting Ray with 35.16 GiB memory available for workers and up to 17.6 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
    2021-05-18 18:29:30,175	INFO services.py:1193 -- View the Ray dashboard at localhost:8265
    Traceback (most recent call last):
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/spacy/__main__.py", line 4, in <module>
        setup_cli()
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/spacy/cli/_util.py", line 69, in setup_cli
        command(prog_name=COMMAND)
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
        return callback(**use_params)  # type: ignore
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/spacy_ray/train_cli.py", line 52, in ray_train_cli
        code_path=code_path,
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/spacy_ray/train_cli.py", line 87, in ray_train
        ray.get(worker.train.remote(workers, evaluator))
      File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ray/worker.py", line 1538, in get
        raise value.as_instanceof_cause()
    ray.exceptions.RayTaskError(TypeError): ray::Worker.train() (pid=5175, ip=172.16.14.165)
      File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
      File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
    TypeError: create_train_batches() missing 1 required positional argument: 'max_epochs'

I looked at the ray code in (https://github.com/explosion/spacy-ray/blob/75cdb637411529f7f0a41c723a8ab71cbae9cc79/spacy_ray/worker.py#L251-L259) and it looks like the problem is in:

    train_batches = create_train_batches(
        self.train_corpus(self.nlp),
        self.T["batcher"],
        self.T["max_epochs"],

self.T is defined as:

        self.T = registry.resolve(config["training"], schema=ConfigSchemaTraining)

So I looked at my config.cfg file to see what's in config["training"] and here it is:

    [training]
    dev_corpus = "corpora.dev"
    train_corpus = "corpora.train"
    seed = ${system.seed}
    gpu_allocator = ${system.gpu_allocator}
    dropout = 0.1
    accumulate_gradient = 1
    patience = 1600
    max_epochs = 0
    max_steps = 20000
    eval_frequency = 200
    frozen_components = []
    before_to_disk = null

It is right there!! Says "max_epochs = 0." 

So, I cannot find the missing argument. Does anyone know what I am missing? Any ideas please?

## My Environment

All of the code above is in one conda_python3 notebook on AWS Sagemaker using ml.p3.2xlarge EC2 instance.

Python Version Used: 3

spaCy Version Used: 3.0.6

**Comment by adrianeboyd** [comment]
Hi, this is a bug in `spacy-ray`. It hasn't been updated for spacy v3.0.6 yet. You can use spacy v3.0.5 in the meanwhile, or have a look at the minimal changes required: https://github.com/explosion/spacy-ray/pull/8

**Comment by adrianeboyd** [comment]
Fixed in `spacy-ray` v0.1.2.

**Comment by Julia-Penfield** [comment]
You are so good @adrianeboyd! Thank-you! :)
