### ISSUE TITLE
Attempting to train TextCategorizer crashes

### ISSUE THREAD

**Issue by Mlallena** [explosion/spaCy#8215]
I am trying to create a text categorizer for sentiment analysis purposes in Spanish, but I get several errors.

The first happens when I attempt to create _config.cfg_ from _base_config.cfg_, as suggested in the Quickstart guide. This error is only averted when I change the value **@architectures** in **[components.tok2vec.model.embed]** from "spacy.MultiHashEmbed.v2" to "spacy.MultiHashEmbed.v1".
`Traceback (most recent call last):
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\init_config.py", line 85, in init_fill_config_cli
    fill_config(output_file, base_path, pretraining=pretraining, diff=diff)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\init_config.py", line 101, in fill_config
    nlp = util.load_model_from_config(config, auto_fill=True, validate=False)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\util.py", line 432, in load_model_from_config
    validate=validate,
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\language.py", line 1659, in from_config
    raw_config=raw_config,
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\language.py", line 772, in add_pipe
    validate=validate,
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\language.py", line 658, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc\config.py", line 728, in resolve
    config, schema=schema, overrides=overrides, validate=validate, resolve=True
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc\config.py", line 777, in _make
    config, schema, validate=validate, overrides=overrides, resolve=resolve
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc\config.py", line 837, in _fill
    overrides=overrides,
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc\config.py", line 837, in _fill
    overrides=overrides,
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc\config.py", line 830, in _fill
    promise_schema = cls.make_promise_schema(value, resolve=resolve)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc\config.py", line 1021, in make_promise_schema
    func = cls.get(reg_name, func_name)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\util.py", line 141, in get
    ) from None
catalogue.RegistryError: [E893] Could not find function 'spacy.MultiHashEmbed.v2' in function registry 'architectures'. If you're using a custom function, make sure the code is available. If the function is provided by a third-party package, e.g. spacy-transformers, make sure the package is installed in your environment.`

The other error happens when I attempt to start the training of the model with the command "python -m spacy train config.cfg --paths.train ./train.spacy --paths.dev ./dev.spacy", as suggested in the tutorial. Here, I get this error.

`=========================== Initializing pipeline ===========================
Set up nlp object from config
Pipeline: ['tok2vec', 'textcat']
Created vocabulary
Finished initializing nlp object
Traceback (most recent call last):
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\training\initialize.py", line 70, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer, link_components=False)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\language.py", line 1249, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "C:\Users\lalarqmi.COMUNY\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\pipeline\tok2vec.py", line 213, in initialize
    assert doc_sample, Errors.E923.format(name=self.name)
**AssertionError: [E923] It looks like there is no proper sample data to initialize the Model of component 'tok2vec'. This is likely a bug in spaCy**, so feel free to open an issue: https://github.com/explosion/spaCy/issues`

## How to reproduce the behaviour
Follow the instructions shown in https://spacy.io/usage/training. Make sure to transform your data into .spicy objects, by using the _convert_ command (if you are starting with JSON, make sure the JSON has each document in a different line).

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7.7
* spaCy Version Used: 3.0.0

**Comment by svlandeg** [comment]
Hi! As a maintenance note: this is a good question for the discussions forum, so I'll move it there. The original issue will be closed and will link through to the open discussion thread.
