### ISSUE TITLE
untimeError: [E039] Array bounds exceeded while searching for root word while using own .conllu to spacy doc converter

### ISSUE THREAD

**Issue by gakonorde** [explosion/spaCy#8293]
Hey. I encountered a problem with visualization via displacy while using spacy doc object generated from conllu file. Here is the full traceback:

```
vis_conllu(r'C:\Other Developments\conllu_1-100\new_2.conllu')
vis_conlluTraceback (most recent call last):
  Python Shell, prompt 2, line 1
    # Used internally for debug sandbox under external interpreter
  File "C:\Users\G. Kostenko\AppData\Local\Programs\Python\Python37\Lib\site-packages\ganalyzer.py", line 1363, in vis_conllu
    displacy.serve(doc, style="dep")
  File "C:\Users\G. Kostenko\AppData\Local\Programs\Python\Python37\Lib\site-packages\spacy\displacy\__init__.py", line 96, in serve
    render(docs, style=style, page=page, minify=minify, options=options, manual=manual)
  File "C:\Users\G. Kostenko\AppData\Local\Programs\Python\Python37\Lib\site-packages\spacy\displacy\__init__.py", line 53, in render
    parsed = [converter(doc, options) for doc in docs] if not manual else docs
  File "C:\Users\G. Kostenko\AppData\Local\Programs\Python\Python37\Lib\site-packages\spacy\displacy\__init__.py", line 53, in <listcomp>
    parsed = [converter(doc, options) for doc in docs] if not manual else docs
  File "C:\Users\G. Kostenko\AppData\Local\Programs\Python\Python37\Lib\site-packages\spacy\displacy\__init__.py", line 148, in parse_deps
    retokenizer.merge(span, attrs=attrs)
  File "C:\Users\G. Kostenko\AppData\Local\Programs\Python\Python37\Lib\site-packages\spacy\tokens\_retokenize.cp37-win_amd64.pyd", line 120, in spacy.tokens._retokenize.Retokenizer.__exit__
    H)uHAÿP0H
ÿtH/u
  File "C:\Users\G. Kostenko\AppData\Local\Programs\Python\Python37\Lib\site-packages\spacy\tokens\_retokenize.cp37-win_amd64.pyd", line 181, in spacy.tokens._retokenize._merge
    HÕAÿÖ
Àu_H\000\000\000H
Ét
  File "C:\Users\G. Kostenko\AppData\Local\Programs\Python\Python37\Lib\site-packages\spacy\tokens\span.cp37-win_amd64.pyd", line 578, in spacy.tokens.span.Span.root.__get__
    HCHËÿP0H
  File "C:\Users\G. Kostenko\AppData\Local\Programs\Python\Python37\Lib\site-packages\spacy\tokens\span.cp37-win_amd64.pyd", line 760, in spacy.tokens.span._count_words_to_root
    Ù¦\000è|ÊÿÿHm§\000H
ÀÙ\000\000\000H
builtins.RuntimeError: [E039] Array bounds exceeded while searching for root word. This likely means the parse tree is in an invalid state. Please report this issue here: http://github.com/explosion/spaCy/issues
```

Obviously, the problem is caused by the way I'm creating a doc object. I asked how to do that some time ago, and then slightly modified the proposed code.

- GitHub Discussions: https://github.com/explosion/spaCy/issues/5600

So, here is how I try to visualize:

```
def vis_conllu(conllu_dir):
    
    print('vis_conllu')
    
    with open(conllu_dir, encoding="UTF-8") as file:
        string = file.read()
    
    doc = from_conllu(string)
    
    displacy.serve(doc, style="dep")
```

Here is what `from_conllu` means:

```
def from_conllu(conllu_string):
    
    nlp = spacy.blank("de")
    
    doc = doc_from_conllu(nlp.vocab, conllu_string)
    
    return doc
```

Here is how I get doc from conllu:

```
import spacy
from spacy.tokens import Doc

def doc_from_conllu(vocab, raw_conllu):
    
    words, spaces, tags, poses, morphs, lemmas = [], [], [], [], [], []
    heads, deps = [], []
    
    lines = raw_conllu.split('\n')
    lines = [i for i in lines if len(i) is not 0 and not i.startswith('#') and i not in ['\r']]
    
    token_id = 0
    
    for i in range(len(lines)):
        line = lines[i]
        parts = line.split("\t")
        original_id, word, lemma, pos, tag, morph, head, dep, _1, misc = parts
        if "." in original_id or "-" in original_id:
            continue
        if "SpaceAfter=No" in misc:
            spaces.append(False)
        else:
            spaces.append(True)

        head = token_id + (int(head) - int(original_id))
        tag = pos if tag == "_" else tag
        morph = morph if morph != "_" else ""
        dep = "ROOT" if dep == "root" else dep

        words.append(word)
        lemmas.append(lemma)
        poses.append(pos)
        tags.append(tag)
        morphs.append(morph)
        heads.append(head)
        deps.append(dep)
        
        token_id += 1

    doc = Doc(vocab, words=words, spaces=spaces)
    
    for i in range(len(doc)):
        doc[i].tag_ = tags[i]          
        doc[i].pos_ = poses[i]
        doc[i].dep_ = deps[i]
        doc[i].lemma_ = lemmas[i]
        doc[i].head = doc[heads[i]]
    doc.is_parsed = True
    doc.is_tagged = True

    return doc
```

... and where, I guess, the problem originates from. Could you advise why the root cannot be located? Is it somehow connected to the sent_id?.. And how to fix it?

- Operating System: WIn10
- Python Version Used: 3.7

**Comment by polm** [comment]
Since this seems to be an issue with your code, and not a bug, I'm going to move it to a Discussion. Follow the link to check the Discussion.
