### ISSUE TITLE
Installing universal sentence encoder now causes errors

### ISSUE THREAD

**Issue by marc-poweruser** [explosion/spaCy#8332]
Without having changed my config file, data, etc., today I'm getting errors when I try to use spacy to either debug my config file or train on the data.  The errors disappear if I don't install spacy-universal-sentence-encoder.  I've pasted the error messaging below.

I was successfully using the sentence encoder until today.  The only thing I can think of is that a new version was released and started causing problems.  When I tried reverting to an older version, I ran into compatibility issues with other installed packages.  It would be quite a tangle to unravel to figure out a combo that works, if that's even the issue.

The custom_pipe.py file referred to below contains the code for my custom pipeline components, which hasn't changed .  It seems to be throwing an error at the first use of a language factory in my code.

Any ideas what's going on?

`2021-06-10 00:15:17.401305: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

============================= Config validation =============================
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/opt/conda/lib/python3.6/site-packages/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.6/site-packages/spacy/cli/debug_config.py", line 42, in debug_config_cli
    config_path, overrides=overrides, show_funcs=show_funcs, show_vars=show_vars
  File "/opt/conda/lib/python3.6/site-packages/spacy/cli/debug_config.py", line 56, in debug_config
    nlp = util.load_model_from_config(config)
  File "/opt/conda/lib/python3.6/site-packages/spacy/util.py", line 434, in load_model_from_config
    validate=validate,
  File "/opt/conda/lib/python3.6/site-packages/spacy/language.py", line 1639, in from_config
    nlp = lang_cls(vocab=vocab, create_tokenizer=create_tokenizer, meta=meta)
  File "/opt/conda/lib/python3.6/site-packages/spacy/language.py", line 150, in __init__
    util.registry._entry_point_factories.get_all()
  File "/opt/conda/lib/python3.6/site-packages/catalogue/__init__.py", line 108, in get_all
    result.update(self.get_entry_points())
  File "/opt/conda/lib/python3.6/site-packages/catalogue/__init__.py", line 123, in get_entry_points
    result[entry_point.name] = entry_point.load()
  File "/opt/conda/lib/python3.6/site-packages/catalogue/_importlib_metadata/__init__.py", line 94, in load
    module = import_module(match.group('module'))
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.6/site-packages/spacy_universal_sentence_encoder/__init__.py", line 13, in <module>
    from . import language
  File "/opt/conda/lib/python3.6/site-packages/spacy_universal_sentence_encoder/language.py", line 7, in <module>
    import tensorflow_hub as hub
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 85, in <module>
    _ensure_tf_install()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 49, in _ensure_tf_install
    import tensorflow as tf
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/experimental/__init__.py", line 99, in <module>
    from tensorflow.python.data.experimental import service
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 140, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 25, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/util/structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 40, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/sparse_tensor.py", line 28, in <module>
    from tensorflow.python.framework import constant_op
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 28, in <module>
    from tensorflow.python.framework import ops
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 26, in <module>
    from absl import app
  File "/opt/conda/lib/python3.6/site-packages/absl/app.py", line 35, in <module>
    import pdb
  File "/opt/conda/lib/python3.6/pdb.py", line 76, in <module>
    import code
  File "/root/pipeline-training/code/__init__.py", line 1, in <module>
    import build_kbs
  File "/root/pipeline-training/code/build_kbs.py", line 10, in <module>
    import custom_pipe # needed for spacy.load()
  File "/root/pipeline-training/code/custom_pipe.py", line 41, in <module>
    @Language.factory("arg_vals")
  File "/opt/conda/lib/python3.6/site-packages/spacy/language.py", line 466, in add_factory
    if not util.is_same_func(factory_func, existing_func):
  File "/opt/conda/lib/python3.6/site-packages/spacy/util.py", line 938, in is_same_func
    same_file = inspect.getfile(func1) == inspect.getfile(func2)
  File "/opt/conda/lib/python3.6/inspect.py", line 654, in getfile
    raise TypeError('{!r} is a built-in class'.format(object))
TypeError: None is a built-in class`

## Your Environment

Running on Sagemaker Studio

## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** Linux-4.14.231-173.361.amzn2.x86_64-x86_64-with-debian-buster-sid
- **Python version:** 3.6.13`

**Comment by marc-poweruser** [comment]
It may be a circular dependency issue because removing some dependencies from my __init__.py seems to help.  But I'm confused why it worked before if that's the case and why the sentence encoder import makes a difference.
Also, I just realized I think spacy-universal-sentence-encoder is a third-party package, so I understand if you can't answer this one.  But any insight would be appreciated.

**Comment by polm** [comment]
You're right that this is third party so we're a little limited in the help we can provide.

Since this isn't a bug I'm going to move it to a discussion.
