### ISSUE TITLE
Do you have issues in compiling Spacy on Centos7?

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#8346]
I am using Spacy 2.3 and CentOS. Ubuntu is compiling file without the problem. Cython 0.29. It always complaints about the absence of cython. The error message is below:

```
$ sudo python setup.py build_ext --inplace
Cythonizing sources
Processing token.pyx
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 840, in setuptools_main
    return main(command_line = 1)
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 858, in main
    result = compile(sources, options)
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 780, in compile
    return compile_multiple(source, options)
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 750, in compile_multiple
    context = options.create_context()
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 597, in create_context
    self.cplus, self.language_level, options=self)
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 80, in __init__
    from . import Builtin, CythonScope
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "Cython/Compiler/Visitor.py", line 12, in init Cython.Compiler.Visitor
  File "/usr/local/lib/python3.7/inspect.py", line 40, in <module>
    import linecache
  File "/usr/local/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.7/tokenize.py", line 35, in <module>
    from token import *
  File "token.pyx", line 1, in init spacy.tokens.token
    # cython: infer_types=True
  File "/usr/local/lib/python3.7/site-packages/numpy/__init__.py", line 152, in <module>
    from . import random
  File "/usr/local/lib/python3.7/site-packages/numpy/random/__init__.py", line 181, in <module>
    from . import _pickle
  File "/usr/local/lib/python3.7/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "_bit_generator.pxd", line 14, in init numpy.random.mtrand
  File "_bit_generator.pyx", line 255, in init numpy.random._bit_generator
AttributeError: type object 'numpy.random._bit_generator.SeedSequence' has no attribute '__reduce_cython__'
Traceback (most recent call last):
  File "/data0/congmin/wb-nlp-tool/spaCy-weibo/bin/cythonize.py", line 60, in process_pyx
    ["cython"] + flags + ["-o", tofile, fromfile], env=os.environ
  File "/usr/local/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cython': 'cython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data0/congmin/wb-nlp-tool/spaCy-weibo/bin/cythonize.py", line 169, in <module>
    run(args.root)
  File "/data0/congmin/wb-nlp-tool/spaCy-weibo/bin/cythonize.py", line 158, in run
    process(base, filename, db)
  File "/data0/congmin/wb-nlp-tool/spaCy-weibo/bin/cythonize.py", line 124, in process
    preserve_cwd(base, process_pyx, root + ".pyx", root + ".cpp")
  File "/data0/congmin/wb-nlp-tool/spaCy-weibo/bin/cythonize.py", line 87, in preserve_cwd
    func(*args)
  File "/data0/congmin/wb-nlp-tool/spaCy-weibo/bin/cythonize.py", line 78, in process_pyx
    raise Exception("Cython failed")
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 199, in <module>
    setup_package()
  File "setup.py", line 187, in setup_package
    generate_cython(root, "spacy")
  File "setup.py", line 114, in generate_cython
    raise RuntimeError("Running cythonize failed")
RuntimeError: Running cythonize failed



```

My gcc:
```
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
```

I also tried a conda environment which uses python 3.8 and gcc 7.5. The issue remains. Mac and Ubuntu compile fine.

**Comment by polm** [comment]
It's been a while since I regularly used CentOS but my impression is that they value stability very highly, to the point they end up with packages several years out of date. This is a poor fit for modern machine learning packages, which often rely on new hardware features. 

I'm not certain that using a version of GCC from 2015 is the source of your problem, but it definitely sounds like it could be an issue. I couldn't find information about what version of GCC Cython requires.

Some questions:

1. For perspective, can you clarify why you're trying to build spaCy from source instead of installing a wheel?
2. Are you able to build any other Cython projects? 
3. Are you absolutely certain you have the `cython` binary in your PATH? Because the error suggests it's not there.

This is the error of interest:

    FileNotFoundError: [Errno 2] No such file or directory: 'cython': 'cython'

**Comment by polm** [comment]
OK, I used a CentOS 7 Docker image to test this. By default it does try to build spaCy from source, but it turns out this is just because the version of pip installed by default is old. If you upgrade pip it will use the wheel and can be installed as normal. 

You can upgrade pip like this on CentOS7:

    pip3 install -U pip

I assume you were building from source because that's what pip defaulted to, and therefore installing wheels resolves your issue, but if you have another reason for doing so let me know.

**Comment by lingvisa** [comment]
@polm I had minor changes on the source code so I need to compile from the source. I am wondering why Mac and Ubuntu don't have this issue. Can you try whether you can reproduce the cython error message on CentOS 7? For example, it might be due to low version of GCC.

**Comment by adrianeboyd** [comment]
This error looks related to the cython installation rather than gcc, although be aware that this gcc version isn't supported by the latest versions of `blis`, so you'd need to use v0.4.1 instead: https://github.com/explosion/cython-blis/issues/49

**Comment by adrianeboyd** [comment]
Looking at the error again, you might want to try upgrading numpy?

**Comment by lingvisa** [comment]
I installed blis=0.41 and number=1.20.0, but no success.  I am now in a Python38 conda environment and upgrade the gcc to latest version, but got the same issue. Normally, where is the cython located while it complains  "No such file or directory": 'cython': 'cython'?  My cython is here when I use conda:

```
$ which cython
~/.conda/envs/py38/bin/cython
```

**Comment by polm** [comment]
I was able to build spaCy on CentOS 7 without issue after some prep. I did not use conda.

```
yum groupinstall Development Tools
yum -y install python3 python3-devel
python3 -m pip install -U pip setuptools wheel virtualenv cython
# inside virtualenv
pip install -r requirements.txt
pip install --no-build-isolation --editable .
```

Except for the groupinstall that I found only after some compilation issues I didn't have to do anything unusual, though I was confused and alarmed to find that `which` didn't work. Maybe if you use the `groupinstall` command it'll work?

**Comment by lingvisa** [comment]
I still fail to get it compiled. I will switch to Ubuntu for this machine. Thanks for the verification and info.

**Comment by polm** [comment]
Sorry I couldn't be of more help, good luck with your project!
