### ISSUE TITLE
spacy.load('en') Memory Error

### ISSUE THREAD

**Issue by tlhampton13** [explosion/spaCy#837]
## Description
Spacy failing with the following memory error when calling spacy.load('en').

## Traceback
Traceback (most recent call last):
File "/data/eddi/lib/eddi/etl/spacyio/spacy_io.py", line 248, in <module>
  main(sys.argv[1:])
File "/data/eddi/lib/eddi/etl/spacyio/spacy_io.py", line 232, in main
  npe = SpacyIoExtractor(doc_type, actions, config)
File "/data/eddi/lib/eddi/etl/spacyio/spacy_io.py", line 64, in __init__
  self.nlp = spacy.load('en')
File "/usr/local/lib64/python3.5/site-packages/spacy/__init__.py", line 42, in load
  return cls(**overrides)
File "/usr/local/lib64/python3.5/site-packages/spacy/en/__init__.py", line 34, in __init__
  Language.__init__(self, **overrides)
File "/usr/local/lib64/python3.5/site-packages/spacy/language.py", line 283, in __init__
  if 'parser' not in overrides \
File "/usr/local/lib64/python3.5/site-packages/spacy/language.py", line 110, in create_parser
  return DependencyParser.load(nlp.path / 'deps', nlp.vocab, **cfg)
File "spacy/syntax/parser.pyx", line 99, in spacy.syntax.parser.Parser.load (spacy/syntax/parser.cpp:5426)
File "thinc/linear/avgtron.pyx", line 95, in thinc.linear.avgtron.AveragedPerceptron.load (thinc/linear/avgtron.cpp:3200)
File "preshed/maps.pyx", line 23, in preshed.maps.PreshMap.__init__ (preshed/maps.cpp:1200)
File "preshed/maps.pyx", line 90, in preshed.maps.map_init (preshed/maps.cpp:2876)
File "cymem/cymem.pyx", line 42, in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1091)
2017-02-16 03:10:31 +0000 -- : Error: MemoryError: Error assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytes

## Your Environment
AWS EC2 (m4.large, 64-bit, AWS Linux)
Python 3.5 (64-bit)
Spacy 1.6.0

## Memory
> free -m -t -g
                       total       used       free     shared    buffers     cached
Mem:                    7            0            6              0              0              0
-/+ buffers/cache:             0            7
Swap:                   0            0            0
Total:                    7            0            6

## pip list
> pip3 list
You are using pip version 6.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
cloudpickle (0.2.2)
cymem (1.31.2)
cytoolz (0.8.2)
flexmock (0.10.2)
murmurhash (0.26.4)
numpy (1.12.0)
pathlib (1.0.1)
pip (6.1.1)
plac (0.9.6)
preshed (0.46.4)
PyYAML (3.12)
semver (2.7.5)
setuptools (12.2)
six (1.10.0)
spacy (1.6.0)
sputnik (0.9.3)
thinc (6.2.0)
toolz (0.8.2)
tqdm (4.11.2)
ujson (1.35)
virtualenv (12.0.7)

**Comment by tlhampton13** [comment]
I noticed that the memory is bleeding down to 0 before the failure.  How much memory does Spacy need to load the 'en' data?

**Comment by tlhampton13** [comment]
Ok, I was kicking off more than one instance concurrently and this is why I ran out of memory.  You can close this issue since the problem was on my end.
