### ISSUE TITLE
Tok2Vec listener is not able to receive valid input from Tok2Vec (when using pretrained weights for tok2vec)

### ISSUE THREAD

**Issue by parinaya-007** [explosion/spaCy#8549]
## Description

I pre-trained tok2vec using the following [config](#config). I got the _model999.bin_ weights file after successful pre-training for 1000 epochs.
Then I am trying to train NER using pre-trained tok2vec weights using the following [config](#config).

Since I have small data for training NER, I aim to freeze tok2vec weights and make them non-trainable. To achieve this, I included "tok2vec" in _frozen_components_. So that while training NER, tok2vec weights would be freezed and gradients would not go upstream through tok2vec listener while learning.

But in doing so I am getting ```ValueError: [E954] The Tok2Vec listener did not receive any valid input from an upstream component.``` [error](#error). Please suggest what should I do to make tok2vec (with pre-trained weights) non-trainable without facing this error.

## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** Windows-10-10.0.17134-SP0
- **Python version:** 3.7.3
- **Pipelines:** en_core_web_md (3.0.0), en_core_web_sm (3.0.0)

## Commands used

For training NER :
```
python -m spacy train config_pretrain.cfg --output ner_pretrained_frozen_tok2vec --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy --paths.init_tok2vec pretrained_tok2vec/model999.bin --training.eval_frequency 2 --training.max_steps 100
```

## <a name="config"> Config used for pretraining tok2vec and training NER </a>

```
[paths]
train = null
dev = null
vectors = null
init_tok2vec = null
raw_text = null

[system]
seed = 0
gpu_allocator = null

[nlp]
lang = "en"
pipeline = ["tok2vec","ner"]
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
batch_size = 1000
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

# -------------------- NER ----------------------
[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = true
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}
upstream = "*"

# -------------------- END NER ----------------------

# -------------------- TOK2VEC ----------------------
[components.tok2vec]
factory = "tok2vec"

[components.tok2vec.model]
@architectures = "spacy.Tok2Vec.v2"

[components.tok2vec.model.embed]
@architectures = "spacy.MultiHashEmbed.v2"
width = ${components.tok2vec.model.encode.width}
attrs = ["ORTH","NORM","PREFIX","SUFFIX","SHAPE"]
rows = [1000,500,500,500,500]
include_static_vectors = false

[components.tok2vec.model.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 96
depth = 4
window_size = 1
maxout_pieces = 3

# -------------------- END TOK2VEC ----------------------

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
gold_preproc = false
max_length = 0
limit = 0
augmenter = null


# [corpora.pretrain]
# @readers = "spacy.JsonlCorpus.v1"
# path = ${paths.raw_text}
# min_length = 5
# max_length = 500
# limit = 0

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
gold_preproc = false
max_length = 2000
limit = 0
augmenter = null

[training]
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.2
accumulate_gradient = 1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 100
frozen_components = ["tok2vec"]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

# [training.logger]
# @loggers = "spacy.ConsoleLogger.v1"
# progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.15
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]
ents_per_type = null
ents_f = 0.66
ents_p = 0.17
ents_r = 0.17

[pretraining]
max_epochs = 2
dropout = 0.2
n_save_every = null
component = "tok2vec"
layer = ""
corpus = "corpora.pretrain"

[pretraining.batcher]
@batchers = "spacy.batch_by_words.v1"
size = 3000
discard_oversize = false
tolerance = 0.2
get_length = null

[pretraining.objective]
@architectures = "spacy.PretrainCharacters.v1"
maxout_pieces = 3
hidden_size = 300
n_characters = 4

[pretraining.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = true
eps = 0.00000001
learn_rate = 0.001

[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]

[training.logger]
@loggers = "spacy.WandbLogger.v2"
project_name = "monitor_ner_pretrained_frozen_tok2vec_training"
remove_config_values = []
log_dataset_dir = "corpus"
model_log_interval = 100
```

##  <a name="error"> Error Stacktrace </a>

```
Traceback (most recent call last):
  File "C:\Users\parinaya.chaturvedi\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\parinaya.chaturvedi\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\cli\train.py", line 59, in train_cli
    train(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\training\loop.py", line 115, in train
    raise e
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\training\loop.py", line 98, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\training\loop.py", line 196, in train_while_improving
    subbatch, drop=dropout, losses=losses, sgd=False, exclude=exclude
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\language.py", line 1112, in update
    proc.update(examples, sgd=None, losses=losses, **component_cfg[name])
  File "spacy\pipeline\transition_parser.pyx", line 358, in spacy.pipeline.transition_parser.Parser.update
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\thinc\model.py", line 309, in begin_update
    return self._func(self, X, is_train=True)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\ml\tb_framework.py", line 36, in forward
    has_upper=model.attrs["has_upper"],
  File "spacy\ml\parser_model.pyx", line 216, in spacy.ml.parser_model.ParserStepModel.__init__
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\pipeline\tok2vec.py", line 284, in forward
    model.verify_inputs(inputs)
  File "D:\work\state_classifier\state_identifier\state_identifier_venv\lib\site-packages\spacy\pipeline\tok2vec.py", line 272, in verify_inputs
    raise ValueError(Errors.E954)
ValueError: [E954] The Tok2Vec listener did not receive any valid input from an upstream component.
```

**Comment by adrianeboyd** [comment]
Hi, please don't post duplicate issues/threads, it just makes it harder for us to keep track of what's going on.

A link to the original thread: https://github.com/explosion/spaCy/discussions/8539
