### ISSUE TITLE
spaCy train - 'Invalid NaN value when encoding double' when creating meta.json

### ISSUE THREAD

**Issue by Lolologist** [explosion/spaCy#8649]
## How to reproduce the behaviour
I am trying to run spacy train for textcat, in a way that I hoped was nothing too complicated. Here's the command I run:
`python -m spacy train config_train.cfg --paths.train ./train.spacy --paths.dev ./test.spacy --output ./output`
and the config file:
[config_train.cfg.txt](https://github.com/explosion/spaCy/files/6784787/config_train.cfg.txt)

and the training data comes from a dataframe with two fields: "text" (a news article) and "binary_human_label" ("positive" or "negative"), which I turn into docs and into a DocBin as follows:

`def make_docs(df):
    docs = []
    data = df[['text','binary_human_label']].to_records(index=False)
    for doc, label in tqdm(nlp.pipe(data, as_tuples=True), total = len(data)):
        if label == "positive":
            doc.cats["positive"] = 0.9
            doc.cats["negative"] = 0.1
        else:
            doc.cats["positive"] = 0.1
            doc.cats["negative"] = 0.9
        docs.append(doc)
    doc_bin = DocBin(docs=docs)
    return doc_bin`

 which I then send to_disk.

My expectation is that I can `spacy train` with these files, and indeed I can! When I exclude `--output` in the command. Something about saving `meta.json` is breaking, stacktrace below:

`Traceback (most recent call last):
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/training/loop.py", line 114, in train
    raise e
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/training/loop.py", line 104, in train
    save_checkpoint(is_best_checkpoint)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/training/loop.py", line 67, in save_checkpoint
    before_to_disk(nlp).to_disk(output_path / DIR_MODEL_LAST)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/language.py", line 1801, in to_disk
    util.to_disk(path, serializers, exclude)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/util.py", line 1159, in to_disk
    writer(path / key)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/language.py", line 1792, in <lambda>
    serializers["meta.json"] = lambda p: srsly.write_json(p, self.meta)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/srsly/_json_api.py", line 75, in write_json
    json_data = json_dumps(data, indent=indent)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/srsly/_json_api.py", line 26, in json_dumps
    result = ujson.dumps(data, indent=indent, escape_forward_slashes=False)
OverflowError: Invalid Nan value when encoding double

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/cli/_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/cli/train.py", line 59, in train_cli
    train(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/training/loop.py", line 118, in train
    save_checkpoint(False)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/training/loop.py", line 67, in save_checkpoint
    before_to_disk(nlp).to_disk(output_path / DIR_MODEL_LAST)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/language.py", line 1801, in to_disk
    util.to_disk(path, serializers, exclude)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/util.py", line 1159, in to_disk
    writer(path / key)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/spacy/language.py", line 1792, in <lambda>
    serializers["meta.json"] = lambda p: srsly.write_json(p, self.meta)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/srsly/_json_api.py", line 75, in write_json
    json_data = json_dumps(data, indent=indent)
  File "/Users/daniel/.local/share/virtualenvs/internet-access-disruption-cv49WcSZ/lib/python3.9/site-packages/srsly/_json_api.py", line 26, in json_dumps
    result = ujson.dumps(data, indent=indent, escape_forward_slashes=False)
OverflowError: Invalid Nan value when encoding double`

Running `python -m spacy debug data config_train.cfg` gets me:

=============================== Training stats ===============================
Language: en
Training pipeline: tok2vec, textcat
200 training docs
52 evaluation docs
⚠ 1 training examples also in evaluation data
⚠ Low number of examples to train a new pipeline (200)

============================== Vocab & Vectors ==============================
ℹ 21129 total word(s) in the data (2579 unique)
ℹ 684830 vectors (684830 unique keys, 300 dimensions)
⚠ 876 words in training data without vectors (0.04%)

============================ Text Classification ============================
ℹ Text Classification: 0 new label(s), 2 existing label(s)
ℹ The train data contains instances without mutually-exclusive classes.
Use '--textcat-multilabel' when training.

================================== Summary ==================================
✔ 2 checks passed
⚠ 3 warnings

(I know this is a terribly small number of documents, I'm trying to bootstrap up a model.)

## Info about spaCy

- **spaCy version:** 3.0.1
- **Platform:** macOS-11.4-x86_64-i386-64bit
- **Python version:** 3.9.5
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_trf (3.0.0)

Thank you very much for your help.

**Comment by Lolologist** [comment]
It seems that having 'uncertain' scores (0.1 and 0.9 for the categories) was my downfall. If anyone sees this and has a recommendation for less-than-24k gold standard data being properly mistrusted by the algorithms, let me know!
