### ISSUE TITLE
Multiprocessing errors in spacy 3.1.0

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#8653]
I got the latest Spacy 3.10 and am having this multiprocessing error on my MacOS 11.2.3:

import spacy
nlp = spacy.load("en_core_web_sm")
texts = ["This is a sentence."] * 100
for doc in nlp.pipe(texts, n_process=2):
    print(doc)

```
/Users/congminmin/.venv/spacy/bin/python /Users/congminmin/nlp/spaCy/spacy/tests/random_test.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/congminmin/miniconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/congminmin/miniconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/congminmin/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/congminmin/nlp/spaCy/spacy/tests/random_test.py", line 6, in <module>
    for doc in nlp.pipe(texts, n_process=2):
  File "/Users/congminmin/nlp/spaCy/spacy/language.py", line 1521, in pipe
    for doc in docs:
  File "/Users/congminmin/nlp/spaCy/spacy/language.py", line 1557, in _multiprocessing_pipe
    proc.start()
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/congminmin/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Comment by svlandeg** [comment]
Thanks for the report!

While the error looks different, it feels like this is probably related to https://github.com/explosion/spaCy/issues/8651.

We'll investigate!

**Comment by adrianeboyd** [comment]
No, this isn't related to the Russian lemmatizer error. In OS X the default switched from fork to spawn in python 3.8. Follow the instructions in the error message to fix the problem. See:

https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods
