### ISSUE TITLE
convert from conllu to spacy doc failed - "ValueError: need more than 1 value to unpack"

### ISSUE THREAD

**Issue by yanirmr** [explosion/spaCy#8684]
## How to reproduce the behaviour

I attempted to convert Conllu data into a spacy document using the following command:
`python -m spacy convert ./conllu_data/1Cor.conllu ./data` 

A short example of `1Cor.conllu` file that create the problems is (the full file creates the same error):
```
1	ܦܿܰܘܠܳܘܣ	ܦܘܠܘܣ	PROPN	PN	_	_	_	_	trlem=pwlws
2	ܩܰܪܝܳܐ	ܩܪܝ	VERB	vb. 	_	_	_	_	trlem=qry| poschar=V
3-4	ܘܰܫܠܺܝܚܳܐ	_	_	_	_	_	_	_	_
3	ܘ_	ܘ_	PREP	_	_	_	_	_	trlem=w
4	ܰܫܠܺܝܚܳܐ	ܫܠܝܚ	NOUN	n.m.	_	_	_	_	trlem=$lyx| poschar=N
5-6	ܕܝܶܫܽܘܥ	_	_	_	_	_	_	_	_
5	ܕ_	ܕ_	PREP	_	_	_	_	_	trlem=d
6	ܝܶܫܽܘܥ	ܝܶܫܽܘܥ	ADP	PROPN	PN	_	_	_	trlem=yܶ$ܽw(
7	ܡܫܺܝܚܳܐ܂	ܡܫܝܚ	NOUN	n.m.	_	_	_	_	trlem=m$yx| poschar=N
8-9	ܒܨܶܒܼܝܳܢܶܗ	_	_	_	_	_	_	_	_
8	ܒ_	ܒ_	PREP	_	_	_	_	_	trlem=b
9	ܨܶܒܼܝܳܢܶܗ	ܨܒܝܢ	NOUN	n.m.	_	_	_	_	trlem=cbyn| poschar=N
10-11	ܕܰܐܠܳܗܳܐ܂	_	_	_	_	_	_	_	_
10	ܕ_	ܕ_	PREP	_	_	_	_	_	trlem=d
11	ܰܐܠܳܗܳܐ܂	ܐܠܗ	NOUN	n.m.	_	_	_	_	trlem=)lh| poschar=N
12-13	ܘܣܳܘܣܬܼܶܢܺܣ	_	_	_	_	_	_	_	_
12	ܘ_	ܘ_	PREP	_	_	_	_	_	trlem=w
13	ܣܳܘܣܬܼܶܢܺܣ	ܣܘܣܬܢܣ	PROPN	PN	_	_	_	_	trlem=swstns
14	ܐܰܚܳܐ܃	ܐܚ	NOUN	n.m.	_	_	_	_	trlem=)x| poschar=N
```

The received error massage is:
`ValueError: need more than 1 value to unpack`
I'm not sure what caused the error, and it appears strange.

This is the full traceback:
```
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\spacy\cli\convert.py", line 78, in convert_cli
    convert(
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\spacy\cli\convert.py", line 142, in convert
    db = DocBin(docs=docs, store_user_data=True)
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\spacy\tokens\_serialize.py", line 79, in __init__
    for doc in docs:
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\spacy\training\converters\conllu_to_docs.py", line 38, in conllu_to_docs
    for sent_doc in sent_docs:
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\spacy\training\converters\conllu_to_docs.py", line 79, in read_conllx
    doc = conllu_sentence_to_doc(
  File "C:\Users\User\anaconda3\envs\pos_tagging_syriac\lib\site-packages\spacy\training\converters\conllu_to_docs.py", line 200, in conllu_sentence_to_
doc
    doc = Doc(
  File "spacy\tokens\doc.pyx", line 357, in spacy.tokens.doc.Doc.__init__
  File "spacy\morphology.pyx", line 49, in spacy.morphology.Morphology.add
  File "spacy\morphology.pyx", line 153, in spacy.morphology.Morphology.feats_to_dict
ValueError: need more than 1 value to unpack
```

## Your Environment

- **spaCy version:** 3.1.0
- **Platform:** Windows-10-10.0.19042-SP0
- **Python version:** 3.9.5

**Comment by adrianeboyd** [comment]
The error message is a bit confusing, but it looks some there some value in the `FEATS` column that isn't the supported CoNLL-U format:

https://universaldependencies.org/format.html#morphological-annotation

Can you double-check for extra characters or weird formatting in that column?
