### ISSUE TITLE
Can't load en_core_web_md.vectors when wrapping spaCy model in an MLFlow Model

### ISSUE THREAD

**Issue by markFriel** [explosion/spaCy#8736]
I'm wrapping a spaCy model within an MLFlow model for deployment, however, when I try and do inference on new data, I am getting the following error: 

```
Traceback (most recent call last):
  File "/Users/n1534239/Documents/Pycharm-Projects/innovasion_nlp/Working Body Model/script.py", line 50, in <module>
    result = model.predict(data)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 596, in predict
    return self._model_impl.predict(data)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/mlflow/pyfunc/model.py", line 257, in predict
    return self.python_model.predict(self.context, model_input)
  File "/Users/n1534239/Documents/Pycharm-Projects/innovasion_nlp/Working Body Model/nlp_toolkit/email_entity_extraction/models/email_body_mlflow_wrapper.py", line 97, in predict
    extracted_entities, _ = predict_entities(self.ner_model, email_text, expanded_tags)
  File "/Users/n1534239/Documents/Pycharm-Projects/innovasion_nlp/Working Body Model/nlp_toolkit/email_entity_extraction/evaluation/model_evaluation_helper.py", line 98, in predict_entities
    doc = model(raw_text)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/spacy/language.py", line 446, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "pipes.pyx", line 397, in spacy.pipeline.pipes.Tagger.__call__
  File "pipes.pyx", line 416, in spacy.pipeline.pipes.Tagger.predict
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/model.py", line 167, in __call__
    return self.predict(x)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/feed_forward.py", line 40, in predict
    X = layer(X)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/model.py", line 167, in __call__
    return self.predict(x)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 310, in predict
    X = layer(layer.ops.flatten(seqs_in, pad=pad))
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/model.py", line 167, in __call__
    return self.predict(x)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/feed_forward.py", line 40, in predict
    X = layer(X)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/model.py", line 167, in __call__
    return self.predict(x)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/model.py", line 131, in predict
    y, _ = self.begin_update(X, drop=None)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 379, in uniqued_fwd
    Y_uniq, bp_Y_uniq = layer.begin_update(X_uniq, drop=drop)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 163, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 163, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 256, in wrap
    output = func(*args, **kwargs)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 163, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 163, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 256, in wrap
    output = func(*args, **kwargs)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 163, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 163, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 256, in wrap
    output = func(*args, **kwargs)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 163, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 163, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/api.py", line 256, in wrap
    output = func(*args, **kwargs)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/static_vectors.py", line 60, in begin_update
    vector_table = self.get_vectors()
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/neural/_classes/static_vectors.py", line 55, in get_vectors
    return get_vectors(self.ops, self.lang)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/extra/load_nlp.py", line 26, in get_vectors
    nlp = get_spacy(lang)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/thinc/extra/load_nlp.py", line 14, in get_spacy
    SPACY_MODELS[lang] = spacy.load(lang, **kwargs)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Users/n1534239/.local/share/virtualenvs/innovasion_nlp-FljM6oUq/lib/python3.8/site-packages/spacy/util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_md.vectors'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
``` 
I believe the issue to be the same as those outlined in the following issues:
#4349
#3690
#3552

I haven't been able to solve this issue with any of the current workarounds that are outlined in those threads. Any help with this would be much appreciated.

## Your Environment

* Operating System: MacOS Catalina
* Python Version Used: 3.8.5
* spaCy Version Used:2.3.0
* thinc Version Used: 7.4.1

**Comment by Oran-Ac** [comment]
Hi, I am facing the same problem.

If we use the 'en_core_web_sm' ,it can be solved by following this issue.
[#4577](https://github.com/explosion/spaCy/issues/4577#issuecomment-549770341)

But when it comes to en_core_web_md, things become different.

**Comment by Oran-Ac** [comment]
> Hi, I am facing the same problem.
> 
> If we use the 'en_core_web_sm' ,it can be solved by following this issue.
> [#4577](https://github.com/explosion/spaCy/issues/4577#issuecomment-549770341)
> 
> But when it comes to en_core_web_md, things become different.

Rather than using `pip install en_core_web_md` , I use
 `pip3 install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.2.0/en_core_web_md-2.2.0.tar.gz`

and

`
import en_core_web_md
`
`nlp = en_core_web_md.load()`

then, it works.

**Comment by polm** [comment]
Sorry for the late reply, but I'm not really sure what's going on here and whether it's a spaCy problem or an MLFlow problem. 

@Oran-Ac The model you downloaded is for spaCy 2.2.0. Is that the version you're using? The OP is using 2.3.0 and should use the models for that. 

There is some weirdness around how you installed the models in v2 but trying to load a model named `en_core_web_md.vectors` just seems wrong. Can you provide some sample code or more details about your setup?

**Comment by polm** [comment]
@Oran-Ac OK, it sounds like your issue is unrelated. It seems like you just hadn't installed the medium model. I missed this earlier, but `pip install en_core_web_md` doesn't work - you have to use `python -m spacy download en_core_web_md`. Downloading the model file and using pip install also works, `spacy download` just takes care of that for you.

Also note that we don't recommend v2 for new projects, and you may find v3 easier to use in general. 

If you need more help please open a separate issue or discussion.

**Comment by polm** [comment]
@markFriel Sorry for getting sidetracked. Your issue does look similar to the issues you linked, though not being very familiar with MLFlow it's unclear to me if you're using it to launch multiple jobs in a multithreaded way or something similar to the other issues. If you could provide more information about your configuration that could give us more to work with.

You might also try using spaCy v3. I'm not sure we've resolved all multithreading related issues, but there have been a lot of bugfixes over time, and one of them might cover your situation.

**Comment by markFriel** [comment]
Hi,

@polm Apologies about the late reply I was on Annual leave. I think the only beneficial information relating to MlFlow is that it serves the models using a Gunicorn web server, so I believe that is where it is launching multiple workers and multithreading. 

I took your advice and upgraded to spacy v3 and that seems to have done the trick, so whatever edits from v2 to v3 seems to have worked for my issue anyway.

Thanks

**Comment by polm** [comment]
Thanks for the update, glad to hear upgrading fixed your issues!
