### ISSUE TITLE
Run into 'cannot reshape array' problem when spacy.load triggered multiple times

### ISSUE THREAD

**Issue by munhouiani** [explosion/spaCy#8867]
## How to reproduce the behaviour
I ran into this problem when I tried to deploy my model to AWS sagemaker today. I have an app handler that looks like this:
```python
class ModelHandler(object):
    def __init__(self):
        self.spacy_model = None

    def initialize(self, context):
        self.spacy_model = spacy.load('en_core_web_lg', disable=['tagger', 'parser', 'senter', 'attribute_ruler', 'lemmatizer', 'ner'])
```

So when the server receives a request, it may reuse the model handler or init a new one (by creating another thread). This code runs fine for the first time when `spacy.load` is called, but for the second time, I ran into this error message: 

```
ValueError: cannot reshape array of size 75913212 into shape (684830,300)
```

From my understanding, `spacy.load` loads a NumPy file from the disk. So will spacy change the NumPy file? What I use spacy for is to extract vector from a document only:

```
self.spacy_model(some_text).vector
```

This is the full traceback message if it helps:
```
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.8/site-packages/mms/model_service_worker.py", line 174, in start_worker
    self.handle_connection(cl_socket)
  File "/opt/miniconda/lib/python3.8/site-packages/mms/model_service_worker.py", line 143, in handle_connection
    result, code = self.load_model(msg)
  File "/opt/miniconda/lib/python3.8/site-packages/mms/model_service_worker.py", line 109, in load_model
    self.service = self.model_loader.load(model_name, model_dir, handler, gpu, batch_size)
  File "/opt/miniconda/lib/python3.8/site-packages/mms/model_loader.py", line 127, in load
    entry_point(None, service.context)
  File "/opt/ml/code/model_handler/model_handler.py", line 117, in handle
    _service.initialize(context)
  File "/opt/ml/code/model_handler/model_handler.py", line 49, in initialize
    self.spacy_model = spacy.load('en_core_web_lg', disable=['tagger', 'parser', 'senter', 'attribute_ruler', 'lemmatizer', 'ner'])
  File "/opt/miniconda/lib/python3.8/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/opt/miniconda/lib/python3.8/site-packages/spacy/util.py", line 324, in load_model
    return load_model_from_package(name, **kwargs)
  File "/opt/miniconda/lib/python3.8/site-packages/spacy/util.py", line 357, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)
  File "/opt/miniconda/lib/python3.8/site-packages/en_core_web_lg/__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/opt/miniconda/lib/python3.8/site-packages/spacy/util.py", line 517, in load_model_from_init_py
    return load_model_from_path(
  File "/opt/miniconda/lib/python3.8/site-packages/spacy/util.py", line 393, in load_model_from_path
    return nlp.from_disk(model_path, exclude=exclude, overrides=overrides)
  File "/opt/miniconda/lib/python3.8/site-packages/spacy/language.py", line 1966, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/opt/miniconda/lib/python3.8/site-packages/spacy/util.py", line 1197, in from_disk
    reader(path / key)
  File "/opt/miniconda/lib/python3.8/site-packages/spacy/language.py", line 1942, in deserialize_vocab
    self.vocab.from_disk(path)
  File "spacy/vocab.pyx", line 484, in spacy.vocab.Vocab.from_disk
  File "spacy/vectors.pyx", line 431, in spacy.vectors.Vectors.from_disk
  File "/opt/miniconda/lib/python3.8/site-packages/spacy/util.py", line 1197, in from_disk
    reader(path / key)
  File "spacy/vectors.pyx", line 423, in spacy.vectors.Vectors.from_disk.load_vectors
  File "/opt/miniconda/lib/python3.8/site-packages/numpy/lib/npyio.py", line 440, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "/opt/miniconda/lib/python3.8/site-packages/numpy/lib/format.py", line 787, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 73433084 into shape (684830,300)
```
## Info about spaCy

- **spaCy version:** 3.1.1
- **Platform:** Linux-5.10.25-linuxkit-x86_64-with-glibc2.17
- **Python version:** 3.8.10
- **Pipelines:** en_core_web_lg (3.1.0)

**Comment by munhouiani** [comment]
It's worth mention that the size of the array changes every time in the error message.

The first one is 

```
ValueError: cannot reshape array of size 75913212 into shape (684830,300)
```

And when I reproduce the error, it changes to 
```
ValueError: cannot reshape array of size 73433084 into shape (684830,300)
```

**Comment by polm** [comment]
Thanks for the report, that looks weird. 

> From my understanding, spacy.load loads a NumPy file from the disk. So will spacy change the NumPy file? 

spaCy is doing more than just loading numpy arrays, though in the case of the vectors in your issue here that is where the problem is happening. spaCy doesn't modify a model when loading it, so I'm not sure why the number would change here, maybe numpy is doing something weird with multiprocess handling. 

It's pretty old but #3402 had a similar error in an Amazon environment, though it looks otherwise unrelated. They resolved their issue by installing the model.

Can you link to documentation or something that gives us more details about the multiprocessing context where the model is loaded? I'm not really familiar with SageMaker in detail.

**Comment by munhouiani** [comment]
Sure. Sagemaker uses [Multi-model server](https://github.com/awslabs/multi-model-server) to serve machine learning models. My code is pretty much the same as the [AWS tutorial](https://github.com/aws/amazon-sagemaker-examples/blob/2294ab22709c5d179c6570aa4e0088e775027bcc/advanced_functionality/multi_model_bring_your_own/container/model_handler.py#L15), except they load a mxnet model, while I load a spacy model at the `initialize` function. The other parts are the same. We both use a [`handle`](https://github.com/aws/amazon-sagemaker-examples/blob/2294ab22709c5d179c6570aa4e0088e775027bcc/advanced_functionality/multi_model_bring_your_own/container/model_handler.py#L173) function, and [the same way to init a server.](https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_bring_your_own/container/dockerd-entrypoint.py)

**Comment by munhouiani** [comment]
I tried `en_core_web_sm` and `en_core_web_md` and both of them are fine. Strange that `en_core_web_lg` won't work.

**Comment by polm** [comment]
Small working is unsurprising - I think the only place numpy arrays are loaded is for the word vectors. But given that it's really weird that the medium model should work, since it should have exactly the same structure, just more data.
