### ISSUE TITLE
EntityRecognizer predict and score - how to?

### ISSUE THREAD

**Issue by jacob-jeppesen** [explosion/spaCy#8871]
## Description of issue
I have been trying to use the .predict and .score methods both belonging to the EntityRecognizer component by following the [documentation](https://spacy.io/api/entityrecognizer) but I have run into several problems along the way.

Initially I wanted to initialize the components by doing the same as in the example [here](https://spacy.io/api/entityrecognizer#init):
```
#%% Setup
import spacy

# Load language object
nlp = spacy.load('en_core_web_sm')
ner = nlp.add_pipe('ner')
```
But this returns:
```
Traceback (most recent call last):
  File ".\ner_check.py", line 6, in <module>
    ner = nlp.add_pipe('ner')
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 757, in add_pipe
    raise ValueError(Errors.E007.format(name=name, opts=self.component_names))
ValueError: [E007] 'ner' already exists in pipeline. Existing names: ['tok2vec', 'tagger', 'parser', 'senter', 'ner', 'attribute_ruler', 'lemmatizer']
```
Instead I opt to initialize my NER component by using a "blank" language class such that:
```
#%% Setup
import spacy
from spacy.lang.en import English

# Load language object
nlp = English()
ner = nlp.add_pipe('ner')

# Create doc
sample1 = 'On June 26th 1963 John F. Kennedy gave a speech in Berlin.'
doc = nlp(sample1)
```
But now my problem becomes:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 995, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "spacy\pipeline\trainable_pipe.pyx", line 56, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 1510, in raise_error
    raise e
  File "spacy\pipeline\trainable_pipe.pyx", line 52, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "spacy\pipeline\transition_parser.pyx", line 209, in spacy.pipeline.transition_parser.Parser.predict
  File "spacy\pipeline\transition_parser.pyx", line 224, in spacy.pipeline.transition_parser.Parser.greedy_parse
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 315, in predict
    return self._func(self, X, is_train=False)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\ml\tb_framework.py", line 31, in forward
    step_model = ParserStepModel(
  File "spacy\ml\parser_model.pyx", line 216, in spacy.ml.parser_model.ParserStepModel.__init__
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\with_array.py", line 30, in forward
    return _ragged_forward(
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\with_array.py", line 90, in _ragged_forward
    Y, get_dX = layer(Xr.dataXd, is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\concatenate.py", line 44, in forward
    Ys, callbacks = zip(*[layer(X, is_train=is_train) for layer in model.layers])
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\concatenate.py", line 44, in <listcomp>
    Ys, callbacks = zip(*[layer(X, is_train=is_train) for layer in model.layers])
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\hashembed.py", line 61, in forward
    vectors = cast(Floats2d, model.get_param("E"))
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 216, in get_param
    raise KeyError(
KeyError: "Parameter 'E' for model 'hashembed' has not been allocated yet."

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\ner_check.py", line 11, in <module>
    doc = nlp(sample1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 998, in __call__
    raise ValueError(Errors.E109.format(name=name)) from e
ValueError: [E109] Component 'ner' could not be run. Did you forget to call `initialize()`?
```
I then follow the example given [here](https://spacy.io/api/entityrecognizer#initialize) by running:
```
#%% Setup
import spacy
from spacy.lang.en import English

# Load language object
nlp = English()
ner = nlp.add_pipe('ner')
ner.initialize(lambda: [], nlp = nlp)

# Create doc
sample1 = 'On June 26th 1963 John F. Kennedy gave a speech in Berlin.'
doc = nlp(sample1)
```
But now I get the error:
```
Traceback (most recent call last):
  File ".\ner_check.py", line 8, in <module>
    ner.initialize(lambda: [], nlp = nlp)
  File "spacy\pipeline\transition_parser.pyx", line 495, in spacy.pipeline.transition_parser.Parser.initialize
  File "spacy\training\example.pyx", line 64, in spacy.training.example.validate_get_examples
TypeError: [E930] Received invalid get_examples callback in `Parser.initialize`. Expected function that returns an iterable of Example objects but got: []
```
Lastly for my "Hail Marry" attempt to use ner.predict I did the following:
```
#%% Setup
import spacy
from spacy.lang.en import English

# Load model and documents
nlp = spacy.load('en_core_web_sm')
sample1 = 'On June 26th 1963 John F. Kennedy gave a speech in Berlin.'
sample2 = 'Ronald Reagan also gave a famous speech in Berlin.'
doc1, doc2 = nlp(sample1), nlp(sample2)

# Load NER component explicitly
nlp = spacy.load('en_core_web_sm', exclude = ['ner'])
ner = nlp.add_pipe('ner')

#%% Test things
scores = ner.predict([doc1, doc2])
```
From which I get:
```
Traceback (most recent call last):
  File ".\ner_check.py", line 16, in <module>
    scores = ner.predict([doc1, doc2])
  File "spacy\pipeline\transition_parser.pyx", line 209, in spacy.pipeline.transition_parser.Parser.predict
  File "spacy\pipeline\transition_parser.pyx", line 224, in spacy.pipeline.transition_parser.Parser.greedy_parse
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 315, in predict
    return self._func(self, X, is_train=False)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\ml\tb_framework.py", line 31, in forward
    step_model = ParserStepModel(
  File "spacy\ml\parser_model.pyx", line 216, in spacy.ml.parser_model.ParserStepModel.__init__
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\with_array.py", line 30, in forward
    return _ragged_forward(
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\with_array.py", line 90, in _ragged_forward
    Y, get_dX = layer(Xr.dataXd, is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\concatenate.py", line 44, in forward
    Ys, callbacks = zip(*[layer(X, is_train=is_train) for layer in model.layers])
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\concatenate.py", line 44, in <listcomp>
    Ys, callbacks = zip(*[layer(X, is_train=is_train) for layer in model.layers])
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\layers\hashembed.py", line 61, in forward
    vectors = cast(Floats2d, model.get_param("E"))
  File "C:\Users\jacob_hessellund\AppData\Roaming\Python\Python38\site-packages\thinc\model.py", line 216, in get_param
    raise KeyError(
KeyError: "Parameter 'E' for model 'hashembed' has not been allocated yet."
```
I must admit I am a bit out of ideas. Have I misunderstood the examples given in the documentation?  Sorry for the long reply.

## Your Environment

* Operating System: Microsoft Windows Server 2019 Datacenter
* Python Version Used: 3.8.5 64-bit ('base': conda)
* spaCy Version Used: 3.0.6 / spacy-transformers 1.0.3 / en-core-web-trf 3.0.0 / thinc 8.0.6
* Environment Information:

**Comment by svlandeg** [comment]
Hi! As a maintenance note: this is a good question for the discussions forum, so I'll move it there. The original issue will be closed and will link through to the open discussion thread.
