### ISSUE TITLE
Executable file made from Pyinstaller showing error for Spacy module i.e.: ModuleNotFoundError: No module named 'spacy.tokens._dict_proxies'

### ISSUE THREAD

**Issue by manasc12** [explosion/spaCy#8873]
I am building a GUI based web crawler application using PyQt5 and Spacy :
1. It runs perfectly fine when I execute it using python.exe.
2. I created a standalone exe file for my whole program using PyInstaller, Just to distribute it with my team (who are just users).
3. But when I double click that .exe file to open, it shows me some error like this:
```
Traceback (most recent call last):
  File "FleetMatch_Web_Crawler.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "spacy\__init__.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "spacy\pipeline\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "spacy\pipeline\attributeruler.py", line 6, in <module>
  File "spacy\pipeline\pipe.pyx", line 1, in init spacy.pipeline.pipe
    # cython: infer_types=True, profile=True
  File "spacy\morphology.pyx", line 1, in init spacy.morphology
    # cython: infer_types
  File "spacy\vocab.pyx", line 1, in init spacy.vocab
    # cython: profile=True
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "spacy\tokens\__init__.py", line 1, in <module>
  File "spacy\tokens\doc.pyx", line 20, in init spacy.tokens.doc
    from ._dict_proxies import SpanGroups
ModuleNotFoundError: No module named 'spacy.tokens._dict_proxies'
[6852] Failed to execute script 'FleetMatch_Web_Crawler' due to unhandled exception!
```

Provided: I have also imported language models for Spacy using Pyinstaller hook files and spec files. Because Spacy was not supported by Pyinstaller. But now I am not sure which module did I miss or where to get this module into my PyInstaller build. Please help me out!  

I am using Spacy 3.0.6

**Comment by manasc12** [comment]
hiddenimports in the hook file was the solution
