### ISSUE TITLE
AttributeError: module 'torch.utils' has no attribute 'dlpack'

### ISSUE THREAD

**Issue by santoshbs** [explosion/spaCy#8927]
## How to reproduce the behaviour
```
import spacy
spacy.require_gpu()
nlp= spacy.load("en_core_web_trf')
nlp("this is test")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/envs/env_spacy3_gensim4/lib/python3.9/site-packages/spacy/language.py", line 1000, in __call__
    error_handler(name, proc, [doc], e)
  File "/anaconda/envs/env_spacy3_gensim4/lib/python3.9/site-packages/spacy/util.py", line 1503, in raise_error
    raise e
  File "/anaconda/envs/env_spacy3_gensim4/lib/python3.9/site-packages/spacy/language.py", line 995, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/anaconda/envs/env_spacy3_gensim4/lib/python3.9/site-packages/spacy_transformers/pipeline_component.py", line 184, in __call__
    outputs = self.predict([doc])
  File "/anaconda/envs/env_spacy3_gensim4/lib/python3.9/site-packages/spacy_transformers/pipeline_component.py", line 220, in predict
    activations = self.model.predict(docs)
  File "/anaconda/envs/env_spacy3_gensim4/lib/python3.9/site-packages/thinc/model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "/anaconda/envs/env_spacy3_gensim4/lib/python3.9/site-packages/spacy_transformers/layers/transformer_model.py", line 133, in forward
    wordpieces = WordpieceBatch.from_batch_encoding(batch_encoding)
  File "/anaconda/envs/env_spacy3_gensim4/lib/python3.9/site-packages/spacy_transformers/data_classes.py", line 102, in from_batch_encoding
    input_ids=torch2xp(token_data["input_ids"]).reshape((n_seq, -1)),
  File "/anaconda/envs/env_spacy3_gensim4/lib/python3.9/site-packages/thinc/util.py", line 312, in torch2xp
    return cupy.fromDlpack(torch.utils.dlpack.to_dlpack(torch_tensor))
AttributeError: module 'torch.utils' has no attribute 'dlpack'
```

## Your Environment
- **spaCy version:** 3.0.6
- **Platform:** Linux-5.4.0-1047-azure-x86_64-with-glibc2.27
- **Python version:** 3.9.6
- **Pipelines:** en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by polm** [comment]
Sounds like this might be an issue with your torch install. 

Could you post the output of `pip freeze`?

How did you install spaCy/Torch?

Also, if you're just getting started, you might want to try upgrading spaCy to the latest version. I don't know that it's specifically related to this issue but the latest version does include some bugfixes.

**Comment by adrianeboyd** [comment]
Let me move this to the installation section of the discussion board...
