### ISSUE TITLE
Error when getting list of package files in model setup.py on Windows (Python 3.6)

### ISSUE THREAD

**Issue by ruiEnca** [explosion/spaCy#894]
After install Spacy 1.7.1 after download any model there is always a problem with the paths.

Traceback of the german model (the last I try):

python -m spacy download de

    Downloading de_core_news_md-1.0.0/de_core_news_md-1.0.0.tar.gz

Collecting https://github.com/explosion/spacy-models/releases/download/de_core_news_md-1.0.0/de_core_news_md-1.0.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/de_core_news_md-1.0.0/de_core_news_md-1.0.0.tar.gz (675.5MB)
    100% |████████████████████████████████| 675.5MB 1.9kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Rui\AppData\Local\Temp\pip-5lr0w63j-build\setup.py", line 61, in <module>
        setup_package()
      File "C:\Users\Rui\AppData\Local\Temp\pip-5lr0w63j-build\setup.py", line 54, in setup_package
        package_data={model_name: list_files(model_dir)},
      File "C:\Users\Rui\AppData\Local\Temp\pip-5lr0w63j-build\setup.py", line 30, in list_files
        output = [p.split('/', 1)[1] for p in paths]
      File "C:\Users\Rui\AppData\Local\Temp\pip-5lr0w63j-build\setup.py", line 30, in <listcomp>
        output = [p.split('/', 1)[1] for p in paths]
    IndexError: list index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Rui\AppData\Local\Temp\pip-5lr0w63j-build\
Traceback (most recent call last):
  File "C:\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\lib\site-packages\spacy\__main__.py", line 71, in <module>
    plac.Interpreter.call(CLI)
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 1142, in call
    print(out)
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 53, in raise_
    raise exc.with_traceback(tb)
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 53, in raise_
    raise exc.with_traceback(tb)
  File "C:\Anaconda\lib\site-packages\plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "C:\Anaconda\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Anaconda\lib\site-packages\spacy\__main__.py", line 30, in download
    cli_download(model, direct)
  File "C:\Anaconda\lib\site-packages\spacy\cli\download.py", line 25, in download
    link_package(model_name, model, force=True)
  File "C:\Anaconda\lib\site-packages\spacy\cli\link.py", line 21, in link_package
    pkg = importlib.import_module(package_name)
  File "C:\Anaconda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'de_core_news_md'

In the meanwhile I placed the model folder manually and it seems working.

## Info about spaCy

* **spaCy version:** 1.7.1
* **Platform:** Windows-10-10.0.14393-SP0
* **Python version:** 3.6.0
* **Installed models:**

**Comment by ines** [comment]
Thanks for the report!

This is interesting – it actually fails in the model's `setup.py` when putting together [the list of package files](https://github.com/explosion/spacy-dev-resources/blob/master/templates/model/setup.py#L24). So the good news is, the spaCy code might be fine – but we'll definitely have to debug the model setup and rebuild and reupload the files.

I'm glad this came up, though. `[p.split('/', 1)[1] for p in paths]` seems like a very brittle way to compile a list of paths, so this needs to be fixed.

**Comment by GruffPrys** [comment]
Happened to me too:

C:\Users\user\Downloads>pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-1.2.0/en_core_web_md-1.2.0.tar.gz
Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_md-1.2.0/en_core_web_md-1.2.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-1.2.0/en_core_web_md-1.2.0.tar.gz (1086.4MB)
    100% |################################| 1086.4MB 738bytes/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-f2c13r4e-build\setup.py", line 61, in <module>
        setup_package()
      File "C:\Users\user\AppData\Local\Temp\pip-f2c13r4e-build\setup.py", line 54, in setup_package
        package_data={model_name: list_files(model_dir)},
      File "C:\Users\user\AppData\Local\Temp\pip-f2c13r4e-build\setup.py", line 30, in list_files
        output = [p.split('/', 1)[1] for p in paths]
      File "C:\Users\user\AppData\Local\Temp\pip-f2c13r4e-build\setup.py", line 30, in <listcomp>
        output = [p.split('/', 1)[1] for p in paths]
    IndexError: list index out of range

spaCy 1.7.1, Win 10, Python 3.5

Thanks for spaCy, enjoying playing around with it :)

**Comment by ines** [comment]
Just rebuilt and reuploaded [all models](https://github.com/explosion/spacy-models/releases) with an [updated setup.py](https://github.com/explosion/spacy-dev-resources/blob/master/templates/model/setup.py).

Pretty sure the cause of this issue on Windows was the old code snippet using a hard-coded `/` to compile paths (duh). Sorry about that. You should be able to download and install models properly now – if not, feel free to reopen.
