### ISSUE TITLE
transformer_config passed to transformer.forward

### ISSUE THREAD

**Issue by RajK853** [explosion/spaCy#8995]
## How to reproduce the behaviour  

While providing the `transformer_config` in the `v2` transformer models, we got the following issue:

```shell
File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/shims/pytorch.py", line 29, in __call__
    return self.predict(inputs), lambda a: ...
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/shims/pytorch.py", line 38, in predict
    outputs = self._model(*inputs.args, **inputs.kwargs)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'max_length'
```

For the training, we used the following configuration:
```
...
[components.tagger.tok2vec]
@architectures = "spacy-transformers.Tok2VecTransformer.v2"
name = "roberta-base"
tokenizer_config = {"use_fast": true}
transformer_config = {"max_length": 50}
grad_factor = 0.0
...
```

### Info about spaCy

- **spaCy version:** 3.1.1
- **Platform:** Linux-4.19.0-17-cloud-amd64-x86_64-with-debian-10.10
- **Python version:** 3.7.3

## Possible issue
For some reason, `transformer_config` was being passed to the `forward` method of the transformer. While going through the source code of the `spacy-transformers`, we found that the `transformer_config` was passed to the `transformer.forward` method [here](https://github.com/explosion/spacy-transformers/blob/1ba8ffc2c92a1a5e73e8d50d392d33eb0de8c12c/spacy_transformers/util.py).  

![image](https://user-images.githubusercontent.com/9031618/130077347-3c8b0fa4-03ec-4423-a821-399963e988e0.png)

Because of this line of the code, we get the above error when the `transformer_config` is not empty.

**Comment by adrianeboyd** [comment]
You've installed `spacy-transformers` from source from the github repo, right? I don't think that change is in a released version yet.

This is the intended use of `transformer_config`, and it doesn't look like `max_length` is a setting that makes sense for training models with `spacy-transformers`, but maybe I don't understand exactly what you're trying to do. Can you provide some more details about your setup and your use of `max_length` here?

The intended use would be for options that can be passed to `forward` like:

```ini
transformer_config = {"output_attentions": true}
```

**Comment by RajK853** [comment]
Yeah. We have installed the `spacy-transformers` from the github repo.

For our experiment, we want to change the `max_length` parameter of the huggingface transformer model.
The available parameters are listed [here](https://github.com/huggingface/transformers/blob/1fec32adc6a4840123d5ec5ff5cf419c02342b5a/src/transformers/configuration_utils.py).

**Comment by RajK853** [comment]
![image](https://user-images.githubusercontent.com/9031618/130087075-b69bdcc2-c926-43b1-a37a-f99921a5452e.png)

In the above code, if the `trf_config` is passed to `line 39` instead, we could change the parameters of the huggingface transformers which is connected as follows.

![automodel](https://user-images.githubusercontent.com/9031618/130086956-7fbaf2a7-cd0d-432b-99c2-cdeb28e22596.png)


![base_automodel](https://user-images.githubusercontent.com/9031618/130086798-df747bb2-4bd1-401b-b2bb-604e3c1cd920.png)

**Comment by RajK853** [comment]
When we used the config
```python
transformer_config = {"output_attentions": true}
```
we got a similar error.

```shell
Traceback (most recent call last):
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/bin/spacy", line 8, in <module>
    sys.exit(setup_cli())
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/spacy/training/initialize.py", line 82, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/spacy/language.py", line 1273, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "/home/jupyter/branch_29/mlgec/mlgec/seq2labels/pipeline.py", line 257, in initialize
    self.model.initialize(X=X, Y=Y)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/model.py", line 299, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/model.py", line 299, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/model.py", line 299, in initialize
    self.init(self, X=X, Y=Y)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/src/spacy-transformers/spacy_transformers/layers/transformer_model.py", line 151, in init
    tensors = model.layers[0].predict(wordpieces)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/model.py", line 315, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/layers/pytorchwrapper.py", line 80, in forward
    Ytorch, torch_backprop = model.shims[0](Xtorch, is_train)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/shims/pytorch.py", line 29, in __call__
    return self.predict(inputs), lambda a: ...
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/thinc/shims/pytorch.py", line 38, in predict
    outputs = self._model(*inputs.args, **inputs.kwargs)
  File "/home/jupyter/.local/share/virtualenvs/mlgec-maJlMuVg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'output_attenstions'
```

**Comment by adrianeboyd** [comment]
Please use code blocks instead of screenshots, it makes it much easier for us to read/test code and search for relevant reports in the future.

I can see why it might be better to add these settings in `AutoConfig.from_pretrained` rather than `forward`, that does make sense and we can have a look at whether that makes sense before we release v1.1.0.

But for `max_length`, it looks like it's only relevant for `generate`, which isn't relevant for `spacy-transformers` as far as I understand? I don't really work with transformer models in depth on a day-to-day basis, though, so there may be some details I'm missing?

**Comment by RajK853** [comment]
I am also not that familiar with transformer models. But as far as I understand,  `spacy-transformers` is a wrapper over the huggingface transformer and tokenizer models. And to reproduce one of the experiment results, we need to set `max_length` to `50` and `min_length` to `3` for our transformer model.

**Comment by adrianeboyd** [comment]
`spacy-transformers` is only a partial wrapper for the functionality needed for training components in spacy pipelines, which are focused on text analysis and not text generation, so it may not be the right tool for you. But I'm still not sure I understand enough about what you're trying to do.

**Comment by RajK853** [comment]
Our purpose was to truncate the sentences using min and max number of words per sentences. I guess this is possible using `spacy.batch_by_words.v1`. But we realized that the huggingface transformers already has such parameters. So we wanted to make sure that the sentences are not truncated twice using different values. 

Also, having access to the parameters of the huggingface transformers will give us more control to improve our experiments if needed ☺️

**Comment by adrianeboyd** [comment]
If you want to truncate sentences, that's going to be a setting in `tokenizer_config`, not `transformer_config`. Depending on what you're doing, you could have your sentences as docs in the spacy training data and then use `doc_spans` instead of `strided_spans`. You could also use `sent_spans`, but then see the notes in the docs about "annotating components".
