### ISSUE TITLE
Model symlinks not working on Windows (Python 2.7)

### ISSUE THREAD

**Issue by solresol** [explosion/spaCy#909]
It's not exactly spaCy's fault. It looks like it's a pathlib problem creating symlinks on Windows.

Anyway, on a fairly fresh Win2k8 (an Amazon workspaces desktop, in fact) pip install spacy works as long as the compiler is in place.

 `python -m spacy download en`  fails with the following error message:

> Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\lib\site-packages\spacy\__main__.py", line 71, in <module>
    plac.Interpreter.call(CLI)
  File "c:\python27\lib\site-packages\plac_ext.py", line 1142, in call
    print(out)
  File "c:\python27\lib\site-packages\plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "c:\python27\lib\site-packages\plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "c:\python27\lib\site-packages\plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "c:\python27\lib\site-packages\plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "c:\python27\lib\site-packages\plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "c:\python27\lib\site-packages\plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "c:\python27\lib\site-packages\plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "c:\python27\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "c:\python27\lib\site-packages\spacy\__main__.py", line 45, in link
    cli_link(origin, link_name, force)
  File "c:\python27\lib\site-packages\spacy\cli\link.py", line 14, in link
    symlink(origin, link_name, force)
  File "c:\python27\lib\site-packages\spacy\cli\link.py", line 50, in symlink
    link_path.symlink_to(model_path)
  File "c:\python27\lib\site-packages\pathlib.py", line 1167, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
TypeError: symlink() takes exactly 3 arguments (4 given)

I've written up a solution over here: [http://stackoverflow.com/questions/42914239/spacy-english-model-install-is-failing](http://stackoverflow.com/questions/42914239/spacy-english-model-install-is-failing)

I think what's going wrong is that pathlib's symlink function doesn't work correctly on Windows.

## Your Environment

* Operating System: Windows
* Python Version Used: 2.7
* spaCy Version Used: 1.7.2
* Environment Information:

**Comment by ines** [comment]
Thanks for the report and getting to the bottom of this! 

That's pretty annoying... just did a quick search and there seem to be some [general problems](http://stackoverflow.com/questions/6260149/os-symlink-support-in-windows) with symlinks and Python 2 on Windows. So we might need to add a little Windows-only workaround. Unfortunately, we don't have a good Windows testing environment at the moment, so I'll be tagging this as "help wanted" in case one of our Windows users wants to give this a go in the meantime (would be much appreciated!).
