### ISSUE TITLE
Run spacy train textcat with transformer on GPU raised TypeError

### ISSUE THREAD

**Issue by tin-olli** [explosion/spaCy#9162]
## How to reproduce the behaviour
I encountered this error while train a textcat on GPU
```
spacy train textcat.cfg --output ./model-out --paths.train ./train.spacy --paths.dev ./val.spacy --gpu-id 0

ℹ Saving to output directory: model-out
ℹ Using GPU: 0

=========================== Initializing pipeline ===========================
[2021-09-07 03:49:08,206] [INFO] Set up nlp object from config
[2021-09-07 03:49:08,217] [INFO] Pipeline: ['transformer', 'textcat']
[2021-09-07 03:49:08,221] [INFO] Created vocabulary
[2021-09-07 03:49:08,222] [INFO] Finished initializing nlp object
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.decoder.weight', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.dense.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[2021-09-07 03:49:31,732] [INFO] Initialized pipeline components: ['transformer', 'textcat']
✔ Initialized pipeline

============================= Training pipeline =============================
ℹ Pipeline: ['transformer', 'textcat']
ℹ Initial learn rate: 0.0
E    #       LOSS TRANS...  LOSS TEXTCAT  CATS_SCORE  SCORE 
---  ------  -------------  ------------  ----------  ------
⚠ Aborting and saving the final best model. Encountered exception:
TypeError("Unsupported type <class 'numpy.ndarray'>",)
Traceback (most recent call last):
  File "/home/tin/spacy/tc_venv/bin/spacy", line 8, in <module>
    sys.exit(setup_cli())
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/spacy/cli/train.py", line 63, in train_cli
    train(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/spacy/training/loop.py", line 122, in train
    raise e
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/spacy/training/loop.py", line 105, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/spacy/training/loop.py", line 219, in train_while_improving
    proc.finish_update(optimizer)
  File "spacy/pipeline/trainable_pipe.pyx", line 252, in spacy.pipeline.trainable_pipe.TrainablePipe.finish_update
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/thinc/model.py", line 328, in finish_update
    (node.id, name), node.get_param(name), node.get_grad(name)
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/thinc/optimizers.py", line 230, in __call__
    gradient = ops.clip_gradient(gradient, self.grad_clip)
  File "/home/tin/spacy/tc_venv/lib/python3.6/site-packages/thinc/backends/cupy_ops.py", line 101, in clip_gradient
    gradient *= cupy.minimum(threshold, grad_norm) / grad_norm
  File "cupy/_core/core.pyx", line 1491, in cupy._core.core.ndarray.__array_ufunc__
  File "cupy/_core/_kernel.pyx", line 1119, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 110, in cupy._core._kernel._preprocess_args
TypeError: Unsupported type <class 'numpy.ndarray'>

```
I modified code from [this blog post](https://medium.com/analytics-vidhya/building-a-text-classifier-with-spacy-3-0-dd16e9979a) to make my train data
```
import spacy
from tqdm.auto import tqdm
from spacy.tokens import DocBin
from ml_datasets import imdb


def make_docs(data):
    docs = []
    for doc, label in tqdm(nlp.pipe(data, as_tuples=True), total = len(data)):
        doc.cats["positive"] = 1 if label == "pos" else 0
        doc.cats["negative"] = 1 if label == "neg" else 0
        docs.append(doc)
    return docs


nlp = spacy.blank("en")
train_data, valid_data = imdb()
train_docs = make_docs(train_data[:500])
doc_bin = DocBin(docs=train_docs)
doc_bin.to_disk("./train.spacy")
valid_docs = make_docs(valid_data[:500])
doc_bin = DocBin(docs=valid_docs)
doc_bin.to_disk("./val.spacy")
```
And here's my pipeline config
```
cat textcat.cfg

[paths]
train = null
dev = null
vectors = null
init_tok2vec = null

[system]
gpu_allocator = "pytorch"
seed = 0

[nlp]
lang = "en"
pipeline = ["transformer","textcat"]
batch_size = 128
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.textcat]
factory = "textcat"
threshold = 0.5

[components.textcat.model]
@architectures = "spacy.TextCatEnsemble.v2"
nO = null

[components.textcat.model.linear_model]
@architectures = "spacy.TextCatBOW.v2"
exclusive_classes = true
ngram_size = 1
no_output_layer = false
nO = null

[components.textcat.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"

[components.transformer]
factory = "transformer"
max_batch_items = 4096
set_extra_annotations = {"@annotation_setters":"spacy-transformers.null_annotation_setter.v1"}

[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "roberta-base"

[components.transformer.model.get_spans]
@span_getters = "spacy-transformers.strided_spans.v1"
window = 128
stride = 96

[components.transformer.model.tokenizer_config]
use_fast = true

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[training]
accumulate_gradient = 3
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
annotating_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_padded.v1"
discard_oversize = true
size = 2000
buffer = 256
get_length = null

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001

[training.optimizer.learn_rate]
@schedules = "warmup_linear.v1"
warmup_steps = 250
total_steps = 20000
initial_rate = 0.00005

[training.score_weights]
cats_score = 1.0
cats_score_desc = null
cats_micro_p = null
cats_micro_r = null
cats_micro_f = null
cats_macro_p = null
cats_macro_r = null
cats_macro_f = null
cats_macro_auc = null
cats_f_per_type = null
cats_macro_auc_per_type = null

[pretraining]

[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```
## Info about spaCy

- **spaCy version:** 3.1.2
- **Platform:** Linux-5.4.0-1049-gcp-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9
- **Pipelines:** en_core_web_sm (3.1.0)
### pip list
```
Package            Version
------------------ ---------
backcall           0.2.0
blis               0.7.4
catalogue          2.0.6
certifi            2021.5.30
charset-normalizer 2.0.4
click              7.1.2
contextvars        2.4
cupy               9.4.0
cupy-cuda112       9.4.0
cymem              2.0.5
dataclasses        0.8
decorator          5.0.9
en-core-web-sm     3.1.0
fastrlock          0.6
filelock           3.0.12
huggingface-hub    0.0.12
idna               3.2
immutables         0.16
importlib-metadata 4.8.1
ipython            7.16.1
ipython-genutils   0.2.0
jedi               0.18.0
Jinja2             3.0.1
joblib             1.0.1
MarkupSafe         2.0.1
ml-datasets        0.2.0
murmurhash         1.0.5
numpy              1.19.5
packaging          21.0
parso              0.8.2
pathy              0.6.0
pexpect            4.8.0
pickleshare        0.7.5
pip                21.2.4
pkg_resources      0.0.0
preshed            3.0.5
prompt-toolkit     3.0.20
ptyprocess         0.7.0
pydantic           1.8.2
Pygments           2.10.0
pyparsing          2.4.7
PyYAML             5.4.1
regex              2021.8.28
requests           2.26.0
sacremoses         0.0.45
setuptools         58.0.2
six                1.16.0
smart-open         5.2.1
spacy              3.1.2
spacy-alignments   0.8.3
spacy-legacy       3.0.8
spacy-transformers 1.0.6
srsly              2.4.1
thinc              8.0.9
tokenizers         0.10.3
torch              1.9.0
tqdm               4.62.2
traitlets          4.3.3
transformers       4.9.2
typer              0.3.2
typing-extensions  3.10.0.2
urllib3            1.26.6
wasabi             0.8.2
wcwidth            0.2.5
wheel              0.37.0
zipp               3.5.0
```

**Comment by tin-olli** [comment]
After doing some debugging, I found that `get_array_ops` function in `thinc` library may hold the key to the  problem. Instead of returning NumpyOps for model weights designated to run on CPU, CupyOps was returned by this function [get_current_ops](https://github.com/explosion/thinc/commit/a00e7f089797f6cc2ccd63f1650fb2672bf6159d). 

Here's my debug session
```
> /home/tin/spacy/tc_venv/lib/python3.6/site-packages/spacy/training/loop.py(105)train()
-> try:
(Pdb) l
100  	        )
101  	    stdout.write(msg.info(f"Initial learn rate: {optimizer.learn_rate}") + "\n")
102  	    with nlp.select_pipes(disable=frozen_components):
103  	        log_step, finalize_logger = train_logger(nlp, stdout, stderr)
104  	    import pdb; pdb.set_trace()
105  ->	    try:
106  	        for batch, info, is_best_checkpoint in training_step_iterator:
107  	            if is_best_checkpoint is not None:
108  	                with nlp.select_pipes(disable=frozen_components):
109  	                    update_meta(T, nlp, info)
110  	                if output_path is not None:
(Pdb) n
> /home/tin/spacy/tc_venv/lib/python3.6/site-packages/spacy/training/loop.py(106)train()
-> for batch, info, is_best_checkpoint in training_step_iterator:
(Pdb) n
TypeError: Unsupported type <class 'numpy.ndarray'>
> /home/tin/spacy/tc_venv/lib/python3.6/site-packages/spacy/training/loop.py(106)train()
-> for batch, info, is_best_checkpoint in training_step_iterator:
(Pdb) l
101  	    stdout.write(msg.info(f"Initial learn rate: {optimizer.learn_rate}") + "\n")
102  	    with nlp.select_pipes(disable=frozen_components):
103  	        log_step, finalize_logger = train_logger(nlp, stdout, stderr)
104  	    import pdb; pdb.set_trace()
105  	    try:
106  ->	        for batch, info, is_best_checkpoint in training_step_iterator:
107  	            if is_best_checkpoint is not None:
108  	                with nlp.select_pipes(disable=frozen_components):
109  	                    update_meta(T, nlp, info)
110  	                if output_path is not None:
111  	                    save_checkpoint(is_best_checkpoint)
(Pdb) down
> /home/tin/spacy/tc_venv/lib/python3.6/site-packages/spacy/training/loop.py(220)train_while_improving()
-> proc.finish_update(optimizer)
(Pdb) down
> /home/tin/spacy/spacy/pipeline/trainable_pipe.pyx(252)spacy.pipeline.trainable_pipe.TrainablePipe.finish_update()
(Pdb) down
> /home/tin/spacy/tc_venv/lib/python3.6/site-packages/thinc/model.py(328)finish_update()
-> (node.id, name), node.get_param(name), node.get_grad(name)
(Pdb) l
323  	                shim.finish_update(optimizer)
324  	        for node in self.walk():
325  	            for name in node.param_names:
326  	                if node.has_grad(name):
327  	                    param, grad = optimizer(
328  ->	                        (node.id, name), node.get_param(name), node.get_grad(name)
329  	                    )
330  	                    node.set_param(name, param)
331  	
332  	    @contextlib.contextmanager
333  	    def use_params(self, params: Dict[Tuple[int, str], FloatsXd]):
(Pdb) node.name
'sparse_linear'
(Pdb) self.name
'with_cpu(extract_ngrams>>resizable(sparse_linear))>>with_cpu(softmax_activation)|transformer-listener>>trfs2arrays>>list2ragged>>para-attn>>reduce_sum>>residual(maxout>>layernorm>>dropout)>>softmax'
(Pdb) type(node.get_param(name))
<class 'numpy.ndarray'>
(Pdb) name
'W'
(Pdb) down
> /home/tin/spacy/tc_venv/lib/python3.6/site-packages/thinc/optimizers.py(230)__call__()
-> gradient = ops.clip_gradient(gradient, self.grad_clip)
(Pdb) ops
<thinc.backends.cupy_ops.CupyOps object at 0x7fe0e829c9e8>
(Pdb) gradient
array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
(Pdb) type(gradient)
<class 'numpy.ndarray'>
(Pdb) down
> /home/tin/spacy/tc_venv/lib/python3.6/site-packages/thinc/backends/cupy_ops.py(101)clip_gradient()
-> gradient *= cupy.minimum(threshold, grad_norm) / grad_norm
(Pdb) l
 96  	    def backprop_mish(self, dY, X, threshold=20.0, out=None):
 97  	        return _custom_kernels.backprop_mish(dY, X, threshold=threshold, out=out)
 98  	
 99  	    def clip_gradient(self, gradient, threshold):
100  	        grad_norm = cupy.maximum(cupy.linalg.norm(gradient), 1e-12)
101  ->	        gradient *= cupy.minimum(threshold, grad_norm) / grad_norm
102  	        return gradient
103  	
104  	    def seq2col(self, seq, nW):
105  	        """Given an (M, N) sequence of vectors, return an (M, N*(nW*2+1)) sequence.
106  	        The new sequence is constructed by concatenating nW preceding and succeeding
(Pdb) type(grad_norm)
<class 'cupy._core.core.ndarray'>
(Pdb) type(gradient)
<class 'numpy.ndarray'>
(Pdb) gradient * cupy.minimum(threshold, grad_norm) / grad_norm
*** TypeError: Unsupported type <class 'numpy.ndarray'>
(Pdb) up
> /home/tin/spacy/tc_venv/lib/python3.6/site-packages/thinc/optimizers.py(230)__call__()
-> gradient = ops.clip_gradient(gradient, self.grad_clip)
(Pdb) l 200, 250
200  	                err = f"Invalid schedule for '{name}' ({type(value)})\n{e}"
201  	                raise ValueError(err)
202  	
203  	    def step_schedules(self):
204  	        for key, schedule in self.schedules.items():
205  	            try:
206  	                value = next(schedule)
207  	            except StopIteration:  # schedule exhausted, use last value
208  	                value = getattr(self, key)
209  	            setattr(self, key, value)
210  	
211  	    def __call__(
212  	        self,
213  	        key: Tuple[int, str],
214  	        weights: FloatsXd,
215  	        gradient: FloatsXd,
216  	        *,
217  	        lr_scale: float = 1.0,
218  	    ):
219  	        """Call the optimizer with weights and a gradient. The key is the
220  	        identifier for the parameter, usually the node ID and parameter name.
221  	        """
222  	        if len(gradient) < 1:
223  	            return weights, gradient
224  	        ops = get_array_ops(weights)
225  	        self.nr_update[key] += 1
226  	        nr_upd = self.nr_update[key]
227  	        if self.L2 != 0 and not self.L2_is_weight_decay:
228  	            gradient += self.L2 * weights
229  	        if self.grad_clip:
230  ->	            gradient = ops.clip_gradient(gradient, self.grad_clip)
231  	        if self.use_radam:
232  	            weights, gradient = self._radam(
233  	                ops, weights, gradient, lr_scale, key, nr_upd
234  	            )
235  	        elif self.b1 > 0.0 and self.b2 > 0.0:
236  	            weights, gradient = self._adam(
237  	                ops, weights, gradient, lr_scale, key, nr_upd
238  	            )
239  	        elif self.b2 > 0.0:  # pragma: no cover
240  	            raise NotImplementedError  # TODO: error message
241  	        else:
242  	            weights -= lr_scale * self.learn_rate * gradient
243  	        gradient *= 0
244  	        if self.L2 != 0 and self.L2_is_weight_decay:
245  	            weights -= lr_scale * self.learn_rate * self.L2 * weights
246  	        if self.averages is not None:
247  	            if key not in self.averages:
248  	                self.averages[key] = ops.alloc(weights.shape, dtype="float32")
249  	            ops.update_averages(self.averages[key], weights, nr_upd)
250  	        return weights, gradient
(Pdb) weights
array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
(Pdb) type(weights)
<class 'numpy.ndarray'>
(Pdb) ops
<thinc.backends.cupy_ops.CupyOps object at 0x7fe0e829c9e8>
(Pdb) ops = get_array_ops(weights)
(Pdb) ops
<thinc.backends.cupy_ops.CupyOps object at 0x7fe0e829c9e8>

```

**Comment by polm** [comment]
Thanks for the report and the debugging info, we'll take a look!

**Comment by adrianeboyd** [comment]
That does look like a bug, we'll revert that change here in thinc v8.0.10: https://github.com/explosion/thinc/pull/533

In the meanwhile, off the top of my head I think you should be able to downgrade to `thinc==8.0.8` for this particular config setup.

**Comment by adrianeboyd** [comment]
Sorry about that! Please upgrade to thinc v8.0.10 for the bug fix.
