### ISSUE TITLE
Issue with spancat evaluate command

### ISSUE THREAD

**Issue by brightgems** [explosion/spaCy#9206]
I'm trying to evaluate the model trained with spacat component. After then, I want to evaluate the model performance on specific label, it raised out error below

```
Traceback (most recent call last):
  File "scripts/evaluate.py", line 47, in <module>
    typer.run(evaluate_cli)
  File "d:\miniconda3\envs\py37\lib\site-packages\typer\main.py", line 859, in run
    app()
  File "d:\miniconda3\envs\py37\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "d:\miniconda3\envs\py37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\miniconda3\envs\py37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\miniconda3\envs\py37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\miniconda3\envs\py37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\miniconda3\envs\py37\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "scripts/evaluate.py", line 42, in evaluate_cli
    spans_key=spans_key,
  File "d:\miniconda3\envs\py37\lib\site-packages\spacy\cli\evaluate.py", line 78, in evaluate
    scores = nlp.evaluate(dev_dataset)
  File "d:\miniconda3\envs\py37\lib\site-packages\spacy\language.py", line 1385, in evaluate
    examples,
  File "d:\miniconda3\envs\py37\lib\site-packages\spacy\util.py", line 1490, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy\pipeline\trainable_pipe.pyx", line 79, in pipe
  File "d:\miniconda3\envs\py37\lib\site-packages\spacy\util.py", line 1509, in raise_error
    raise e
  File "spacy\pipeline\trainable_pipe.pyx", line 75, in spacy.pipeline.trainable_pipe.TrainablePipe.pipe
  File "d:\miniconda3\envs\py37\lib\site-packages\spacy\pipeline\spancat.py", line 226, in predict
    scores = self.model.predict((docs, indices))
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\model.py", line 315, in predict
    return self._func(self, X, is_train=False)[0]
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\layers\with_getitem.py", line 29, in forward
    Y_i, backprop_item = model.layers[0](items[idx], is_train)
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\layers\with_array.py", line 40, in forward
    return _list_forward(cast(Model[List2d, List2d], model), Xseq, is_train)
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\layers\with_array.py", line 75, in _list_forward
    Xf = layer.ops.flatten(Xs, pad=pad)  # type: ignore
  File "d:\miniconda3\envs\py37\lib\site-packages\thinc\backends\ops.py", line 236, in flatten
    result = xp.concatenate(X)
  File "<__array_function__ internals>", line 6, in concatenate
  File "cupy\_core\core.pyx", line 1513, in cupy._core.core.ndarray.__array_function__
  File "d:\miniconda3\envs\py37\lib\site-packages\cupy\_manipulation\join.py", line 55, in concatenate
    return _core.concatenate_method(tup, axis, out)
  File "cupy\_core\_routines_manipulation.pyx", line 533, in cupy._core._routines_manipulation.concatenate_method
  File "cupy\_core\_routines_manipulation.pyx", line 546, in cupy._core._routines_manipulation.concatenate_method
TypeError: Only cupy arrays can be concatenated
```

## How to reproduce the behaviour

the evaluate command in project.yml is:

```
python scripts/evaluate.py ./training/model-best ./corpus/dev.spacy --output ./metrics/${vars.config}.json --gpu-id ${vars.gpu} --spans-key ${vars.spans_key}
```

## config file:
```
[paths]
train = null
dev = null
vectors = null
init_tok2vec = null

[system]
gpu_allocator = null
seed = 0

[nlp]
lang = "zh"
pipeline = ["spancat"]
batch_size = 1000
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null

[nlp.tokenizer]
@tokenizers = "spacy.zh.ChineseTokenizer"
segmenter = "pkuseg"

[components]

[components.spancat]
factory = "spancat"
max_positive = null
spans_key = "grit"
threshold = 0.5

[components.spancat.model]
@architectures = "spacy.SpanCategorizer.v1"

[components.spancat.model.reducer]
@layers = "spacy.mean_max_reducer.v1"
hidden_size = 128

[components.spancat.model.scorer]
@layers = "spacy.LinearLogistic.v1"
nO = null
nI = null

[components.spancat.model.tok2vec]
@architectures = "spacy.Tok2Vec.v2"

[components.spancat.model.tok2vec.embed]
@architectures = "spacy.MultiHashEmbed.v2"
width = 96
rows = [5000,2000,1000,1000]
attrs = ["ORTH","POS","DEP","SHAPE"]
include_static_vectors = false

[components.spancat.model.tok2vec.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 96
window_size = 1
maxout_pieces = 3
depth = 4

[components.spancat.suggester]
@misc = "spacy.ngram_suggester.v1"
sizes = [1, 2, 3]

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 2000
gold_preproc = false
limit = 0
augmenter = null

[training]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 8000
max_epochs = 0
max_steps = 200000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_sequence.v1"
size = 32
get_length = null

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.0
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]
spans_grit_f = 1.0
spans_grit_p = 0.0
spans_grit_r = 0.0
spans_sc_f = null
spans_sc_p = null
spans_sc_r = null

[pretraining]

[initialize]
vectors = null
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
pkuseg_model = "mixed"
pkuseg_user_dict = "default"
```

**Comment by polm** [comment]
What is the output of `spacy info`? What version of `thinc` do you have? There was a recent bug in Thinc that might be related to this.

**Comment by brightgems** [comment]
Here is env info:
```
spaCy version    3.1.2
Location         /anaconda3/lib/python3.7/site-packages/spacy
Platform         Linux-5.4.0-1056-aws-x86_64-with-debian-buster-sid
Python version   3.7.5
Pipelines        zh_core_web_trf (3.0.0)

Thinc: 8.0.10
```

**Comment by polm** [comment]
OK, your thinc is up to date so that's probably OK. 

Does this only happen when you're trying to evaluate data? Since it's happening in the `predict` method I'm surprised it wouldn't come up during training. 

Can you share how you're creating training data (the code)? I don't think it should be a problem, but your data looks pretty different from the sample data in the spancat project. I'm not clear how you're handling the attribute - are you creating a span with class "positive" or something?
