### ISSUE TITLE
Gradient during training is NoneType when training on GPU with textcat listed before ner in pipeline 

### ISSUE THREAD

**Issue by Lolologist** [explosion/spaCy#9221]
## How to reproduce the behaviour
Using the quickstart base_config from https://spacy.io/usage/training, selecting gpu, english, and then textcat and ner, using init-config to make it into a real config file, then trying to train (or run a whole project) results in the following:
`============================= Training pipeline =============================
ℹ Pipeline: ['transformer', 'textcat', 'ner']
ℹ Initial learn rate: 0.0
E    #       LOSS TRANS...  LOSS TEXTCAT  LOSS NER  CATS_SCORE  ENTS_F  ENTS_P  ENTS_R  SCORE 
---  ------  -------------  ------------  --------  ----------  ------  ------  ------  ------
⚠ Aborting and saving the final best model. Encountered exception:
TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/spacy/cli/train.py", line 63, in train_cli
    train(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/spacy/training/loop.py", line 122, in train
    raise e
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/spacy/training/loop.py", line 105, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/spacy/training/loop.py", line 203, in train_while_improving
    nlp.update(
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/spacy/language.py", line 1123, in update
    proc.update(examples, sgd=None, losses=losses, **component_cfg[name])
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/spacy/pipeline/textcat.py", line 205, in update
    bp_scores(d_scores)
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/thinc/layers/chain.py", line 60, in backprop
    dX = callback(dY)
  File "/home/dbishop@interos.ai/anaconda3/envs/tariff/lib/python3.8/site-packages/thinc/layers/concatenate.py", line 69, in backprop
    dX += gradient
TypeError: 'NoneType' object is not iterable`

In my config file, I have:
pipeline = ["transformer","textcat","ner"]

In order to make this work, I had to transpose ner and textcat.
Note that training on CPU doesn't have this issue. 

 ## Info about spaCy

- **spaCy version:** 3.1.2
- **Platform:** Linux-4.14.231-173.360.amzn2.x86_64-x86_64-with-glibc2.17
- **Python version:** 3.8.11
- **Pipelines:** en_core_web_lg (3.1.0), en_core_web_trf (3.1.0)

**Comment by Lolologist** [comment]
cf. https://github.com/explosion/spaCy/discussions/7651

**Comment by polm** [comment]
Thanks for the report, we'll look at it!

**Comment by polm** [comment]
I believe this was fixed by #8012. If not let us know.
