### ISSUE TITLE
`ZeroDivisionError` when calling `as_doc` method

### ISSUE THREAD

**Issue by Joozty** [explosion/spaCy#9243]
## How to reproduce the behaviour

I would like to extract the second line from the text and create a document from it but I get `ZeroDivisionError`.  This is just a very simple example obviously I could do it the other way around and iterate over lines and create docs from them.  Hovewer that doesn't fit my use case.

```python
import spacy

nlp = spacy.load("en_core_web_md", exclude=['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner'])
nlp.add_pipe("sentencizer")

text = """Earth's surface albedo is regularly estimated via Earth observation satellite sensors such as NASA's MODIS instruments on board the Terra and Aqua satellites, and the CERES instrument on the Suomi NPP and JPSS. As the amount of reflected radiation is only measured for a single direction by satellite, not all directions, a mathematical model is used to translate a sample set of satellite reflectance measurements into estimates of directional-hemispherical reflectance and bi-hemispherical reflectance (e.g.,). These calculations are based on the bidirectional reflectance distribution function (BRDF), which describes how the reflectance of a given surface depends on the view angle of the observer and the solar angle. BDRF can facilitate translations of observations of reflectance into albedo. 
Earth's average surface temperature due to its albedo and the greenhouse effect is currently about 15 °C (59 °F). If Earth were frozen entirely (and hence be more reflective), the average temperature of the planet would drop below −40 °C (−40 °F). If only the continental land masses became covered by glaciers, the mean temperature of the planet would drop to about 0 °C (32 °F). In contrast, if the entire Earth was covered by water – a so-called ocean planet – the average temperature on the planet would rise to almost 27 °C (81 °F). 
For land surfaces, it has been shown that the albedo at a particular solar zenith angle θ can be approximated by the proportionate sum of two terms: """

doc = nlp(text)
doc[801:1338].as_doc()
```

```python
Traceback (most recent call last):
  File "/Users/joozty/Documents/project/test.py", line 105, in <module>
    doc[801:1338].as_doc()
  File "spacy/tokens/span.pyx", line 263, in spacy.tokens.span.Span.as_doc
  File "spacy/tokens/span.pyx", line 476, in spacy.tokens.span.Span.vector.__get__
ZeroDivisionError: division by zero
```

## Info about spaCy
- **spaCy version:** 3.1.2
- **Platform:** macOS-11.6-arm64-arm-64bit
- **Python version:** 3.9.5
- **Pipelines:** en_core_web_md (3.1.0)

**Comment by Joozty** [comment]
Possibly related to https://github.com/explosion/spaCy/issues/9224

**Comment by adrianeboyd** [comment]
I don't think you're getting the span you intend here. `doc[x:y]` uses token offsets, not character offsets, so this is the same bug as #9224 where you're looking at an empty span in effect.

For a character span you'd use `doc.char_span`.
