### ISSUE TITLE
ValueError: cannot reshape array of size 16352 into shape (684831,300)

### ISSUE THREAD

**Issue by usbader** [explosion/spaCy#9295]
## How to reproduce the behaviour

The code was working fine. I am using Spacy pretrained large model.  I tried to rerun my code, but I cam across the following bug:

```
Traceback (most recent call last):
  File "/Users/Bader/Documents/bnsf/den_app/run.py", line 1, in <module>
    from den import app
  File "/Users/Bader/Documents/bnsf/den_app/den/__init__.py", line 1, in <module>
    from .views import app
  File "/Users/Bader/Documents/bnsf/den_app/den/views.py", line 2, in <module>
    from .models import User
  File "/Users/Bader/Documents/bnsf/den_app/den/models.py", line 40, in <module>
    nlp = spacy.load('en_core_web_lg')
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy/util.py", line 215, in load_model
    return load_model_from_package(name, **overrides)
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy/util.py", line 236, in load_model_from_package
    return cls.load(**overrides)
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/en_core_web_lg/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy/util.py", line 279, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy/util.py", line 262, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy/language.py", line 940, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy/util.py", line 733, in from_disk
    reader(path / key)
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy/language.py", line 924, in <lambda>
    p
  File "vocab.pyx", line 470, in spacy.vocab.Vocab.from_disk
    
  File "vectors.pyx", line 448, in spacy.vectors.Vectors.from_disk
    
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy/util.py", line 733, in from_disk
    reader(path / key)
  File "vectors.pyx", line 441, in spacy.vectors.Vectors.from_disk.load_vectors
    
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/numpy/lib/format.py", line 771, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 16352 into shape (684831,300)
```

## Your Environment

* Operating System: MacOs High Sierra 10.13.6
* Python Version Used: Python 3.7.0
* spaCy Version Used: spaCy version    2.2.2
* Environment Information: Flask 1.1.2, Werkzeug 1.0.1

**Comment by polm** [comment]
Uh, it sounds like you were using spaCy and then for some reason it just stopped working? That shouldn't happen. Maybe you downloaded a different model version without realizing it? Did you update anything in your Python environment?

Can you share the output of `spacy info`?

**Comment by usbader** [comment]
I am sure that I did not download a different model version. 

The following is the result of running spacy info:

============================== Info about spaCy ==============================

spaCy version    2.2.2                         
Location         /Users/Bader/miniconda3/envs/venv1/lib/python3.7/site-packages/spacy
Platform         Darwin-17.7.0-x86_64-i386-64bit
Python version   3.7.0                         
Models

**Comment by usbader** [comment]
I also did not update anything in my python environment.

**Comment by polm** [comment]
Well, sorry you're having trouble, but if nothing changed I'm not sure what to tell you. Loading models doesn't change their state and it's not like spaCy has a self-destruct switch. 

Here are some things you can try:

- uninstall the model and re-install it
- uninstall and reinstall spaCy
- upgrade to spaCy v2.3
