### ISSUE TITLE
Spacy train - ValueError: Cannot deserialize model: mismatched structure

### ISSUE THREAD

**Issue by gustavengstrom** [explosion/spaCy#9330]
Attempting to train a text classifier yields the error below when including init_tok2vec weights:

Steps and config from the docs were followed. Same config file was used when pretraining and training.

```
=========================== Initializing pipeline ===========================
[2021-09-30 07:58:19,797] [INFO] Set up nlp object from config
[2021-09-30 07:58:19,807] [INFO] Pipeline: ['tok2vec', 'textcat']
[2021-09-30 07:58:19,810] [INFO] Created vocabulary
[2021-09-30 07:58:19,811] [INFO] Finished initializing nlp object
Traceback (most recent call last):
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/spacy/cli/train.py", line 60, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/spacy/training/initialize.py", line 84, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/spacy/language.py", line 1276, in initialize
    init_tok2vec(self, P, I)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/spacy/training/initialize.py", line 189, in init_tok2vec
    layer.from_bytes(weights_data)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/thinc/model.py", line 529, in from_bytes
    return self.from_dict(msg)
  File "/home/gustav/anaconda3/envs/cli-pol/lib/python3.9/site-packages/thinc/model.py", line 546, in from_dict
    raise ValueError("Cannot deserialize model: mismatched structure")
ValueError: Cannot deserialize model: mismatched structure
```

Config file: 

```
[paths]
train = null
dev = null
vectors = null
init_tok2vec = "./pretraining/model5.bin"
raw_text = null

[system]
gpu_allocator = "pytorch"
seed = 0

[nlp]
lang = "sv"
pipeline = ["tok2vec","textcat"]
batch_size = 1000
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.textcat]
factory = "textcat"
threshold = 0.5

[components.textcat.model]
@architectures = "spacy.TextCatEnsemble.v2"
nO = null

[components.textcat.model.linear_model]
@architectures = "spacy.TextCatBOW.v2"
exclusive_classes = true
ngram_size = 1
no_output_layer = false
nO = null

[components.textcat.model.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}
upstream = "*"

[components.tok2vec]
factory = "tok2vec"

[components.tok2vec.model]
@architectures = "spacy.Tok2Vec.v2"

[components.tok2vec.model.embed]
@architectures = "spacy.MultiHashEmbed.v2"
width = ${components.tok2vec.model.encode.width}
attrs = ["ORTH","SHAPE"]
rows = [5000,2500]
include_static_vectors = true

[components.tok2vec.model.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 256
depth = 8
window_size = 1
maxout_pieces = 3

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.pretrain]
@readers = "spacy.JsonlCorpus.v1"
path = ${paths.raw_text}
min_length = 5
max_length = 500
limit = 0

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[training]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
annotating_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]
cats_score = 1.0
cats_score_desc = null
cats_micro_p = null
cats_micro_r = null
cats_micro_f = null
cats_macro_p = null
cats_macro_r = null
cats_macro_f = null
cats_macro_auc = null
cats_f_per_type = null
cats_macro_auc_per_type = null

[pretraining]
max_epochs = 1000
dropout = 0.2
n_save_every = 5
component = "textcat"
layer = "tok2vec"
corpus = "corpora.pretrain"

[pretraining.batcher]
@batchers = "spacy.batch_by_words.v1"
size = 3000
discard_oversize = false
tolerance = 0.2
get_length = null

[pretraining.objective]
@architectures = "spacy.PretrainCharacters.v1"
maxout_pieces = 3
hidden_size = 300
n_characters = 4

[pretraining.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = true
eps = 0.00000001
learn_rate = 0.001

[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```

## Your Environment

- **spaCy version:** 3.1.3
- **Platform:** Linux-5.4.0-86-generic-x86_64-with-glibc2.31
- **Python version:** 3.9.7
- **Pipelines:** sv_pipeline (0.0.0)

**Comment by polm** [comment]
How did you generate this config?

Looking at this section...

```
[pretraining]
max_epochs = 1000
dropout = 0.2
n_save_every = 5
component = "textcat"
layer = "tok2vec"
corpus = "corpora.pretrain"
```

When I generate a pretraining config, the `component` value is `tok2vec` and the `layer` value is empty, which are the default values. You can't pretrain a `textcat` because it doesn't have the right signature, though I'm not sure exactly what kind of error you'd get if you tried. 

I think that might be your issue.

**Comment by svlandeg** [comment]
> When I generate a pretraining config, the `component` value is `tok2vec` and the `layer` value is empty, which are the default values. You can't pretrain a `textcat` because it doesn't have the right signature, though I'm not sure exactly what kind of error you'd get if you tried. 

Technically you should be able to pretrain the `tok2vec` layer of the `textcat` component, but I think this will only work if you have an "in-house" or inline `tok2vec` as part of your `textcat` model. In that case, your pipeline would just be `["textcat"]`, and `textcat.model.tok2vec` would be for instance the `spacy.Tok2Vec.v2` architecture.

In this case however, it's clear from the config that the `textcat` is using a `spacy.Tok2VecListener.v1` and so yes the settings of the pretraining should indeed be
```
component = "tok2vec"
layer = ""
```

**Comment by gustavengstrom** [comment]
Thanks! I tried this and it works. I think I was confused as I didn´t quite understand the difference highlighted in the in the docs between when to: 
1. Use the whole model of the "tok2vec" component
2. Pretrain the "tok2vec" node of the "textcat" component
Examples of use cases would be great when you find the time....

**Comment by polm** [comment]
Basically you would want to pretrain whichever tok2vec you have, and you typically would have only one or the other of those options.
