### ISSUE TITLE
Spacy throws error on validate and loading.

### ISSUE THREAD

**Issue by andyhegedus** [explosion/spaCy#9370]
Getting error on validate prefer_gpu

**(base) andreashegedus@Andys-iMac ~ % python -m spacy validate**
Traceback (most recent call last):
  File "/Users/andreashegedus/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/andreashegedus/anaconda3/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/andreashegedus/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/andreashegedus/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 11, in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
ImportError: cannot import name 'prefer_gpu' from 'thinc.api' (/Users/andreashegedus/anaconda3/lib/python3.7/site-packages/thinc/api.py)

## Your Environment

* Mac OS 11.6
* Python 3.7
* 3.1.3

Andy

**Comment by ljvmiranda921** [comment]
Hi @andyhegedus , this may be related to #9319. Can you try re-downloading your model? 
The models should also be updated to v3

**Comment by andyhegedus** [comment]
It seems to work.  Actions taken
Uninstall thinc
ReInstall thinc
Uninstall Spacy
Reinstall spacy

Previously working code called import Spacy gave error suggested pip install transformers
pip install transformers

It now seems to work.

Andy
