### ISSUE TITLE
'module' object has no attribute 'load'

### ISSUE THREAD

**Issue by Xeoncross** [explosion/spaCy#953]
I upgraded to spacy 1.7 and tried to run the example code to make sure everything worked.

### Code

```
import spacy
nlp = spacy.load('en')
doc = nlp(u'This is a sentence which contains a lot of text.')
```

### Error

```
$ python spacy.py
Traceback (most recent call last):
  File "spacy.py", line 1, in <module>
    import spacy
  File "/Users/user/python/sentence_matching/spacy.py", line 3, in <module>
    nlp = spacy.load('en')
AttributeError: 'module' object has no attribute 'load'
```

## Your Environment

OS X 10.11.1

```
$ python -m spacy info --markdown
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/user/python/sentence_matching/spacy.py", line 1, in <module>
    import spacy
  File "spacy.py", line 3, in <module>
    nlp = spacy.load('en')
AttributeError: 'module' object has no attribute 'load'
```

**Comment by Xeoncross** [comment]
I just realized the filename matches the module name and python is trying to load it. Don't name your file "spacy.py".

**Comment by ines** [comment]
Thanks for updating with the solution! I remember this issue coming up before, and it's definitely an easy (but frustrating) mistake to make. Will add this to the [troubleshooting guide](http://spacy.io/docs/usage/troubleshooting) – I'm sure it'll be helpful to others as well.

**Comment by kiranvarghesev** [comment]
import spacy 
nlp = spacy.load("en")
This Code gives error

  File "/home/kiran/python-envgym/gym/lib/python3.5/site-packages/spacy/__init__.py", line 19, in load
    for _lang in _languages:

AttributeError: module 'spacy.util' has no attribute 'load_model'

**Comment by eranhirs** [comment]
@kiranvarghesev I am having the same problem, which version of spacy are you using? I am using spacy `1.10.0`
