### ISSUE TITLE
error in downloading en , I have installed spacy using pip

### ISSUE THREAD

**Issue by gmvidooly** [explosion/spaCy#958]
```bash
gulshan@gulshan-Inspiron-3543:/usr/local/lib/python2.7/dist-packages$  python -m spacy download en

    Downloading en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz


Usage:   
  /usr/bin/python -m pip install [options] <requirement specifier> ...
  /usr/bin/python -m pip install [options] -r <requirements file> ...
  /usr/bin/python -m pip install [options] [-e] <vcs project url> ...
  /usr/bin/python -m pip install [options] [-e] <local project path> ...
  /usr/bin/python -m pip install [options] <archive url/path> ...

no such option: --no-cache-dir
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/spacy/__main__.py", line 109, in <module>
    plac.Interpreter.call(CLI)
  File "plac_ext.py", line 1142, in call
    print(out)
  File "plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spacy/__main__.py", line 31, in download
    cli_download(model, direct)
  File "spacy/cli/download.py", line 25, in download
    link_package(model_name, model, force=True)
  File "spacy/cli/link.py", line 21, in link_package
    pkg = importlib.import_module(package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named en_core_web_sm
gulshan@gulshan-Inspiron-3543:/usr/local/lib/python2.7/dist-packages$
```

**Comment by ines** [comment]
Which version of pip are you running?

The `download` command uses pip to install the models, and sets the `--no-cache-dir` flag to avoid pip requiring too much memory. This setting seems to not be available in your version, so could you try updating pip to the latest version and re-run the download?

**Comment by gmvidooly** [comment]
Thanks it worked.

**Comment by ines** [comment]
Thanks for reporting back – I'll add this problem and solution to the [troubleshooting guide](https://spacy.io/docs/usage/troubleshooting), in case others come across this problem as well.

**Comment by milsanore** [comment]
Hi, I have this issue when running `python3 -m spacy download en` on Ubuntu 14.04 LTS. Thx
