### ISSUE TITLE
Pickling with dill and recurse=True fails

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spaCy#9584]
While trying to use spaCy in preparing a dataset, I found that `dill` is not able to dump a `Language` when using `recurse=True`. In my case it is not possible to set `recurse=None/False` because this handled externally. (Related https://github.com/huggingface/datasets/issues/3178) So this issue serves to ask why this is the case and whether this behavior can be improved. I must admit that I do not quite understand the deep implication of `recurse`, but the [docs](https://dill.readthedocs.io/en/latest/dill.html#dill._dill.dumps) write

> If recurse=True, then objects referred to in the global dictionary are recursively traced and pickled, instead of the default behavior of attempting to store the entire global dictionary. This is needed for functions defined via exec().

## How to reproduce the behaviour

```python
import dill
import spacy

if __name__ == '__main__':
    nlp = spacy.load("en_core_web_sm", disable=["tagger", "parser", "ner", "lemmatizer"])
    # fails
    with open("temp.pkl", "wb") as f:
        dill.Pickler(f, recurse=True).dump(nlp)
```

## Your Environment

- **spaCy version:** 3.1.0
- **Platform:** Windows-10-10.0.19041-SP0
- **Python version:** 3.6.8
- **Pipelines:** en_core_web_sm (3.1.0)

**Comment by polm** [comment]
Stack trace doesn't look very helpful, but here it is.

<details>

```
Traceback (most recent call last):
  File "/mnt/pool/work/spacy/fiddle/dillpickle.py", line 8, in <module>
    dill.Pickler(f, recurse=True).dump(nlp)
  File "/mnt/pool/work/spacy/env/lib/python3.9/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.9/pickle.py", line 487, in dump
    self.save(obj)
  File "/usr/lib/python3.9/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.9/pickle.py", line 717, in save_reduce
    save(state)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/mnt/pool/work/spacy/env/lib/python3.9/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.9/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.9/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.9/pickle.py", line 931, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.9/pickle.py", line 955, in _batch_appends
    save(x)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.9/pickle.py", line 886, in save_tuple
    save(element)
  File "/usr/lib/python3.9/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.9/pickle.py", line 717, in save_reduce
    save(state)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.9/pickle.py", line 886, in save_tuple
    save(element)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/mnt/pool/work/spacy/env/lib/python3.9/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.9/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.9/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/mnt/pool/work/spacy/env/lib/python3.9/site-packages/dill/_dill.py", line 1176, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/usr/lib/python3.9/pickle.py", line 692, in save_reduce
    save(args)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.9/pickle.py", line 886, in save_tuple
    save(element)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/mnt/pool/work/spacy/env/lib/python3.9/site-packages/dill/_dill.py", line 1493, in save_function
    pickler.save_reduce(_create_function, (obj.__code__,
  File "/usr/lib/python3.9/pickle.py", line 692, in save_reduce
    save(args)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.9/pickle.py", line 901, in save_tuple
    save(element)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/mnt/pool/work/spacy/env/lib/python3.9/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.9/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.9/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/usr/lib/python3.9/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.9/pickle.py", line 687, in save_reduce
    save(cls)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/mnt/pool/work/spacy/env/lib/python3.9/site-packages/dill/_dill.py", line 1439, in save_type
    StockPickler.save_global(pickler, obj, name=name)
  File "/usr/lib/python3.9/pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle <class 'spacy.errors.add_codes.<locals>.ErrorsWithCodes'>: it's not found as spacy.errors.add_codes.<locals>.ErrorsWithCodes
```

</details>
