### ISSUE TITLE
Basic Text Categorization fails in 3.2

### ISSUE THREAD

**Issue by vrunhofen** [explosion/spaCy#9727]
A very basic test for Text Categorization fails.

```python
import spacy
nlp = spacy.load("en_core_web_md")
doc = nlp("This is a sentence.")
textcat = nlp.add_pipe("textcat")
processed = textcat(doc)
```

I get the following error:

```
Traceback (most recent call last):                                                                                                                                                                      
  File "<stdin>", line 1, in <module>                                                                                                                                                                   
  File "spacy/pipeline/trainable_pipe.pyx", line 56, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__                                                                                            
  File "/usr/local/lib/python3.9/site-packages/spacy/util.py", line 1618, in raise_error                                                                                                                
    raise e                                                                                                                                                                                             
  File "spacy/pipeline/trainable_pipe.pyx", line 52, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__                                                                                            
  File "/usr/local/lib/python3.9/site-packages/spacy/pipeline/textcat.py", line 191, in predict                                                                                                         
    scores = self.model.predict(docs)                                                                                                                                                                   
  File "/usr/local/lib/python3.9/site-packages/thinc/model.py", line 315, in predict                                                                                                                    
    return self._func(self, X, is_train=False)[0]                                                                                                                                                       
  File "/usr/local/lib/python3.9/site-packages/thinc/layers/chain.py", line 54, in forward                                                                                                              
    Y, inc_layer_grad = layer(X, is_train=is_train)                                                                                                                                                     
  File "/usr/local/lib/python3.9/site-packages/thinc/model.py", line 291, in __call__                                                                                                                   
    return self._func(self, X, is_train=is_train)                                                                                                                                                       
  File "/usr/local/lib/python3.9/site-packages/thinc/layers/concatenate.py", line 44, in forward                                                                                                        
    Ys, callbacks = zip(*[layer(X, is_train=is_train) for layer in model.layers])                                                                                                                       
  File "/usr/local/lib/python3.9/site-packages/thinc/layers/concatenate.py", line 44, in <listcomp>                                                                                                     
    Ys, callbacks = zip(*[layer(X, is_train=is_train) for layer in model.layers])                                                                                                                       
  File "/usr/local/lib/python3.9/site-packages/thinc/model.py", line 291, in __call__                                                                                                                   
    return self._func(self, X, is_train=is_train)                                                                                                                                                       
  File "/usr/local/lib/python3.9/site-packages/thinc/layers/chain.py", line 54, in forward                                                                                                              
    Y, inc_layer_grad = layer(X, is_train=is_train)                                                                                                                                                     
  File "/usr/local/lib/python3.9/site-packages/thinc/model.py", line 291, in __call__                                                                                                                   
    return self._func(self, X, is_train=is_train)                                                                                                                                                       
  File "/usr/local/lib/python3.9/site-packages/thinc/layers/with_cpu.py", line 24, in forward                                                                                                           
    cpu_outputs, backprop = model.layers[0].begin_update(_to_cpu(X))                                                                                                                                    
  File "/usr/local/lib/python3.9/site-packages/thinc/model.py", line 309, in begin_update                                                                                                               
    return self._func(self, X, is_train=True)                                                                                                                                                           
  File "/usr/local/lib/python3.9/site-packages/thinc/layers/chain.py", line 54, in forward                                                                                                              
    Y, inc_layer_grad = layer(X, is_train=is_train)                                                                                                                                                     
  File "/usr/local/lib/python3.9/site-packages/thinc/model.py", line 291, in __call__                                                                                                                   
    return self._func(self, X, is_train=is_train)                                                                                                                                                       
  File "/usr/local/lib/python3.9/site-packages/thinc/layers/resizable.py", line 27, in forward                                                                                                          
    Y, callback = layer(X, is_train=is_train)                                                                                                                                                           
  File "/usr/local/lib/python3.9/site-packages/thinc/model.py", line 291, in __call__                                                                                                                   
    return self._func(self, X, is_train=is_train)                                                                                                                                                       
  File "thinc/layers/sparselinear.pyx", line 44, in thinc.layers.sparselinear.forward                                                                                                                   
  File "thinc/layers/sparselinear.pyx", line 69, in thinc.layers.sparselinear._begin_cpu_update                                                                                                         
  File "/usr/local/lib/python3.9/site-packages/thinc/model.py", line 175, in get_dim                                                                                                                    
    raise ValueError(err)                                                                                                                                                                               
ValueError: Cannot get dimension 'nO' for model 'sparse_linear': value unset
```

I tried using en_core_web_sm, and another piece of code dervied from the API docs as follows. I still get the same error.

```python
nlp = spacy.load("en_core_web_sm")
from spacy.pipeline.textcat import DEFAULT_SINGLE_TEXTCAT_MODEL
config = {
   "threshold": 0.5,
   "model": DEFAULT_SINGLE_TEXTCAT_MODEL,
}
nlp.add_pipe("textcat", config=config)
nlp("spacy.io usage spacy-101")
```

## Info about spaCy

- **spaCy version:** 3.2.0
- **Platform:** macOS-10.15.7-x86_64-i386-64bit
- **Python version:** 3.9.5
- **Pipelines:** en_core_web_md (3.2.0), en_core_web_sm (3.2.0)

**Comment by adrianeboyd** [comment]
The `textcat` component that you've just added this way hasn't been initialized (it doesn't even know which labels it's supposed to predict) and it hasn't been trained. I'd suggest having a look at the training docs (https://spacy.io/usage/spacy-101#training, https://spacy.io/usage/training) and trying out a textcat demo project (`spacy project clone pipelines/textcat_demo`, https://spacy.io/usage/projects)

**Comment by adrianeboyd** [comment]
Let me convert this to a discussion...
