### ISSUE TITLE
PanicException in SudachiPy

### ISSUE THREAD

**Issue by mhmrx** [explosion/spaCy#9751]
## How to reproduce the behaviour
```
import spacy
nlp = spacy.load("ja_ginza")
nlp("三井住友ファイナンス＆リースがご提供する「総合資産管理サービスA.S.P")
```
## The error that occured:

```
thread '<unnamed>' panicked at 'byte index 31 is not a char boundary; it is inside '＆' (bytes 30..33) of `三井住友ファイナンス＆リースがご提供する「総合資産管理サービスA.S.P`', /github/workspace/sudachi/src/analysis/morpheme.rs:122:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-98989bb93dac>", line 1, in <module>
    nlp("三井住友ファイナンス＆リースがご提供する「総合資産管理サービスA.S.P")
  File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 437, in __call__
    doc = self.make_doc(text)
  File "/usr/local/lib/python3.7/site-packages/spacy/lang/ja/__init__.py", line 282, in make_doc
    return self.tokenizer(text)
  File "/usr/local/lib/python3.7/site-packages/spacy/lang/ja/__init__.py", line 144, in __call__
    dtokens = self._get_dtokens(sudachipy_tokens)
  File "/usr/local/lib/python3.7/site-packages/spacy/lang/ja/__init__.py", line 174, in _get_dtokens
    sub_tokens_list = self._get_sub_tokens(sudachipy_tokens) if need_sub_tokens else None
  File "/usr/local/lib/python3.7/site-packages/spacy/lang/ja/__init__.py", line 209, in _get_sub_tokens
    dtokens = self._get_dtokens(sub_a, False)
  File "/usr/local/lib/python3.7/site-packages/spacy/lang/ja/__init__.py", line 183, in _get_dtokens
    ) for idx, token in enumerate(sudachipy_tokens) if len(token.surface()) > 0
  File "/usr/local/lib/python3.7/site-packages/spacy/lang/ja/__init__.py", line 183, in <listcomp>
    ) for idx, token in enumerate(sudachipy_tokens) if len(token.surface()) > 0
pyo3_runtime.PanicException: byte index 31 is not a char boundary; it is inside '＆' (bytes 30..33) of `三井住友ファイナンス＆リースがご提供する「総合資産管理サービスA.S.P`
```

## Your Environment

* Operating System: Linux (docker containter https://hub.docker.com/layers/python/library/python/3.7.10-slim-buster/images/sha256-dbaa3e2f80a0164214940d5cafb1fedf249bfd963a9379812407a08dc95a5ad8?context=explore) 
* Python Version Used: python:3.7.10
* spaCy Version Used: '2.3.5'
* Environment Information:  ginza==4.0.5, ja-ginza==4.0.0

**Comment by adrianeboyd** [comment]
Hi, this looks like it might be a bug in new rust implementation of sudachipy. This model might work fine with the latest python/cython version instead, which is v0.5.4 (`pip install sudachipy==0.5.4`).

And it might be helpful to report it in their issue tracker. It looks like this may be the same bug: https://github.com/WorksApplications/sudachi.rs/issues/182
