### ISSUE TITLE
V 3.2 TypeError: Plain typing.NoReturn is not valid as type argument

### ISSUE THREAD

**Issue by dabasmoti** [explosion/spaCy#9792]
Hi
After upgrading to spacy 3.2(pip)
Can't import spacy

```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/motid/p37/lib/python3.7/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/Users/motid/p37/lib/python3.7/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/Users/motid/p37/lib/python3.7/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy/strings.pyx", line 15, in init spacy.strings
  File "/Users/motid/p37/lib/python3.7/site-packages/spacy/util.py", line 1595, in <module>
    default_error_handler: Callable[[str, "Pipe", List["Doc"], Exception], NoReturn],
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 755, in __getitem__
    return self.__getitem_inner__(params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 251, in inner
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 774, in __getitem_inner__
    result = _type_check(result, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 135, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument

```
Edit:
V-3.1.3 works
So, The issue start from v-3.1.4

## Environment
* Operating System: 20.6.0-x86_64-i386-64bit
* Python Version Used: 3.7
* spaCy Version Used: 3.2

**Comment by adrianeboyd** [comment]
Hi, this was a bug in python and I think you'll need to upgrade to a newer version of python. See: #9600.
