### ISSUE TITLE
Spacy import error! >> thinc.linear.avgtron.AveragedPerceptron

### ISSUE THREAD

**Issue by spate141** [explosion/spaCy#986]
After installing spacy, when I import spacy I get following error! 
`ValueError: thinc.linear.avgtron.AveragedPerceptron has the wrong size, try recompiling`

## Environment

* Operating System: Ubuntu
* Python Version Used: 2.7
* spaCy Version Used: 1.8.0

**Comment by honnibal** [comment]
When I have this sort of problem, it's usually from a `pip` cache. This usually fixes it:

```
pip uninstall thinc
pip install --no-cache-dir thinc
```

**Comment by spate141** [comment]
So, after following above steps you mentioned... now I am getting this error:

```
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 8, in <module>
    from . import en, de, zh, es, it, hu, fr, pt, nl, sv, fi, bn, he
  File "/usr/local/lib/python2.7/dist-packages/spacy/en/__init__.py", line 4, in <module>
    from ..language import Language
  File "/usr/local/lib/python2.7/dist-packages/spacy/language.py", line 9, in <module>
    from .tagger import Tagger
  File "spacy/tagger.pyx", line 1, in init spacy.tagger (spacy/tagger.cpp:18883)
ImportError: No module named thinc.linear.avgtron
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 4, in <module>
    from . import util
ImportError: cannot import name util
>>> 
```

**Comment by spate141** [comment]
Issue solved with following commands, thanks @honnibal : 
```
pip uninstall spacy
pip install --no-cache-dir spacy
```
