### ISSUE TITLE
"python -m spacy download en"  throws  OverflowError: regular expression code size limit exceeded

### ISSUE THREAD

**Issue by ravi-manik** [explosion/spaCy#990]
After installing spacy, when I try to download en language model. I'm getting the below error: **OverflowError: regular expression code size limit exceeded**
Below is the stack trace:

```
root@linux:[~]:python -m spacy download en
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/local/python/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/local/python/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/local/python/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/local/python/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/local/python/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/local/custom_python/lib/python2.7/site-packages/spacy/__init__.py", line 16, in <module>
    from . import fr
  File "/usr/local/custom_python/lib/python2.7/site-packages/spacy/fr/__init__.py", line 7, in <module>
    from .language_data import *
  File "/usr/local/custom_python/lib/python2.7/site-packages/spacy/fr/language_data.py", line 5, in <module>
    from .tokenizer_exceptions import get_tokenizer_exceptions, TOKEN_MATCH
  File "/usr/local/custom_python/lib/python2.7/site-packages/spacy/fr/tokenizer_exceptions.py", line 213, in <module>
    TOKEN_MATCH = re.compile('|'.join('(?:{})'.format(m) for m in REGULAR_EXP), re.IGNORECASE).match
  File "/usr/local/custom_python/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/local/custom_python/lib/python2.7/re.py", line 240, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/custom_python/lib/python2.7/sre_compile.py", line 523, in compile
    groupindex, indexgroup
OverflowError: regular expression code size limit exceeded
```
Not sure, whether it's a version mismatch issue, tried it with 1.7 and 1.7.3.

## Your Environment

* Operating System:  CentOS Linux release 7.2.1511 (Core) 
* Python Version Used: Python 2.7.3
* spaCy Version Used: 1.7.3
* Environment Information:

**Comment by lukeorland** [comment]
This happens on my Python 2.7 system with just `import spacy`.

**Comment by sauravy** [comment]
facing the same issue in our environment as well.

**Comment by honnibal** [comment]
Are you still seeing this on 1.8? It should be fixed by using the `regex` module, instead of `re`

**Comment by lukeorland** [comment]
`import spacy` worked under my Python 2.7 environment with `spacy==1.8.2` 👍
