### ISSUE TITLE
"write() argument 1 must be unicode, not str" with spacy convert on Python2

### ISSUE THREAD

**Issue by Tpt** [explosion/spaCy#991]
When trying to convert UD French conllu file with Spacy 1.8 using Python 2.7 I get the following error:

```
% python -m spacy convert UD_French/fr-ud-dev.conllu UD_French/fr-ud-morph-dev --morphology
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "lib/python2.7/site-packages/spacy/__main__.py", line 133, in <module>
    plac.Interpreter.call(CLI)
  File "lib/python2.7/site-packages/plac_ext.py", line 1142, in call
    print(out)
  File "lib/python2.7/site-packages/plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "lib/python2.7/site-packages/plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "lib/python2.7/site-packages/plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "lib/python2.7/site-packages/plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "lib/python2.7/site-packages/plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "lib/python2.7/site-packages/plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "lib/python2.7/site-packages/plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "lib/python2.7/site-packages/spacy/__main__.py", line 121, in convert
    cli_convert(input_file, output_dir, n_sents, morphology)
  File "lib/python2.7/site-packages/spacy/cli/convert.py", line 25, in convert
    CONVERTERS[file_ext](input_path, output_path, *args)
  File "lib/python2.7/site-packages/spacy/cli/converters/conllu2json.py", line 32, in conllu2json
    json.dump(docs, output_file.open('w', encoding='utf-8'), indent=2)
  File "/usr/lib/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
TypeError: write() argument 1 must be unicode, not str

```

## Your Environment
* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 1.8.0
* **Installed models:**

**Comment by ines** [comment]
Thanks for the report – I think the converter is still mising use the new `json_dumps` replacement from `spacy.compat` for Python 2/3 compatibility.

Fixing!
