### ISSUE TITLE
Torch import issue on Windows: [WinError 127] The specified procedure could not be found.

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spaCy#9948]
## How to reproduce the behaviour
Install the following on Windows (I tested this on a completely new environment):
* Python 3.7.9
* `pip install torch==1.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`
* `pip install -U spacy[cuda113]`

Then, try to load spaCy in your interpreter:

```shell
python -c "import spacy"
```

This fails with the following traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\bramv\.virtualenvs\test-rg3hBYkR\lib\site-packages\spacy\__init__.py", line 11, in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
  File "C:\Users\bramv\.virtualenvs\test-rg3hBYkR\lib\site-packages\thinc\api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "C:\Users\bramv\.virtualenvs\test-rg3hBYkR\lib\site-packages\thinc\initializers.py", line 4, in <module>
    from .backends import Ops
  File "C:\Users\bramv\.virtualenvs\test-rg3hBYkR\lib\site-packages\thinc\backends\__init__.py", line 7, in <module>
    from .ops import Ops
  File "C:\Users\bramv\.virtualenvs\test-rg3hBYkR\lib\site-packages\thinc\backends\ops.py", line 11, in <module>
    from ..util import get_array_module, is_xp_array, to_numpy
  File "C:\Users\bramv\.virtualenvs\test-rg3hBYkR\lib\site-packages\thinc\util.py", line 27, in <module>
    import torch
  File "C:\Users\bramv\.virtualenvs\test-rg3hBYkR\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\bramv\.virtualenvs\test-rg3hBYkR\lib\site-packages\torch\lib\cudnn_adv_train64_8.dll" or one of its dependencies.
```

However, and here's the weird part, importing torch works just fine so I think this is a spaCy/thinc issue. What's more: if you first import torch and then spacy, it also works just fine!

```shell
python -c "import torch; import spacy"  # succeeds
python -c "import spacy; import torch"  # fails
```

## Your Environment
`python -m spacy info --markdown` is not working due to the import issue, so I wrote down the relevant libraries.

* Operating System: Windows 10 64 bit
* Python Version Used: 3.7.9
* Libraries Used:

cupy-cuda113==9.6.0
spacy==3.2.1
thinc==8.0.13
torch==1.10.1+cu113

**Comment by BramVanroy** [comment]
So this was a CUDA issue. I had 11.5 installed which cupy then tries to use (?), which in turn conflicted with 11.3 that came shipped with the torch insallation. I really dislike this naming convention of CUDA: I would expect all 11.x versions to be backwards-compatible. I guess it's my own fault for not using docker but still. /rant
